### ISSUE TITLE
Coin flagged erroneously as zero balance on radar_relay

### ISSUE THREAD

**Issue by Steve1943** [CoinAlpha/hummingbot#101]
During trading (arbitrage) on radar_relay,  Hummingbot 4.0 says zero DNT coin balance but Radar_Relay exchange console shows 900 DNT enabled for trading.

See hummingbot terminal log at   https://photos.app.goo.gl/cmrvVpWpEBNqDpr3A  

https://photos.app.goo.gl/cmrvVpWpEBNqDpr3A

plus Radar_relay screenshot :
https://user-images.githubusercontent.com/2613649/56614841-3ff95b00-661a-11e9-94dc-df7c51ef9600.jpg

The fault seems confined to radar_relay - I have not replicated the fault in either DDEX or Binance.

This error manifested in Windows bash (Ubuntoo 18.04) with HB compiled from HBv4.0 source.  
I have replicated the fault identically in VirtualBox emulating Ubuntoo 18.04 with HBv4.0, likewise compiled from source.

I have replicated the fault also with another coin (BAT) in both software environments.
NB other coins work fine e.g. BNB and ETH/WETH.

All tests employed the same Metamask wallet  <0xf452895f879CB78A60af303BCF7B34E56A934Da8>
which confirms the 900 DNT balance available.

So the fault seems to be exchange and coin specific and independent of the host platform.

Steve Henderson
4mostip@gmail.com

**Attachments**
// Attach any relevant configuration files, logs, tx hashes, etc. here.
![Firefox_Screenshot_2019-04-23T19-43-08 318Z](https://user-images.githubusercontent.com/2613649/56614841-3ff95b00-661a-11e9-94dc-df7c51ef9600.jpg)
// NOTE: We understand If you do not want to publish your config/log files. You can instead send them privately to dev@coinalpha.com and drop a link of this issue in the email.

**Comment by yzhang1994** [comment]
@Steve1943 Thanks for reporting the bug. The newly merged PR might have fixed it. Please try clone the repo again and see if it is still an issue.

**Comment by Steve1943** [comment]
Thanks - I have recloned and reinstalled - and SUCCESS - the problem has dissappeared.

**Comment by mifeng** [comment]
This qualified for bug bounty program as well, @Steve1943
