### ISSUE TITLE
[BUG] Bamboo Relay order books not initializing in discovery

### ISSUE THREAD

**Issue by PtrckM** [CoinAlpha/hummingbot#1024]
**Describe the bug**
Discovery fails to show the profitability between bamboo_relay and radar_relay

VM1: waited 30 minutes for profitability result
VM2: waited 40 minutes for profitability result
VM3: waited 50 minutes for profitability result

**Screenshots**

![image](https://user-images.githubusercontent.com/54516858/68082618-01125080-fe5a-11e9-9fd2-9b1c24cc239b.png)

**Release version**
```
                "branch": "dev-0.18.0",
                "commit": "999dbd725f8f8adb2a6bb0a13748f8c57e92c365",
                "date": "2019-10-31T09:02:42Z"
```

**Config**
[config.txt](https://github.com/CoinAlpha/hummingbot/files/3801371/config.txt)

**Logs**
[logs.log](https://github.com/CoinAlpha/hummingbot/files/3801372/logs.log)

**Comment by BUDDHA-TONY** [comment]
Tested this for an hour and was able to reproduce the error using the same configs

```
                "branch": "development",
                "commit": "999dbd725f8f8adb2a6bb0a13748f8c57e92c365",
                "date": "2019-10-31T09:02:42Z",
                "maintainer": "CoinAlpha, Inc. <dev@coinalpha.com>"
```

![disco1](https://user-images.githubusercontent.com/55869559/68101207-68d2a500-ff07-11e9-9941-d8b8a1b63ffe.png)

**Comment by chowryan** [comment]
we shouldnt be running tests on bamboo relay imo since they aren't an officially supported exchange. looks like there  was an error fetching a token (error 404) maybe because there's an `!` in the trading pair.
![Uploading image.png…]()

**Comment by dennisocana** [comment]
Tagging @Arctek for Bamboo Relay

**Comment by PtrckM** [comment]
unable to start using dev-0.20.0

![image](https://user-images.githubusercontent.com/54516858/69471774-1ede3000-0dde-11ea-8b71-69a2307460da.png)

**Comment by Arctek** [comment]
I'll have a look soon. It's because `symbol` has been changed to `trading_pair` everywhere in hummingbot, so the connector needs to be updated to reflect this.

**Comment by yzhang1994** [comment]
We have finished the refactor in Bamboo (dev branch). @Arctek could you take a look again?

**Comment by PtrckM** [comment]
unable to show the profitability

![image](https://user-images.githubusercontent.com/54516858/70110176-1d87ef80-1689-11ea-82e3-cebfed09a55b.png)

                "branch": "development",
                "commit": "49a5c7071b122e4369bd1b062771cf6998fa8b15",
                "date": "2019-12-03T18:37:34Z",

**Comment by Arctek** [comment]
Got a log file there for that?

**Comment by PtrckM** [comment]
[logs_conf_disc_rr-br.log](https://github.com/CoinAlpha/hummingbot/files/3920143/logs_conf_disc_rr-br.log)

**Comment by PtrckM** [comment]
confirmed fix from https://github.com/CoinAlpha/hummingbot/pull/1183

![image](https://user-images.githubusercontent.com/54516858/70763533-5a419e00-1d8f-11ea-8d8b-0796b8812553.png)

- LOGS
[logs_conf_discovery_strategy_0.log](https://github.com/CoinAlpha/hummingbot/files/3958635/logs_conf_discovery_strategy_0.log)

- CSV
[discovery_strategy_output_2019-12-12-20-50-09.txt](https://github.com/CoinAlpha/hummingbot/files/3958639/discovery_strategy_output_2019-12-12-20-50-09.txt)
