### ISSUE TITLE
[BUG] Missing "Simple_trade" strategy

### ISSUE THREAD

**Issue by rennel-tabing** [CoinAlpha/hummingbot#1043]
**Describe the bug**
// A clear and concise description of what the bug is.
When creating a  new strategy, using the `simple_trade` will give out a not valid strategy error.
![image](https://user-images.githubusercontent.com/53868268/68398483-ce5ea580-0142-11ea-8d4f-f7f08d3d2e32.png)

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:
1. on hummingbot CLI, create a new strategy using the `config` command then press ENTER
2. Press the TAB button and you will notice that this `simple_trade` is no longer on the list of the strategies.

**Screenshots**
// If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/53868268/68398105-395bac80-0142-11ea-9cef-8d300afeff25.png)

**Release version**
// Include your bot's version number (Can be found at the bottom left corner of your CLI).
Tried using docker installation on the following versions:
version-0.16.0
version-0.17.0
version-0.17.1
version-0.18.0
dev-0.19.0

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:** hellwind#3143
**Optional: your ETH address:** 0xa537E2887B9887Cb72bDd381C9E21DA4856bb60d

**Comment by BUDDHA-TONY** [comment]
Tested this on `version-0.18.1` 

![git1043](https://user-images.githubusercontent.com/55869559/68442883-5c9f5e00-020d-11ea-8a90-3afea56b3765.png)

**Comment by spmuppar** [comment]
Yes, had same issue few days ago

**Comment by yzhang1994** [comment]
@rennel-tabing this is not a bug. Since we don't really expect people to use simple trade in live trading (the strategy is there to serve as a code sample & help people understand how to write customized strategies), we hide that option from users. The option will show if you are on a local branch that is not named master.
