### ISSUE TITLE
[New Exchange Connector] HitBTC

### ISSUE THREAD

**Issue by jgarzik** [CoinAlpha/hummingbot#1044]
## Exchange Details ✏️

- **Name of exchange**: Hitbtc
- **Exchange URL**: https://hitbtc.com/
- **Link to API docs**: https://api.hitbtc.com/
- **Type of exchange**: [X] Centralized [ ] Decentralized
- **Requester details**: Are you affiliated with the exchange? [ ] yes [X] no 
  - If yes, what is your role?

## Rationale / impact ✏️
Hitbtc is a Top-40 exchange in terms of CMC adjusted volume.  Selfishly, it has the best liquidity and volume for some of the key DeFi pairs for the Ethereum community, such as DAI & MKR, which are less often seen at US exchanges.

## Additional information ✏️
The API seems similar to Bittrex, and includes familiar REST and Websocket calls, including subscribing to order books & deltas, trades and tickers.

---

⚠️ ***Note: do not modify below here***

## Developer notes

This feature request entails building a new exchange connector to allow Hummingbot to connect to an exchange that is currently not supported.

### Resources
- [Exchange connector developer guide](https://docs.hummingbot.io/developers/connectors/)
- [Discord forum](https://discord.hummingbot.io)

### Deliverables
1. A complete set of exchange connector files as listed [above](#developer-notes-resources).
2. Unit tests (see [existing unit tests](https://github.com/CoinAlpha/hummingbot/tree/master/test/integration)):
  1. Exchange market test ([example](https://github.com/CoinAlpha/hummingbot/blob/master/test/integration/test_binance_market.py))
  2. Order book tracker ([example](https://github.com/CoinAlpha/hummingbot/blob/master/test/integration/test_binance_order_book_tracker.py))
  3. User stream tracker ([example](https://github.com/CoinAlpha/hummingbot/blob/master/test/integration/test_binance_user_stream_tracker.py))
3. Documentation:
  1. Code commenting (particularly for any code that is materially different from the templates/examples)
  2. Any specific instructions for the use of that exchange connector ([example](https://docs.hummingbot.io/connectors/binance/))

### Required skills
- Python
- Previous Cython experience is a plus (optional)

**Comment by rennel-tabing** [comment]
@jgarzik Development of this connector is currently in progress. https://github.com/CoinAlpha/hummingbot/pull/1022

**Comment by jgarzik** [comment]
Closing as duplicate

**Comment by jason-hb** [comment]
Closing issue in order to create a fresh story in ZenHub for the HitBtc connector build currently underway
