### ISSUE TITLE
Cross-Exchange market making BSV-USDT (Bittrex-Huobi)[BUG]

### ISSUE THREAD

**Issue by spmuppar** [CoinAlpha/hummingbot#1049]
**Describe the bug**
Cannot perform cross exchange market making on Bittrex (maker), Huobi (Taker) exchanges for BSV-USDT

**Steps To Reproduce**
Please see the attached config snapshot. 
Basically cross-exchange market making on Bittrex (maker), Huobi (taker), for BSV-USDT. 0.01 profitability

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: ...
2. Start the bot using this command: ...
...

**Screenshots**
![Screen Shot 2019-11-08 at 11 50 56 AM](https://user-images.githubusercontent.com/19416572/68495564-7c8b4d80-021e-11ea-96d7-7e62064b31e5.png)
![Screen Shot 2019-11-08 at 11 31 39 AM](https://user-images.githubusercontent.com/19416572/68495578-81500180-021e-11ea-9171-e267bc7f14d2.png)
![Screen Shot 2019-11-08 at 11 31 25 AM](https://user-images.githubusercontent.com/19416572/68495593-87de7900-021e-11ea-9ae9-9f70632938ee.png)

**Release version**
//dev-0.18.0

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

[cross_exchange_mm_bittrex_huobi_bug_bsv_usdt.zip](https://github.com/CoinAlpha/hummingbot/files/3825502/cross_exchange_mm_bittrex_huobi_bug_bsv_usdt.zip)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username: spmuppar**
**Optional: your ETH address:** (If you want to participate in the bug bounty)

**Comment by chowryan** [comment]
this is fixed in 0.18.1 please upgrade your version
