### ISSUE TITLE
[BUG] Order failed (rejected) on Coinbase - precision issue

### ISSUE THREAD

**Issue by buttcoindeluxe** [CoinAlpha/hummingbot#106]
When attempting arbitrage, one side of the order is failing on Coinbase

Failed on XLMBTC market, whenever HB attempted an order. Configured for arbitrage Binance <-> Coinbase XLM-BTC. Order is not posted to Coinbase, it is rejected by the API - order size is too precise.

![hb](https://user-images.githubusercontent.com/40475858/56627998-2ce48c00-6616-11e9-9c56-ee2c08b8ce83.png)

Version 0.4.0

**Comment by yzhang1994** [comment]
@buttcoindeluxe This is a bug and it should have been fixed by the PR above. Please let us know if you are seeing seeing the same issue.
