### ISSUE TITLE
[Question] Arbitrage, min_profitability minimum value

### ISSUE THREAD

**Issue by starlounge** [CoinAlpha/hummingbot#1061]
Hi to all,
I'm testing Hummingbot for arbitrage.
The minimum value for min_profitability is 0.01 or I can insert 0.001?

Many thanks!

**Comment by Clint-G13** [comment]
Hi! starlounge, yes you can set your preferred value for the min_profitability parameter if you are currently testing the strategy. The value 0.01 is just an example, you can find more details about the arbitrage strategy on this link: https://docs.hummingbot.io/strategies/arbitrage/#configuration-parameters. If you have additional inquiry, you can post them to Hummingbot's discord channel: https://discord.hummingbot.io/
