### ISSUE TITLE
Tokocrypto Connector

### ISSUE THREAD

**Issue by Septian-Bhoechie** [CoinAlpha/hummingbot#1065]
## Exchange Details ✏️

- **Name of exchange**: Tokocrypto
- **Exchange URL**: www.tokocrypto.com
- **Link to API docs**: https://documenter.getpostman.com/view/1457251/RWgm2L5S
- **Type of exchange**: [x] Centralized [ ] Decentralized
- **Requester details**: Are you affiliated with the exchange? [x ] yes [ ] no 
  - If yes, what is your role? Backend Developer

## Rationale / impact ✏️
Some our users in indonesia use hommingbot as their trade tools, so we want facilitate them to use bot to trade with our exchange

## Additional information ✏️
Tokocrypto is the first and the only one exchange that has obtained permission from the Indonesian government to open a crypto market and exchange in Indonesia

---

⚠️ ***Note: do not modify below here***

## Developer notes

This feature request entails building a new exchange connector to allow Hummingbot to connect to an exchange that is currently not supported.

### Resources
- [Exchange connector developer guide](https://docs.hummingbot.io/developers/connectors/)
- [Discord forum](https://discord.hummingbot.io)

### Deliverables
1. A complete set of exchange connector files as listed [above](#developer-notes-resources).
2. Unit tests (see [existing unit tests](https://github.com/CoinAlpha/hummingbot/tree/master/test/integration)):
  1. Exchange market test ([example](https://github.com/CoinAlpha/hummingbot/blob/master/test/integration/test_binance_market.py))
  2. Order book tracker ([example](https://github.com/CoinAlpha/hummingbot/blob/master/test/integration/test_binance_order_book_tracker.py))
  3. User stream tracker ([example](https://github.com/CoinAlpha/hummingbot/blob/master/test/integration/test_binance_user_stream_tracker.py))
3. Documentation:
  1. Code commenting (particularly for any code that is materially different from the templates/examples)
  2. Any specific instructions for the use of that exchange connector ([example](https://docs.hummingbot.io/connectors/binance/))

### Required skills
- Python
- Previous Cython experience is a plus (optional)

**Comment by silencebeat** [comment]
hi. this is a good request.
i'm the fan of tokocrypto. will be grateful if you guys can make it happen

**Comment by PtrckM** [comment]
@Septian-Bhoechie Hummingbot is primarily in Python/Cython - feel free to use the bot or fork the codebase and build a connector, You can read developers manual at this [link](https://docs.hummingbot.io/developers/) and its [tutorials](https://docs.hummingbot.io/developers/tutorial/) or post on [devforum](https://forum.hummingbot.io/) if you have concerns and questions.

**Comment by dennisocana** [comment]
The pull request linked to this story is incomplete and outdated. Closing for now due to no progress for four months. Feel free to reopen when work will be resumed for this connector.

https://www.reddit.com/r/Hummingbot/comments/n0tyte/announcement_review_stoppage_on_tokocrypto_and/
