### ISSUE TITLE
Continuously save trades to CSV file

### ISSUE THREAD

**Issue by sweetpotatoz** [CoinAlpha/hummingbot#1066]
**Feature Suggestion**
// A succinct description of **how you want to achieve the desired behavior**.
// If you have looked at the code and know exactly what code changes are needed then please _consider submitting a pull request_ instead.
1) Scheduled auto Trade Data export
2) Capable of export trade data on a certain date

**Impact**
// A succinct description of **why you want the _desired behavior_** specified above.
The desired behavior will allow me to ...
1) So Users do not need to manually export the trade data constantly.  
*When the container stopped running, all trades data are wiped off if we did not export the trade data manually
2) When we export trade data, all trade data are exported to .csv.  If we manually exported the trade data every day, we are getting a lot of previous trade data in the same file.

**Additional context**
Trade data is valuable data for bot traders
So the above features mentioned is very important for us

**Comment by dennisocana** [comment]
@sweetpotatoz as a workaround, I can show you how to get trade data from the local database.

**Comment by mifeng** [comment]
@dennisocana can you describe the workaround briefly here?

**Comment by dennisocana** [comment]
@mifeng the trades are saved in the database in the `.sqlite` file inside the `/data` folder. I provided instructions how to access this file even if Hummingbot is installed via Docker.

<img width="960" alt="dbeaver_nlyGdfrW2H" src="https://user-images.githubusercontent.com/50150287/81458129-74ab6680-91cb-11ea-8fff-686905ff8142.png">

Then I created PR https://github.com/CoinAlpha/hummingbot/pull/1280 to edit the `create.sh` and `update.sh` scripts so it will always map the folder to `hummingbot_data` when creating an instance and this file can be easily accessed.

**Comment by mifeng** [comment]
@dennisocana I meant describing the tool that you used to access the trades.

What software is it? How should users import the `.sqlite` file into the software?

**Comment by dennisocana** [comment]
@mifeng any database management software like [DBeaver](https://dbeaver.io/) or [DataGrip](https://www.jetbrains.com/datagrip/) or via web at https://inloop.github.io/sqlite-viewer/

![image](https://user-images.githubusercontent.com/50150287/81459334-f9997e80-91d1-11ea-879c-311f345015f4.png)

**Comment by dennisocana** [comment]
Importing the database file varies depending on the software. For DBeaver, create a new database connection by following the steps outlined [here](https://github.com/dbeaver/dbeaver/wiki/Create-Connection) and select **SQLite**.

![image](https://user-images.githubusercontent.com/50150287/81459436-7fb5c500-91d2-11ea-8d70-fa18b471336d.png)

Click *Next** and **Browse ...** to where the `.sqlite` file is saved, then click **FInish**.

![image](https://user-images.githubusercontent.com/50150287/81459455-9d832a00-91d2-11ea-9ec3-ae00e4e3a1b9.png)
