### ISSUE TITLE
[Feature] Pure market making configuration improvement.

### ISSUE THREAD

**Issue by Nullably** [CoinAlpha/hummingbot#1073]
A few things I came across while inputting configuration for pure market making (v 0.18.0):

**Some default values are not working**

- `Enter quantity of orders per side [bid/ask] (single/multiple) default is single` _(also note it should read (Default is single)_

- `What is your target base asset inventory percentage (Enter 0.01 to indicate 1%). (Default is 0.5 (50%)) ?`

**Some yes/no questions require `y/n` input while some require `True/False`**
I find it inconsistent, I personally prefer` y/n`. Also some questions don't show all valid input options, like just `(Default is False)` (implying the user knows True is an option)

- `Would you like to enable inventory skew? (y/n)`
- `Do you want to enable order_filled_stop_cancellation.If enabled, when orders are completely filled, the other side remains uncanceled (Default is False)?` _also note the question mark is at the wrong place_
- `Do you want to enable jump_orders? If enabled, when the top bid price is lesser than your order price, buy order will jump to one tick above top bid price & vice versa for sell order. (Default is False)`

**Comment by dennisocana** [comment]
@Nullably most of these have been addressed yesterday. See https://github.com/CoinAlpha/hummingbot/pull/1070
