### ISSUE TITLE
[BUG] PMM Binance Killed.  binance.exceptions.BinanceAPIException: APIError(code=-1021)

### ISSUE THREAD

**Issue by sweetpotatoz** [CoinAlpha/hummingbot#1075]
**Describe the bug**
// A clear and concise description of what the bug is.
Bot killed, log attached.  Trade data all gone.

binance.exceptions.BinanceAPIException: APIError(code=-1021)

: Timestamp for this request is outside of the recvWindow.
2019-11-16 10:13:53,240 - 11 - hummingbot.market.binance.binance_market - WARNING - Failed to submit sell order to Binance. Check API key and network connection.

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:
Strategy file attached.

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: ...
2. Start the bot using this command: ...
...

**Screenshots**
// If applicable, add screenshots to help explain your problem.

**Release version**
// Include your bot's version number (Can be found at the bottom left corner of your CLI).
0.18.1 

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 
[PMM_Binance_Killed.txt](https://github.com/CoinAlpha/hummingbot/files/3856453/PMM_Binance_Killed.txt)

[PMM_strategy.txt](https://github.com/CoinAlpha/hummingbot/files/3856460/PMM_strategy.txt)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**
**Optional: your ETH address:** (If you want to participate in the bug bounty)

**Comment by dennisocana** [comment]
After initial investigation, this timestamp issue might be caused by de-synced time. Both Binance's server and your machine's clock must be somewhat in sync as they can drift apart for a number of reasons.

Let me know as soon as this happens again so I can give you further instructions.

**Comment by yzhang1994** [comment]
I believe this is not a bug. The Binance clock gets de-synced from time to time but the bot should safely recover. It is only an issue if the same error gets printed over and over.

**Comment by dennisocana** [comment]
Logs indicate that bot continued to run normally and has recovered from the error.
