### ISSUE TITLE
[New Exchange Connector] coinFLEX

### ISSUE THREAD

**Issue by Nazif79** [CoinAlpha/hummingbot#1076]
## Exchange Details ✏️

- **Name of exchange**: coinFLEX
- **Exchange URL**: https://trading.coinflex.com/
- **Link to API docs**: tzIOmpiYyLg9f3qmd+3GxxTmZX4=
- **Type of exchange**: [ ] Centralized Not sure
- **Requester details**: Are you affiliated with the exchange? no 
  - If yes, what is your role?

## Rationale / impact ✏️
(Describe your rationale for building this exchange connector, impact for hummingbot users/community) has program MM to user or company 
And i need bot to trade on this platform.

## Additional information ✏️
(Provide any other useful information that may be helpful to know about this exchange)

MM’s are eligible for mining FLEX Coins on any taker volumes. For more on this go here: https://coinflex.com/assets/whitepaper-en.pdf

---

⚠️ ***Note: do not modify below here***

## Developer notes

This feature request entails building a new exchange connector to allow Hummingbot to connect to an exchange that is currently not supported.

### Resources
- [Exchange connector developer guide](https://docs.hummingbot.io/developers/connectors/)
- [Discord forum](https://discord.hummingbot.io)

### Deliverables
1. A complete set of exchange connector files as listed [above](#developer-notes-resources).
2. Unit tests (see [existing unit tests](https://github.com/CoinAlpha/hummingbot/tree/master/test/integration)):
  1. Exchange market test ([example](https://github.com/CoinAlpha/hummingbot/blob/master/test/integration/test_binance_market.py))
  2. Order book tracker ([example](https://github.com/CoinAlpha/hummingbot/blob/master/test/integration/test_binance_order_book_tracker.py))
  3. User stream tracker ([example](https://github.com/CoinAlpha/hummingbot/blob/master/test/integration/test_binance_user_stream_tracker.py))
3. Documentation:
  1. Code commenting (particularly for any code that is materially different from the templates/examples)
  2. Any specific instructions for the use of that exchange connector ([example](https://docs.hummingbot.io/connectors/binance/))

### Required skills
- Python
- Previous Cython experience is a plus (optional)

**Comment by GildedHonour** [comment]
Is help needed?

**Comment by dennisocana** [comment]
Please refer to this article on how connectors are integrated into Hummingbot
https://hummingbot.zendesk.com/hc/en-us/articles/900004506986-How-connectors-are-integrated-into-Hummingbot
