### ISSUE TITLE
[BUG] Inventory skew enabled causes order size becomes less than allowed on Bittrex

### ISSUE THREAD

**Issue by supervik** [CoinAlpha/hummingbot#1092]
**Describe the bug**
It is the same bug as I posted here https://github.com/CoinAlpha/hummingbot/issues/1025 
with the help of a support person, but it apparently was not understood correctly, so I am posting it myself with more descriptions.

The problem occurs using the Pure Market Making strategy with Inventory skew option enabled on a Bittrex market. During trends, there is a possibility that one of the assets inventory becomes rather small ~10%-20%. The bot calculates the order amount according to the formula:
`bid_order_amount = order_amount * current_ratio_base / inventory_target_base_pct`
But the bot doesn't take into consideration Bittrex trading requirements of the minimum order size equal to 0.0005 BTC: 
https://bittrex.zendesk.com/hc/en-us/articles/360001473863-Bittrex-Trading-Rules

Depending on the initial order_size and current inventory ratios Hummingbot may try to open an order that is less than 0.0005 BTC and it causes an infinite updating error and greatly increases the log file size (more than 100 Mb in a few hours). 

```
SError: Error fetching response from POST-https://api.bittrex.com/v3/orders. HTTP Status Code 400: {'code': 'DUST_TRADE_DISALLOWED_MIN_VALUE'}
2019-11-20 16:15:22,304 - 3000 - hummingbot.market.bittrex.bittrex_market - WARNING - Failed to submit sell order to Bittrex. Check API key and network connection.
2019-11-20 16:15:22,973 - 3000 - hummingbot.strategy.pure_market_making.pure_market_making_v2 - INFO - (ETH-BTC) Creating limit ask orders at (Size, Price): ['0.01818838 ETH, 0.02179896 BTC'] [clock=2019-11-20 13:15:23+00:00]
2019-11-20 16:15:23,656 - 3000 - hummingbot.market.bittrex.bittrex_market - NETWORK - Error submitting sell LIMIT order to Bittrex for 0.01818838 ETH-BTC 0.02179896.
Traceback (most recent call last):
  File "hummingbot\market\bittrex\bittrex_market.pyx", line 847, in hummingbot.market.bittrex.bittrex_market.BittrexMarket.execute_sell
  File "hummingbot\market\bittrex\bittrex_market.pyx", line 702, in place_order
  File "hummingbot\market\bittrex\bittrex_market.pyx", line 996, in _api_request
  File "hummingbot\market\bittrex\bittrex_market.pyx", line 1004, in hummingbot.market.bittrex.bittrex_market.BittrexMarket._api_request
```

**Steps To Reproduce**
For example, after some time the inventory becomes ~90/10. 
1. Start from the inventory like this where ETH quantity is rather small:
BTC: 0.0086
ETH: 0.04
2. Set up your configuration with the order_size = 0.1 ETH and the rest as in the conf files attached
3. Start the bot

Due to Inventory skew enabled the Bot calculates new order_sizes like this:
```
bid_order_amount = 0.1818 ETH
ask_order_amount = 0.01818 ETH
```
Bittrex minTradeSize ETH allowed is 0.01314872. It is Ok 0.01818 ETH is larger.
But 0.01818 ETH is less than 0.0005 BTC so the the order fails to be opened.

As a result, Bittrex has one order opened + infinite error in logs + status command showing different results: one time it shows 2 orders opened, while another just 1, see the screenshot with several status outputs. 

**Screenshots**
![status_log_w](https://user-images.githubusercontent.com/57992574/69244432-fe339180-0bb5-11ea-9d3b-015d92a4cc91.jpg)

**Release version**
Version	0.19.0
Tried on two machines: Binary Windows + Linux from source

**Attachments**
[logs_conf_pure_market_making_strategy_2.log](https://github.com/CoinAlpha/hummingbot/files/3869530/logs_conf_pure_market_making_strategy_2.log)
[conf_pure_market_making_strategy_2.txt](https://github.com/CoinAlpha/hummingbot/files/3869535/conf_pure_market_making_strategy_2.txt)

**Optional: your discord username:** vik
**Optional: your ETH address:**
0x8b5d5c13C9Df50930C626583f47234f7f1314B27

**Comment by CrimsonJacket** [comment]
Looking into this, it appears that there is some inconsistencies with the values for `minTradeSize` and the minimum trading size as stated in their [documentation](https://bittrex.zendesk.com/hc/en-us/articles/360001473863-Bittrex-Trading-Rules).

It should be obvious that `0.01314872ETH` < `0.0005BTC`.

I have already pinged a Bittrex contact with regards to this matter. 
Thanks for the understanding and I will update accordingly

**Comment by supervik** [comment]
It is very simple. As I see there are 2 limits in trading sizes on Bittrex. One is different for every coin and is expressed in a coin value so doesn't change over time. For ETH it is equal to 0.01314872 ETH. And another one is the same for any coin and is equal to 0.0005 BTC.  Since it is in BTC, it changes in a coin value depending on the current rate. The biggest one should be used.

For example, if ETH rate is 0.021 BTC, then `0.0005 BTC = 0.0238 ETH`. 
`0.0238 > 0.01314872`, so 0.0238 should be used for calculating the minimum trading size.

**Comment by CrimsonJacket** [comment]
Got confirmation for Bittrex, there seems to be 2 requirements. First there's the `minTradeSize` which can be derived from the API response. Like you mentioned, this is different for every coin. The other is a `minTradeValue`, again this is a static value of 0.0005 BTC. 

Essentially **both** must be fulfilled for an order to be successfully placed. Will be working on a fix for address this issue.
