### ISSUE TITLE
[BUG] Error fetching data from RadarRelay Orders and Error submitting trade order wings/radar_relay_market

### ISSUE THREAD

**Issue by mdominoni** [CoinAlpha/hummingbot#110]
**Describe the bug**
// A clear and concise description of what the bug is.
Error fetching data from RadarRelay Orders and Error submitting trade order
**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior** along with screenshots:
When trying to put an order in RadarRelay, using cross_exchange_market_making strategy, using RadarRelay (BAT-WETH) as Maker and Binance (BATETH) as Taker with default fees and profitability

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: ...
2. Start the bot using this command: ...
...

**Screenshots**
// If applicable, add screenshots to help explain your problem.
<img width="636" alt="Captura de pantalla 2019-04-24 16 43 51" src="https://user-images.githubusercontent.com/1105982/56689914-8601fd80-66b2-11e9-8838-3236ee619802.png">

**Release version**
// Include your bot's version number (Can be found at the bottom left corner of your CLI).
0.3.1

**Attachments**
// Attach any relevant configuration files, logs, tx hashes, etc. here.

// NOTE: We understand If you do not want to publish your config/log files. You can instead send them privately to dev@coinalpha.com and drop a link of this issue in the email.
// WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!

**Comment by chowryan** [comment]
Radar Relay rejects orders that expire <120s from current time. Try resyncing your computers clock, if that doesn't work try increasing the order expiration time in your strategy yml file.
```limit_order_min_expiration: 130.0``` to maybe ```limit_order_min_expiration: 140.0```

**Comment by chowryan** [comment]
@mdominoni there was a critical bug for Radar Relay in 0.4.0. please pull the latest master branch which includes this fix https://github.com/CoinAlpha/hummingbot/pull/113

**Comment by mifeng** [comment]
@mdominoni Please let us know if you're still seeing this error in the latest release. We believe the fix @chowryan mentioned addresses this error.

Also, since this qualifies the bug bounty program, please send me your ETH address and I will send you 0.1 ETH if the fix addresses your issue.

**Comment by chowryan** [comment]
assuming the config change fixed this issue (not a bug). @mdominoni  please reopen if you are still having this issue.
