### ISSUE TITLE
[BUG] Intermittent errors routing order book messages in Coinbase Pro

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#1101]
**Describe the bug**

Every one in a while these errors will come up when market making in Coinbase Pro. Haven't found out yet what the errors will result to since the strategy can still create and cancel orders in the exchange and the orders are getting filled without issues.

```
2019-11-21 05:14:13,643 - 10 - hummingbot.market.coinbase_pro.coinbase_pro_order_book_tracker - NETWORK - Unexpected error routing order book messages.
Traceback (most recent call last):
  File "/hummingbot/core/data_type/order_book_tracker.py", line 264, in _emit_trade_event_loop
    trading_pair: str = trade_message.trading_pair
  File "/hummingbot/core/data_type/order_book_message.py", line 50, in trading_pair
    return self.content["trading_pair"]
KeyError: 'trading_pair'
```

<img width="947" alt="multiple_client2" src="https://user-images.githubusercontent.com/50150287/69328697-a87ce900-0c8a-11ea-9f0d-8dac9d7fdd24.png">

**Release version**

```
"branch": "development",
"commit": "6a342013d42c050210501f69a44782b3012b4e16",
"date": "2019-11-20T23:59:55Z",
```

**Attachments**

[logs_coinbasepro_multiple.log](https://github.com/CoinAlpha/hummingbot/files/3874048/logs_coinbasepro_multiple.log)
[config_coinbasepro_multiple.txt](https://github.com/CoinAlpha/hummingbot/files/3874035/config_coinbasepro_multiple.txt)

**Comment by martinkou** [comment]
Fixed with #1104
