### ISSUE TITLE
Docker hub to report status of multiple bots

### ISSUE THREAD

**Issue by Zethtren** [CoinAlpha/hummingbot#1102]
**Concept**

Not advanced enough in coding to write this program however it would be nice to be able to run 'docker hummingbot-main' to pull up a hub that relays commands to each individual instance so I could run 'assign_instance 1 = hummingbot-instance', 'assign_instance 2= hummingbot-instance2'.....

and then run commands like 
'history 1',
'history 2',
'status 1',
'input 1 : "config min_profitability"'

**Impact**
It would make managing multiple markets easier without putting strain on containers.

**Comment by PtrckM** [comment]
Hi @Zethtren you will able to achieve this if your running single or multiple bots by integrating hummingbot to telegram, creating telegram token for each hummingbot and only one telegram chat id to control it. You can read more about this on https://docs.hummingbot.io/utilities/telegram/

**Comment by Zethtren** [comment]
Thank you, I’ll take a look at it tomorrow morning and report back
