### ISSUE TITLE
[BUG] Bamboo Relay unexpected keyword argument 'trading_pairs'

### ISSUE THREAD

**Issue by PtrckM** [CoinAlpha/hummingbot#1113]
**Describe the bug**
Unable to start and got an error `2019-11-23 01:20:47,044 - 10 - root - ERROR - Unhandled error in background task: __init__() got an unexpected keyword argument 'trading_pairs'` when starting xemm for bamboo_relay and radar_relay. Tried trading pair WETH-DAI and WETH-SAI on paper_trade

**Screenshots**
![image](https://user-images.githubusercontent.com/54516858/69470751-abcfbc00-0dd3-11ea-96de-53ebe783d9eb.png)

**Release version**
```
                "branch": "dev-0.20.0",
                "commit": "59a64224020e8f598d5612a784c27c0d7fc16bf2",
                "date": "2019-11-22T20:22:41Z",
```
**Attachments**
[conf.log](https://github.com/CoinAlpha/hummingbot/files/3882036/conf.log)
[logs.log](https://github.com/CoinAlpha/hummingbot/files/3882037/logs.log)

**Comment by BUDDHA-TONY** [comment]
Tested this with a different exchange pair ddex/radar-relay - WETH-DAI and was able to start.Possible the error exist with bamboo relay, as `Joshua l Bamboo Relay` said on discord channel `It's because symbol has been changed to trading_pair in hummingbot, so the Bamboo connector needs updating.`

                "branch": "development",
                "commit": "d70b143288a9959000d5b8aa0a309e13576394d0",
                "date": "2019-11-27T00:05:04Z",

**Comment by PtrckM** [comment]
confirmed fix on dev

                "branch": "development",
                "commit": "edfe7e82f6959aae47d163cb8e9095a6986183f4",
                "date": "2019-11-28T00:59:55Z",

![image](https://user-images.githubusercontent.com/54516858/69771972-9ab6ee80-11c9-11ea-9b75-a53a66005541.png)
