### ISSUE TITLE
[Feature] Automatic market_symbol update

### ISSUE THREAD

**Issue by Zethtren** [CoinAlpha/hummingbot#1117]
**Feature Suggestion**
Automatic market_symbol update request

We should add an IF THEN behavior so when taker or maker market information is updated it will check to see if the market_symbol is still valid and force you to update it immediately if it is not.

**Impact**
Reduce user error, reduce support staff workload, streamline performance

**Additional context**

**Comment by chowryan** [comment]
this seems impossible to scope and predict as it may differ between exchange apis. Can you give an example of this?

**Comment by Zethtren** [comment]
Yes. So, I had a mismatched pair on XEMM.  I had BTC-USDT on Bittrex and BTC-USDC on Coinbase Pro. The markets were pretty close and occasionally which one had a larger market would change. In response, I would change the maker and taker markets. These markets don’t exist on the others’ exchange. Meaning I then had to submit a second config request. This might be annoying if you didn’t have mismatched markets but, if a program checked if the market existed and received a result of let’s say, “market_exists=False” it would them prompt you to update your market.  Otherwise, it would continue as it does now.

**Comment by mifeng** [comment]
I believe fetching an updated list of trading pairs from the exchange using API (#1005) would cover this need.
