### ISSUE TITLE
[BUG]Cross-exchange MM strategy has incorrect price calculation with BUSD as base token

### ISSUE THREAD

**Issue by emjcsantos** [CoinAlpha/hummingbot#1120]
**Describe the bug**

I'm trying the cross-exchange MM on binance. ETC-BUSD and ETC-USDT.. I set the min. prof. to 1% and it still post limit orders even if it's not profitable.

**Steps To Reproduce**
1) Create Cross-exchange Market Making strategy
2) Maker and Taker exchange: Binance
3) Maker market symbol: ETC-BUSD
4) Taker market symbol: ETC-USDT
5) Min. profitability: 0.01 (also tried 0.001 and 0.1 - same result)
6) Other settings shown in the image below

**Screenshots**
![image](https://user-images.githubusercontent.com/47171080/69533765-64078b00-0fb3-11ea-861e-68b5102b70aa.png)

**Release version**
version 0.19.0

**Optional: your discord username:**
vhm

**Note**
Already discussed this with a support in discord (lorenz). He said that this is due to the changes in the new version. 

**ETH Address**
0x887c557d1da1ef56a409cb79d1ee108c17355888

**Comment by mifeng** [comment]
I replicated this bug - it's related to the BUSD token, a new Binance stablecoin that we are not handling correctly.

**Comment by emjcsantos** [comment]
Hi mike! thanks for the quick response! as you have mentioned, using other stable coins solved it.

**Comment by PtrckM** [comment]
@emjcsantos tested on paper trade, confirmed fix on dev

                "branch": "development",
                "commit": "f53b4c92914f70820f5231d96f964ad5ce7c04ca",
                "date": "2019-11-28T02:30:31Z",


![image](https://user-images.githubusercontent.com/54516858/69774531-1f593b00-11d1-11ea-9ca6-4c1f00bc01df.png)
