### ISSUE TITLE
[BUG] Primary market trading pair not valid

### ISSUE THREAD

**Issue by PtrckM** [CoinAlpha/hummingbot#1130]
**Describe the bug**
ETH-QNT / ETH_QNT - Primary market trading pair not valid

**Steps To Reproduce**
config -> pmm -> create -> idex -> trading_pair 

**Screenshots**
![image](https://user-images.githubusercontent.com/54516858/69689484-0d5d9680-1104-11ea-874c-55f622a52cf5.png)

**Work-around**
edit conf and manually enter ETH_QNT

`input maker_market_trading_pair: ETH_QNT`

![image](https://user-images.githubusercontent.com/54516858/69690327-59113f80-1106-11ea-8ce4-6dc7cc147ba8.png)

**Release version**
tested on both 0.19.1 and dev-0.20.0

                "branch": "master",
                "commit": "a7544f028b6d8a16a363058ea5f9968dd98dc589",
                "date": "2019-11-26T22:34:43Z",

                "branch": "development",
                "commit": "d70b143288a9959000d5b8aa0a309e13576394d0",
                "date": "2019-11-27T00:05:04Z",

**Comment by BUDDHA-TONY** [comment]
Also tested with command `config market_making_trading_pair` and was able to reproduce this behavior. Binary/windows/v-0.19.1

![1130](https://user-images.githubusercontent.com/55869559/69691941-8ad8d500-110b-11ea-87f3-85fa5e8da111.png)

**Comment by dennisocana** [comment]
@PtrckM @BUDDHA-TONY the generic trading pair format across all exchanges that we have recently released is in base-quote. In this case it should be QNT-ETH as QNT is the base token and ETH is quote.

![image](https://user-images.githubusercontent.com/50150287/69692031-cd9aad00-110b-11ea-984d-6b462c9d2960.png)

**Comment by PtrckM** [comment]
thank you @dennisocana 

![image](https://user-images.githubusercontent.com/54516858/69692280-76e1a300-110c-11ea-8b31-0196b78be2fc.png)
