### ISSUE TITLE
[BUG]Paper trade accepting orders below minimum order sizes

### ISSUE THREAD

**Issue by znerol19619** [CoinAlpha/hummingbot#1137]
**Describe the bug**
Orders with below minimum order size are being placed in paper trade mode.

In the screenshot below, i set the ``order_amount`` to 5, which is equal to ``0.0087925`` for buy order and ``0.0087945`` for sell order when multiplied to its corresponding prices. The total price of each orders are less than the required minimum order size in binance which is 0.01 ETH. 

**Steps To Reproduce**
Run a normal pure market making, enable paper trade and set a paper trade account balance you want to trade.

exchange : BINANCE
trading pair: ZRX-ETH

**Screenshots**
![Screenshot from 2019-11-28 16-02-34](https://user-images.githubusercontent.com/27669951/69794919-22225300-1206-11ea-9e1f-7116a574c818.png)

**Release version**
```
"branch": "development",
"commit": "7a2d92225781d0be87dec09279e702f3c0d39dc7",
"date": "2019-11-28T04:03:08Z",
```

**Comment by Hashira-Lars** [comment]
Tested & confirmed issue still persist both master & dev

**Comment by mifeng** [comment]
We added global minimum order sizes in Hummingbot around v0.23.0 which addresses this issue.
