### ISSUE TITLE
[BUG] PureMM with "NOT NULL constraint failed: TradeFill.exchange_trade_id" Error

### ISSUE THREAD

**Issue by rennel-tabing** [CoinAlpha/hummingbot#1138]
**Describe the bug**
// A clear and concise description of what the bug is.

orders are placed but start getting errors when orders are filled. I'm running into a `NOT NULL constraint failed error` when inserting into `TradeFill`

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: ...
I am confirming what the actual config parameters does the user have with `1e-08` of value
  ```
 template_version: 3
order_amount: 50.0
cancel_order_wait_time: 5
bid_place_threshold: 1e-08
ask_place_threshold: 1e-08
mode: single
number_of_orders: 3
order_start_size: 25
order_step_size: 5
order_interval_percent: 1e-09
inventory_skew_enabled: true
# Target base asset inventory percentage target to be maintained
inventory_target_base_percent: 0.5

# How long to wait before placing the next order in case your order gets filled for single order mode
filled_order_replenish_wait_time: 5.0
enable_order_filled_stop_cancellation: false
jump_orders_enabled: false
jump_orders_depth: 0.0
add_transaction_costs: false


```
2. Start the bot and wait for orders to get filled.

**Screenshots**
// If applicable, add screenshots to help explain your problem.

**Release version**
// 0.19.1 via source

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

Config and error logs are available on this link  https://gist.github.com/ariejan/3f85ef242c3c82bcb1edd2589903876c

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:** Airborne#6921
**Optional: your ETH address:** (If you want to participate in the bug bounty)

**Comment by moraliang** [comment]
@rennel-tabing  May I have the ETH address of this bug reporter? Thanks.
