### ISSUE TITLE
Binance margin wallet supported?

### ISSUE THREAD

**Issue by opoloko** [CoinAlpha/hummingbot#1141]
Hi I cant find this info, does Hummingbird support margin wallet on Binance?

**Comment by znerol19619** [comment]
@opoloko , hummingbot doesn't support margin wallet in Binance and we have no information about it included in our hummingbot documentation. For a much faster response of support you can join our Hummingbot discord community. https://discord.hummingbot.io

**Comment by Clint-G13** [comment]
Future and Margin trading will be in the year 2020's road map. Once these are integrated into Hummingbot, margin wallets will be added.

![Capture](https://user-images.githubusercontent.com/57189990/69880685-8ed04700-1305-11ea-8e25-d32504e5e7ce.PNG)
