### ISSUE TITLE
[BUG] Unable to convert 'from_currency' to 'to_currency' using fiat (EUR) and failing to display performance analysis

### ISSUE THREAD

**Issue by Clint-G13** [CoinAlpha/hummingbot#1144]
**Describe the bug**
// A clear and concise description of what the bug is.

The user is placing an order using BTC-EUR/ BTC-USDT pairs and when performing `history` command, `Error running performance analysis` occurs.

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters (Paper_trade): ...

   maker_market: coinbase_pro
   taker_market: binance
   maker_market_trading_pair: BTC-EUR
   taker_market_trading_pair: BTC-USDT
   min_profitability: 0.01
   order_amount: 0.02
   active_order_canceling: true
   cancel_order_threshold: 0.05
   limit_order_min_expiration: 130.0
   adjust_order_enabled: true
   top_depth_tolerance: 0.0
   anti_hysteresis_duration: 60.0
   order_size_taker_volume_factor: 0.25
   order_size_taker_balance_factor: 0.995
   order_size_portfolio_ratio_limit: 0.1667

2. Add `EUR` on the exchange rate conversion found on the global.yml template
3. Validate with the user if fiat trading is authorized in his region.

**Screenshots**
// If applicable, add screenshots to help explain your problem.

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).
`branch: 0.20.0 via source`
`commit: 6a974d8aad79c8fa19d24738e8ae5a991f03e02c`
**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*
[logs_brs.log](https://github.com/CoinAlpha/hummingbot/files/3906638/logs_brs.log)

[brs.yml.zip](https://github.com/CoinAlpha/hummingbot/files/3906639/brs.yml.zip)

**Optional: your discord username: **Vesla**
**Optional: your ETH address:** (If you want to participate in the bug bounty)

**Comment by vesl** [comment]
I found this error : 
```
Traceback (most recent call last):
  File "/hummingbot/client/command/history_command.py", line 168, in trade_performance_report
    raw_queried_trades,
  File "/hummingbot/client/performance_analysis.py", line 245, in calculate_trade_performance
    combined_acquired, quote_asset, primary_quote_asset, source="default"
  File "/hummingbot/core/utils/exchange_rate_conversion.py", line 179, in convert_token_value_decimal
    return Decimal(repr(self.convert_token_value(float(amount), from_currency, to_currency, source)))
  File "/hummingbot/core/utils/exchange_rate_conversion.py", line 204, in convert_token_value
    raise ValueError(f"Unable to convert '{from_currency}' to '{to_currency}'. Aborting.")
ValueError: Unable to convert 'EUR' to 'EUR'. Aborting.
```

On /hummingbot/core/utils/exchange_rate_conversion.py line 204: 
```
        from_currency_usd_rate = exchange_rate.get(from_currency.upper(), NaN)
        to_currency_usd_rate = exchange_rate.get(to_currency.upper(), NaN)
        if math.isnan(from_currency_usd_rate) or math.isnan(to_currency_usd_rate):
            raise ValueError(f"Unable to convert '{from_currency}' to '{to_currency}'. Aborting.")
```

So, each from_currency_usd_rate or to_currency_usd_rate is NaN.
Let’s see definition of this function : 
```
    def get_exchange_rate(self, source: str = None) -> Dict[str, float]:
        if source == "default":
            if self._default_data_feed not in self.all_exchange_rate:
                self.logger().error(f"{self._default_data_feed} is not in one of the data feeds: "
                                    f"{self.all_exchange_rate.keys()}.")
                raise Exception("Data feed name not valid.")
            self.logger().error(self.all_exchange_rate[self._default_data_feed])
            return self.all_exchange_rate[self._default_data_feed]
```

I added a `print(self.all_exchange_rate[self._default_data_feed])` result is in [coingeko_api.txt](https://github.com/CoinAlpha/hummingbot/files/3907120/coingeko_api.txt)
Search in, there is no key EUR : that’s the problem.
I searched on Coingecko from webui the better key is EURS since it value is mirrored from EUR https://eurs.stasis.net/.
So I added following patch line 202 : 
 ```
       currency_mapping_table = {
            'EUR':'EURS',
        }
        if from_currency.upper() in currency_mapping_table: from_currency_mapped = currency_mapping_table[from_currency.upper()]
        else: from_currency_mapped = from_currency.upper()
        if to_currency.upper() in currency_mapping_table: to_currency_mapped = currency_mapping_table[to_currency.upper()]
        else: to_currency_mapped = to_currency.upper()
        from_currency_usd_rate = exchange_rate.get(from_currency_mapped, NaN)
        to_currency_usd_rate = exchange_rate.get(to_currency_mapped, NaN)
```
Of course I had to add EURS in my conf_global to tell hummingbot getting EURS value on coingeckoapi :
```
- - EURS
  - 1.0
  - coin_gecko_api
```
Working 👍 
![history_working](https://user-images.githubusercontent.com/12445651/69900935-20799c00-137a-11ea-9de1-6721e3ef0bd3.png)

**Comment by vesl** [comment]
I still try this trading pair in paper_trade mode until you tell me if there is no other conversion problem about EUR somewhere else in the app because of coingecko API return.

**Comment by veecos2** [comment]
We currently do not have the feature for exchange rate conversions between fiat currencies, such as EUR to USD. Please raise a feature request for the same.
