### ISSUE TITLE
[BUG] Unable to start Dolomite error 'trading_pairs'

### ISSUE THREAD

**Issue by PtrckM** [CoinAlpha/hummingbot#1148]
**Describe the bug**
Any exchange connector pair to dolomite won't start. 

`__init__() got an unexpected keyword argument 'trading_pairs' `

**Screenshots**
![image](https://user-images.githubusercontent.com/54516858/69911148-14f9a400-1452-11ea-8efe-feba72e0f0ea.png)
![image](https://user-images.githubusercontent.com/54516858/69911213-3ad37880-1453-11ea-87df-3db0a0133167.png)

**Release version**

                "branch": "development",
                "commit": "6a974d8aad79c8fa19d24738e8ae5a991f03e02c",
                "date": "2019-11-29T08:53:30Z",

**Attachments**
[conf_discovery_strategy_1.txt](https://github.com/CoinAlpha/hummingbot/files/3907930/conf_discovery_strategy_1.txt)
[logs_conf_discovery_strategy_1.log](https://github.com/CoinAlpha/hummingbot/files/3907931/logs_conf_discovery_strategy_1.log)

**Comment by PtrckM** [comment]
unable to display profitabilty dolomite-huobi

![image](https://user-images.githubusercontent.com/54516858/70017037-f4019200-15bc-11ea-90ca-769d10627e79.png)


                "branch": "development",
                "commit": "4dfaa01c6476ed4492a165b507bdc7b4bc41dfa9",
                "date": "2019-12-03T00:45:00Z",

**Comment by BUDDHA-TONY** [comment]
Tested this getting an error despite my wallet address is correct resulting to unable to display profitability/unlimited loop of `waiting to finish fetching trading pair from dolomite`.

1.also tried connecting my metamask/wallet before starting the strategy
2.tried restarting the strategy same output

```
2019-12-04 08:48:38,536 - 1655 - hummingbot.market.dolomite.dolomite_market - INFO - Issue with Dolomite API GET to /v1/addresses/******************************************/info, response: 
2019-12-04 08:48:38,536 - 1655 - hummingbot.market.dolomite.dolomite_market - INFO - {"global_objects":null,"data":null,"paging_metadata":null,"cursor":null,"error":{"category":"NOT_FOUND_ERROR_CATEGORY","code":"ACCOUNT_WALLET_NOT_FOUND","description":"Account information for wallet address ****************************************** not found.","request_id":1995771,"invalid_fields":[],"extra_data":null}}
2019-12-04 08:48:38,536 - 1655 - hummingbot.market.dolomite.dolomite_market - INFO - No Dolomite account for ******************************************. Create an account on the exchange at dolomite.io
```

**Comment by PtrckM** [comment]
tagging @coreycaplan3

**Comment by PtrckM** [comment]
Unable to start with error "Market name dolomite is invalid."

![image](https://user-images.githubusercontent.com/54516858/71301900-f9921100-23df-11ea-93bf-29fa7ac6aae3.png)
![image](https://user-images.githubusercontent.com/54516858/71301903-0151b580-23e0-11ea-9aa9-e726835e517c.png)

using autostart trading https://docs.hummingbot.io/operation/client/#trading-strategy-autostart bot will work but still dolomite unable to show profitability

![image](https://user-images.githubusercontent.com/54516858/71301918-3c53e900-23e0-11ea-9a09-9c7d4e00bf02.png)

[logs_conf_discovery_strategy_dolomite_binance.log](https://github.com/CoinAlpha/hummingbot/files/3990975/logs_conf_discovery_strategy_dolomite_binance.log)
[logs_conf_discovery_strategy_dolomite_huobi.log](https://github.com/CoinAlpha/hummingbot/files/3990976/logs_conf_discovery_strategy_dolomite_huobi.log)
[logs_conf_discovery_strategy_dolomite_ddex.log](https://github.com/CoinAlpha/hummingbot/files/3990979/logs_conf_discovery_strategy_dolomite_ddex.log)
[logs_conf_discovery_strategy_dolomite_bamboo.log](https://github.com/CoinAlpha/hummingbot/files/3990986/logs_conf_discovery_strategy_dolomite_bamboo.log)


```
                "branch": "development",
                "commit": "5a94dbb9d8876dd0ab2f5d166dd90193e0a25e72",
                "date": "2019-12-21T00:32:40Z",
```

**Comment by coreycaplan3** [comment]
Looking into this now. I think Dolomite's errors need to be more descriptive. Essentially, this error will be fixed by creating an account which is done in 1 of 2 ways:

1. If you're **outside** the US, you simply submit a trade from the website.
2. If you're **inside** the US, you create an account from the website.

**Comment by coreycaplan3** [comment]
I'm going to push a commit that adequately describes the above problem and addresses it

**Comment by PtrckM** [comment]
I already link my wallet but still having problem @coreycaplan3 

- **SCREENSHOTS**

![image](https://user-images.githubusercontent.com/54516858/71703096-f3535a00-2e0d-11ea-910d-c09bf454b94c.png)

![image](https://user-images.githubusercontent.com/54516858/71703106-fe0def00-2e0d-11ea-9dfa-73c1e690a778.png)

![image](https://user-images.githubusercontent.com/54516858/71703113-01a17600-2e0e-11ea-818c-0924f290270d.png)

- **LOGS**
[logs_conf_discovery_strategy_0.log](https://github.com/CoinAlpha/hummingbot/files/4017894/logs_conf_discovery_strategy_0.log)

**Comment by Hashira-Lars** [comment]
@coreycaplan3 just to clarify . if we are outside of the US we need to trade. do you mean by `trade` that we need to sell or buy in any token pair on dolomite exchange website?

**Comment by PtrckM** [comment]
**confirmed fix**

![image](https://user-images.githubusercontent.com/54516858/71706158-2271c780-2e1e-11ea-8dab-efc3c423aab0.png)

@Hashira-Lars thats correct talk to Corey at telegram, must create a trade in order to be fully registered if using metamask wallet.

**Comment by coreycaplan3** [comment]
@Hashira-Lars yes, it means placing a `maker` or `taker` trade on the exchange, for any pair!
