### ISSUE TITLE
[BUG] idex fail to show profitability on discovery

### ISSUE THREAD

**Issue by PtrckM** [CoinAlpha/hummingbot#1165]
**Describe the bug**
 - Idex fails to show profitability on discovery strategy
- Any exchange connector pair to idex won't show profitability.

![image](https://user-images.githubusercontent.com/54516858/70199099-c6971e80-174b-11ea-9220-a346343d4475.png)
![image](https://user-images.githubusercontent.com/54516858/70199172-f9d9ad80-174b-11ea-82a3-838722047deb.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/54516858/70199246-2e4d6980-174c-11ea-98a6-7e714d3c5cdc.png)
![image](https://user-images.githubusercontent.com/54516858/70199255-32798700-174c-11ea-80ca-84681aba7892.png)
![image](https://user-images.githubusercontent.com/54516858/70199260-36a5a480-174c-11ea-959d-e85e73f8712a.png)

**Release version**
```
                "branch": "development",
                "commit": "ada2912e293ae932f69ba5b65eb8825843ee484e",
                "date": "2019-12-04T21:33:55Z",
```

**Attachments**
- LOGS
[logs_conf_discovery_strategy_coinbase_idex.log](https://github.com/CoinAlpha/hummingbot/files/3924881/logs_conf_discovery_strategy_coinbase_idex.log)
[logs_conf_discovery_strategy_binance_idex.log](https://github.com/CoinAlpha/hummingbot/files/3924882/logs_conf_discovery_strategy_binance_idex.log)

- CONF
[conf_discovery_strategy_binance_idex.txt](https://github.com/CoinAlpha/hummingbot/files/3924887/conf_discovery_strategy_binance_idex.txt)

**Comment by rennel-tabing** [comment]
I am able to reproduce the issue using the latest builds.

```
Tested on latest dev branch (as of this writing)
"Labels": {
                "branch": "development",
                "commit": "54a4441558d868f0466ccbea62ce8989caba61f2",
                "date": "2020-01-04T06:43:32Z",
```
```				
Tested on main branch 

 "Labels": {
                "branch": "master",
                "commit": "a8070e3369d9273ddb29e7d9e505987ad8fa1b46",
                "date": "2019-12-30T21:27:45Z",	
```

**Comment by yzhang1994** [comment]
The IDEX connector is deprecated - we will no longer support IDEX-related issues. Closing this issue for now.
