### ISSUE TITLE
[BUG] Hanging orders resulting to memory leak

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#1167]
**Describe the bug**

Running pure market making strategy with hanging orders enabled continuously increase RAM usage and will eventually kill Hummingbot instance when out of memory.

When hanging orders feature is disabled on single order mode it only uses 1.084gb of RAM even when kept running for a while. When enabled, it starts to use about 1.121gb. I monitored the usage and captured screenshots over a period of time.

Usage as of 04:11 PM

<img width="239" alt="04_11" src="https://user-images.githubusercontent.com/50150287/70205933-cf461f80-1760-11ea-8c27-bce9c79d6ce6.png">

As of 06:09 PM and 06:57 PM

<img width="307" alt="06_09" src="https://user-images.githubusercontent.com/50150287/70205979-fac90a00-1760-11ea-8db4-637a85d835f4.png"> <img width="326" alt="06_57" src="https://user-images.githubusercontent.com/50150287/70206009-17fdd880-1761-11ea-84d4-987ec6cb8295.png">

As of 08:01 PM and 09:44 PM

<img width="319" alt="08_01" src="https://user-images.githubusercontent.com/50150287/70206015-1cc28c80-1761-11ea-9673-54a46905f97c.png"> <img width="318" alt="09_44" src="https://user-images.githubusercontent.com/50150287/70206020-20eeaa00-1761-11ea-8a13-aff3321008a7.png">

As of 10:40 PM and 11:18 PM

<img width="319" alt="10_40" src="https://user-images.githubusercontent.com/50150287/70206024-25b35e00-1761-11ea-89df-e06a5046aab4.png"> <img width="305" alt="11_18" src="https://user-images.githubusercontent.com/50150287/70206045-31068980-1761-11ea-9841-c6cfa821f46d.png">

Around 7:00 AM the instance was killed with Docker exit code 137 and 23 outstanding orders.

Regardless of how many open hanging orders, usage will continue to increase. There are intervals where the count of orders does not move while the memory usage continues to go up.

**Release version**

```
"branch": "development",
"commit": "49a5c7071b122e4369bd1b062771cf6998fa8b15",
"date": "2019-12-03T18:37:34Z",
```

**Attachments** : [hanging_orders.zip](https://github.com/CoinAlpha/hummingbot/files/3925247/hanging_orders.zip)

**Comment by bb111189** [comment]
Thanks, guys for the fix. Looking forwarding to the official release of the fix

**Comment by veecos2** [comment]
This is now merged into Development.

**Comment by nlnico** [comment]
running 0.24.0 latest and still having the issue with hanging orders.
