### ISSUE TITLE
[BUG] Running Discovery - ERROR - Unexpected error with WebSocket connection

### ISSUE THREAD

**Issue by rennel-tabing** [CoinAlpha/hummingbot#1179]
**Describe the bug**
// A clear and concise description of what the bug is.

Running Discovery between binance and Huobi gives out an error. Changes on the config parameters that is not default to this test was "Target profitability" and "Target amount"

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: ...

```
# Exchange and token parameters
primary_market: binance
secondary_market: huobi
target_trading_pair_1: []
target_trading_pair_2: []

# Minimum profitability target required to place an order
# Expressed in decimals: 0.01 = 1% target profit
target_profitability: 0.5
target_amount: 100.0

```

2. Start the bot

**Screenshots**
// If applicable, add screenshots to help explain your problem.

My first attempt to run the given config gave me this error

```
019-12-10 14:58:09,707 - 11 - hummingbot.market.huobi.huobi_api_order_book_data_source - ERROR - Unexpected error with WebSocket connection. Retrying after 30 seconds...
Traceback (most recent call last):
  File "/hummingbot/market/huobi/huobi_api_order_book_data_source.py", line 192, in listen_for_trades
    await ws.send(f'{{"op":"pong","ts": {str(msg["ping"])}}}')
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/websockets/protocol.py", line 361, in send
    yield from self.ensure_open()
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/websockets/protocol.py", line 501, in ensure_open
    self.close_code, self.close_reason) from self.transfer_data_exc
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason
```

![image](https://user-images.githubusercontent.com/53868268/70546074-9c26d600-1b3c-11ea-8e57-ba441dfaf56f.png)
 
Please note that the results has been exported to a CSV file without an issue. 

I re-run the strategy and had a different error. This time the bot just do the discovery on loop and no results were exported. It also have a different error logs
```2019-12-10 15:29:10,944 - 11 - hummingbot.market.binance.binance_api_order_book_data_source - ERROR - Unexpected error.
Traceback (most recent call last):
  File "/hummingbot/market/binance/binance_api_order_book_data_source.py", line 233, in listen_for_order_book_snapshots
    snapshot: Dict[str, Any] = await self.get_snapshot(client, trading_pair)
  File "/hummingbot/market/binance/binance_api_order_book_data_source.py", line 125, in get_snapshot
    raise IOError(f"Error fetching Binance market snapshot for {trading_pair}. "
OSError: Error fetching Binance market snapshot for KAVABTC. HTTP status is 418.

```

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).

version dev-0.20.0
```
"Labels": {
                "branch": "development",
                "commit": "86ac7e58336bf2f47ba6454391dce2940158b1ac",
                "date": "2019-12-09T23:38:15Z",
```

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 
[logs_conf_discovery_strategy_2.log](https://github.com/CoinAlpha/hummingbot/files/3945849/logs_conf_discovery_strategy_2.log)

Log file on the first attempt of running the strategy
[logs_conf_discovery_strategy_2.log](https://github.com/CoinAlpha/hummingbot/files/3945852/logs_conf_discovery_strategy_2.log)

Log file on the second attempt of running the strategy
[logs_conf_discovery_strategy_2 - Second attempt.log](https://github.com/CoinAlpha/hummingbot/files/3945860/logs_conf_discovery_strategy_2.-.Second.attempt.log)

**Comment by PtrckM** [comment]
Test1 VM1:

![image](https://user-images.githubusercontent.com/54516858/70583812-d1452e00-1bf9-11ea-90a3-10aced8861b9.png)

- LOGS
[logs_conf_discovery_strategy_2.log](https://github.com/CoinAlpha/hummingbot/files/3948023/logs_conf_discovery_strategy_2.log)

- CSV
[discovery_strategy_output_2019-12-11-01-28-06.txt](https://github.com/CoinAlpha/hummingbot/files/3948019/discovery_strategy_output_2019-12-11-01-28-06.txt)


Test2 VM2:

![image](https://user-images.githubusercontent.com/54516858/70584416-05215300-1bfc-11ea-9829-94cd966773f1.png)

- CSV
[discovery_strategy_output_2019-12-11-01-49-31.txt](https://github.com/CoinAlpha/hummingbot/files/3948043/discovery_strategy_output_2019-12-11-01-49-31.txt)

- LOGS
[logs_conf_discovery_strategy_8.log](https://github.com/CoinAlpha/hummingbot/files/3948044/logs_conf_discovery_strategy_8.log)


                "branch": "development",
                "commit": "5fd961662b97d04fbcfed9e9715b7a0d55099725",
                "date": "2019-12-11T00:34:54Z",

**Comment by BUDDHA-TONY** [comment]
I was able to replicate this behavior when i was having a problem with my internet connection 
Was your internet okay when this behavior happened? the error might be showing because of slow internet connection.

```
ConnectionResetError
2019-12-11 09:40:24,864 - 559 - hummingbot.market.coinbase_pro.coinbase_pro_api_order_book_data_source - WARNING - Unexpected error with WebSocket connection. Retrying in 30 seconds. Check network connection.
2019-12-11 09:40:30,273 - 559 - hummingbot.market.coinbase_pro.coinbase_pro_api_order_book_data_source - WARNING - WebSocket ping timed out. Going to reconnect...
2019-12-11 09:40:32,164 - 559 - hummingbot.market.coinbase_pro.coinbase_pro_api_order_book_data_source - WARNING - WebSocket ping timed out. Going to reconnect...
```

**Comment by Clint-G13** [comment]
Just re-tested these errors again, I was able to reproduce the error on my local VM however no issue using the test server. After re-creating a new development instance on my local VM, no issue persisted.

**Comment by rennel-tabing** [comment]
Re-run the strategy twice using the most recent development release version up to date.
```
 "branch": "development",
                "commit": "b148468e9c281c1f417dbee1a03ef018a8fae798",
                "date": "2019-12-16T00:26:18Z",
```

No issues found. I am now resolving this issue.
