### ISSUE TITLE
Dex without real order book  - Question

### ISSUE THREAD

**Issue by patidarmanoj10** [CoinAlpha/hummingbot#1180]
Does Humming architecture support  exchange ( dex)  which has no real order book.  Example is Bancor which has no order book.  Trades are done based on available liquidity  in converter .  If it support then what are requirement to develop this kind of connector.

**Comment by Clint-G13** [comment]
There is an active discussion about this topic, you can check this forum: https://forum.hummingbot.io/t/hummingbot-connector-for-uniswap-and-other-amms/143 If you have dev related question, you can post it on the forum.

**Comment by patidarmanoj10** [comment]
Thanks for quick reply. will read dev forum for more details.
