### ISSUE TITLE
[BUG] Bot won't trade even when both bid and ask profitabilities are true 

### ISSUE THREAD

**Issue by moraliang** [CoinAlpha/hummingbot#119]
**Describe the bug**
Tried to do cross-exchange MM between Binance and DDEX, with TRUE bid and ask profitabilities and enough balances on both sides, the bot wouldn't place any orders. 

**Steps To Reproduce**
Just run the bot 

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/14824365/56755391-47b51e80-6744-11e9-80f1-c416308a60de.png)

**Release version**
The latest

**Attachments**
**Configs** as below - 
```
########################################################
###   Cross exchange market making strategy config   ###
########################################################

The following configuations are only required for the
cross exchange market making strategy

### Exchange and token parameters
maker_market: ddex
taker_market: binance
maker_market_symbol: WETH-TUSD
taker_market_symbol: ETHUSDC

### Minimum profitability target required to place an order
### Expressed in decimals: 0.01 = 1% target profit
min_profitability: 0.0005

### Maximum order size in terms of quote currency
trade_size_override: 0.0

### Maximum aggregate amount of orders in quote currency
### that are allowed at a better price than Hummingbot's
### order before Hummingbot adjusts its order and pricing
top_depth_tolerance:
- - ^.+(USDT|USDC|USDS|DAI|PAX|TUSD)$
  - 1000
- - ^.+ETH$
  - 10
- - ^.+BTC$
  - 0.5
active_order_canceling: true

### If active_order_canceling = false, this is the profitability/
### loss threshold at which to cancel the order.
### Expressed in decimals: 0.01 = 1% target profit
cancel_order_threshold: -0.5

### An amount in seconds, which is the minimum duration for any
### placed limit orders. Default value = 130 seconds.
limit_order_min_expiration: 130.0
```
// NOTE: We understand If you do not want to publish your config/log files. You can instead send them privately to dev@coinalpha.com and drop a link of this issue in the email.
// WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!

**Comment by mifeng** [comment]
In the cross-exchange market making strategy, profitability is only one of a number of checks that Hummingbot performs before placing an order. See this [question](https://github.com/CoinAlpha/hummingbot/issues/146) for a fuller description of the logic that Hummingbot uses.

We should revise the `status` output to reflect these additional indicators, such as  `top_depth_tolerance`
