### ISSUE TITLE
[BUG] Discovery | Any exchange paired with idex makes the bot freeze

### ISSUE THREAD

**Issue by znerol19619** [CoinAlpha/hummingbot#1213]
**Describe the bug**
Running Discovery strategy on any exchange paired with idex makes the hummingbot instance hanging. 

**Steps To Reproduce**
Configure a discovery strategy and set any exchange along with idex. After running ``start`` command it will then hang after a few minutes. 

No errors were found in the log file and right log pane.
...

**Screenshots**
![discovery_usage](https://user-images.githubusercontent.com/27669951/71166271-4d401580-228d-11ea-9ce3-b27a638fd639.png)
![discovery](https://user-images.githubusercontent.com/27669951/71164042-40212780-2289-11ea-8022-04847ef217d6.png)

**Release version**
```
                "branch": "development",
                "commit": "ccb6c2a4df26f22583f7cc449793744c9a17f297",
                "date": "2019-12-18T08:37:17Z"
```

**Attachments**
[conf_discovery_strategy_0.txt](https://github.com/CoinAlpha/hummingbot/files/3982814/conf_discovery_strategy_0.txt)
[logs_conf_discovery_strategy_0.log](https://github.com/CoinAlpha/hummingbot/files/3982930/logs_conf_discovery_strategy_0.log)

**Comment by PtrckM** [comment]
https://github.com/CoinAlpha/hummingbot/issues/1165

**Comment by znerol19619** [comment]
Tested again and got a different behavior this time. Infinite loop of order book initialization. Profitability doesn't show as well. 

**Error**

```
Traceback (most recent call last):
  File "/hummingbot/market/liquid/liquid_api_order_book_data_source.py", line 223, in get_tracking_pairs
    snapshot: Dict[str, Any] = await self.get_snapshot(client, trading_pair, 1)
  File "/hummingbot/market/liquid/liquid_api_order_book_data_source.py", line 199, in get_snapshot
    raise IOError(f"Error fetching Liquid market snapshot for {id}. "
OSError: Error fetching Liquid market snapshot for <built-in function id>. HTTP status is 429.
2019-12-30 10:33:20,781 - 10 - hummingbot.market.liquid.liquid_api_order_book_data_source - NETWORK - Unexpected error with WebSocket connection.
Traceback (most recent call last):
  File "/hummingbot/market/liquid/liquid_api_order_book_data_source.py", line 357, in listen_for_order_book_snapshots
    snapshot: Dict[str, any] = await self.get_snapshot(client, trading_pair)
  File "/hummingbot/market/liquid/liquid_api_order_book_data_source.py", line 199, in get_snapshot
    raise IOError(f"Error fetching Liquid market snapshot for {id}. "
OSError: Error fetching Liquid market snapshot for <built-in function id>. HTTP status is 429.
```

```
                "branch": "development",
                "commit": "38ceaf9995d7a37c49c4734b0c95e0e27f2a9632",
                "date": "2019-12-29T15:16:11Z",

```

**Attachement**
[logs_conf_discovery_strategy_2.log](https://github.com/CoinAlpha/hummingbot/files/4009594/logs_conf_discovery_strategy_2.log)

**Comment by yzhang1994** [comment]
The IDEX connector is deprecated - we will no longer support IDEX-related issues. Closing this issue for now.
