### ISSUE TITLE
[BUG]Bamboo_Relay: Error conversion from NoneType to Decimal is not supported

### ISSUE THREAD

**Issue by Clint-G13** [CoinAlpha/hummingbot#1219]
**Describe the bug**
Running PMM  and XEMM  using bamboo_relay

**Steps To Reproduce**
Update development branch to the most recent commit and run strategy.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/57189990/71221237-e95a3300-2306-11ea-86fc-5b6dcd6eae82.PNG)

**Release version**
Commit: `851a01be8d24d5e588f359134bc65acee9879e5d`
Branch: Development
Date:   Thu Dec 19 16:02:24 2019

**Attachments**
[logs_conf_pure_market_making_strategy_0.log](https://github.com/CoinAlpha/hummingbot/files/3986220/logs_conf_pure_market_making_strategy_0.log)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**
**Optional: your ETH address:** (If you want to participate in the bug bounty)

**Comment by Arctek** [comment]
@Clint-G13 is `kill_switch_rate` set in your global config file?

As those logs are complaining about it not being present (`NoneType`), so I'd guess if you added this then it should continue.

i.e. `kill_switch_rate: -1.0`

**Comment by PtrckM** [comment]
Make sure your kill switch was set either true or false and has value on the rate.

```
# Kill switch
kill_switch_enabled: false
## The rate of performance at which you would want the bot to stop trading (-0.2 = 20%)
kill_switch_rate: -1.0
```

**Comment by Clint-G13** [comment]
Confirm fix, closing ticket now.
