### ISSUE TITLE
[BUG] Kill switch decimal value not converted to %

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#1226]
**Describe the bug**

Setting `kill_switch_rate` to -0.1 should be equivalent to -10% profit. Below screenshot shows kill switch being triggered at -0.162%

<img width="373" alt="kill_switch" src="https://user-images.githubusercontent.com/50150287/71252844-0b809f00-2361-11ea-95bd-6942c4273bbb.png">

**Release version**

```
"branch": "development",
"commit": "ac91e82310f2f9d4fac0281443c0e25e45584baa",
"date": "2019-12-20T01:21:32Z",
```

**Comment by BUDDHA-TONY** [comment]
Confirm fix tested with the most recent dev merged with the PRhttps://github.com/CoinAlpha/hummingbot/pull/1239/files [RESOLVE] 

![image](https://user-images.githubusercontent.com/55869559/71455227-1018dd80-27cf-11ea-91ad-f581fd6bb24d.png)
