### ISSUE TITLE
[BUG] Radar Relay WebSocket connection error

### ISSUE THREAD

**Issue by Clint-G13** [CoinAlpha/hummingbot#1229]
**Describe the bug**
// User upgraded binary installer of Hummingbot to version 0.20.0 and running arbitrage strategy.

**Steps To Reproduce**
![unknown](https://user-images.githubusercontent.com/57189990/71299604-1f5feb80-23c9-11ea-8dca-d2180bd9a917.png)

      2019-12-20 17:06:59,151 - 16416 - 
      hummingbot.market.radar_relay.radar_relay_api_order_book_data_source - 
      ERROR - Unexpected error with WebSocket connection. Retrying after 30 
      seconds...
      Traceback (most recent call last):
      File 
     "hummingbot\market\radar_relay\radar_relay_api_order_book_data_source.py", line 207, in listen_for_order_book_diffs
       File "site-packages\websockets\py35\client.py", line 2, in __aenter__
       File "site-packages\websockets\py35\client.py", line 19, in __await_impl__
       File "site-packages\websockets\client.py", line 263, in handshake
       websockets.exceptions.InvalidStatusCode: Status code not 101: 502
**Release version**
version 0.20.0 (master)

**Attachments**
[logs_conf_arbitrage_strategy_15.log](https://github.com/CoinAlpha/hummingbot/files/3990768/logs_conf_arbitrage_strategy_15.log)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username: sk22
**Optional: your ETH address:** (If you want to participate in the bug bounty)

**Comment by dennisocana** [comment]
Clinton said this error doesn't show on previous version 0.19.0
Same errors also intermittently show on my pure-mm bot in Radar Relay
[logs_conf_pmm_zrx-weth.log](https://github.com/CoinAlpha/hummingbot/files/3990817/logs_conf_pmm_zrx-weth.log)

**Comment by bghughes** [comment]
I am also having issues on version 0.22.0 with connecting to Radar Relay. I am not passing the initial market check for connection to the exchange... perhaps this has something to do with their V3 release: https://medium.com/radartech/introducing-relay-v3-abd8158f2771. Any guidance or help would be fantastic. Thanks!

**Comment by dennisocana** [comment]
@bghughes the Radar Relay connector is broken right now because Radar moved their API to a new version. We have not updated hummingbot's Radar connector which is probably why you are seeing all the issues on Radar.

https://docs.hummingbot.io/release-notes/0.22.0/#radar-relay-upgrade-to-0x-v3
