### ISSUE TITLE
[BUG] Active orders not deducted from available balance in Bamboo Relay

### ISSUE THREAD

**Issue by znerol19619** [CoinAlpha/hummingbot#1238]
**Describe the bug**
No deduction from available balance, even tho there's an active order. 

**Steps To Reproduce**
1. Setup XEMM / PMM 
2. Run start command
3. Wait for orders to be placed.
4. Run status command

**Screenshots**
PMM

you can see here that the ``available balance`` for sell/buy order is the same with ``total balance`` even tho there are orders placed on each side.
![pmmbamboo](https://user-images.githubusercontent.com/27669951/71409920-32e7ac80-267e-11ea-90d8-181ba8cdf05e.png)

XEMM

The same with xemm.
![xemmbamboo](https://user-images.githubusercontent.com/27669951/71409928-3844f700-267e-11ea-9759-2dbc1ded5035.png)

**Release version**
```
                "branch": "development",
                "commit": "86b356f45f2eb55c3e5cc174384a3e4e1c5a8c0f",
                "date": "2019-12-24T00:50:13Z",

```

**Attachments**
[logs_conf_cross_exchange_market_making_strategy_0.log](https://github.com/CoinAlpha/hummingbot/files/3998094/logs_conf_cross_exchange_market_making_strategy_0.log)
[conf_cross_exchange_market_making_strategy_0.txt](https://github.com/CoinAlpha/hummingbot/files/3998096/conf_cross_exchange_market_making_strategy_0.txt)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:** Lorenz | Support

**Comment by Arctek** [comment]
See PR #1253 for fix

**Comment by znerol19619** [comment]
Just tested PR https://github.com/CoinAlpha/hummingbot/pull/1253 and ``available balance`` has a correct value now. Will test again once merged to dev. 
![Screenshot from 2019-12-29 18-54-11](https://user-images.githubusercontent.com/27669951/71555945-aa498180-2a6c-11ea-8bd7-eb8689b66964.png)

**Comment by znerol19619** [comment]
Tested in latest development release, and it is confirmed working now. Will now close this github issue.

**Release version**
```
                "branch": "development",
                "commit": "38ceaf9995d7a37c49c4734b0c95e0e27f2a9632",
                "date": "2019-12-29T15:16:11Z",

```
