### ISSUE TITLE
[BUG] Hummingbot trades not showing in Coinbase Pro

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#1241]
**Describe the bug**

Hummingbot shows there are trades executed but doesn't reflect in Coinbase Pro. Trades may not be real since my portfolio value hasn't changed.

Exported trades from Hummingbot - [hummingbot_trades.xlsx](https://github.com/CoinAlpha/hummingbot/files/3999685/hummingbot_trades.xlsx)

<img width="947" alt="putty_R661uRC9cW" src="https://user-images.githubusercontent.com/50150287/71433606-1188ce00-271b-11ea-8590-eeb648101bcf.png">

See below for filled orders as showing in Coinbase Pro.

Downloaded report - [coinbasepro_report.xlsx](https://github.com/CoinAlpha/hummingbot/files/3999687/coinbasepro_report.xlsx)

![image](https://user-images.githubusercontent.com/50150287/71433681-8956f880-271b-11ea-9a07-59e625ba53f6.png)

Log file - [logs_pmm_cbp_link-eth.log](https://github.com/CoinAlpha/hummingbot/files/3999697/logs_pmm_cbp_link-eth.log)

**Comment by dennisocana** [comment]
I am no longer getting this issue since this recent release 0.21.0 - will keep an eye on it and see this will reoccur.

**Comment by yzhang1994** [comment]
@dennisocana closing this for now. Feel free to re-open if the error appears again.
