### ISSUE TITLE
[BUG] Too aggressive API calls with hanging orders enabled

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#1246]
**Describe the bug**

Opening a GitHub issue related to a bug that was posted here:
https://forum.hummingbot.io/t/too-aggressive-api-calls-with-hanging-orders-mode/138

A couple of cases were reported relating hanging orders to aggressive API calls and eventually resulting to IP getting blocked by Binance.

This has been fixed or is being investigated further. One user confirmed he's no longer experiencing this issue when running in the most recent development image.

**Discord username:** Dominator008
**ETH address:** Upon request

**Comment by bb111189** [comment]
I used to encounter this issue but after upgrading to version `0.21.0` in `dev` branch, it is no longer the issue. Seems like https://github.com/CoinAlpha/hummingbot/pull/1182 resolved it

**Comment by dennisocana** [comment]
Confirmed fix #1182.
