### ISSUE TITLE
[BUG] UnboundLocalError and OOM in Pure MM with multiple orders

### ISSUE THREAD

**Issue by bb111189** [CoinAlpha/hummingbot#1247]
**Describe the bug**
While running hummingbot, it encountered an OOM issue due to ever-increasing RAM usage. This is the last few lines of log file. Not sure whether is the OOM related to this exception or not
 
```
2019-12-26 22:40:25,393 - 10 - root - ERROR - Unhandled error in background task: local variable 'cancel_result' referenced before assignment
Traceback (most recent call last):
  File "/hummingbot/core/utils/async_utils.py", line 8, in safe_wrapper
    return await c
  File "binance_market.pyx", line 1095, in execute_cancel
UnboundLocalError: local variable 'cancel_result' referenced before assignment
2019-12-26 22:40:33,167 - 10 - root - ERROR - Unhandled error in background task: local variable 'cancel_result' referenced before assignment
Traceback (most recent call last):
  File "/hummingbot/core/utils/async_utils.py", line 8, in safe_wrapper
    return await c
  File "binance_market.pyx", line 1095, in execute_cancel
UnboundLocalError: local variable 'cancel_result' referenced before assignment
2019-12-26 22:40:38,991 - 10 - root - ERROR - Unhandled error in background task: local variable 'cancel_result' referenced before assignment
Traceback (most recent call last):
  File "/hummingbot/core/utils/async_utils.py", line 8, in safe_wrapper
    return await c
  File "binance_market.pyx", line 1095, in execute_cancel
UnboundLocalError: local variable 'cancel_result' referenced before assignment
2019-12-26 22:40:41,856 - 10 - root - ERROR - Unhandled error in background task: local variable 'cancel_result' referenced before assignment
Traceback (most recent call last):
  File "/hummingbot/core/utils/async_utils.py", line 8, in safe_wrapper
    return await c
  File "binance_market.pyx", line 1095, in execute_cancel
UnboundLocalError: local variable 'cancel_result' referenced before assignment
2019-12-26 22:40:46,233 - 10 - root - ERROR - Unhandled error in background task: local variable 'cancel_result' referenced before assignment
Traceback (most recent call last):
  File "/hummingbot/core/utils/async_utils.py", line 8, in safe_wrapper
    return await c
  File "binance_market.pyx", line 1095, in execute_cancel
UnboundLocalError: local variable 'cancel_result' referenced before assignment
2019-12-26 22:40:53,705 - 10 - hummingbot.core.event.event_reporter - EVENT_LOG - {"order_id": "sell-ZILETH-1577399888965065", "event_name": "OrderCancelledEvent", "event_source": "binance", "ts": 1577400042.0}
```

Looking deeper into the code at https://github.com/CoinAlpha/hummingbot/blob/master/hummingbot/market/binance/binance_market.pyx
```
    async def execute_cancel(self, trading_pair: str, order_id: str):
        try:
            cancel_result = await self.query_api(self._binance_client.cancel_order,
                                                 symbol=trading_pair,
                                                 origClientOrderId=order_id)
        except BinanceAPIException as e:
            if "Unknown order sent" in e.message or e.code == 2011:
                # The order was never there to begin with. So cancelling it is a no-op but semantically successful.
                self.logger().debug(f"The order {order_id} does not exist on Binance. No cancellation needed.")
                self.c_stop_tracking_order(order_id)
                self.c_trigger_event(self.MARKET_ORDER_CANCELLED_EVENT_TAG,
                                     OrderCancelledEvent(self._current_timestamp, order_id))
                return {
                    # Required by cancel_all() below.
                    "origClientOrderId": order_id
                }

        if isinstance(cancel_result, dict) and cancel_result.get("status") == "CANCELED":
            self.logger().info(f"Successfully cancelled order {order_id}.")
            self.c_stop_tracking_order(order_id)
            self.c_trigger_event(self.MARKET_ORDER_CANCELLED_EVENT_TAG,
                                 OrderCancelledEvent(self._current_timestamp, order_id))
        return cancel_result
```
Where there is a BinanceAPIException occured and did not trigger `if "Unknown order sent" in e.message or e.code == 2011:`, the function don't return. As a result, an unreferenced `cancel_result` was passed onto `isinstance(cancel_result, dict) and cancel_result.get("status")`, hitting `unboundlocalerror`. 

I think one possible way to declare `cancel_result` outside the `try` and let `isinstance()` do the job of checking `cancel_result`

This was the last error I seen before my instance goes OOM (rose from 400mb to 2gb). I hope that helps. 

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: ...
2. Start the bot using this command: ...
...
Parameters:
- Pure MM
- multiple bid and asks 
- `enable_order_filled_stop_cancellation` false 
- `best_bid_ask_jump_mode` false

2. start the bot
3. memory usage rising (might be due to another bug)
4. oom and killed
5. saw the exception above

**Screenshots**
// If applicable, add screenshots to help explain your problem.

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).
0.20.0

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**
**Optional: your ETH address:** (If you want to participate in the bug bounty)
`0x7BD500D2ebF748bB5b4BD57Fc3856bCeba9D26c4`

**Comment by veecos2** [comment]
@bb111189 : Can you send us the entire log file and complete config file ?. I am trying to find out what caused the binance api exception in the first place.

**Comment by bb111189** [comment]
@veecos2 unfortunately, I didn't retain the logs as the instance I am using crashed (not due to hummingbot) and become inaccessible. 

But I do noticed that I get IP banned for too many requests from time to time.

**Comment by dennisocana** [comment]
I'm running on multiple order of 3 orders on each side, with `enable_order_filled_stop_cancellation` and `best_bid_ask_jump_mode` set to `false`. The instance started with 1.1 GB of RAM usage.

![image](https://user-images.githubusercontent.com/50150287/71711819-ae471c00-2e3d-11ea-91e9-698e4414898c.png)

After running for 4 hours, I'm not getting a drastic increase in usage.

![image](https://user-images.githubusercontent.com/50150287/71711912-ff571000-2e3d-11ea-892c-e3317a6880fd.png)

**Comment by veecos2** [comment]
@bb111189 : Did you use default settings for all the other configuration variables or did you change any of them ?. We seem to be unable to replicate this.

**Comment by bb111189** [comment]
[hummingbot-zilusdt_files.zip](https://github.com/CoinAlpha/hummingbot/files/4022270/hummingbot-zilusdt_files.zip)

Managed to salvage the log files and config file

**Comment by veecos2** [comment]
@bb111189 : You had attached log configurations and not the actual log file. Could you recheck to see if you have original logs ?. @dennisocana : Can you check if you can replicate with this configuration ?.

**Comment by veecos2** [comment]
From what I can see, this error was caused due to hitting the 
API rate limit (http 429). Investigating further.

**Comment by dennisocana** [comment]
@bb111189 Just a random thought: do you have another Hummingbot instance on Binance running on the same server/machine?

**Comment by bb111189** [comment]
Yes. It is the same instance. I have another bot running. Similar setup with another pair. However, both bot is running under different binance sub-account

**Comment by dennisocana** [comment]
@bb111189 we recommend not to have more than one instance using Binance connector running on the same server especially if on multiple order mode. Otherwise, your IP will hit the Binance IP limit. When we do our testing, we make sure only one instance is running on Binance per server.

The limits on the API are based on the IPs, not the API keys. See [Binance API Limits](https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#ip-limits) for more information.

This may be the root cause of the issue based on your logs.

1. Binance sends `APIError(code=-1003)` because of too many requests from your IP.
2. Then will get disconnected from Binance market from time to time `Network status has changed to NetworkStatus.NOT_CONNECTED. Stopping networking...`
3. Hummingbot tries to recover and pick up where it left off attempting to cancel the orders.
4. If unsuccessful, it continues to do this over and over spamming the API which will result to `HTTP status is 418` when attempting to get snapshots of the market.
5. The strategy doesn't automatically stop so it continues to attempt generating order proposals per second (similar behavior to https://github.com/CoinAlpha/hummingbot/issues/1140) therefore flooding the logs with errors and the software eventually crashing the instance.

**Comment by bb111189** [comment]
Yep, this seems the logical flow of the event to me. 

Was previously confused by the IP limit due to 
```
API users will be pleased to know that each sub-account will have its own set of API limits, enabling them to trade with more freedom and at a higher capacity.
```
https://medium.com/binanceexchange/binance-introduces-sub-account-support-d7bf2f95e28c

But I guess that will be on the Binance plate to clarify the limit. 

I guess this should be a non-issue then. Just one more thing, will Hummingbot team consider to implement some mechanism like exponential backoff for binance connector to avoid spamming the API
```
When a 429 is received, it's your obligation as an API to back off and not spam the API.
```

**Comment by veecos2** [comment]
@bb111189 : Yes we will definitely consider. Please raise a feature request for the same, through going to issues and selecting new feature request.

**Comment by dennisocana** [comment]
@bb111189 their limitation on API trading through the endpoint https://api.binance.com/api/v3/exchangeInfo indicates the request weight limit of 1,200 per minute. And 10 orders per second or 200,000 in a day.

Exceeding the 1,200 requests per minute will result in an IP ban. And the order limits are depending on the account. I assume instead of two sub-accounts sharing the same API limit on orders, it is applicable to each sub-account.

```
"timezone": "UTC",
"serverTime": 1578374813914,
"rateLimits": [
    {
        "rateLimitType": "REQUEST_WEIGHT",
        "interval": "MINUTE",
        "intervalNum": 1,
        "limit": 1200
    },
    {
        "rateLimitType": "ORDERS",
        "interval": "SECOND",
        "intervalNum": 10,
        "limit": 100
    },
    {
        "rateLimitType": "ORDERS",
        "interval": "DAY",
        "intervalNum": 1,
        "limit": 200000
    }
```
