### ISSUE TITLE
[BUG]Autostart not working when using DEX market

### ISSUE THREAD

**Issue by Clint-G13** [CoinAlpha/hummingbot#1250]
**Describe the bug**
// I was running the autostart script to initiate a strategy automatically. Using a centralized market, you won't face an issue however once a DEX market is used even if the wallet is added, the strategy won't automatically start. `Start` command is required to be entered and will result in an unknown error.

**Steps To Reproduce**
// Here are the steps to reproduce the issue (see attachments in the section below):
1. Create a new strategy file, example would be Pure market-making and use any decentralize market.
2. Exit bot
3. Start strategy using Autostart command (Source)
bin/hummingbot_quickstart.py \
--strategy ${STRATEGY} \
--config-file-name ${CONFIG_FILENAME} \
--config-password ${CONFIG-PASSWORD}
--wallet ${WALLET} \
4. Type `start` since strategy won't automatically start (`config` command is needed to unlock wallet when running discovery).

          2019-12-28 06:08:24,453 - 13764 - hummingbot.client.hummingbot_application - ERROR - 
          Unknown error during initialization.
          Traceback (most recent call last):
           File "/home/clinton_gogoc/hummingbot/hummingbot/strategy/pure_market_making/start.py", line 79, 
          in start
          self._initialize_markets(market_names)
          File "/home/clinton_gogoc/hummingbot/hummingbot/client/hummingbot_application.py", line 301, in _initialize_markets
           assert self.wallet is not None
           AssertionError
          2019-12-28 06:09:35,249 - 13764 - root - ERROR - Unhandled error in background task: 
          list.remove(x): x not in list
         Traceback (most recent call last):
          File "/home/clinton_gogoc/hummingbot/hummingbot/core/utils/async_utils.py", line 8, in 
          safe_wrapper
         return await c
        File "/home/clinton_gogoc/hummingbot/hummingbot/client/command/stop_command.py", 
        line 32, in stop_loop
         self.clock.remove_iterator(self.strategy)
       File "hummingbot/core/clock.pyx", line 83, in hummingbot.core.clock.Clock.remove_iterator
        self._child_iterators.remove(iterator)
        ValueError: list.remove(x): x not in list
       2019-12-28 06:09:38,621 - 13764 - hummingbot.data_feed.coin_gecko_data_feed - WARNING - 
      Coin Gecko API request failed. Unable to get prices.

**Screenshots**
// 
![Autostart](https://user-images.githubusercontent.com/57189990/71534321-0ad7a200-2939-11ea-8958-cc020abf5df1.PNG)
![Autostart1](https://user-images.githubusercontent.com/57189990/71534334-1fb43580-2939-11ea-86c6-da2b73839b3f.PNG)
![Autostart2](https://user-images.githubusercontent.com/57189990/71534348-38245000-2939-11ea-93da-0f0314419b9f.PNG)

**Release version**
// 

      commit 7fa2cc1b6de3b5ee7147b63afdb27b25d4e8a4de 
      environment: via source
      Date:   Fri Dec 27, 2019

**Attachments**
// 
[logs_conf_pure_market_making_strategy_1.log](https://github.com/CoinAlpha/hummingbot/files/4006367/logs_conf_pure_market_making_strategy_1.log)
[conf_pure_market_making_strategy_1.txt](https://github.com/CoinAlpha/hummingbot/files/4006370/conf_pure_market_making_strategy_1.txt)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**
**Optional: your ETH address:** (If you want to participate in the bug bounty)

**Comment by veecos2** [comment]
Hi Clinton, I think you need to configure the wallet first before you can run the quickstart with it. Can you recheck configuring it ?.
