### ISSUE TITLE
[BUG] Bamboo-Relay Discovery Strategy unable to show profitability

### ISSUE THREAD

**Issue by Hashira-Lars** [CoinAlpha/hummingbot#1254]
**Describe the bug**
// Discovery strategy any exchange pair  with  `bamboo-relay` will unable to show profitability

bamboo - ddex = unable to show profitability
bamboo - radar = unable to show profitability
bamboo - bittrex = unable to show profitability
bamboo - binance = unable to show profitability
bamboo - coinbase = unable to show profitability
bamboo - huobi = unable to show profitability
bamboo - liquid = unable to show profitability
bamboo- bitcoin = unable to show profitability
bamboo - idex = skip known bug
bamboo - dolomite = skip known bug

**Steps To Reproduce**
1.Create Discovery Strategy 
2.Select `Enter your first exchange name >>> Bamboo-Relay`
3.Finish Configuration
4.Enter start 

**Release version**
0.21.0

**Attachments**

sample logs/bamboo-relay-bitcoin/default parameters
[x] [logs_conf_discovery_strategy_0.log](https://github.com/CoinAlpha/hummingbot/files/4006914/logs_conf_discovery_strategy_0.log)

one of the error in the log files 
```
Traceback (most recent call last):
  File "/hummingbot/market/bamboo_relay/bamboo_relay_api_order_book_data_source.py", line 291, in listen_for_order_book_snapshots
    snapshot: Dict[str, any] = await self.get_snapshot(client, trading_pair, self._api_endpoint, self._api_prefix)
  File "/hummingbot/market/bamboo_relay/bamboo_relay_api_order_book_data_source.py", line 156, in get_snapshot
    raise IOError(f"Error fetching Bamboo Relay market snapshot for {trading_pair}. "
OSError: Error fetching Bamboo Relay market snapshot for NEXXO-WETH. HTTP status is 404.
```

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**
**Optional: your ETH address:** (If you want to participate in the bug bounty)

**Comment by Hashira-Lars** [comment]
tagging @Arctek

**Comment by PtrckM** [comment]
**fix confirmed**

```
                "branch": "development",
                "commit": "38ceaf9995d7a37c49c4734b0c95e0e27f2a9632",
                "date": "2019-12-29T15:16:11Z",
```

**Comment by Hashira-Lars** [comment]
CONFIRM FIX tested with all pairs except with known issues using the latest dev image. as Joshua said it was a server side problem with bamboo not in HB.
