### ISSUE TITLE
[BUG] Scroll bars are not working on Windows 10

### ISSUE THREAD

**Issue by Nullably** [CoinAlpha/hummingbot#1259]
**Describe the bug**
Scroll bars are not working on Windows 10 on all panels.

**Steps To Reproduce**
- Fill in the screen with commands
- Start a strategy, e.g. Pure Market Making.
- Scroll bars appear but clicking on them doesn't scroll.

**Screenshots**
![image](https://user-images.githubusercontent.com/37262506/71618910-ced46380-2bfc-11ea-8a38-91c5c6cd0894.png)

**Release version**
0.21.0 
Also happens on development branch.

**Comment by rennel-tabing** [comment]
I am able to reproduce this issue. This is only applicable for "Windows Binary Installation".

**Comment by Hashira-Lars** [comment]
User also reported using putty. docker linux installation. Cannot be drag via scroll bar but can be use when using mouse scroll bar.

**Comment by Hashira-Lars** [comment]
I have reproduce this behavior using docker windows installation method. I can scroll using the `mouse scroll bar` but cannot scroll by dragging the `scroll bar`.

**Comment by Nullably** [comment]
I have researched into this, I think `prompt_toolkit` scroll bars are simply just not working  on Windows at the moment. Many of their examples on Github also have the same issue, scroll bars appear but not responsive to mouse at all (neither clicking or wheeling), e.g. https://github.com/prompt-toolkit/python-prompt-toolkit/blob/2.0.2/examples/full-screen/text-editor.py
