### ISSUE TITLE
[BUG] [Windows] Windows Time calculation is inaccurate which leads to nonce issues which leads to orders not being tracked properly

### ISSUE THREAD

**Issue by Nullably** [CoinAlpha/hummingbot#1261]
**Describe the bug**
Hummingbot keeps on issuing maker orders non stop on Binance pure market making strategy, multiple orders mode. Numbers of open orders reached over 50 in a few minutes. Stop command cancels just one order, left the rest open on the exchange.
I found this bug while investigating another issue #1247 , not sure if they are related, will investigate further.

Here are the steps to reproduce the issue (see attachments in the section below):
Starting balance: 
ETH: 1
LINK: 0

Configure the bot as followings:
```
maker_market: binance
primary_market_trading_pair: LINKETH
mode: multiple
cancel_order_wait_time: 20.0
number_of_orders: 5
order_start_size: 1.0
```
The rest of configs are set to default
Start the bot

**Screenshots**
![image](https://user-images.githubusercontent.com/37262506/71641016-e0d30680-2ccf-11ea-8e74-3352975d8743.png)

Open orders on Binance reached over 50 within a few minutes.
![image](https://user-images.githubusercontent.com/37262506/71641030-124bd200-2cd0-11ea-9cde-edcf93d3cd14.png)

**Release version**
0.21.0
Same problem on Development branch

**Optional: your discord username: Jack | Coinalpha

**Comment by Nullably** [comment]
Here is the log file.
[logs_conf_pure_market_making_strategy_8.log](https://github.com/CoinAlpha/hummingbot/files/4017888/logs_conf_pure_market_making_strategy_8.log)

**Comment by Nullably** [comment]
What happened is the `tracking_nonce used` for `order_id` returns the same value for multiple orders issued almost simultaneously. If this bug is not present on other system, it might be a Windows thing where time.time() is returned within a micro (or lower) second precision.

Once I added a function to check for duplicates as below, the problem solved.
```
cdef int64_t c_last_tracing_nonce(self):
        cdef int64_t tracking_nonce = <int64_t>(time.time() * 1e6)
        self._last_tracking_nonce = tracking_nonce if tracking_nonce > self._last_tracking_nonce else \
            self._last_tracking_nonce + 1
        return self._last_tracking_nonce
```

**Comment by dennisocana** [comment]
@veecos2 confirmed that this happens on Hummingbot installed via binary but not when running in Linux cloud server. Here's a recording of the behavior in Windows.

[multiple_windows_bug.zip](https://github.com/CoinAlpha/hummingbot/files/4017935/multiple_windows_bug.zip)
[logs_conf_pmm_oneusdc.log](https://github.com/CoinAlpha/hummingbot/files/4017936/logs_conf_pmm_oneusdc.log)

I have multiple orders configured to place 5 orders per side.

**Comment by veecos2** [comment]
@Nullably : I don't have any issues on Mac either. On further reading I see that this time implementation in Windows: https://stackoverflow.com/questions/1938048/high-precision-clock-in-python. Can you check some of the workarounds mentioned in the thread ?.

**Comment by Nullably** [comment]
@veecos2 I think the most acceptable/applicable from that thread is to use time.time_ns() from Python 3.7 but we are still on Python 3.6, right?

What do you think about my approach of storing last_tracking_nonce used and just add one if it is duplicate?

**Comment by Nullably** [comment]
@martinkou 
The problem is time.time() on Windows returns time precision within about a millisecond, which is not good enough for our tracking_nonce calculation.

I propose a change to `market_base.py` by adding `cdef int64_t c_tracking_nonce(self)`, which then can be used later by derived classes, e.g. `binance_market.py` to get `tracking_nonce`. `c_tracking_nonce` will make sure the value of at least 1 greater than the last `tracking_nonce`. 

The problem is we likely need to apply this change to all market connectors. 

Another solution (that @veecos2  found) is to use time.time_ns() which only supported on Python 3.7 onward, time_ns() returns are at nano second precision.

**Comment by martinkou** [comment]
Then we should investigate moving to Python 3.7 and using `time.time_ns()` instead. The Windows `time.time()` has a 16ms resolution, which is way too bad for us.

**Comment by martinkou** [comment]
I'm on it. Having some success porting hummingbot to Python 3.8 on Windows this weekend.

**Comment by martinkou** [comment]
Tested the `time.time_ns()` function in Python 3.8 today. It didn't help with timestamp resolution - it's simply multiplying the timestamp by 1e9.

The better solution to this seems to be using a counter-assisted nonce function instead - which @Nullably has proposed.

Handing this back to @Nullably.

**Comment by Nullably** [comment]
merged.
