### ISSUE TITLE
[BUG] Generic trading pair syntax broken

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#1264]
**Describe the bug**

The feature to use generic trading pair syntax we used to have which was in PR https://github.com/CoinAlpha/hummingbot/pull/1000 is broken. When creating a new strategy or configuring a trading pair, it reverted back to the old syntax depending on the connector.

This happens on master branch version 0.21.0 and dev-0.22.0

<img width="947" alt="putty_qfShX0MZLa" src="https://user-images.githubusercontent.com/50150287/71651058-ad3abf80-2d55-11ea-8f0e-3fa2ba7c90c8.png">
<img width="947" alt="putty_venBv5yyh4" src="https://user-images.githubusercontent.com/50150287/71651061-b2980a00-2d55-11ea-957e-22a05a0aa555.png">

**Release version**

```
"branch": "master",
"commit": "a8070e3369d9273ddb29e7d9e505987ad8fa1b46",
"date": "2019-12-30T21:27:45Z",
```

```
"branch": "development",
"commit": "7f73abc040c894e6e87fdd887b5bc508bd6a910b",
"date": "2020-01-01T04:58:19Z",
```

**Comment by Hashira-Lars** [comment]
Tested with the most latest dev image merge with PR #1297 - CONFIRM FIX

![image](https://user-images.githubusercontent.com/55869559/72121456-09c15e80-3396-11ea-975d-d54baaf651ff.png)

![image](https://user-images.githubusercontent.com/55869559/72121463-0f1ea900-3396-11ea-9427-edec7eb81dd5.png)
