### ISSUE TITLE
[BUG] Bamboo Relay, Incorrect warning message for expired orders

### ISSUE THREAD

**Issue by chowryan** [CoinAlpha/hummingbot#1276]
**Describe the bug**
// A clear and concise description of what the bug is.
Seems like instead of stating that an order has expired, hummingbot thinks that an "order can't be found".
**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:
Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up PMM strategy on Bamboo Relay with any params in non-coordinator mode.
2. wait for orders to expire to see the incorrect message
...

**Screenshots**
// If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/26056161/71745035-e50d3a00-2e1d-11ea-821b-720e842eb4ca.png)

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).
dev-0.22.0
**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**
**Optional: your ETH address:** (If you want to participate in the bug bounty)

@Arctek

**Comment by Arctek** [comment]
Do you have the full logs?

I just checked my server logs and can see:
`[2020-01-03 20:06:26, 1578081986.488] Sell 0.1@134.90651 WETH/DAI by 0x6502981bdd36bbbee79cbd71db1cf2c52a2a187c via mesh in 38ms
[2020-01-03 20:06:26, 1578081986.639] Validation error occurred during mesh creation: OrderUnfunded`

At the moment hummingbot orders bypass waiting for the mesh validation - but I'll change this, given this means hummingbot thinks the limit order was created successfully (but can't find it subsequently).
So this is not an expiry message, and is actually correct for what's happening - order not found after submission.

Looking at your WETH balance on etherscan it is indeed un/underfunded - so it looks like the hummingbot WETH balance state is out of sync here for some reason?

**Comment by chowryan** [comment]
ill try to find the logs. this seems like it might be a hummingbot issue. thanks for the info!

**Comment by Arctek** [comment]
Looking at the history on etherscan it looks like some custom smart contract/aggregator picked up a few orders and filled them.

Might need to check the full logs - but Bamboo should have issued a filled notification for those orders, which should in theory trigger a balance re-check?

So either the Bamboo API never issued a correct filled event here, or hummingbot isn't re-checking the available balance after an order fill (on the web3 wallet backend)?

**Comment by Arctek** [comment]
This may (or may not be) have been fixed by my other PR that got merged #1271

If the wallet backend ever had start called again for a second time, then the watcher event listeners weren't being re-attached correctly.

This could likely explain how the balances ended up out of sync - assuming there isn't a further issue on top of this.
