### ISSUE TITLE
[BUG] Hummingbot keeps fetching status of non-existing orders in client

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#1281]
**Describe the bug**

Even after restarting, Hummingbot gets flooded with errors because it keeps fetching the status of previous orders that are no longer in the client nor in the exchange.

```
hummingbot.market.coinbase_pro.coinbase_pro_market - NETWORK - Error fetching status update for the order buy-LINK-ETH-1575680534001444: None.
hummingbot.market.coinbase_pro.coinbase_pro_market - WARNING - Could not fetch updates for the order buy-LINK-ETH-1575680534001444. Check API key and network connection.
hummingbot.market.coinbase_pro.coinbase_pro_market - NETWORK - Error fetching status update for the order sell-LINK-ETH-1575680534001835: None.
hummingbot.market.coinbase_pro.coinbase_pro_market - WARNING - Could not fetch updates for the order sell-LINK-ETH-1575680534001835. Check API key and network connection.
hummingbot.market.coinbase_pro.coinbase_pro_market - NETWORK - Error fetching status update for the order sell-LINK-ETH-1575680534001893: None.
hummingbot.market.coinbase_pro.coinbase_pro_market - WARNING - Could not fetch updates for the order sell-LINK-ETH-1575680534001893. Check API key and network connection.
```

![image](https://user-images.githubusercontent.com/50150287/71774570-84f8ce00-2fac-11ea-8a50-5aad7dbe5dd6.png)

Using the order ID, I confirmed that these are previous orders stored in the local database.

![image](https://user-images.githubusercontent.com/50150287/71774577-b5406c80-2fac-11ea-98f4-8abf24d42e98.png)
![image](https://user-images.githubusercontent.com/50150287/71774579-b96c8a00-2fac-11ea-999d-36d5517c03a0.png)
![image](https://user-images.githubusercontent.com/50150287/71774580-bb364d80-2fac-11ea-9560-5e7ad33dc7aa.png)

Another effect of this behavior is it thinks the orders are outstanding and you will get a warning when you try to `stop` or `exit` from Hummingbot.

![image](https://user-images.githubusercontent.com/50150287/71774637-a4dcc180-2fad-11ea-9271-b7ea0d81c358.png)
![image](https://user-images.githubusercontent.com/50150287/71774641-a7d7b200-2fad-11ea-9598-5215750bb662.png)

The workaround is to delete the SQLite file in the data folder. Will continue to monitor to see if this is just a one-off or if it will reoccur.

**Release version**

```
"branch": "master",
"commit": "a8070e3369d9273ddb29e7d9e505987ad8fa1b46",
"date": "2019-12-30T21:27:45Z",
```

**Attachments**

Database file and logs are in zip file below.
[database_logs.zip](https://github.com/CoinAlpha/hummingbot/files/4022877/database_logs.zip)

**Comment by dennisocana** [comment]
I just ran into this bug while using Liquid connector.

**Comment by yzhang1994** [comment]
@dennisocana Have you ever seen this error with Binance? This could be serious if the bug is in hummingbot.

**Comment by dennisocana** [comment]
@yzhang1994 I haven't seen this yet in Binance. I will continue monitoring and post updates here when I find one. I will also let you know directly right away.

**Comment by dennisocana** [comment]
@yzhang1994 I just ran into this again but on IDEX connector. I couldn't retrieve the logs as it is 3.5GB in size just for running 24 hours.

<img width="674" alt="putty_jgOKISoDsO" src="https://user-images.githubusercontent.com/50150287/72032361-1a0c0780-32ca-11ea-9263-2d06477dcdc2.png">

**Comment by dennisocana** [comment]
Exited Hummingbot --> Deleted the huge log file --> Restart
You will see in the logs it's trying to fetch data of previous orders.
[logs_conf_pmm_qnt-eth.log](https://github.com/CoinAlpha/hummingbot/files/4038286/logs_conf_pmm_qnt-eth.log)

**Comment by zeitgeistf** [comment]
@dennisocana were you able to reproduce with Liquid connector?

**Comment by dennisocana** [comment]
@zeitgeistf yes, I ran into this issue in Liquid connector but did not get the logs. Will send you the files when I encounter this again.

**Comment by Nullably** [comment]
@dennisocana Can I please get steps on how to produce this?
Is it something that happens after running the bot for a long while?

**Comment by dennisocana** [comment]
@Nullably yes, it happens after running the bot for a while. I couldn't find what exactly triggers it - I just run a bot. It doesn't happen all the time.

**Comment by Nullably** [comment]
@dennisocana Can I have your strategy config file for this please?

**Comment by dennisocana** [comment]
@Nullably sent the configs over Discord.

**Comment by dennisocana** [comment]
We ran into this error again just now. If you look at the logs you will see that it's running fine for almost 18 hours from 2020-01-14 06:58 to 2020-01-15 00:38 then an order will eventually get an error when attempting to cancel.
```
2020-01-15 00:37:10,904 - 11 - hummingbot.market.coinbase_pro.coinbase_pro_market - NETWORK - Failed to cancel order sell-LINK-ETH-1579048580002424: 
Traceback (most recent call last):
  File "coinbase_pro_market.pyx", line 829, in hummingbot.market.coinbase_pro.coinbase_pro_market.CoinbaseProMarket.execute_cancel
  File "coinbase_pro_market.pyx", line 344, in _api_request
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/aiohttp/client.py", line 504, in _request
    await resp.start(conn)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 860, in start
    self._continue = None
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/aiohttp/helpers.py", line 586, in __exit__
    raise asyncio.TimeoutError from None
concurrent.futures._base.TimeoutError
```
And then you will always get this error because Hummingbot will keep looking for that order.
```
2020-01-15 00:38:01,074 - 11 - root - ERROR - Unhandled error in background task: 'OSError' object has no attribute 'message'
Traceback (most recent call last):
  File "coinbase_pro_market.pyx", line 829, in hummingbot.market.coinbase_pro.coinbase_pro_market.CoinbaseProMarket.execute_cancel
  File "coinbase_pro_market.pyx", line 344, in _api_request
  File "coinbase_pro_market.pyx", line 348, in hummingbot.market.coinbase_pro.coinbase_pro_market.CoinbaseProMarket._api_request
OSError: Error fetching data from https://api.pro.coinbase.com/orders/409eddce-2c66-4a9e-a84b-cf9cecadf69f. HTTP status is 404. {'message': 'order not found'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/hummingbot/core/utils/async_utils.py", line 8, in safe_wrapper
    return await c
  File "coinbase_pro_market.pyx", line 837, in execute_cancel
AttributeError: 'OSError' object has no attribute 'message'
```
My guess is when it received the first error "Failed to cancel order x" it actually cancelled. But Hummingbot thinks it did not so it keeps trying to call to fetch updates or cancel it but the order can no longer be found.

Here's the log file of when it started to happen.

[start_of_error.log](https://github.com/CoinAlpha/hummingbot/files/4063855/start_of_error.log)

**Comment by yzhang1994** [comment]
@dennisocana We merged a fix to this. Please check if this is happening again. Thanks

**Comment by dennisocana** [comment]
So far I haven't encountered this bug again after the fix was merged.
