### ISSUE TITLE
[BUG] Incorrect wallet balance

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#1282]
**Describe the bug**

This is my available wallet balance in Metamask.

![image](https://user-images.githubusercontent.com/50150287/71776230-e038b980-2fc8-11ea-928c-7fbe9e16ecb4.png)

In Hummingbot it says I have 0 DAI and WETH balance is not the same as what I have.

![image](https://user-images.githubusercontent.com/50150287/71776241-2130ce00-2fc9-11ea-98da-81c849f8a40a.png)

Confirmed that this is not specific to a connector since it also happens on Radar Relay and DDEX.

![image](https://user-images.githubusercontent.com/50150287/71780306-dbd9c400-2ffb-11ea-97c6-d0c045d6db79.png)
![image](https://user-images.githubusercontent.com/50150287/71780301-c4024000-2ffb-11ea-88a9-85ea4d8ef869.png)

I made sure I am using the same wallet address. The order I'm seeing on the exchange also confirms it.

![image](https://user-images.githubusercontent.com/50150287/71776251-39085200-2fc9-11ea-8e75-6bb6ad9f72ca.png)

**Release version**

This happens on both master and development branch.

```
"branch": "development",
"commit": "54a4441558d868f0466ccbea62ce8989caba61f2",
"date": "2020-01-04T06:43:32Z",
```

**Attachments**

[logs_pmm_bamboo_weth-dai.log](https://github.com/CoinAlpha/hummingbot/files/4022951/logs_pmm_bamboo_weth-dai.log)

**Comment by rennel-tabing** [comment]
tested using the same dev version and unable to reproduce this behavior.

![image](https://user-images.githubusercontent.com/53868268/71815347-2899bb00-304d-11ea-81f7-acc4e8a73f03.png)

**Comment by Hashira-Lars** [comment]
Tested and got a different behavior HB is showing a balance in `WETH` even though i don't have. 

![image](https://user-images.githubusercontent.com/55869559/71858049-b98f9580-3124-11ea-8f3c-831c2f88625e.png)


![image](https://user-images.githubusercontent.com/55869559/71858056-c01e0d00-3124-11ea-850e-49cd390a6771.png)


![image](https://user-images.githubusercontent.com/55869559/71858067-cad8a200-3124-11ea-80f6-4aaaa70eb6f1.png)

**Comment by MishaelTereso** [comment]
**Metamask wallet**
![image](https://user-images.githubusercontent.com/56957119/71879308-c33aec80-3168-11ea-9aeb-743835e26355.png)


Tested using ``dev branch``  and was able to reproduced the issue.

![image](https://user-images.githubusercontent.com/56957119/71878980-f16bfc80-3167-11ea-9a9c-35594f96f11a.png)
![image](https://user-images.githubusercontent.com/56957119/71879034-1496ac00-3168-11ea-92d1-5005e3ecc474.png)

**Comment by dennisocana** [comment]
When I try to change wallets let's say from 0xC20a... to 0xE973... it fails to start. Because it thinks I have 0 balance in the new wallet?
```
2020-01-07 01:48:45,047 - 10 - hummingbot.wallet.ethereum.web3_wallet_backend - NETWORK - Error sending transaction 0x12cf426423de3ce802fea3c98b1c2a8e52977200d0cffa1ef767f14cb31ead31.
Traceback (most recent call last):
  File "/hummingbot/wallet/ethereum/web3_wallet_backend.py", line 410, in outgoing_eth_transactions_loop
    await async_scheduler.call_async(self._w3.eth.sendRawTransaction, signed_transaction.rawTransaction)
  File "/hummingbot/core/utils/async_call_scheduler.py", line 128, in call_async
    return await self.schedule_async_call(coro, timeout_seconds, app_warning_msg=app_warning_msg)
  File "/hummingbot/core/utils/async_call_scheduler.py", line 117, in schedule_async_call
    return await fut
  File "/hummingbot/core/utils/async_call_scheduler.py", line 80, in _coro_scheduler
    fut.set_result(await coro)
  File "/opt/conda/envs/hummingbot/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/web3/eth.py", line 274, in sendRawTransaction
    [raw_transaction],
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/web3/manager.py", line 112, in request_blocking
    raise ValueError(response["error"])
ValueError: {'code': -32010, 'message': 'Insufficient funds. The account you tried to send transaction from does not have enough funds. Required 1543710000000000 and got: 0.'}
```
This is my actual balance in metamask.
![image](https://user-images.githubusercontent.com/50150287/72119054-180b7c80-338e-11ea-9824-b1bd70f45605.png)
Here's the log file. I added a comment between I was using the old wallet and the new one.
[logs_pmm_bamboo_weth-dai.log](https://github.com/CoinAlpha/hummingbot/files/4043530/logs_pmm_bamboo_weth-dai.log)

**Comment by znerol19619** [comment]
Encountered this in Bittrex exchange 

![btrrx-hb-bal](https://user-images.githubusercontent.com/27669951/72426086-0da11680-37c4-11ea-8ace-3f3412b8feb5.png)
![btrrx-bal](https://user-images.githubusercontent.com/27669951/72426095-11349d80-37c4-11ea-9cc7-039bf6052adc.png)

and got this error as well.
```
2020-01-13 10:25:04,489 - 10 - hummingbot.market.bittrex.bittrex_market - NETWORK - Error submitting buy LIMIT order to Bittrex for 1.66905059 XZC-BTC 0.00044744.
Traceback (most recent call last):
  File "bittrex_market.pyx", line 779, in hummingbot.market.bittrex.bittrex_market.BittrexMarket.execute_buy
  File "bittrex_market.pyx", line 739, in place_order
  File "bittrex_market.pyx", line 1034, in _api_request
  File "bittrex_market.pyx", line 1042, in hummingbot.market.bittrex.bittrex_market.BittrexMarket._api_request
OSError: Error fetching response from POST-https://api.bittrex.com/v3/orders. HTTP Status Code 409: {'code': 'INSUFFICIENT_FUNDS'}
```

**Comment by dennisocana** [comment]
Switching the `ethereum_rpc_url` from CoinAlpha node to Infura node worked and balance is now showing correctly.

![image](https://user-images.githubusercontent.com/50150287/73650875-25cace00-46be-11ea-8023-ec453bf1c85d.png)

Then switching it back to CoinAlpha node showed the incorrect balance again.

**Comment by dennisocana** [comment]
Confirmed that the problem is caused by the node that I was using. Will use Infura going forward.
