### ISSUE TITLE
[BUG] Running Pure MM with zero balance results in unexpected errors when inventory skew is enabled

### ISSUE THREAD

**Issue by Nullably** [CoinAlpha/hummingbot#1292]
**Describe the bug**
Running Pure MM when no balance on neither base nor quote asset results in many unexpected errors.

Here are the steps to reproduce the issue (see attachments in the section below):
1. Configure the bot as attached config file
2. Make sure to enable inventory_skew_enabled
2. Having zero balances on both base and quote assets on the exchange

**Screenshots**
![image](https://user-images.githubusercontent.com/37262506/71945224-37c16a00-3201-11ea-9d13-b9565ce2e87c.png)

**Release version**
0.21.0 
development

**Attachments**

[conf_pure_market_making_strategy_10.txt](https://github.com/CoinAlpha/hummingbot/files/4033361/conf_pure_market_making_strategy_10.txt)

[logs_conf_pure_market_making_strategy_10.log](https://github.com/CoinAlpha/hummingbot/files/4033353/logs_conf_pure_market_making_strategy_10.log)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**
**Optional: your ETH address:** (If you want to participate in the bug bounty)

**Comment by znerol19619** [comment]
Tested on development branch, and it does the same behavior. 
Error when there's no balance on quote/base and inventory skew is enabled.

**Release version**
```
                "branch": "development",
                "commit": "860157b7b07fe80fcd0efe97b50b71a4bb1cc86d",
                "date": "2020-01-07T19:11:40Z",

```

**Comment by chowryan** [comment]
this should be fixed now
