### ISSUE TITLE
[BUG] Orders get stuck in client but not in Liquid

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#1295]
**Describe the bug**

I'm running pure market making strategy with multiple orders on Liquid connector. If you keep the bot running long enough, a set of orders will eventually get stuck in Hummingbot but you will see that those orders do not exist in the exchange.

[liquid_stuck_orders.log](https://github.com/CoinAlpha/hummingbot/files/4040147/liquid_stuck_orders.log)

![image](https://user-images.githubusercontent.com/50150287/72063932-c3c4b600-3315-11ea-8675-f5bd43cdefc9.png)
![image](https://user-images.githubusercontent.com/50150287/72064016-efe03700-3315-11ea-8e68-43e7336713e6.png)

```
cancel_order_wait_time: 30.0
bid_place_threshold: 0.0001
ask_place_threshold: 0.0001
mode: multiple
number_of_orders: 2
order_start_size: 50.0
order_step_size: 0.0
order_interval_percent: 0.0003
inventory_skew_enabled: true
inventory_target_base_percent: 0.5
filled_order_replenish_wait_time: 10.0
```

The rest of the advanced parameters are set to `false` value.

**Release version**

```
"branch": "development",
"commit": "860157b7b07fe80fcd0efe97b50b71a4bb1cc86d",
"date": "2020-01-07T19:11:40Z",
```

**Comment by dennisocana** [comment]
I ran into this bug again. There is an order stuck in Hummingbot that is not in Liquid. This stops new orders from being created.

[liquid_stuck_order.log](https://github.com/CoinAlpha/hummingbot/files/4210269/liquid_stuck_order.log)

![image](https://user-images.githubusercontent.com/50150287/74608801-28e2a700-511f-11ea-9704-9c149b277205.png)

![image](https://user-images.githubusercontent.com/50150287/74608785-11a3b980-511f-11ea-8f93-ff4896d2e013.png)

**Comment by martinkou** [comment]
@Nullably @yzhang1994 we discussed this during Asia standup yesterday. Seems important to get it fixed before the Liquid program rollout.

**Comment by Nullably** [comment]
@dennisocana Can you please run the bot from this branch https://github.com/CoinAlpha/hummingbot/tree/fix/liquid_order_stuck
And please send me the log & config files when the error happens.
Thanks.

**Comment by dennisocana** [comment]
Been running a long-term bot in Liquid and no longer experiencing this issue since version 0.26.0

**Comment by dennisocana** [comment]
Ran into this issue again just when the issue was closed.

![image](https://user-images.githubusercontent.com/50150287/84338305-48ba4100-abce-11ea-807e-5d6b10ecbb3b.png)
[logs_liquid_qash-eth.log](https://github.com/CoinAlpha/hummingbot/files/4762214/logs_liquid_qash-eth.log)

As discussed during Asia standup we'll keep this issue opened and gather more data from testing and users.
