### ISSUE TITLE
[BUG] Error exporting trades in Windows

### ISSUE THREAD

**Issue by Hashira-Lars** [CoinAlpha/hummingbot#1302]
**Describe the bug**
// export_trades does not recognize the default path in binary windows , a work around would be defining the `path --path=FILE_PATH_TO_LOGS+FILE_NAME_YOU_WANT_TO_SAVE_THE_TRADES`

- Re-tested in new latest master image 0.22.0
 - issue still persist

**Steps To Reproduce**
1. Download/Install Binary Windows
2. Open binary windows , setup a bot 
3. Run the bot , wait for trades
4. Execute Command `export_trades`
5. Error will show

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/55869559/72200885-913bca00-3489-11ea-930c-6256298e75fc.png)

![image](https://user-images.githubusercontent.com/55869559/72313000-db5cbf80-36c4-11ea-86a0-b50ddcc62170.png)

**Release version**
 Master /0.21.0/0.22.0

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:** Lars l Support
**Optional: your ETH address:** (If you want to participate in the bug bounty)

**Comment by PtrckM** [comment]
![image](https://user-images.githubusercontent.com/54516858/72213088-c563c900-3523-11ea-925f-3675d3b7465f.png)
![image](https://user-images.githubusercontent.com/54516858/72213090-c7c62300-3523-11ea-867d-90a2fdd45448.png)

**Comment by Nullably** [comment]
I have submitted a PR https://github.com/CoinAlpha/hummingbot/pull/1319 
to address this issue, please test and let me know.

**Comment by Hashira-Lars** [comment]
Thanks , im testing it right now , waiting for trades to happen

**Comment by PtrckM** [comment]
![image](https://user-images.githubusercontent.com/54516858/72692542-75aa8080-3b67-11ea-8485-e411e5ad6cd2.png)

**Comment by Hashira-Lars** [comment]
Tested in latest master branch released - Confirm Fix

HB
![image](https://user-images.githubusercontent.com/55869559/73709352-cad7bc00-473b-11ea-9998-4f90729f8095.png)

Logs file
![image](https://user-images.githubusercontent.com/55869559/73709375-dcb95f00-473b-11ea-97ef-e49a8c4f98c6.png)
