### ISSUE TITLE
OrderBookTracker trade execution bug

### ISSUE THREAD

**Issue by majd1239** [CoinAlpha/hummingbot#1330]
While reading over the code, I noticed a small logic bug in `order_book_tracker.py` when fetching trade messages and sending the trade event to be logged.

In line 276-277: https://github.com/CoinAlpha/hummingbot/blob/master/hummingbot/core/data_type/order_book_tracker.py#L277

```python
order_book.apply_trade(OrderBookTradeEvent(
    trading_pair=trade_message.trading_pair,
    timestamp=trade_message.timestamp,
    price=float(trade_message.content["price"]),
    amount=float(trade_message.content["amount"]),
    type=TradeType.SELL if
    trade_message.content["trade_type"] == float(TradeType.SELL.value) else TradeType.SELL
))
```

Notice that the dataclass `OrderBookTradeEvent` `type` attribute is always set to `TradeType.SELL` even if `trade_message.content["trade_type"] != float(TradeType.SELL.value)`. The if statement should evaluate to `TradeType.BUY` instead.

**Comment by mifeng** [comment]
This seems like a bug but it's strange that we haven't seen its impact while running the bot.

We should investigate whether this needs to be changed.
