### ISSUE TITLE
[BUG] Trading pair fetcher broken on KuCoin

### ISSUE THREAD

**Issue by Hashira-Lars** [CoinAlpha/hummingbot#1342]
**Describe the bug**
- Accepting anything entered within that parameter.
- Accepting Lower Case.
- Auto-Complete not showing.

**Steps To Reproduce**
1. Create New Strategy
2. Wait for this question : Enter the token pair you would like to trade on kucoin <e . g ETH- 
    USDT> >>> ? (enter anything here)
3. Finishing configuration
4. Enter list configs to check
5. Exit and check external conf file to verify
6. Issue will show

**Screenshots**
example entered input : 
![image](https://user-images.githubusercontent.com/55869559/73035200-45722300-3e82-11ea-95ba-588983f490b3.png)

list_configs
![image](https://user-images.githubusercontent.com/55869559/73035227-558a0280-3e82-11ea-92d2-cdf87ea7ca4a.png)

conf_file
![image](https://user-images.githubusercontent.com/55869559/73035260-718da400-3e82-11ea-93b6-9a4903b7edd4.png)

**Release version**
Development

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:** Lars l Support
**Optional: your ETH address:** (If you want to participate in the bug bounty)

**Comment by yzhang1994** [comment]
@vic-en Could you take a look at this? Thanks

**Comment by Hashira-Lars** [comment]
Confirm fix tested on latest dev image . Thanks @yzhang1994 

![image](https://user-images.githubusercontent.com/55869559/73413871-f6c3fd80-4347-11ea-8705-cecbc434e8e8.png)
