### ISSUE TITLE
[BUG] Auto-complete for trading pair not showing on KuCoin

### ISSUE THREAD

**Issue by Hashira-Lars** [CoinAlpha/hummingbot#1343]
**Describe the bug**
// Auto-complete for trading pair not showing on KuCoin.

**Steps To Reproduce**
1.Create new strategy file
2.Select KuCoin as the exchange
3.Wait for it to ask which token trading pair you want to trade in
4.Press Tab or Space or Enter a letter for a token pair
5.Auto-complete not showing

**Screenshots**
KuCoin
![image](https://user-images.githubusercontent.com/55869559/73036799-b36d1900-3e87-11ea-8f9e-a4e8e93c8f4f.png)

**Release version**
Development
 
*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:** Lars l Support
**Optional: your ETH address:** (If you want to participate in the bug bounty)

**Comment by PtrckM** [comment]
Was able to replicate issue on docker linux and docker windows

![image](https://user-images.githubusercontent.com/54516858/73037389-d4366e00-3e89-11ea-89e3-dab3fe13dc41.png)
![image](https://user-images.githubusercontent.com/54516858/73037419-f6c88700-3e89-11ea-87ed-3ec19eca79a3.png)

**Version:**
```
                "branch": "development",
                "commit": "8554c75cc7bf9ca984ec522b00d77b6cf774c028",
                "date": "2020-01-23T00:28:23Z",
```

**Comment by yzhang1994** [comment]
@PtrckM @Hashira-Lars The Radar Relay connector is broken right now and needs to be upgraded to version 3. We have alerted our users not to use Radar at this moment. So I believe this is a bug on the KuCoin trading pair fetcher, which is mentioned in another issue here: https://github.com/CoinAlpha/hummingbot/issues/1342

**Comment by Hashira-Lars** [comment]
Thanks @yzhang1994 ♥

**Comment by dennisocana** [comment]
Treating as duplicate, closing issue.
