### ISSUE TITLE
[BUG] Recreating config password not working with quickstart

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#1348]
**Describe the bug**

In case of a forgotten config password, the solution is to delete or move the encrypted files --> restart Hummingbot --> set up a new password.

![ekZNlZZKUk](https://user-images.githubusercontent.com/50150287/73115219-00232380-3f5e-11ea-830b-5686051c13cb.gif)

This does not work on a container created through quickstart. It asks for the API keys and skips the question to enter a new password.

![JMp1VPHgsh](https://user-images.githubusercontent.com/50150287/73115244-5001ea80-3f5e-11ea-9ef2-7f6fdb53f5eb.gif)

The workaround is to delete the encrypted files --> remove the docker container --> recreate the container normally or use `create.sh` script --> enter a new password.

**Release version**

```
"branch": "master",
"commit": "03aaa8d2000c48f988d94a873d7e65b4714a65b9",
"date": "2020-01-13T20:02:43Z",
```

**Comment by Nullably** [comment]
@dennisocana 
If the password is supplied as a parameter when starting a quick_start, HB will not ask for a new password, whatever password supplied is the new password. So this is an expected behaviour.
