### ISSUE TITLE
[BUG] Losing track of orders on Coinbase Pro

### ISSUE THREAD

**Issue by yzhang1994** [CoinAlpha/hummingbot#1357]
**Describe the bug**
- Orders are shown in Coinbase Pro UI but are "forgotten" by the hummingbot client.

**Screenshots**
![](https://media.discordapp.net/attachments/563462222878212098/671830260337344532/unknown.png)

**Release version**
0.22.0

**Attachments**
[hummingbot_logs (2).zip](https://github.com/CoinAlpha/hummingbot/files/4125075/hummingbot_logs.2.zip)

**Comment by Hashira-Lars** [comment]
Tested in latest master branch windows binary and was able to reproduce the behavior

note : in my account i only have link so its only placing ask order

exchange / created 2 ask order
![image](https://user-images.githubusercontent.com/55869559/73315772-f5bd9e00-426b-11ea-93a2-7f2110f9473e.png)

hb client / only showing 1 successfully created ask order
![image](https://user-images.githubusercontent.com/55869559/73315795-02da8d00-426c-11ea-8c73-e56fe9b12967.png)

orders
![image](https://user-images.githubusercontent.com/55869559/73315841-2271b580-426c-11ea-9b98-e2066369eaa0.png)

after stopping the bot the other order which hb did not recognize to create was stuck at the exchange
![image](https://user-images.githubusercontent.com/55869559/73315864-39180c80-426c-11ea-9716-03371180b615.png)

(still stuck after 18mins)
![image](https://user-images.githubusercontent.com/55869559/73316084-eb4fd400-426c-11ea-9aed-23d8c0248272.png)


![image](https://user-images.githubusercontent.com/55869559/73315891-49c88280-426c-11ea-9c3e-7506fec0ab9a.png)

logs also not showing successful creation of the the other ask order
[logs_conf_pure_market_making_strategy_1.log](https://github.com/CoinAlpha/hummingbot/files/4125476/logs_conf_pure_market_making_strategy_1.log)

**Comment by Clint-G13** [comment]
I'm getting a different behavior, after disabling inventory_skew and start the bot. Hummingbot is displaying no active order however, an active order is shown on Coinbase pro. After a few minutes, the order gets filled. Will continue monitoring this behavior.
![Untitled](https://user-images.githubusercontent.com/57189990/73317116-f5270680-426f-11ea-9944-a08654ac09f6.png)

**Comment by Hashira-Lars** [comment]
Tested with the latest dev image merged with pr #1362 

Confirm Fix however from my observation the orders being placed at hb and exchange are not matching even if i have set my config `add_transaction_costs` to false. can someone enlighten me thanks.

first placed orders
![image](https://user-images.githubusercontent.com/55869559/73416934-583c9a00-4351-11ea-9526-07163f959b71.png)

exchange
![image](https://user-images.githubusercontent.com/55869559/73416946-6094d500-4351-11ea-87a2-b608e653702e.png)

2nd placed order(not enough link to place ask order)
![image](https://user-images.githubusercontent.com/55869559/73416998-87530b80-4351-11ea-9107-8b26c884c974.png)

exchange
![image](https://user-images.githubusercontent.com/55869559/73417017-9934ae80-4351-11ea-9614-f87543bcc029.png)

note : upon stopping the bot no more stuck orders

**Comment by Clint-G13** [comment]
Adding additional information for the reported bug:
discord username: Gene
eth address:  0x158d63A32482b3384089eC077899271d63E81bBF

**Comment by dennisocana** [comment]
Confirmed and tested fix by @Hashira-Lars

**Comment by feuGeneA** [comment]
@dennisocana @Hashira-Lars when is the fix expected to be released?

**Comment by dennisocana** [comment]
@feuGeneA the fix should be in today's release, version 0.23.0
