### ISSUE TITLE
[BUG] Order prices that are "0" in value are being placed by the bot- Coinbase pro

### ISSUE THREAD

**Issue by rennel-tabing** [CoinAlpha/hummingbot#1370]
**Describe the bug**
// A clear and concise description of what the bug is.
Trade history shows an order with price value of "0" has been filled

![image](https://user-images.githubusercontent.com/53868268/73554695-365b1a00-441a-11ea-9ffb-4c0ea45d6ac1.png)

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: ...
```
pure_market_making strategy configs:                                                        
                                       Key Current Value                                    
0                             maker_market  coinbase_pro                                    
1              primary_market_trading_pair       ZRX-USD                                    
2                                     mode        single                                    
3                      bid_place_threshold       0.00375                                    
4                      ask_place_threshold       0.00375                                    
5                       expiration_seconds         130.0                                    
6                   cancel_order_wait_time         300.0                                    
7                             order_amount         100.0                                    
8                         number_of_orders             1                                    
9                         order_start_size           1.0                                    
10                         order_step_size           0.0                                    
11                  order_interval_percent          0.01                                    
12                  inventory_skew_enabled          True                                    
13           inventory_target_base_percent           0.5                                    
14        filled_order_replenish_wait_time          10.0                                    
15   enable_order_filled_stop_cancellation         False                                    
16                  best_bid_ask_jump_mode         False                                    
17          best_bid_ask_jump_orders_depth           0.0                                    
18                   add_transaction_costs         False                                    
19                 external_pricing_source         False                                    
20              external_price_source_type          None                                    
21          external_price_source_exchange          None                                    
22   external_price_source_feed_base_asset          None                                    
23  external_price_source_feed_quote_asset          None                                    
24        external_price_source_custom_api          None 
```
2. Start the bot using this command: ...
...

**Screenshots**
// If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/53868268/73554805-67d3e580-441a-11ea-8122-8da6b66ba140.png)
related log 
```
2020-01-30 11:41:15,115 - 10 - hummingbot.market.coinbase_pro.coinbase_pro_market - INFO - Filled 59.00000000 out of 70.00000000 of the limit buy order buy-ZRX-USD-1580384473002856.
2020-01-30 11:41:15,116 - 10 - hummingbot.strategy.pure_market_making.pure_market_making_v2 - INFO - (ZRX-USD) Maker buy order of 59.00000000 ZRX filled. [clock=2020-01-30 11:41:15+00:00]
2020-01-30 11:41:15,116 - 10 - hummingbot.core.event.event_reporter - EVENT_LOG - {"order_id": "buy-ZRX-USD-1580384473002856", "trading_pair": "ZRX-USD", "trade_type": "TradeType.BUY", "order_type": "OrderType.LIMIT", "price": "0", "amount": "59.00000000", "trade_fee": ["0.0015", []], "exchange_trade_id": "be9bbdf2-d56a-4ee9-8724-76166eab9956", "event_name": "OrderFilledEvent", "event_source": "coinbase_pro", "ts": 1580384475.0}

```

Another sample occurrence
![image](https://user-images.githubusercontent.com/53868268/73555098-fc3e4800-441a-11ea-860b-75c992e34d51.png)

Related logs (there is no related logs for this event though)
![image](https://user-images.githubusercontent.com/53868268/73557537-5e994780-441f-11ea-96ea-13b584b87b9b.png)

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).
0.22.0 via docker

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 
[pureMM logs - 0 filled order.txt](https://github.com/CoinAlpha/hummingbot/files/4140503/pureMM.logs.-.0.filled.order.txt)

**Optional: your discord username:** Gene #8670
**Optional: your ETH address:** 0x158d63A32482b3384089eC077899271d63E81bBF

**Comment by feuGeneA** [comment]
Original reporter here.  Note that for the second occurrence cited above, not only is there no record of the trade in the logs, but there's also no record of it in my Coinbase Pro fills either:

![image](https://user-images.githubusercontent.com/7883777/73560402-e0d83a80-4424-11ea-9484-1d1ab1cf579a.png)

Unfortunately, I don't have any record of what Coinbase thought of the first occurrence described above...

**Comment by znerol19619** [comment]
Just tested using the same version of hummingbot 0.22.0 (docker linux), and wasn't able to reproduce the behavior where amounts being placed are 0. 

You might want to update your hummingbot to 0.23.0, new release version. There's a bug with coinbase pro that was fixed on that version. Try running your strategy again and let us know if you'll encounter that kind of behavior again in the latest version of hummingbot.

**Comment by Nullably** [comment]
I believe this issue is the same as #1241 and #1387, trades are reported on HB (whether you look at it in logs, trade history or status command) but no actual trades on Coinbase Pro.
