### ISSUE TITLE
[BUG] Liquid, bot stuck when using pure market making for trading pair TRX-BTC

### ISSUE THREAD

**Issue by paleboot** [CoinAlpha/hummingbot#1375]
**Describe the bug**
Bot seems to be stuck forever in `Started order book tracking for {trading_pair}` for trading pair TRX-BTC. Tried restarting the bot for 13 minutes to no avail. Balance is available and bot did track the right market, but no orders were made.

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: 
[conf.txt](https://github.com/CoinAlpha/hummingbot/files/4142689/conf.txt)

2. Start the bot using this command: `start`

**Screenshots**
![Screenshot from 2020-02-01 21-52-17](https://user-images.githubusercontent.com/54321501/73594221-ea55c580-453e-11ea-9283-4b1011c190d0.png)

![Screenshot from 2020-02-01 21-39-59](https://user-images.githubusercontent.com/54321501/73594301-a1ead780-453f-11ea-929d-4a278ef6530f.png)

**Release version**
dev-0.23.0

**Attachments**
[logs_conf_pure_market_making_strategy_1.log](https://github.com/CoinAlpha/hummingbot/files/4142691/logs_conf_pure_market_making_strategy_1.log)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:** paleboot #5423
**Optional: your ETH address:** 0x5447c76339ce0abf07bb5cc15f2e5a115ca33106

**Comment by MishaelTereso** [comment]
@paleboot I tried your configuration with same exact parameter values with **paper_trade** enabled (since I don't have actual assets on Liquid exchange) and seems like the bot is working fine (**dev branch**) and it didn't reproduced the issue. Hummingbot shows it placed an order in a paper_trade environment.

![image](https://user-images.githubusercontent.com/56957119/73601825-202c9580-45a3-11ea-9918-048970107868.png)

![image](https://user-images.githubusercontent.com/56957119/73601866-03449200-45a4-11ea-9105-f70f3d07a613.png)

**Comment by dennisocana** [comment]
Also confirmed that the configs meet the exchange's trade rule as I can manually place a limit order of the specified amount.

<img width="800" alt="chrome_CUi45snlaO" src="https://user-images.githubusercontent.com/50150287/73610189-a1217680-460f-11ea-83b6-843144d36002.png">

**Comment by MishaelTereso** [comment]
UPDATE:
Performed test in the latest release version (master branch - 0.23.0). BUG still persist.

![image](https://user-images.githubusercontent.com/56957119/73736737-45283080-477c-11ea-8ff4-2b3b16c35d0d.png)

**Comment by paleboot** [comment]
Hello @MishaelTereso @dennisocana thanks for replying. 

I figured out the culprit; no orders was placed due to empty `filtered_proposal`, I'm referring to this snippet from `c_tick()` found in `pure_market_making_v2.pyx`:
 
```
for market_info in self._market_infos.values():
    self._sb_delegate_lock = True
    orders_proposal = None
    try:
        orders_proposal = self.c_get_orders_proposal_for_market_info(
            market_info,
            market_info_to_active_orders.get(market_info, [])
        )
    except Exception:
        self.logger().error("Unknown error while generating order proposals.", exc_info=True)
    finally:
        self._sb_delegate_lock = False
    filtered_proposal = self._filter_delegate.c_filter_orders_proposal(self,
                                                                       market_info,
                                                                       market_info_to_active_orders.get(market_info, []),
                                                                       orders_proposal)
    filtered_proposal = self.c_filter_orders_proposal_for_takers(market_info, filtered_proposal)
    self.c_execute_orders_proposal(market_info, filtered_proposal)
```

So what happens is the bot fails to quantize the order price properly, which causes `buy_price` and `sell_price` to be equal with `asset_mid_price` and passed on to `pricing_proposal`. I'm referring to this snippet from `c_get_orders_proposal_for_market_info()` found in `pure_market_making_v2.pyx`:
```
asset_mid_price = Decimal("0")
if self._asset_price_delegate is None:
    asset_mid_price = market_info.get_mid_price()
else:
    asset_mid_price = self._asset_price_delegate.c_get_mid_price()
    pricing_proposal = self._pricing_delegate.c_get_order_price_proposal(self,
                                                                         market_info,
                                                                         active_orders,
                                                                         asset_mid_price)
```

Then when the bot filters the order, it fails to meet the conditions `if first_ask.is_nan() or (buy_price < first_ask)` and `if first_ask.is_nan() or (buy_price < first_ask)` hence no price was appended which leads to `filtered_proposal` being empty. I'm referring to this snippet from `c_filter_orders_proposal_for_takers()` found in `pure_market_making_v2.pyx`:
```
if len(orders_proposal.buy_order_sizes) > 0 and orders_proposal.buy_order_sizes[0] > 0:
            first_ask = market.c_get_price(market_info.trading_pair, True)
            for buy_price, buy_size in zip(orders_proposal.buy_order_prices, orders_proposal.buy_order_sizes):
                if first_ask.is_nan() or (buy_price < first_ask):
                    buy_prices.append(buy_price)
                    buy_sizes.append(buy_size)
if len(orders_proposal.sell_order_sizes) > 0 and orders_proposal.sell_order_sizes[0] > 0:
            first_bid = market.c_get_price(market_info.trading_pair, False)
            for sell_price, sell_size in zip(orders_proposal.sell_order_prices, orders_proposal.sell_order_sizes):
                if first_bid.is_nan() or (sell_price > first_bid):
                    sell_prices.append(sell_price)
                    sell_sizes.append(sell_size)
```

I found that this was caused due to the connector not fetching the correct price increment for TRX-BTC, hence failed to quantize the buy and sell price properly. I've opened a pull request #1389, please test it out to see if it works, thanks!

**Comment by moraliang** [comment]
@paleboot  Sent you 0.1ETH bug bounty. Thanks.
