### ISSUE TITLE
[question] Uniswap connector

### ISSUE THREAD

**Issue by zhiji666** [CoinAlpha/hummingbot#1386]
You said uniswap connector is comming soon in April 2019 in the article below. Why it hasn't release until now? Did you have another plan or you get some tough problems? Can I know what problems are? Thanks.

article:https://hummingbot.io/blog/2019-04-hummingbot-vs-uniswap/

**Comment by rennel-tabing** [comment]
Unfortunately, our developers don't have bandwidth to explore a Uniswap integration till 2nd half of the year, but if any users are interested in building a custom arb strategy, we can probably provide tech support

https://discordapp.com/channels/530578568154054663/563462222878212098/663807958852829184
