### ISSUE TITLE
[BUG] Order filled reported when no trade happened. (Coinbase Pro)

### ISSUE THREAD

**Issue by Nullably** [CoinAlpha/hummingbot#1387]
**Describe the bug**
Buy order partially filled reported on log screen and log file when no trade actually happened. This happens on Coinbase Pro.

**Steps To Reproduce**
Configure the bot to run pure market making strategy as conf file attached. And start the bot, it soon reports filled order while balances remain the same.

**Screenshots**
![image](https://user-images.githubusercontent.com/37262506/73757652-7fa5c380-47a4-11ea-9043-452ac3c2e8ff.png)
![image](https://user-images.githubusercontent.com/37262506/73757668-859ba480-47a4-11ea-9065-af4cfdac095c.png)

**Release version**
Curent development

**Attachments**
[conf_pure_market_making_coinbase_pro.txt](https://github.com/CoinAlpha/hummingbot/files/4156861/conf_pure_market_making_coinbase_pro.txt)
[logs_conf_pure_market_making_coinbase_pro.log](https://github.com/CoinAlpha/hummingbot/files/4156862/logs_conf_pure_market_making_coinbase_pro.log)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**
**Optional: your ETH address:** (If you want to participate in the bug bounty)

**Comment by znerol19619** [comment]
I run some tests one wasn't able to reproduce the behavior. 

![Screenshot from 2020-02-05 18-45-26](https://user-images.githubusercontent.com/27669951/73835280-17a8b900-4848-11ea-842f-829dddbe5175.png)

**Release version**

***
                "branch": "development",
                "commit": "8b3a8e9bfc4239c1549b626deef9c12c9e28ec51",
                "date": "2020-02-05T00:39:44Z",

***

**Comment by Nullably** [comment]
@znerol19619 
I just found out more about this bug, you will need to have inventory for the bot to be able to put both bid and ask orders at different order amounts, so make sure to set `inventory_skew_enabled` to `inventory_skew_enabled`.

**Comment by MishaelTereso** [comment]
I ran a test using the same exact configuration and was not able to reproduce the behavior. 

![Coinbase](https://user-images.githubusercontent.com/56957119/73918624-eb02a900-48fc-11ea-9f88-6bb6b3b47e5d.png)

![Coinbase_Filled](https://user-images.githubusercontent.com/56957119/73918792-403eba80-48fd-11ea-8491-afa22826ed24.png)

**Comment by Nullably** [comment]
@MishaelTereso This bug is hard to reproduce, there are a few thing you have to make sure.
- The bot needs to send out both bid and ask orders
- The order amount of the 2 orders need to differ, e.g. bid size is 3 and ask size is 1
- `inventory_skew_enabled` is set to true
- You might need to run the bot for a while for this to happen
To understand more of the mechanism behind this see PR #1390
