### ISSUE TITLE
[BUG] Bot keeps on fetching nonexisting orders in IDEX

### ISSUE THREAD

**Issue by znerol19619** [CoinAlpha/hummingbot#1393]
**Describe the bug**
Bot still trying to fetch status updates of successfully cancelled orders or nonexisting orders.
It floods the log file with too much errors resulting the bot to freeze.

**Screenshots**
![Screenshot from 2020-02-06 17-22-41](https://user-images.githubusercontent.com/27669951/73925329-de844d80-4908-11ea-8795-84560fa65f79.png)
![Screenshot from 2020-02-06 16-05-25](https://user-images.githubusercontent.com/27669951/73925436-096ea180-4909-11ea-9cb2-4e69aec6aef3.png)
![Screenshot from 2020-02-06 16-04-32](https://user-images.githubusercontent.com/27669951/73925456-0e335580-4909-11ea-8b8b-b6a60dd3f06c.png)
![Screenshot from 2020-02-06 16-09-55](https://user-images.githubusercontent.com/27669951/73925480-168b9080-4909-11ea-9ba4-fd2f168d779b.png)
![Screenshot from 2020-02-06 17-59-49](https://user-images.githubusercontent.com/27669951/73926407-89e1d200-490a-11ea-846f-2d5cf2136bb4.png)

**Release version**
0.23.0 (Master)

**Attachments**
[conf_pmm_qnt-eth.txt](https://github.com/CoinAlpha/hummingbot/files/4164372/conf_pmm_qnt-eth.txt)
[logs_conf_pmm_qnt-eth-2020-02-05.log](https://github.com/CoinAlpha/hummingbot/files/4164407/logs_conf_pmm_qnt-eth-2020-02-05.log)

**Comment by znerol19619** [comment]
Related Issue https://github.com/CoinAlpha/hummingbot/issues/1281

**Comment by yzhang1994** [comment]
The IDEX connector is deprecated - we will no longer support IDEX-related issues. Closing this issue for now.
