### ISSUE TITLE
[BUG] Windows Binary - Error saving Discovery result

### ISSUE THREAD

**Issue by Clint-G13** [CoinAlpha/hummingbot#1402]
**Describe the bug**
When running a discovery strategy, the csv result fails to save on the designated path.

```
2020-02-07 08:10:45,073 - 1760 - hummingbot.client.hummingbot_application - INFO - Saving discovery output...
2020-02-07 08:10:45,075 - 1760 - hummingbot.client.hummingbot_application - ERROR - Error saving discovery result as csv: [Errno 2] No such file or directory: 'C:\\Program Files (x86)\\Hummingbot\\hummingbot\\strategy\\discovery\\../../../logs/discovery_strategy_output_2020-02-07-08-10-45.csv'
````

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):
1. Open Hummingbot installed via windows binary
2. Start a Discovery strategy and wait until scan finishes. 
...

**Screenshots**
![Discovery-Export Issue](https://user-images.githubusercontent.com/57189990/74204164-067b0480-4cad-11ea-83ae-10cf62c00afb.PNG)

**Release version**
Windows binary: 0.23.0 - Master branch only

**Attachments**
[Discovery logs.txt](https://github.com/CoinAlpha/hummingbot/files/4183757/Discovery.logs.txt)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**
**Optional: your ETH address:** (If you want to participate in the bug bounty)

**Comment by znerol19619** [comment]
Related issue https://github.com/CoinAlpha/hummingbot/issues/1302

**Comment by PtrckM** [comment]
Workaround:

1. Create a new folder called `logs` under `Hummingbot` on `C:\Program Files (x86)` for example `C:\Program Files (x86)\Hummingbot\logs`
2. run hummingbot app as administrator (to have write permission on the created folder)
    [pressing CTRL + Shift + hummingbot app to run hummingbot as administrator]

![image](https://user-images.githubusercontent.com/54516858/77872637-11e4b800-727a-11ea-8ccd-b9ef6037d455.png)
![image](https://user-images.githubusercontent.com/54516858/77872659-2d4fc300-727a-11ea-9c0b-f55130d5c2eb.png)

**Comment by dennisocana** [comment]
Deprecated discovery strategy in version 0.26.0
