### ISSUE TITLE
[BUG] Paper Trade | Cross-Exchange MM - Unable to initiate

### ISSUE THREAD

**Issue by MishaelTereso** [CoinAlpha/hummingbot#1425]
**Describe the bug**
Bot won't execute trade or even initiate an order when **paper_trade** is enabled using Cross-Exchange MM strategy.

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):
1. Enable Paper_Trade mode
2. Establish a bot using Cross-Exchange Market Making
3. Select Exchanges. Bamboo Relay (maker) Binance (taker)
3. Set min_profitability = 0.01
4. Set order amount = 0.05 or 5
5. Start the bot
...

**Screenshots**
![image](https://user-images.githubusercontent.com/56957119/74597772-c1394700-509f-11ea-84dd-615ff64332b5.png)
![image](https://user-images.githubusercontent.com/56957119/74597779-df06ac00-509f-11ea-93b2-052e3c334319.png)

**Release version**
Master (0.23.0) and Development branch (0.24.0)
Tested on: Windows Binary installer and Docker (AWS server)

**Attachments**
[conf_xemm_papertrade.txt](https://github.com/CoinAlpha/hummingbot/files/4209265/conf_xemm_papertrade.txt)
[logs_xemm_papertrade.txt](https://github.com/CoinAlpha/hummingbot/files/4209266/logs_xemm_papertrade.txt)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:** MishaelT
**Optional: your ETH address:** (0x98211e49660e5680AeA6bb84b4bDB099bc3BE083)

**Comment by PtrckM** [comment]
@MishaelTereso this is a known bug from https://github.com/CoinAlpha/hummingbot/issues/1248 when paper trade already enabled while creating new conf on xemm.

to workaround it:
disable paper trade before creating new conf (these applies to development and master release / docker linux/windows/binary and WSL)

![image](https://user-images.githubusercontent.com/54516858/74600591-8ac6f080-50ce-11ea-8d19-555c9a4a7c21.png)

![image](https://user-images.githubusercontent.com/54516858/74600589-86023c80-50ce-11ea-94db-61049d336c0f.png)

![image](https://user-images.githubusercontent.com/54516858/74600594-93b7c200-50ce-11ea-9972-69ac1021ff5b.png)

**Comment by MishaelTereso** [comment]
@PtrckM That workaround did the trick. Thanks!
![image](https://user-images.githubusercontent.com/56957119/74612115-648c6980-513d-11ea-89b8-5b348fd2ed9c.png)
