### ISSUE TITLE
[Feature] BOT stop after orders conclusion

### ISSUE THREAD

**Issue by starloungeswitzerland** [CoinAlpha/hummingbot#1429]
**Feature Suggestion**
It make possible have a command like `stop --onclose` to stop trading activities after active orders conclusion.

**Impact**
Actually we can stop or force stop of trading activities, but seems interesting to stop without cancelling actual orders on exchange.

**Additional context**
Nothing

**Comment by rennel-tabing** [comment]
@starloungeswitzerland 
Can you confirm if orders were not getting cancelled after issuing the `stop` command  on your end 
 or do you mean that you want to  cancel all active orders after  one orders got filled when doing a `stop`  command`?

The `stop` command should cancel all active orders in place.
![image](https://user-images.githubusercontent.com/53868268/74661696-75050a00-5166-11ea-96ea-105cd4e270ff.png)

**Comment by starloungeswitzerland** [comment]
The second is ok!
I want to cancel all active orders after one orders got filled when doing a stop command.

**Comment by mifeng** [comment]
We won't add this as a new parameter, but users will be able to customize the bot to perform his behavior after #1691 and #1714
