### ISSUE TITLE
[BUG]Radar_relay broken trading fetcher

### ISSUE THREAD

**Issue by Clint-G13** [CoinAlpha/hummingbot#1441]
**Describe the bug**
When creating a strategy, radar_relay accepts any input on entered as market trading pair.

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):
1. Create a PMM or XEMM strategy and use radar_relay
2. Enter any text for radar relay trading pair and it will be accepted.

**Screenshots**
![Radar_broken_trading_pair_fetcher](https://user-images.githubusercontent.com/57189990/74997877-27eca500-5492-11ea-84b4-de44ed7d0d35.png)
![Radar_broken_trading_pair_fetcher_2](https://user-images.githubusercontent.com/57189990/74997878-29b66880-5492-11ea-9e21-a5040f7c05c3.png)
![Radar_broken_trading_pair_fetcher1](https://user-images.githubusercontent.com/57189990/74997884-2c18c280-5492-11ea-8129-b02f27b8b3f5.png)

**Release version**
Environment: Docker (Linux) and Source
```
"branch": "development",
"commit": "9a107f4c6896bb52ce777ae6b428dc7c6309004b",
"date": "2020-02-20T09:53:23Z",
```

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**
**Optional: your ETH address:** (If you want to participate in the bug bounty)

**Comment by Hashira-Lars** [comment]
Re-tested both on `0.25.0` latest dev & `0.24.1` master issue still persist

![image](https://user-images.githubusercontent.com/55869559/76911147-02b15200-68eb-11ea-8284-c135ab93b513.png)

**Comment by Hashira-Lars** [comment]
Re-tested on latest master branch and dev = issue still persist

![image](https://user-images.githubusercontent.com/55869559/77713725-1e66d780-7012-11ea-8ef0-f51aabc30b3f.png)

**Comment by PtrckM** [comment]
this is fixed on https://github.com/CoinAlpha/hummingbot/pull/1588

![image](https://user-images.githubusercontent.com/54516858/78878296-bdfd7e80-7a84-11ea-998c-3f6aed3ea25b.png)
