### ISSUE TITLE
[BUG] Multiple CoinGecko errors show soon after bot starting.

### ISSUE THREAD

**Issue by Nullably** [CoinAlpha/hummingbot#1469]
**Describe the bug**
Multiple errors display soon after start running Hummingbot. This also seems to make configuration process much slower than usual.

**Steps To Reproduce**
Start the bot

**Screenshots**
<img width="1536" alt="Screenshot 2020-02-26 at 5 58 52 PM" src="https://user-images.githubusercontent.com/37262506/75333757-ab0e6080-58c1-11ea-9877-7bddb9d374f0.png">

**Release version**
Development.

**Comment by Nullably** [comment]
The issue is CoinGecko has decreased their limit on number of ids on `api.coingecko.com/api/v3/simple/price` api (on ids parameter). Down from 500 to around 70 (can't find this on api document, found out just by simply trying). 
The actual API error message return is 
`translation missing: en.api.errors.too_many_coin_ids`

**Comment by mifeng** [comment]
This error is blocking the bot from starting for me: https://www.loom.com/share/cb32d5b14e434c95ac3cff9be957fb2e
