### ISSUE TITLE
[BUG] Multiple Pairs Reported in Trade History

### ISSUE THREAD

**Issue by RJDavison** [CoinAlpha/hummingbot#1471]
**Describe the bug**
When running two docker instances on the same machine, which each trade different pairs i.e. LINK/BTC and RLC/ETH and which use a common configuration folder, the history command reports the trades for both sets of pairs in the same list

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):
1. run two docker bot instances on the same machine.
2. each bot has different trading pairs
3. both instances should point to the same config and logs folder
4. allow a trade to occur on both bots
5. run the 'history' command

**Screenshots**

![ScreenCapture](https://user-images.githubusercontent.com/1660611/75336421-2b21cf80-589c-11ea-9e03-1ebb102635e5.PNG)

**Release version**

0.24

**Attachments**

[configs.zip](https://github.com/CoinAlpha/hummingbot/files/4255126/configs.zip)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**
RJDavison
**Optional: your ETH address:** (If you want to participate in the bug bounty)
0x20B755b33f224a25b59587A2202Ac4816E3cE69E

**Comment by rennel-tabing** [comment]
I was able to reproduce this behavior yesterday using dev-0.24.0
It is worth mentioning that for you to be able to reproduce this issue, both instance should point on the same config and logs folder.

**Comment by mifeng** [comment]
Users who encounter this issue should use different folders for config and logs.
