### ISSUE TITLE
[BUG] Cross Exchange bot keep placing/cancelling orders rapidly when order size less than specified amount

### ISSUE THREAD

**Issue by Peppers-Anawin** [CoinAlpha/hummingbot#1480]
**Describe the bug**
when using Cross Exchange strategy (Maker: Kucoin/ Taker: Binance) bots keep placing/cancelling orders rapidly when order size less than specified amount. For example when BTC on the taker exchange is low and the bot place a smaller ask order size on the maker exchange to match it then it start creating and cancelling that order like every second

**Steps To Reproduce**
the specified order size just has to be higher than the value of the quote asset on the taker exchange and might have to wait awhile for this behavior to start

**Screenshots**
<img width="1278" alt="Screen Shot 2020-02-28 at 8 13 54 PM" src="https://user-images.githubusercontent.com/59044268/75552728-81903900-5a69-11ea-8b13-9b4cbab2e294.png">

**Release version**
0.24.0

**Comment by rennel-tabing** [comment]
Please provide the other information's for us to further check on the issue.

1. Deployment environment
    - Machine - local computer or cloud server?
    - Which cloud provider?
    - What operating system?
    - Installation type - Docker, from source, or binary
2. **Screenshot** - In the hummingbot client, run the `status` command and take a screenshot that includes the full Terminal/Bash window. Make sure to include both the left pane and the right log pane of Hummingbot.
3. **Strategy config file -** This is the file with the parameters associated with your strategy. It does not contain API keys, wallet private keys, or other confidential data. It is located in the `conf/` folder. For example, if you have configured a pure market making strategy for the first time, the file's default name is `conf_pure_market_making_0.yml`
4. **Log file**: This is the file that contains a detailed log output and error stack trace. It is located in the `logs/` folder. If you are sending logs related to your most recent Hummingbot session, sort the folder for the most recently updated file. It should have a name similar to `logs_conf_pure_market_making_0.log`

**Comment by Peppers-Anawin** [comment]
Running on Ubuntu 18.04 LTS on Google Cloud N1 Instance
Installation type: Docker

Strategy Config File
`template_version: 2
# The following configuations are only required for the
# cross exchange market making strategy
# Exchange and token parameters
maker_market: kucoin
taker_market: binance
maker_market_trading_pair: OMG-BTC
taker_market_trading_pair: OMG-BTC
# Minimum profitability target required to place an order
# Expressed in decimals: 0.01 = 1% target profit
min_profitability: 0.004
# Maximum order size in terms of base currency
order_amount: 500.0
# Have Hummingbot actively adjust/cancel orders if necessary.
# If set to true, outstanding orders are adjusted if
# profitability falls below min_profitability.
# If set to false, outstanding orders are adjusted if
# profitability falls below cancel_order_threshold.
active_order_canceling: true
# If active_order_canceling = false, this is the profitability/
# loss threshold at which to cancel the order.
# Expressed in decimals: 0.01 = 1% target profit
cancel_order_threshold: 0.05
# An amount in seconds, which is the minimum duration for any
# placed limit orders. Default value = 130 seconds.
limit_order_min_expiration: 130.0
# If enabled (parameter set to `True`), the strategy will place the order on top of the top bid and ask,
# if its more profitable to place it there
adjust_order_enabled: true


# An amount expressed in base currency which is used for getting the top bid and ask,
# ignoring dust orders on top of the order book
top_depth_tolerance: 25.0
# An amount in seconds, which is the minimum amount of time interval between adjusting limit order prices
anti_hysteresis_duration: 30.0
# An amount expressed in decimals (i.e. input of `0.01` corresponds to 1%), which is the maximum size limit of new limit orders,
# in terms of ratio of hedge-able volume on taker side.
order_size_taker_volume_factor: 0.5
# An amount expressed in decimals (i.e. input of `0.01` corresponds to 1%), which is the maximum size limit of new limit orders,
# in terms of ratio of asset balance available for hedging trade on taker side
order_size_taker_balance_factor: 0.995
# An amount expressed in decimals (i.e. input of `0.01` corresponds to 1%), which is the maximum size limit of new limit orders,
# in terms of ratio of total portfolio value on both maker and taker markets
order_size_portfolio_ratio_limit: 0.1667
# For more detailed information, see:
# https://docs.hummingbot.io/strategies/cross-exchange-market-making/#configuration-parameters`

**Comment by Peppers-Anawin** [comment]
Running on Ubuntu 18.04 LTS on Google Cloud N1 Instance
Installation type: Docker

Strategy Config File

template_version: 2
# The following configuations are only required for the
# cross exchange market making strategy
# Exchange and token parameters
maker_market: kucoin
taker_market: binance
maker_market_trading_pair: OMG-BTC
taker_market_trading_pair: OMG-BTC
# Minimum profitability target required to place an order
# Expressed in decimals: 0.01 = 1% target profit
min_profitability: 0.004
# Maximum order size in terms of base currency
order_amount: 500.0
# Have Hummingbot actively adjust/cancel orders if necessary.
# If set to true, outstanding orders are adjusted if
# profitability falls below min_profitability.
# If set to false, outstanding orders are adjusted if
# profitability falls below cancel_order_threshold.
active_order_canceling: true
# If active_order_canceling = false, this is the profitability/
# loss threshold at which to cancel the order.
# Expressed in decimals: 0.01 = 1% target profit
cancel_order_threshold: 0.05
# An amount in seconds, which is the minimum duration for any
# placed limit orders. Default value = 130 seconds.
limit_order_min_expiration: 130.0
# If enabled (parameter set to `True`), the strategy will place the order on top of the top bid and ask,
# if its more profitable to place it there
adjust_order_enabled: true


# An amount expressed in base currency which is used for getting the top bid and ask,
# ignoring dust orders on top of the order book
top_depth_tolerance: 25.0
# An amount in seconds, which is the minimum amount of time interval between adjusting limit order prices
anti_hysteresis_duration: 30.0
# An amount expressed in decimals (i.e. input of `0.01` corresponds to 1%), which is the maximum size limit of new limit orders,
# in terms of ratio of hedge-able volume on taker side.
order_size_taker_volume_factor: 0.5
# An amount expressed in decimals (i.e. input of `0.01` corresponds to 1%), which is the maximum size limit of new limit orders,
# in terms of ratio of asset balance available for hedging trade on taker side
order_size_taker_balance_factor: 0.995
# An amount expressed in decimals (i.e. input of `0.01` corresponds to 1%), which is the maximum size limit of new limit orders,
# in terms of ratio of total portfolio value on both maker and taker markets
order_size_portfolio_ratio_limit: 0.1667
# For more detailed information, see:
# https://docs.hummingbot.io/strategies/cross-exchange-market-making/#configuration-parameters

**Comment by Peppers-Anawin** [comment]
Running on Ubuntu 18.04 LTS on Google Cloud N1 Instance
Installation type: Docker

Strategy Config File

template_version: 2

maker_market: kucoin
taker_market: binance
maker_market_trading_pair: OMG-BTC
taker_market_trading_pair: OMG-BTC

min_profitability: 0.004

order_amount: 500.0
active_order_canceling: true
cancel_order_threshold: 0.05.
limit_order_min_expiration: 130.0
adjust_order_enabled: true

top_depth_tolerance: 25.0
anti_hysteresis_duration: 30.0
order_size_taker_volume_factor: 0.5
order_size_taker_balance_factor: 0.995
order_size_portfolio_ratio_limit: 0.1667

**Comment by rennel-tabing** [comment]
@Peppers-Anawin Thanks. I guess you missed sending us the 2. `Screenshot of the status command ` and 4. `Log file inside the humminbot_log folder.`

**Comment by Peppers-Anawin** [comment]
@rennel-tabing Yes sorry its because I already made adjustments to fix it. Let me reproduce it again and will post more info

**Comment by dennisocana** [comment]
Ticket has become stale and most likely this is fixed since we haven't run into this error again nor there are users reporting this same behavior. Please feel free to re-open if this happens again.
