### ISSUE TITLE
[Feature] Stopping the bot without canceling hanging orders

### ISSUE THREAD

**Issue by RJDavison** [CoinAlpha/hummingbot#1486]
**Feature Suggestion**
The ability to stop the bot without it cancelling any hanging orders which are waiting to be filled.

**Impact**
I have a lot of hanging orders which have already been placed at the exchange. These orders are already a bid to an ask (or vice versa) with the required spread. stopping the bot will mean that there will be unfilled pairs, impacting the profitability.

I don't want the ability to adjust on the fly, just to be able to stop the bot without cancelling existing orders.

**Comment by mifeng** [comment]
@RJDavison To clarify, why do you want to leave the hanging orders when you stop the bot? Is that because you don't want to have your inventory position move around a lot? 

Let me know what risk you're trying to defuse, since we're looking at other bot tweaks that might accomplish the same thing.

**Comment by dennisocana** [comment]
Based on experience and testing, hanging orders remain open when sending the `stop` or `exit` command from the client. I think this is because hanging orders are not tracked in HB and the stop/exit command only cancels active orders in the client.

**Comment by mifeng** [comment]
@dennisocana Agree that's the current behavior, but HB should track hanging orders and cancel them upon stop/exit. Otherwise, it's a terrible UX.

**Comment by RJDavison** [comment]
Say the market is on the decline and my bot is set up in such a way that it is making alot of bid orders and the market is not increasing to close out the corresponding sell orders which are left hanging. I would want to be able to stop the bot to make the necessary changes to the config, but still leave the sell orders hanging in the hope that the market will change and the sell orders woul get filled in the future.

**Comment by RJDavison** [comment]
I'm not saying that the default action, or only action, should be to leave the orderst hanging. The user should be given the option when they are stopping the HB.

**Comment by mifeng** [comment]
A Discord user (n3b1) also requested this feature:
"is there a way to have the hanging orders stay when you stop the bot? (without manually creating them yourself). my concern is mostly that the bot crashes while i am afk and the hanging orders get cancelled"

**Comment by mifeng** [comment]
#1716 which allows users to alter params on the fly should fix this issue
