### ISSUE TITLE
[BUG] Discovery unable to start on decentralized exchanges | Bamboo Relay & Radar Relay

### ISSUE THREAD

**Issue by MishaelTereso** [CoinAlpha/hummingbot#1504]
**Describe the bug**
Discovery Strategy won't start when selecting decentralize exchanges like Bamboo Relay & Radar Relay as primary and secondary markets.

**Steps To Reproduce**

Here are the steps to reproduce the issue (see attachments in the section below):
1. Create a new conf strategy (discovery)
2. Select decentralized exchanges (Bamboo Relay & Radar Relay)
3. Set ``trading_pair 1 & 2`` to [ ]
4. Set ``target_prof`` to 0.0
5. Set ``target_amount`` to inf
6. Start the bot

NOTE: When paper_trade is ON, the error will show at the very end of the discovery process. See attached screenshots.

**Screenshots**
Paper_Trade OFF
![image](https://user-images.githubusercontent.com/56957119/76171290-540f6200-61c4-11ea-8ca9-b5178fac3b5c.png)
![image](https://user-images.githubusercontent.com/56957119/76171367-60e08580-61c5-11ea-9904-8e2011702145.png)

Paper_Trade ON
![image](https://user-images.githubusercontent.com/56957119/76171550-a30ac680-61c7-11ea-8288-db8c44a486a7.png)

**Release version**
Dev. 0.25.0 & Master 0.24.1
```
"branch": "development",
                "commit": "f1f42383a4e63b84e7591623f6668baa4f75279f",
                "date": "2020-03-06T02:20:38Z",
                "maintainer": "CoinAlpha, Inc. <dev@coinalpha.com>"
```

**Attachments**
[logs_conf_discovery_strategy_0.log](https://github.com/CoinAlpha/hummingbot/files/4303934/logs_conf_discovery_strategy_0.log)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**MishaelT**
**Optional: your ETH address:** (0x98211e49660e5680AeA6bb84b4bDB099bc3BE083)

**Comment by Hashira-Lars** [comment]
Tested on Windows Binary 0.24.1 - Issue Persist

To bypass the error you have to enable paper-trade and the strategy will initialize & finish.

![image](https://user-images.githubusercontent.com/55869559/76179561-44a90c80-61f6-11ea-8322-bc5007503cf4.png)

**Comment by Hashira-Lars** [comment]
Issue still persist on Latest Dev image 0.26.0 , still need to enable paper-trade to bypass error.

**Comment by vic-en** [comment]
https://github.com/CoinAlpha/hummingbot/pull/1571
