### ISSUE TITLE
[BUG] The bot still creates orders (make and take) after the stop command.

### ISSUE THREAD

**Issue by dietzam** [CoinAlpha/hummingbot#1508]
**Describe the bug**
// The bot was running normally.  I used the CONFIG command to change a parameter ( bid order price) and changed it successfully.  I started the bot again and then observed that there where 3 orders on Binance 2 sell and one buy.  I then used the STOP again to manually clean up my orders on Binance. The bot stopped, but continued to issue orders on Binance.
![HBbug](https://user-images.githubusercontent.com/8992858/76187732-3f65b500-622a-11ea-8dc5-960f2e158414.png)

**Release version**
// 24.1 compiled from Source. Running in WSL on W10 pro

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

Discord  :      
[logs_conf_pure_market_making_strategy_11.log](https://github.com/CoinAlpha/hummingbot/files/4304937/logs_conf_pure_market_making_strategy_11.log)
[logs_hummingbot.log](https://github.com/CoinAlpha/hummingbot/files/4304938/logs_hummingbot.log)
[logs_hummingbot.log](https://github.com/CoinAlpha/hummingbot/files/4304940/logs_hummingbot.log)
[logs_conf_pure_market_making_strategy_11.log](https://github.com/CoinAlpha/hummingbot/files/4304941/logs_conf_pure_market_making_strategy_11.log)

dietz
ETH address: 0x0Bd438198559d6d90cf1cF1E5d6c015836d03D16

**Comment by dietzam** [comment]
I actually think the message on the CLI that the bot has stopped is incorrect, because I can see I still got mining rewards.

**Comment by Clint-G13** [comment]
@dietzam are you still getting the same behavior even after restarting your bot or running `exit -f`?This kind of behavior in hummingbot typically occurs when there was an error that occurred during the process. And upon checking your logs, there are orders that failed to submit and cause an error which may have trigger this behavior. For most cases, doing a restart or force exit fix this issue.

**Comment by dietzam** [comment]
exit -f does fix it. But I think it is still a bug. I rather use STOP and start to keep my session history.

**Comment by mifeng** [comment]
I'm closing this for now since we have not been able to replicate this bug yet.
