### ISSUE TITLE
[BUG]Unable to enter any input on Hummingbot after update

### ISSUE THREAD

**Issue by Clint-G13** [CoinAlpha/hummingbot#1514]
**Describe the bug**
After updating to latest development commit and trying to run hummingbot, the screen seems to have frozen and unable to enter anything.

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):
1. Install hummingbot via source and create a development branch or update the current development branch to the latest commit.
2. Used command `git pull origin development` to get the update.
3. Compile using the command `./compile`
4. Start hummingbot after compiling using the command `bin/hummingbot.py`
5. Enter `config` or any text and bot will do nothing.
...

**Screenshots**
WSL and cloud (Source)
![WSL](https://user-images.githubusercontent.com/57189990/76267994-8645c000-62a7-11ea-8238-8fee0de90e1a.PNG)

**Release version**
Tested on the following Environment:
- WSL and Cloud
Note: No issue when using Docker build
```
Branch: Development Only
commit d900c8fd3b99d4045786b8ca8d0644e6d1408239 
Merge: 25491b76 a396471e
Date:   Mon Mar 9 15:58:55 2020 -0700
```

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**
**Optional: your ETH address:** (If you want to participate in the bug bounty)

**Comment by Hashira-Lars** [comment]
Tested on WSL ubuntu 18.04 and have reproduce the same behavior. 

- git checkout development
- git pull origin development
- conda deactivate
- ./install
- conda activate hummingbot
- ./compile
- bin/hummingbot.py
- bot freezes cannot input anything

**Comment by PtrckM** [comment]
Did you apply this commands before git, install and compile?

```
rm -rf $(pwd)/miniconda3/envs/hummingbot
./uninstall
./clean
```

**Comment by Hashira-Lars** [comment]
Tested what sir @PtrckM said and it fixes the issue. did it before executing normal commands.

![image](https://user-images.githubusercontent.com/55869559/76274969-0b879f80-62bd-11ea-961b-bba627ae2e11.png)

**Comment by dennisocana** [comment]
@PtrckM @Hashira-Lars will it also work without this command `rm -rf $(pwd)/miniconda3/envs/hummingbot`?

**Comment by PtrckM** [comment]
@dennisocana for personal experience I always apply `rm -rf $(pwd)/miniconda3/envs/hummingbot` when [updating](https://raw.githubusercontent.com/CoinAlpha/hummingbot/development/installation/install-from-source/update.sh
) (either master, branch testing or development), I don't use that command when its fresh/new install.

**Comment by dennisocana** [comment]
@PtrckM can you try without that command and see if it works? Check if the steps currently outlined in the documentation works or not. If going forward if executing the command is required, then we add it to the docs.

**Comment by PtrckM** [comment]
@dennisocana it does work without the `rm -rf $(pwd)/miniconda3/envs/hummingbot`, tested on both Linux source build and WSL source build. I think that [./uninstall](https://github.com/CoinAlpha/hummingbot/raw/master/uninstall) script already doing it. I also confirm @Hashira-Lars that he does forget doing `./uninstall` and `./clean`

**Comment by dennisocana** [comment]
Thanks @PtrckM for testing and confirming. Closing issue.
