### ISSUE TITLE
[BUG] PMM-Failed to submit order (using 0.24.1) and failed to cancel order (using 0.25.0)

### ISSUE THREAD

**Issue by MishaelTereso** [CoinAlpha/hummingbot#1516]
**Describe the bug**
PMM-Failed to submit order using windows binary version 0.24.1 and failed to cancel order using dev branch 0.25.0. Exchange connectors affected are decentralized exchanges Radar Ralay & Bamboo Relay.

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):
1. Create a new config file with markets Radar and Bamboo Relay as maker markets.
2. Set up your configuration file with these parameters:
- ``order_amount``: 3
- ``min_prof``: 0.01
- ``cancel_order_wait_time``: 60
- ``advance_mode``: false

3. Start the bot.
...

**Screenshots**
![image](https://user-images.githubusercontent.com/56957119/76300933-7dc9a580-62f8-11ea-96f5-85cbea45761c.png)
![image](https://user-images.githubusercontent.com/56957119/76301040-9fc32800-62f8-11ea-8a50-b46047477bc3.png)
![image](https://user-images.githubusercontent.com/56957119/76301088-b0739e00-62f8-11ea-9fa6-5e48ea6a9cc2.png)

**I performed the same configuration on dev branch version 0.25.0 and it places orders but when you ``stop`` the bot, hummingbot won't cancel the order. The order will get stuck at the exchange as an active order.**
![image](https://user-images.githubusercontent.com/56957119/76301412-26780500-62f9-11ea-955b-f0ce43896708.png)

**Release version**
```
"branch": "development",
                "commit": "9fe6986f80da61511a22697bc83878d8a725f694",
                "date": "2020-03-09T02:11:24Z",
                "maintainer": "CoinAlpha, Inc. <dev@coinalpha.com>"

```

**Attachments**
[conf_pmm_strategy_2.txt](https://github.com/CoinAlpha/hummingbot/files/4311672/conf_pmm_strategy_2.txt)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**MishaelT**
**Optional: your ETH address:** (0x98211e49660e5680AeA6bb84b4bDB099bc3BE083)

**Comment by znerol19619** [comment]
@MishaelTereso , I think this is a duplicate issue of this bug report https://github.com/CoinAlpha/hummingbot/issues/1505
