### ISSUE TITLE
Binance.us Connector

### ISSUE THREAD

**Issue by EmpireLinux** [CoinAlpha/hummingbot#1518]
## Exchange Details ✏️

- **Name of exchange**: Binance.us
- **Exchange URL**:https://binance.us
- **Link to API docs**: 
- **Type of exchange**: [x ] Centralized [ ] Decentralized
- **Requester details**: Are you affiliated with the exchange? [ ] yes [ x] no 
  - If yes, what is your role?

## Rationale / impact ✏️
(Describe your rationale for building this exchange connector, impact for hummingbot users/community)
binance.us is a branch of binance that conforms to US regulations for exchanges and it services all of binance US customers. From what I can tell it appears to be identical to the binance website and the connector should be almost a copy/paste action then touch up the urls.  

## Additional information ✏️
(Provide any other useful information that may be helpful to know about this exchange)
It is a relatively new exchange and currently the liquidity is very low so the spread is larger in most pairs, comparing it side-by-side with coinbase-pro the prices are visibly offset and would be an excellent candidate for arbitrage.  
---

⚠️ ***Note: do not modify below here***

## Developer notes

This feature request entails building a new exchange connector to allow Hummingbot to connect to an exchange that is currently not supported.

### Resources
- [Exchange connector developer guide](https://docs.hummingbot.io/developers/connectors/)
- [Discord forum](https://discord.hummingbot.io)

### Deliverables
1. A complete set of exchange connector files as listed [above](#developer-notes-resources).
2. Unit tests (see [existing unit tests](https://github.com/CoinAlpha/hummingbot/tree/master/test/integration)):
  1. Exchange market test ([example](https://github.com/CoinAlpha/hummingbot/blob/master/test/integration/test_binance_market.py))
  2. Order book tracker ([example](https://github.com/CoinAlpha/hummingbot/blob/master/test/integration/test_binance_order_book_tracker.py))
  3. User stream tracker ([example](https://github.com/CoinAlpha/hummingbot/blob/master/test/integration/test_binance_user_stream_tracker.py))
3. Documentation:
  1. Code commenting (particularly for any code that is materially different from the templates/examples)
  2. Any specific instructions for the use of that exchange connector ([example](https://docs.hummingbot.io/connectors/binance/))

### Required skills
- Python
- Previous Cython experience is a plus (optional)

**Comment by vic-en** [comment]
After analyzing both v3 API from binance.com and binance.US with a visual diff software, the result shows that the major difference between both APIs is just their root addresses. In order words, a connector for binance.com would work for binance.US by just altering the base address. All endpoint and responses appear to be thesame.

Diff Software: Meld
Binance.com documentation: https://github.com/binance-exchange/binance-official-api-docs
Binance.US documentation: https://github.com/binance-us/binance-official-api-docs

**Comment by ZeroCool940711** [comment]
Hi, have been there any updates on the binance.us connector?
will it be implemented?

**Comment by Nullably** [comment]
![image](https://user-images.githubusercontent.com/37262506/94101462-79af4080-fe62-11ea-8df1-856ab610d5d3.png)

**Comment by Nullably** [comment]
The `python-binance` that we use is 0.7.1 version, it doesn't have country specific binance support yet.
The 0.7.5 version has 
https://python-binance.readthedocs.io/en/latest/changelog.html
