### ISSUE TITLE
[BUG] Start, Stop, Start error

### ISSUE THREAD

**Issue by Nullably** [CoinAlpha/hummingbot#1519]
**Describe the bug**
Starting and stopping the bot a few times, the bot screen resets to a command line screen with a message to `Press ENTER to continue...` 
The below error is logged in the log file
`
2020-03-11 14:19:31,574 - 55595 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: object NoneType can't be used in 'await' expression
Traceback (most recent call last):
  File "/Users/jack/github/hummingbot/hummingbot/core/utils/async_utils.py", line 7, in safe_wrapper
    return await c
TypeError: object NoneType can't be used in 'await' expression
`

**Steps To Reproduce**
1. Start the bot on pure market making strategy 
2. Stop the bot (by issuing stop command)
3. Key in Start command again
4. If error doesn't appear, repeat step 1-3 again.

**Screenshots**

![image](https://user-images.githubusercontent.com/37262506/76408180-89d06880-63c7-11ea-9752-1f1c946315e9.png)
![image](https://user-images.githubusercontent.com/37262506/76408224-96ed5780-63c7-11ea-843c-fd77f4c1a544.png)

**Comment by rennel-tabing** [comment]
I am unable to reproduce this issue using 0.24.1 - master branch.
I did a multiple start stop (as indicated on step 1-3) . I also did a close, reopen app, start strategy, stop, config, start strategy with no issue found.

@Nullably Can you try on the master branch? the development branch is not stable so might as well not use it for now.

**Comment by Nullably** [comment]
@rennel-tabing Can you please confirm if you can reproduce this in the development branch?
What do you mean when you said the development branch is not stable? The development branch has the latest updates, bug fixes and new features, which will later be applied to the master branch. So very important that it works as expected.

**Comment by Clint-G13** [comment]
We were able to get this issue after updating to the latest development branch, the issue can occur as well if you will be importing a strategy and do step 1-3.

![Capture](https://user-images.githubusercontent.com/57189990/76442986-b5ba1100-63fc-11ea-900b-d1f83e734132.png)
![Capture1](https://user-images.githubusercontent.com/57189990/76442996-b81c6b00-63fc-11ea-8cad-71a7e99ad40a.png)
```
branch: development
commit 7f223556060085ff2ac441c483ce6cce7854aa87 
Merge: 1558e73d 01b9e82b
Date:   Wed Mar 11 08:16:40 2020 +0800
```

**Comment by PtrckM** [comment]
Same behavior when pasting inside hummingbot its either running or just started the bot.

Issue:
Using **Ctrl + V** or **Ctrl + shift + V**

Affected Platform:
Source Build (WSL and Linux) / Docker Build (Windows and Linux)

![image](https://user-images.githubusercontent.com/54516858/76480954-1e2fdf00-644b-11ea-859f-8980e92b78d7.png)

![image](https://user-images.githubusercontent.com/54516858/76480918-0bb5a580-644b-11ea-8e7c-2ab162988efc.png)

**Comment by Hashira-Lars** [comment]
Re-tested with sir @PtrckM said , in my end ctrl+v or ctrl+shift+v triggers the behavior (paper-trade=off) when paper-trade is on nothing happens.

![image](https://user-images.githubusercontent.com/55869559/76483590-5edf2680-6452-11ea-9b0e-4827d8067ee3.png)

![image](https://user-images.githubusercontent.com/55869559/76483600-64d50780-6452-11ea-8ca1-1cfaf37fd322.png)

**Comment by mifeng** [comment]
@Hashira-Lars @PtrckM Are you seeing that behavior with the paste commands on `development` or `master`?

**Comment by PtrckM** [comment]
@mifeng behavior affects on delevopment branch

**Comment by Clint-G13** [comment]
Re-tested this issue and confirm fix when running from Source, however, if we test using docker build, the issue still persists.
![stop start error3](https://user-images.githubusercontent.com/57189990/77102642-65cbe300-69d6-11ea-9e6d-625272b0dc44.PNG)
```
branch": "development,
commit": "2cb30669e98b745915bf91189af783d19d5a3341,
date": "2020-03-19T17:41:05Z,
maintainer": "CoinAlpha, Inc. <dev@coinalpha.com>
```

**Comment by Clint-G13** [comment]
Confirm fix on both docker and source build after the latest development push
```
branch": "development
commit": "67e2c1d2b630796380068405fc062dd89718117d
date": "2020-03-19T18:41:59Z
maintainer": "CoinAlpha, Inc. <dev@coinalpha.com>
```
