### ISSUE TITLE
[BUG] PMM | Bot placing order below the exchange minimum order size

### ISSUE THREAD

**Issue by Clint-G13** [CoinAlpha/hummingbot#1536]
**Describe the bug**
Hummingbot creates an order that is below the exchanges minimum order size and if you will verify the order on the exchange, the order is not available.

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):
1. Override the minimum order size on the global config file
2. Create a pure market making strategy.
3. Set a wide-spread for both bid and ask thresholds (for this test 0.4 spread is use)
4. Set order_amount and order_start_size just as close as the minimum trade size allowed by the exchange (for this test, 3 is use as the value of order_amount and order_start_size)
5. Start bot and you will see an order that is being created with the quantity that is below the exchange minimum order size.

**Screenshots**
Single order test
![Single order](https://user-images.githubusercontent.com/57189990/77022417-d1666f80-6946-11ea-98d1-f08031445a4b.PNG)
![Single order1](https://user-images.githubusercontent.com/57189990/77022426-d5928d00-6946-11ea-962a-3dfb3882fe8d.PNG)

Multiple order test
![Test RLC-BTC with tight spread2](https://user-images.githubusercontent.com/57189990/77022448-df1bf500-6946-11ea-9c52-e19ec34e20bf.PNG)
![Test RLC-BTC exchange](https://user-images.githubusercontent.com/57189990/77022456-e3e0a900-6946-11ea-8cb2-b7681be2c16f.PNG)

**Release version**
Master branch (0.24.1)

**Attachments**

[logs_conf_pure_market_making_strategy_0 (1).log](https://github.com/CoinAlpha/hummingbot/files/4352225/logs_conf_pure_market_making_strategy_0.1.log)
[Strategy file-PMM.txt](https://github.com/CoinAlpha/hummingbot/files/4352227/Strategy.file-PMM.txt)

Note: Logs and Strategy use ONE-BTC pair and also, behavior seems to happen when using wide- spread only.

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**
**Optional: your ETH address:** (If you want to participate in the bug bounty)

**Comment by Hashira-Lars** [comment]
I think this is expected behavior because `inventory_skew` is enabled the order amount will be dynamic. not sure though

**Comment by mifeng** [comment]
This is expected behavior. Hummingbot's minimum order size are intended to prevent beginner users from accidentally creating a strategy with too small order sizes. This is needed because We don't load the exchange trading rules when the user is creating a strategy so we don't have the exchange-specific rules. 

Advanced users can eliminate those constraints by editing `conf_global.yml`.

When the bot starts, the actual exchange rules are applied.
