### ISSUE TITLE
[BUG] Incorrect Total Order Amount on Inventory Skew table 

### ISSUE THREAD

**Issue by Nullably** [CoinAlpha/hummingbot#1540]
**Describe the bug**
The total order amount shown on Inventory Skew table (0.8 DASH) is much higher than actual (0.443, all submitted order amount). 
Also the Target base asset range looks off.

![image](https://user-images.githubusercontent.com/37262506/77129928-ccadd280-6a90-11ea-91a2-67a118b0c1d6.png)

**Steps To Reproduce**
Start the bot on Pure Market Making strategy with the following configs:

```
maker_market: binance
maker_market_trading_pair: DASH-ETH
order_amount: 0.4
bid_place_threshold: 0.02
ask_place_threshold: 0.02
advanced_mode: true
mode: single
inventory_skew_enabled: true
inventory_target_base_percent: 50.0
inventory_range_multiplier: 1.0
```

After bot starts creating orders, run Status command.

**Release version**
development

**Comment by mifeng** [comment]
I think this occurs b/c the order amount is 180% of the total assets that the user has

**Comment by Nullably** [comment]
@mifeng Sorry, I don't quite follow. This is a normal spot trading testing account, it cannot have more total active orders amount than the total assets the account has.

**Comment by mifeng** [comment]
These settings are nonsensical:
* The account has 0.4 DASH and a tiny amount of ETH (92% DASH / 8% current split)
* Order amount is 0.4 DASH
* Target inventory split is 50%

Given the order size, it's mathematically impossible for the bot to hit 50% inventory split. The Total Order Amount is equal to 0.4 DASH x2, which would be correct if there were more ETH in the portfolio. After @dennisocana's fix(https://github.com/CoinAlpha/hummingbot/pull/1559), the Target base asset range will say 0 to 100%, which is correct.

While we may be able to change the UI to better inform users about what's going on, for now I think we should just explain to users why these settings don't make sense.

**Comment by Nullably** [comment]
@mifeng Ok, so the Total Order Amount is Order Amount * sides (0.8 DASH), not actually the total order amount that the bot puts and shown on the screen which is 0.443 DASH. But isn't this a bug?

**Comment by mifeng** [comment]
I think it's a communication/UX issue, not a bug. Inventory Skew needs to use the "intended" order amount to adjust the sizes, since the actual sizes are a result of the adjustment.

As part of this Clubhouse story (https://app.clubhouse.io/coinalpha/story/8078/reassess-inventory-skew-multiple-order-levels), I'll take a fresh look at how we use the order amount in figuring out Inventory Skew. Pretty sure that we can improve the UX around using it.
