### ISSUE TITLE
[Feature] Bid order price rounded up

### ISSUE THREAD

**Issue by Nullably** [CoinAlpha/hummingbot#1543]
**Feature Suggestion**
Currently Hummingbot always rounds order price down when creating order proposal. This, in some cases, results in order price spread greater than `bid_place_threshold` setting and, in turn, could make the order not eligible for mining reward (if the threshold is set at the edge of mining reward spread limit).

This screenshot is taken right after the bot submits orders, both `bid_place_threshold` and `ask_place_threshold` are configured to 0.01.
![image](https://user-images.githubusercontent.com/37262506/77143294-d13cb000-6abd-11ea-852b-af86f260bb85.png)

The requested feature is to round the price up for bid orders.

**Comment by mifeng** [comment]
I think we should apply order logic as follows:
1. set spread mathematically
2. quantize - if sell order, quantize up to next tick; if buy order, quantize down to next tick

**Comment by vic-en** [comment]
I believe this feature has been implemented

<img width="392" alt="buy" src="https://user-images.githubusercontent.com/31972210/84912197-14a0bd80-b0b1-11ea-8fc3-ec9a4836decc.PNG">
<img width="392" alt="sell" src="https://user-images.githubusercontent.com/31972210/84912205-19657180-b0b1-11ea-8ba1-f4cde4bfd3a0.PNG">

This can be closed now.
