### ISSUE TITLE
[BUG] Hummingbot Windows Binary 0.25.0 unable to type

### ISSUE THREAD

**Issue by PtrckM** [CoinAlpha/hummingbot#1551]
**Describe the bug**
Hummingbot Windows Binary unable to type commands after installation.

**Steps To Reproduce**

Here are the steps to reproduce the issue (see attachments in the section below):
1. download new version of [hummingbot 0.25.0](https://hummingbot-distribution.s3.amazonaws.com/hummingbot_v0.25.0_setup.exe)
2. uninstall 0.24.1 on local pc
3. install the new version
4. run
...

**Screenshots**
![image](https://user-images.githubusercontent.com/54516858/77379342-748a0f80-6db3-11ea-898e-bba8c2d63ca1.png)

**Release version**
0.25.0

**Comment by dennisocana** [comment]
For documentation : Issue has been resolved with the new binary installer.

![image](https://user-images.githubusercontent.com/50150287/77386216-47465d00-6dc5-11ea-828b-bb9548e47c2a.png)

Although after testing, some users are getting a different error with Hummingbot crashing after 5 seconds. Patrick was advised to create a new GitHub issue related to that bug.
