### ISSUE TITLE
[BUG] Hummingbot Windows Binary 0.25.0 crashing

### ISSUE THREAD

**Issue by PtrckM** [CoinAlpha/hummingbot#1553]
**Describe the bug**
Hummingbot crashing after 5 seconds

**Steps To Reproduce**

Here are the steps to reproduce the issue (see attachments in the section below):
1. download latest version of [hummingbot windows binary 0.25.0](https://hummingbot-distribution.s3.amazonaws.com/hummingbot_v0.25.0_setup.exe)
2. uninstall previous version locally
3. install [0.25.0](https://docs.hummingbot.io/release-notes/0.25.0)
4. run hummingbot application

...

**Screenshots**
![image](https://user-images.githubusercontent.com/54516858/77386165-254cda80-6dc5-11ea-8dd0-1602d083c250.png)

**Release version**
0.25.0

**Comment by Hashira-Lars** [comment]
Tested on Windows 10 pro version and have reproduce the behavior.

-installing = no error
-bot crashes upon opening hb

![image](https://user-images.githubusercontent.com/55869559/77386820-c1c3ac80-6dc6-11ea-856e-7984e59f7bda.png)

**Comment by martinkou** [comment]
What is your Windows build number?

**Comment by PtrckM** [comment]
Microsoft Windows 10 Home
Version 10.0.18363 Build 18363

Microsoft Windows 10 Enterprise
Version 10.0.17134 Build 17134

**Comment by clarodarg** [comment]
Hi everyone, I have the same issue.

![win](https://user-images.githubusercontent.com/62623294/77476460-665ee200-6df9-11ea-83d9-3a93905c222b.png)
![image](https://user-images.githubusercontent.com/62623294/77476483-71b20d80-6df9-11ea-80bb-866f43dacf9a.png)

**Comment by Hashira-Lars** [comment]
![image](https://user-images.githubusercontent.com/55869559/77486287-44517800-6e6a-11ea-9b13-5245bf98942f.png)

here is mine sir @martinkou

**Comment by clarodarg** [comment]
Hi Everyone, any news about that?

Many thanks !!!

**Comment by Hashira-Lars** [comment]
Hi @clarodarg I've re-tested (re-download/re-install) and the issue still persist. 

Let's wait for further update from the Team.

**Comment by mifeng** [comment]
We upgraded the most recent version to Python 3.8, so that's probably what's causing it but it's only on certain Windows builds, so we are still trying to reproduce and fix. The Docker version should be used in the meantime on Windows.

**Comment by clarodarg** [comment]
Ok. good. Thanks

**Comment by PtrckM** [comment]
As a **WORKAROUND** try installing or updating your [MS Visual C++ Redistributable 2015, 2017 and 2019 Runtime](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads) for x86: [vc_redist.x86.exe](https://aka.ms/vs/16/release/vc_redist.x86.exe) or x64: [vc_redist.x64.exe](https://aka.ms/vs/16/release/vc_redist.x64.exe).
