### ISSUE TITLE
[Feature] Volatility Skew

### ISSUE THREAD

**Issue by Blacksage-beep** [CoinAlpha/hummingbot#1555]
**Feature Suggestion**
// A succinct description of **how you want to achieve the desired behavior**.
Hey guys! First of all, I want to say that I am excited to try out the new features of the 0.25.0 version as they look very neat. I also wanted to add one suggestion how to battle the inventory risk which I saw professional Market Makers  do during the volatile time
So whenever I was trading FX/Stocks and worked either for a market maker or a taker(prop shop) what I saw people doing during the volatile times was that the MMs increased the spreads(so for example from 1 % to 3%) everytime a news event was out or anything which caused volatility

So a volatility skew feature basically. Everytime the price moves x in y amount of seconds, the spread widens by x for the duration of y seconds

**Impact**
That way when there is a huge move in prices, the market maker is able to capture the best price whereas when the spread stays static the market maker captures the worst price

**Additional context**

**Comment by veecos2** [comment]
I had also suggested adding this feature a year ago for the above reasons.

**Comment by mifeng** [comment]
You can do this with the new [Scripts](https://docs.hummingbot.io/advanced/scripts/) feature in v0.29.0. In particular, the `spreads_adjusted_on_volatility_script.py` example allows you to adjust spreads based on market volatility.
