### ISSUE TITLE
[BUG] history command showing past trades incorrectly when more than one instance of the bot is running

### ISSUE THREAD

**Issue by neohowie** [CoinAlpha/hummingbot#1556]
**Describe the bug**
// A clear and concise description of what the bug is.
I have 2 instances of Hummingbot running at the moment locally. I ran instance A (ONE/BTC) first and then have another instance B (ENG/BTC) turned on. When I check the past trades of each instance by using the "history" command, in both scenario, the program returns the past trades of the instance B running the ENG/BTC pair. Shouldn't it only show the past trades of the pair the bot is running on?  

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:
As per above. 

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: ...
2. Start the bot using this command: ...
...

**Screenshots**
// If applicable, add screenshots to help explain your problem.

<img width="1395" alt="Screenshot 2020-03-24 at 7 08 33 PM" src="https://user-images.githubusercontent.com/1378301/77419283-1f75ea00-6e03-11ea-9e41-e6504d76158b.png">

<img width="1192" alt="Screenshot 2020-03-24 at 7 08 56 PM" src="https://user-images.githubusercontent.com/1378301/77419313-27ce2500-6e03-11ea-8617-871d4c6d38ba.png">

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).
0.25.0

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

[conf_pure_market_making_strategy_engbtc.yml.txt](https://github.com/CoinAlpha/hummingbot/files/4374871/conf_pure_market_making_strategy_engbtc.yml.txt)
[conf_pure_market_making_strategy_onebtc.yml.txt](https://github.com/CoinAlpha/hummingbot/files/4374872/conf_pure_market_making_strategy_onebtc.yml.txt)

[logs_conf_pure_market_making_strategy_onebtc.log.txt](https://github.com/CoinAlpha/hummingbot/files/4374876/logs_conf_pure_market_making_strategy_onebtc.log.txt)
[logs_conf_pure_market_making_strategy_engbtc.log.txt](https://github.com/CoinAlpha/hummingbot/files/4374877/logs_conf_pure_market_making_strategy_engbtc.log.txt)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**
Howie#7291

**Optional: your ETH address:** (If you want to participate in the bug bounty)

**Comment by Hashira-Lars** [comment]
issue same with #1471
