### ISSUE TITLE
[BUG] MetaMask wallet not connecting the first time in Miner's app

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#1558]
**Describe the bug**

MetaMask wallet does not connect to the miner's app right away the first time. It will be stuck and you have to refresh the page then re-attempt to connect the wallet to make it work.

![IIlg4cKyL6](https://user-images.githubusercontent.com/50150287/77500267-850fb800-6e8f-11ea-9ea7-9a9ec29cedda.gif)

**Steps To Reproduce**

1. Close web browser
2. Re-launch browser and go to https://miners.hummingbot.io/
3. Connect to MetaMask wallet and enter password
5. Click **Connect** then **Sign In**

Then it will be stuck in "Connecting to MetaMask".

**Comment by yzhang1994** [comment]
@dennisocana I have merged a fix for this. Could you please test again? Thanks!

**Comment by dennisocana** [comment]
@yzhang1994 yes, it worked perfectly this time. Thanks!
