### ISSUE TITLE
[BUG] Arbitrage buying high and selling low

### ISSUE THREAD

**Issue by rennel-tabing** [CoinAlpha/hummingbot#1561]
**Describe the bug**
// A clear and concise description of what the bug is.
Arbitrage strategy should always execute orders that buys low and sells high at a given point in time however, test shows that there are trades that are doing the opposite (buying high and selling low)

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: ...

```
#####################################
###   Arbitrage strategy config   ###
#####################################

template_version: 2

# The following configurations are only required for the
# arbitrage strategy

# Exchange and token parameters
primary_market: binance
secondary_market: kucoin
primary_market_trading_pair: NULS-BTC
secondary_market_trading_pair: NULS-BTC

# Minimum profitability target required to place an order
# Expressed in decimals: 0.01 = 1% target profit
min_profitability: 0.0045

```
**Screenshots**
// If applicable, add screenshots to help explain your problem.

![image](https://user-images.githubusercontent.com/53868268/77559925-277d6a80-6e93-11ea-96d0-81f7db34115b.png)

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).
0.25.0
**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 
[logs_conf_arbitrage_strategy_0.txt](https://github.com/CoinAlpha/hummingbot/files/4382111/logs_conf_arbitrage_strategy_0.txt)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:** n1njawtf
**Optional: your ETH address:** (If you want to participate in the bug bounty)

**Comment by Hashira-Lars** [comment]
A user reported he's experiencing this behavior on live trading where his bot buy high and sells low. 

![image](https://user-images.githubusercontent.com/55869559/77604038-8357fa00-6f4c-11ea-9feb-c9a095a0b30a.png)

#beastleb (convo in spreadsheet)

**Comment by mifeng** [comment]
The arbitrage strategy does not guarantee that it always buys and and sells high. It places simultaneous market orders when it detects an arbitrage opportunity. However, it may lose out to another bot.
