### ISSUE TITLE
GUI price reporting precision linked to exchange precision 

### ISSUE THREAD

**Issue by Steve1943** [CoinAlpha/hummingbot#159]
**Feature Suggestion**
Presently the GUI reports coin prices to 6 decimal places for all coins.  For coins with low prices (relative to their counterpart in the pair) this can yield odd results due to excessive rounding. 
For example, the DNT-ETH pair is quoted to 7 decimals in Radar Relay and to 8 on Binance.
I suggest that the reporting precision be set to the finer of the two exhanges. 

**Impact**
Provide more realistic information upon which traders might tune their profit margin targets.

**Additional context**
https://drive.google.com/file/d/1QesHhLfUIm_oRYWmpWfJmLyYXx8Dz6hh/view?usp=sharing
https://drive.google.com/file/d/19ZtPKheugeD4XsaDMaSgDDMSsHz80rzS/view?usp=sharing
https://drive.google.com/file/d/1l3DUOwtccFTWiLN6QIFkcAibf6_8x8zY/view?usp=sharing

**Comment by Steve1943** [comment]
Alternatively, allow users to adjust the precision of price reporting for each coin in their strategy file.  
Assume a default value (eg 6 decimals) if nothing else is specified.

**Comment by Steve1943** [comment]
Another alternative to consider - express small numbers in scientific notation.  

This is fixed width to display - and facilitates rapid comprehension of price comparisons e.g. bid vs ask -  or price differences between exchanges.  Saves counting zeros!

**Comment by martinkou** [comment]
This means we need to adjust the data frame display precision depending on the symbol's quantization parameters.

Assigning this to myself for now. Will come back to this later.

**Comment by mifeng** [comment]
Added to Backlog
