### ISSUE TITLE
[BUG] Unable to connect Atomic wallet using Walletconnect on Hummingbot miner app

### ISSUE THREAD

**Issue by Clint-G13** [CoinAlpha/hummingbot#1592]
**Describe the bug**

Failed to connect or register wallet on hummingbot liquidty mining page with Error: An unknown error occurred: Error: Invariant failed

**Steps To Reproduce**

Here are the steps to reproduce the issue (see attachments in the section below):
1. Install **Atomic wallet** to your mobile device.
2. Go to the Hummingbot liquidity mining page and click the **Connect wallet**.
3. Choose **WalletConnect** since we don't have option to enter the public/private key.
4. From your Atomic wallet app, click the cog/gear icon and choose **WalletConnect.**
5. Scan the bar code provided on the liquidity mining app.
6. Provide permission to Hummingbot.
7. After confirming that Hummingbot is approved, on your Atomic wallet app, check the registration page and you will see an unknown error.
...

**Screenshots**
![Connect Atomic wallet](https://user-images.githubusercontent.com/57189990/78629713-69ae9f00-78ca-11ea-8de8-c0dc06e1e275.PNG)

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**
**Optional: your ETH address:** (If you want to participate in the bug bounty)

**Comment by rennel-tabing** [comment]
I had the same behavior on an IOS device.  The Atomic Wallet shows that hummingbot is already connected with it but an error is shown on the miner app.

This issue could be related to this https://lifesaver.codes/answer/invariant-violation-you-should-not-use-route-or-withrouter()-outside-a-router

**Comment by yzhang1994** [comment]
Did some research and found that Atomic wallet only allows walletconnect login with Binance wallet, not Ethereum wallet: https://support.atomicwallet.io/article/116-how-to-use-wallet-connect

Unfortunately, there isn't really a way to fix that. But I will try to show users a more helpful message.
