### ISSUE TITLE
[BUG] question: portfolio management

### ISSUE THREAD

**Issue by Amarchuk** [CoinAlpha/hummingbot#1594]
Hi,

I check all the docs and try to find examples, but still not sure about. My usecase strategy is simple to formulate: I have a portfolio with some weights (for example [0.25, 0.5, 0.25, 0.0]) and on each step I have new prediction of the weights and thus need to sell/buy several pairs to rebalance according to prediction. Previously I did this manually calculating limit prices and tradable amount and it works more or less correctly. And I try to understand if it possible to develop such approach here, because really wanted to use all cool features `hummingbot` propose.

If a question covered in documentation - link is appreciated. Thanks!

**Comment by devoger** [comment]
What you are trying to achieve is not yet possible in the current feature of Hummingbot.
It is best to change the label of this request from Bug to Feature request so we can easily track this request in the future.

**Comment by Amarchuk** [comment]
Thanks for the answer! It was actually not a feature request, more like a question
