### ISSUE TITLE
[BUG]Hummingbot miner app unable to connect to Ledger Nano S

### ISSUE THREAD

**Issue by devoger** [CoinAlpha/hummingbot#1601]
**Describe the bug**
// A clear and concise description of what the bug is.

Unable to connect or register a wallet on Hummingbot miner app using Ledger Nano S.
The latest firmware version 1.6 of Ledger Nano S doesn't have a Browser Support option available under ETH app.

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):

1. Login to your Ledger and open ETH app
2. Click "Connect Wallet" button at the top right navigation of the miner app page
3. Select "Ledger" to connect your Ledger
![Screen Shot 2020-04-08 at 16 21 16](https://user-images.githubusercontent.com/8411294/78762402-642e8300-79b6-11ea-935e-eedd34bbafc2.png)

4. A window will appear with detailed guide how to connect to your Ledger. In order to connect, we must enable Contract Data & Browser Support under ETH app settings.

The problem is that the recent Firmware version 1.6 of Ledger doesn't have Browser Support option available so the Ledger unable to detect.

![Screen Shot 2020-04-08 at 16 31 41](https://user-images.githubusercontent.com/8411294/78762481-7c9e9d80-79b6-11ea-97f3-e283adab3421.png)

5. After 3 seconds, the window will refresh and will give you the Metamask window instead even though I did not select Metamask and I don't have it instead on my browser.

![Screen Shot 2020-04-08 at 16 32 54](https://user-images.githubusercontent.com/8411294/78762990-3269ec00-79b7-11ea-9257-27b198a0fbeb.png)

...

**Screenshots**
// If applicable, add screenshots to help explain your problem.

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).

Ledger Nano S firmware version 1.6

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**
**Optional: your ETH address:** (If you want to participate in the bug bounty)

**Comment by yzhang1994** [comment]
@devoger This should be fixed by https://github.com/CoinAlpha/hummingbot-miners/pull/149

**Comment by yzhang1994** [comment]
@devoger I deployed a fix for this bug,  please try again and let me know if it works for you now.

**Comment by devoger** [comment]
Confirmed fix.
