### ISSUE TITLE
[BUG] Paper_trade command on Telegram does not toggle the feature on hummingbot

### ISSUE THREAD

**Issue by rennel-tabing** [CoinAlpha/hummingbot#1605]
**Describe the bug**
// A clear and concise description of what the bug is.
Clicking the `paper_trade` button or issuing the command on telegram does not change any existing config

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:
1. Connect the hummingbot on telegram
2. Run a `paper_trade` command inside the telegram or click the `paper_trade box`

You will notice that issuing the command or clicking the paper trade box does not have any effect on the hummingbot 
...

**Screenshots**
![image](https://user-images.githubusercontent.com/53868268/78917103-6c40fe00-7a5c-11ea-88db-054a2302f4aa.png)

**Release version**
dev-0.26.0

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**
**Optional: your ETH address:** (If you want to participate in the bug bounty)

**Comment by PtrckM** [comment]
here's an update: improve telegram integration https://github.com/CoinAlpha/hummingbot/pull/1611

**Comment by dennisocana** [comment]
Paper trade command is not supported in Telegram.
