### ISSUE TITLE
never sell with a loss

### ISSUE THREAD

**Issue by bashir1961** [CoinAlpha/hummingbot#1634]
**Feature Suggestion**
In pure market making mode sometimes it happens that market goes down, the bot has a buy order filled, market goes down again and bot has a sell order filled at a lower price than the buy order, that is bot sells with a loss. It would be interesting to have a boolean checking the previously filled buy price, before making a sell order, so we should never have a loss.

**Impact**
// A succinct description of **why you want the _desired behavior_** specified above.
Extra safety, in addition to kill switch.

**Additional context**
This is just a sketchy request,from a user point of view, no code,

**Comment by mifeng** [comment]
Can you elaborate on the logic in pseudo-code for this parameter? I'm in favor of adding params that help make the bot safer, want to make sure I'm clear what you mean.

**Comment by bashir1961** [comment]
ok, I try, did not read your code though
// when an order is filled
last_buy = order_that_is_filled
// before placing a sell order
if ( parameter)
if ( sell_order > last_buy )
    this is ok;
else
   we are trying to sell at a lower price than what we bought
endif
endif

**Comment by phbrgnomo** [comment]
Being implemented here:

https://github.com/CoinAlpha/hummingbot/pull/2332

@mifeng This issue can be closed.

**Comment by mifeng** [comment]
Thanks @phbrgnomo feel free to close these types of issues in the future
