### ISSUE TITLE
[BUG] Dolomite - Object has no attribute capitalize

### ISSUE THREAD

**Issue by rennel-tabing** [CoinAlpha/hummingbot#1646]
**Describe the bug**
// A clear and concise description of what the bug is.
Using Dolomite as an exchange to run a strategy will give errors causing the strategy to fail

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:
1. Create a Discovery Strategy using Dolomite and Binance as an exchange
```
#####################################
###   Discovery strategy config   ###
#####################################

template_version: 2

# The following configuations are only required for the discovery strategy

# Exchange and token parameters
primary_market: binance
secondary_market: dolomite
target_trading_pair_1: []
target_trading_pair_2: []

# Minimum profitability target required to place an order
# Expressed in decimals: 0.01 = 1% target profit
target_profitability: 0.0
target_amount: .inf

# Tokens that the bot assumes are equivalent
equivalent_tokens:
- - USDT
  - USDC
  - USDS
  - DAI
  - PAX
  - TUSD
  - USD
- - ETH
  - WETH
- - BTC
  - WBTC

```

2. Run the strategy

**Screenshots**
Here is the error after running the Discovery strategy

![image](https://user-images.githubusercontent.com/53868268/80004634-8fbe6c80-8490-11ea-8c83-39c69dc27245.png)

Similar error will reflect when running Pure market making

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).
0.25.0
dev-0.26.0

**Attachments**
[logs_conf_Dolomite_PMM.log](https://github.com/CoinAlpha/hummingbot/files/4517340/logs_conf_Dolomite_PMM.log)
[logs_discovery_Dolomite-Binance.log](https://github.com/CoinAlpha/hummingbot/files/4517341/logs_discovery_Dolomite-Binance.log)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**
**Optional: your ETH address:** (If you want to participate in the bug bounty)

**Comment by PtrckM** [comment]
Discovery Strategy Deprecated

**Comment by dennisocana** [comment]
Closing since we already deprecated discovery strategy.
