### ISSUE TITLE
[BUG] Orders not filled in paper trade mode if more per side

### ISSUE THREAD

**Issue by leftys** [CoinAlpha/hummingbot#1647]
**Describe the bug**
I noticed orders rarely fill in paper trading mode and probably found a bug happening when more orders are open per side for example in pure market making. Then an order is filled just when all the orders would be filled (even the deepest order in the book).

**Release version**
0.25.0

**Possible cause**
I think the problem is in this code:
```
        if is_maker_buy:
            orders_rit = orders_collection_ptr.rbegin()
            while orders_rit != orders_collection_ptr.rend():
                cpp_limit_order_ptr = address(deref(orders_rit))
                if <object>cpp_limit_order_ptr.getPrice() <= trade_price:
                    break
                process_order_its.push_back(getIteratorFromReverseIterator(
                    <reverse_iterator[SingleTradingPairLimitOrdersIterator]>orders_rit))
                inc(orders_rit)
```
The orders seem to be iterated from the deepest and fill only happens when even the deepest order is to be filled.

Not sure if eligible, but my eth address: 0x0696f26e5644ea656d50e3693fd646d46cd64a8d

**Comment by vic-en** [comment]
@leftys 
The logic is very correct.

Try doing something like this:
```
         if is_maker_buy:
            orders_rit = orders_collection_ptr.rbegin()
            while orders_rit != orders_collection_ptr.rend():
                cpp_limit_order_ptr = address(deref(orders_rit))
                # if <object>cpp_limit_order_ptr.getPrice() <= trade_price:
                #    break
                print(<object>cpp_limit_order_ptr.getPrice())
                process_order_its.push_back(getIteratorFromReverseIterator(
                    <reverse_iterator[SingleTradingPairLimitOrdersIterator]>orders_rit))
                inc(orders_rit)
```

You'll notice that it starts iterating from the deepest order.
The commented if block session makes it stop iteration when a trade price wouldn't fill any more order.
