### ISSUE TITLE
[Bug] Inventory skew breaks with low range multiplier and multiple orders

### ISSUE THREAD

**Issue by FinLouarn** [CoinAlpha/hummingbot#1657]
**Describe the bug**
With Inventory skew activated, the bot is placing more aggressive buy orders in numbers and amounts even if I´m already above the Target asset base range.
For instance I set a 50% target (RLC/USDT) with a small multiplier 0.25, resulting in a range in between 26.1 - 73.9 %, which seems ok, and my inventory is already out of range with 76.6% of the base asset (RLC). But the bot is placing more aggressive buy orders than sell, in numbers and amounts.
PS: I set multiple orders at 3. (cf list configs screenshot )

**Steps To Reproduce**
This happened from starting the bot, no need to wait many iterations.
I run version 0.25.0, installed with docker, on AWS t3a small instance.
starting the bot with ./start.sh script, importing the config file (cf list configs screenshot)
then adjust few parameters of the config and start.

**Screenshots**
Here is list configs and status screenshots.
![hb-list_configs-screenshot](https://user-images.githubusercontent.com/6131050/80195184-c4126400-861b-11ea-9548-9327288a505e.jpg)
![hb-status-screenshot](https://user-images.githubusercontent.com/6131050/80195187-c5439100-861b-11ea-97eb-de1a37fe9efb.jpg)

[conf_pure_market_making_strategy_0.txt](https://github.com/CoinAlpha/hummingbot/files/4527893/conf_pure_market_making_strategy_0.txt)

**Release version**
0.25.0 master branch

**Optional: your discord username: finfox
**Optional: your ETH address: 0x6973126F86969ABbe371c130268A1E255F7d59E6

**Comment by PtrckM** [comment]
Inventory Skew + Hanging Orders
- we do not recommend to use them both at the same time, basically, they are two different methods trying to do the same objective

**Comment by FinLouarn** [comment]
I can understand, but as you can see on the status there is no hanging orders, since the bot was just starting.

**Comment by FinLouarn** [comment]
I have disabled hanging orders, kept similar others config parameters, and still even if my inventory is already above the higher boundary of my Target base asset range, the bot is placing 3 buy orders and no sell orders.

![hb-status2-screenshot](https://user-images.githubusercontent.com/6131050/80304581-41bea700-87b7-11ea-933f-ce1bd30bcba0.jpg)

The issue remain.

**Comment by mifeng** [comment]
We should make inventory skew and hanging orders play nicely together. This combination fits a common market making strategy well.

**Comment by mifeng** [comment]
Actually this is a different issue. This is related to the way that the range multipler parameter currently works. I will propose a different fix for that feature.

**Comment by FinLouarn** [comment]
> Actually this is a different issue. This is related to the way that the range multipler parameter currently works. I will propose a different fix for that feature.

To give another exemple, here the target %, inventory range, order adjust %, seems correctly calculated, but the bot place only buy orders with amounts adjusted by 200%, when it should place sell orders adjusted with 200%, since I´m already above of the inventory range. This happen just after starting the bot, from the first orders, before any trades are done. No paper_mode, no hanging_orders.
![hb_screenshot_2020-05-16_12-30-31](https://user-images.githubusercontent.com/6131050/82118335-f6286900-9776-11ea-8aeb-bc4c8240a1ea.png)
