### ISSUE TITLE
[BUG] Trades appear multiple times in history list

### ISSUE THREAD

**Issue by leftys** [CoinAlpha/hummingbot#1663]
**Describe the bug**
When I run `history` command some trades appear twice, see example bellow. Tested with pure market making on binance.

**Example**
```
    10  RLCETH 0.001704    6.97      limit  sell  binance  2020-04-25 10:27:40        0.001 
    11  RLCETH 0.001711   17.38      limit  sell  binance  2020-04-25 12:48:35        0.001
    12  RLCETH 0.001711   17.38      limit  sell  binance  2020-04-25 12:48:35        0.001
    13  RLCETH 0.001711    0.02      limit  sell  binance  2020-04-25 12:48:35        0.001
    14  RLCETH 0.001721    8.46      limit  sell  binance  2020-04-25 13:14:30        0.001
```
Trade id 11 and 12 are the same according to binance trade list.

**Release version**
0.25.0

**Comment by PtrckM** [comment]
What build of hummingbot are you using? Binary installer, Source Build, Docker Build? Are you running the bot with other token pair within the same instance? Have you try the [new version](https://docs.hummingbot.io/release-notes/0.26.0) of [hummingbot 0.26.0](https://hummingbot.io/download/) and see if problem still persist?

Providing the strategy config and recent logs will also help to determine the problem.

**Comment by leftys** [comment]
I am using source build, will try to upgrade and upload recent logs as well. Config follows:
```
########################################################
###       Pure market making strategy config         ###
########################################################

template_version: 10

############  Basic configuration section  ############

# Exchange and token parameters.
maker_market: binance
maker_market_trading_pair: RLC-ETH

# Size of your bid and ask order.
order_amount: 50.0

# How far away from mid price to place the bid order.
# Expressed in decimals : 0.01 = 1% away from mid price at that time.
# Example if mid price is 100 and bid_place threshold is 0.01.
# Your bid is placed at 99.
bid_place_threshold: 0.006

# How far away from mid price to place the ask order.
# Expressed in decimals : 0.01 = 1% away from mid price at that time.
# Example if mid price is 100 and ask_place threshold is 0.01.
# Your bid is placed at 101.
ask_place_threshold: 0.002


# Time in seconds before cancelling and rerunning strategy.
# If tick size is 60, the bot cancels active orders and reruns after a minute.
cancel_order_wait_time: 30.0

# Whether to enable advanced configuration setting (true/false).
# Only used when creating a new configuration file.
advanced_mode: true

############  Advanced configuration section  ############

# Ox ONLY - Sets the expiration of limit orders. Minimum is 130 seconds.
expiration_seconds: 130.0

# Whether to single or multiple bids and asks.
mode: multiple

# Number of orders to place on each side of the order book (for multiple orders mode).
number_of_orders: 1

# Size of the first bid and ask order (for multiple orders mode).
order_start_size: 50.0

# Increment size of consecutive orders after the first order (for multiple orders mode).
order_step_size: 100.0

# Order price space between orders (for multiple orders mode).
order_interval_percent: 0.002

# Whether to enable Inventory skew feature (true/false).
inventory_skew_enabled: true

# Target base asset inventory percentage target to be maintained (for Inventory skew feature).
inventory_target_base_percent: 50.0

# The range around the inventory target base percent to maintain, expressed in multiples of total order size (for
# inventory skew feature).
inventory_range_multiplier: 2.0

# How long to wait before placing the next order in case your order gets filled.
filled_order_replenish_wait_time: 300.0

# Whether to stop cancellations of orders on the other side when one side is filled (hanging orders feature) (true/false).
enable_order_filled_stop_cancellation: false

# Spread (from mid price, in percentage) hanging orders will be canceled (Enter 0.01 to indicate 1%)
cancel_hanging_order_pct: 0.0
# The depth in base asset amount to be used for finding top bid and ask (for best bid ask jumping mode).
best_bid_ask_jump_orders_depth: 0.0

# Whether to enable adding transaction costs to order price calculation (true/false).
add_transaction_costs: false

# Whether to use external pricing source for the mid price (true/false).
external_pricing_source: false

# The type of external pricing source (exchange/feed/custom_api).
external_price_source_type:

# An external exchange name (for external exchange pricing source).
external_price_source_exchange:

# A trading pair for the external exchange (for external exchange pricing source).
external_price_source_exchange_trading_pair:

# A base asset, e.g. ETH (for external feed pricing source).
external_price_source_feed_base_asset:

# A quote asset, e.g. USD (for external feed pricing source).
external_price_source_feed_quote_asset:

# An external api that returns price (for external custom_api pricing source).
external_price_source_custom_api:
best_bid_ask_jump_mode: false

# For more detailed information, see:
# https://docs.hummingbot.io/strategies/pure-market-making/#configuration-parameters
```

**Comment by mifeng** [comment]
@leftys I think we'll need your logs for this session (logs folder) and your local sqlite database (data folder) to confirm this bug. If you don't know how to find them, please ask our support team on [Discord](https://discord.hummingbot.io)

**Comment by Clint-G13** [comment]
We have another user that experiences this issue (user Oriolfs ), duplicate trade was shown on the history output however only 2 trades appear on Binance. I was able to check the data file and seen 4 trade however only 2 trades shown on the logs.

![4history](https://user-images.githubusercontent.com/57189990/82513221-efb63a80-9b44-11ea-9fbf-e83a1b25940c.PNG)
![bnb](https://user-images.githubusercontent.com/57189990/82512285-35253880-9b42-11ea-9716-2255722f3433.png)
![db screenshot](https://user-images.githubusercontent.com/57189990/82512291-39e9ec80-9b42-11ea-94b9-001c20c5cdcf.PNG)

```
2020-05-19 10:12:21,854 - 10 - hummingbot.strategy.pure_market_making.pure_market_making_v2 - INFO - (ZILBNB) Maker sell order of 1496.00000000 ZIL filled. [clock=2020-05-19 10:12:21+00:00]
2020-05-19 10:12:21,864 - 10 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1589883141.73, "order_id": "x-XEKWYICX-SZLBB1589883097011743", "trading_pair": "ZILBNB", "trade_type": "TradeType.SELL", "order_type": "OrderType.LIMIT_MAKER", "price": "0.00060820", "amount": "1496.00000000", "trade_fee": ["0.00075", []], "exchange_trade_id": 1244295, "event_name": "OrderFilledEvent", "event_source": "binance"}
2020-05-19 10:12:23,877 - 10 - hummingbot.strategy.pure_market_making.pure_market_making_v2 - INFO - (ZILBNB) Maker sell order of 4504.00000000 ZIL filled. [clock=2020-05-19 10:12:23+00:00]
2020-05-19 10:12:23,886 - 10 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1589883143.754, "order_id": "x-XEKWYICX-SZLBB1589883097011743", "trading_pair": "ZILBNB", "trade_type": "TradeType.SELL", "order_type": "OrderType.LIMIT_MAKER", "price": "0.00060820", "amount": "4504.00000000", "trade_fee": ["0.00075", []], "exchange_trade_id": 1244296, "event_name": "OrderFilledEvent", "event_source": "binance"}
2020-05-19 10:12:23,887 - 10 - hummingbot.market.binance.binance_market - INFO - The market sell order x-XEKWYICX-SZLBB1589883097011743 has completed according to user stream.
2020-05-19 10:12:23,887 - 10 - hummingbot.strategy.pure_market_making.pure_market_making_v2 - INFO - (ZILBNB) Maker sell order x-XEKWYICX-SZLBB1589883097011743 (6000.00000000 ZIL @ 0.00060820 BNB) has been completely filled. [clock=2020-05-19 10:12:23+00:00]
2020-05-19 10:12:23,895 - 10 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1589883143.0, "order_id": "x-XEKWYICX-SZLBB1589883097011743", "base_asset": "ZIL", "quote_asset": "BNB", "fee_asset": "BNB", "base_asset_amount": "6000.00000000", "quote_asset_amount": "3.6492000000000000", "fee_amount": "0.00273689", "order_type": "OrderType.LIMIT_MAKER", "event_name": "SellOrderCompletedEvent", "event_source": "binance"}

2020-05-19 10:12:35,115 - 10 - hummingbot.client.hummingbot_application - INFO - stop command initiated.
2020-05-19 10:15:24,565 - 10 - hummingbot.market.binance.binance_market - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2020-05-19 10:15:24,885 - 10 - hummingbot.market.binance.binance_api_order_book_data_source - INFO - Initialized order book for ZILBNB. 1/1 completed.

# It appears that bot stop then reconnected, and the filled transaction was pulled which may have caused the duplicate
2020-05-19 10:15:25,414 - 10 - hummingbot.market.binance.binance_api_user_stream_data_source - INFO - Reconnecting to wss://stream.binance.com:9443/ws/9gAlUcIx5dwlJaO9UOI5OcCp19xu3tiGXxOUDYLMTlCGPi3WZ0jTtA9WChW7.
2020-05-19 10:15:25,887 - 10 - hummingbot.market.binance.binance_order_book_tracker - INFO - Started order book tracking for ZILBNB.
2020-05-19 10:15:26,586 - 10 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1589883326.0, "order_id": "x-XEKWYICX-SZLBB1589883097011743", "trading_pair": "ZILBNB", "trade_type": "TradeType.SELL", "order_type": "OrderType.LIMIT_MAKER", "price": "0.00060820", "amount": "1496.00000000", "trade_fee": ["0.00075", []], "exchange_trade_id": 1244295, "event_name": "OrderFilledEvent", "event_source": "binance"}
2020-05-19 10:15:26,595 - 10 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1589883326.0, "order_id": "x-XEKWYICX-SZLBB1589883097011743", "trading_pair": "ZILBNB", "trade_type": "TradeType.SELL", "order_type": "OrderType.LIMIT_MAKER", "price": "0.00060820", "amount": "4504.00000000", "trade_fee": ["0.00075", []], "exchange_trade_id": 1244296, "event_name": "OrderFilledEvent", "event_source": "binance"}
```

[hummingbot_tradesdb.zip](https://github.com/CoinAlpha/hummingbot/files/4660099/hummingbot_tradesdb.zip)
[logs_conf_pure_mm_ZIL_BNB.log](https://github.com/CoinAlpha/hummingbot/files/4660100/logs_conf_pure_mm_ZIL_BNB.log)

**Comment by dennisocana** [comment]
I ran into the same issue today. There are multiple duplicate trades in this report, on the left are exported trades from Hummingbot and from Bitfinex on the right. Highlighted in yellow is one of the duplicate trades.

[bitfinex_trades.xlsx](https://github.com/CoinAlpha/hummingbot/files/4861339/bitfinex_trades.xlsx)

![image](https://user-images.githubusercontent.com/50150287/86302654-ec31cb00-bc3b-11ea-8362-4c730938bb68.png)

Confirmed in in DB some executed trades have the same order ID. [hummingbot_trades.zip](https://github.com/CoinAlpha/hummingbot/files/4861340/hummingbot_trades.zip)

<img width="784" alt="dbeaver_cTWBf3isdr" src="https://user-images.githubusercontent.com/50150287/86302712-12576b00-bc3c-11ea-96f2-ef6a38be4087.png">

**Comment by vic-en** [comment]
> 
> 
> I ran into the same issue today. There are multiple duplicate trades in this report, on the left are exported trades from Hummingbot and from Bitfinex on the right. Highlighted in yellow is one of the duplicate trades.
> 
> [bitfinex_trades.xlsx](https://github.com/CoinAlpha/hummingbot/files/4861339/bitfinex_trades.xlsx)
> 
> ![image](https://user-images.githubusercontent.com/50150287/86302654-ec31cb00-bc3b-11ea-8362-4c730938bb68.png)
> 
> Confirmed in in DB some executed trades have the same order ID. [hummingbot_trades.zip](https://github.com/CoinAlpha/hummingbot/files/4861340/hummingbot_trades.zip)
> 
> <img alt="dbeaver_cTWBf3isdr" width="784" src="https://user-images.githubusercontent.com/50150287/86302712-12576b00-bc3c-11ea-96f2-ef6a38be4087.png">

@dennisocana 
This is caused by a kind of race condition between the user websocket tracker and the user API tracker(which is implemented as a backup in case websocket fails) in the Bifinex connector. I request a review from Nioni which should address this issue in the Bitfinex code on https://github.com/CoinAlpha/hummingbot/pull/1482#discussion_r450853699.

**Comment by vic-en** [comment]
> 
> 
> We have another user that experiences this issue (user Oriolfs ), duplicate trade was shown on the history output however only 2 trades appear on Binance. I was able to check the data file and seen 4 trade however only 2 trades shown on the logs.
> 
> ![4history](https://user-images.githubusercontent.com/57189990/82513221-efb63a80-9b44-11ea-9fbf-e83a1b25940c.PNG)
> ![bnb](https://user-images.githubusercontent.com/57189990/82512285-35253880-9b42-11ea-9716-2255722f3433.png)
> ![db screenshot](https://user-images.githubusercontent.com/57189990/82512291-39e9ec80-9b42-11ea-94b9-001c20c5cdcf.PNG)
> 
> ```
> 2020-05-19 10:12:21,854 - 10 - hummingbot.strategy.pure_market_making.pure_market_making_v2 - INFO - (ZILBNB) Maker sell order of 1496.00000000 ZIL filled. [clock=2020-05-19 10:12:21+00:00]
> 2020-05-19 10:12:21,864 - 10 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1589883141.73, "order_id": "x-XEKWYICX-SZLBB1589883097011743", "trading_pair": "ZILBNB", "trade_type": "TradeType.SELL", "order_type": "OrderType.LIMIT_MAKER", "price": "0.00060820", "amount": "1496.00000000", "trade_fee": ["0.00075", []], "exchange_trade_id": 1244295, "event_name": "OrderFilledEvent", "event_source": "binance"}
> 2020-05-19 10:12:23,877 - 10 - hummingbot.strategy.pure_market_making.pure_market_making_v2 - INFO - (ZILBNB) Maker sell order of 4504.00000000 ZIL filled. [clock=2020-05-19 10:12:23+00:00]
> 2020-05-19 10:12:23,886 - 10 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1589883143.754, "order_id": "x-XEKWYICX-SZLBB1589883097011743", "trading_pair": "ZILBNB", "trade_type": "TradeType.SELL", "order_type": "OrderType.LIMIT_MAKER", "price": "0.00060820", "amount": "4504.00000000", "trade_fee": ["0.00075", []], "exchange_trade_id": 1244296, "event_name": "OrderFilledEvent", "event_source": "binance"}
> 2020-05-19 10:12:23,887 - 10 - hummingbot.market.binance.binance_market - INFO - The market sell order x-XEKWYICX-SZLBB1589883097011743 has completed according to user stream.
> 2020-05-19 10:12:23,887 - 10 - hummingbot.strategy.pure_market_making.pure_market_making_v2 - INFO - (ZILBNB) Maker sell order x-XEKWYICX-SZLBB1589883097011743 (6000.00000000 ZIL @ 0.00060820 BNB) has been completely filled. [clock=2020-05-19 10:12:23+00:00]
> 2020-05-19 10:12:23,895 - 10 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1589883143.0, "order_id": "x-XEKWYICX-SZLBB1589883097011743", "base_asset": "ZIL", "quote_asset": "BNB", "fee_asset": "BNB", "base_asset_amount": "6000.00000000", "quote_asset_amount": "3.6492000000000000", "fee_amount": "0.00273689", "order_type": "OrderType.LIMIT_MAKER", "event_name": "SellOrderCompletedEvent", "event_source": "binance"}
> 
> 2020-05-19 10:12:35,115 - 10 - hummingbot.client.hummingbot_application - INFO - stop command initiated.
> 2020-05-19 10:15:24,565 - 10 - hummingbot.market.binance.binance_market - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
> 2020-05-19 10:15:24,885 - 10 - hummingbot.market.binance.binance_api_order_book_data_source - INFO - Initialized order book for ZILBNB. 1/1 completed.
> 
> # It appears that bot stop then reconnected, and the filled transaction was pulled which may have caused the duplicate
> 2020-05-19 10:15:25,414 - 10 - hummingbot.market.binance.binance_api_user_stream_data_source - INFO - Reconnecting to wss://stream.binance.com:9443/ws/9gAlUcIx5dwlJaO9UOI5OcCp19xu3tiGXxOUDYLMTlCGPi3WZ0jTtA9WChW7.
> 2020-05-19 10:15:25,887 - 10 - hummingbot.market.binance.binance_order_book_tracker - INFO - Started order book tracking for ZILBNB.
> 2020-05-19 10:15:26,586 - 10 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1589883326.0, "order_id": "x-XEKWYICX-SZLBB1589883097011743", "trading_pair": "ZILBNB", "trade_type": "TradeType.SELL", "order_type": "OrderType.LIMIT_MAKER", "price": "0.00060820", "amount": "1496.00000000", "trade_fee": ["0.00075", []], "exchange_trade_id": 1244295, "event_name": "OrderFilledEvent", "event_source": "binance"}
> 2020-05-19 10:15:26,595 - 10 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1589883326.0, "order_id": "x-XEKWYICX-SZLBB1589883097011743", "trading_pair": "ZILBNB", "trade_type": "TradeType.SELL", "order_type": "OrderType.LIMIT_MAKER", "price": "0.00060820", "amount": "4504.00000000", "trade_fee": ["0.00075", []], "exchange_trade_id": 1244296, "event_name": "OrderFilledEvent", "event_source": "binance"}
> ```
> 
> [hummingbot_tradesdb.zip](https://github.com/CoinAlpha/hummingbot/files/4660099/hummingbot_tradesdb.zip)
> [logs_conf_pure_mm_ZIL_BNB.log](https://github.com/CoinAlpha/hummingbot/files/4660100/logs_conf_pure_mm_ZIL_BNB.log)
> version: 0.27.0

This should rarely happen. It occurred because:
1. The spreads are very tight.
2. The bot was stopped and restarted within ~1minute.
3. Trades were executed but were not recorded to the database because the `stop` command was executed which stopped the `market_recorder` listener task before orders were recorded.
4. And on restarting the bot, the connector restored the orders in to the list of pending `in_flight_orders`.

Note that:
- Except for some DEXes, restoring orders for CEXes after a restart should only happen if the bot crashed for whatever reason. Or the system resources are overloaded(or for other strange reasons) and a similar situation like the above happens.

**Comment by Nullably** [comment]
@vic-en On Binance one, can you reproduce the duplicates error?

> 3. Trades were executed but were not recorded to the database because the stop command was executed which stopped the market_recorder listener task before orders were recorded.

If the trades are not recorded, shouldn't this produce the opposite behaviour, i.e. the orders are not recorded as completed?

**Comment by vic-en** [comment]
> 
> 
> @vic-en On Binance one, can you reproduce the duplicates error?
> 
> > 1. Trades were executed but were not recorded to the database because the stop command was executed which stopped the market_recorder listener task before orders were recorded.
> 
> If the trades are not recorded, shouldn't this produce the opposite behaviour, i.e. the orders are not recorded as completed?

The table shown is the **TradeFIll** table which is updated every time a `OrderFilledEvent` is acknowledged by the `marker_recorder`. There is another **MarketState** table which should be updated by a `SellOrderCompletedEvent`(in this scenario after both fill events were received).
**MarketState** table is what is used determine if an order is active or not. But it wasn't updated in this case for some unlikely reasons before the bot stopped the market_recorder when the `stop` command was triggered. So this caused that particular order to be restored when the bot was started again.

**Comment by vic-en** [comment]
@Nullably 
I think the only possible way to avoid a similar case from occurring again is to reinforce the `restore_market_states` in the market recorder to double check orders in the `TradeFill` table before it takes any order it sees active as an active order.
