### ISSUE TITLE
[BUG] Kraken orders not being canceled consistently (about 1-2% incidence)

### ISSUE THREAD

**Issue by babygiraffe05** [CoinAlpha/hummingbot#1664]
**Describe the bug**
When running the new Kraken connector with the advanced market making strategy, there is an occasional instance of the orders failing to cancel on Kraken. It appears to happen only about once an hour, but I haven't yet managed to catch it happen live. This translates to an incidence rate of about 1.5% based on the frequency with which I've been placing orders.

**Steps To Reproduce**
I am running a docker implementation of advanced market making on Ubuntu 18.04. I set the order refresh frequency to 30 seconds. I have tried both single and multiple bid / ask orders. I also had settings with inventory skew set to 50%. When running the bot, uncancelled orders accumulate over time.

I've scanned through the logs and for the orders in question, there is the following pattern:

hummingbot.strategy.pure_market_making.pure_market_making_v2 - INFO - (TRADINGPAIR) Creating limit bid orders at (Size, Price) ...

hummingbot.market.kraken.kraken_market - INFO - Created OrderType.LIMIT buy order ...

hummingbot.core.event.event_reporter - EVENT_LOG - {ORDER DETAILS}

hummingbot.market.kraken.kraken_market - INFO - Successfully cancelled order buy-TRADINGPAIR ...

NOTE: At no point did the bot ever actually send the following command:
hummingbot.strategy.pure_market_making.pure_market_making_v2 - INFO - (TRADINGPAIR) Cancelling the limit order buy-TRADINGPAIR ...

It appears like the system thinks the order has been cancelled (either because of a bug in hummingbot or because Kraken incorrectly signals that it cancelled the order) when in fact no command has been sent to cancel the order.

**Release version**
Version 0.26.0

**Potential solution**
If Kraken is sending bad information to the bot, it might make sense to send a blanket "cancel all outstanding orders" command to the exchange regardless of whether the bot thinks there are open orders or not before issuing the next set of orders. Or the bot needs to ensure that before it accepts that an order has truly been cancelled, that it must first check whether it has actually requested the cancellation.

**Comment by dennisocana** [comment]
Ran into the same problem but my logs show that the orders are cancelled even though they're not. Looks like the bug is triggered when the cancelled order event happens the same time when orders were created. See timestamps of order ID `buy-XBTUSDC-1588043540001383` and `buy-XBTUSDC-1588044070001517`.

Attached log file : 
[logs_kraken_xxbt-usdc.log](https://github.com/CoinAlpha/hummingbot/files/4549564/logs_kraken_xxbt-usdc.log)

![dM2Q4KXV8u](https://user-images.githubusercontent.com/50150287/80556307-bd159800-8a05-11ea-9fe5-d3bb0156dec3.png)
![GnDmJIVJf8](https://user-images.githubusercontent.com/50150287/80556296-b7b84d80-8a05-11ea-8458-78e2c076eec6.png)
![HECh9aBjqX](https://user-images.githubusercontent.com/50150287/80556300-bb4bd480-8a05-11ea-8a1a-c25f0fdf8757.png)

**Comment by babygiraffe05** [comment]
Can confirm this is in fact exactly what was happening with my errors as well. In advanced market making with multiple orders, the issue is dramatically more frequent (basically every set of orders leaves uncancelled orders). This effectively makes the Kraken connector unusable for the market making strategy for the time being.

**Comment by rxlxrxsx** [comment]
Encountered this bug again in dev-0.30.0 Kraken shows open orders were stuck or uncancelled causing less available balance. These orders are not showing as active orders in status output.

![image](https://user-images.githubusercontent.com/64377055/88469567-71e82400-cf25-11ea-8987-306e38e766d1.png)

![image](https://user-images.githubusercontent.com/64377055/88469550-32b9d300-cf25-11ea-9d52-f99a1ea3f52e.png)

`"branch": "development",`
`"commit": "d13b3401642b83ebddf5844c9fd2901771495911",`
`"date": "2020-07-25T20:37:34Z",`

[logs_kraken_btc-usdc.log.zip](https://github.com/CoinAlpha/hummingbot/files/4977033/logs_kraken_btc-usdc.log.zip)
[logs_kraken_btc-usdc.log](https://github.com/CoinAlpha/hummingbot/files/4977027/logs_kraken_btc-usdc.log)

**Comment by dennisocana** [comment]
@rxlxrxsx @RC-13 are we still getting this with Kraken in the current version?

**Comment by rxlxrxsx** [comment]
Currently there are no instances of this error happening in the current version.
