### ISSUE TITLE
[BUG]Unusually high spread when using a pair with price below 1000 sats

### ISSUE THREAD

**Issue by devoger** [CoinAlpha/hummingbot#1665]
**Describe the bug**
// A clear and concise description of what the bug is.

Incorrect spread when using a pair with price below 1000sats.

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
1. Start a pure marketing making bot in paper trade mode or live 
2. Use a pair with a price below 1000 sats like STORM/BTC, HOT/BTC, TNB/BTC
3. Ask / Bid spread 1% 

...

**Screenshots**
// If applicable, add screenshots to help explain your problem.

Configuration
![Screen Shot 2020-04-26 at 12 43 55](https://user-images.githubusercontent.com/8411294/80298579-6cf9c400-87c0-11ea-83da-2250b23e7194.png)

Notice the spread is unusually high
![Screen Shot 2020-04-26 at 13 21 59](https://user-images.githubusercontent.com/8411294/80298640-075a0780-87c1-11ea-8036-e559ae3ef46c.png)

This example is using OGN/BTC with a price ( 0.00003141) higher than 1000 sats and it is working just fine

![Screen Shot 2020-04-26 at 12 49 31](https://user-images.githubusercontent.com/8411294/80298584-83078480-87c0-11ea-96c8-bdac5440a2f2.png)

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).
0.26.0

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 
[logs_conf_pure_mm_1.log](https://github.com/CoinAlpha/hummingbot/files/4534666/logs_conf_pure_mm_1.log)
```
########################################################
###       Pure market making strategy config         ###
########################################################

template_version: 12
strategy: pure_market_making

# Exchange and token parameters.
exchange: binance

# Token trading pair for the exchange, e.g. BTC-USDT
market: STORM-BTC

# How far away from mid price to place the bid order.
# Spread of 1 = 1% away from mid price at that time.
# Example if mid price is 100 and bid_spread is 1.
# Your bid is placed at 99.
bid_spread: 1.0

# How far away from mid price to place the ask order.
# Spread of 1 = 1% away from mid price at that time.
# Example if mid price is 100 and ask_spread is 1.
# Your bid is placed at 101.
ask_spread: 1.0

# Time in seconds before cancelling and placing new orders.
# If the value is 60, the bot cancels active orders and placing new ones after a minute.
order_refresh_time: 120.0

# Size of your bid and ask order.
order_amount: 8000.0

# Whether to enable Inventory skew feature (true/false).
inventory_skew_enabled: false

# Target base asset inventory percentage target to be maintained (for Inventory skew feature).
inventory_target_base_pct:

# The range around the inventory target base percent to maintain, expressed in multiples of total order size (for
# inventory skew feature).
inventory_range_multiplier: 1.0

# Ox ONLY - Sets the expiration of limit orders. Minimum is 130 seconds.
order_expiration_time: 130.0

# Number of levels of orders to place on each side of the order book.
order_levels: 5

# Increment size of consecutive orders after the first order (if order_levels > 1).
order_level_amount: 0

# Order price space between orders (if order_levels > 1).
order_level_spread: 1.0

# How long to wait before placing the next order in case your order gets filled.
filled_order_delay: 60

# Whether to stop cancellations of orders on the other side (of the order book),
# when one side is filled (hanging orders feature) (true/false).
hanging_orders_enabled: false

# Spread (from mid price, in percentage) hanging orders will be canceled (Enter 1 to indicate 1%)
hanging_orders_cancel_pct: 10.0

# Whether to enable order optimization mode (true/false).
order_optimization_enabled: false

# The depth in base asset amount to be used for finding top bid and ask (for order optimization mode).
order_optimization_depth: 0

# Whether to enable adding transaction costs to order price calculation (true/false).
add_transaction_costs: false

# Whether to use external pricing source for the mid price (true/false).
price_source_enabled: false

# The type of external pricing source (exchange/custom_api).
price_source_type:

# An external exchange name (for external exchange pricing source).
price_source_exchange:

# A trading pair for the external exchange, e.g. BTC-USDT (for external exchange pricing source).
price_source_market:

# An external api that returns price (for external custom_api pricing source).
price_source_custom:

# For more detailed information, see:
# https://docs.hummingbot.io/strategies/pure-market-making/#configuration-parameters
```

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by mifeng** [comment]
@dennisocana can you ask the support team to confirm this bug?

**Comment by dennisocana** [comment]
Tested and confirmed this is not a bug. This is due to quantization.

@devoger

If bid_spread = 1% following the calculation for bid price : `bid_price = mid_price * (1 - spread)`
Then your order price is `0.00000012375‬ = 0.000000125 *(1- 0.01)`.

However, the price precision is only up to 8 decimal values so your buy order will be placed at `0.00000012` shown as the top order in the orderbook and its spread is 4% away from the mid price.

```
"symbol": "STORMBTC",
"status": "TRADING",
"baseAsset": "STORM",
"baseAssetPrecision": 8,
"quoteAsset": "BTC",
"quotePrecision": 8,
"quoteAssetPrecision": 8,
```

<img width="504" alt="Untitled" src="https://user-images.githubusercontent.com/50150287/81639018-52288000-944d-11ea-9b0f-a27becafa004.png">

The subsequent orders are placed on the next tick and show the correct spreads.
