### ISSUE TITLE
[BUG] XEMM | unsupported operand type(s) for /: 'float' and 'decimal.Decimal'

### ISSUE THREAD

**Issue by PtrckM** [CoinAlpha/hummingbot#1667]
**Describe the bug**
- unable to start bot with Unhandled error in background task: unsupported operand type(s) for /: 'float' and 'decimal.Decimal'

**Steps To Reproduce**
1. create xemm strategy
2. choose any connector (binance-liquid)
3. choose any token pair (ETH-BTC)
4. set min prof
5. set order amount
6. start bot

**Screenshots**
![image](https://user-images.githubusercontent.com/54516858/80305542-e5c44480-87ef-11ea-9f7f-adffa4b1764a.png)
![image](https://user-images.githubusercontent.com/54516858/80305596-36d43880-87f0-11ea-8bd7-946f65892262.png)

**WORKAROUND**
- edit default value to `order_size_taker_balance_factor: 0.995`
- edit default value to `order_size_portfolio_ratio_limit: 0.1667`
- edit default value to `order_size_taker_volume_factor: 1`

![image](https://user-images.githubusercontent.com/54516858/80305613-5ff4c900-87f0-11ea-87a3-3cd5f0bbf333.png)
![image](https://user-images.githubusercontent.com/54516858/80305619-68e59a80-87f0-11ea-920a-58504bfe17d5.png)

**Release version**
0.26.0 / Docker Build, Source Build and Binary Installer

**Attachments**
```
2020-04-26 18:57:36,128 - 14220 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: unsupported operand type(s) for /: 'float' and 'decimal.Decimal'
Traceback (most recent call last):
  File "hummingbot\core\utils\async_utils.py", line 9, in safe_wrapper
  File "hummingbot\client\command\start_command.py", line 82, in start_check
  File "hummingbot\client\command\start_command.py", line 90, in start_market_making
  File "hummingbot\strategy\cross_exchange_market_making\start.py", line 28, in start
TypeError: unsupported operand type(s) for /: 'float' and 'decimal.Decimal'
```

**Comment by rennel-tabing** [comment]
I was able to replicate the issue using the parameters given by Patrick 
```
xemm strategy
connector binance-liquid
token pair ETH-BTC
min prof 1
set order amount 0.05
```
I do not have this issue though when I used these strategy parameters

```
xemm strategy
connector binance-huobi
token pair ETH-USDT
min prof 1
set order amount 0.08

```

![image](https://user-images.githubusercontent.com/53868268/80374016-ff9f6f00-8863-11ea-9f73-6dacf00167ea.png)

* Note that I have to exit the bot and relaunch for the strategy to start

**Comment by saumyabratadutt** [comment]
version 0.26.0 (docker version)
Even I was facing the same problem.
**Error**
16:27:00 - async_utils - Unhandled error in background task: unsupported operand type(s) for /: 'float' and 'decimal.Decimal' (See log file for stack trace dump)

**I solved it using the below mentioned steps**
1. exit
2. open humming_bot
3. import the strategy

It worked fine for me. I'll let you all know if the error occurs again.

**Comment by Clint-G13** [comment]
Confirmed fixed, error no longer shows using the current default parameters.
![XEMM startup](https://user-images.githubusercontent.com/57189990/81023341-9b535f80-8ea2-11ea-8623-62bb7938434c.PNG)
