### ISSUE TITLE
[BUG] Arbitrage using  Kraken - ERROR - Unhandled error in background task: can only concatenate tuple 

### ISSUE THREAD

**Issue by rennel-tabing** [CoinAlpha/hummingbot#1676]
**Describe the bug**
// A clear and concise description of what the bug is.

Using Arbitrage with Kraken will cause the bot to not start the strategy

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: ...
```
#####################################
###   Arbitrage strategy config   ###
#####################################

template_version: 3
strategy: arbitrage

# The following configuations are only required for the
# arbitrage strategy

# Exchange and token parameters
primary_market: binance
secondary_market: kraken
primary_market_trading_pair: ADA-ETH
secondary_market_trading_pair: ADA-XETH

# Minimum profitability target required to place an order
# Expressed in percentage value, e.g. 1 = 1% target profit
min_profitability: 0.5


```

2. Start the bot 
...

**Screenshots**
// If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/53868268/80510586-ef14f480-8948-11ea-83d5-2ae9c0cc86ae.png)

Error is as follows:
```
TypeError: can only concatenate tuple (not "list") to tuple
2020-04-28 15:24:31,952 - 10 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: can only concatenate tuple (not "list") to tuple
Traceback (most recent call last):
  File "/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/hummingbot/client/command/start_command.py", line 82, in start_check
    await self.start_market_making(self.strategy_name)
  File "/hummingbot/client/command/start_command.py", line 90, in start_market_making
    start_strategy(self)
  File "/hummingbot/strategy/arbitrage/start.py", line 30, in start
    self._initialize_wallet(token_trading_pairs=list(set(primary_assets + secondary_assets)))
TypeError: can only concatenate tuple (not "list") to tuple

```

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).
0.26.0

-This behavior happens on both paper trade and live mode
-Tried using other trading pair and had the same issue
-Changing the secondary market (replacing Kraken) will not show the error

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Comment by rennel-tabing** [comment]
This maybe related to issue https://github.com/CoinAlpha/hummingbot/issues/1674 as both bug have a similar error on the second line that says
 `  File "/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c`

**Comment by Clint-G13** [comment]
A new error now showing for Kraken connector: #1693

**Comment by Clint-G13** [comment]
New error currently showing using Kraken connector: #1693, however, the same error still persist with Arbitrage and XEMM if you manually create a strategy and fill `none` parameters.
After importing the strategy:
![XEMM1](https://user-images.githubusercontent.com/57189990/81033108-d36b9a00-8ec4-11ea-9236-ac40230832d6.PNG)
After manually editing `none` values
![XEMM3](https://user-images.githubusercontent.com/57189990/81033135-ed0ce180-8ec4-11ea-9a7c-a272db60ee04.PNG)

**Comment by Clint-G13** [comment]
Test with PR #1729 and confirmed fixed.

Arbitrage:
![kraken tuple](https://user-images.githubusercontent.com/57189990/81765488-8613ac00-9506-11ea-9d05-63abacb54101.PNG)

Cross exchange:
![kraken tuple xemm](https://user-images.githubusercontent.com/57189990/81765499-8dd35080-9506-11ea-9a95-7fe1391e53e2.PNG)
