### ISSUE TITLE
[BUG] Error when responding to order amount prompt in Huobi

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#1678]
**Describe the bug**

Same as https://github.com/CoinAlpha/hummingbot/issues/1668 getting an error and can't get past the order amount prompt when setting up pure market making on Huobi.

![image](https://user-images.githubusercontent.com/50150287/80561292-8d22c080-8a16-11ea-9c95-3081480d55c1.png)

Error from logs :

```
2020-04-28 03:50:25,314 - 11 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: type NoneType doesn't define __round__ method
Traceback (most recent call last):
  File "/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/hummingbot/client/command/create_command.py", line 64, in prompt_for_configuration
    await self.asset_ratio_maintenance_prompt(config_map)
  File "/hummingbot/client/command/create_command.py", line 130, in asset_ratio_maintenance_prompt
    base_ratio = round(base_ratio, 3)
TypeError: type NoneType doesn't define __round__ method
```

Same workaround :

1. Create a strategy config file first before adding Huobi APi keys
2. If there are API keys in `conf` directory, delete encrypted keys
3. Import an existing strategy config file then start - make sure to use the latest version of the pure market making strategy config file template

```
########################################################
###       Pure market making strategy config         ###
########################################################

template_version: 12
strategy: pure_market_making
```

**Comment by PtrckM** [comment]
Confirmed fix on **dev-0.27.0**

![image](https://user-images.githubusercontent.com/54516858/81273177-18d4c680-9081-11ea-8960-e100aecaa2c0.png)
![image](https://user-images.githubusercontent.com/54516858/81273470-7f59e480-9081-11ea-9988-0679923a649b.png)
