### ISSUE TITLE
New PMM param: take_if_crossed

### ISSUE THREAD

**Issue by babygiraffe05** [CoinAlpha/hummingbot#1680]
**Feature Suggestion**
The current behavior in Advanced Market Making is as follows:

"In a situation where the calculaton of maker order prices from external sources would result in the order matching any existing orders on the order book, such order will be ignored. For example, if ETH-USDC market is currently displaying 109 bid and 111 ask. A specified external exchange is showing 99 bid and 101 ask on its book (mid price = 100). 2 maker orders will be proposed, a bid maker order at 98 (for 2% bid spread) and an ask maker order at 102 (for 2% ask spread). The 102 ask order will be ignored (as it would match the 109 bid order), only the bid order will be submitted to the exchange."

However, in the above example, assuming the exchange in question is a less liquid market than the external exchange, it is likely that the price will converge toward 100. There would be tremendous value in selling at 109 (highest bid).

Therefore, a desirable setting would be "submit_matching_orders" [Yes/No] which would effectively post limit taker orders that will match existing maker orders. Even if the fee is higher, the behavior may be desirable because of the likely future price migration.

**Impact**
This would effectively allow Advanced Market Making strategy to double as "one-sided" arbitrage strategy on less-liquid exchanges, and lead to much greater liquidity when an exchange's price becomes dislocated from the broader market.

**Comment by mifeng** [comment]
This is a great idea. The #1714 script feature may allow for this, but we may want to add this as an additional parameter regardless.
