### ISSUE TITLE
[BUG] Advance parameters on Cross Exchange accepts alphanumeric Value

### ISSUE THREAD

**Issue by rennel-tabing** [CoinAlpha/hummingbot#1682]
**Describe the bug**
// A clear and concise description of what the bug is.
Advanced parameters on XEMM  such as cancel_order_threshold, limit_order_min_exiration, etc.. accepts invalid parameters while basic parameters prevents you in doing so.

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:
1. Configure a Cross Exchange Market Making strategy.
2. Do a config `cancel_order_threshold` command then `Enter`
3. Specify an invalid value such as `abc123` then `Enter`. Logs will show that the input was invalid but hummingbot will still update the invalid value on the config file 

**Screenshots**
// If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/53868268/80734205-d63d4800-8adc-11ea-9c4f-e0e5ac4b3d83.png)

**Release version**
// 
0.26.0
dev-0.27.0

**Comment by Clint-G13** [comment]
This issue occurs on PMM order_level parameter as well:
![PMM](https://user-images.githubusercontent.com/57189990/80772239-a0559d80-8b88-11ea-9555-2e72b8b33353.PNG)

**Comment by PtrckM** [comment]
Confirmed fix

![image](https://user-images.githubusercontent.com/54516858/83949090-7d3b9f00-a854-11ea-8cb8-0f75d388756d.png)

![image](https://user-images.githubusercontent.com/54516858/83949136-b3791e80-a854-11ea-855d-4efc658f612b.png)
