### ISSUE TITLE
[Feature]More popular market making strategy, grid trade

### ISSUE THREAD

**Issue by hkingofsaga** [CoinAlpha/hummingbot#1703]
**Feature Suggestion**
I found the bituniverse.org, its easy of use and easy to understand,
but unsafe.
They store the API !

Change Advanced Market Making a little bit to implement this, may be?

**Comment by bitfag** [comment]
If I understand right, grid trade is similar what we did in [Staggered Orders](https://github.com/Codaone/DEXBot/wiki/The-Staggered-Orders-strategy) strategy in the DEXBot, which could be re-implemented for Hummingbot. There are additional options like different order size modes, and automatic profit reinvestments.

Here is a short video visually showing the idea: https://twitter.com/cryptokong123/status/1080196253030457345

**Comment by phbrgnomo** [comment]
Another description of grid strategy on Forex markets.

https://admiralmarkets.com/education/articles/forex-strategy/forex-grid-trading-strategy-explained

Keep in mind that Forex trading is usually done through margin trading. Differences could apply to spot markets.

**Comment by JCBauza** [comment]
Would love to see grid trading bot! Profit reinvestment or retaining gains in crypto vs base currency would be amazing! Could do it on margin as well. Wish I could help code it as I really want it but I lack the required skill
