### ISSUE TITLE
[BUG] Kraken Autocomplete not working

### ISSUE THREAD

**Issue by Clint-G13** [CoinAlpha/hummingbot#1707]
**Describe the bug**
When choosing market pair on Kraken, autocomplete options are not showing even if you press tab.

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):
1. Create a pure market making strategy or cross-exchange strategy
2. When asked to enter market trading pair, press tab or type the first letter of the token and you won't see any suggested token or list of token options.

**Screenshots**
![Kraken Autocomplete](https://user-images.githubusercontent.com/57189990/81365493-d790f500-911a-11ea-8501-cfb7bc548620.PNG)

**Release version**
Development branch - 0.27.0
```
branch: development
commit 69cf78752cb058fc8eb2921e5be1d768762731ba 
Date:   Fri May 8 10:00:33 2020 +0800
```

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by rennel-tabing** [comment]
I am able to reproduce using 
Branch: development
commit a3867c45c16f3e688bf2391742949c4c00e04273

**Comment by mifeng** [comment]
This is same as #1693 so I'm closing this one
