### ISSUE TITLE
Trade notifications

### ISSUE THREAD

**Issue by mifeng** [CoinAlpha/hummingbot#1711]
<img width="646" alt="Screen_Shot_2020-05-06_at_5 27 20_PM" src="https://user-images.githubusercontent.com/1795030/81464185-025b6780-9174-11ea-8cd1-88e400ff98c5.png">

A number of users like the one above have requested additional notifications when a trade is filled. We should explore what options are viable:
- can we print trades to the left output panel to give users better visibility
- is it possible to hook up hummingbot with an transactional email API?

**Comment by Pascal66** [comment]
If I may extend this, an rpc api could be usefull (for those who are not using telegram for example)
