### ISSUE TITLE
New PMM parameter: price bands 

### ISSUE THREAD

**Issue by mifeng** [CoinAlpha/hummingbot#1713]
* Add 2 new parameters: `price_ceiling` and `price_floor`
* Set them at -1 by default, which means they are not used
* If the price is within the band set by `floor_price` and `ceiling_price`, run the bot as normal
* If price goes above `price_ceiling`, only place sell orders
* If price falls below `price_floor`, only place buy orders

**Comment by petioptrv** [comment]
Hey @mifeng, I've been pocking around in the repo the last couple of days and I'd like to take a crack at a contribution with this if it's up for grabs.

**Comment by mifeng** [comment]
@petioptrv Wow that would be great! 

Note that we are big on unit tests, so if you're working on this feature, please add a test for it in https://github.com/CoinAlpha/hummingbot/tree/master/test

If you have any questions, you can ask them here or on the #dev channel in https://discord.hummingbot.io.

**Comment by petioptrv** [comment]
@mifeng will definitely add tests! I did run into some issues however. Apparently PyCharm does not support Cython debugging, so I only get `Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)` when I try to run the current test cases (after I've made the changes to PMM). Do you use an IDE for that or you use directly gbd?

**Comment by mifeng** [comment]
To run tests, run `nosetests <filename>` in the `test` directory

**Comment by mifeng** [comment]
Hey @petioptrv I assigned you to this story so that other devs don't work on it. 

Let me know if you have any questions as you begin to work on it - thanks!
