### ISSUE TITLE
Scripts: dynamic bot controls

### ISSUE THREAD

**Issue by mifeng** [CoinAlpha/hummingbot#1714]
# Scripts

PRD for a feature set in the Hummingbot client that generalizes **kill switch** and lets users run **scripts** that automate **commands** based on **indicators.**

This is a research doc for discussion purposes only.

## Summary

We will introduce a new feature in the client called **Scripts**. A script is a Python function that allows the user to automate commands if certain conditions are met.

Each strategy can load one or more scripts, specified in the config file. At each clock tick, the client runs all the loaded scripts in sequence.

## What does a script look like?

```python
# interface
if <indicator> <operand> <threshold>:
	<action>

# sample
if volume_current >= volume_1h * 5:
	# widen spreads
	exec_command("config bid_spread 2")
	exec_command("config ask_spread 2")
```

## What indicators are scriptable?

Initially, we add a limited set of basic parameters related to the state of the user's portfolio and the market. 

Each parameter has a current version (value in the last tick) and a trailing 1h version (average of all ticks in last hour). If this feature is heavily used, we can add more indicators later on.

- Portfolio state (current, trailing 1h):
    - `return_pct`
    - `trade_value_delta`
    - `base_asset_pct`
- Market state (current, trailing 1h)
    - `price`
    - `bid_2_pct_depth`: bid OOV within 2% of mid price
    - `ask_2_pct_depth`: ask OOV within 2% of mid price
    - `volume`

## How do we store trailing indicators?

To keep track of the trailing indicators, I think we need to store the indicator value at each tick and maintain the data for the last X hours, where X is a parameter in `conf_global`

## Should we include technical indicators?

I'm not sure TA indicators should be in v1 of this feature, since they may not be as important to market makers as they are to TA traders. Since many users come from a trading background and are familiar with technical indicators, we should make the basic TA indicators available eventually.

- MACD: different between a longer moving average and a shorter moving average
    - Parameters:`lookback1`, `lookback2`
- RSI: 100 - (100 / ( 1 + (avg gain / avg loss)))
    - Parameters: `lookback`
- Bollinger bands: standard deviation bands around the moving average of the price
    - Parameters: `stdev`, `lookback`

## What commands are scriptable?

Any command available in the Hummingbot CLI. I expect that the most common commands users want to script are:

- `stop`
- `start`
- `config <param> <value>`

To give users more scriptable commands, we should also make more of the commands configurable on the fly. The most important ones to adjust on the fly are:

- `order_amount`
- `order_levels`

Since users would also want to execute commands to place and cancel orders, we should also introduce new commands:

- `place`: places a new order given inputs `side`, `type`, `amount`, `price` (if not market type)
- `cancel`: cancels an existing order. needs to be able to identify orders.

## What scripts will Hummingbot ship with?

To maintain existing functionality and to provide a sample script to users, we will write a `kill_switch` script:

- if `return_pct` ≤ `-1.0` execute `stop`

In addition, we should also write a few more basic scripts, such as:

- If `volume_current` ≥ `volume_trailing_1h` * 5, execute `stop`
- if abs[(`price_current` - `price_trailing_1h`) / `price_trailing_1h`] ≥ 0.2, execute `config_bid_spread 2` and `config_ask_spread 2`

## How do users create scripts?

Initially, users are expected to write the scripts in Python outside of Hummingbot.

If this feature is heavily used, we can create a script editor within the client. `python-prompt-toolkit` is intended for custom IDEs so it should fit this purpose.

## How do users import scripts?

We add a directory called `/scripts` to the hummingbot directory. Each strategy config contains a parameter named `scripts` that references one or more script in this directory.

## How do we prevent users from loading buggy scripts?

Perform a validation check upon `start` command to ensure that the script doesn't contain errors.

In addition, we should maintain a list of scriptable indicators and commands in the docs.

**Comment by eugencuic** [comment]
Hey Mike, we have been talking about this in discord a day ago. 
A nice feature would be to have a possibility to check for certain values from outside the bot. For example I will do some calculations on tick data form outside of the bot. the output will be the calculated bid and ask spread. 
now i can have a call of this variable in the Database every x seconds / minutes. 

the call downloads the value and assigns it to the config in bid_spread and ask_sread

or the other way round (which i do not prefer) is to have a possiblity to load a fully script and let it run in the background. every X sec / min the bot looks for this calculation and assigns it to a config variable. 

This would give the bot a whole new level of flexibility without putting it up for too much risk (failure)

**Comment by fernandobender** [comment]
i suggest to include amongst the accessible indicators of portfolio, the balance as well. perhaps only manage % the balance might not allow some use cases. thank you.

**Comment by Nullably** [comment]
#1888 
The first version of the `scripts` feature is currently under review, it can do the followings:
- Update the below pure market making parameters:
    buy_levels 
    sell_levels 
    order_levels
    bid_spread
    ask_spread
    order_amount
    order_level_spread
    order_level_amount
    order_refresh_time
    order_refresh_tolerance_pct
    filled_order_delay
    hanging_orders_enabled
    hanging_orders_cancel_pct
- Subscribe to the below events:
    on_tick
    on_buy_order_completed
    on_sell_order_completed
    on_status

*on_tick*
This is called every second, and the script gets the below information
   - mid_price (this is stored in a list, so that it can be used to calculate indicators)
   - current pure_market_making strategy parameters (as listed above)       

*on_buy_order_completed*
This is called every time a buy order is filled completely

*on_sell_order_completed*
This is called every time a sell order is filled completely
 
*on_status*
To report status when you input `status` command

I have included 4 examples on how you can code the script
* `hello_world_script.py`
The most basic example.
* `ping_pong_script.py`
To replicate our current ping pong strategy using script.
* `price_band_script.py`
To replicate our current price band strategy.
* `dynamic_price_band_script.py`
To demonstrate how to set the band around mid price moving average.

The `script` feature can be configured using below commands
- `config script_enabled`
This is to enable the feature
- `config script_file_path`
To specify the script file (it's recommended to put the files into `conf` folder at the moment`)
