### ISSUE TITLE
Extend price source param

### ISSUE THREAD

**Issue by mifeng** [CoinAlpha/hummingbot#1715]
## Description:
Extend the `price_source_type` parameter in the PMM strategy to give users fine-grained control over how the reference price used to set spreads is calculated each tick. 

## Tasks
1. Change `price_source_type` to allow user to input the following options:
- `mid_price`: use the avg of top bid and lowest ask (current, default)
- `last_trade`: use the price of the last trade as the reference price
- `custom`: allows users to enter a custom endpoint (no change)
- remove the `exchange` option

2. Add the params:
- `price_source_mid_price_depth`: set the depth in base asset units to calculate bid and ask prices. this lets users ignore dust orders (default: zero)
- `price_source_external_exchange`. If this param is null (default) use the same exchange. Users can config this to pick a different exchange. 
- `price_source_imputed_enabled`: `bool`, uses an imputed market's mid price. When users config this option and answer Yes, display questions that set the params below
- `price_source_imputed_market1` 
- `price_source_imputed_market2`: these 2 parameters are the pairs used to impute the price when `price_source_imputed` is True. When the user sets these parameters, use `price_source_external exchange` to display auto-complete if specified; otherwise, use the current exchange.

**Comment by petioptrv** [comment]
Following up on the suggestion in #1720, I'd like to take on this issue next

**Comment by mifeng** [comment]
@petioptrv Sounds good - that's a good one because I believe most of the changes are in the asset price delegate module. FYI we are about to start refactoring the structure of the pure_market_making_v2.pyx file. However, it shouldn't impact these price source changes.

Let me know if you have any questions about the options above.

**Comment by petioptrv** [comment]
@mifeng I like this issue. It looks like it will touch on aspects of the code I haven't worked on yet.

Question:  How are the last two parameters used? Are they used as fallbacks in case the current price source (either the market we are trading on or the external exchange) has no active trades posted?

**Comment by mifeng** [comment]
> Question: How are the last two parameters used? Are they used as fallbacks in case the current price source (either the market we are trading on or the external exchange) has no active trades posted?
@petioptrv Those are the two markets used if `price_source_imputed_enabled` is True.

I realized that this story's description is not detailed enough, here is additional clarification.

Users should be able to control different aspects of how the price is determined. These variables are independent of each other:

### Price calculation: How the price is derived from an order book
* `price_source_type` selects whether it's mid price, last trade, or custom.
* If mid price is selected, user can also modify `price_source_mid_price_depth` to change the depth at which price is calculated
* Note that if `price_source_type` is `custom`, none of the other params take effect.

### Market selection: Which external order book to use, if an order book exists
* `price_source_external_exchange` sets which exchange to use.
* `price_source_external_market` (I forgot this param in the description): sets the trading pair, if it exists

### Market selection (imputed): Which markets to impute the price from, if no order book exists
* Active if `price_source_imputed_enabled:` is True. 
* This means that `price_source_external_market` is ignored, and market selection is driven by `price_source_imputed_market1` and  `price_source_imputed_market2`
* Note that if `price_source_imputed_enabled` is True, it is incompatible with selecting the `last trade` option in `price_source_type`.

@Nullably do you still have the code you wrote for the imputing the price from 2 different markets?

**Comment by cartano** [comment]
It may be a consideration to split it in two stories. One story just to add the additional `price_source_type = last_trade` option to use the price of the last trade as the reference price, as it addresses the current major risk of repeat one-sided orders without price movement, if order depth is high around mid price for example in sat pairs like SC, or DGB.  and cause either inventory or quote currency to deplete to fast. Price source type `last_trade` addresses similar risk as #1794. 
And it may allow to promote this story then to be released along with #1720.

While as second story then could focus on all second level options as per @mifeng above, after next release.

**Comment by petioptrv** [comment]
@mifeng, thank you for the clarifications! @cartano, I like the idea of splitting the story up. This upcoming week will be very busy for me work-wise (as was last), so I might not be able to work on this before the weekend, but am hoping to complete it then.

**Comment by Nullably** [comment]
@mifeng @petioptrv @cartano 
For the price imputation, does this mean to derive market price from 2 different market pairs, e.g. you can get `RLC-USDT` price indirectly from `RLC-BTC` and `BTC-USDT` trading pairs?
The code I had was for a different use case, it was for searching. But I think some examples will help explain. For the above example, you can simply multiply `RLC-BTC` price with `BTC-USDT` price, you will get `RLC-USDT`, 0.00005454 * 9724 (current prices as time of writing) =  0.53023. You can also get `RLC-BTC` if `RLC-USDT` and `BTC-USDT` are specified,  0.5306 / 9724 = 0.00005456.

The `last_trade` price is probably going to be a fair bit of work, to my knowledge, we don't store this information anywhere. Likely, we need to modify `market_base` or `order_book` class, and all our connectors. @martinkou could confirm on this.

**Comment by Nullably** [comment]
@mifeng @petioptrv @cartano
The task for pure market making refactoring has been merged into `development`. We no longer have `pure_market_marking_v2.pyx`, just `pure_market_making.pyx` now. Unit test cases for it are now any files that start with `test_pmm` where `test_pmm.py` is the main one.

**Comment by mifeng** [comment]
@Nullably "if price_source_imputed_enabled is True, it is incompatible with selecting the last trade option in price_source_type." <-- I don't think we should support `last_trade` is price is imputed

**Comment by mifeng** [comment]
@petioptrv @cartano Sure, let's split this story up into 3 parts:
1. Add `price_source_type` and the `last_trade`
2. Add `price_source_mid_price_depth`
3. Add ability to use imputed price from other order books.

We are planning to release Hummingbot in 1 week and have code freeze on Thursday, so it might be better to plan this feature for the next release.

**Comment by cartano** [comment]
If at all possible could you keep 1. on this release, it adds a major feature on allowing hummingbot to run like a grid bot, and work for sat pairs; 2. may elaborate on an existing parameter but not fundamentally change the strategy, for 3. I have no sense of the value proposition. Consideration greatly appreciated.

**Comment by petioptrv** [comment]
> @petioptrv @cartano Sure, let's split this story up into 3 parts:
> 
> 1. Add `price_source_type` and the `last_trade`
> 2. Add `price_source_mid_price_depth`
> 3. Add ability to use imputed price from other order books.
> 
> We are planning to release Hummingbot in 1 week and have code freeze on Thursday, so it might be better to plan this feature for the next release.

@mifeng @cartano I suppose I can just split this up into three PRs instead of creating the tasks (as suggested when I went to create a new Feature Request issue)? In any case, I'll start work on 1 and link the PR to the relevant task when the time comes

**Comment by petioptrv** [comment]
> If at all possible could you keep 1. on this release, it adds a major feature on allowing hummingbot to run like a grid bot, and work for sat pairs; 2. may elaborate on an existing parameter but not fundamentally change the strategy, for 3. I have no sense of the value proposition. Consideration greatly appreciated.

Sorry @cartano, had a lot on my plate lately but will have more time to put into this now

**Comment by petioptrv** [comment]
@mifeng since we're giving more fine-grained control over how the price is derived (i.e. mid or last trade), would that mean that `price_source_type` would be considered even if no external exchange is specified? In other words, would `price_source_type="last_trade"` result in `pmm` considering the last trade on the exchange it is trading on as the source when `price_source_exchange` and `price_source_market` are not defined?

If no, then `price_source_type` will only be considered, as is currently the case, when `price_source_enabled=True`, and that's fairly straightforward. If yes, then how do we handle `price_source_enabled`?

**Comment by mifeng** [comment]
Hey @petioptrv sorry for the late reply - I've asked @Nullably and other members on our team to take a more active role in working with external developers.

Yes, when `price_source_exchange` and `price_source_market` are not defined, then the strategy uses the last trade's price in the current market as the mid price.

To make this clearer, I'm going to create 3 separate stories for each part.

**Comment by petioptrv** [comment]
@mifeng thank you for the clarification and for writing up the stories. I will get started with the first one
