### ISSUE TITLE
Make more params configurable on the fly

### ISSUE THREAD

**Issue by mifeng** [CoinAlpha/hummingbot#1716]
In the PMM strategy, all parameters that do not entail changing markets should be configurable on the fly. I think they should take into effect at the next tick if possible 

The key ones include:
- `order_amount`
- `order_levels`
- `order_level_spread`
- `filled_order_delay
- `inventory_skew_enabled`
- `inventory_target_base_pct`
- `inventory_range_multiplier`

**Comment by thomasyit** [comment]
if there are so many key options to configure in the future, possible to allow user to add it as a separate strategy file. similar to this feature request:  https://github.com/CoinAlpha/hummingbot/issues/1968

**Comment by vic-en** [comment]
In order to make `inventory_target_base_pct` configurable on the fly for DEXs, I'd modify the `UserBalance` class to manage balances for DEXs as well.
