### ISSUE TITLE
[BUG] Inventory skew: amount adjustment error - both sized adjusted down

### ISSUE THREAD

**Issue by carlolm** [CoinAlpha/hummingbot#1719]
**Describe the bug**

Inventory skew adjustment is downsizing both bid and ask sides (< 100%) even though one side should be > 100%:

![image](https://user-images.githubusercontent.com/12274903/81490028-a22afb00-9231-11ea-9e22-ec92b26b1e16.png)

![image](https://user-images.githubusercontent.com/12274903/81489999-3c3e7380-9231-11ea-8cb5-774ca2b587ce.png)

**Steps To Reproduce**

- bot configured with multiple orders (3 levels)
- inventory skew enabled with 50% target

![image](https://user-images.githubusercontent.com/12274903/81490131-19ad5a00-9233-11ea-9724-47f37e64ab58.png)

**Comment by mifeng** [comment]
I believe #1936 may have fixed this issue. @dennisocana can you assign someone from support to see if this bug still exists?

**Comment by dennisocana** [comment]
@mifeng tested and confirming fixed. One side is downsized while the opposite is increased in amount.

<img width="344" alt="xq5K3Q1NdJ" src="https://user-images.githubusercontent.com/50150287/86879108-0298c480-c11d-11ea-890e-30142d5fa353.png">
<img width="339" alt="3JAPuZiIVw" src="https://user-images.githubusercontent.com/50150287/86879117-0593b500-c11d-11ea-8e68-a2bb95f5b8e5.png">
