### ISSUE TITLE
New PMM param: ping_pong

### ISSUE THREAD

**Issue by mifeng** [CoinAlpha/hummingbot#1720]
## Summary
Enables the common ping pong bot strategy, in which the bot alternates buys and sells.

## Type
`bool`

## Description
If True, when order proposals are generated in PMM, don't replace the imbalanced order levels that were filled during the cycle. I think this would involve keeping track of a `level_balance` variable throughout orders:
* User sets order levels [2,1,1,2] (2 buys and 2 sells)
* 2 buy orders are filled, `level_balance` = -2, so bot only places 2 sell levels
* 1 sell order is filled: `level_balance`= -1, so bot places 1 buy level and 2 sell levels
* another sell order is filled: `level_balance`= 0, so bot places 2 buy level and 2 sell levels

**Comment by petioptrv** [comment]
Hey @mifeng this feature seems very useful to have, and I'd like to take it on if no one has started work on it already.

**Comment by mifeng** [comment]
@petioptrv that would be great - it's all yours!

We will release your price band feature later today - thanks very much for working on it! A number of users have already started using it.

**Comment by petioptrv** [comment]
> @petioptrv that would be great - it's all yours!
> 
> We will release your price band feature later today - thanks very much for working on it! A number of users have already started using it.

@mifeng glad to hear it! I've been meaning to get some hands-on experience with Cython for some time now, so I'm happy I discovered `hummingbot`. Your code and architecture are very clean! Also, been going over some of the reading material (whitepaper and such), and am digging the initiative

**Comment by petioptrv** [comment]
> ## Summary
> Enables the common ping pong bot strategy, in which the bot alternates buys and sells.
> 
> ## Type
> `bool`
> 
> ## Description
> If True, when order proposals are generated in PMM, don't replace the imbalanced order levels that were filled during the cycle. I think this would involve keeping track of a `level_balance` variable throughout orders:
> 
> * User sets order levels [2,1,1,2] (2 buys and 2 sells)
> * 2 buy orders are filled, `level_balance` = -2, so bot only places 2 sell levels
> * 1 sell order is filled: `level_balance`= -1, so bot places 1 buy level and 2 sell levels
> * another sell order is filled: `level_balance`= 0, so bot places 2 buy level and 2 sell levels

If I'm reading this right, this scenario would play out like so:

[b2, b1, s1, s2] -> [b2, b1] executed
[s1, s2] -> [s1] executed
[b1, s1, s2] -> [s1] executed
[b2, b1, s1, s2]

which means we balance [b2, b1] with two [s1]'s. I propose we instead wait to reintroduce new orders until the balance is fully restored:

[b2, b1, s1, s2] -> [b2, b1] executed
[s1, s2] -> [s1] executed
[s2] -> [s2] executed
[b2, b1, s1, s2]

What do you think?

**Comment by mifeng** [comment]
Yup, I agree with your approach - it's more intuitive for the user and works just as well!

**Comment by cartano** [comment]
value of ping/pong may be increased significantly together with PMM Extend price source param #1715 where price_source_type = last_trade instead of mid_price, especially for satoshi pairs like SC-BTC on binance. Consideration of pursuing #1720 and 1715 together appreciated.

**Comment by petioptrv** [comment]
@cartano I'd be interested to take on #1720 as well, but I'd like to deliver them one by one (not sure if that's what you were suggesting or to work on them at the same time) since it doesn't look like there will be code-overlap between the two.

**Comment by petioptrv** [comment]
@mifeng @cartano I might need some help with this bug I'm facing. This is the test case to the current implementation of pin-pong (as outlined in the original post):

```Python
    def test_multiple_orders_ping_pong(self):
        logging_options: int = (PureMarketMakingStrategyV2.OPTION_LOG_ALL &
                                (~PureMarketMakingStrategyV2.OPTION_LOG_NULL_ORDER_SIZE))

        self.clock.remove_iterator(self.strategy)
        self.ping_pong_enabled_multi_order_strategy: PureMarketMakingStrategyV2 = PureMarketMakingStrategyV2(
            [self.market_info],
            logging_options=logging_options,
            filter_delegate=self.filter_delegate,
            pricing_delegate=self.multiple_order_strategy_pricing_delegate,
            sizing_delegate=self.equal_strategy_sizing_delegate,
            order_refresh_time=self.order_refresh_time,
            ping_pong_enabled=True,
        )
        self.clock.add_iterator(self.ping_pong_enabled_multi_order_strategy)

        self.clock.backtest_til(self.start_timestamp + self.clock_tick_size)
        self.assertEqual(5, len(self.ping_pong_enabled_multi_order_strategy.active_bids))
        self.assertEqual(5, len(self.ping_pong_enabled_multi_order_strategy.active_asks))

        for i in range(2):
            ask_order = self.ping_pong_enabled_multi_order_strategy.active_asks[i][1]
            simulate_limit_order_fill(self.maker_market, ask_order)

        self.clock.backtest_til(
            self.start_timestamp + 2 * self.clock_tick_size + 1
        )
        self.assertEqual(5, len(self.ping_pong_enabled_multi_order_strategy.active_bids))
        self.assertEqual(3, len(self.ping_pong_enabled_multi_order_strategy.active_asks))

        bid_order = self.ping_pong_enabled_multi_order_strategy.active_bids[0][1]
        simulate_limit_order_fill(self.maker_market, bid_order)

        self.clock.backtest_til(
            self.start_timestamp + 3 * self.clock_tick_size + 1
        )
        self.assertEqual(5, len(self.ping_pong_enabled_multi_order_strategy.active_bids))
        self.assertEqual(4, len(self.ping_pong_enabled_multi_order_strategy.active_asks))
```

The second-to-last line fails with assert 5 != 0. After the second `simulate_order_fill`, one of the **ask** orders doesn't get cancelled. It remains as active-non-hanging and gets sent for cancellation at each step (if I run more steps) in `StrategyBase.c_cancel_order`, but never actually cancels. If I add a third simulated order fill to consume that first ask order, like so :

```Python
...
        bid_order = self.ping_pong_enabled_multi_order_strategy.active_bids[0][1]
        ask_order = self.ping_pong_enabled_multi_order_strategy.active_asks[0][1]
        simulate_limit_order_fill(self.maker_market, bid_order)
        simulate_limit_order_fill(self.maker_market, ask_order)

        self.clock.backtest_til(
            self.start_timestamp + 3 * self.clock_tick_size + 1
        )
        self.assertEqual(5, len(self.ping_pong_enabled_multi_order_strategy.active_bids))
        self.assertEqual(4, len(self.ping_pong_enabled_multi_order_strategy.active_asks))
```

then the first **bid** order is the one that hangs and doesn't get cancelled. I wanted to continue chasing the problem down to `MarketBase.c_cancel` but it looks like that code is in `hummingsim` and is not open-source. Any pointers?

**Comment by mifeng** [comment]
@petioptrv can you make a PR so that our engineer @Nullably can look at the issue?

**Comment by cartano** [comment]
please consider to define the behavior of ping / pong param with hanging orders / or whether ping pong and hanging orders exclude each other.
