### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by SteveMBao** [CoinAlpha/hummingbot#1723]
**Feature Suggestion**
// A succinct description of **how you want to achieve the desired behavior**.
// If you have looked at the code and know exactly what code changes are needed then please _consider submitting a pull request_ instead.
Hello hummingbot Team, how do I debug cython code with python? can someone help me? Many thx.
**Impact**
// A succinct description of **why you want the _desired behavior_** specified above.
The desired behavior will allow me to ...

**Additional context**

**Comment by mifeng** [comment]
Here are some suggestions:
1. Use the debug console: https://docs.hummingbot.io/developers/debug/
2. Add `print` statements in the code

Also, the fastest way to get answers to questions like this is via [Discord](https://discord.hummingbotio), where we provide 24/7 support
