### ISSUE TITLE
[BUG] Bot keeps on reporting trading rule errors upon starting.

### ISSUE THREAD

**Issue by Nullably** [CoinAlpha/hummingbot#1731]
**Describe the bug**
Bot keeps on reporting trading rule errors upon starting.
![image](https://user-images.githubusercontent.com/37262506/81763889-de48af00-9502-11ea-9fd2-4adad87a9aef.png)

Upon closer inspection, it is actually the withdraw rules API that Binance has deprecated.
![image](https://user-images.githubusercontent.com/37262506/81764018-28319500-9503-11ea-9714-bb8a48353c39.png)

Please note, this issue is happening on and off in the past 3-4 days. It doesn't affect already running bots, and doesn't affect every user. The API is now back to normal.

**Steps To Reproduce**
Run the bot on any pure market making on Binance

**Release version**
Affect all version

**Comment by mifeng** [comment]
This is caused by a recently deprecated Binance endpoint. We have released hotfix version v0.26.1 today to fix this issue on `master` branch and will fix on `development` branch shortly.
