### ISSUE TITLE
[Feature] restart shortcut

### ISSUE THREAD

**Issue by Pascal66** [CoinAlpha/hummingbot#1750]
When changing config parameter 
**Impact**
The desired behavior will allow me to restart instead of typing stop & start

**Comment by mifeng** [comment]
We have an existing story to make more params configurable on the fly: https://github.com/CoinAlpha/hummingbot/issues/1716

Would that story fix the need for this command?

**Comment by Pascal66** [comment]
No, I meen when we do exit and be back, having a story command for the last closed one or a list of all session in past
