### ISSUE TITLE
[Feature] Sessions history

### ISSUE THREAD

**Issue by Pascal66** [CoinAlpha/hummingbot#1751]
Having a session_history can be helpfull

**Impact**
The desired behavior will allow me to have a sessions history (like history) for a period or for all periods

**Comment by mifeng** [comment]
Can you please elaborate with more details?

**Comment by Pascal66** [comment]
I think when we do exit and be back, having a session_history command for the last closed one or a list of all session in past

**Comment by phbrgnomo** [comment]
This would create a "memory" of each session.

Maybe the bot could save the performance information when `exit` command is entered in a file with a name related to the strategy .yml file.

strategy_pmm_1.yml --> `exit` --> add performance information on strategy_pmm_1_old_sessions_performance.csv

Could be added to the issue [#2129](https://github.com/CoinAlpha/hummingbot/issues/2129) scope.

**Comment by PtrckM** [comment]
Current `history` command already has this feature.
![image](https://user-images.githubusercontent.com/54516858/104443496-75ee2800-55d1-11eb-8f81-98af48fb89e3.png)

```
history --verbose  #displays a list of past trades 
history --days #retrieve x number of days
history --precision #decimal precision
```
