### ISSUE TITLE
[Feature] Exponential backoff logic in Binance connector

### ISSUE THREAD

**Issue by mifeng** [CoinAlpha/hummingbot#1754]
**Feature Suggestion**
* Add an exponential backoff, and recovery, mechanism to `AsyncCallScheduler`
* Try to catch 418 and 429 errors in Binance market connector, and notify its `_async_scheduler` on such errors to activate exponential backoff behavior.

**Impact**
When request rate limits are exceeded in Binance, their API endpoints would first respond with a HTTP 429 error to indicate the client should slow down. After a while it'd become an HTTP 418 error which means the client is banned for 1 hour.

Currently, Hummingbot would just keep on sending requests as normal when it sees these errors, which usually results in it getting banned when, e.g. the user is running too many instances from the same IP.

We should make Hummingbot handle this kind of errors more gracefully. When it sees HTTP 429, it should slow down its API requests rate, and try to avoid getting 418 banned.

**Comment by dennisocana** [comment]
With the improved API Throttlers in development and managing via `rate_limits_share_pct` global config, it should be rare to the exceed the exchange's rate limits. This story was created before the implementation of API throttlers. Should we find the need to do this in the future, we will reopen the story.
