### ISSUE TITLE
[Feature] Proxy for users without direct connection to Exs

### ISSUE THREAD

**Issue by livelybug** [CoinAlpha/hummingbot#1758]
**Feature Suggestion**
* Add proxies in the configuration of hummingbot, for users without direct connections to Exs to use hummingbot.  

**Impact**
* Connections to Exs are banned for some users.

**Comment by carlolm** [comment]
Unfortunately, we are unable to accommodate this request since Hummingbot is not intended to circumvent any exchange rules or requirements.

**Comment by livelybug** [comment]
Thank you for your reply.
To confirm if the request is understood.
The request is not about providing proxies to users but adding configuration of proxies, for users to use their own proxies.
