### ISSUE TITLE
The bot dont open, even if is the last version 0.26.1[BUG]

### ISSUE THREAD

**Issue by Pacimaker** [CoinAlpha/hummingbot#1760]
**Describe the bug**
// A clear and concise description of what the bug is.

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: ...
2. Start the bot using this command: ...
...

**Screenshots**
// If applicable, add screenshots to help explain your problem.

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT p
[New Text Document (2).txt](https://github.com/CoinAlpha/hummingbot/files/4632432/New.Text.Document.2.txt)

ublish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**Soptea Cristian

**Comment by Clint-G13** [comment]
@Pacimaker Can you please send us a screenshot of or recording when the crashing happens, I send you a DM on discord as well to follow up on this concern since I installed 0.26.1 on my side and did not get any issue.

**Comment by Clint-G13** [comment]
Found out that the user is running Hummingbot on a Windows 7 operating system and verified that his OS can only support version 0.24.1. Version 0.25.0 to the latest version crash even if the latest Visual C++ redistributable packages are installed.

**Comment by mifeng** [comment]
Thanks @Clint-G13. I'm closing this issue since our system requirements for Windows are 10 or greater.

<img width="718" alt="Screen Shot 2020-05-15 at 10 21 12 AM" src="https://user-images.githubusercontent.com/1795030/82078340-d53c1700-9695-11ea-8b4b-a9b3d6124f17.png">
