### ISSUE TITLE
[Feature] Support Ethereum's decentralized exchanges

### ISSUE THREAD

**Issue by DaniellMesquita** [CoinAlpha/hummingbot#1764]
- [ ] UniSwap
- [ ] Kyber
- [ ] 1inch

**Comment by mifeng** [comment]
We have some of these tracked already:
* A community member has submitted a pull request for a [Kyber](https://github.com/CoinAlpha/hummingbot/pull/1368) connector
* [Uniswap](https://github.com/CoinAlpha/hummingbot/issues/1710) is on the roadmap

I believe 1inch is a DEX aggregator - Hummingbot connectors are for primary venues only.
