### ISSUE TITLE
[Refactor] Convert arbitrage market orders to limit taker orders

### ISSUE THREAD

**Issue by mifeng** [CoinAlpha/hummingbot#1777]
Currently we use market orders in the arbitrage and XEMM strategies. This makes sense for XEMM since the taker leg is only executed after a fill has occurred in the maker leg. 

However, since the arbitrage strategy executes both legs simultaneously, this behavior is risky since market orders can fail, which is why we have logic in the arbitrage strategy to limit retries if one leg fails. Using limit taker orders would be safer and allow us to adjust how the arbitrage strategy works.

# What
* Change order type in the arbitrage strategy to limit taker orders
* Adjust the retry logic so that the bot retries only if there's an error. If the limit order is successfully placed, the bot doesn't retry
* Placed limit taker orders should appear in `status`

**Comment by spmcelrath** [comment]
Has this actually been resolved and included in 0.28.0? Don't see any linked PRs.

**Comment by mifeng** [comment]
Actually, this story hasn't been completed yet - it was moved to Released accidentally. I will move it back
