### ISSUE TITLE
[BUG] Cross exchange refreshing orders rapidly on a liquid market

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#1792]
Cross exchange market making on liquid markets like BTC and ETH pairs causes orders to refresh every second then resulting to hitting the exchange's API rate limit.

This behavior doesn't happen on illiquid markets and currently supported DEXs.

![qUPnxCej3G](https://user-images.githubusercontent.com/50150287/82535513-87358080-9b79-11ea-9d2d-2eb8da9c90f8.gif)

[logs_krbn_bch_usdt.log](https://github.com/CoinAlpha/hummingbot/files/4661164/logs_krbn_bch_usdt.log)
[conf_krbn_bch_usdt.txt](https://github.com/CoinAlpha/hummingbot/files/4661178/conf_krbn_bch_usdt.txt)

**Version** : latest 0.27.0
**Environment** : Docker in AWS EC2 instance running on Ubuntu 18.04 LTS

**Comment by rxlxrxsx** [comment]
Ran the bot using the following markets and pairs below for 3 hours but wasn't able to reproduce the issue on the latest version (v0.33.1). Closing this now.

Maker market - pair: Kraken - BTC-USDC
Taker market - pair: Bittrex - BTC-USDT

Logs: [logs_conf_xemm_1.log](https://github.com/CoinAlpha/hummingbot/files/5671948/logs_conf_xemm_1.log)
Config: [conf_xemm_1.yml.zip](https://github.com/CoinAlpha/hummingbot/files/5671952/conf_xemm_1.yml.zip)
