### ISSUE TITLE
[BUG] PMM Bamboo relay } Error formatting market stats

### ISSUE THREAD

**Issue by rennel-tabing** [CoinAlpha/hummingbot#1793]
**Describe the bug**
// A clear and concise description of what the bug is.
Unable to start a strategy
**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: ...
Please note that I also tried a different pair (WETH-USDC) and had the same error
```
########################################################
###       Pure market making strategy config         ###
########################################################

template_version: 14
strategy: pure_market_making

# Exchange and token parameters.
exchange: bamboo_relay

# Token trading pair for the exchange, e.g. BTC-USDT
market: ZRX-WETH

# How far away from mid price to place the bid order.
# Spread of 1 = 1% away from mid price at that time.
# Example if mid price is 100 and bid_spread is 1.
# Your bid is placed at 99.
bid_spread: 10.0

# How far away from mid price to place the ask order.
# Spread of 1 = 1% away from mid price at that time.
# Example if mid price is 100 and ask_spread is 1.
# Your bid is placed at 101.
ask_spread: 10.0

# Time in seconds before cancelling and placing new orders.
# If the value is 60, the bot cancels active orders and placing new ones after a minute.
order_refresh_time: 30.0

# The spread (from mid price) to defer order refresh process to the next cycle.
# (Enter 1 to indicate 1%), value below 0, e.g. -1, is to disable this feature - not recommended.
order_refresh_tolerance_pct: 0.0

# Size of your bid and ask order.
order_amount: 32.0

# Price band ceiling.
price_ceiling: -1.0

# Price band floor.
price_floor: -1.0

# Whether to enable Inventory skew feature (true/false).
inventory_skew_enabled: false

# Target base asset inventory percentage target to be maintained (for Inventory skew feature).
inventory_target_base_pct:

# The range around the inventory target base percent to maintain, expressed in multiples of total order size (for
# inventory skew feature).
inventory_range_multiplier: 1.0

# Ox ONLY - Sets the expiration of limit orders. Minimum is 130 seconds.
order_expiration_time: 130.0

# Number of levels of orders to place on each side of the order book.
order_levels: 1

# Increment size of consecutive orders after the first order (if order_levels > 1).
order_level_amount: 0

# Order price space between orders (if order_levels > 1).
order_level_spread: 1.0

# How long to wait before placing the next order in case your order gets filled.
filled_order_delay: 60

# Whether to stop cancellations of orders on the other side (of the order book),
# when one side is filled (hanging orders feature) (true/false).
hanging_orders_enabled: false

# Spread (from mid price, in percentage) hanging orders will be canceled (Enter 1 to indicate 1%)
hanging_orders_cancel_pct: 10.0

# Whether to enable order optimization mode (true/false).
order_optimization_enabled: false

# The depth in base asset amount to be used for finding top bid and ask (for order optimization mode).
order_optimization_depth: 0

# Whether to enable adding transaction costs to order price calculation (true/false).
add_transaction_costs: false

# Whether to use external pricing source for the mid price (true/false).
price_source_enabled: false

# The type of external pricing source (exchange/custom_api).
price_source_type:

# An external exchange name (for external exchange pricing source).
price_source_exchange:

# A trading pair for the external exchange, e.g. BTC-USDT (for external exchange pricing source).
price_source_market:

# An external api that returns price (for external custom_api pricing source).
price_source_custom:

# For more detailed information, see:
# https://docs.hummingbot.io/strategies/pure-market-making/#configuration-parameters
```

2. Start the bot.
...

**Screenshots**
// If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/53868268/82572251-14fd7580-9b52-11ea-91f9-987e93f9ec85.png)

**Release version**
0.27.0
dev-0.28.0
docker

**Attachments**
[ZRX-WETH-logs0.28.0.txt](https://github.com/CoinAlpha/hummingbot/files/4663117/ZRX-WETH-logs0.28.0.txt)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by rennel-tabing** [comment]
@Arctek Can you check on this if you have a chance? Thank you.

**Comment by Arctek** [comment]
Ok so from what I can see if you start the strategy and type `status` then this fails because the networking has not yet initialized and so no prices/orderbooks etc have been loaded.

Not sure if this is something I should do something about in my strategy? (I.e. return 0 price)
Or if the status command when it goes through `market_status_data_frame` should probably check that the markets are loaded first before asking for the price?

**Comment by Dante2333** [comment]
Thanks @rennel-tabing for documenting this bug. I manage to get it to work on WETH-USDC markets but could not get it to work with a unverified contract which did not have an orderbook.

**Comment by mifeng** [comment]
@rennel-tabing please confirm if this issue is related to hitting status as soon as strategy starts. If markets aren't ready, it'll throw an error on every market and that is expected behavior. Otherwise, let Josh know if this error affects status after markets are ready.

**Comment by Clint-G13** [comment]
Confirmed that the error is due to running `status` while the market isn't ready. Somehow it takes around 20 sec or more for the market to initialize
![bamboo](https://user-images.githubusercontent.com/57189990/82624864-46d81000-9c16-11ea-8b4c-8f3a8c9e8831.PNG)

**Comment by PtrckM** [comment]
- Unable to cancel order unless do `exit -f` or wait to expire
![image](https://user-images.githubusercontent.com/54516858/82648871-f333e980-9c4a-11ea-8b65-b789c27fd6b4.png)
![image](https://user-images.githubusercontent.com/54516858/82648891-f7f89d80-9c4a-11ea-89e7-bfbfaf155679.png)

- when you try to start again on the same config
![image](https://user-images.githubusercontent.com/54516858/82648934-0e065e00-9c4b-11ea-8c15-f3bfb45b4de6.png)

**Comment by Arctek** [comment]
@PtrckM Can I have the logs for that?
Probably trying to double-cancel orders is what is happening.

**Comment by PtrckM** [comment]
sure here you go @Arctek 
[logs_conf_pure_mm_8.log](https://github.com/CoinAlpha/hummingbot/files/4667393/logs_conf_pure_mm_8.log)

**Comment by Arctek** [comment]
@PtrckM see my PR - https://github.com/CoinAlpha/hummingbot/pull/1800

Looks like the newer version of Web3.py expects the ABI-encoded addresses to also be checksummed now, so I've added this.

**Comment by rennel-tabing** [comment]
Yes, the error only occurs before hitting the `INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...` message.

Another issue that a user noticed is that when using the DEX-WETH pair, it throws an error of

```
File "hummingbot/market/bamboo_relay/bamboo_relay_market.pyx", line 1406, in hummingbot.market.bamboo_relay.bamboo_relay_market.BambooRelayMarket.execute_trade
    exchange_order_id, zero_ex_order = await self.submit_limit_order(trading_pair=trading_pair,
  File "hummingbot/market/bamboo_relay/bamboo_relay_market.pyx", line 1194, in submit_limit_order
    base_token_asset_data = "0xf47261b0000000000000000000000000" + remove_0x_prefix(tokens[pair_split[0]].address.lower())

``` 

This seems to be isolated to this pair and it seems that it is a newly listed token on bamboo relay
[PureMM-DXD-WETH-logs.txt](https://github.com/CoinAlpha/hummingbot/files/4668424/PureMM-DXD-WETH-logs.txt)
[PureMM-DXD-WETH.txt](https://github.com/CoinAlpha/hummingbot/files/4668425/PureMM-DXD-WETH.txt)

I am able to reproduce this behavior on my end. Let me know if this issue is not related to the original inquiry so that I can submit a separate git issue

**Comment by Arctek** [comment]
@rennel-tabing I think this is expected behavior, if a token doesn't exist in the `/hummingbot/wallet/ethereum/erc20_tokens.json` file or manually added to the config as a custom token then it wont work AFAIK.

**Comment by Dante2333** [comment]
@Arctek will try that and report back.

**Comment by Dante2333** [comment]
There's on more issue though, orders are expiring too fast even though I increased orders expiration time for 0x based exchanges. Should i make another thread or report to @rennel-tabing ?

**Comment by Dante2333** [comment]
Ive run into more errors related to bamboo relay, some considerations:

1 - The coordinator should be used or i'll run into 20 transactions that need to pay gas and does not make a lot of sense, so maybe turn that on by default, Joshua from Bamboo has been informed about this

More bugs:
1 - The bot will get network errors after some orders fill which then will stop setting orders and keep mentioning that its canceling orders
2 - From time to time, random errors appear and the bot wont go into next cycle, this is related to the cancelled orders.

[eth-dxd3.log](https://github.com/CoinAlpha/hummingbot/files/4674515/eth-dxd3.log)
[dxd-eth2.log](https://github.com/CoinAlpha/hummingbot/files/4674518/dxd-eth2.log)
[dxd-eth.log](https://github.com/CoinAlpha/hummingbot/files/4674519/dxd-eth.log)

**Comment by mifeng** [comment]
@Dante2333 For order books with no orders, we recommend that users use the **external price source** feature to use a price from a different order book or from a custom endpoint: https://docs.hummingbot.io/strategies/advanced-mm/price-source/
