### ISSUE TITLE
[BUG] Error Sending Transaction-Replacement Transaction Underpriced

### ISSUE THREAD

**Issue by nsshommo** [CoinAlpha/hummingbot#180]
**Describe the bug**
Tried to do cross-exchange market making between RadarRelay and Binance.  It is showing error as shown in the screenshot.

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: Cross Exchange MM, Maker: RadarRelay, Taker: Binance
2. Start the bot using this command: Conf, Start

**Screenshots**
![1](https://user-images.githubusercontent.com/31445351/57201590-c881df00-6fbc-11e9-8e3d-2ba5241a64d5.png)

**Release version**
Version 0.5.0

**Attachments**
N/A

**Comment by mifeng** [comment]
@nsshommo Can you post your strategy config file and log file please?

**Comment by martinkou** [comment]
Were you running multiple bots based on the same wallet? Seems like to me that the bot was sending out a transaction with the same nonce of another transaction from a different bot.

One way to fix it is probably to set up some IPC mechanisms for different bot instances to sync their wallet nonces.

**Comment by mifeng** [comment]
I don't think the user was running multiple bots since he is one of our contract testers. 

@nsshommo this bug may be fixed now - are you still seeing this issue?

**Comment by chowryan** [comment]
old bug that should be fixed. please reopen if it's still an issue.
