### ISSUE TITLE
[BUG] Hanging orders are cancelled when order_refresh_tolerance_pct is triggered

### ISSUE THREAD

**Issue by masonyoungblood** [CoinAlpha/hummingbot#1805]
Hanging orders are cancelled every time that order_refresh_tolerance_pct is triggered and new orders are created. I'm using Kucoin in paper trading mode with single orders, and this bug has been replicated across multiple coin pairs. hanging_orders_cancel_pct is set much higher than order_refresh_tolerance_pct so they are not being triggered at the same time.

My most recent configuration resulting in this bug is attached below.

![Screenshot from 2020-05-23 18-51-12](https://user-images.githubusercontent.com/43799018/82742545-a6750f00-9d2d-11ea-8681-da2e1d8aafd0.png)

**Describe the bug**
// A clear and concise description of what the bug is.

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: ...
2. Start the bot using this command: ...
...

**Screenshots**
// If applicable, add screenshots to help explain your problem.

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by devoger** [comment]
The issue occurs when order_tolerance_pct triggers, all hanging orders are cancelled.
I was able to reproduce the issue with the following configurations:
Docker
version 0.27.0

![config-cancel-1](https://user-images.githubusercontent.com/8411294/82746236-28ae1380-9dc0-11ea-95fd-34cf2b57d233.png)

Hanging Orders before the order_refresh_tolerance_pct triggers
![hang-yes](https://user-images.githubusercontent.com/8411294/82746255-5004e080-9dc0-11ea-8d32-d443f6d4c7cc.png)

After order_refresh_tolerance_pct triggers
![cancel-yes-hang](https://user-images.githubusercontent.com/8411294/82746263-5abf7580-9dc0-11ea-8857-def944e8de59.png)

**Comment by PtrckM** [comment]
Similar with https://github.com/CoinAlpha/hummingbot/issues/1653
