### ISSUE TITLE
[Feature] Allow filtering by trading pair in miner app 

### ISSUE THREAD

**Issue by mhardock** [CoinAlpha/hummingbot#1807]
**Feature Suggestion**
Allow users to filter and choose which trading pairs they want to view the latest earnings for. Currently we can only view all the trading pairs together in the same chart. Total earnings should then read for only the trading pairs selected.

**Impact**
Easier readability for users. Currently it is difficult to judge the performance of a single trading pair when they are all stacked on top of each other, and the hourly/daily rewards for a specific trading pair can't be calculated unless all the snapshots are added together manually.

**Additional context**

**Comment by dennisocana** [comment]
Created a clubhouse story internally for miner-related issues and feature suggestions.
