### ISSUE TITLE
[Feature] Ability to become a Market Taker with zero/negative bid and ask spread value.

### ISSUE THREAD

**Issue by zksnar** [CoinAlpha/hummingbot#1817]
**Feature Suggestion**
1. Need to allow 0 or negative bid_spread and ask_spread value so that it can sell or buy into the existing orders. This will allow buying or selling coins at certain price until inventory skew is met.

2. Need random order refresh time. A min_order_refresh_time and max_order_refresh_time would be a great addition to go with this. (but also for pure market making strategy)

**Impact**
// A succinct description of **why you want the _desired behavior_** specified above.
1. To be able to accumulate or offload certain amount of coins at random times.
2. Allows maker trade volume. It can be wash, but also genuine buy/sell volume.

This would make hummingbot an essential tool for not just market makers but also to genuine buyers or sellers.

**Comment by phbrgnomo** [comment]
This could also be implemented as a script function, so the bot would act as a buyer only on specific condition.
