### ISSUE TITLE
[Feature] Allow backtesting against tick data

### ISSUE THREAD

**Issue by cryptochassis** [CoinAlpha/hummingbot#1821]
When comprehensive historical tick data are available, it will be very useful for hummingbot to allow for backtesting against such data sets. At this moment, it isn't clear how to accomplish this. Assume there are some csv files containing data for historical tick quotes and/or tick trades, for exmaple:
trade.csv, where each data point represents a trade
timestamp,price,size
...
quote.csv, where each data point represents a new quote on the tick level
timestamp,bid_price,bid_size,ask_price,ask_size
...
We'd like to run hummingbot's pure market-making strategy for a given historical period of time on such data sets to conduct some research. Thank you.

**Comment by fengkiej** [comment]
Related discussion

https://quant.stackexchange.com/questions/38781/backtesting-market-making-strategy-or-microstructure-strategy

**Comment by phbrgnomo** [comment]
Backtesting wont be added to hummingbot client, but our team is working on developing a backtest specific tool.
