### ISSUE TITLE
[BUG + REFACTOR] Client actively cancels orders by default on DEXs

### ISSUE THREAD

**Issue by mifeng** [CoinAlpha/hummingbot#1833]
**Describe the bug**
Currently, running a bot on Ethereum DEXs like Radar and Bamboo results in active order cancellations. This results in a high gas payment every minute if the user sets `order_cancellation_time`.

**Logs**
[logs_conf_pure_mm_13.log](https://github.com/CoinAlpha/hummingbot/files/4737880/logs_conf_pure_mm_13.log)

**Release version**
`dev-0.28.0`

**How to fix**
I think we should use this opportunity to refactor up how we handle DEXs that require gas for cancellations while fixing this particular bug. This includes Radar Relay, Bamboo Relay, and others in the future as well:

## General
* Add a global param called `0x_exchange_actively_cancel_orders`, default is False
* This param is only used for 0x DEX: [Bamboo, Radar]
* If this parameter is True, ask the expiration question during `create` instead of the refresh time question.
* If this parameter is True, ignore `order_refresh_time` and use `order_expiration_time` in place of the cancel timer in the `c_tick()` function in the PMM strategy, and expire the order instead of cancelling it.

## XEMM
* The XEMM strategy has some code to handle active cancellations vs letting the code expire. I don't think this should be above the strategy layer since it affects all strategies.
* It also has logic so that if a trade is unprofitable, it will actively cancel the order. I think we should remove this entirely since users can customize how the bot behaves after we have Scripts.

**Comment by vic-en** [comment]
**For PMM**

- I noticed that expiration_seconds is actually initiated to order_refresh_time. In order words, order_refresh_time is **also** used to expire 0x orders aside being used to refresh orders. So there's no point trying to prompt for expiration_seconds during create command.
- I added code to delay till orders expire when `0x_exchange_actively_cancel_orders` is set to `false`

**For XMM**

- I removed logic that actively cancels order if unprofitable as requested. The logic is implemented in `c_check_if_still_profitable(...)`
- There's actually no logic that waits for order to expire. What does something close to that is `c_check_if_price_has_drifted(...)`.

**Comment by vic-en** [comment]
Note that users can still get errors if they set `0x_exchange_actively_cancel_orders` to `True`. Should the logic remain like that?

Also, should I add the expiration logic in XMM too?

**Comment by mifeng** [comment]
@vic-en Actually, please replace the code removed in XMM. I think that function may be used for other aspects of XMM. After further thought, I think changing it now is risky and we should leave that strategy till later on.

**Comment by mifeng** [comment]
In the new PMM strategy, I see:
```
    cdef c_execute_orders_proposal(self, object proposal):
        cdef:
            double expiration_seconds = (self._order_refresh_time
                                         if ((self._market_info.market.name in self.RADAR_RELAY_TYPE_EXCHANGES) or
                                             (self._market_info.market.name == "bamboo_relay" and
                                              not self._market_info.market.use_coordinator))
                                         else NaN)
```

Where is the logic that sets the order expiration time to be 130 seconds or greater?

**Comment by vic-en** [comment]
> 
> 
> In the new PMM strategy, I see:
> 
> ```
>     cdef c_execute_orders_proposal(self, object proposal):
>         cdef:
>             double expiration_seconds = (self._order_refresh_time
>                                          if ((self._market_info.market.name in self.RADAR_RELAY_TYPE_EXCHANGES) or
>                                              (self._market_info.market.name == "bamboo_relay" and
>                                               not self._market_info.market.use_coordinator))
>                                          else NaN)
> ```
> 
> Where is the logic that sets the order expiration time to be 130 seconds or greater?


It is in the strategy_base file.

`self._sb_limit_order_min_expiration = 130.0`

        cdef:
            dict kwargs = {
                "expiration_ts": self._current_timestamp + max(self._sb_limit_order_min_expiration, expiration_seconds)
            }

**Comment by mifeng** [comment]
@vic-en Please remove this code in the strategy base class. We'll make this the user's responsibility to handle, such that users who trade on 0x DEXs should know that `order_refresh_time` sets expiration time, not cancel time.
