### ISSUE TITLE
Unable to connect to Trust WalletConnect

### ISSUE THREAD

**Issue by pulkitsharma** [CoinAlpha/hummingbot#1835]
**Decribe the bug:**
I am able to connect the wallet on Trust mobile app browser. But when I connect on computer, it gives error.

**Steps To Reproduce:**

Here are the steps to reproduce the issue (see attachments in the section below):

Install Trust wallet on your mobile device.
Go to the Hummingbot liquidity mining page and click the Connect wallet.
Choose WalletConnect.
From your Trust wallet app, click the cog/gear icon and choose WalletConnect.
Scan the bar code provided on the liquidity mining app.
Click on Approve on Trust to give permission to Hummingbot.
After confirming that Hummingbot is approved, on your Trust wallet app, check the registration page and you will see an unknown error.

Logs :
Below are the logs from Chrome console.
Failed to load resource: the server responded with a status of 401 ()
9b437cb7b91edd28b5234336862291286cbb4cf2.js:1 authenticateUser Error Error: Signed nonce cannot be validated
    at ue (9b437cb7b91edd28b5234336862291286cbb4cf2.js:1)
    at 9b437cb7b91edd28b5234336862291286cbb4cf2.js:1
    at u (9b437cb7b91edd28b5234336862291286cbb4cf2.js:1)
    at Generator._invoke (9b437cb7b91edd28b5234336862291286cbb4cf2.js:1)
    at Generator.e.<computed> [as throw] (9b437cb7b91edd28b5234336862291286cbb4cf2.js:1)
    at n (9b437cb7b91edd28b5234336862291286cbb4cf2.js:1)
    at u (9b437cb7b91edd28b5234336862291286cbb4cf2.js:1)
index.js:28611 Uncaught Error: Could not find block
    at index.js:28611
    at index.js:28666
    at index.js:28687
    at index.js:5073
    at p (index.js:14277)
    at d (index.js:14270)
    at index.js:5090
    at index.js:5194
    at 9b437cb7b91edd28b5234336862291286cbb4cf2.js:1
    at l (9b437cb7b91edd28b5234336862291286cbb4cf2.js:1)

![trustwallet](https://user-images.githubusercontent.com/2555898/83965119-e7912580-a8ce-11ea-8ff1-2514f02b804c.PNG)

DiscordUsername : pulkitnitj
Eth Address : 0xe12D16d66a46b705b25a4713093AbAF4D0372302

**Comment by dennisocana** [comment]
Closing since we already migrated to using email for logging in to the miner app.
