### ISSUE TITLE
[BUG] Kill switch trigger 

### ISSUE THREAD

**Issue by moonorblue** [CoinAlpha/hummingbot#1866]
**Describe the bug**
I set my kill switch trigger with 5, and the switch was kept being triggered even there was no base position in hand.  

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):
1. set kill switch trigger with 5,
2. PMM in Binance with ZIL/BNB
3. several hours/minutes later it shows being killed because it triggered to profit -5%, but no base position at the same time. (Have filled orders before, but no base position at the time when switch triggered) 
4. even use "start" command, it will be triggered switch then. We need to exit and start the bot again to solve this issue.

**Release version**
dev-0.28.0

**Comment by moonorblue** [comment]
1. What is your Deploment environment?
a. Machine - cloud server,  4 GB RAM, 2 vCPUs, 80 GB SSD
b. Which cloud provider - AWS
c. What operating system? - Ubuntu 18.04 LTS
d. Installation type - Docker

Strategy config file: https://drive.google.com/file/d/1ERxBFhCNc5G6MWAmHK1SVqhpZ4yMhJzg/view?usp=sharing

Log file: 
https://drive.google.com/file/d/15VNEBOnoNFjKCiiFRxwUoxF_T0YacL9e/view?usp=sharing

**Comment by Clint-G13** [comment]
@moonorblue we have a similar scenario reported before wherein kill switch is triggered even when there is no trade that happened at that specific time. Base on the test we did, this can happen if there was an initial trade like an hour before then market price movement occurred which will affect your performance and can trigger the kill switch. Exiting your bot helps since this will clear the current history you have, but it may occur again once you have a filled trade and if there will be a price movement. You can check out our updated kill switch documentation for sample scenario: https://docs.hummingbot.io/advanced/kill-switch/

**Comment by moonorblue** [comment]
@Clint-G13 thanks for the reply, yes exiting bots and start again helped. As my observation, it felt like the bot did not catch some order filled: for example, bot recorded my ask orders, but it stilled marked it "unfilled" after these orders got filled. Is it make sense?

**Comment by rennel-tabing** [comment]
@moonorblue Do you mean that a particular trade were filled on your Binance account but the hummingbot does not show that it was a filled order? If that is correct,  would you mind if you can 1. let us know what time that happened and 2. the order amount in question the hummingbot placed?

**Comment by moonorblue** [comment]
@rennel-tabing yes, this is according to my telegram bot with hummingbot.  Please check the screenshot below,
1. From Binance
![b](https://user-images.githubusercontent.com/1680971/84972699-05258100-b152-11ea-8824-795578ce4fea.jpg)
2. From Telegram 
![IMG_3488](https://user-images.githubusercontent.com/1680971/84972726-1078ac80-b152-11ea-9639-6fa3688111b9.jpg)

or it was because the order was partially filled?

**Comment by Clint-G13** [comment]
@moonorblue We apologize for the delayed response regarding your last question. Yes, you are correct that you won't get a notification for your other partially filled orders. I had open another ticket regarding that matter - ([#2005](https://github.com/CoinAlpha/hummingbot/issues/2005))

**Comment by RC-13** [comment]
Closing this case, will leave other ticket related to user inquiry.
