### ISSUE TITLE
Improve Dashboard Statistics Per Pair

### ISSUE THREAD

**Issue by thomasyit** [CoinAlpha/hummingbot#1896]
When the bot is stopped, there is no other way to retrieve the history to check performance other than using  some DB reader. Once the bot stop, the history should be automatically exported to an excel sheet or sent to the Dashboard. 

Sometimes a bot can be stopped for a few reasons over the course of mining, be it a system error, system reboot, manual stop, etc. The only way to retrieve history is not to delete the telegram messages and manually aggregate the histories to have a complete picture on the bot performance.  

If possible, the Dashboard should should all previous histories of the bot, aggregation of the histories performance, and the average cost per coin.

**Comment by mifeng** [comment]
This week, we're adding a **Performance** view to the https://miners.hummingbot.io/ that shows you historical performance for each market, along with a breakdown of your total P&L between trading performance, fees, and liquidity rewards.

That should give you more info on the markets in Hummingbot Miner. Do you also run Hummingbot for other exchanges or markets not available in Hummingbot Miner? I agree that the Hummingbot client software doesn't maintain historical records well, so we might be able to improve that as well.

**Comment by thomasyit** [comment]
Hi Michael 
Nope, just on Binance. 
Good to know, any plans to allow user to change strategy file (.yaml). on the fly? for example, i am using technical indicator like moving average or RSI, if price falls below certain value, i want to increase my spread to 2% or decrease the amount of units traded to the minimum as to reduce exposure, yet still providing liquidity.  
When market is gg up, it can switch back to original file.
I understand there is a delay parameter, maybe i missing out other parameters.
Regards 
    On Wednesday, 24 June 2020, 08:47:46 am GMT+8, Michael Feng <notifications@github.com> wrote:  
 
 


This week, we're adding a Performance view to the https://miners.hummingbot.io/ that shows you historical performance for each market, along with a breakdown of your total P&L between trading performance, fees, and liquidity rewards.

That should give you more info on the markets in Hummingbot Miner. Do you also run Hummingbot for other exchanges or markets not available in Hummingbot Miner? I agree that the Hummingbot client software doesn't maintain historical records well, so we might be able to improve that as well.

**Comment by thomasyit** [comment]
close due to the performance dashboard release
