### ISSUE TITLE
[BUG] Available balance does not update on cross exchange bot until the price changes.

### ISSUE THREAD

**Issue by Alfonso-20** [CoinAlpha/hummingbot#1898]
**Describe the bug**
The cross exchange bot does not update the current available balance on the taker side after it created a buy order on the maker side, not until the price change for the market.

**Steps To Reproduce**
Market pair: COIN-BTC
What happend was that I had a manual sell order on the taker side for COIN when I started the bot. Then I canceled it to manually move it to another price, the bot updated because the price just changed and the bot made a buy order on the maker side for all the available COIN balance I had on the taker side. Then I manually put half of my available COIN for sale again on the taker side but the bot does not cancel the current buy order it have on the maker side to recreate it based on the new available COIN balance I have on the taker side. This cause a problem in case someone sell COIN on the maker side, then it does not have enough COIN balance available on the taker side to complete the trade, this will leave me with more COIN on maker side than I can sell on taker side.

**Release version**
0.28.0

**Comment by rennel-tabing** [comment]
Hi @Alfonso-20 

Please share your strategy file if you have a chance.
Hummingbot will not know if you manually add inventory , withdraw or place orders while the orders are in place. It will always see/check your inventory after the specified `limit_order_min_expiration` configuration.

**Comment by dennisocana** [comment]
No response from user, unable to investigate due to no support information packets provided.
