### ISSUE TITLE
[BUG] Best bid and ask price never updates on Kraken

### ISSUE THREAD

**Issue by Nullably** [CoinAlpha/hummingbot#1901]
**Describe the bug**
Best bid and ask price on `status` are never updated with current prices, this causes the bot to not replacing orders and to potentially submit taker orders.

**Steps To Reproduce**
Start a PMM strategy on BTC-USDC market on Kraken exchange.
Run `status` command 
<img width="1454" alt="Screenshot 2020-06-22 at 12 19 39 PM" src="https://user-images.githubusercontent.com/37262506/85249723-260a1100-b487-11ea-9da5-5646f08fcdf9.png">

On the Kraken site, look for the order book
<img width="245" alt="Screenshot 2020-06-22 at 12 19 51 PM" src="https://user-images.githubusercontent.com/37262506/85249769-40dc8580-b487-11ea-9f8e-fa2b60830a21.png">

Note the difference in prices.
This seems to affect only BTC pairs

**Comment by Clint-G13** [comment]
Re-occurring issue: We have a user that encountered the problem
![user](https://user-images.githubusercontent.com/57189990/88148557-559c6c80-cc31-11ea-83b3-9f05764c53bf.png)
Tried on the latest development with the same result:
![Kraken BTC](https://user-images.githubusercontent.com/57189990/88148751-a57b3380-cc31-11ea-8ac1-68428525335c.PNG)

**Comment by Blacksheep70** [comment]
One more hint: Can confirm that this happens only for (X)BTC. Other currencys works fine

**Comment by Clint-G13** [comment]
Test PR #2112 and confirm that it fixed this issue,
Live trade: (Despite the error that occurred on my live trade test, price update works)
![Kraken BTC price update](https://user-images.githubusercontent.com/57189990/88572268-74f02b00-d071-11ea-99e6-e7a73b558b96.JPG)
Paper trade:
![Kraken BTC price update -paper trade](https://user-images.githubusercontent.com/57189990/88572280-7c173900-d071-11ea-8ba3-025a2e1abfe6.JPG)
