### ISSUE TITLE
[Extend price source param] Change price source logic (1/4)

### ISSUE THREAD

**Issue by mifeng** [CoinAlpha/hummingbot#1917]
This is part 1 of https://github.com/CoinAlpha/hummingbot/issues/1715:

## Remove `exchange` option in `price_source_type` and add `mid_price`

Currently, the `price_source_type` parameter allows users to select whether they want to use an external exchange (`exchange`) or a custom API (`custom`) to generate the mid price used for algo trading. It is only used when `price_source_enabled` is true.

Since we're going to change `price_source_type` so that it sets the **type** of price used rather than its **source**, we don't need the exchange option anymore. Make `mid_price` the default value instead of `None`.

## Adjust `price_source_exchange` and `price_source_market`

Adjust the external price source logic so that the `price_source_exchange` and `price_source_market` params determines if we use the current order book or a different order book. If either of those params is `None`, the current order book is used. If both parameters are not `None`, then the bot

## Remove `price_source_enabled`

Given the change above, this boolean is not needed anymore.

**Comment by petioptrv** [comment]
Currently working on this.

**Comment by Nullably** [comment]
The changes here are a little confusing to me. `price_source_type` has both source of the price (custom API) and the type of the price (mid_price or last_trade) implied in the same parameter. Would it be easier to understand if we separate the parameter into 2 parameters as below 
* price_source
  This is the source of price, the choices for this are `current_market` (default), `external_market`, `custom_api`
* price_type
  The type of price used, this can be either `mid_price` (default) or `last_trade`   

If `external_market` price source is selected, `price_source_exchange` and `price_source_market` are required. The `price_source` takes a higher priority, if `current_market` or `custom_api` is selected, ignore `price_source_exchange` and `price_source_market`.
If `custom_api` is selected `price_source_custom` is required and ignore `price_type`.
We can remove `price_source_enabled`.

**Comment by petioptrv** [comment]
> @mifeng @petioptrv
> The changes here are a little confusing to me. `price_source_type` has both source of the price (custom API) and the type of the price (mid_price or last_trade) implied in the same parameter. Would it be easier to understand if we separate the parameter into 2 parameters as below
> 
> * price_source
>   This is the source of price, the choices for this are `current_market` (default), `external_market` and `custom_api`
> * price_type
>   The type of price used, this can be either `mid_price` (default) or `last_trade`
> 
> Tasks:
> 
> * Rename `price_source_custom` to `price_source_custom_api`
> * If `external_market` price source is selected, `price_source_exchange` and `price_source_market` are required and they are used only for `external_market` price_source.
> * If `custom_api` is selected `price_source_custom_api` is required and ignore `price_type`.
> * Remove `price_source_enabled`.

I like that. @mifeng?
