### ISSUE TITLE
[Extend price source param] Add mid price depth (2/4)

### ISSUE THREAD

**Issue by mifeng** [CoinAlpha/hummingbot#1918]
This is part 2 of #1715:

## Add `price_source_mid_price_depth`

This lets users ignore dust orders and control how the mid price is calculated, instead of always averaging the highest bid and lower ask orders.

When `price_source_type` equals `mid price`, this param specifies the volume (denominated in the base asset) used to determine the mid price. Default value for this param is 0.

**Comment by petioptrv** [comment]
@mifeng, to make sure I understand the problem correctly, if `price_source_mid_price_depth` is set to, say 10, and the bid and ask orders are

+ 11 at $13 a
+ 6 at $12 a
+ 4 at $11 a
- 1 at $9 b
- 5 at $8 b
- 12 at $7 b

then the mid-price will be calculated as the average of the first 10 on either side, as in
(6 * 12 + 4 * 11 + 1 * 9 + 5 * 8 + 4 * 7) / 20 = 9.65
or are we really looking for the first order with volume of at least 10, in which case it would be
(13 + 7) / 2 = 10?
