### ISSUE TITLE
[Extend price source param] Add last trade (3/4)

### ISSUE THREAD

**Issue by mifeng** [CoinAlpha/hummingbot#1919]
This is part 3 of #1715:

## Add `last_trade` option to `price_source_type`

After https://github.com/CoinAlpha/hummingbot/issues/1917, `price_source_type` allows users to input `mid_price` (default) and `custom` to specify a custom endpoint. 

Add a `last_trade` option: if users select this option, use the price of the last trade as the reference price instead of the mid price.

@Nullably do we need to add more API calls in our exchange connectors to allow for this?

**Comment by Nullably** [comment]
@mifeng Sorry for the late reply. For the `last_trade` price, I don't think we store this data in our `order_book` object, but we can do so by using trade data (we track this). This will need to be done for all connectors, and add it in to developer manual and unit tests st. new connectors will have this implemented. I will need to spend some time to understand this part of connector (the order book and how it gets updated) which I haven't really got a chance to work on yet.

**Comment by mifeng** [comment]
This story is blocked by #2036

**Comment by Nullably** [comment]
I think it'd be better to offer price type choices as they are in the `PriceType` enum.
``` python
class PriceType(Enum):
    MidPrice = 1
    BestBid = 2
    BestAsk = 3
    LastTrade = 4
```
 This offers users more options and make the code cleaner as well.
