### ISSUE TITLE
[BUG] 0x_active_cancels inconsistently cancels orders

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#1924]
**Describe the bug**

When `0x_active_cancels` is set to `True`, the expected behavior is that the orders should be cancelled instead of expiring. The logs below shows that the orders are sometimes cancelled and sometimes expired.

Out of 26 orders created, only 6 of them were cancelled. And the logs says the order has expired even though it was cancelled.

[0x_active_cancels_enabled.log](https://github.com/CoinAlpha/hummingbot/files/4823755/0x_active_cancels_enabled.log)

![](https://user-images.githubusercontent.com/50150287/85517177-9785c300-b631-11ea-8d56-23e0f22c2baa.png)

![](https://user-images.githubusercontent.com/50150287/85514358-89827300-b62e-11ea-885a-95eb7f3cfdd4.png)

The logs below shows when `0x_active_cancels` is disabled for comparison.

[0x_active_cancels_disabled.log](https://github.com/CoinAlpha/hummingbot/files/4823759/0x_active_cancels_disabled.log)

**Release version** : 0.28.0

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1pd1c99) by [Unito](https://www.unito.io)

**Comment by RC-13** [comment]
Closing ticket, `0x_active_cancels` parameter has been deprecated.
