### ISSUE TITLE
[BUG] Order refresh tolerance causes to skip order proposals on DEX

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#1925]
**Describe the bug**

May be related to https://github.com/CoinAlpha/hummingbot/issues/1924 , orders expire when they reach `order_refresh_time` value disregarding the `order_refresh_tolerance_pct` parameter.

For example, orders were created at 07:48 and order refresh time is set to every 5 minutes. At 07:53 the spreads did not go above the 1% tolerable change but the orders still expired. There were no active orders during that 5 minute interval.

![](https://user-images.githubusercontent.com/50150287/85521428-d1a59380-b636-11ea-9db9-c69b39b1655a.png)

![](https://user-images.githubusercontent.com/50150287/85521457-dbc79200-b636-11ea-8e1e-5be6068c2bc9.png)

**Steps To Reproduce**

1. Run a pure market making bot on Radar Relay
1. Set `order_refresh_tolerance_pct` to a positive value like `1.0`

**Release version** : 0.28.0

**Log file** : [logs_test_radar_relay.log](https://github.com/CoinAlpha/hummingbot/files/4824067/logs_test_radar_relay.log)

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1pd1c9t) by [Unito](https://www.unito.io)

**Comment by RC-13** [comment]
Closing ticket, affected connector has been deprecated. Tested order refresh tolerance with Loopring, and the expected behavior is followed.
