### ISSUE TITLE
[BUG] Error Sending Transaction- The limit order buy has expired.

### ISSUE THREAD

**Issue by nsshommo** [CoinAlpha/hummingbot#193]
**Describe the bug**
Error Sending Transaction. The limit order sell has expired according to order status API. The limit order buy has expired according to order status API.

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: Cross Exchange MM, Maker: RadarRelay, Taker: Binance
2. Start the bot using this command: Config, Start

**Screenshots**
![hummingbot_bug_3](https://user-images.githubusercontent.com/31445351/57394899-7cb37d80-71e8-11e9-986d-48e9431ecb8e.png)

**Release version**
Version: 0.5.0

**Attachments**
N/A

**Comment by mifeng** [comment]
@nsshommo Can you post your strategy config file and log file please?

**Comment by martinkou** [comment]
@chowryan please take a look
