### ISSUE TITLE
[BUG] Error Sending Transaction- The limit order sell has expired.

### ISSUE THREAD

**Issue by nsshommo** [CoinAlpha/hummingbot#194]
**Describe the bug**
Error Sending Transaction. The limit order sell has expired according to order status API.

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: Cross Exchange MM, Maker: RadarRelay, Taker: Binance
2. Start the bot using this command: Config, Start

**Screenshots**
![hummingbot_bug_4](https://user-images.githubusercontent.com/31445351/57395153-301c7200-71e9-11e9-8a91-a54192df4faf.png)

**Release version**
Version: 0.5.0

**Attachments**
N/A

**Comment by mifeng** [comment]
@nsshommo Can you post your strategy config file and log file please?

**Comment by martinkou** [comment]
@chowryan please take a look
