### ISSUE TITLE
[BUG] _optionals error reported after exiting the bot.

### ISSUE THREAD

**Issue by Nullably** [CoinAlpha/hummingbot#1946]
**Describe the bug**
A user reported the followings:
> When exiting the Docker version, I get the following error.  Does anyone else? AttributeError: 'NoneType' object has no attribute '_optionals' it also totally mangles the UI of the shell. I have to reset it for it to be usable again.
not a huge deal, but an annoyance... wondering if I'm the only one

From @mifeng 
> when i exit the client, i sometimes get this error (installed from source). has anyone else seen this/
![image](https://user-images.githubusercontent.com/37262506/85831389-d1d19a80-b7c0-11ea-925e-ba1d571d6c76.png)

After some investigation, this can happen when user accidentally hit space bar on the hummingbot input (without issue any command) then exit the app

**Steps To Reproduce**
Hit space bar on the hummingbot input (without issue any command) then exit the app

**Comment by PtrckM** [comment]
fix on the PR

- without patched
![2020-06-28-15-03-03](https://user-images.githubusercontent.com/54516858/85940805-505d4200-b951-11ea-92bb-1b72a0eab725.gif)

- with patched
![2020-06-28-15-03-50](https://user-images.githubusercontent.com/54516858/85940816-5eab5e00-b951-11ea-939d-95f36bf50d63.gif)
