### ISSUE TITLE
[BUG] instance crashes after updating hummingbot when config files layout amended

### ISSUE THREAD

**Issue by gabririgo** [CoinAlpha/hummingbot#1956]
**Describe the bug**
Any time the config files layout is changed after a hummingbot update, the app crashed and causes performance isses on aws.

**Steps To Reproduce**
update to a new hummingbot release when the hummingbot client layout params have been changed.

**Release version**
>=0.28.0.

**Optional: your discord username:**
gabrigo | RigoBlock #6195

**Comment by Clint-G13** [comment]
Thank you for reporting @gabririgo. Can you share with us a screenshot of the issue and your log files?

**Comment by gabririgo** [comment]
> Thank you for reporting @gabririgo. Can you share with us a screenshot of the issue and your log files?

actually I restarted the instance again and it works correctly. I believe it's some kind of memory leak when upgrading on ubuntu instances on aws.

**Comment by gabririgo** [comment]
[logs_conf_pure_mm_1.log](https://github.com/CoinAlpha/hummingbot/files/4840056/logs_conf_pure_mm_1.log)

**Comment by Clint-G13** [comment]
Thanks for uploading the logs. If this is a possible memory leak issue, our team has started to do some investigation since we have one user that reported an increase in memory usage over time.

**Comment by vic-en** [comment]
Closing issue because nothing unusual was discovered after observing memory usage with `objgraph`
