### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by supervik** [CoinAlpha/hummingbot#1957]
**Feature Suggestion**
It will be good if **order_optimization_depth** parameter has options for bid and ask sides separately. Now it sets for both ask and bid at the same time.

**Impact**
A market may have a larger volume in sell orders than in buy orders in the order book or vice versa and this option allows us to adjust the bot to market conditions. For example, it allows you to place buy orders at the best price but sell deeper and vice versa.

**Comment by PtrckM** [comment]
@supervik please see https://github.com/CoinAlpha/hummingbot/issues/1752 https://github.com/CoinAlpha/hummingbot/pull/1869 and https://docs.hummingbot.io/release-notes/0.28.1/#enhancements

**Comment by supervik** [comment]
Wow! Thank you!
