### ISSUE TITLE
[BUG] PermissionError: [Errno 1] Operation not permitted

### ISSUE THREAD

**Issue by BouweCeunen** [CoinAlpha/hummingbot#1964]
**Describe the bug**
Running headless with autostart of docker gives me the following error `PermissionError: [Errno 1] Operation not permitted`. Running with the option `-it` resolves this, but this is not what I want.

**Steps To Reproduce**
```
docker run \
  --network host \
  --mount "type=bind,source=$(pwd)/hummingbot_files/hummingbot_conf,destination=/conf/" \
  --mount "type=bind,source=$(pwd)/hummingbot_files/hummingbot_logs,destination=/logs/" \
  --mount "type=bind,source=$(pwd)/hummingbot_files/hummingbot_data,destination=/data/" \
  -e STRATEGY=pure_market_making -e CONFIG_FILE_NAME=conf_pure_mm_1.yml -e CONFIG_PASSWORD=... \
  coinalpha/hummingbot:latest
```

**Screenshots**
![image](https://user-images.githubusercontent.com/5576686/85952843-53196080-b96c-11ea-996b-92b273224b70.png)

**Release version**
latest

**Attachments**
/

**Comment by rennel-tabing** [comment]
Hi @BouweCeunen , if you want to run the instance without showing the hummingbot interface then use
```
docker run -itd \
  --network host \
  --mount "type=bind,source=$(pwd)/hummingbot_files/hummingbot_conf,destination=/conf/" \
  --mount "type=bind,source=$(pwd)/hummingbot_files/hummingbot_logs,destination=/logs/" \
  --mount "type=bind,source=$(pwd)/hummingbot_files/hummingbot_data,destination=/data/" \
  -e STRATEGY=pure_market_making -e CONFIG_FILE_NAME=conf_pure_mm_1.yml -e CONFIG_PASSWORD=... \
  coinalpha/hummingbot:latest
```

**Comment by BouweCeunen** [comment]
Hi @rennel-tabing, thanks for the switch reply. This indeed fixes my problem, I was having difficulties setting this up in Kubernetes, setting `tty: true` on my Kubernetes Deployment did the trick!
