### ISSUE TITLE
Docker image does not run on RaspBerryPi [BUG]

### ISSUE THREAD

**Issue by KoenBal** [CoinAlpha/hummingbot#1966]
When trying to start the docker container the following error occurs on a RaspBerry Pi running Ubuntu 20.

`Standard_init_linux.go:211: exec user process caused “exec format error”`

I assume this is due to the aarch64 architecture of the RaspBerry Pi?

**Comment by rennel-tabing** [comment]
Hi @KoenBal One of our community member shared what he did to make it work with RaspBerryPI . Please see if this helps
https://www.reddit.com/r/Hummingbot/comments/h83lhv/hummingbot_on_rpi4_howto/

**Comment by KoenBal** [comment]
I think an extra or new image should be created - https://www.docker.com/blog/multi-arch-images/
Not sure how to do this. But Ill check the comment first. thx

**Comment by KoenBal** [comment]
> Hi @KoenBal One of our community member shared what he did to make Hummingbot work with RaspBerryPI . Please see if this helps
> https://www.reddit.com/r/Hummingbot/comments/h83lhv/hummingbot_on_rpi4_howto/
> 
> So far, no users were able to make it work on docker though.

Ok, maybe not really a solution as he required a new OS instead of ubuntu. Ill check if I can built an arm image.

**Comment by KoenBal** [comment]
Using Docker Desktop on windows and mac it seems doable to built multi arch images. https://www.docker.com/blog/multi-arch-images/ Not sure how to get the edge version on Ubuntu though. I'm going for the easy way and launch an aws instance :).
