### ISSUE TITLE
[Feature] Improve `history` command for celo-arb

### ISSUE THREAD

**Issue by mifeng** [CoinAlpha/hummingbot#1969]
Currently, the history command for `celo-arb` is different from that of other strategies:
- Trades are not ordered by time
- No **Inventory** and **Assets** section
- No Performance Analysis section

Users expect the `history` command to provide the same info regardless of strategy. We should add this info to the Celo history command.

**Comment by Clint-G13** [comment]
We have a report from a user that Hummingbot sqlite db is not recording filled trades from CELO market. Check one db file from test bot and only see trades from Bittrex market. It would be good to include this for the history feature.
User's db file:
[hummingbot_trades.sqlite.gz](https://github.com/CoinAlpha/hummingbot/files/4906425/hummingbot_trades.sqlite.gz)
