### ISSUE TITLE
[BUG] Available balance not updating when paper trading on Huobi

### ISSUE THREAD

**Issue by alexchenzl** [CoinAlpha/hummingbot#1975]
**Describe the bug**
When running a paper trading bot, frozen balances in limit orders are always not taken into account.

**Steps To Reproduce**
Here are the steps to reproduce the issue :
1. Create a pure market making strategy 
2. Set paper_trade_enabled: true
3. Start the bot
4. Run status command, you will find total balances are always equal to available balances even when there are active orders. 

**Reason**
In paper_trade_market.pyx,  the dict __available_balances_ use upper case keys, while the property _on_hold_balances_ use lower case keys.

**Comment by Clint-G13** [comment]
Hi @alexchenzl  may I know what version are you using, and can you send us a screenshot. I just made some test on my end and I did not get the same behavior.
![balance](https://user-images.githubusercontent.com/57189990/86186520-e1a80080-bb6b-11ea-9143-8d8c11c812a2.PNG)

**Comment by alexchenzl** [comment]
I compiled it from the latest master branch, the version is v0.28.1 according to the git log. The commit id is cb9cc32e68942a6e361959a4dfbf01f0decd45bd 

I reproduced this issue from the scratch just now. Here is the screenshot.
![1593572531788](https://user-images.githubusercontent.com/2885415/86199032-99003f80-bb8b-11ea-8b11-68fba378fcb5.jpg)

**Comment by Clint-G13** [comment]
Thank you for the screenshot, I was able to replicate the issue and it appears that this happens with Huobi exchange only.

**Comment by Clint-G13** [comment]
Re-test issue and found out that there is a delay for Available balance on live trade using the windows binary installer and Source build (no issue on docker build). During the first order creation, the available balance will remain the same but if you do "Ctrl + S" or run status after, or after your first order refreshed, correct Available balance will display.
![zrx-eth1](https://user-images.githubusercontent.com/57189990/86702847-ea09ab00-c045-11ea-9617-294e763c6682.PNG)

However when paper_trade is enabled the issue does persist, Available balance never update even orders are refreshed.
![zrx-eth](https://user-images.githubusercontent.com/57189990/86704297-520cc100-c047-11ea-8998-f685d3ca3e72.PNG)

**Comment by RC-13** [comment]
Confirmed that delay when displaying available balance is no longer happening in version 0.31.0 for Huobi exchange
