### ISSUE TITLE
Ringfenced asset trades [Feature]

### ISSUE THREAD

**Issue by hrkuipers** [CoinAlpha/hummingbot#1984]
**Feature Suggestion**
I would like to ring fence my assets for a trading pair when trading from one portfolio. For example, I have a 10 BTC portfolio on Binance. I want to trade with 5 bots. Bot 1 runs BTC-ADA, bot 2 runs BTC-SOL, bot 3 runs ... I want each bot to trade with a max of 2 BCT to manage my inventory risk. 

**Impact**
Allows for better asset management and better management of inventory risk. Offers clearer delineation of assets than the inventory skew when trading with multiple bots of the same portfolio. Also, it allows me to quickly increase or reduce trade exposure to a pair straight from the bot if I desire. 

**Additional context**
Ringf fencing is only partly possible with inventory skew. If you want to set a inventory spread and orders on pair 1 get filled quicker than on pair 2 you can end up with a higher inventory risk on pair 1 than desired. 

Ring fencing can sometimes be done on the exchange side. For example on coinbase pro by putting assets in separate portfolios with different APIs. On binance is is possible with sub-accounts but this is already much more cumbersome.  Both are not as flexible as doing it directly from Hummingbot which allows you to quickly shift ring fenced assets from the same portfolio.

**Comment by PtrckM** [comment]
The feature `balance limit` has this functionality. You can set how much of a particular token the bot can use by running the command `balance limit [exchange] [asset] [amount]`. You can disable this feature by editing it in the global config file and set it to -1. While setting it to 0 will initially not place any order for a specific asset until a trade is executed to accumulate the said asset. For more info please visit our [documentation page](https://docs.hummingbot.io/features/balance-limit/#how-it-works).
