### ISSUE TITLE
[BUG] Failing to cancel order in Huobi

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#1993]
**Describe the bug**

Hummingbot continuously attempts to cancel a filled order which prevents new orders from getting created.

```
2020-07-02 04:31:44,254 - 1 - hummingbot.market.huobi.huobi_market - NETWORK - Failed to cancel order buy-htusdt-1593650489001393: {'error': {'status': 'error', 'err-code': 'order-orderstate-error', 'err-msg': 'Incorrect order state', 'data': None, 'order-state': 6}}
Traceback (most recent call last):
  File "hummingbot/market/huobi/huobi_market.pyx", line 777, in hummingbot.market.huobi.huobi_market.HuobiMarket.execute_cancel
    response = await self._api_request("post", path_url=path_url, is_auth_required=True)
  File "hummingbot/market/huobi/huobi_market.pyx", line 302, in _api_request
    async with response_coro as response:
  File "hummingbot/market/huobi/huobi_market.pyx", line 313, in hummingbot.market.huobi.huobi_market.HuobiMarket._api_request
    raise HuobiAPIError({"error": parsed_response})
hummingbot.market.huobi.huobi_market.HuobiAPIError: {'error': {'status': 'error', 'err-code': 'order-orderstate-error', 'err-msg': 'Incorrect order state', 'data': None, 'order-state': 6}}
```

<img width="947" alt="putty_60tI90Kr6x" src="https://user-images.githubusercontent.com/50150287/86606655-de34cf00-bfda-11ea-8fae-69e212046581.png">

This is the order that the bot was trying to cancel.

<img width="465" alt="r1dKJwJxby" src="https://user-images.githubusercontent.com/50150287/86606893-294ee200-bfdb-11ea-8e2b-c8515e4248ab.png">

<img width="960" alt="sUT9Wq4i2h" src="https://user-images.githubusercontent.com/50150287/86606900-2c49d280-bfdb-11ea-91bf-f04c97e6028b.png">

DB file shows the order's last status is created. Order ID buy-htusdt-1593650489001393 is in `Order` and `OrderStatus` but not in `TradeFill` table.

<img width="820" alt="dbeaver_DwlyGopqIC" src="https://user-images.githubusercontent.com/50150287/86607155-7f238a00-bfdb-11ea-8e5d-fea8272b1c06.png">

**Release version**

0.28.1
Installed via Docker on AWS server
Ubuntu 18.04 LTS

**Attachments**

[2020-07-01_huobi.log](https://github.com/CoinAlpha/hummingbot/files/4879648/2020-07-01_huobi.log)
[2020-07-02_huobi.log](https://github.com/CoinAlpha/hummingbot/files/4879650/2020-07-02_huobi.log)
[hummingbot_trades.zip](https://github.com/CoinAlpha/hummingbot/files/4879656/hummingbot_trades.zip)

**Comment by dennisocana** [comment]
This was resolved after exiting and restarting the Hummingbot instance.

<img width="947" alt="37JsfYZfUV" src="https://user-images.githubusercontent.com/50150287/86737940-3e715280-c067-11ea-9016-f2e7e42720dd.png">

**Comment by rxlxrxsx** [comment]
In version 0.30.0 getting the same errors and behavior but it doesn't get stuck in the "canceling order" message so proceeds to create new orders. It looks like it happens when the order has been filled and Hummingbot tries to cancel it before the filled order event message is generated.

![image](https://user-images.githubusercontent.com/64377055/90243746-04634f80-de62-11ea-84b5-086015ccc944.png)

[logs_huobi_ht-usdt.log](https://github.com/CoinAlpha/hummingbot/files/5074233/logs_huobi_ht-usdt.log)

**Comment by dennisocana** [comment]
Closing since we haven't run into this issue again starting from version 0.31
