### ISSUE TITLE
[BUG] Orders not created caused by broken balance update

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#2012]
**Describe the bug**

So far I only tested this while running on Liquid and Coinbase Pro but not happening on Binance. Some orders are not created during certain cycles because it thinks I don't have enough balance to place the order.

For example, in the first cycle all orders are created.

<img width="947" alt="putty_5hjUOIFtV0" src="https://user-images.githubusercontent.com/50150287/87036075-d7959a00-c21c-11ea-8cbd-872e53b789e2.png">

In the next order refresh, it says I have insufficient balance - which is incorrect.

<img width="947" alt="jKZR4eATte" src="https://user-images.githubusercontent.com/50150287/87036240-1592be00-c21d-11ea-8721-5906120f417a.png">

This is running on Liquid exchange, same bug is happening. First cycle all orders are created.

<img width="947" alt="putty_GWFgSnOsZf" src="https://user-images.githubusercontent.com/50150287/87036433-630f2b00-c21d-11ea-87e4-33dc80890442.png">

In the next order refresh, some orders are not created.

<img width="947" alt="CUPWgFrZQI" src="https://user-images.githubusercontent.com/50150287/87036528-83d78080-c21d-11ea-8fc7-ab976ec580c3.png">

**Steps To Reproduce**

1. Run a pure market making bot on Coinbase Pro or Liquid
2. Set order amount to just 60% or above of your total balance on each side
3. Wait for orders to refresh

**Release version**

dev-0.29.0

```
"branch": "development",
"commit": "9dfdc1d5dc18e09364e8868dded42d9f8421fb90",
"date": "2020-07-09T06:40:46Z",
"maintainer": "CoinAlpha, Inc. <dev@coinalpha.com>"
```

**Attachments**

[logs_cbp_link-eth.log](https://github.com/CoinAlpha/hummingbot/files/4896543/logs_cbp_link-eth.log)
[logs_liquid_qash-eth.log](https://github.com/CoinAlpha/hummingbot/files/4896545/logs_liquid_qash-eth.log)
[logs_binance_mft-eth.log](https://github.com/CoinAlpha/hummingbot/files/4896654/logs_binance_mft-eth.log)

**Comment by PtrckM** [comment]
- Got same behavior on **Bittrex**
![image](https://user-images.githubusercontent.com/54516858/87044592-555fa280-c229-11ea-98d6-811202fbc496.png)
![image](https://user-images.githubusercontent.com/54516858/87044604-5abced00-c229-11ea-87e4-4e581735d806.png)
![image](https://user-images.githubusercontent.com/54516858/87044611-5f81a100-c229-11ea-8917-0f514a3fe07c.png)
![image](https://user-images.githubusercontent.com/54516858/87044622-61e3fb00-c229-11ea-909c-d4ecee10ac1a.png)

- on **Kraken** as well.
![image](https://user-images.githubusercontent.com/54516858/87045300-51805000-c22a-11ea-8a93-c2a691ad2ed2.png)
