### ISSUE TITLE
[BUG] Docker build can't find celo-cli

### ISSUE THREAD

**Issue by mifeng** [CoinAlpha/hummingbot#2024]
**Describe the bug**
I updated to the latest `development` build. 

Afterwards, the `celo-arb` strategy can't run because the client can't find `celo-cli`. 

**Screenshots**
<img width="1255" alt="Screen Shot 2020-07-11 at 2 25 58 PM" src="https://user-images.githubusercontent.com/1795030/87234091-82739880-c382-11ea-9cfc-ac76a53b4dc7.png">

**Release version**
`dev-0.29.0`

**Comment by rennel-tabing** [comment]
tested  a celo-arb strategy and had the same error on dev commit `3e55e2f3b96a92fe9139dc474bca9a881031d465`
