### ISSUE TITLE
[Bug] Unclear on what to do next after following Install instruction document (on docker).

### ISSUE THREAD

**Issue by Nullably** [CoinAlpha/hummingbot#2030]
**Describe the bug**
The bot starts automatically once users follow install instruction, it is unclear on what to do if users want to keep the bot running but exit the terminal, (we had to stop the bot and start it all over again on a new `screen`).
A step to explain how to detach and attach to the docker instance would be nice to have ( Ctl p and Ctl q to detach).

![image](https://user-images.githubusercontent.com/37262506/87265162-9dfeb080-c4f4-11ea-8bee-2e584d701884.png)

**Comment by PtrckM** [comment]
PR created https://github.com/CoinAlpha/hummingbot/pull/2053
