### ISSUE TITLE
[BUG] Unable to connect to miner app with Brave browser + MetaMask

### ISSUE THREAD

**Issue by discosultan** [CoinAlpha/hummingbot#2031]
**Describe the bug**
Unable to connect to miner app with Brave browser + MetaMask. It's as if it never recognizes the MetaMask extension is installed.

![issue](https://i.imgur.com/O7QXGgl.png)

**Steps To Reproduce**
- Install Brave (Version 1.10.97 Chromium: 83.0.4103.116 (Official Build) (64-bit))
- Install MetaMask (7.7.9)
- Log in to MetaMask (optional but tried)
- Disable Brave shields for miners.hummingbot.io (optional but tried)
- Try connecting with MetaMask

**Additional Comments**
Maybe Brave is simply not supported or there's something extra I need to disable in the browser for the MetaMask integration to be picked up.

**Comment by rxlxrxsx** [comment]
Can you try the steps provided on this [link](https://docs.hummingbot.io/faq/troubleshooting/#how-to-connect-metamask-using-brave-browser)?

**Comment by discosultan** [comment]
@rxlxrxsx Thank you for a prompt reply! This works.

Apologies for not checking troubleshooting FAQ earlier but hopefully this issue can provide reference to people who try to search from GitHub issues instead.
