### ISSUE TITLE
[Feature] Maintain last_trade price in market connectors

### ISSUE THREAD

**Issue by Nullably** [CoinAlpha/hummingbot#2036]
**Feature Suggestion**
In anticipation for https://github.com/CoinAlpha/hummingbot/issues/1919, the market connector needs to maintain the last trade price of the market (either through REST or web socket API or both).

**Tasks**
- Add `last_trade_price` to `market_base`
- Add a new Enum `PriceType`, it contains `top_bid`, `top_ask`, `mid_price`, `last_trade` - this will also be useful for the new Price Param on PMM strategy.
- Modify `market_base.c_get_price` to take `PriceType` instead of `is_buy`
- Revisit all market connectors, there are a few ways to make sure `last_trade` price is most recent.
  - If the connector subscribes to trades web socket channel, keep updating `last_trade` for each recv
  - Find out which REST API `end_point` offers this information, usually it's `ticker` API and some kind of `market_summary`, update `last_trade_price` each response received.
  - If the exchange offers both web socket and REST API for this, make sure to implement both mechanism.
- Add unit testing to make sure `last_trade_price` gets updated. 
- Update connector developer document.

**Comment by mifeng** [comment]
LGTM
