### ISSUE TITLE
[BUG] Coinbase Pro - Trading pair not available using fiat

### ISSUE THREAD

**Issue by rennel-tabing** [CoinAlpha/hummingbot#2043]
**Describe the bug**
// A clear and concise description of what the bug is.
Using a `USD` pair on coinbase pro exchange will give an error of `Trading pair not available`
for example `BTC-USD` token pair

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: ...
[conf_pure_mm_coinbase-btc-usd.txt](https://github.com/CoinAlpha/hummingbot/files/4920645/conf_pure_mm_coinbase-btc-usd.txt)

2. Start the bot

Note: Using non-USD token pair will work.
...

**Screenshots**
// If applicable, add screenshots to help explain your problem.
The first order will be placed 
![image](https://user-images.githubusercontent.com/53868268/87463866-2312c400-c5e0-11ea-85b2-67efd95b7f82.png)

then the bot will error out and will no longer place any orders
![image](https://user-images.githubusercontent.com/53868268/87463890-2ad26880-c5e0-11ea-8b09-c4f719864c8b.png)

```
raceback (most recent call last):
  File "hummingbot/market/coinbase_pro/coinbase_pro_market.pyx", line 818, in hummingbot.market.coinbase_pro.coinbase_pro_market.CoinbaseProMarket.execute_sell
    order_result = await self.place_order(order_id, trading_pair, decimal_amount, False, order_type, decimal_price)
  File "hummingbot/market/coinbase_pro/coinbase_pro_market.pyx", line 730, in place_order
    order_result = await self._api_request("post", path_url=path_url, data=data)
  File "hummingbot/market/coinbase_pro/coinbase_pro_market.pyx", line 348, in _api_request
    async with client.request(http_method,
  File "hummingbot/market/coinbase_pro/coinbase_pro_market.pyx", line 352, in hummingbot.market.coinbase_pro.coinbase_pro_market.CoinbaseProMarket._api_request
    raise IOError(f"Error fetching data from {url}. HTTP status is {response.status}. {data}")
OSError: Error fetching data from https://api.pro.coinbase.com/orders. HTTP status is 400. {'message': 'Trading pair not available'}
2020-07-14 16:51:40,358 - 1 - hummingbot.market.coinbase_pro.coinbase_pro_market - WARNING - Failed to submit sell order to Coinbase Pro. Check API key and network connection.
2020-07-14 16:51:50,001 - 1 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (BTC-USD) Creating 1 ask orders at (Size, Price): ['0.005 BTC, 9318.6 USD']
2020-07-14 16:51:50,681 - 1 - hummingbot.market.coinbase_pro.coinbase_pro_market - NETWORK - Error submitting sell LIMIT order to Coinbase Pro for 0.00500000 BTC-USD 9318.60000000.

```

**Release version**

// Include your bot's version number (Can be found at the upper left corner of your CLI).
0.28.1
dev-0.29.0

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 
[coinbase-PMM logs.txt](https://github.com/CoinAlpha/hummingbot/files/4920686/coinbase-PMM.logs.txt)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Comment by dennisocana** [comment]
@rennel-tabing in which environment did you get this error? Also note that there are trading pair restrictions depending on your region.

![image](https://user-images.githubusercontent.com/50150287/87482647-70387980-c664-11ea-8bbc-a2dbc397ebf7.png)

**Comment by blondie63** [comment]
Is this issue fixed with v0.29 ?
I had tried the BTC / EUR pair with version 0.28.1 and it was giving problems

**Comment by dennisocana** [comment]
@blondie63 can you confirm if you can place orders manually on the exchange for that pair? And are you running Hummingbot locally on your computer?

**Comment by blondie63** [comment]
> @blondie63 can you confirm if you can place orders manually on the exchange for that pair? And are you running Hummingbot locally on your computer?

Yes i can buy & sell manually with my Coinbase pro account, tested now!
My Hummingbot running on a upcloud.com VPS

**Comment by dennisocana** [comment]
@blondie63 can you try running Hummingbot locally on your computer using the binary installer from https://hummingbot.io/download/ and see if that would allow you to place an order since it will use your local IP. This doesn't look like an issue with HB rather, a limitation with Coinbase Pro's trading rules.

https://help.coinbase.com/en/pro/trading-and-funding/cryptocurrency-trading-pairs/locations-and-trading-pairs

**Comment by dennisocana** [comment]
Closing this since this is not an issue with the client.
