### ISSUE TITLE
[BUG] high cpu usage after upgrade to v0.29.0 (public beta) using a DEX

### ISSUE THREAD

**Issue by gabririgo** [CoinAlpha/hummingbot#2049]
**Describe the bug**
After upgrading to 0.29.0 CPU usage for 1 hummingbot instance run inside a docker container goes from 2% to 50%. This happens both when upgrading old configuration files and with a fresh configuration of a new bot.

**Steps To Reproduce**
upgrade hummingbot with ./update.sh script, run the bot and you will soon see the performance issue.
The process that gives problems seems to be python3.

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: wethdai, 1bps spread, 0.4WETH, ping-pong true, ethereum https and wss
2. Start the bot using this command: any
3. check CPU usage with top -i command
4. after a few minutes you'll be able to see the higher CPU usage in aws if you're using it

...

**Screenshots**
![Screenshot from 2020-07-15 09-38-19](https://user-images.githubusercontent.com/12066256/87517720-8e5fa300-c67f-11ea-95b6-64a258a3f09d.png)
![Screenshot from 2020-07-15 09-42-41](https://user-images.githubusercontent.com/12066256/87517745-9586b100-c67f-11ea-87b3-c1df2215a94b.png)

**Release version**
0.29.0

**Attachments**
[logs_conf_pure_mm_1.log](https://github.com/CoinAlpha/hummingbot/files/4924669/logs_conf_pure_mm_1.log)
[logs_conf_pure_mm_1.log](https://github.com/CoinAlpha/hummingbot/files/4924690/logs_conf_pure_mm_1.log)
logs_hummingbot.log file is empty as this is a fresh bot and does not crash. Same happens also when upgrading an existing bot with different config file.

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**
gabrigo | RigoBlock

**Comment by mifeng** [comment]
@gabririgo thanks for raising this - a couple of questions that may help us figure out what happened: 
* did you try this on both DEX and CEX or only on DEX?
* was the CPU level stable at 50% or does it fluctuate as in the image above?

**Comment by gabririgo** [comment]
> @gabririgo thanks for raising this - a couple of questions that may help us figure out what happened:
> 
> * did you try this on both DEX and CEX or only on DEX?
> * was the CPU level stable at 50% or does it fluctuate as in the image above?

- DEX only so far
- CPU level stable. The fluctuation in the image is due to me stopping the instance and then restarting it. The following was taken right now:
![Screenshot from 2020-07-17 06-40-20](https://user-images.githubusercontent.com/12066256/87749233-6a739d00-c7f8-11ea-9614-dca9bae243be.png)

**Comment by dennisocana** [comment]
Thanks for reporting this. I'm running a bot on AWS t2.micro with single order per side and 5 minutes order refresh time on DEX.

While trying to replicate this behavior, I found out that in version 0.28.1 the actual physical memory consumed was at around 200 MB and the CPU usage ranges somewhere at 2%

<img width="674" alt="putty_NwlHGCHqRR" src="https://user-images.githubusercontent.com/50150287/87757078-9d3f8480-c83c-11ea-85b7-458fd432cd14.png">

After updating to 0.29.0 the CPU usage spiked to 100% while running the strategy. But notice the resident size for the Hummingbot process is only at 167 MB and there doesn't seem to be a performance issue while using the instance nor crashing.

<img width="674" alt="putty_yT0JY4yMBN" src="https://user-images.githubusercontent.com/50150287/87757582-77ff4600-c83d-11ea-8d51-8166f447c93f.png">

<img width="608" alt="rGYHZPg8g2" src="https://user-images.githubusercontent.com/50150287/87758086-5bafd900-c83e-11ea-983e-822e1971b6e1.png">

I will send some more updates here of what I'll find out.

**Comment by dennisocana** [comment]
Just confirmed that this only happens when running on DEX and not on CEX. I also started to get performance issues in the other bot on DEX and the machine will most likely crash if I leave it running overnight.
