### ISSUE TITLE
[BUG] Strategy not running on DEX market

### ISSUE THREAD

**Issue by RC-13** [CoinAlpha/hummingbot#2050]
**Describe the bug**
When running a pure market making strategy using Radar relay or Bamboo relay, the strategy never starts and doesn't throw any error unless you run the status command. This issue happens when using binary version and Source build.
**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):

1. Create a pure market making strategy and set Radar relay or Bamboo relay your exchange.
1. Start bot
...

**Screenshots**
Windows Binary: Waited for 40 minutes and still no progress
![radar3](https://user-images.githubusercontent.com/57189990/87523197-347bcf00-c6b9-11ea-9f69-308539144b79.PNG)
Source Build: 20 minutes have lapsed but the strategy hasn't started
![radar4](https://user-images.githubusercontent.com/57189990/87523200-36459280-c6b9-11ea-81e0-28bf5325d693.PNG)

Running status command causes unhandled error since strategy doesn't start.
![radar0](https://user-images.githubusercontent.com/57189990/87523457-891f4a00-c6b9-11ea-8cee-e85875ee79ee.PNG)

**Release version**
Windows Binary: 0.29.0
Source Build: 0.29.0 and 0.30.0

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

_WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!_

**Optional: your discord username:**

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1pd1dqw) by [Unito](https://www.unito.io)

**Comment by PtrckM** [comment]
similar issue on https://github.com/CoinAlpha/hummingbot/issues/1505 different behavior

**Comment by PtrckM** [comment]
- ARB
![image](https://user-images.githubusercontent.com/54516858/89099914-644f0480-d425-11ea-9d47-be1434145e01.png)

```
2020-07-30 11:24:28,239 - 1 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 'hummingbot.market.bamboo_relay.bamboo_relay_market.BambooRelayMarket' object has no attribute '_withdraw_rules'
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/hummingbot/hummingbot/client/command/start_command.py", line 84, in start_check
    await self.start_market_making(self.strategy_name)
  File "/home/hummingbot/hummingbot/client/command/start_command.py", line 90, in start_market_making
    start_strategy(self)
  File "/home/hummingbot/hummingbot/strategy/arbitrage/start.py", line 34, in start
    self._initialize_markets(market_names)
  File "/home/hummingbot/hummingbot/client/hummingbot_application.py", line 275, in _initialize_markets
    market = BambooRelayMarket(
  File "hummingbot/market/bamboo_relay/bamboo_relay_market.pyx", line 187, in hummingbot.market.bamboo_relay.bamboo_relay_market.BambooRelayMarket.__init__
    self._withdraw_rules = {}
AttributeError: 'hummingbot.market.bamboo_relay.bamboo_relay_market.BambooRelayMarket' object has no attribute '_withdraw_rules'
2020-07-30 11:27:21,656 - 1 - hummingbot.client.hummingbot_application - INFO - stop command initiated.
```

- XEMM
![image](https://user-images.githubusercontent.com/54516858/89099931-88124a80-d425-11ea-83d1-0653ce3226a3.png)

- PMM
![image](https://user-images.githubusercontent.com/54516858/89099939-96f8fd00-d425-11ea-873c-65e28b3e23d7.png)
- @Clint-G13  tried removing  `self._withdraw_rules = {} from bamboo_relay_market.pyx` just like what was done on PR https://github.com/CoinAlpha/hummingbot/pull/2134 however, got stuck with current issue.

**Comment by dennisocana** [comment]
@PtrckM that last comment should be treated as a separate issue and the error is more related to https://github.com/CoinAlpha/hummingbot/issues/2121 than the error here. Could you create a new issue for that error in Bamboo Relay?

**Comment by dennisocana** [comment]
This now happens on docker as well in version 0.31.0

![image](https://user-images.githubusercontent.com/50150287/93009092-1cd4a000-f5af-11ea-9d61-aa7ee0a192da.png)

**Comment by RC-13** [comment]
Closing ticket, affected connectors has been deprecated.
