### ISSUE TITLE
New Exchange Connector for STEX

### ISSUE THREAD

**Issue by adel-ecosystem** [CoinAlpha/hummingbot#2054]
## Exchange Details ✏️

- **Name of exchange**: STEX
- **Exchange URL**: https://www.stex.com/
- **Link to API docs**: https://apidocs.stex.com/
- **Type of exchange**: Centralized 
- **Requester details**: Are you affiliated with the exchange? no 
  - If yes, what is your role?

## Rationale / impact ✏️
(Describe your rationale for building this exchange connector, impact for hummingbot users/community)
STEX exchange offers a variety of altcoins (400+) that are undervalued and not on top exchanges. I represent one of such projects and we need market making for our token. There are plenty of other projects that need it too. They do introduce to market-making partners, but since small projects can't afford to pay for such prices I see the best option with Humingbot
## Additional information ✏️
(Provide any other useful information that may be helpful to know about this exchange)
They are a regulated exchange in Estonia and have over 400 altcoins listed. You can find more about them here - https://www.stex.com/about-us
---

⚠️ ***Note: do not modify below here***

## Developer notes

This feature request entails building a new exchange connector to allow Hummingbot to connect to an exchange that is currently not supported.

### Resources
- [Exchange connector developer guide](https://docs.hummingbot.io/developers/connectors/)
- [Discord forum](https://discord.hummingbot.io)

### Deliverables
1. A complete set of exchange connector files as listed [above](#developer-notes-resources).
2. Unit tests (see [existing unit tests](https://github.com/CoinAlpha/hummingbot/tree/master/test/integration)):
  1. Exchange market test ([example](https://github.com/CoinAlpha/hummingbot/blob/master/test/integration/test_binance_market.py))
  2. Order book tracker ([example](https://github.com/CoinAlpha/hummingbot/blob/master/test/integration/test_binance_order_book_tracker.py))
  3. User stream tracker ([example](https://github.com/CoinAlpha/hummingbot/blob/master/test/integration/test_binance_user_stream_tracker.py))
3. Documentation:
  1. Code commenting (particularly for any code that is materially different from the templates/examples)
  2. Any specific instructions for the use of that exchange connector ([example](https://docs.hummingbot.io/connectors/binance/))

### Required skills
- Python
- Previous Cython experience is a plus (optional)

**Comment by phbrgnomo** [comment]
Duplicated #2634.
