### ISSUE TITLE
Bamboo Relay - Incorrect balance update

### ISSUE THREAD

**Issue by gabririgo** [CoinAlpha/hummingbot#2055]
**Describe the bug**
hummingbot creates an order for the full balance, displays a wrong balance

**Steps To Reproduce**
This is probably due to infura endpoint return value, not sure how to reproduce.

Here are the steps to reproduce the issue (see attachments in the section below):

1. bot configured with multiple orders (3 levels)
1. inventory skew enabled with 50% target
...

**Screenshots**
![Screenshot from 2020-07-15 14-10-33](https://user-images.githubusercontent.com/12066256/87543599-4eabb200-c6a5-11ea-87a7-ffa1a5a07c4c.png)
![Screenshot from 2020-07-15 14-10-18](https://user-images.githubusercontent.com/12066256/87543611-5408fc80-c6a5-11ea-842e-6eceee9e60ae.png)

**Release version**
0.29.0

_WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!_

**Optional: your discord username:**
gabrigo | RigoBlock

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1pd1dw0) by [Unito](https://www.unito.io)

**Comment by PtrckM** [comment]
- Able to replicate this using docker-linux build. First `status` shows full balance after order refresh shows correct balance (minus the orders)

![image](https://user-images.githubusercontent.com/54516858/87549419-5ccaf400-c6e0-11ea-9652-5a539b249365.png)

![image](https://user-images.githubusercontent.com/54516858/87549674-b29f9c00-c6e0-11ea-85ee-dcb21c9f6edb.png)

![image](https://user-images.githubusercontent.com/54516858/87549580-96036400-c6e0-11ea-8945-230d5ca21ced.png)

- logs and config
[logs_pmm-br_weth-usdc.log](https://github.com/CoinAlpha/hummingbot/files/4925446/logs_pmm-br_weth-usdc.log)
[pmm-br_weth-usdc.txt](https://github.com/CoinAlpha/hummingbot/files/4925448/pmm-br_weth-usdc.txt)

**Comment by gabririgo** [comment]
@PtrckM imo you cannot just let the bot running for debugging, but you need the bot's order to get filled. I think it's a problem with trade logs. The way you can get that is either by taking your own orders, or by placing bigger orders (i.e. 10eth) so that the market will take them.

**Comment by gabririgo** [comment]
by stopping and restarting the bot, balances are then correct. However, the inventory skew adjustment is wrong, you can see from the screenshot where inventory % is in line with target % but adjusted values differ by a lot from the original values. Please let me know if I should open a separate issue for this one @mifeng 
![Screenshot from 2020-07-17 18-12-17](https://user-images.githubusercontent.com/12066256/87808080-717ec780-c859-11ea-9124-5629302ba49a.png)

**Comment by RC-13** [comment]
Closing ticket, connector has been deprecated.
