### ISSUE TITLE
[BUG] Net Delta and Trade Delta does not match in history

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#2060]
**Describe the bug**

Net Delta and Trade Delta in the `history` output does not match in most connectors. I did not make any deposits or withdrawals while the bot is in session. This does not happen on Binance and Huobi bots I'm running.

## Eterbase

<img width="465" alt="eterbase_eth-usdt" src="https://user-images.githubusercontent.com/50150287/87650130-c3edb480-c783-11ea-85e2-ec7c18c6ad4c.png">

## Binance

<img width="445" alt="binance_eth-usdt" src="https://user-images.githubusercontent.com/50150287/87650146-c8b26880-c783-11ea-9173-a07ccf4f1c52.png">

I did a single trade in a new session in Eterbase to check again.

<img width="447" alt="putty_amXeUX90xL" src="https://user-images.githubusercontent.com/50150287/87650331-1202b800-c784-11ea-8cdf-0baf0e1b8509.png">

<img width="800" alt="v0VmyhPSra" src="https://user-images.githubusercontent.com/50150287/87650346-16c76c00-c784-11ea-801d-c2b85080583f.png">

**Release version**

0.29.0

**Attachments**

[logs_eterbase_eth-usdt.log](https://github.com/CoinAlpha/hummingbot/files/4930362/logs_eterbase_eth-usdt.log)
[2020-07-15_eterbase_eth-usdt.log](https://github.com/CoinAlpha/hummingbot/files/4930365/2020-07-15_eterbase_eth-usdt.log)
[hummingbot_trades.zip](https://github.com/CoinAlpha/hummingbot/files/4930369/hummingbot_trades.zip)

**Comment by vic-en** [comment]
@dennisocana 
I think the outputs(approximately) are correct.
The Net Delta and Trade Delta wouldn't always be thesame in majority of cases.
Note that the Trade Delta factors in fees. In the case of Eterbase, when the 0.35% fees is considered, you'll see the output is correct.

**Comment by vic-en** [comment]
In the case of the Binance showing a matching result. I'm guessing the fee was overridden to zero(0). 

<img width="463" alt="eter" src="https://user-images.githubusercontent.com/31972210/91593517-3c858a80-e958-11ea-9797-e68adb0ce1ae.PNG">
I ran several times on Eterbase and the result are accurate.

**Comment by dennisocana** [comment]
@vic-en the config fee override was at default, no changes made to both Binance and Eterbase.

**Comment by Nullably** [comment]
This should be considered as part of #2129
