### ISSUE TITLE
[BUG] PMM | Removing transaction cost will still add transaction fees on history

### ISSUE THREAD

**Issue by rennel-tabing** [CoinAlpha/hummingbot#2069]
**Describe the bug**
// A clear and concise description of what the bug is.
Disabling the transaction fees using `config add_transaction_costs no` will still results to trades that uses transaction fees as if it was not disabled.

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:
1. Create a Pure Market making strategy
2. Disable the transaction costs parameter using `config add_transaction_costs no`
3. Wait for your orders to be filled then use the history command.
  You will notice that the `fee_percent` column still shows a transaction cost of 0.001
...

**Screenshots**
// If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/53868268/87714546-e7abfd00-c779-11ea-977e-9178b587168d.png)

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).
0.29.0

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by dennisocana** [comment]
1. `add_transaction_costs` only affects the order prices created by taking the fees into the calculation when enabled during pure market making - see [How It Works](https://docs.hummingbot.io/strategies/advanced-mm/add-transaction-costs/#how-it-works) i.e. 
2. `fee_percent` value is default, unless specified in `conf_fee_overrides.yml` - see [Fee Overrides](https://docs.hummingbot.io/advanced/fee-overrides/)
3. Those two mentioned above don't affect each other in any way as they are are two separate things
4. In development from PR https://github.com/CoinAlpha/hummingbot/pull/2039, `fee_percent` will no longer be shown in the history output but it still takes fees into calculation
