### ISSUE TITLE
[BUG]  Errors after updating the conf_fee_overrides.yml

### ISSUE THREAD

**Issue by rennel-tabing** [CoinAlpha/hummingbot#2075]
**Describe the bug**
// A clear and concise description of what the bug is.
Updating the conf_fee_overrides.yml value for an exchange will cause an error preventing a strategy to place orders.

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
1. Close/exit any running hummingbot instance
2. edit `conf_fee_overrides.yml` under `hummingbot_conf` folder
3. Set a value with the folowing as an example:
binance_maker_fee: 0.05
binance_taker_fee:  0.05
4. Save the changes and start your hummingbot
5. Right after you enter the hummingbot password, an error will occur on the screen
![image](https://user-images.githubusercontent.com/53868268/87882121-fd186580-c9cb-11ea-8c96-4cd7e10ed0b9.png)
the bot will still load and you will be able to import the strategy
6. Import the strategy using a pair that uses Binance  as an exchange on this example
7. Run the strategy using the `start` command. You will notice that the bot will not place any orders
![image](https://user-images.githubusercontent.com/53868268/87882213-9e072080-c9cc-11ea-80ab-f12f930a4b11.png)

...

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).
0.29.0
Environment
docker
Ubuntu 18.04

**Attachments**
logs from the `logs_hummingbot.log` file
```
020-07-19 18:12:33,290 - 1 - root - ERROR - Error loading configs. Your config file may be corrupt. <lambda>() missing 1 required positional argument: 'x'
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/client/config/config_helpers.py", line 256, in load_yml_into_cm
    err_msg = cvar.validate(str(cvar.value))
  File "/home/hummingbot/hummingbot/client/config/config_var.py", line 53, in validate
    if self.required and (value is None or value == ""):
  File "/home/hummingbot/hummingbot/client/config/config_var.py", line 48, in required
    return self._required_if()
TypeError: <lambda>() missing 1 required positional argument: 'x'

```

strategy log file
```
2020-07-19 18:12:40,618 - 1 - hummingbot.client.hummingbot_application - ERROR - Unknown error during initialization.
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/strategy/pure_market_making/start.py", line 54, in start
    self._initialize_wallet(token_trading_pairs=list(set(maker_assets)))
TypeError: 'NoneType' object is not iterable
2020-07-19 18:12:40,619 - 1 - hummingbot.client.hummingbot_application - INFO - start command initiated.

```

**Optional: your discord username:*JackShiloh*

**Comment by rennel-tabing** [comment]
I also tried using a format of 
binance_maker_fee:0.05
binance_taker_fee:0.05
(without a space after the ":" symbol ) and I am still getting errors on the logs.

**Comment by sigit2306** [comment]
I tried to replicate the issue on Windows binary, from source, docker build:
Similar result:
- logs from the logs_hummingbot.log file are the same.

Different Behaviour:
- The bot still can place orders.
![001](https://user-images.githubusercontent.com/12313129/87915501-77b0b600-ca9c-11ea-81c7-ad50b6e635cc.png)


Others: 
- Checking up the `conf_fee_overrides.yml` and saw that the taker_fee was gone.
![002](https://user-images.githubusercontent.com/12313129/87915535-8008f100-ca9c-11ea-876e-83dbca13680f.png)
![003](https://user-images.githubusercontent.com/12313129/87915548-84cda500-ca9c-11ea-922d-64bc18e38ec7.png)

- The `conf_fee_overrides.yml` didn't change the `fee_percentage` on live trade.
![004](https://user-images.githubusercontent.com/12313129/87916596-db87ae80-ca9d-11ea-8d8e-8e7162d2b58e.png)

**Comment by rennel-tabing** [comment]
I recreated by docker instance and the bot is now able to place trades. 
I had the exact behavior as what @sigit2306 had mentioned wherein the taker fee suddenly disappeared from the configuration. Can we close this issue and just use the issue https://github.com/CoinAlpha/hummingbot/issues/2078 moving forward?
