### ISSUE TITLE
[BUG] Eterbase always showing on auto-complete when typing -e in client

### ISSUE THREAD

**Issue by rxlxrxsx** [CoinAlpha/hummingbot#2079]
**Describe the bug**
Eterbase always showing on auto-complete when typing -e in client.

**Steps To Reproduce**
Create a new strategy and when asked for your file name typing "-e" shows Eterbase on the auto-complete. This is exclusive to Eterbase based on my tests on other exchanges.

**Screenshots**
![image](https://user-images.githubusercontent.com/64377055/87933687-4fd34980-cac0-11ea-8a57-2ee2dd0a4973.png)
![image](https://user-images.githubusercontent.com/64377055/87934228-3bdc1780-cac1-11ea-8dd6-6b819d61c818.png)

**Release version**
version-0.29.0

**Attachments**

_WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!_

**Optional: your discord username:**

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1pd1e5z) by [Unito](https://www.unito.io)

**Comment by RC-13** [comment]
Closing ticket, connector has been deprecated.
