### ISSUE TITLE
[BUG] Incorrect account balance for DAI at RadarRelay

### ISSUE THREAD

**Issue by Steve1943** [CoinAlpha/hummingbot#208]
**Describe the bug**
hummingbot incorrectly reports DAI balance as zero and warns that balance is insufficient to trade

**Steps To Reproduce**
Launch hummingbot to arbitrage WETH-DAI and ETHTUSD between Radar Relay and Binance respectively.
...

**Screenshots**
[Dai_balance_zero.txt](https://github.com/CoinAlpha/hummingbot/files/3166394/Dai_balance_zero.txt)

![Firefox_Screenshot_2019-05-10T11-41-44 750Z](https://user-images.githubusercontent.com/2613649/57525016-df606280-7329-11e9-8384-be30156e69c0.jpg)

**Release version**
dev-0.6.0

**Comment by martinkou** [comment]
@chowryan any ideas?

**Comment by Steve1943** [comment]
I have replicated same problem for DDEX so it is not exchange specific
[console_snapshot.txt](https://github.com/CoinAlpha/hummingbot/files/3207887/console_snapshot.txt)

**Comment by mifeng** [comment]
@Steve1943 I believe this bug originated from the network not being connected when the bot tried to fetch the wallet balance. We made a big networking fix in 0.7.0 - can you pls check again? Thx

**Comment by Steve1943** [comment]
I ran a range of (arbitrage) tests over several coins on both DDEX and Radar_Relay as makers and with Binance as taker - without replicating this error - so I agree that the networking fixes seem to have done the trick.
