### ISSUE TITLE
[BUG] Filled order fees are not recorded correctly

### ISSUE THREAD

**Issue by Nullably** [CoinAlpha/hummingbot#2084]
**Describe the bug**

Fees for orders that are filled are not recorded correctly for many connectors, instead of taking fees reported from exchange's API, the connectors call `c_get_fee` (which estimates fee). This results in incorrect fees stored on trades table (sqlite) and incorrect performance reported on `history` command.

This mistake was partly due to Binance connector had this bug which other connectors copied the code from. The bug was fixed on 29 December 2020 on Binance connector so connectors created after the date should not get affected.

Connectors which broadcast fee incorrectly on `OrderFilledEvent`:

- [ ] ~Kucoin~
- [x] Binance Perpetual Derivative
- [x] Bifinex
- [x] Coinbase Pro
- [x] Bittrex
- [ ] ~OkEx~
- [x] Huobi
- [ ] ~Beaxy~
- [x] FTX
- [ ] ~Blocktane~
- [ ] ~Coinzoom~
- [ ] ~DigiFinex~
- [x] Gate.io
- [ ] Liquid

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1pd1e7e) by [Unito](https://www.unito.io)

**Comment by aarmoa** [comment]
- Kucoin does not include fee information in the websocket event sent when orders are filled. There is no alternative but to estimate the fee based on the configured fee rate (see https://docs.kucoin.com/#private-order-change-events)

**Comment by aarmoa** [comment]
OkEx does not provide trades (order fills) events through the websocket. The only alternative for this connector is to estimate fees (see https://www.okex.com/docs/en/#spot_ws-channel)

**Comment by aarmoa** [comment]
Cooper from Beaxy exchange confirmed that they don't have the possibility for the time being to include fees information in the order update events.

**Comment by aarmoa** [comment]
Blocktane does not provide fee information in the trade websocket channel. They don't include fee information in the websocket order update channel either. They do have a trades REST api that could be used to retrieve fees, but that would require modifying the current client logic to make this call every time a trade is completed, cancelled or failed.
For the time being we will have to keep estimating fees.

**Comment by aarmoa** [comment]
Digifinex does not provide fees information in the trades updates websocket endpoint (https://github.com/DigiFinex/api/blob/master/Websocket_API_en.md). It does not provide that information through the REST API interface, making it impossible to stop estimating fees for this exchange.
