### ISSUE TITLE
[BUG] Error connecting to kraken API using v0.29.0

### ISSUE THREAD

**Issue by javiermatos** [CoinAlpha/hummingbot#2085]
**Describe the bug**
I have created a kraken api key following the instructions shown in documentation page https://docs.hummingbot.io/connectors/kraken/ enabling same key permissions with different nonce window from 10 to 50. It does not matter which api key configuration I set (even all permissions) that I will have problems connecting it to hummingbot.

Once I run the connect kraken command I fill the api and secret keys. Once everything is there I receive the "kraken_market - Error received from https://api.kraken.com/0/private/Balance. Response is {'error': []}." message in log.

If I remove all the key permissions I get a different error "kraken_market - Error received from https://api.kraken.com/0/private/Balance. Response is {'error': ['EGeneral:Permission denied']}."

When I run the connect command after adding the key it shows that key was added but keys are not confirmed.

**Steps To Reproduce**
Steps to reproduce are just to install a new and empty docker instance running version-0.29.0 and running the connect kraken command while using a key that is configured just as shown in your documentation.

**Comment by Clint-G13** [comment]
Hi @javiermatos Just to verify, do you have funds or any balance on Kraken? Typically that error you receive means that your account is currently not verified and you need to have a fund on Kraken exchange for your account to be confirmed.
Here's a reference: https://docs.hummingbot.io/faq/troubleshooting/#kraken-0-balance-error

**Comment by javiermatos** [comment]
Hi @Clint-G13 Thank you for that information. I have a verified kraken account but I do not have funds. In documentation I read "not verified and no current funds" -> "not verified and not funds" -> "false and true" -> "false"... So in theory I should not have the issue... am I right? Hehehe. I think the documentation wants to say "not verified OR not current funds".

**Comment by Clint-G13** [comment]
@javiermatos Thanks for bringing this up, we need to update that statement on our docs. You will still get the error since you don't have a balance on the Kraken exchange.

**Comment by dennisocana** [comment]
Troubleshooting docs updated here
https://github.com/CoinAlpha/hummingbot/pull/2092/files#diff-e05527aabadbf65b0c6e323dd32b9b4eR298

![image](https://user-images.githubusercontent.com/50150287/88469970-89291080-cf29-11ea-8975-6f9dc34346ba.png)
