### ISSUE TITLE
[BUG] Kraken incorrect minimum order size suggestion

### ISSUE THREAD

**Issue by somethingaboutnothing** [CoinAlpha/hummingbot#2094]
**Describe the bug**
I followed the advice on screen re: minimum order size but was incorrect as per what was suggested on [Kraken's website](https://support.kraken.com/hc/en-us/articles/205893708-Minimum-order-size-volume-for-trading)
![image](https://user-images.githubusercontent.com/67629188/88190412-263a2f80-cc32-11ea-853f-2b8756953753.png)
![image](https://user-images.githubusercontent.com/67629188/88190380-1f132180-cc32-11ea-87f5-a16257f75e40.png)

**Steps To Reproduce**
Create a bot with ICX-USD on Kraken

**Release version**
Version 0.29.0

**Optional: your discord username:**
5sdfg34

**Comment by sigit2306** [comment]
By default, we configured the minimum order amount of around $11 which you're seeing in the order_amount prompt. 
The minimum order size varies per exchange so we estimated the amount for all pairs to be around $11 hence the default values in the global config file. So it's not exactly the same as the exchange's trade rule.

To override this, edit `conf_global.yml` in the conf folder and set USD to 0 under min_quote_order_amount.
