### ISSUE TITLE
Installation issue on Mac

### ISSUE THREAD

**Issue by polymorpher** [CoinAlpha/hummingbot#21]
Following https://docs.hummingbot.io/installation/source/
Without anaconda installed:

```
Aarons-iMac:hummingbot polymorpher$ ./install 
usage: dirname path
env: list: No such file or directory
env: create: No such file or directory
```

**Comment by wpank** [comment]
You'll need to install anaconda unfortunately. 

That error is the result of the `./install` running 
```conda env list | egrep -qe "^hummingbot"```
and then 
```conda env create -f setup/environment.yml```

Without anaconda installed, anything that calls `conda` will result in 
```No such file or directory```

The install script doesn't provide the appropriate error message without anaconda being installed at the moment (also got the same error without anaconda on Ubuntu 18.10).

[You can install anaconda from here](https://www.anaconda.com/distribution/)
