### ISSUE TITLE
[BUG] xemm profitability calculation error

### ISSUE THREAD

**Issue by carlolm** [CoinAlpha/hummingbot#210]
**Describe the bug**

Bid side of xemm strategy on WETH-DAI / ETH-USDT is reported at -100%, which is not right.

**Steps To Reproduce**

xemm | binance/ddex | weth-dai | eth-usdt

**Screenshots**
![image](https://user-images.githubusercontent.com/12274903/57535714-57a04580-7375-11e9-8d21-a97d6c8759d8.png)

**Release version**

dev/0.6.0 last commit: 0d23b5f May 10, 2019

**Attachments**

**Comment by mifeng** [comment]
@carlolm can you post log file and config file? It's not clear from `status` what happened to trigger this issue.

**Comment by martinkou** [comment]
Fixed with #212
