### ISSUE TITLE
[Feature] Use different strategy specific sqlite db files

### ISSUE THREAD

**Issue by carlolm** [CoinAlpha/hummingbot#2106]
**Feature Suggestion**

Create different sqlite files for each strategy.
For example, if I create a new configuration `conf-BASEQUOTE.yml`, then create a corresponding `conf-BASEQUOTE.sqlite` database file.

**Impact**

This will avoid errors in `history` when switching between strategy files from the same instance.
For example if I have a configuration to trade BASE1 and QUOTE1, if I create a new strategy to trade BASE2 and QUOTE2, the database and trade history will show trades from both BASE1/QUOTE1 and BASE2/QUOTE2.

This will also enable running multiple instances (from source) more easily, since a user can simply launch `bin/hummingbot.py` from multiple terminal windows or by using tmux.

Currently, running multiple instances from the same installation results in database errors, interfering with functions such as `history` and `kill switch`.

**Additional context**

Currently, hummingbot saves trades to a single `hummingbot_trades.sqlite` file.
This results in errors in `history` if you switch strategies between different pairs or if you run multiple instances of an instance installed from source.  The only away to avoid this and run multiple instances from source is by creating new separate folders and installations for each instance, so that they do not write to the same db.

Creating new db files for each configured strategy file seems like a simple fix to avoid errors due to changing between strategies as well as enabling an easier and more efficient way to run multiple instances (from source).

**Comment by Nullably** [comment]
A feedback from user
![image](https://user-images.githubusercontent.com/37262506/92138458-f725f900-ee40-11ea-9934-9eee4c664029.png)

I reopen this issue, we should actually implement solution as originally requested.
