### ISSUE TITLE
[BUG] Filled orders are not showing in history command on Kucoin.

### ISSUE THREAD

**Issue by rxlxrxsx** [CoinAlpha/hummingbot#2111]
**Describe the bug**

Filled orders are not showing in history command. Confirmed orders in KuCoin trade history.

**Steps To Reproduce**

Run a pmm strategy on Kucoin and wait until an order gets filled.

**Screenshots**

![image](https://user-images.githubusercontent.com/64377055/88510237-32990080-d015-11ea-92ff-10e7d3895d57.png)
![image](https://user-images.githubusercontent.com/64377055/88510443-93283d80-d015-11ea-8a44-2ee5bea80653.png)

```
"branch": "development",
"commit": "18705a055a9f25b1286f078d0c4f20d4e70ffab5",
"date": "2020-07-23T23:20:11Z",
```

**Release version**
dev-0.30.0

**Attachments**

[kucoin_kcs-usdt.zip](https://github.com/CoinAlpha/hummingbot/files/4980334/kucoin_kcs-usdt.zip)
[logs_kucoin_kcs-usdt.zip](https://github.com/CoinAlpha/hummingbot/files/4980626/logs_kucoin_kcs-usdt.zip)
[hummingbot_trades.zip](https://github.com/CoinAlpha/hummingbot/files/4980336/hummingbot_trades.zip)

**Comment by rxlxrxsx** [comment]
Tried to reproduce the issue from scratch, new log file and db file. Confirmed bug persists.

![image](https://user-images.githubusercontent.com/64377055/88520125-bce96080-d025-11ea-9854-ff0a5d89548e.png)


[hummingbot_trades.zip](https://github.com/CoinAlpha/hummingbot/files/4980804/hummingbot_trades.zip)
[logs_kucoin_kcs-usdt.log](https://github.com/CoinAlpha/hummingbot/files/4980805/logs_kucoin_kcs-usdt.log)

**Comment by PtrckM** [comment]
- tried on paper trade seems to work fine.

![image](https://user-images.githubusercontent.com/54516858/88532945-fdea7080-d037-11ea-89d4-b70a7bebae33.png)
![image](https://user-images.githubusercontent.com/54516858/88532970-0b075f80-d038-11ea-8223-908522b3450c.png)

**Comment by vic-en** [comment]
@PtrckM 
The bug is related to how KuCoin sends updates over websocket.
A fix is on the way!
