### ISSUE TITLE
[BUG] "TypeError: object NoneType can't be used in 'await' expression" happens on live trade.

### ISSUE THREAD

**Issue by rxlxrxsx** [CoinAlpha/hummingbot#2113]
**Describe the bug**

"TypeError: object NoneType can't be used in 'await' expression" happens on live trade. This is similar to an old GitHub issue [#1570](https://github.com/CoinAlpha/hummingbot/issues/1570) but now this is also occurring with paper mode disabled. This happened when I ran the bot on Eterbase, tried it on Binance but didn't get the same error.

```
2020-07-27 04:53:39,968 - 1 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: object NoneType can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
TypeError: object NoneType can't be used in 'await' expression
```

**Steps To Reproduce**

Run a pmm strategy using Eterbase exchange.

**Screenshots**

![Capture](https://user-images.githubusercontent.com/64377055/88515341-25ccda80-d01e-11ea-9d6f-a3815dc8c9d8.JPG)

```
"branch": "development",
"commit": "3d12d15f1f832b79ecf8a1ad793cea0a18bfe592",
"date": "2020-07-26T02:09:13Z",
```

**Release version**

dev-0.30.0

**Attachments**
[eterbase-eth_usdt.txt](https://github.com/CoinAlpha/hummingbot/files/4980555/eterbase-eth_usdt.txt)
[logs_eterbase_eth-usdt.txt](https://github.com/CoinAlpha/hummingbot/files/4980556/logs_eterbase_eth-usdt.txt)

**Comment by dennisocana** [comment]
Thanks @rxlxrxsx can you also check the logs from other connectors if they're getting this?

**Comment by rxlxrxsx** [comment]
Checked the logs on the following connectors but did not find anything:
-Binance
-Liquid
-Bittrex
-Huobi
-Coinbase Pro
-Raday Relay
-KuCoin
-Kraken

**Comment by dennisocana** [comment]
We haven't run into this error again. @rxlxrxsx feel free to reopen if issue persists
