### ISSUE TITLE
[BUG] Intermittent server errors on Radar Relay

### ISSUE THREAD

**Issue by rxlxrxsx** [CoinAlpha/hummingbot#2117]
**Describe the bug**
Getting this error from time to time while running the bot on Radar Relay.

```
2020-07-28 01:54:30,564 - 1 - hummingbot.market.radar_relay.radar_relay_market - NETWORK - Error
fetching status update for the order buy-WETH-DAI-1594964031010130: Error fetching data from
https://api.radarrelay.com/v3/orders/0xfa512fb7e1f5512d3093fc2238480c74586b776687beb6e3c4d636d0d8992932.
HTTP status is 502 - Server Error: Bad Gateway..

2020-07-28 01:54:30,564 - 1 - hummingbot.market.radar_relay.radar_relay_market - WARNING - Failed to
fetch status update for the order buy-WETH-DAI-1594964031010130. Check Ethereum wallet and network
connection.
```

**Steps To Reproduce**
Run a PMM strategy on Radar Relay.

**Screenshots**

![image](https://user-images.githubusercontent.com/64377055/88623987-bcf66880-d0d8-11ea-8a86-219a1354db08.png)

**Release version**

dev-0.30.0

```
"branch": "development",
"commit": "18705a055a9f25b1286f078d0c4f20d4e70ffab5",
"date": "2020-07-23T23:20:11Z",
```

**Attachments**

[radar_weth-dai.txt](https://github.com/CoinAlpha/hummingbot/files/4986226/radar_weth-dai.txt)
[logs_radar_weth-dai.log](https://github.com/CoinAlpha/hummingbot/files/4986227/logs_radar_weth-dai.log)

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rak52x) by [Unito](https://www.unito.io)

**Comment by RC-13** [comment]
Closing ticket, connector has been deprecated
