### ISSUE TITLE
[Feature] history command redesign

### ISSUE THREAD

**Issue by Nullably** [CoinAlpha/hummingbot#2129]
**Why**
The current history command shows a list of trades since the bot started, this list can get really long, hundreds of trades, especially for professional market makers. This clogs up their telegram bot channel. 
The command also has limitation on starting timestamp that fixates on the time since the bot started, users cannot see older records and performance. The command can also not be used if there is no strategy running.

**Feature Suggestion**
- Remove dependency on having a running strategy.
- The command can be used any time.
- Add `--verbose` argument, if supplied show the list of past trades, this means by default the command no longer shows historical trades.
- Add `--config_file` command argument, defaulted to current `strategy_file_name`. If there is no current `strategy_file_name`, prompt error message asking user to supply the argument.
- Add `--duration` argument, defaulted to the bot starting time, the value can be supplied with unit letter, `d` for days, `h` for hours and `m` for minutes, e.g. 7d for 7 days or 12h for 12 hours. If unit is not specified, assume hours, e.g. 12 is 12h.
- Since start time is no longer the bot starting time, we can no longer get starting balance snapshot. Remove `Starting` and
`Net Delta` from `Inventory` table.
- Update `Return %` to use total current inventory value as a denominator.

**Other considerations**
- Since the command is now more about stats and performance than history, it could be rename it to `stats` or `performance` to avoid confusion.
- Consider display past trades under `list` command, ie. `list trades`. We used to have `list` command, but removed it.
- We should sync up with Miner app on how the performance is calculated there and use the same calculation here.

**Comment by Nullably** [comment]
@mifeng Please review.

**Comment by mifeng** [comment]
>Add --duration argument, defaulted to the bot starting time, the value can be supplied with unit letter, d for days, h for hours and m for minutes, e.g. 7d for 7 days or 12h for 12 hours. If unit is not specified, assume hours, e.g. 12 is 12h.
I think we can make this simpler by assuming that the the increment is always days, since that's the most common one and allow users to enter decimal values, i.e. `history --days 0.5`

>Add --config_file command argument, defaulted to current strategy_file_name. If there is no current strategy_file_name, prompt error message asking user to supply the argument.
I don't think we need this, since data comes from the trades stored in the current session.

>Since the command is now more about stats and performance than history, it could be rename it to stats or performance to avoid confusion.
I don't think we should rename the command since users are already used to typing `history` and any change causes friction.

>Consider display past trades under list command, ie. list trades. We used to have list command, but removed it.
Since users can see list of trades with `history --verbose`, we shouldn't have another command that does the same thing, which is a UX anti-pattern.

>We should sync up with Miner app on how the performance is calculated there and use the same calculation here.
Agreed - I believe it's the same already but we should use the exact same layout and wording as Miner app.

**Comment by Nullably** [comment]
> > Add --config_file command argument, defaulted to current strategy_file_name. If there is no current strategy_file_name, prompt error message asking user to supply the argument.

> I don't think we need this, since data comes from the trades stored in the current session.

Having --config_file argument will let user see `history` from other bot's session, it will also let the user run the command before `import`. Alternatively, the command can show error message if the user hasn't yet `import` a strategy config file, and the bot shows only trades from the current imported config file.

**Comment by Nullably** [comment]
Another related feature request.
#2175

**Comment by phbrgnomo** [comment]
The `history` report could also show the average cost of the inventory at the moment, to help traders have quick information if they want to liquidate their inventory at that moment.

**Comment by mifeng** [comment]
I created a [Google Sheet](https://docs.google.com/spreadsheets/d/1zp8EmeJdiP5soR_Bu7hRjaSy65bc7lsg98J5jKanRn8/edit?usp=sharing) with a revised layout for the information displayed by this command.

**Comment by phbrgnomo** [comment]
Added extra performance indicators to the sheet @mifeng created. [Link to my copy](https://docs.google.com/spreadsheets/d/1p9K3i3xKgvN8Fv9GrndSzTrUfYBnJ_QU5z5TSzbEEbg/edit?usp=sharing).

Added:

1 - Inventory average cost price - A reference price above which the trades executed will be profitable. This price could be used as a reference to the feature requested on Issue [#2314](https://github.com/CoinAlpha/hummingbot/issues/2314)

2 - A resume of the effective trade performance (Not comparing to Holding the asset)

3 - Profitable liquidation price - It shows the at what price the market maker can fully liquidate his current inventory without a loss.

**Comment by Nullably** [comment]
We'll have to do this one #2106 for this feature request to work.

**Comment by Nullably** [comment]
@mifeng 
Since the start time is no longer the strategy start time, we can no longer have starting user balances information (we don't know at each point in history how much user has and how much is allocated into positions). 
All we now have is trades information. So all the calculation must derive from the trades table. 

@phbrgnomo 
The extra columns in the table are really complicated, and as mentioned above, we might not be able to do it. 
Would it be easier to understand to keep it simpler?

**Comment by mifeng** [comment]
Yeah, let's put @phbrgnomo's suggestions into a new story. I think they're worth exploring, especially avg cost of inventory, but I don't think we should add more complexity to this story.

**Comment by phbrgnomo** [comment]
I will work on simplifying the calculations in a more code friendly way.

**Comment by Nullably** [comment]
@mifeng 
Here is a draft PR for the new design, all calculation done.
https://github.com/CoinAlpha/hummingbot/pull/2512

There are a few problems with the new design from displaying a performance metric for each exchange / market.
- For Arbitrage and XEMM strategies, there will be 2 sets of performance metric.
- Kill switch needs a single Return % - I am not sure on how to resolve this

**Comment by Nullably** [comment]
Can we use an average of Return % for Kill switch purpose? Assuming each side of Arb or XEMM executes roughly the same amount of capital.

**Comment by mifeng** [comment]
> Can we use an average of Return % for Kill switch purpose? Assuming each side of Arb or XEMM executes roughly the same amount of capital.

Yes, let's use the average if there are more than 1 market.

**Comment by mifeng** [comment]
@vic-en said during client squad standup that this may affect how the Binance Perpetuals connector works, so we should review this and merge into development ASAP, so that we see how it works with other changes in this release.
