### ISSUE TITLE
[BUG] Telegram integration still working even if it's set to false

### ISSUE THREAD

**Issue by rxlxrxsx** [CoinAlpha/hummingbot#2131]
**Describe the bug**

Still getting notified on Telegram even when ``telegram_enabled`` is set to false. It only happens when setting ``telegram_enabled`` from true to false inside Hummingbot. The current workaround is to restart Hummingbot for it to reflect the changes.

**Steps To Reproduce**

Set-up a bot with ``telegram_enabled`` set to true first, then inside Hummingbot change ``telegram_enabled`` to false and you'll still get notified on Telegram when you start the bot.

**Release version**

version-0.29.0

**Comment by dennisocana** [comment]
@rxlxrxsx @sigit2306 as discussed during last catch up, this is an expected behavior. When changing this parameter, `exit` Hummingbot and restart the session for this change to take effect. If you think this should be improved, submit a feature request instead.
