### ISSUE TITLE
[BUG] Paper Trading Accounting 

### ISSUE THREAD

**Issue by cryptohustlin** [CoinAlpha/hummingbot#2132]
**Describe the bug**
// A clear and concise description of what the bug is.
After making a loosing trade, hummingbots paper trade "history" accounting shows a "win" in terms of trade delta

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: ...
2. Start the bot using this command: ...
...
Paper trading and having trades fill

**Screenshots**
// If applicable, add screenshots to help explain your problem.
https://cdn.discordapp.com/attachments/636733596899606538/738433849561710632/unknown.png
https://cdn.discordapp.com/attachments/636733596899606538/738433968730538095/unknown.png
https://cdn.discordapp.com/attachments/636733596899606538/738434061025935380/unknown.png
https://cdn.discordapp.com/attachments/636733596899606538/738434162624692315/unknown.png
-------------------------------------------------
status
https://cdn.discordapp.com/attachments/563462222878212098/738435945111486624/unknown.png
-------------------------------------------------
Trade History
https://cdn.discordapp.com/attachments/636997035043717142/738464370106826800/unknown.png
https://cdn.discordapp.com/attachments/636997035043717142/738464763528609812/unknown.png

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).
0.29
**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 
https://cdn.discordapp.com/attachments/636997035043717142/738463745356857853/unknown.png

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by Clint-G13** [comment]
Test cross-exchange market-making in paper trade mode and verified that calculation on the history is correct. Did manual computation as well and calculation is almost the same with what's on the user's performance screenshot.
```
Inventory:
                 Market Asset     Starting      Current    Net Delta  Trade Delta
  0  bittrex_PaperTrade   BTC       0.4500       0.5651      0.1151      0.1148 BTC
  1  bittrex_PaperTrade   VET    310000.00000  235000.0000  -75000.0000  -75000.0000 VET
  2   kucoin_PaperTrade   BTC       0.4500       0.3339     -0.1161      -0.1161 BTC
  3   kucoin_PaperTrade   VET    310000.00000  385000.0000  75000.0000   74925.0000 VET

Markets:
                 Market     Pair   Start Price     End Price  Trades Trade Value Delta
  0   kucoin_PaperTrade  VET-BTC    0.00000147  0.0000015650       8    0.00111444 BTC
  1  bittrex_PaperTrade  VET-BTC  0.0000014544  0.0000015600       6   -0.00223638 BTC

Total Trade Value Delta: [0.00111444 + (-0.00223638) ] = -0.00112198 BTC 
Return %: -0.0622%
```
Starting quotes --> Convert base asset to quote currency then add quote token
```
bittrex: (310000.00000 * 0.0000014544) + 0.4500 = 0.900864
kucoin: (310000.00000 * 0.00000147) + 0.4500 = 0.9057
total starting qoute: 1.801728 BTC
```
return
```
total return = total trade value delta / total starting quote 
= -0.00112198 / 1.801728 
= -6.227022058823529e-4 *100%
return = -0.0622%
```

**Comment by sigit2306** [comment]
Hi @cryptohustlin,  After making a loosing trade, hummingbots paper trade "history" accounting shows a "win" in terms of trade delta.

If you refer **win in terms of trade delta** is Trade Delta on Bittrex. And **after making a losing trade** refers to Trade Value Delta and/or Return% which shows negative value.
After executing those trades on Bittrex Exchange:
- Quote asset inventory level/balance changed, acquired 0.1148 BTC.
- Base asset inventory level/balance changed, lost 0.117 BTC.
- That's why your Trade Value Delta shows a negative value of -0.0022 BTC
