### ISSUE TITLE
[Feature] Dashboard Enhancement - Portfolio 

### ISSUE THREAD

**Issue by thomasyit** [CoinAlpha/hummingbot#2165]
**Feature Suggestion**
Currently, there are Rewards, Payouts, Performance in the Dashboard. To have a new feature Portfolio as one of the new tab. The Portfolio allows users to have an overview of their assets performance overtime, its similar to blox.io, see [Top panel](https://coincise.co/wp-content/uploads/2020/08/Portfolio-Overview-Wo-bargraph_cropped.jpg) and [bottom panel](https://coincise.co/wp-content/uploads/2020/07/Screenshot-2020-07-31-at-4.49.45-PM.png)

Features:
**Portfolio Balance:** balance of all the exchange accounts
**Accounts:** Shows the different exchanges account and value.
**Assets** : Shows the different types, percentage, value of each asset under the account.
**Portfolio balance graph**:  can add more graphs for each coin.

**Impact**
The Performance is mainly targeted for the liquidity campaign and limited over the past Hr, 24Hrs, and week. It is good to have more visualisation of the overall performance of liquidity mining, and non-liquidity mining coins.

**Comment by phbrgnomo** [comment]
This is related to Liquidity mining, @thomasyit redirect this suggestion (if still needed) to the Liquidity Mining squad.
