### ISSUE TITLE
Balancer gateway API

### ISSUE THREAD

**Issue by mifeng** [CoinAlpha/hummingbot#2169]
Similar to #1710 but for Balancer

Spec TBC

**Comment by mifeng** [comment]
@Nullably Balancer APIs in `gateway-api` are now all working. Do you want me to convert the function names and params to the ones above?

**Comment by Nullably** [comment]
@mifeng Probably not needed, I'll start working on the connector and will let you know, thanks.

**Comment by mifeng** [comment]
I will make the following changes today/tomorrow:

* Add `gasPrice` param to all function calls so that user can pass in how much gas to spend
* Convert the `price` and `trade` functions to `buy-price`, `sell-price`, `buy`, and `sell`

**Comment by mifeng** [comment]
@Nullably After Balancer sent us the [test repo](https://github.com/johngrantuk/swapExample ), I fixed the buy functions in Balancer gateway-api in the last commit to `master`

Note that:
- There are separate `buy` and `sell` functions, along with price functions for each
- The trade functions now wait for transaction confirmation before returning, so now I can show the `status` in the response (1 = success, 2 = fail)

I will create separate tasks that optimizes the Balancer part of `gateway-api`:
- add a function to check for transaction status, so that waiting for tx confirmation is non-blocking
- handle errors properly

Either @sdgoh or I should be able to do those remaining tasks.
