### ISSUE TITLE
[BUG] Failed to connect to Coinbase Pro since API Key is not requested on a specific scenario

### ISSUE THREAD

**Issue by sazed5055** [CoinAlpha/hummingbot#217]
**Steps to Reproduce:**

1. Launch Hummingbot 
2. Configure Binance as a taker
3. Close Hummingbot
4. Relaunch Hummingbot
5. Create a new confiuration and set Coinbase Pro as a taker

**Expected Behavior:**

   Coinbase API key is requested

**Actual Behavior:**

Coinbase API key is not requested therefore failed to connect

![1](https://user-images.githubusercontent.com/50499987/57578011-4d0bac00-745a-11e9-97fb-6cf54c7317ba.jpg)

![2](https://user-images.githubusercontent.com/50499987/57578023-817f6800-745a-11e9-902c-f3817af0af86.jpg)

**Comment by nsshommo** [comment]
Hello @sazed5055 Thanks for letting us know this. The team is working and will change the way it works very soon in later release. By this time follow the below process:
You can change the API by writing "config coinbase_pro_api_Key". Then the hummingbot will ask for your coinbase pro API and you will have to copy paste the API key. After that it should be changed. However, you will have to change the key again if you wish to use Binance as take by writing "config binance_api_key".
Hopefully it will help. Try and let us know your feedback.

**Comment by martinkou** [comment]
We've released v0.6.0 today which should have fixed this issue. Please try again by deleting the `conf_global.yml` config file and entering your API keys again.

**Comment by smonsurMetOcean** [comment]
Sounds Good

**Comment by sazed5055** [comment]
Sounds Good
