### ISSUE TITLE
Design approach for integrating new protocols into the client

### ISSUE THREAD

**Issue by mifeng** [CoinAlpha/hummingbot#2170]
* Propose a design for how the client integrates with other protocols
* Assume that when a user connects to a protocol, they automatically get access to all exchanges on that protocol. This is how it works in Ethereum, where once you connect ethereum, you can trade on Radar Relay, Uniswap, and other Ethereum-based DEXs
* Since many of these new protocols only have one exchange which uses AMM structures, it's easier to create custom strategies for them.
* strategies we develop should only be dependent on the type of market (order book vs AMM), not the market itself
* ie a `celo-arb` strategy runs can on Celo, but if there's an order book DEX on Celo, our PMM strategy can also run on that exchange

**Comment by Nullably** [comment]
This task has expanded into re-design market connector architecture.
See https://www.notion.so/hummingbot/Market-connector-re-design-8ff11cd9ff474a07bb0e19c327a91317
