### ISSUE TITLE
[BUG] Connect command doesn't work after trying to connect on an exchange and using ctrl + x midway

### ISSUE THREAD

**Issue by sigit2306** [CoinAlpha/hummingbot#2171]
**Describe the bug**
When trying to connect hummingbot to ethereum, accidentally chose eterbase, and realized it midway, effort to cancel the connection to eterbase was by using ctrl + x that exited the prompt, then connect hummingbot to ethereum as planned.
Afterward, the `connect` command doesn't work.

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):
1. Run hummingbot, and type `connect eterbase` command
2. Enter arbitrary value for eterbase API key 
3. On secret key prompt, hit ctrl + x to exit
4. Type `connect ethereum` command
5. Fill in all requested value correctly for wallet private key, ethereum node, and web socket address
6. Type `connect` command, it will not display the status of connections. Exiting and restarting the bot will not resolve this issue,
7. Type `connect eterbase` and enter arbitraty value for all user prompt. It will display an error message `signature cannot be verified` for eterbase.
8. Type `connect` command, it will display the status of connections and error message `signature cannot be verified` for eterbase.
9. Exit the bot, go to `conf/` and delete all **encrypted_eterbase_*.json** files
10. Run the bot, type `connect` command, it will display the status of connections with no error message.  
...

**Screenshots**
![01](https://user-images.githubusercontent.com/12313129/89504524-59fc8400-d7f2-11ea-8429-c1382a5dfd55.png)
![02](https://user-images.githubusercontent.com/12313129/89504536-5ff26500-d7f2-11ea-9922-4b3b40770af2.png)
![03](https://user-images.githubusercontent.com/12313129/89504556-67b20980-d7f2-11ea-9e4f-203330012c43.png)
![04](https://user-images.githubusercontent.com/12313129/89504565-6e408100-d7f2-11ea-911d-8a0a9b9dc29a.png)
![05](https://user-images.githubusercontent.com/12313129/89504571-71d40800-d7f2-11ea-9486-c8a5d3e6244d.png)

**Release version**
Windows Binary, Version 0.29.0
Docker Build, Version 0.29.0 

**Optional: your discord username:**
sigit#7187

**Comment by rxlxrxsx** [comment]
Confirmed it happens when trying to connect to other exchanges then cancelling (ctrl + x) midway.

```
2020-08-06 18:00:45,957 - 13716 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: tuple 
index out of range
Traceback (most recent call last):
  File "hummingbot\core\utils\async_utils.py", line 9, in safe_wrapper
  File "hummingbot\client\command\connect_command.py", line 80, in show_connections
  File "hummingbot\client\command\connect_command.py", line 92, in connection_df
  File "hummingbot\user\user_balances.py", line 104, in update_exchanges
  File "hummingbot\core\utils\async_utils.py", line 22, in safe_gather
  File "hummingbot\user\user_balances.py", line 91, in update_exchange_balance
  File "hummingbot\user\user_balances.py", line 74, in add_exchange
  File "hummingbot\user\user_balances.py", line 35, in connect_market
IndexError: tuple index out of range
```

**Comment by RC-13** [comment]
Test using windows binary and WSL source, I no longer get this issue when cancelling a question midway.
