### ISSUE TITLE
Probit Exchange Connector

### ISSUE THREAD

**Issue by sunburntcat** [CoinAlpha/hummingbot#2174]
## Exchange Details ✏️

- **Name of exchange**:   Probit
- **Exchange URL**:   https://www.probit.com/en-us/
- **Link to API docs**:    https://docs-en.probit.com/docs
- **Type of exchange**: [y] Centralized [ ] Decentralized
- **Requester details**: Are you affiliated with the exchange? [ ] yes [y] no 
  - If yes, what is your role?

## Rationale / impact ✏️
(Describe your rationale for building this exchange connector, impact for hummingbot users/community)
We are building the connector for our own purpose of liquidity of Telos token with the Probit exchange. We would like to hand over what we have to Hummingbot, so that their users may benefit as well.

## Additional information ✏️
(Provide any other useful information that may be helpful to know about this exchange)
Their API is straightforward with respect to order queries and posts. The interactions look similar to Bittrex's API, and therefore may be valuable to U.S. and European users.

---

⚠️ ***Note: do not modify below here***

## Developer notes

This feature request entails building a new exchange connector to allow Hummingbot to connect to an exchange that is currently not supported.

### Resources
- [Exchange connector developer guide](https://docs.hummingbot.io/developers/connectors/)
- [Discord forum](https://discord.hummingbot.io)

### Deliverables
1. A complete set of exchange connector files as listed [above](#developer-notes-resources).
2. Unit tests (see [existing unit tests](https://github.com/CoinAlpha/hummingbot/tree/master/test/integration)):
  1. Exchange market test ([example](https://github.com/CoinAlpha/hummingbot/blob/master/test/integration/test_binance_market.py))
  2. Order book tracker ([example](https://github.com/CoinAlpha/hummingbot/blob/master/test/integration/test_binance_order_book_tracker.py))
  3. User stream tracker ([example](https://github.com/CoinAlpha/hummingbot/blob/master/test/integration/test_binance_user_stream_tracker.py))
3. Documentation:
  1. Code commenting (particularly for any code that is materially different from the templates/examples)
  2. Any specific instructions for the use of that exchange connector ([example](https://docs.hummingbot.io/connectors/binance/))

### Required skills
- Python
- Previous Cython experience is a plus (optional)

**Comment by PtrckM** [comment]
dup https://github.com/CoinAlpha/hummingbot/issues/1990

**Comment by subzer42** [comment]
Any updates on this?

**Comment by dennisocana** [comment]
Will be available in version 0.37 release
