### ISSUE TITLE
[Feature] Redesign and reimplement top and bottom navbars in client

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#2179]
**Feature Suggestion**

## Why

In the client, we display persistent information in the top navbar:

<img width="1527" alt="Screen Shot 2020-07-09 at 5 48 45 PM" src="https://user-images.githubusercontent.com/50150287/89611018-9d1c2d00-d8ae-11ea-8f00-ad6df847c096.png">

This isn't the most relevant information that is needed by the user.

## What

Redesign what information the top navbar should display. Add a bottom navbar if needed.

The navbar info should give users information about:

- version (existing)
- paper trading mode on vs off (existing)
- active strategy file
- primary market (if strategy active)
- primary exchange (if strategy active)

As a stretch goal, it would also be helpful to provide information - this might be better for the bottom navbar:

- duration of bot
- number of trades made
- P&L
- performance %

**Comment by dennisocana** [comment]
Similar to user's feature request here https://github.com/CoinAlpha/hummingbot/issues/1699

**Comment by krisj** [comment]
It would be great to be able to inject some information from user scripts into either of navbars too. Like volatility % or whatever other variables.... similar to log/notify sub-enhancement here: https://github.com/CoinAlpha/hummingbot/issues/2104#issuecomment-670786338

**Comment by PtrckM** [comment]
suggestions to add on navbars 
- show memory usage mb / percent
 - cpu usage percent
 - can toggle on or off

![image](https://user-images.githubusercontent.com/54516858/95468207-dce7b980-09b0-11eb-85e1-0d5db47ec507.png)

**Comment by mifeng** [comment]
During client planning, @vic-en mentioned that the new duration in #2129 (history command redesign) may need to be updated to make this duration consistent. Overall, I think we should merge both PRs to `development` and test them together.
