### ISSUE TITLE
Remove unnecessary `TimeoutError` excepts

### ISSUE THREAD

**Issue by Nullably** [CoinAlpha/hummingbot#2198]
There are many places in our code base in `_inner_messages` function where we except `asyncio.TimeoutError` but don't do anything with it. As per this PR https://github.com/CoinAlpha/hummingbot/pull/2182, we should make the same refactor to those other `_inner_messages` as well.

Be careful to remove the except only when the except doesn't do anything with the error and there is no other except within the same try-except block.

**Comment by Nullably** [comment]
There is another problem with `__inner_messages`
```
    pong_waiter = await ws.ping()
    await asyncio.wait_for(pong_waiter, timeout=self.PING_TIMEOUT)
```
pong_waiter is a result, not a task (nor future), so it can't be used in the another wait for.
This code should simply be just
```
   await asyncio.wait_for(ws.ping(), timeout=self.PING_TIMEOUT)
```

**Comment by dennisocana** [comment]
Closing w.r.t. https://github.com/CoinAlpha/hummingbot/issues/3485
