### ISSUE TITLE
[REFACTOR] Minimise new connectors Task 4.

### ISSUE THREAD

**Issue by Nullably** [CoinAlpha/hummingbot#2199]
**Why**
Currently we ask new connector to modify various parts of Hummingbot client code base when the connector is ready to merge in (task 4 in developer connectors tutorial). 

https://docs.hummingbot.io/developers/connectors/tutorial/#task-4-hummingbot-client

Many of these steps can be reduced by
 
1. Standardise market connector constructor functions, by making sure all the market connectors have the same init function signature, we can load up the object dynamically (using `__import__`), this removes the modification steps for hummingbot/client/hummingbot_application.py and hummingbot/user/user_balances.py.

2. Move `fetch_new_market_trading_pairs` function to the market api data source class (also make the function abstract in the base class), similar to step 1 we can dynamically load this function up at run time for all connector without having to manually call the function one by one. Then we can also request the connector developer to supply unit test case for this.

3. Similar to the fetch trading pair, hummingbot/core/utils/market_mid_price.py this can be added to the market api data source class, note that for most exchanges this is probably the same API used to get last traded price.

**Comment by vic-en** [comment]
We can further eliminate the need to make changes to files outside the directory for new connector.
1. Contents from the `hummingbot/client/settings.py` and the api ConfigVar keys in `hummingbot/client/config/global_config_map.py` can be moved to be moved to the utils.py file of each connector directory.
2. The default estimate fee for `hummingbot/core/utils/estimate_fee.py` can also be defined as a constant(List type) in the utils.py file of each connector directory.
3. Dict keys and values of `fee_overrides_config_map` in `hummingbot/client/config/fee_overrides_config_map.py`  can be done programmatically.
4. Lastly, the content of `conf/__init_.py` can be done programmatically and all test files can be adjusted to to work accordingly.

**Comment by vic-en** [comment]
Done.
