### ISSUE TITLE
[BUG] History and kill switch do not work when running multiple bots from source installation

### ISSUE THREAD

**Issue by carlolm** [CoinAlpha/hummingbot#2201]
**Describe the bug**

When running multiple bots from the same installation (same bin/hummingbot.py file), this results in db conflicts. rendering `kill switch` and `history` unusable:

![image](https://user-images.githubusercontent.com/12274903/89944253-5727d780-dbd4-11ea-8bce-c6f136741b32.png)

Hummingbot says that the database is locked.

**Steps To Reproduce**
1. Install HB from source
2. Run multiple instances from the same install (different terminals or different tmux sessions)
3. Run `history`

**Screenshots**
// If applicable, add screenshots to help explain your problem.

**Release version**
0.30.0

**Comment by TheHolyRoger** [comment]
I've experienced this too: https://github.com/CoinAlpha/hummingbot/pull/2190#discussion_r468017576

Had to `exit -f`

I experienced it during normal operation (without running any additional commands during) - with 7 bots running from the same directory.

Was hammering it quite a bit with 4 pure market making strats (2-8 order levels each)  and 3 simple loop trade strats.

Resulted in crashes on all instances I think :)

**Comment by dennisocana** [comment]
This is fixed by https://github.com/CoinAlpha/hummingbot/pull/2498
