### ISSUE TITLE
[BUG] API requests intermittently failing on Kraken

### ISSUE THREAD

**Issue by rxlxrxsx** [CoinAlpha/hummingbot#2204]
**Describe the bug**

Getting several intermittent errors on Kraken when fetching status updates through API requests which results to the following errors shown in the screenshots (checking for open orders, canceling orders, submitting orders).

**Steps To Reproduce**

Run a pure market making strategy on Kraken.

**Screenshots**

![image](https://user-images.githubusercontent.com/64377055/90001023-80736100-dcc3-11ea-9c4f-35b124c83961.png)
![image](https://user-images.githubusercontent.com/64377055/90001072-8e28e680-dcc3-11ea-98d2-9208f5a166bc.png)
![image](https://user-images.githubusercontent.com/64377055/90001156-a436a700-dcc3-11ea-8426-1d8ca249dc9b.png)
![image](https://user-images.githubusercontent.com/64377055/90006480-853c1300-dccb-11ea-8718-5847a11bd781.png)

```
"branch": "development",
"commit": "7659cfeee8ae7032647b466c335255eed417b084",
"date": "2020-08-11T02:22:37Z",
```

**Release version**

dev-0.30.0

**Attachments**

[logs_kraken_btc-usdc.log](https://github.com/CoinAlpha/hummingbot/files/5061910/logs_kraken_btc-usdc.log)

**Comment by TheHolyRoger** [comment]
Two problems here - kraken should use the same throttler that binance uses and this chunk should be moved inside the try:

https://github.com/CoinAlpha/hummingbot/blob/master/hummingbot/market/kraken/kraken_market.pyx#L1017

**Comment by TheHolyRoger** [comment]
This fixes one part of the problem: https://github.com/CoinAlpha/hummingbot/pull/2206/files

**Comment by TheHolyRoger** [comment]
This should fix the other part: https://github.com/CoinAlpha/hummingbot/pull/2214

**Comment by RC-13** [comment]
Same issue re-occurred on Kraken running on development branch [0.32.0]. 
![stuck order](https://user-images.githubusercontent.com/57189990/93402746-27957a80-f8b8-11ea-9c22-63dfdccaae4f.PNG)
The bot thought it failed to create the order due to connectivity issues however the order actually pushed through to the exchange resulting to order not getting tracked.
![kraken](https://user-images.githubusercontent.com/57189990/93402550-9faf7080-f8b7-11ea-9852-376e9cf6fd2a.png)
[kraken_log.txt](https://github.com/CoinAlpha/hummingbot/files/5235395/kraken_log.txt)

**Comment by dennisocana** [comment]
Reopening due to the same errors found in the current release that causes orders to get stuck in the exchange (uncancelled).

**Comment by mifeng** [comment]
May be rate limits

**Comment by keithbaum** [comment]
Today I've been testing the proposed fix from the PR and it seems to be working properly. Been running the bot in a PMM strategy for 2 hours and from the logs it can be seen that the API although no longer hitting the rate limit, it's always pretty near. I wonder if the throttler limit may be inducing too many sleep time and delaying api requests in a way bot profitability is harmed.

Kraken API Capacity analysis:
[https://app.zenhub.com/files/179163124/d22f656e-1d78-4ec8-91e9-4646d21f7d6a/download](https://app.zenhub.com/files/179163124/d22f656e-1d78-4ec8-91e9-4646d21f7d6a/download)

**Comment by tomma100** [comment]
+1 to pull this PR!

**Comment by rxlxrxsx** [comment]
Reopening due to the same issue that causes the orders to get stuck on the exchange.

<img width="1104" alt="Screen Shot 2021-01-31 at 3 49 16 PM" src="https://user-images.githubusercontent.com/64377055/106378272-66971900-63de-11eb-80a8-1df2c1b751e6.png">
<img width="1162" alt="Screen Shot 2021-01-31 at 3 50 01 PM" src="https://user-images.githubusercontent.com/64377055/106378276-6d259080-63de-11eb-8017-bfd19d10791c.png">
These were the stuck orders that I manually cancelled which can also be found on the log file.
<img width="1156" alt="Screen Shot 2021-01-31 at 3 53 21 PM" src="https://user-images.githubusercontent.com/64377055/106378281-6f87ea80-63de-11eb-9718-399d37524961.png">

Errors and warning that's intermittently present in the logs:
<img width="1032" alt="Screen Shot 2021-01-31 at 4 13 56 PM" src="https://user-images.githubusercontent.com/64377055/106378446-d4901000-63df-11eb-8a47-0d3f3df67f5c.png">
<img width="1033" alt="Screen Shot 2021-01-31 at 4 17 05 PM" src="https://user-images.githubusercontent.com/64377055/106378447-d5c13d00-63df-11eb-81ab-bcfb686a48ff.png">
<img width="1094" alt="Screen Shot 2021-01-31 at 4 19 31 PM" src="https://user-images.githubusercontent.com/64377055/106378490-3badc480-63e0-11eb-9f48-73660d302aa0.png">

[logs_kraken_btc-usdc.log](https://github.com/CoinAlpha/hummingbot/files/5899361/logs_kraken_btc-usdc.log)

```
version: development 0.36.0
commit: ed6e337e0d4280abdf8d9be78e132f9399a59531
Date:   Thu Jan 28 22:37:19 2021 -0300
```

**Comment by keithbaum** [comment]
Hey @rxlxrxsx , will modify the retry interval and push new code for this.
