### ISSUE TITLE
[BUG] Target Values of Assets in PMM status report incorrect when orders are updating

### ISSUE THREAD

**Issue by vic-en** [CoinAlpha/hummingbot#2207]
**Describe the bug**
The sum of the current values for both assets does not equal to the sum of the target values of the assets when orders are updating.

![unknown](https://user-images.githubusercontent.com/31972210/90044942-45bef800-dcc6-11ea-884d-57c82468903e.png)

**Comment by RC-13** [comment]
Closing this ticket, checked all active centralized connectors, and has matching total for current value and target value.
