### ISSUE TITLE
[BUG]float division by zero on Binance

### ISSUE THREAD

**Issue by hongson1981** [CoinAlpha/hummingbot#222]
**Describe the bug**
Show error float division by zero on Binance when tracing

**Steps To Reproduce**

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: Please refer attached file
2. Start the bot using this command: start
...

**Screenshots**
N/A

**Release version**
dev-0.7.0

**Attachments**
Log, config files
[hummingbot_logs_2019-05-13-13-54-33.log](https://github.com/CoinAlpha/hummingbot/files/3173230/hummingbot_logs_2019-05-13-13-54-33.log)
[conf_global.txt](https://github.com/CoinAlpha/hummingbot/files/3173247/conf_global.txt)
[conf_cross_exchange_market_making_strategy_0.txt](https://github.com/CoinAlpha/hummingbot/files/3173257/conf_cross_exchange_market_making_strategy_0.txt)

// WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!

**Comment by martinkou** [comment]
@yzhang1994 please take a look. seems to me like we're not accounting for 0 initial balance case correctly here.

**Comment by yzhang1994** [comment]
This should be handled now.
