### ISSUE TITLE
[Feature] Update Bittrex connector to V3

### ISSUE THREAD

**Issue by Nullably** [CoinAlpha/hummingbot#2221]
**Feature Suggestion**
Bittrex v1.1 API will no longer be supported as of 9/30/2020

**Tasks**
* Update the connector (market, datasource and tracker files) to be compatible with v3 Bittrex API
* Update unit test cases accordingly

**Notes**
* The current unit test doesn't pass in mocked API test mode, please correct this as well.

**Comment by vic-en** [comment]
**Issues with upgrading to v3 of Bittrex socket:**
1. Bittrex Documentation isn't very good for developers using languages other than c#.
2. The python SignalR library is a little bit different from the original Microsoft ASP.net’s SignalR library written in C#. As a result of this, there's no method as `CreateHubProxy` in the python library which makes it difficult to connect to "c3" hub.
3. No examples exit on Bittrex's github repo. Also there are currently 2 open issues on their repo from different people having thesame problems as I've stated and getting exactly thesame error I get when trying to subscribe to the "c3" hub.

**Comment by mifeng** [comment]
@vic-en from Bittrex support: https://github.com/Bittrex/beta/blob/master/samples/PythonAsyncioSample should get you most of the way there, if it doesn't i'm afraid we cannot help 3rd parties develop signalr clients.

**Comment by vic-en** [comment]
> 
> 
> @vic-en from Bittrex support: "https://github.com/Bittrex/beta/blob/master/samples/PythonAsyncioSample should get you most of the way there, if it doesn't i'm afraid we cannot help 3rd parties develop signalr clients"

@mifeng , that only demonstrates how to use version 1.1 of Bittrex websocket.
