### ISSUE TITLE
[Feature] Binance Perpetual connector

### ISSUE THREAD

**Issue by Nullably** [CoinAlpha/hummingbot#2246]
**Feature Suggestion**
- Update existing `binance_perpetual` connector to python only.
- This new connector will serve as a new example on how to build a connector without using `cython`
- For this new connector, you will have to create/design a new base class `derivative_base` (extended from `exchange_base`).

**Comment by krisj** [comment]
Can't wait to start testing this connector!

**Comment by mifeng** [comment]
Ready for testing by the team
