### ISSUE TITLE
[BUG]DAI token not available on Binance connector

### ISSUE THREAD

**Issue by RC-13** [CoinAlpha/hummingbot#2255]
**Describe the bug**
DAI token isn't showing on the list of available trading pairs on all strategies of Hummingbot.

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):
1. Create any strategy on Hummingbot and set Binance as market
2. Press tab to display all supported market pairs or type in a token that is paired with DAI.
3. Notice that DAI is not available, manually typing the trading pair will give an error  `not a valid trading pair`
...

**Screenshots**
Checking on Binance website, DAI was listed a month ago
![Untitled (2)](https://user-images.githubusercontent.com/57189990/91242691-a2b4b680-e77a-11ea-906f-9a885946b40c.png)

However, if you check for DAI market, it's not available on Hummingbot Binance connector:
![Untitled](https://user-images.githubusercontent.com/57189990/91242685-9d576c00-e77a-11ea-89b0-2968d7432bf1.png)
![Untitled (1)](https://user-images.githubusercontent.com/57189990/91242688-a0525c80-e77a-11ea-80b7-4706fca12cab.png)

**Release version**
0.30.0

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by Clint-G13** [comment]
Fix on development version [0.31.0]
