### ISSUE TITLE
[Feature] Option to adjust inventory skew through reduction of spread size on one side

### ISSUE THREAD

**Issue by phbrgnomo** [CoinAlpha/hummingbot#2277]
**Feature Suggestion**
Add a setting that will make the bot reduce the spread size to compensate for the inventory skewness.

**Impact**
A lot of literature on market-making talk about using different spread size on one of the sides of the operation (bid or ask spread) to adjust the inventory balance.

An `inventory_skew_type` could be added to the `config` parameters, containing 2 options:

`order_size_skew` - Would work as it is now.
`spread_size_skew` - Change the spread size on one side of the operation

The user would define a threshold `inventory_skew_limit`, in percentage, telling the bot when it must start to change spread to rebalance the inventory:

A `skew_spread_size` setting would define what would be the new spread during the inventory rebalance.

example:

`ask_spread` = 0.5
`bid_spread` = 0.5
`inventory_skew_enable` = true
`inventory_skew_type` = spread_size
`inventory_skew_limit`= 30
`skew_spread_size` = 0.1
`market` = BTC-USD

IF (BTC inventory current % < 30%)
    `initial_ask_spread` = `ask_spread`
    `ask_spread` =   `skew_spread_size`
ELSE IF (BTC inventory current % > 75%)
     `initial_bid_spread` = `bid_spread`
     `bid_spread` =   `skew_spread_size`
ELSE
      `ask_spread` = `initial_ask_spread`
      `bid_spread` = `initial_bid_spread`

**Additional context**
Wrote using an IF logic, but a WHEN logic would probably be more efficient.

**Comment by mifeng** [comment]
As discussed, Paulo will work with engineering to create a sample script that does this, similar to https://github.com/CoinAlpha/hummingbot/blob/master/scripts/spreads_adjusted_on_volatility_script.py
