### ISSUE TITLE
[BUG] `discovery` strategy issues

### ISSUE THREAD

**Issue by mifeng** [CoinAlpha/hummingbot#230]
**Describe the bug**
Some issues with the `discovery` strategy hinder the user experience:

### 1. Nomenclature consolidation
<img width="719" alt="Screen Shot 2019-05-14 at 11 05 52 AM" src="https://user-images.githubusercontent.com/1795030/57711936-b0a1ff00-763d-11e9-9112-9038a7baf941.png">

Change text to: 
`Enter a list of trading pairs on [exchange] (e.g. [ZRX-WETH, BAT-WETH]) or press ENTER or all trading pairs`

### 2. Allow users to press ENTER
It's not obvious that users have to enter `[]` for all pairs. Most users will want to scan for all pairs, so we should optimize for that scenario.

### 3. ETH balance check not working
<img width="716" alt="Screen Shot 2019-05-14 at 11 14 27 AM" src="https://user-images.githubusercontent.com/1795030/57712131-17bfb380-763e-11e9-8a77-ad17e1c17f3b.png">
I have enough ETH in wallet, and when I run other strategies, this check passes.

### 4. Update users about status when fetching market data
It takes 5-10 minutes to get data from all pairs. From the status output above, it's not clear if bot is working or not. Can we keep a tally of how many pairs we currently have fetched, so that we can display a status message like `Fetching market data: 10/1000 trading pairs processed`?

**Release version**
`master`

**Comment by yzhang1994** [comment]
My PR (https://github.com/CoinAlpha/hummingbot/pull/228) will fix #2

**Comment by michaelc9** [comment]
PR [245](https://github.com/CoinAlpha/hummingbot/pull/245/commits/f3f60322e4ebdb20306fea49c44e4e53685035f0) will fix 1,3,4.

**Comment by michaelc9** [comment]
Resolved in dev/0.7.0
