### ISSUE TITLE
[BUG] Timestamp column in CSV export

### ISSUE THREAD

**Issue by mifeng** [CoinAlpha/hummingbot#2308]
**Describe the bug**
// A clear and concise description of what the bug is.
`timestamp` column in the trades csv file continuously saved to the `data` directory is incorrect. It's the same value for each row in the table, which seems to indicate a bug when the data is being written to the file.

<img width="1195" alt="Screen Shot 2020-09-10 at 11 30 34 AM" src="https://user-images.githubusercontent.com/1795030/92782639-f9fd7e00-f359-11ea-8bf3-212c80b014d0.png">

**Comment by CrimsonJacket** [comment]
**Timestamp in CSV:**
![image.png](https://images.zenhubusercontent.com/5ff320fa0a71217aa2d07d1a/31942eb4-dbcc-4832-bbd5-f3c888de0c78)

**Timestamp in SQLite file:**
![image.png](https://images.zenhubusercontent.com/5ff320fa0a71217aa2d07d1a/896cc37a-4589-493e-9267-198da0619759)

**Comment by RC-13** [comment]
We can go ahead and close this ticket, checked csv file from the Hummingbot client using google sheet and MS excel and timestamp are now showing correctly.
