### ISSUE TITLE
[Feature] Pure Market Maker strategy using the inventory cost as mid price for new orders

### ISSUE THREAD

**Issue by phbrgnomo** [CoinAlpha/hummingbot#2314]
**Feature Suggestion**
Implement a simpler and less-risk strategy that considers the average inventory buying cost as the reference for new orders.

Every time a bid type order is filled, the bot updates a new variable called `inventory_price`, which will store the volume-weighted average price of the inventory, and the strategy will use this value as the reference to define the ask and bid price of new orders, instead of the market mid-price.

Example:

First, the bot would have to set a price for the present inventory, and we have two options for that:

1 - The user defines the inventory cost starting price
2 - If there is no price entered, the bot could use the mid market price when `start` is entered

Either way, two values should be stored:

`inventory_size` - the number of assets on the account at the start of the bot run;
`inventory_price` - the price used on one of the two cases above

Then calculate:

`inventory_cost = inventory_size * inventory price`

The bot proceeds to send the bid and ask orders to the exchange using inventory_price as the mid-price, where:

`ask_price = inventory_price + inventory_price * ask_spread`
`bid_price = inventory_price - inventory_price * bid_spread`

When a bid order is filled:

`inventory_size = inventory_size + order_amount`
`inventory_cost = inventory_cost + (order_amount * bid_price)`

`inventory_price = inventory_cost / inventory_size`

When a ask order is filled:

`inventory_size = inventory_size - order_amount`
`inventory_cost = inventory_cost - (order_amount * ask_price)`

`inventory_price = inventory_cost / inventory_size`

When the new order cycle starts, repeat that calculation of `ask_price` and `bid_price` with the new value of `inventory_size`.

There is also the need for a check to compare the inventory_price with the market mid-price, to avoid sending orders as market taker:

`IF inventory_price > market_mid_price:

`ask_price = inventory_price + inventory_price * ask_spread`
`bid_price = market_mid_price - market_mid_price * bid_spread`

`IF inventory_price < market_mid_price:

`ask_price = market_mid_price + market_mid_price * ask_spread`
`bid_price = inventory_price - inventory_price * bid_spread`

**Impact**
This strategy is easier to understand, especially by those new to market making, since the bot will only create orders that will be profitable relative to the buying cost.

**Additional context**
It doesn't have to be a new strategy, but a trigger inside the pure_mm strategy, like ping_pong.

**Comment by bitphage** [comment]
@phbrgnomo is there a typo in section "When a ask order is filled:", should be

`inventory_cost = inventory_cost - (order_amount * ask_price)` ?

**Comment by mifeng** [comment]
Rather than a new parameter, @phbrgnomo will work with engineering to create a sample script that adjusts spreads based on the user's inventory position, similar to how https://github.com/CoinAlpha/hummingbot/blob/master/scripts/spreads_adjusted_on_volatility_script.py changes spreads based on volatility.

**Comment by bitphage** [comment]
It's interesting how this simple strategy behaves when profits are realized: with every profit trade inventory cost is decreased, which means that upper bound for buy orders is decreased too.

Simple example: 
1. Buy 1 BTC at 5000 USD
1. Price goes up and you're sell 0.45 BTC at 10000
1. Inventory cost now is `5000 - 0.45 * 10000 = 500`
1. The strategy is now limited to place buy orders not higher that 500 USD/BTC

**Comment by Nullably** [comment]
@bitphage 
The new ref price (inventory price) in your example is actually 909 USD (500 / 0.55), but I see your point. 
If you want to crater for partially filled situation, you will also have to consider:
* Your second order filled amount is 2 BTC (your first order filled is partial)
* Your second order filled at lower price (with both lower and higher order amount than the first).

**Comment by jason-hb** [comment]
Per meeting on 1/25:

Jack to review
Clinton to QA
Paulo to document

**Comment by phbrgnomo** [comment]
@bitphage i though a bit and figured out what should happen when a ask order is filled:

these are the calculations to be executed on this sequence
1 - calculate how much must be reduced from the inventory cost
`transaction_cost = (order_amount/(balance+order_amount)) * inv_cost`
2 - Reduce the inventory cost
inv_cost = inv_cost - (transaction_cost)

with that, when an ask order is filled, the impact of the next buy order (that will cause the `inventory_price` to change) will be bigger because the total inventory cost has went down.

@RC-13 (Clinton) is testing the PR to include it on the next release. Check with him about this code change.

**Comment by jason-hb** [comment]
@bitphage Can you please review Paulo's comment. We have code freeze on 2/4 and would like to deliver this feature fully complete if time allows.

Thanks,
Jason

**Comment by bitphage** [comment]
@phbrgnomo the code is written in a bit different way, so the this formula is not applicable here, but I think I got the idea: sell orders aren't moving `inventory_price`. This is already implemented. Would be nice to get a code review from the client team again.

**Comment by jason-hb** [comment]
Keith to review

**Comment by tronder88** [comment]
I see case is closed, but did @phbrgnomo's issue make it through the testing?

I have been testing this inventory price control in live bot for a week, and current version 0.36 does not solve this issue. 
The new buys are not moving the average inventory cost enough to have the spread within acceptable limits.



> @bitphage i though a bit and figured out what should happen when a ask order is filled:
> 
> these are the calculations to be executed on this sequence
> 1 - calculate how much must be reduced from the inventory cost
> `transaction_cost = (order_amount/(balance+order_amount)) * inv_cost`
> 2 - Reduce the inventory cost
> `inv_cost = inv_cost - (transaction_cost)`
> 
> with that, when an ask order is filled, the impact of the next buy order (that will cause the `inventory_price` to change) will be bigger because the total inventory cost has went down.
> 
> @RC-13 (Clinton) is testing the PR to include it on the next release. Check with him about this code change.
> 
> Edit: `(balance+order_amount)` is the balance before the sell were filled.
