### ISSUE TITLE
[Feature] Submit lower order amount on low balance.

### ISSUE THREAD

**Issue by Nullably** [CoinAlpha/hummingbot#2321]
**Why**
I set up my bot to run on PMM COTI-BTC with order amount of 1500, and my COTI balance is 1500.
After the bot starts making market, the sell order got partially filled, say 200, then the bot stops placing sell orders, as the available balance (1300) is now less than the order amount setting. And the bot also misses on buy orders as my BTC balance is less than what it needs to place 1500 COTI buy order.

**Feature Suggestion**
A new default bot behaviour for when if the available balance is not enough for the order, the bot recalculates new lesser order amount based on available balance after balance limit applied (if any). For sell orders, this is the base token available balance, for buy orders this is the quote token available balance. Note that this does not permanently change `order_amount`.

**Comment by PtrckM** [comment]
similar https://github.com/CoinAlpha/hummingbot/issues/2138

**Comment by Nullably** [comment]
We've started working on this on our last code jam session (as an easy example for a 1.5 hours coding). 
The main functionality is done, what left are:
- unit testing
- integration testing.
https://github.com/CoinAlpha/hummingbot/tree/feat/place_lower_order_amount

**Comment by dennisocana** [comment]
As discussed, this will no longer be a configurable parameter for pure market making. It will be a fix for Hummingbot to place an order size of the remaining available balance if the balance is less than the `order_amount`.
