### ISSUE TITLE
[Doc] Connector tutorial rework

### ISSUE THREAD

**Issue by thomasyit** [CoinAlpha/hummingbot#2337]
**Feedback from Doon and Patrick:**

Doon:
 - breakup the task4 into two topics, Hummingbot configuration, and, testing and debugging.
- add table description to the .py files for the hummingbot configuration
- add testing reference for each task to the testing and debugging topics
- highlight binance as an example for the devs

Patrick:
- Have a flowchart and code examples at the end of each task to add more clarity.
------------------------------------------------------------------------------------------------------------------

**Tasks**

- Patrick to work on flowchart and code examples
   - Task 1
   - Task 2
   - Task 3
- Thomas to work on Doon suggestions  
-------------------------------------------------------------------------------------------------------------------

**Comment by mifeng** [comment]
@thomasyit Will part of this story be completed as of the v0.32 release on Monday? 

If so, please create a new story for the remaining work and mark it as v0.33 release. For this story, please link the PR associated with the changes.

If not, please mark this story as v0.33 release and describe what is needed for engineering to take over from Patrick.

**Comment by thomasyit** [comment]
@mifeng will complete my part and submit PR later. For patrick part, will create a new issue
