### ISSUE TITLE
[BUG] Kucoin connector takes a while to get ready

### ISSUE THREAD

**Issue by Nullably** [CoinAlpha/hummingbot#2348]
**Describe the bug**
Occasionally, Kucoin connector takes a long while to get ready, in my case, about a minute.

**Steps To Reproduce**
- Create a pure market making strategy on Kucoin exchange.
- Start the strategy
- As this happens occasionally, you might have to stop and restart a few times.

![image](https://user-images.githubusercontent.com/37262506/93664227-cfb96800-fa9f-11ea-9a56-e68b381828e3.png)

Note, at 17:36:27, the bot took about a minute before it starts market making.

**Comment by mifeng** [comment]
@dennisocana @vic-en 
Can you take a fresh look at this issue? @martinkou said during Asia standup that it doesn't seem to fix the issue. Patrick is no longer with us.

**Comment by mifeng** [comment]
I think I've figured out the problem (at least for me). Kucoin now has a "main account" and "trading account." You have to manually move your assets from Main to Trading in order for you to make a trade. It's not obvious, even using the KuCoin GUI, that you have to do this before you can make a trade.
![Screen Shot 2020-09-23 at 3.39.52 PM.png](https://images.zenhubusercontent.com/545072957c6ccc6277a5c098/0173ceb4-6b3b-4833-8514-0658b540a1c8)

After I moved some of my assets to Trading, I was able to run the bot (`development`) successfully on KuCoin.
![Screen Shot 2020-09-23 at 3.39.26 PM.png](https://images.zenhubusercontent.com/545072957c6ccc6277a5c098/815576ab-20f4-4464-8233-b12fdbb01522)

@martinkou can you check this with your KuCoin bot?
