### ISSUE TITLE
[Testing] Create QA testing guidelines for protocol connectors

### ISSUE THREAD

**Issue by sdgoh** [CoinAlpha/hummingbot#2359]
Create testing guidelines for dev and QA team for the new protocol connectors - Balancer and Terra. Similar to the QA testing guidelines that Dennis has for exchange connectors, we should create one for these protocol connectors for the QA team to look for when testing.

**Comment by sdgoh** [comment]
Gateway QA Testing  Notion document created & share with QA

**Comment by mifeng** [comment]
Most issues are Windows Home-related, related to Docker Toolbox
