### ISSUE TITLE
[Feature] Celo Gateway API

### ISSUE THREAD

**Issue by sdgoh** [CoinAlpha/hummingbot#2362]
**Feature Suggestion**

**Impact**

**Additional context**

**Comment by Nullably** [comment]
These are expected APIs (requests and responses) for Hummingbot connector.
- `get_quote_price(trading_pair: str, is_buy: bool, amount: Decimal)` quote_price Returns quote price (exchange rate)
- `get_order_price(trading_pair: str, is_buy: bool, amount: Decimal)` Returns price used for order submission if this is different to get_quote_price above
- `unlock_account(address: str, password: str)` or some way to authenticate user to the network
- `get_balances()` - Returns a list of coins with their total amount and locked amount
- `buy(trading_pair: str, amount: Decimal, price: Decimal)`
- `sell(trading_pair: str, amount: Decimal, price: Decimal)`
- `check_network_status()` (For celo this is node:synced command) Returns True if network is up and connection is good

All APIs above should handle errors the same way, e.g. return {"error": "Reason for error or error message."}, if errors occur.

**Comment by mifeng** [comment]
still need to update the Celo functions in gateway-api

**Comment by mifeng** [comment]
Mike will update Celo team upon v0.33.0 release

**Comment by phbrgnomo** [comment]
Moving this to `gateway-v2` for discussion:

[Issue #7](https://github.com/CoinAlpha/gateway-v2/issues/7)
