### ISSUE TITLE
[Doc] Minimum order size workaround update

### ISSUE THREAD

**Issue by thomasyit** [CoinAlpha/hummingbot#2374]
Explains how Hummingbot calculates the default minimum required value for order_amount and how they can override it if they want.

https://github.com/CoinAlpha/hummingbot/commit/fafb5570e7f7e369b924eff88128973c1f5c8dc4#diff-3051ad0042ac2fb0bb937066c574a88c

Will add a note in strategies/pure-market-making/ as best practice, and then in the troubleshooting guide of there is none.

**Comment by dennisocana** [comment]
This PR may help with better understanding how the feature works https://github.com/CoinAlpha/hummingbot/pull/1432. We also use it for the `order_amount` prompt with cross exchange strategy, I suggest a page for this feat instead of just pure market making.
