### ISSUE TITLE
[Feature] Update Binance connector to support multiple domains.

### ISSUE THREAD

**Issue by Nullably** [CoinAlpha/hummingbot#2378]
**Feature Suggestion**
Binance offers their services specifically to certain countries, e.g Binance.US. From the APIs prospective, this is simply changing the domain name of the URL, e.g. from binance.com to binance.us, the formats of requests and responses remain the same. 
What we can do to make the existing binance connector able to support other domains
- Upgrade `python-binance` library to 0.7.5 version
- Create a new config paramemter - `binance_domain` in global config map. 
- Update `fetch_trading_pairs` and other places where binance API url is used.

https://github.com/CoinAlpha/hummingbot/issues/1518

**Considerations**
- Do we get broker commission for binance exchange in other domains?
- Should the UI display `binance_{domain}` e.g. `binance_us` when connecting to sub domain?
- Should HB be able to connect to multiple domains of binance at the same time? 
- Should HB be able store multiple sets of API key and secret for those domains?

**Comment by mifeng** [comment]
See below for considerations for how to use the Binance connector code for other Binance exchanges.

> Do we get broker commission for binance exchange in other domains?
Yes, there will be a different commission ID for various Binance exchanges, so we should refactor how the commission ID logic works in the Binance connector when making this change.

> Should the UI display binance_{domain} e.g. binance_us when connecting to sub domain?
Yes, it should appear to the user as if they are connecting to a new exchange

> Should HB be able to connect to multiple domains of binance at the same time?
Yes a user should be able to connect to Binance.com and Binance.US simultaneously. Users should also be able to Set different fee overrides for Binance.com and Binance.US.

> Should HB be able store multiple sets of API key and secret for those domains?
No, a user should only have a single API key/secret for each exchange. However, API/secret for Binance.US is different from Binance.US.

> Should we consider other exchanges besides Binance with a similar setup?
Yes - we will likely do something similar for OKCoin using the new OKEx connector.
