### ISSUE TITLE
[BUG] Celo CLI error: 'gold'

### ISSUE THREAD

**Issue by RC-13** [CoinAlpha/hummingbot#2388]
**Describe the bug**
When checking balance on Hummingbot that is running via source and celo account is connected, instead of seeing your actual celo balance you will get an error: `Celo CLI error: 'gold'`

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
1. Run Hummingbot via Source
2. Connect celo account
3. Run `balance` command
...

**Screenshots**
![balance-celo](https://user-images.githubusercontent.com/57189990/94323614-14c22a80-ffc9-11ea-8c88-d677f30ab4c3.PNG)

**Release version**
0.31.0

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by PtrckM** [comment]
fix on dev-0.32.0 https://github.com/CoinAlpha/hummingbot/pull/2376 https://github.com/CoinAlpha/hummingbot/pull/2320

![image](https://user-images.githubusercontent.com/54516858/94822788-9edd1980-0435-11eb-841b-5afdaa87ddcc.png)
