### ISSUE TITLE
[Feature] Taker or maker on both side.  Cross Exchange Market Making¶

### ISSUE THREAD

**Issue by ethanhe1983** [CoinAlpha/hummingbot#2389]
**Feature Suggestion**
 Dear admin ,Can u tell me how to make  the bot  to  file taker order or maker order  on both exchange site  with "Cross Exchange Market Making" so the bot can get more chance to make profit .
Site A taker ,Site B taker. Priority first
Site A maker ,site b taker 
site A taker. site b maker
site A maker   
site b maker  
more change to Arbitrage 

**Impact**
// A succinct description of **why you want the _desired behavior_** specified above.
The desired behavior will allow me to ...

**Additional context**

**Comment by dennisocana** [comment]
@ethanhe1983 it looks like you need support. Please create a bug report rather than a feature request, or send a message in our [Discord server](https://discord.hummingbot.io).
