### ISSUE TITLE
[Feature] Add an option for not cancel pending orders with `stop` or `exit` command

### ISSUE THREAD

**Issue by phbrgnomo** [CoinAlpha/hummingbot#2399]
**Feature Suggestion**
When `stop` command is entered, ask the user want to cancel the pending orders

`Cancel all pending orders? (Y/N)`

Since the bot also try to cancel orders on some exchanges with `start` command (It happens with Kucoin, where all orders on the book are canceled, including orders from different pairs, and not created by the bot), this interaction should also be considered

**Impact**
IT's a feature requested by a lot of users, mostly by those using `hanging_orders`

**Additional context**

**Comment by phbrgnomo** [comment]
User comment on the topic:

**Comment by PtrckM** [comment]
- feature already implemented [pause / resume](https://docs.hummingbot.io/features/pause-resume/)
- `exit --suspend` command will "pause" the strategy and exit the hummingbot client. All active orders will become hanging orders while hanging orders will stay hanging when resumed at a later time.
- To resume a "paused" strategy, import the config file and run the command `start --restore.` It will create new sets of active orders on top of the hanging orders from when it was paused.
- for more info please visit [documentation page](https://docs.hummingbot.io/features/pause-resume/).
- kindly reopen if this feature doesn't satisfy your request.
