### ISSUE TITLE
[BUG]Status and History shows incorrect exchange output

### ISSUE THREAD

**Issue by RC-13** [CoinAlpha/hummingbot#2412]
**Describe the bug**
When running cross exchange market making or arbitrage using two different exchanges in **paper trade only**, and you run `status`, instead of showing two exchange, only one exchange will be displayed as both maker and taker. This affects the history output as well.

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
1. Create a cross exchange market making strategy using 2 different exchanges. 
2. Set a very low minimum profitability to get a fill order easily.
3. Start strategy
4. Run `status` and check the displayed exchange. You will notice that the taker exchange will be set as both maker and taker.
5. If you have a fill order, run `history` and you will see as well that only one exchange is use as well.
...

**Screenshots**
![Untitled (1)](https://user-images.githubusercontent.com/57189990/94952521-b2ad7c00-0518-11eb-8baa-107b9ef86f4c.png)
![Untitled2](https://user-images.githubusercontent.com/57189990/94952536-b7723000-0518-11eb-8682-213a6a7867a8.PNG)
![Untitled](https://user-images.githubusercontent.com/57189990/94952546-b93bf380-0518-11eb-8a8a-067327786456.png)

**Release version**
0.32.0

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by lirwin3007** [comment]
I am encountering this error too - is there a workaround?

**Comment by RC-13** [comment]
Fix on development branch [v0.35.0]
