### ISSUE TITLE
[Feature] Add Volume to Dockerfile.

### ISSUE THREAD

**Issue by MicahZoltu** [CoinAlpha/hummingbot#242]
**Feature Suggestion**
The Dockerfile currently doesn't have any [`VOLUME`](https://docs.docker.com/engine/reference/builder/#volume) references, yet according to the documentation there are two mount points.  Consider adding VOLUME lines to the Dockerfile so users looking at the Dockerfile can easily identify what volume mounts they need.

**Impact**
When looking at a dockerfile, it is valuable to be able to easily identify what parameters are needed to correctly run the resulting Dockerimage.  VOLUME lines provide a mechanism for documenting this in a standardized way.

**Comment by carlolm** [comment]
Thanks @MicahZoltu , have added this here:
https://github.com/CoinAlpha/hummingbot/pull/278
