### ISSUE TITLE
[Feature] Use Docker Hub's automated build system.

### ISSUE THREAD

**Issue by MicahZoltu** [CoinAlpha/hummingbot#243]
**Feature Suggestion**
Docker Hub has an automated build system that can be configured to build from a GitHub repository anytime a particular branch is updated, or a tag is created.  Consider using Docker Hub's automated build system rather than your own CI system for publishing new images.

**Impact**
Automated builds give confidence to the user that the published Dockerimage is the same as the code in the GitHub repository.  When images are pushed as part of other CI systems, the user cannot be confident that the code in the repository matches the code in the docker image.

**Comment by carlolm** [comment]
Thanks for the suggestion @MicahZoltu .
We have now implemented this: https://hub.docker.com/r/coinalpha/hummingbot/builds
