### ISSUE TITLE
[BUG] Missing exchange: Bamboo_relay

### ISSUE THREAD

**Issue by RC-13** [CoinAlpha/hummingbot#2431]
**Describe the bug**
Bamboo relay is no longer showing on the list of exchange, importing an existing strategy that uses Bamboo relay will result to the following error:
```
2020-10-06 09:13:43,265 - 6855 - root - ERROR - Invalid value bamboo_relay for config variable exchange
```
**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
1. Update development branch to latest commit
2. Start Hummingbot from development branch
3. Create a pure market making strategy
4. When asked to enter exchange/connector, press tab to show current list

...

**Screenshots**
List of available exchange, missing Bamboo_relay
![exchange](https://user-images.githubusercontent.com/57189990/95148465-f1ac2d80-07b5-11eb-9998-dea4e2ae1b40.png)

After importing a strategy that uses Bamboo_relay:
![exchange1](https://user-images.githubusercontent.com/57189990/95148498-07215780-07b6-11eb-8580-252fe53dc008.png)

**Release version**
0.32.0

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by TheHolyRoger** [comment]
@RC-13 PR to fix https://github.com/CoinAlpha/hummingbot/pull/2433
