### ISSUE TITLE
[Feature] Add option to use testnet with Binance Perpetuals connector

### ISSUE THREAD

**Issue by vic-en** [CoinAlpha/hummingbot#2441]
**Feature Suggestion**
Paper trading mode doesn't work for derivatives exchanges due to liquidation risk which only presents when you have a position, so we need to implement a sandbox/testnet mode. This is similar to what we're doing for Binance.US.

**To-do:**
- Add a configurable option to use Binance's perpetual testnet(https://binance-docs.github.io/apidocs/testnet/en/#change-log).
- Add logic in Binance perpetual connector to switch base endpoint according the set value of the configurable option.

**Comment by PtrckM** [comment]
- feature already impletemented as of [0.33.0](https://docs.hummingbot.io/release-notes/0.33.0/#-connectors) PR https://github.com/CoinAlpha/hummingbot/pull/2549
- for more info visit https://docs.hummingbot.io/strategies/perpetual-market-making/#how-to-start

![image](https://user-images.githubusercontent.com/54516858/102586860-d65e8680-4145-11eb-9c40-68d589bb5f16.png)
