### ISSUE TITLE
[BUG] Unable to connect to any exchange using Hummingbot binary on Mac

### ISSUE THREAD

**Issue by RC-13** [CoinAlpha/hummingbot#2444]
**Describe the bug**
Discord user **king** reported an issue wherein he is unable to connect to crypto.com exchange and Hummingbot throws an error:
```
04:02:58 - async_utils - Unhandled error in background task: list index out of range (See log file for stack trace dump)
```
Confirmed that this happens when connecting to other exchange as well using the binary version on Mac.

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
1. Download the latest binary installer for mac
2. Install Hummingbot and run the application
3. Connect any exchange using `connect` command
...

**Screenshots**
![unknown](https://user-images.githubusercontent.com/57189990/95259127-4ce32c00-0859-11eb-8238-2f4eb1c96eb2.png)

**Release version**
0.32.0

**Attachments**
[logs_hummingbot.log](https://github.com/CoinAlpha/hummingbot/files/5336712/logs_hummingbot.log)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by TheHolyRoger** [comment]
Misconfiguration issue - user is using 0.30.0 code mixed with 0.32 somehow - bad merge on a personal fork maybe?

See code line in 0.30.0:
https://github.com/CoinAlpha/hummingbot/blob/v0.30.0/hummingbot/client/command/connect_command.py#L37

**Comment by TheHolyRoger** [comment]
Ah I guess it's an issue with the dmg package building from cache...

**Comment by softbear** [comment]
I'm a Mac user seeing the exact error. I previously installed 0.31.0 and updated to 0.32.0 with the dmg installer, and none of the connectors are working.

**Comment by RC-13** [comment]
@softbear Sorry about this, our dev team are now aware about this issue, for the mean time, you can opt to use the older version. You can download version 0.31.0 from our website or if you happen to have a cloud server, you can install Hummingbot via cloud: [Cloud server guide](https://docs.hummingbot.io/installation/cloud/), and [Docker installation step](https://docs.hummingbot.io/installation/docker/linux/)

**Comment by Nullably** [comment]
This bug affects only MAC binary version.
The problem is in `def connector_keys()` in `hummingbot/client/config/global_config_map.py` which uses relative path.

The fix is 
```python
def connector_keys():
    all_keys = {}
    for conector_type, connectors in ALL_CONNECTORS.items():
        for connector in connectors:
            try:
                module_path = f"hummingbot.connector.{conector_type}.{connector}.{connector}_utils"
                all_keys.update(getattr(importlib.import_module(module_path), "KEYS"))
            except Exception:
                continue
    return all_keys
```

I created a hotfix from `master` branch and uploaded the new 0.32.0 binary for MAC (however it will be take effect in about 24 hours - AWS keeps cache of the old one).

I will apply the fix to `development` st. the new coming release will have this fixed.
