### ISSUE TITLE
[Feature] Implement command to merge hanging orders

### ISSUE THREAD

**Issue by phbrgnomo** [CoinAlpha/hummingbot#2447]
**Feature Suggestion**
Implement the command `merge_hanging_orders` that will cancel all active hanging orders and create a new order with the size equal to all the hanging orders that were canceled and the price equals to the weighted average of these orders:

Example:

After a while there will be the following hanging orders:

| Price          |    Size   |
| --------|--------| 
|110  | 1000 |
|120 | 1000| 

After using `merge_hanging_orders` command, all the above orders would be cancelled and a new order tagged as hanging would be created:

Size = 1000+1000
Price = ( (1000 * 110) + (1000 * 120) ) / Size = 115

When this new order is filled, the final result will be the same as if both hanging orders were filled.

**Impact**
Merging hanging orders bring old orders that are too far from the market price (and with a lower probability to be filled) closer to it.

This means that the price will have to move back to the average price of the hanging orders, instead of the price of the highest hanging order to turn the trading session profitable

In the example above, the price would only have to reach 115 instead of 120 for all operations be closed with profit.

**Additional context**

**Comment by TradeClaw** [comment]
This is a take profit setting taking inventory cost into account, it's also a feature request somewhere so once the inventory cost is implemented, this should be a piece of cake to implement
