### ISSUE TITLE
[BUG] Inconsistent order creation when using various price_type option

### ISSUE THREAD

**Issue by rxlxrxsx** [CoinAlpha/hummingbot#2459]
**Describe the bug**

Inconsistent order creation when using various price_type option. So far it happens when you use ``last_price``, ``last_own_trade_price`` and ``best_bid`` as your ``price_type`` and ``hanging_orders`` is enabled.

**Steps To Reproduce**

Here are the steps to reproduce the issue (see attachments in the section below):
1. Run a pure market making bot, enable ``hanging_orders`` and choose your ``price_type`` to either ``last_price``, ``last_own_trade_price`` and ``best_bid``.
2. Notice that sometimes it doesn't create orders on the other side even with enough balance.

**Screenshots**

![image](https://user-images.githubusercontent.com/64377055/95545405-5d99ca80-0a30-11eb-8427-aed9de3e5476.png)

**Release version**
dev-0.33.0

**Attachments**

[logs_zil-btc.log](https://github.com/CoinAlpha/hummingbot/files/5352624/logs_zil-btc.log)

**Comment by dennisocana** [comment]
- In the logs it shows in timestamp `020-10-09 07:30:15` orders on both sides were created.
- Then in the next cycle at `2020-10-09 07:30:46` (boxed in red) it only created a buy order.
- Afterwards it returned to creating a buy and a sell order at `2020-10-09 07:31:17`.

<img width="1792" alt="Screen Shot 2020-10-15 at 10 54 34 PM" src="https://user-images.githubusercontent.com/50150287/96147379-d968ab00-0f39-11eb-81c4-2e0df081a7fc.png">

@rxlxrxsx do you have the config file? Have we also reproduced this behavior to confirm?

**Comment by RC-13** [comment]
Just tried to re-test this behavior again, and I can't seems to replicate it anymore. Tried using `last_price`, `best_bid`, and `best_ask` using the latest development commit.
```
branch: development
commit: 6f883227d243a5fa71d76752df52b02334a94fed
Date:   Fri Oct 16 17:25:01 2020 +0800
```

**Comment by dennisocana** [comment]
Thanks @RC-13 feel free to re-open if we're able to reproduce the behavior and pinpoint the exact configs or scenario that causes the issue.
