### ISSUE TITLE
[BUG] crypto.com connector issue - Windows 0.32.0

### ISSUE THREAD

**Issue by softbear** [CoinAlpha/hummingbot#2461]
**Describe the bug**
After entering keys for crypto.com, the following error message appears:

> Failed connections:                                                                                                   |
>     crypto_com: Error fetching data from https://api.crypto.com/v2/private/get-account-summary. HTTP status is 401.   |
>  Message: {'id': XXXXXXXXXXXX, 'method': 'private/get-account-summary', 'code': 10002, 'message': 'UNAUTHORIZED   |
> '}

Keys for another exchange, like Bittrex, works fine.

**Steps To Reproduce**

Here are the steps to reproduce the issue:
1. install hummingbot with windows installer v0.32.0
2. add crypto.com keys through the connect command

**Screenshots**
![image](https://user-images.githubusercontent.com/16596457/95590230-ccb4f600-0a13-11eb-868a-44fc2f8dedee.png)

**Release version**
0.32.0

**Optional: your discord username:**

**Comment by nico-coinalpha** [comment]
Replicated with same error

![image](https://user-images.githubusercontent.com/71703120/95594527-a5930e80-0a7d-11eb-868e-f231367477cf.png)

**Comment by dennisocana** [comment]
Works fine for me on the same environment and installation method.

![image](https://user-images.githubusercontent.com/50150287/95644286-37cffc80-0ae8-11eb-98dc-8fc39f8db5de.png)

@softbear we'll have someone from support reach out to to help figure out the issue you're getting. You can send a message in our Discord channel or comment here your Discord username.

**Comment by softbear** [comment]
@nico-coinalpha enabling the "Ctrl+Shft+V" as paste in my command properties did the fix like you said. My previous command setting did not have that option checked. Thanks for the quick fix!
