### ISSUE TITLE
[BUG] Both XEMM and arbitrage unit test cases failed

### ISSUE THREAD

**Issue by martinkou** [CoinAlpha/hummingbot#247]
**Describe the bug**
The strategy unit test cases we have are failing.

**Steps To Reproduce**
- Install and compile the dev/0.7.0 branch as usual
- Run any strategy unit tests

This is likely caused by @yzhang1994 refactoring yesterday.

**Comment by martinkou** [comment]
I've fixed the XEMM strategy unit test last weekend. But arbitrage strategy unit test is still broken.

**Comment by carlolm** [comment]
Tests are now passing.
