### ISSUE TITLE
[BUG] Error submitting orders on Loopring but pushes through on the exchange

### ISSUE THREAD

**Issue by rxlxrxsx** [CoinAlpha/hummingbot#2483]
**Describe the bug**

Error submitting orders on Loopring but pushes through on the exchange and eventually gets stuck. This immediately happens after you start the bot.

```
2020-10-15 16:22:32,017 - 11284 - hummingbot.connector.exchange.loopring.loopring_exchange - WARNING - Error submitting 
BUY LIMIT_MAKER order to Loopring for 0.0500 ETH-USDT at 373.55.
2020-10-15 16:22:32,017 - 11284 - hummingbot.connector.exchange.loopring.loopring_exchange - INFO - processing
```

**Steps To Reproduce**

1. Run a pure market making bot on Loopring
2. After entering the ``start`` command, notice that the bot will tell that it failed to submit an order to Loopring
3. Check on the exchange and you'll see that the order is successfully placed however it'll get stuck and will not get cancelled as the bot recognized it earlier as a failed submission of order.

**Screenshots**

![image](https://user-images.githubusercontent.com/64377055/96096827-d7cfc080-0f02-11eb-8431-f2861c18bcd3.png)
![image](https://user-images.githubusercontent.com/64377055/96096881-e74f0980-0f02-11eb-9e7d-53eba2a8c458.png)

**Release version**
version-0.32.0

**Attachments**

[loopring-test.log](https://github.com/CoinAlpha/hummingbot/files/5383400/loopring-test.log)

**Comment by mborraccia** [comment]
This was due to a Loopring api change that has been fixed, and so should no longer be a problem.

**Comment by rxlxrxsx** [comment]
Closing as the issue is already resolved.
