### ISSUE TITLE
[Feature] Add an easier way for scripts to pull the balance of the assets being traded on the bot

### ISSUE THREAD

**Issue by phbrgnomo** [CoinAlpha/hummingbot#2489]
**Feature Suggestion**
Add to `script_base.py` a function to allow scripts to easily pull the balance of the assets being traded

**Impact**
Balance information is useful to implement a lot of possible scripts, including complementary risk management strategies.

**Additional context**
As working on issue [#2277](https://github.com/CoinAlpha/hummingbot/issues/2277), I found out that there is no easy way to read what is the balance from the assets being traded.

@vic-en suggested using this code:
`def __init__(self):
        super().__init__()
        self.base_asset = None
        self.quote_asset = None
        self.base_balance = Decimal("0")
        self.quote_balance = Decimal("0")

    def on_tick(self):
        self.base_balance = self.all_total_balances["exchange"].get(self.base_asset, self.base_balance)
        self.quote_balance = self.all_total_balances["exchange"].get(self.quote_asset, self.quote_balance)
        # your calculations can follow
        # you may also want to do a  try and catch for a possible zero division error, just in case it happens
   
    def on_buy_order_completed(self, event: BuyOrderCompletedEvent):
        if self.base_asset is None:
            self.base_asset = event.base_asset
            self.quote_asset = event.quote_asset

    def on_sell_order_completed(self, event: SellOrderCompletedEvent):
        if self.base_asset is None:
            self.base_asset = event.base_asset
            self.quote_asset = event.quote_asset`

The issue is that for the script to write the balances to be used on calculations, it needs to first execute a buy or sell order.

Using `event.base_asset` or `event.quote_asset` on the function `on_tick(self)` doesn't work because there is no event associated with this function, as mentioned in the error:
![Captura de tela 2020-10-16 15.55.17.png](https://images.zenhubusercontent.com/5f64254ca13ff3717cc3a0c5/41289623-34e2-4c61-a262-ed7cdc0b7a28)

**Comment by Nullably** [comment]
I summarised changes for `scripts` in #2492
