### ISSUE TITLE
[Feature] Remove default "start" command after importing or creating a strategy

### ISSUE THREAD

**Issue by phbrgnomo** [CoinAlpha/hummingbot#2496]
**Feature Suggestion**
Title

**Impact**
Usually, after creating a strategy, the user needs to check and change some extra configuration on the strategy before starting the bot.

When importing, the user usually wants to start the bot right away.

**Additional context**

**Comment by Nullably** [comment]
I think we should remove the default `start` after `create` or `import`. Generally I either `config` or `start` after I create or import a strategy and if the default is not what I want, I have to delete it and enter a new one and it's quite annoying.

**Comment by dennisocana** [comment]
As discussed, the commands executed after creating or importing a strategy varies depending on the user i.e. some prefer to check their balances first before starting, some runs the `config` command again to make sure they have the right settings (or they want to reconfigure some advanced params).

The desired behavior is to just delete the default command instead. Updating the ticket to reflect this.
