### ISSUE TITLE
[BUG] Unexpected error running clock tick when running arbitrage strategy

### ISSUE THREAD

**Issue by rxlxrxsx** [CoinAlpha/hummingbot#2499]
**Describe the bug**

Getting an ``Unexpected error running clock tick`` when running arbitrage strategy. This immediately happens after starting the strategy. The current workaround I found is to restart the strategy, so far I didn't encounter the error again after restarting. Also, based on testing it only immediately happens when setting the ``min_profitability`` to a negative value.

```
Traceback (most recent call last):
  File "hummingbot/core/clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
    child_iterator.c_tick(self._current_tick)
  File "hummingbot/strategy/arbitrage/arbitrage.pyx", line 190, in hummingbot.strategy.arbitrage.arbitrage.ArbitrageStrategy.c_tick
    self.c_process_market_pair(market_pair)
  File "hummingbot/strategy/arbitrage/arbitrage.pyx", line 325, in hummingbot.strategy.arbitrage.arbitrage.ArbitrageStrategy.c_process_market_pair
    self.c_process_market_pair_inner(market_pair.second, market_pair.first)
  File "hummingbot/strategy/arbitrage/arbitrage.pyx", line 343, in hummingbot.strategy.arbitrage.arbitrage.ArbitrageStrategy.c_process_market_pair_inner
    best_amount, best_profitability, buy_price, sell_price = self.c_find_best_profitable_amount(
  File "hummingbot/strategy/arbitrage/arbitrage.pyx", line 516, in hummingbot.strategy.arbitrage.arbitrage.ArbitrageStrategy.c_find_best_profitable_amount
    return best_profitable_order_amount, best_profitable_order_profitability, bid_price, ask_price
UnboundLocalError: local variable 'bid_price' referenced before assignment
```

**Steps To Reproduce**

1. Run an arbitrage strategy and set the ``min_profitability`` to -1.
2. Notice that after starting it immediately throws an ``Unexpected error running clock tick``.
3. Try to restart the strategy and see that it'll now work properly.

**Screenshots**

The error immediately happens after starting strategy
![clock tick](https://user-images.githubusercontent.com/64377055/96825630-2e3d8180-1464-11eb-931d-96a6117ec5fe.PNG)

After restarting the strategy notice that it's now working properly, I was also able to produce an arbitrage opportunity during the duration of this session.
![arb opportunity](https://user-images.githubusercontent.com/64377055/96825764-75c40d80-1464-11eb-8798-17b1e66c4340.PNG)
![history](https://user-images.githubusercontent.com/64377055/96825777-7c528500-1464-11eb-99ab-420e9e97d2f2.PNG)

Configuration
![image](https://user-images.githubusercontent.com/64377055/96826089-41048600-1465-11eb-808d-9aab4e7a2d6b.png)

**Release version**

version-0.32.0

**Attachments**

[logs_conf_arb_1.log](https://github.com/CoinAlpha/hummingbot/files/5420138/logs_conf_arb_1.log)

**Comment by TradeClaw** [comment]
Got the same on 0.33.1 running arbi between Binance spot pairs on different stable coins

**Comment by rxlxrxsx** [comment]
Closing as behavior can no longer be replicated on current version (0.35.0)

**Comment by TheHolyRoger** [comment]
This bug has reappeared for me in 0.36.0 when there's no profitable orders, but I've already found the fix and included it in this PR: https://github.com/CoinAlpha/hummingbot/pull/2893
