### ISSUE TITLE
Add gas price API to gateway-api

### ISSUE THREAD

**Issue by mifeng** [CoinAlpha/hummingbot#2505]
Add a gas price API to `gateway-api` to enable dynamic gas price lookups, such as:

* https://etherscan.io/apis#gastracker
* https://docs.ethgasstation.info/

**Comment by mifeng** [comment]
To calculate Ethereum gas price dynamically, we should add support for the ETHGasStation API. To create a ETHGasStation API key, sign up at https://data.defipulse.com and generate. 

Request:
GET `https://data-api.defipulse.com/api/v1/egs/api/ethgasAPI.json?api-key=API_KEY`

Response:
```
fast: 190,
fastest: 199,
safeLow: 147,
average: 147,
block_time: 12.903225806451612,
blockNum: 11128631,
speed: 0.8992295722638604,
safeLowWait: 1.3,
avgWait: 1.3,
fastWait: 0.5,
fastestWait: 0.4,
gasPriceRange: {
5: 215,
7: 215,
9: 215,
19: 215,
29: 215,
39: 215,
49: 215,
59: 215,
69: 215,
79: 215,
89: 215,
99: 215,
109: 215,
119: 215,
129: 215,
139: 215,
147: 1.3,
149: 1.3,
159: 0.8,
169: 0.6,
179: 0.5,
189: 0.5,
190: 0.5,
199: 0.4
```

* Since this affects trade prices, I think we should build this into the Hummingbot client as another option to set the price price
* I think we should introduce 4 new global variables: 1) `manual_gas_price` (int), 2) `ethgasstation_api_key` (string), 3) `ethgasstation_gas_enabled` (bool) 3) `ethgasstation_gas_level` (fast, fastest, safeLow, average)
* By default, use the manual_gas_price setting. If we need a default value, I suggest 50
* If `ethgasstation_gas_enabled` is true and  both `ethgasstation_api_key` and `ethgasstation_gas_level` are not null, then the gas price that corresponds to the `ethgasstation_gas_level` in the AP response is used
* Since gas is price * gas used by the transaction, we may also need to assume a default value for gas used by a transaction. If so, I suggest 120000.
* (future) Since gas optimization is a big part of Ethereum trading, I think we will likely make this more sophisticated and connect to external modules. It would be better to build this out in `gateway-api` rather than the client since these external modules are in JS. A better long-term solution would have the client read the gas price and limit from `gateway-api`, so that all the Ethereum gas logic is contained in `gateway-api`.

**Comment by Nullably** [comment]
https://data.defipulse.com has 2000 monthly API call limits, which is about once every 22 minutes (free trial plan). 
Would this be sufficient?

**Comment by mifeng** [comment]
@Nullably As mentioned in client squad planning, I think we should add another variable `ethgasstation_refresh_time` that defines how often to check the API in seconds (default = 1800), which allows users who pay for ETHGastStation to use a lower refresh time.
