### ISSUE TITLE
[BUG] [dev/0.7.0] Hummingbot hanging when API Key is invalid - docker based installation

### ISSUE THREAD

**Issue by vkapsIT** [CoinAlpha/hummingbot#251]
**Describe the bug**

BUG] [dev/0.7.0] - When the coinbase API key was entered incorrectly, the HB hangs

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):

1. Delete the existing container and image using docker commands
 - docker rm my-hummingbot
 - docer image rm coinalpha/hummingbot:development

2. Pull the latest image from the source
-  docker run -it \
--name my-hummingbot \
-v "$PWD"/conf/:/conf/ \
-v "$PWD"/logs/:/logs/ \
coinalpha/hummingbot:development 

3. docker start my-hummingbot && docker attach my-hummingbot

4.  Set up your configuration file with these parameters: ...

4.1. maker exchange - ddex
4.2. taker exchnage - coinbase-pro
4.3. coinbase API key - enter some random invalid key
4.4. rest all configuration is default (metamask key was imported)

5 . Start the trading using start command after configuration is done

Now it will give you error: message: invalid API Key

6. Now even if you try multiple time to stop or exit, it will not stop/exit, you will have to force kill the bot using kill 

**Screenshots**
// If applicable, add screenshots to help explain your problem.

**Release version**
dev/0.7.0

**Attachments**
Attaching the log file and conf file
[hummingbot_logs_2019-05-19-14-46-11.log](https://github.com/CoinAlpha/hummingbot/files/3195235/hummingbot_logs_2019-05-19-14-46-11.log)

[conf_cross_exchange_market_making_strategy_0.yml.txt](https://github.com/CoinAlpha/hummingbot/files/3195242/conf_cross_exchange_market_making_strategy_0.yml.txt)
[conf_global.yml.txt](https://github.com/CoinAlpha/hummingbot/files/3195243/conf_global.yml.txt)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**
Sudesh Agrawal

**Comment by mifeng** [comment]
This bug was fixed in v0.8.0
