### ISSUE TITLE
[BUG] Paper trading balance changes due to trading do not persist

### ISSUE THREAD

**Issue by zappra** [CoinAlpha/hummingbot#2511]
**Describe the bug**

When stopping/starting a strategy in paper trading mode, balance changes due to trading do not persist

**Steps To Reproduce**

1. Configure paper trading balances MFT-ETH pair, 200000 and 1 respectively
2. Run the attached strategy
[conf_pure_mm_test2.txt](https://github.com/CoinAlpha/hummingbot/files/5434790/conf_pure_mm_test2.txt)
3. Note: strategy is deliberately configured to general sell trades only
4. Run "status" command and note balances, should be roughly 50/50 at time of writing
5. Wait a short time for some sell trades
6. Run "status" command and note balances
7. Stop the strategy, and restart it
8. Run "status" command
9. Balances are the same as at step 4, not step 6

**Release version**
// 0.32.0

**Comment by PtrckM** [comment]
can you also send some screenshots of the command `history`, `status` with the whole hummingbot client and attach the strategy logs and trade logs?

if you set paper balance to MFT 200000 and ETH 1 then you decide to stop and restart
- stopping then starting the bot again will set the paper balance back to MFT 200000 and ETH 1 

I'm running this strategy see if I'm able to replicate.

**Comment by zappra** [comment]
[trades_conf_pure_mm_test2.txt](https://github.com/CoinAlpha/hummingbot/files/5434863/trades_conf_pure_mm_test2.txt)
[logs_conf_pure_mm_test2.log.txt](https://github.com/CoinAlpha/hummingbot/files/5434868/logs_conf_pure_mm_test2.log.txt)

**Comment by Nullably** [comment]
This is a feature request rather than a bug. 
Currently, balances in paper trade mode reset after you stop a strategy or quit Hummingbot. We can make the balances persist but not sure if that what most users want.

**Comment by zappra** [comment]
The original reason for posting this is that I had experienced some issues with inventory skew when stopping/restarting a bot, and was trying to repro them with paper trading to see if it was user error or a bug. 

More generally paper trading is useful for testing strategies, scripts and the general workings of Hummingbot but only if it recreates to a reasonable degree the live trading environment. Having trades persist from one session to the next seems reasonable to me but if I'm the only one that thinks that then fair enough :)
