### ISSUE TITLE
[Feature] Expose kill switch/pause/resume functionality to scripts

### ISSUE THREAD

**Issue by zappra** [CoinAlpha/hummingbot#2514]
**Feature Suggestion**

Add additional functions to ScriptBase allowing scripts to develop more nuanced kill switch behaviour:

Stop - stop the running strategy
Pause - cancel outstanding orders and pause trading
Resume - resume trading

**Impact**

The current implementation of the kill switch is quite limited and it would be useful to expose more functionality to scripting allowing users to develop more nuanced responses to extreme trading conditions, and/or extend the kill switch parameters

For example:

Implement a take profit as well as a stop loss (currently either/or)
Pause trading if temporary price spike detected
Resume trading when volatility has returned to normal levels

**Comment by phbrgnomo** [comment]
Pause the bot with scripts can be achieved using the function `self.pmm_parameters.order_levels = 0` and resumed setting it to 1

**Comment by zappra** [comment]
A stop function would still be useful, though. I have this in my own fork, don't have the bandwidth atm to create a PR.

I use it to gracefully exit the bot if an error is detected during start up. I have some fairly well developed scripts that query the public binance API, read their own configs, etc. I also use it to bail if an error occurs during order processing, which rarely happens but nice to know its there. So actually kill switch isn't something I've needed, but scripted stop I use all the time
