### ISSUE TITLE
[BUG] Sometimes there are duplicated price items in order book

### ISSUE THREAD

**Issue by luckyCoco3418** [CoinAlpha/hummingbot#2533]
**Describe the bug**
I have implemented a new connector derived from crypto_com.
After implemented, I found a problem.
When I check the orderbook by using "orderbook" command, there are some items with duplicated price.

**Reason of the error**
This is because the orderbook snapshot has been stored with incorrect prices.
For example, let say item's price is 0.0032. But the item couldn't be stored with correct price in orderbook. I found that the item stored with price 0.0031999999 instead of 0.0032
So when diff message received, because prices are not same, the previous item couldn't be updated and the item in diff message is stored as a new item.
So there was duplicated in some prices and bot didn't work correctly sometimes.

The incorrect price was generated in c_convert_snapshot_message_to_np_arrays function of crypto_com_active_order_tracker.pyx
In the following code, when the value is stored in 'price' variable, the value is modified to the value as mentions above.

`price, amount = self.get_rates_and_quantities(order)`

**Patch**
In c_convert_snapshot_message_to_np_arrays function, I removed the declaration of 'price' variable, like below.

```
cdef tuple c_convert_snapshot_message_to_np_arrays(self, object message):
        cdef:
            # float price
            # float amount
            str order_id
            dict order_dict
```

So I fixed the error and it works fine.
If the patch is right, I'd like hummingbot team to update the code for all of us.
Thanks.

**Comment by RC-13** [comment]
I believe this concern has been addressed by pull request #2910, and has been added to v0.35.0, I'll be closing this ticket but feel free to re-open in case the issue persists on your side.
