### ISSUE TITLE
[BUG] Cosmetic bug with trade volume quantization on redesigned history output

### ISSUE THREAD

**Issue by RC-13** [CoinAlpha/hummingbot#2535]
**Describe the bug**

Currently trade volume precision is set to 6 decimal, some token with more than 6 precision may tend to have slight different result once performance is computed, for example, QASH-ETH market on liquid, Trade P&L and return are slightly off when calculated manually.
![history-output](https://user-images.githubusercontent.com/57189990/97651441-00c18b00-1a97-11eb-80ed-7f5c0047abfa.PNG)

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
1. Create a pure market making strategy and use a market pair with more than 6 precision
2. Set a thigh spread to easily get a fill
3. Once you have a filled order, run history command and try to manually compute the results of performance
using the formula from the code base
```
    perf.hold_value = (perf.start_base_bal * perf.cur_price) + perf.start_quote_bal
    perf.cur_value = (perf.cur_base_bal * perf.cur_price) + perf.cur_quote_bal
    perf.trade_pnl = perf.cur_value - perf.hold_value
    fee_paid = 0
    perf.fee_token = quote
    if trades[0].trade_fee.get("percent", None) is not None and trades[0].trade_fee["percent"] > 0:
        fee_paid = sum(t.price * t.amount * t.trade_fee["percent"] for t in trades)
    elif trades[0].trade_fee.get("flat_fees", []):
        perf.fee_token = trades[0].trade_fee["flat_fees"][0]["asset"]
        fee_paid = sum(f["amount"] for t in trades for f in t.trade_fee.get("flat_fees", []))
    perf.fee_paid = Decimal(str(fee_paid))
    perf.total_pnl = perf.trade_pnl - perf.fee_paid if perf.fee_token == quote else perf.trade_pnl
    perf.return_pct = divide(perf.total_pnl, perf.hold_value)
    return perf
```
...

**Screenshots**
// If applicable, add screenshots to help explain your problem.

**Release version**
0.33.0
```
branch: development
commit: b4b11fa913f080a2ae58885e62abd03c27aaa294
Date:   Thu Oct 29 10:24:37 2020 -0700
```

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by Nullably** [comment]
@RC-13 Can you please retest this on `development`? thanks

**Comment by RC-13** [comment]
Re-test on development [v0.33.0] and can confirm that manual calculation and history matches ( no recent change in the market/current price), issue can now be closed.:
![history calc](https://user-images.githubusercontent.com/57189990/98423555-ed7f7280-20c9-11eb-9068-2c88959d32c0.png)
