### ISSUE TITLE
[BUG] P&L and Return mismatched between history and navbar

### ISSUE THREAD

**Issue by RC-13** [CoinAlpha/hummingbot#2537]
**Describe the bug**
After getting a filled trade, when you run `history` or `history --verbose` and compare the `Total PnL` output and  and `Return %` with what's displayed on the navbar, most of the time they mismatched or output are delayed on the UI.

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
1. Create a pure market making strategy on any market pair
2. Set a tight spread to speed up getting a fill
3. Once you have filled order, run `history` or `history --verbose` then compare the result with what's displayed on the navbar/UI
...

**Screenshots**
Binance test bot:
![pnl](https://user-images.githubusercontent.com/57189990/97766666-6d4d9000-1b52-11eb-9105-7da53582c5f6.png)

Kucoin test bot:
![image](https://user-images.githubusercontent.com/57189990/97766851-578c9a80-1b53-11eb-9709-3e50eb17c001.png)

**Release version**
0.33.0
```
branch: development
commit: 90de286843f3a8b881303f6e98c537e42ce9493e 
Date:   Fri Oct 30 17:36:59 2020 +0800
```

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by vic-en** [comment]
The values from both history and nav bar may not always be thesame.
The values from the bottom nav bar should be treated as estimate due to design.

This issue can be closed.

**Comment by Nullably** [comment]
The reason Return % are not the same is the current market price used for Return % calculation moves during the time navbar reports the return and the time `history` command is run. 
To verify if this is the case, please test if Return % values are different during the period where last traded price doesn't move.

**Comment by RC-13** [comment]
Re-test and confirmed that return% on the navbar matches with the calculated return on history after the last trade. If the current price move, return on history will change but navbar will retain the calculated return base on the last price.

Base on the last trade:
![last trade](https://user-images.githubusercontent.com/57189990/98421341-1bfa4f00-20c4-11eb-9a8e-4efbd6f367f2.PNG)

After a change in the current price:
![move price](https://user-images.githubusercontent.com/57189990/98421656-ca9e8f80-20c4-11eb-81c7-663da15ed0c0.PNG)

```
branch: development
commit c074b03b82f622c10cafc59b66a4a0828bede791
Date:   Fri Nov 6 16:53:22 2020 +0800
```

**Comment by dennisocana** [comment]
Same comment in https://github.com/CoinAlpha/hummingbot/issues/2538#issuecomment-723764720, will close when we have this in the docs.

**Comment by thomasyit** [comment]
![Screenshot 2020-11-09 at 3 11 07 PM](https://user-images.githubusercontent.com/52696508/98510430-0e98bc80-229e-11eb-9b95-f430ee823369.png)
added the note at the return% in the history command section
