### ISSUE TITLE
[BUG] XEMM/ARB Incorrect P&L and return 

### ISSUE THREAD

**Issue by RC-13** [CoinAlpha/hummingbot#2538]
**Describe the bug**
Similar to #2537, after getting a filled trade using cross exchange market making or arbitrage strategy. The total P&L and return doesn't matched with what's displayed on the navbar/UI.

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
1. Create a cross exchange market making strategy
2. Set a low min_profitability to speed up getting a fill
3. Once orders are filled, run `history` or `history --verbose`
3. Compare the averaged return and return % on the navbar, the result will be different
5. Same goes with the Total P&L, compare the P&L for both exchange or even get the average, it won't match the Total P&L on the UI.
...

**Screenshots**
Test done between Huobi and Binance for ZRX-ETH market pair
![xemm3](https://user-images.githubusercontent.com/57189990/97767176-63795c00-1b55-11eb-8ff5-08d8e20bc7c3.PNG)

**Release version**
0.33.0
```
branch: development
commit: 90de286843f3a8b881303f6e98c537e42ce9493e 
Date:   Fri Oct 30 17:36:59 2020 +0800
```
**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by vic-en** [comment]
Similar to #2537, the values at the bottom nav bar should be treated as estimate.

This issue can also be closed.

**Comment by Nullably** [comment]
Also please see my comment on #2537 before closing this.

**Comment by RC-13** [comment]
Re-test and confirm return% base on the last trade.  Average return and return under the navbar match, can confirm that issue can now be closed.
![history xemm](https://user-images.githubusercontent.com/57189990/98491999-83a1cd00-2271-11eb-8656-c2bb78d5bc74.PNG)
![history xemm1](https://user-images.githubusercontent.com/57189990/98492002-86042700-2271-11eb-9028-71d570621721.PNG)

**Comment by dennisocana** [comment]
Reopening issue. Actually we should explicitly indicate first in our docs why there will be a difference on the performance in `history` output and the navbar when the price changes. This will definitely be a common question from users. Will close when the docs are ready.
