### ISSUE TITLE
[BUG] Kraken: Unexpected error in user stream listener loop

### ISSUE THREAD

**Issue by RC-13** [CoinAlpha/hummingbot#2539]
**Describe the bug**
The following error keeps occurring when using Kraken as exchange keeps every minute or few second , despite the error, bot will continue to run however, 
![image](https://user-images.githubusercontent.com/57189990/97767241-e26e9480-1b55-11eb-982c-7082e84d17f2.png)
```
2020-10-30 00:51:44,179 - 24638 - hummingbot.connector.exchange.kraken.kraken_exchange - ERROR - Unexpected error in user stream listener loop.
Traceback (most recent call last):
  File "hummingbot/connector/exchange/kraken/kraken_exchange.pyx", line 455, in hummingbot.connector.exchange.kraken.kraken_exchange.KrakenExchange._user_stream_event_listener
    event_type: str = event_message[-1]
TypeError: Expected unicode, got dict
```

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
1. Create a pure market making strategy and set Kraken as exchange
2. Start the bot and monitor the log pane
...

**Screenshots**

**Release version**
0.33.0
```
branch: development
commit: 90de286843f3a8b881303f6e98c537e42ce9493e 
Date:   Fri Oct 30 17:36:59 2020 +0800
```
**Attachments**
[logs_kraken_btc-usdc.log](https://github.com/CoinAlpha/hummingbot/files/5468279/logs_kraken_btc-usdc.log)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by strikeout** [comment]
Having the same issue. Any updates here so far?

**Comment by jhlq** [comment]
![Screenshot from 2020-11-23 22-33-29](https://user-images.githubusercontent.com/6324698/100019845-09c82280-2ddf-11eb-9d43-3d6040575aa0.png)
Same issue here, also the trades aren't being recorded as shown

**Comment by RC-13** [comment]
Thanks for reporting this issue @jhlq . I just did a test on this issue and confirmed that trades are not getting saved in the database which is why there are no trades shown when running history command. I think what's happening is that the bot is unable to pickup its own trade due to the current error. For the mean time, you can try using other exchange since this issue is happening on Kraken only and will send another update for this case if we get a new update.

**Comment by dennisocana** [comment]
Changing ticket priority from P4 to P1 since based the connector is unusable because of the flooding errors.

**Comment by mifeng** [comment]
#2688
