### ISSUE TITLE
Design data collection initiative

### ISSUE THREAD

**Issue by mifeng** [CoinAlpha/hummingbot#2548]
# Why

To sustain development of Hummingbot, we partner with exchanges and protocols to build connectors and/or strategies. These partners usually ask us for data like number of users or total volume from all users. Since we don't collect data from users, we currently can't answer these questions well and rely on guesstimates based on users on Hummingbot Miner, which is likely a small subset of the overall user base.

Collecting data on individual trades may cause users to turn off data collection for privacy reasons. It's also not necessary since we just need aggregate data for marketing and reporting purposes.

# What

## Client

Build a `heartbeat` process that send aggregate trade volume data to Datadog every [15] minutes. Data sent in each `heartbeat` should include:
* clientID
* exchange
* base asset
* quote asset
* trade volume, denominated in quote asset

Send the trade data as an array of markets since user may have trades in multiple markets.

Add the following variables to `conf_global`:
* `heartbeat_enabled`: default = True
* `heartbeat_interval_min`: default = 15

## Backend

Build a Datadog dashboard that shows on a daily basis:
* number of clients that reported data
* total trade volume by quote asset
* total trade volume by exchange
* total trade volume (aggregated using Sparrow prices)

**Comment by jason-hb** [comment]
Per conversation in business sync meeting today, we will discuss long term data collection business objectives in the December offsite strategy meeting. The functionality described in this story is a much needed start and should be implemented as soon as possible. Longer term, we will consider additional features including but not limited to:

- Rewarding users for allowing data collection
- Rewarding users for total trade volume
- Special bonuses for surpassing cumulative FOV levels (overall and possibly token specific)
- Lockdown only the data collection code (with appropriate notification and/or buy-in from the community) to prevent tampering by users to inflate volume

**Comment by mifeng** [comment]
Consider adding:

* version
* OS / Docker / source

**Comment by Nullably** [comment]
I have added the followings:
`version` - current version including `dev`
`system` - Windows, Darwin (Mac) or Linux
`installation` - binary, docker or source
