### ISSUE TITLE
Expose the new ETH global variables when user runs `config`

### ISSUE THREAD

**Issue by mifeng** [CoinAlpha/hummingbot#2555]
When running `amm-arb` on Balancer, users will need to edit global config variables related to gas. List the following config settings in Global Configurations when the user runs `config` so they know what the current settings are before they edit them:

```
manual_gas_price
ethgasstation_gas_enabled
ethgasstation_api_key
ethgasstation_gas_level
ethgasstation_refresh_time
gateway_enabled
gateway_cert_passphrase
gateway_api_host: localhost
gateway_api_port
```

![Screen Shot 2020-11-03 at 2.29.51 PM.png](https://images.zenhubusercontent.com/545072957c6ccc6277a5c098/9b7a8c38-4b33-4ba0-8c89-ab7c0534220b)

**Comment by mifeng** [comment]
Also, I think `ethereum_token_overrides` should be removed. It will be much easier for users to edit the `erc20_tokens.json` file to add or remove Ethereum tokens.

**Comment by Nullably** [comment]
For this
> Also, I think ethereum_token_overrides should be removed. It will be much easier for users to edit the erc20_tokens.json file to add or remove Ethereum tokens.

I think it's better (and safer) if we include this in another design ticket #2588.
