### ISSUE TITLE
[BUG]Can not import previous config file with command config strategy_file_path

### ISSUE THREAD

**Issue by hongson1981** [CoinAlpha/hummingbot#256]
**Describe the bug**
Can not import previous config file with command config strategy_file_path

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):
1. Hummingbot is already install via docker and can start success at least one time.
2.Exit hummingbot and start via docker again by command : docker attach $name
3. Set up your configuration file with these parameters: >config strategy_file_path
4. Choose Import
5. Select current config file 

Expected result : 
the config file should be load success and can start hummingbot

Actual result : 
Show error that can not read config file because permission

Workaround : 
I can load current config by steps below : 
3. Set up your configuration file with these parameters: >config
4. Select strategy
5. Import current config file -> success

**Screenshots**
![Screenshot from 2019-05-20 21-30-57](https://user-images.githubusercontent.com/29745336/58030055-144d9000-7b48-11e9-8f7e-057ea7301ad3.png)

**Release version**
dev 0.7.0

**Attachments**
[hummingbot_logs_2019-05-20-14-30-34.log](https://github.com/CoinAlpha/hummingbot/files/3198399/hummingbot_logs_2019-05-20-14-30-34.log)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by yzhang1994** [comment]
@hongson1981 Thanks for reporting the bug. We currently require that you enter the strategy before importing an existing config file.  Please continue to use the workaround to start your bot for now.

We realize that the client has a few glitches, but it will probably take us a while to make any substantial improvements since we are prioritizing bugs in the core trading engine.

**Comment by yzhang1994** [comment]
This issue has been resolved with the re-config option
