### ISSUE TITLE
[BUG] Bot unable to display both open positions

### ISSUE THREAD

**Issue by RC-13** [CoinAlpha/hummingbot#2569]
**Describe the bug**
After getting filled order, running `status` shows only one available open position (LONG) however if you check Binance, both LONG and SHORT position are open.

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):
1. Enable HEDGE Mode position on your Binance futures account
2. Create perpetual market making strategy and set a tight spread to get fill immediately
3. Run status command to check for open positions and compare it with Binance exchange

**Screenshots**
BTC-USDT market
![binance perpetual - positions](https://user-images.githubusercontent.com/57189990/98427454-29b9cf80-20d8-11eb-9577-5f7e9726bb11.PNG)

ETH-USDT market
![ETH-USDT](https://user-images.githubusercontent.com/57189990/98427466-376f5500-20d8-11eb-8bc2-84d759518c63.PNG)

**Release version**
0.33.0
```
branch: development
commit c074b03b82f622c10cafc59b66a4a0828bede791
Date:   Fri Nov 6 16:53:22 2020 +0800
```
**Attachments**

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by PtrckM** [comment]
confirmed fix https://github.com/CoinAlpha/hummingbot/pull/2685#issuecomment-737101989
