### ISSUE TITLE
[BUG] binance_perpetual_testnet price_source external_market does not seem to work

### ISSUE THREAD

**Issue by TradeClaw** [CoinAlpha/hummingbot#2573]
**Describe the bug**
// A clear and concise description of what the bug is.
binance_perpetual_testnet price_source external_market does not seem to work

Since the testnet of Binance Futures is pretty much inactive and mid_price is not a reference, I wanted to set the main Binance Futures as a price source.
When starting the bot like that, it does nothing, I have let it run for a long time but no action.

Previously I used the mid_price on that testnet but the orders fly all over the place and you get errors from being out of price range the whole time.

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your bot for binance_perpetual_testnet on BTC-USDT
2. configure external_market as price_source, chosing binance_perpetual as price_source_derivative
3. take_if_crossed is set to True (don't think that has anything to do with the situation)

**Screenshots**
// If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/63117227/98452578-d9328880-2150-11eb-8dd1-e8c151a3a621.png)

**Release version**
dev-0.33.0

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by PtrckM** [comment]
error no longer persist 

![image](https://user-images.githubusercontent.com/54516858/98933085-2761d600-251b-11eb-8733-7250bf2097eb.png)
![image](https://user-images.githubusercontent.com/54516858/98933157-39437900-251b-11eb-9342-7fd3c398f934.png)

**Comment by krisj** [comment]
@PtrckM I think the confusion might have resulted from @TradeClaw using the `configure external_market as price_source` instead of `current_market` in your test case. Isn't it the case where price_source_derivative and price_source_market are ignored unless the price_source is set to external_market?

**Comment by PtrckM** [comment]
thank you for noticing i missed that I updated my post bug still occurs, I was trying as well the `order_book` command unable to pickup the exchange to compare the orderbook from the exchange on the bot

![image](https://user-images.githubusercontent.com/54516858/98936872-90981800-2520-11eb-8c15-ce13b329c852.png)

```
2020-11-12 19:55:26,041 - 9324 - hummingbot.notifier.telegram_notifier - INFO - Telegram is listening...
2020-11-12 19:55:26,043 - 9324 - hummingbot.client.hummingbot_application - ERROR - Unknown error during initialization.
Traceback (most recent call last):
  File "hummingbot\strategy\perpetual_market_making\start.py", line 67, in start
  File "hummingbot\connector\exchange\paper_trade\__init__.py", line 26, in create_paper_trade_market
TypeError: __init__() missing 2 required positional arguments: 'base_url' and 'stream_url'
2020-11-12 19:55:26,046 - 9324 - hummingbot.client.hummingbot_application - INFO - start command initiated.
2020-11-12 19:55:28,206 - 9324 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_derivative - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2020-11-12 19:55:31,336 - 9324 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_order_book_tracker - INFO - Initialized order book for BTC-USDT. 1/1 completed.

```

**Comment by mifeng** [comment]
@vic-en Per discussion in weekly meeting, please delete the `price_source_derivative` parameter and allow the user to use any other exchange for price source (including spot exchanges).

If this change is problematic or requires refactoring, I recommend removing the `price source` parameter from the perpetuals strategy entirely.
