### ISSUE TITLE
[BUG] price_type last_own_trade_price should set refresh tolerance pct to -1

### ISSUE THREAD

**Issue by TradeClaw** [CoinAlpha/hummingbot#2575]
**Describe the bug**
// A clear and concise description of what the bug is.
When using price_type : last_own_trade_price, and the default order refresh tolerance of 0 (or for that matter any besides -1) is still active, the bot just goes inactive and does not refresh orders after one got hit and it does not go into the other direction anymore to change the last_own_trade_price.
It cancels the opposite order after one gets hit, but does not recreate any because the order refresh pct has to be disabled for this price_type to work.
This price_type seemed like a good way to go about on binance perpetual but not if it just gets stuck.

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:
1. leave the default order refresh time of 0
2. create a bot with price_type last_own_trade_price
3. wait until orders get hit

**Screenshots**
// If applicable, add screenshots to help explain your problem.

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).
dev-0.33.0

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by RC-13** [comment]
Hi @TradeClaw I think this concern has been resolve on our latest release (v0.34.0), kindly re-try it on your side and let us know if issue has been address so we can close this ticket. 

I did test on this and my bot was able to create new orders after getting fill and position getting closed.
Here's a screenshot of my test bot: Note, order refresh tolerance is set to default (0)
![perpetual](https://user-images.githubusercontent.com/57189990/102597434-9c957c00-4155-11eb-829d-937769d66b91.PNG)

Binance perpetual testnet:
![testnet last trade](https://user-images.githubusercontent.com/57189990/102597477-ab7c2e80-4155-11eb-91c0-0983fe6ec0b4.png)

**Comment by RC-13** [comment]
Closing this ticket for now
