### ISSUE TITLE
[BUG] Unexpected error with Websocket connection when using Bitfinex connector

### ISSUE THREAD

**Issue by mnvoh** [CoinAlpha/hummingbot#2576]
**Describe the bug**

I've added api keys for both Binance and Bitfinex. I've also created a simple pure mm strategy. When I set `config exchange binance` everything works fine but when I set it to `bitfinex` and `start` the bot, I'm constantly getting the following exception whenever it tries to `bid` or `ask`:

**NOTE**: I'm using paper trade mode.

```
hummingbot.connector.exchange.bitfinex.bitfinex_api_order_book_data_source - WARNING - Unexpected error with WebSocket connection. Retrying in 30 seconds. Check network connection.
```

**Steps To Reproduce**
1- Setup a bot using the attached config
2- Add Bitfinex api key and secret
3- Set exchange to `bitfinex`
4- Start the bot using the `start` command

**Screenshots**

![Selection_091](https://user-images.githubusercontent.com/4628766/98468926-e6538400-21f1-11eb-89a9-6210793ecad1.png)

**Release version**

`0.32.0`

**Attachments**
Config:

[conf.zip](https://github.com/CoinAlpha/hummingbot/files/5506557/conf.zip)

Logs:

[logs.zip](https://github.com/CoinAlpha/hummingbot/files/5506564/logs.zip)

Discord uname: `MiladNozari#7290`

**Comment by PtrckM** [comment]
I'm unable to replicate it using your strategy config on 0.32.0 [ETH-UST](https://www.bitfinex.com/t/ETH:UST) (for USDt) FYi there is an issue https://github.com/CoinAlpha/hummingbot/issues/2622
![image](https://user-images.githubusercontent.com/54516858/99037872-8f69f800-25bf-11eb-96d8-d2f1fd91c776.png)

**Comment by mnvoh** [comment]
Yup, that was it. I created another strategy and set its market to `ETH-UST` and now it's working. Thanks @PtrckM
