### ISSUE TITLE
New Uniswap Gateway API

### ISSUE THREAD

**Issue by Nullably** [CoinAlpha/hummingbot#2585]
Uniswap endpoints in Gateway API similar to Balancer:

1. Add a `src/services/uniswap.js` file with Uniswap pricing and trading related functions from the SDK
2. Add a `src/routes/uniswap.route.js` file with buy-price, sell-price, buy, and sell functions for Uniswap
3. Check that the ETH-related functions work with Uniswap (blocked by #2557)
4. Test the functionality below on Kovan testnet running Postman locally.

## Acceptance criteria
1. Using the WETH-DAI pair, buy-price and sell-price works for both leg of the trade. Buy price is higher than sell price.
2. Using the WETH-DAI pair, buy and sell transactions work
3. Non-approved tokens: If token is not approved, transaction is rejected with error message specific to this issue.
4. Transaction failure confirmation: If transaction succeeds but no value is transferred, the buy and sell routes should return error message specific to this issue.
5. Gas limit: Using a high gas limit, buy and sell transactions goes through and routes return True. If gas limit is set below transaction gas usage, routes return False with error message specific to this issue.
6. Gas price: Using a high gas limit, buy and sell transactions goes through and routes return True. If gas price is set too low and transaction is never confirmed, routes return False with error message after a certain timeout.
7. Out of gas: If user doesn't have enough ETH to pay for transaction, buy and sell routes return False with an error message specific to this issue.

**Comment by mifeng** [comment]
@vic-en I took a brief look at the [Uniswap Javascript SDK](https://uniswap.org/docs/v2/javascript-SDK/quick-start) and it appears to have the functionality we need to build something similar to what we have for Balancer.

Similar to Balancer, I suggest first creating a `uniswap.js` file with functions for buy-price, sell-price, buy, and sell. The **Pricing** and **Trading** pages in the Uniswap SDK has examples that show how to do it. Afterwards, I suggesting creating the routes and testing extensively on Kovan.

Ethereum coding has a lot of frustrating but simple gotchas that I can probably help you resolve. If you get stuck on something or need test WETH, etc please DM me on Discord and I should be able to help.
