### ISSUE TITLE
[Feature] Disable paper_trade for Celo

### ISSUE THREAD

**Issue by sdgoh** [CoinAlpha/hummingbot#2587]
**Feature Suggestion**
Disable paper_trade option for Celo. If the Celo is configured for mainnet, but paper_trade is enabled. Trade will execute on the mainnet for Celo, while paper_trade will be executed on the exchange side. 

**Impact**
This will lead to confusion where turning paper_trade on will not execute any read trade on Celo. 

**Additional context**
Paper trade is disabled for Balancer, and Binance Perpetual. Celo should be consistent with this.

**Comment by viktorya777** [comment]
User jophish#8025 had the same experience trying Celo Arbitrage on paper trading mode.

**Comment by dennisocana** [comment]
Paper trade does not support perpetual and protocol connectors, only spot. Will create a new story as a feature request to prevent users from enabling paper trade mode when it detects the strategy is using one of the connectors not supported by paper trading.
