### ISSUE TITLE
Integrate Token Lists to retrieve ERC-20 tokens

### ISSUE THREAD

**Issue by Nullably** [CoinAlpha/hummingbot#2588]
**Design Considerations**
- Currently, HB allows only one Ethereum wallet connection, later on when we add support for Uniswap, should we allow users to be able to multiple wallets?
- Should we allow user to set ERC20 token address file name? (This will be a new configuration)

**Proposal**
- Add a new config file (and template) for ERC20 token address with template version number, this file will be under `conf` folder (rather than current `hummingbot/wallet/ethereum`). This will allow update the config while getting new token addresses update upon new HB release.
- Remove ethereum_token_override. It will be much easier for users to edit the erc20_tokens.json file to add or remove Ethereum tokens.

**Comment by mifeng** [comment]
I think each protocol connector should only support one account for that protocol, similar to how the client only allows one account per exchange, so only one wallet is needed. However, I do think we should make the user responsible for entering a ERC-20 token addresses. The current method of maintaining ERC-20 token addresses is not very secure and may introduce user errors if they have to edit it.

## Proposal
* Add a global variable called `erc20_token_list`, a string that corresponds to a [Token List](https://tokenlists.org/) URL.
* I think the default list should either be https://tokenlists.org/token-list?url=erc20.cmc.eth or https://tokenlists.org/token-list?url=tokens.1inch.eth (the latter is better if it doesn't take too long)
* When the bot starts, fetch the specified Token List along with `erc20_tokens.json`, and store both in memory. If resource is not available, this ideally doesn't block the bot from operation.
* User can use `erc20_tokens.json` to override or append to the Token List. This lets the user add a new token not found in the Token List or override token addresses if user is testing on testnet.

**Comment by vic-en** [comment]
In addition to the proposal from @mifeng, token list fetched from url will have corresponding decimal values which will be fetched through etherscan api(https://etherscan.io/apis#tokens) and stored alongside in memory. This is necessary in order to do proper calculations for each token and also prevent issues like #2681. 
However, users wouldn't have to specify decimals in override file. Only the corresponding token address(in memory) would be overwritten by the address specified in the override file. Decimals fetched from etherscan would be maintained.

**Comment by mifeng** [comment]
> However, users wouldn't have to specify decimals in override file. Only the corresponding token address(in memory) would be overwritten by the address specified in the override file. Decimals fetched from etherscan would be maintained.

@vic-en Sounds good - that makes sense.
