### ISSUE TITLE
Binance perpetual connectors missing from the "connect" output

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#2593]
**Describe the bug**

The binance perpetual connectors are not showing in the list of connectors in the `connect` command output on a macOS binary version.

![image](https://user-images.githubusercontent.com/50150287/98566411-acfe3f80-22e9-11eb-80fb-3aac20dfd307.png)

There's this error when you launch the app.

![image](https://user-images.githubusercontent.com/50150287/98566057-48db7b80-22e9-11eb-8fb7-500a881def4c.png)

**Steps To Reproduce**

1. Create a binary installer for macOS using the most updated `development` branch
2. Start Hummingbot and run `connect` command

Version: dev-0.33

**Comment by RC-13** [comment]
fix release on v0.33
