### ISSUE TITLE
[BUG] hanging orders remain on the book after a derivatives position is closed

### ISSUE THREAD

**Issue by krisj** [CoinAlpha/hummingbot#2596]
**Describe the bug**
In the current implementation of Binance perpetual connector, when using One-Way position mode, the hanging orders remain open on both sides even after the position is closed. Since there is no inventory to skew/manage in derivatives, all the hanging orders should be closed as soon as the position is closed or there should be a way to actively manage them when a position is open.

**Steps To Reproduce**
This works in any configuration as long as One-Way (Non hedge) mode is enabled and hanging orders are in use.

**Release version**
dev-0.33.0

**Comment by vic-en** [comment]
We would remove the hanging order parameter since we have the position management features and stop loss as well.
Thanks.

**Comment by krisj** [comment]
Yes, makes sense, it is now redundant.

**Comment by RC-13** [comment]
Closing this ticket now
