### ISSUE TITLE
Handle rate limits when starting client more gracefully

### ISSUE THREAD

**Issue by mifeng** [CoinAlpha/hummingbot#2601]
# Why
When testing `development`, I encountered a situation where I hit the Binance API rate limit. This resulted in lack of response from Binance API when running the bot, which is expected behavior. 

However, the problem is that when I exited the bot and tried to start the client again, the client froze after running `import` and during `create` when asking the order amount question, likely because it was waiting for a response from the Binance API that never resolved due to rate limit. Since there was no response from the client that this was related to the rate limits, this seems like a bug. After an hour passed and rate limit eased, I tried again and ran these commands successfully.

# What
Add a timeout to the following spots where we call exchange APIs and return an error message that contains the status code and message from the exchange API. The timeout duration should be 30 seconds by default - ideally this is a global parameter that the user can set:
- `create` (order amount)
-- In the case of the create, the timeout should apply when the creation is determining the minimum order amount. If after 10 seconds (as default value, that should be configurable) the request does not return, the creation should continue considering that the minimum amount is cero.

- `import`
- `connect`
- `balance`
- `history`
For this commands, the timeout for their execution will be 30 seconds by default (the value should be configurable). If the timeout happens, the action should be canceled and an error message should be displayed in the client main pane, explaining that the action can't be executed due to connection problems with the exchange/exchanges.

# DoD
All of the actions specified before are interrupted by the client, and the control returned to the user, if they take longer than the configured wait time.

**Comment by CrimsonJacket** [comment]
**Initial Investigation**
- There are several ways Rate Limits are being implemented by the various exchanges. 

  1. Weighted Requests, where each user is assigned a fix rate limit and each method is assigned a weight. This is used by Binance. Where certain API endpoints has a higher weight depending on the resource consumed.
  2. Rate Limit by Methods, this essentially assigns rate limits for every API endpoint by API key pair. This is observed in Crypto.com i.e. `private/create-order` is limited to `15 requests per 100ms`
  3. Fixed Rate Limit, this is implemented by most other exchanges. i.e. AscendEx has a fixed rate limit of 6,000 requests/min

**Suggested Solution**
- Populate the various exchange specific rate limits for each API endpoint.
- Refactor of a `Throttler` class to deal with these 3 types of rate limits.

**Comment by CrimsonJacket** [comment]
As per mentioned in the standup and refinement session. This task, after some initial discussion with @Nullably , although is the first task that suggests some sort of rate limit throttler, we felt that this task should address the API rate limit concerns across the entire client. As such I will be creating a new Epic that will capture all the details pertaining to the new APIThrottler.

New Issue #TBD

**Comment by CrimsonJacket** [comment]
During a meeting with @aarmoa, we felt that this task should really be a **maintenance** task to enforce timeouts at the aforementioned commands.

**Comment by CrimsonJacket** [comment]
@Nullably has mentioned the need to discuss how we should handle the `connect` and `balance` commands. Mainly because these commands requires interaction with all the connectors.

**Comment by phbrgnomo** [comment]
@CrimsonJacket Would the implementation of the new Throttler have any impact on this story?

**Comment by dennisocana** [comment]
@phbrgnomo to update the description of the story as discussed during one of our refinement sessions and add a definition of done.

**Comment by dennisocana** [comment]
@aarmoa rewrote this task's description and added a definition of done as agreed by the client squad during a previous discussion.
