### ISSUE TITLE
[Bug] Error Connecting crypto_com or coinbase_pro on windows binary 

### ISSUE THREAD

**Issue by CalicaliT** [CoinAlpha/hummingbot#2608]
**Describe the bug**
// A clear and concise description of what the bug is.
Trying to connect on Crypto_com and Coinbase_pro on windows binary shows an error
Connecting Crypto_com
![image](https://user-images.githubusercontent.com/71769411/98839127-2334aa80-2480-11eb-8eae-bfeecbd45897.png)
Connecting coinbase_pro
![image](https://user-images.githubusercontent.com/71769411/98840114-5cb9e580-2481-11eb-95b5-1088d8ef39d4.png)

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:
Here are the steps to reproduce the issue (see attachments in the section below):
1. Use Hummingbot windows binary ver. 0.33.0 
2. Add crypto/coinbase API keys using connect command
...

**Screenshots**
// If applicable, add screenshots to help explain your problem.

**Release version**
v. 0.33.0

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 
[logs_hummingbot.log](https://github.com/CoinAlpha/hummingbot/files/5525548/logs_hummingbot.log)

**Comment by RC-13** [comment]
Re-testing issue, no issue on my side:
![image](https://user-images.githubusercontent.com/57189990/101614775-50a55180-3a48-11eb-8b32-32af4c483cba.png)

**Comment by PtrckM** [comment]
Can you try running the bot as administrator? Works on me when run as admin.

![image](https://user-images.githubusercontent.com/54516858/101615521-30c25d80-3a49-11eb-94bb-108277783de2.png)

**Comment by rapcmia** [comment]
Tried this on Binary 0.33.1, all ok

![image](https://user-images.githubusercontent.com/73840223/102455485-a5654f80-407a-11eb-9962-7a967bad4f03.png)

**Comment by RC-13** [comment]
Will close this ticket now since most of support team no longer gets this issue.
