### ISSUE TITLE
Sudo Error on Windows

### ISSUE THREAD

**Issue by meg91318** [CoinAlpha/hummingbot#2613]
When trying to run DockerDesktop using GitBash. Steps provided on script followed until "_./create.sh_" 
Error shown below:

![SudoError](https://user-images.githubusercontent.com/73913975/98965390-f3030f80-2544-11eb-8e8e-c160a9d16f48.PNG)

_.create.sh/: **line 71**: sudo: command not found._

**Comment by PtrckM** [comment]
Looks like you are trying to use the docker script on git-bash or on dockertoolbox (deprecated), I highly advise to use docker desktop + WSL 2 in able to resolve this issue. For more info https://docs.hummingbot.io/installation/windows/#install-via-docker
