### ISSUE TITLE
[BUG] Extra ")" on prompt message

### ISSUE THREAD

**Issue by rapcmia** [CoinAlpha/hummingbot#2616]
**Describe the bug**
// A clear and concise description of what the bug is.
There is a extra ")" on the prompt message when setting up perpetual_market_making on HB client (Binary\Docker\Source)
_"How much leverage do you want to use? (Binance Perpetual supports up to 75X for most pairs)**)**>>>"_

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:
1. What is your market making strategy? >>> perpetual_market_making    
Please see https://docs.hummingbot.io/strategies/perpetual-market-making/ while setting up these below configuration.

2. Enter your maker derivative name >>> binance_perpetual_testnet          

3. Enter the token trading pair you would like to trade on binance_perpetual_testnet (e.g. BTC-USDT) >>> BTC-USDT  
 
4. How much leverage do you want to use? (Binance Perpetual supports up to 75X for most pairs)) >>>

**Screenshots**
// If applicable, add screenshots to help explain your problem.
![v33](https://user-images.githubusercontent.com/73840223/99014804-7137d400-258e-11eb-9bfe-6c20588b8e3d.PNG)

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).
v0,33,0

**Comment by PtrckM** [comment]
fix on current dev-0.34.0

![image](https://user-images.githubusercontent.com/54516858/101976793-bdf0f680-3c83-11eb-8566-6cf0d30f7e5b.png)
