### ISSUE TITLE
[BUG] Windows binary v.0.33 Loopring paper trade mode error

### ISSUE THREAD

**Issue by CalicaliT** [CoinAlpha/hummingbot#2630]
**Describe the bug**
Creating PMM strategy with loopring as exchange while paper trade in enabled shows error

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):
1. Enable paper trade mode
2. Create PMM choose loopring as exchange
3. Start bot then error will appear on log

**Screenshots**
![image](https://user-images.githubusercontent.com/71769411/99116850-b3652200-262f-11eb-9287-509b6dada699.png)

**Release version**
v. 0.33.0

**Attachments**
[logs_loopringtest.log](https://github.com/CoinAlpha/hummingbot/files/5539090/logs_loopringtest.log)

**Comment by RC-13** [comment]
Closing this case in favor of #2614, same cause.
