### ISSUE TITLE
Stex Exchange Connector

### ISSUE THREAD

**Issue by Dev-JamesR** [CoinAlpha/hummingbot#2634]
## Exchange Details ✏️

- **Name of exchange**: Stex
- **Exchange URL**: https://stex.com/
- **Link to API docs**: https://apidocs.stex.com/
- **Type of exchange**: [X] Centralized [ ] Decentralized
- **Requester details**: Are you affiliated with the exchange? [ ] yes [X] no 
  - If yes, what is your role?

## Rationale / impact ✏️
(Describe your rationale for building this exchange connector, impact for hummingbot users/community)
Many altcoin projects start on exchanges like stex and need market making/algo trading made available to them via the open-source community. Stex is a great starting point to bring this side of the market into the fold.
## Additional information ✏️
(Provide any other useful information that may be helpful to know about this exchange)
Additional Documentation/Links:
https://help.stex.com/api-v3-documentation
https://packagist.org/packages/stocks_exchange/php-client
https://www.npmjs.com/package/stocks-exchange-client
https://rubygems.org/gems/stocks_exchange_api_client
https://cocoapods.org/pods/StexSDK
---

⚠️ ***Note: do not modify below here***

## Developer notes

This feature request entails building a new exchange connector to allow Hummingbot to connect to an exchange that is currently not supported.

### Resources
- [Exchange connector developer guide](https://docs.hummingbot.io/developers/connectors/)
- [Discord forum](https://discord.hummingbot.io)

### Deliverables
1. A complete set of exchange connector files as listed [above](#developer-notes-resources).
2. Unit tests (see [existing unit tests](https://github.com/CoinAlpha/hummingbot/tree/master/test/integration)):
  1. Exchange market test ([example](https://github.com/CoinAlpha/hummingbot/blob/master/test/integration/test_binance_market.py))
  2. Order book tracker ([example](https://github.com/CoinAlpha/hummingbot/blob/master/test/integration/test_binance_order_book_tracker.py))
  3. User stream tracker ([example](https://github.com/CoinAlpha/hummingbot/blob/master/test/integration/test_binance_user_stream_tracker.py))
3. Documentation:
  1. Code commenting (particularly for any code that is materially different from the templates/examples)
  2. Any specific instructions for the use of that exchange connector ([example](https://docs.hummingbot.io/connectors/binance/))

### Required skills
- Python
- Previous Cython experience is a plus (optional)

**Comment by dennisocana** [comment]
Closing for now. We will reopen if the connector will be integrated in the future.
