### ISSUE TITLE
[BUG] Missing USDT-BRL pair on HB client

### ISSUE THREAD

**Issue by rapcmia** [CoinAlpha/hummingbot#2640]
**Describe the bug**
// A clear and concise description of what the bug is.
kaiofabian was trying to set up token pair USDT-BRL on Binance market however the pair is not showing as available. Tried to create a new instance on docker getting same results (using PMM strategy), missing USDT-BRL pair

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:
1. User trying to setup HB client on his virtual machine
2. User does not have the option to select 'USDT-BRL'

**Screenshots**
// If applicable, add screenshots to help explain your problem.
![kaiofabian BR 2](https://user-images.githubusercontent.com/73840223/99339037-56cc6600-28c0-11eb-9691-20c31f2c4f21.jpg)

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).
0.33.0

**Optional: your discord username:**
kaiofabian 🇧🇷#8967

**Comment by PtrckM** [comment]
hotfix has been release for this https://github.com/CoinAlpha/hummingbot/pull/2661
![image](https://user-images.githubusercontent.com/54516858/99948110-e20f9500-2db3-11eb-8d4c-f07d4792bef6.png)

Can now update to the hotfix release [0.33.1](https://hummingbot.io/download/)
