### ISSUE TITLE
Create new installation guide for Docker on Windows

### ISSUE THREAD

**Issue by mifeng** [CoinAlpha/hummingbot#2654]
# Why

The current [Windows Docker installation guide](https://docs.hummingbot.io/installation/windows/#install-via-docker) is outdated, since Docker Toolbox is now deprecated in favor of Docker Desktop. Docker Desktop uses Windows Subsystem for Linux 2, which is an [upgrade](https://docs.microsoft.com/en-us/windows/wsl/compare-versions) over WSL 1.

Docker Desktop no longer loads the command line as Docker Toolbox did. Instead, it enables the `docker` command in Windows Powershell and `cmd`. However, since our current installation scripts assume access to Unix commands, they throw errors currently in Powershell. To get these scripts to work as-is, the user may need to take another action, like downloading [Windows Terminal](https://docs.microsoft.com/en-us/windows/terminal/) or enabling the Linux distro in it.

If users can easily install the Docker version of Hummingbot in Windows and use components like `gateway-api` and the Loopring connector which currently don't work in the binary version, we should be able to deprecate the binary installers which will save the team a lot of time.

# What

Update the instructions in this guide to fit the latest Docker Desktop / Windows Terminal method. Test out 1) `gateway-api` and 2) the Loopring connector to make sure that they work in Windows.

**Comment by dennisocana** [comment]
@phbrgnomo please test this guide from support and see if that works for you. Let us know if you run into errors while following the guide. https://docs.hummingbot.io/installation/windows/#install-via-docker

**Comment by phbrgnomo** [comment]
Docker Desktop is installing now.

I remember that my big issue was on setting up the WSL 2, wich i only solved after finding the proper guide ([the Microsoft article you already linked](https://docs.microsoft.com/en-us/windows/wsl/install-win10) )

My suggestion is to Highlight that without a proper installation of WSL 2, Docker Desktop won't install on windows home (not sure about the other versions).

Also could be interesting as an alternative, the user could download the Ubuntu client (or any other version like Debian) directly from the Microsoft Store and follow the "Linux Installation Guide" (That is how i did):

![Captura de tela 2020-11-25 14 05 56](https://user-images.githubusercontent.com/34484531/100259895-89610900-2f27-11eb-9e22-ef87ef91917c.png)

Only one small trick is needed: to run the docker (through `./start.sh script`), the user must execute `sudo dockerd` (to start the docker daemon), then he can open a new Linux window and rund the start script (or any other docker command)
