### ISSUE TITLE
Add better error handling for Ethereum connectors

### ISSUE THREAD

**Issue by mifeng** [CoinAlpha/hummingbot#2655]
For each Ethereum protocol integration, pass an appropriate error message back to the Hummingbot in the following cases:
- token allowance is too low
- token address not found
- insufficient ETH balance, not enough gas
- gasLimit set too low
- timeout (gasPrice set too low)
- price too low on sell tx (variable is named maxPrice)

**Comment by sdgoh** [comment]
Added exception check prior to trade execution to list out exceptions in log panel.

**Comment by sdgoh** [comment]
![image.png](https://images.zenhubusercontent.com/5f339fa8ad3191f8b453f190/77cdb841-1bd8-4c99-819b-b6f39aac2d3b)

![image.png](https://images.zenhubusercontent.com/5f339fa8ad3191f8b453f190/d616ae71-4a8d-4a0f-9c87-1307f9d4dbc5)

**Comment by sdgoh** [comment]
QA please test this PR against Gateway `feat/optimize_protocol_endpoints`

**Comment by sdgoh** [comment]
Steps for testing:

- token allowance is too low
- insufficient ETH balance, not enough gas
Test: Use new account with low or zero balance. 

- token address not found
Test: 
Use `ETHEREUM_TOKEN_LIST_URL=http://defi.cmc.eth.link/` for Gateway's `.env`
User `config etheruem_token_list_url` for `https://uniswap.mycryptoapi.com/` for HB Client
Create `amm_arb` in client for Uniswap `WETH-USDT`, Binance `ETH-USDT`.
Run strategy, error will report on first run, and check `status` to see the captured warning.
