### ISSUE TITLE
Add dynamic gas calculation for Balancer in the client

### ISSUE THREAD

**Issue by mifeng** [CoinAlpha/hummingbot#2657]
# Why

In https://github.com/CoinAlpha/gateway-api/pull/12#issuecomment-730833834, I added a `maxSwaps` parameter to the Balancer gateway. Since gas estimation is very important for Balancer, we should try to make sure that the client accurately estimates gas based on the number of swaps used.

# What
* Add a new global parameter called `balancer_max_swaps` (default = 2)
* Pass this parameter as `maxSwaps` in the Balancer pricing and trading functions
* Use the method in this comment above to estimate gas usage for Balancer transactions. The resulting estimated gas used number should be incorporated into the profitability calculation.

**Comment by jason-hb** [comment]
Not sure if this needs a new story or can be incorporated into this one...but I think a "gas limit" parameter should also be added so the bot stops trading during periods of high gas cost. In theory this should be covered if an accurate gas estimate is used in profitability calculation, but as a trader I would feel better if I had more control over gas prices
