### ISSUE TITLE
Balancer AMM - Disconnecton with balancer detected, transaction was created and completed, opposing Binance order wasn't created

### ISSUE THREAD

**Issue by phbrgnomo** [CoinAlpha/hummingbot#2658]
**Describe the bug**
Executing balancer amm strategy against Binance.

Bot detected opportunity and created the transaction on the blockchain.

As can be seen on the log file attached, on the time stamp 14:32:47,855 the order was created

At the time stamp 14:32:47,870 bot detected an error submitting the BUY order, But the order have already been created ([tx link](https://etherscan.io/tx/0x3cf74d85031439d22c7ea72d9e731355d046520320e53ca0a299a4e42bd05540)) 

The blockchain order creating time stamp is 14:39:09

After that, the blockchain order was mined, but no order opposing order were created on Binance

**Steps To Reproduce**

`eth_gasstation_gas_enabled = True`
`eth_gasstation_gas_level = average`
`concurrent_orders_submission = False`

**Screenshots**
// If applicable, add screenshots to help explain your problem.

**Release version**
0.033.0

**Attachments**
[logs_conf_amm_arb_1.log](https://github.com/CoinAlpha/hummingbot/files/5574308/logs_conf_amm_arb_1.log)

[conf_amm_arb_1.txt](https://github.com/CoinAlpha/hummingbot/files/5574330/conf_amm_arb_1.txt)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by Nullably** [comment]
@RC-13 Just wondering if you were able to reproduce this issue in v0.35?

**Comment by RC-13** [comment]
@Nullably No, we haven't been able to replicate this behavior yet, the profitability for the past days where really low. We have a long term test bot running and currently observing.

**Comment by keithbaum** [comment]
Hi @RC-13, for this issue were you able to reproduce it?

**Comment by RC-13** [comment]
@keithbaum Not yet, the arbitrage opportunity is very low right now and the gas price is very high so we haven't had the chance to try it again. We can do another test after the release.
