### ISSUE TITLE
False positive virustotal - hb v0.33.0 & v0.33.1 detecting virus from ethsnarks

### ISSUE THREAD

**Issue by PtrckM** [CoinAlpha/hummingbot#2680]
**Describe the bug**
- Hummingbot version 0.33.0 and 0.33.1 currently virustotal detecting `Cyren W32/Trojan.YOAU-3838` and `Gridinsoft Ransom.Win32.Filecoder.dd!s1`
- v0.33.1 hotfix #2661 
https://www.virustotal.com/gui/file/e05a58d90c0593d8127986108947071eaa1f6c48b9cfa50fa71984ee1dc94a97/detection
- v0.33.0 PR [#2522](https://github.com/CoinAlpha/hummingbot/pull/2522)
https://www.virustotal.com/gui/file/2f310f164c25b2e30ba450746415ad7c30d0cb12bdd01e3d0180f560edc97a8d/detection

- v0.32.0 no ethsnarks-loopring
https://www.virustotal.com/gui/file/1e979ff01124cd0b81241718903d82b0fec83ec1ee6c309451ccea983f0c74b0/detection

**Test and Rebuild**
- remove dependency `ethsnarks-loopring` for loopring connector https://github.com/CoinAlpha/hummingbot/tree/master/setup
- start building your binary installer using `./build` https://github.com/CoinAlpha/hummingbot/tree/master/pyinstaller
![image](https://user-images.githubusercontent.com/54516858/100417813-a9760100-30bc-11eb-8e69-d90d3a7b7682.png)

- scan result after re-build from 0.33.1: https://www.virustotal.com/gui/file/167f103fb5a160aec29ea134e1a63fff8dcde74c810abe7c650bcc531fd35d43/detection
![image](https://user-images.githubusercontent.com/54516858/100416478-88f87780-30b9-11eb-8ffb-1f91e026aacb.png)
- scan result after re-build from 0.33.0: 
https://www.virustotal.com/gui/file/7a1cb54e7ebc45cac1eee20ad438a1e7a1a56092290bc754d963e99089b00cee/detection

- Install re-build binary installer and test `connect loopring` without the dependency.
![image](https://user-images.githubusercontent.com/54516858/100418376-a3345480-30bd-11eb-9435-672516323dd0.png)

**Release version**
0.33.0 and 0.33.1

**Attachments**
[logs_hummingbot.log](https://github.com/CoinAlpha/hummingbot/files/5606207/logs_hummingbot.log)

**Comment by dennisocana** [comment]
Entry has been added to FAQ docs. See https://github.com/CoinAlpha/hummingbot-docs/pull/85
