### ISSUE TITLE
USDC balance not detected on ethereum network.

### ISSUE THREAD

**Issue by vic-en** [CoinAlpha/hummingbot#2681]
USDC balance not detected when running balance command.
![bot](https://user-images.githubusercontent.com/31972210/100482443-ae0bdb00-30f7-11eb-8431-95d206a345b2.png)
![metamask](https://user-images.githubusercontent.com/31972210/100482444-afd59e80-30f7-11eb-9b7c-0085bda9ae5b.png)

USDC balance not detected correctly when running status command.
![stat](https://user-images.githubusercontent.com/31972210/100484421-a69b0080-30fc-11eb-9000-6fc7a2e2467d.png)

**Comment by mifeng** [comment]
This issue should have been fixed by #2588. @RC-13 please review.

**Comment by PtrckM** [comment]
Issue is fixed as mention

![image](https://user-images.githubusercontent.com/54516858/101565738-a4904600-3a08-11eb-9424-f772a5265f92.png)
