### ISSUE TITLE
Resume trading after Kill Switch activation

### ISSUE THREAD

**Issue by MrBig1964** [CoinAlpha/hummingbot#2697]
**Circumstances:**
A user has the kill switch activated and a trigger value defined.
The account reach the kill switch trigger value.
The bot normally stops the trading.
If the user wants to resume trading, must normally have to restart the bot from the beginning. 

**New Feature:**
A command that enable the user to manually reset the account P&L calculations.

**Improvement:**
Be able to resume trading without having to make a cold restart of the bot.

**Comment by phbrgnomo** [comment]
Already covered on #2497. Closing this issue.
