### ISSUE TITLE
[BUG] HB Dev 0.7.0 - 20th May - Config should allow a way to reenter wrongly entered wallet key

### ISSUE THREAD

**Issue by vkapsIT** [CoinAlpha/hummingbot#270]
**Describe the bug**
 Config exits if the wallet private key entered is wrong instead of allowing to reenter right there

**Steps To Reproduce**

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with the following  parameters: 

- cross_exchange_market_making
- create
- ddex
- coinbase
- BAT-WETH
- BAT-ETH
- minimum profitability to make trade- default
- actively adjust - default
- minimum profitability to cancel trade- default
- minimum expiration - default
- coinbase API key - correctly entered
- coinbase secket key - correctly entered
- coinbase pass - correctly entered
- import or create existing wallet - import
-Wallet private key - entered incorrectly 3 bytes long
- Wallet pass - correctly entered

Now bot throws an error saying and exit the config process - The private key must be exactly 32 bytes long, instead of 3 bytes.

It should however allow to reenter correct private key by prompting again to enter the correct private key

2. Start the bot using this command: ...
... docker start <CONTAINERNAME> && docker attach <CONTAINERNAME>

**Screenshots**

**Release version**
// 0.7.0 development - 20th May

**Attachments**
![Screenshot 2019-05-22 09 28 48](https://user-images.githubusercontent.com/50767247/58147259-56292400-7c77-11e9-985f-cc301f5c893b.png)

[hummingbot_logs_2019-05-22-04-12-31.log](https://github.com/CoinAlpha/hummingbot/files/3205594/hummingbot_logs_2019-05-22-04-12-31.log)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by yzhang1994** [comment]
@vkapsIT This should be fixed now. Please check.
