### ISSUE TITLE
[Bug] History command doesn't calculate total P&L if fees paid is in another token

### ISSUE THREAD

**Issue by glenntomas** [CoinAlpha/hummingbot#2710]
**Describe the bug**
User tried using `history` command, but when `history` command is entered the trade P&L, fees paid and total P&L is not calculating and not the same as the example in docs. If fees paid is in another token it doesn't calculate trade P&L, fees paid and total P&L.

Here are the steps to reproduce the issue (see attachments in the section below):
1. Create PMM on crypto_com with CRO/BTC pair.
2. Start the bot and wait for orders to be filled.
3. Run `history` command.

**Screenshots**
![unknown](https://user-images.githubusercontent.com/73885708/101924265-6b73f380-3c0b-11eb-8b16-92dc6bc6fe16.png)

**Release version**
0.34.0

**Discord Name: tRiFFiD**

**Comment by bonez56** [comment]
This is affecting me on the crypto_com exchange, since fees are paid in CRO. I get exactly the same result as per the screenshot above, so it's hard to calculate fees paid and work out the P&L.
