### ISSUE TITLE
FTX connector

### ISSUE THREAD

**Issue by algo88** [CoinAlpha/hummingbot#2711]
## Exchange Details ✏️

- **Name of exchange**: FTX
- **Exchange URL**: https://ftx.com/
- **Link to API docs**:  https://docs.ftx.com/#overview
- **Type of exchange**: Centralized 
- **Requester details**: Are you affiliated with the exchange? no 
  - If yes, what is your role?

## Rationale / impact ✏️
(Describe your rationale for building this exchange connector, impact for hummingbot users/community)
Ftx is very up and coming, their derivatives and options are going to help expand opportunity in this space imo. They even have a FIX api, along with standard rest/websocket.

## Additional information ✏️
(Provide any other useful information that may be helpful to know about this exchange)
They have the most interesting and unique derivatives that would benefit greatly from added liquidity. they have rebate programs for larger market makers that is very competitive with exchanges like Binance. They have various alt-coin perpetual indexes, MOVE contracts, options, quarterly and perpetual btc futures and a many other random things like a TRUMP-GO/ TRUMP-STAY product, FIAT, stocks,  prediction markets, volatility. Lots of products, not always the most liquidity.

---

⚠️ ***Note: do not modify below here***

## Developer notes

This feature request entails building a new exchange connector to allow Hummingbot to connect to an exchange that is currently not supported.

### Resources
- [Exchange connector developer guide](https://docs.hummingbot.io/developers/connectors/)
- [Discord forum](https://discord.hummingbot.io)

### Deliverables
1. A complete set of exchange connector files as listed [above](#developer-notes-resources).
2. Unit tests (see [existing unit tests](https://github.com/CoinAlpha/hummingbot/tree/master/test/integration)):
  1. Exchange market test ([example](https://github.com/CoinAlpha/hummingbot/blob/master/test/integration/test_binance_market.py))
  2. Order book tracker ([example](https://github.com/CoinAlpha/hummingbot/blob/master/test/integration/test_binance_order_book_tracker.py))
  3. User stream tracker ([example](https://github.com/CoinAlpha/hummingbot/blob/master/test/integration/test_binance_user_stream_tracker.py))
3. Documentation:
  1. Code commenting (particularly for any code that is materially different from the templates/examples)
  2. Any specific instructions for the use of that exchange connector ([example](https://docs.hummingbot.io/connectors/binance/))

### Required skills
- Python
- Previous Cython experience is a plus (optional)

**Comment by bonez56** [comment]
+1 for FTX, it would be a great connector to add.

**Comment by makktomm** [comment]
Adding FTX to Hummingbot is an absolute must in my opinion. 
Is this in progress already?

**Comment by aureel** [comment]
+1 for FTX guys. They now offer 0% maker fees as long as you stake at least 25 FTT (their coins).

**Comment by krisj** [comment]
+1 for FTX

**Comment by tomma100** [comment]
+1

**Comment by PtrckM** [comment]
Duplicate entry https://github.com/CoinAlpha/hummingbot/issues/2394

**Comment by donzthefonz** [comment]
+1

**Comment by Bobjfarid** [comment]
+1
