### ISSUE TITLE
error: RPC failed; curl 56 OpenSSL SSL_read: No error

### ISSUE THREAD

**Issue by normanlmfung** [CoinAlpha/hummingbot#2716]
hi team,
I'm new here. I downloaded the source code zip package. But i failed to git clone (Meaning I can't contribute to the project):
```
"C:\Users\xxxxx\AppData\Local\Programs\Git\bin\git.exe" clone -v --recurse-submodules --progress --branch development "https://github.com/CoinAlpha/hummingbot.git" "C:/Norman/dev/trading/hummingbot/development/hummingbot"
Cloning into 'C:/Norman/dev/trading/hummingbot/development/hummingbot'...
POST git-upload-pack (gzip 4025 to 2053 bytes)
remote: Enumerating objects: 101, done.
remote: Counting objects: 100% (101/101), done.
remote: Compressing objects: 100% (80/80), done.
remote: Total 50918 (delta 61), reused 34 (delta 21), pack-reused 50817
Receiving objects: 100% (50918/50918), 59.04 MiB | 248.00 KiB/s, done.
error: RPC failed; curl 56 OpenSSL SSL_read: No error
Resolving deltas: 100% (38691/38691), done.
Done

```
I already tried
```
git init
git config http.postBuffer 524288000
git config --global http.postBuffer 524288000
```

Thanks!

REF: https://stackoverflow.com/questions/46232906/git-clone-error-rpc-failed-curl-56-openssl-ssl-read-ssl-error-syscall-errno

**Comment by RC-13** [comment]
Hi @normanlmfung Does this issue occur as well if you clone the repo using SSH instead of downloading a zip copy?

**Comment by normanlmfung** [comment]
Yes, only when i tried to clone. Next thing I will try is to try clone from a VM in America (I am from Hong Kong)

**Comment by RC-13** [comment]
Hi @normanlmfung just wanted to follow up again if changing your VM's region help when cloning the hummingbot repo?

**Comment by rxlxrxsx** [comment]
Closing as there's no update from user.
