### ISSUE TITLE
10 second delay when cancelling orders on Huobi

### ISSUE THREAD

**Issue by rxlxrxsx** [CoinAlpha/hummingbot#2719]
**Describe the bug**

There's a 10 second delay on the bot when cancelling orders on Huobi exchange.

**Steps To Reproduce**

1. Run a pure market making bot on Huobi.
2. Set the order refresh time to your preferred amount (in my case, 30).
3. Disable order_refresh_tolerance_pct (-1) so that orders will get cancelled every cycle.
4. Notice that when it's time for orders to be cancelled there's a 10 second delay.

**Screenshots**

Notice that the open orders are still there after 30 seconds has passed.
![ht2](https://user-images.githubusercontent.com/64377055/102047205-d1cd6180-3e17-11eb-95e4-8654a64834b5.PNG)

Notice the time the orders were created. On the second screenshot the orders should be created on ``13:47:31`` when order refresh time is set to 30.
![ht1](https://user-images.githubusercontent.com/64377055/102047684-a72fd880-3e18-11eb-8a89-af8739a0fba1.PNG)
![ht3](https://user-images.githubusercontent.com/64377055/102047697-aac35f80-3e18-11eb-9ab2-8bb79274e551.PNG)

**Release version**

Installation type: Source
Version: dev-0.34.0
Machine: AWS EC2 instance
Operating system: Linux

**Attachments**

Log: [logs_testnet_btc-usdt.log](https://github.com/CoinAlpha/hummingbot/files/5686854/logs_testnet_btc-usdt.log)
Config: [huobi_ht-usdt.txt](https://github.com/CoinAlpha/hummingbot/files/5686857/huobi_ht-usdt.txt)

**Comment by mifeng** [comment]
Assess for 1 hour
