### ISSUE TITLE
[Refactor] Rename client_id to instance_tag

### ISSUE THREAD

**Issue by Nullably** [CoinAlpha/hummingbot#2722]
**Why**
client_id is a randomly generated 20 characters string (e.g. 20a4c722e8616dac0a85f1142f6c61a05ad59e7b) to identify HB instance. Since we started collecting this data (see #2548), to avoid having misunderstanding that this field can be used to identify user in anyway (it cannot) we should rename this field to instance_tag.

**Comment by mifeng** [comment]
If we change this, I would prefer `instance_id` since the word tag might add further confusion.
