### ISSUE TITLE
[BUG]export_trades command doesn't work

### ISSUE THREAD

**Issue by hongson1981** [CoinAlpha/hummingbot#273]
**Describe the bug**
export_trades command doesn't work

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
1. Install hummingbot from docker and start hummingbot
2. export trades this command: export_trades -p /home/son/test.csv
Expected result :
Trades should be exported to test.csv

Actual result:
No file to export, please check screenshot

**Screenshots**
![Screenshot from 2019-05-22 21-39-22](https://user-images.githubusercontent.com/29745336/58184034-8b1a9280-7cda-11e9-8812-02ba9b0fdbbe.png)

**Release version**
// Include your bot's version number (Can be found at the bottom left corner of your CLI).

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 
[hummingbot_logs_2019-05-22-14-32-53.log](https://github.com/CoinAlpha/hummingbot/files/3207890/hummingbot_logs_2019-05-22-14-32-53.log)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by yzhang1994** [comment]
@hongson1981 the errors in your logs come from another bug. That one is fixed. 

As for export_trades, I believe the command is only now available during a session (before stopping the bot). Will try to reproduce your issue.

**Comment by hongson1981** [comment]
@yzhang1994 I executed command export_trades during bot running and after stop bot. Please refer screenshot. There is not .csv file created
Please check again

**Comment by yzhang1994** [comment]
@hongson1981 I tested the command a bit. One possibility is that path you entered "/home/son" is not a valid directory (no directory named "son"). Please try to export it to "/home" or make the directory "son" first.

If that still doesn't work, I've created a PR for the bot to log the errors. Please pull the latest `dev/0.7.0` branch. It should log a specific error message and help us debug.

**Comment by yzhang1994** [comment]
This should have been fixed. Closing for now.
