### ISSUE TITLE
Can't set balancer_max_swaps to 1

### ISSUE THREAD

**Issue by mifeng** [CoinAlpha/hummingbot#2735]
<img width="435" alt="Screen Shot 2020-12-15 at 5 14 33 PM" src="https://user-images.githubusercontent.com/1795030/102291963-14b33600-3ef9-11eb-9f7d-4edeb0c0227d.png">

User should be able to set this param to minimum 1, inclusive.

**Comment by RC-13** [comment]
Working now on latest master (v0.34.0) and current dev (v0.35.0)
![image](https://user-images.githubusercontent.com/57189990/102604663-783e9d00-415f-11eb-8d68-5110d3158fb4.png)
