### ISSUE TITLE
Test and confirm potential issues with > 8 order levels on Binance

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#2751]
One of our users reported an issue when using more than 8 order levels.

![image](https://user-images.githubusercontent.com/50150287/102553706-421d0100-40fe-11eb-98e5-f09687bcf4e4.png)

Based on latest testing, we were able to run 10 orders each side on Binance without problems.

@RC-13 please have QA run this test again in the current version (v0.34), compare on different machines, and compare different strategy configuration e.g. run basic configs with 10 orders per side on cloud server vs. locally, run with some advanced params (inventory skew, order refresh tolerance, 15 seconds refresh time, etc.) on cloud vs. locally.

Create a summary of the results and add them here as comments.

**Comment by dennisocana** [comment]
Link to the Twitter thread.
https://twitter.com/memcardisfull/status/1339644661317701638

**Comment by sophos9** [comment]
Hello - I left the message on twitter. All information, logs and screenshots have been previously shared on Discord. Its been reproduced across multiple versions. Support in the Discord have all the info, would you like it posted here also?

**Comment by sophos9** [comment]
Strategy setup
![image](https://user-images.githubusercontent.com/3750100/102630730-d0b47100-4144-11eb-8220-10bce743b8c7.png)

@50 order levels
![image](https://user-images.githubusercontent.com/3750100/102630761-dad66f80-4144-11eb-83ad-eb74ded33b33.png)

@20 order levels
![image](https://user-images.githubusercontent.com/3750100/102630802-e45fd780-4144-11eb-8e8a-bb5501e17e11.png)

When quitting HB
![image](https://user-images.githubusercontent.com/3750100/102630895-06f1f080-4145-11eb-87a8-3fef31b6a96a.png)

HB Logs
[logs_BTC (1).log](https://github.com/CoinAlpha/hummingbot/files/5716517/logs_BTC.1.log)

Tested on HB 0.20, 0.33, 0.33.1 - same fault conditions. Tested on AWS, local LAN and various other IP's - No issues on other bots using websockets - no issues with Binance websockets

**Comment by RC-13** [comment]
Did a test on binance using 30 order levels, 30 sell orders and 6 buy orders are created at the same time and run the bot for more than an hour. This is done locally and using cloud server (docker and source), and the issue I've encountered is that the network randomly stop and immediately start during cancellation and creation of orders. Also if this happens, this is where the `cancel_all ` function intermittently fails to cancel all orders causing time out and causing stuck orders on the bot when `stop` command is send.

Test summary: (test done before and after Binance maintenance)
 - Test using COTI-BNB market on Binance
 - Order level tested: 10, 16, and 30
 - Order refresh time : 15, 30, and 120 sec
 - The following message randomly occurs on the logs, usually during creating and cancellation of order `Network status has changed to NetworkStatus.NOT_CONNECTED. Stopping networking...`  but bot recovers
 - If `stop` command is send, orders on the exchange gets cancelled but `cancel_all` function intermittently fails to cancel all orders on the bot
 ```
2020-12-22 07:36:32,550 - 1 - hummingbot.connector.exchange.binance.binance_exchange - NETWORK - Unexpected error cancelling orders.
Traceback (most recent call last):
  File "hummingbot/connector/exchange/binance/binance_exchange.pyx", line 935, in hummingbot.connector.exchange.binance.binance_exchange.BinanceExchange.cancel_all
    cancellation_results = await safe_gather(*tasks, return_exceptions=True)
  File "/home/hummingbot/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
    return await asyncio.gather(*args, **kwargs)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hummingbot/connector/exchange/binance/binance_exchange.pyx", line 934, in hummingbot.connector.exchange.binance.binance_exchange.BinanceExchange.cancel_all
    async with timeout(timeout_seconds):
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/async_timeout/__init__.py", line 55, in __aexit__
    self._do_exit(exc_type)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/async_timeout/__init__.py", line 92, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError
```

**Comment by RC-13** [comment]
As per support and QA discussion, we concluded that this issue is due to Hummingbot unable to handle the too much load, causing a disconnection on the websocket. And when bot recovers, it forgets some of the orders which then fails to cancel and getting stuck when bot is stopped.

**Comment by dennisocana** [comment]
Moving story to "in discussion" pipeline to discuss during next sync if we will work on this release.

**Comment by dennisocana** [comment]
@Nullably to take a look at the cause of this issue but not a high priority for this release.

**Comment by Nullably** [comment]
I still can't yet to reproduce this (ran 10 order levels), I'll keep this in icebox for now.
This is likely Binance connector issue, the problem might come up again when I am implementing the new Liquidity Mining strategy, so will revisit then.

**Comment by dennisocana** [comment]
Issue has gone stale and we did not receive any more reports about this problem. Will reopen if issue resurfaces.
