### ISSUE TITLE
Allow edits from maintainers not showing on pull requests

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#2752]
We advise external developers to enable "Allow edits from maintainers" on pull requests (also indicated in our [contributing guidelines](https://docs.hummingbot.io/developer/contributing/#general-workflow)) so we can sync their branch with `development` whenever needed. See related doc from GitHub below.

https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork

Some have reported e.g. https://github.com/CoinAlpha/hummingbot/pull/2692 that this button is not available for them.

**Comment by PtrckM** [comment]
**Test Result**

   - initial attempt to see if this option won't be available
      - create new github account and fork HB repo and try to submit PR : allow edit by maintainer is available 
      - fork PR from linq and create a PR to submit to HB repo : allow edit by maintainer is available 
      - check is always tick on **Allow edits by maintainers** when trying to submit a PR on both forks [hb](https://github.com/CoinAlpha/hummingbot) or [linq](https://github.com/Linq-Liquidity-Network/hummingbot)

![image](https://user-images.githubusercontent.com/54516858/102854053-999fd180-445c-11eb-8f78-312f06d201d5.png)
---

**Comment by dennisocana** [comment]
After further research, confirmed that these two pull requests https://github.com/CoinAlpha/hummingbot/pull/2323 https://github.com/CoinAlpha/hummingbot/pull/2692 did not have the option "Allow edits by maintainers" because they are submitted by users from a fork of [Linq's organization account](https://github.com/Linq-Liquidity-Network
) which is a limitation in GitHub.

https://github.community/t/how-can-we-enable-allow-edits-from-maintainers-by-default/2847
