### ISSUE TITLE
cosmetic bug on uniswap when checking balance

### ISSUE THREAD

**Issue by PtrckM** [CoinAlpha/hummingbot#2755]
**Describe the bug**
- when using `balance` command bot shows `balancer_connector - Update wallet balance` on the right pane even if you're using uniswap.
- 

**Steps To Reproduce**
- create amm strategy
- first connector select uniswap
- finish all prompt for the strategy
- `start` bot and/or use `balance` command

**Screenshots**
![image](https://user-images.githubusercontent.com/54516858/102594169-cbf5ba00-4150-11eb-80c6-c8898aab9c33.png)

**Release version**
0.34.0

**Comment by mifeng** [comment]
We should remove this message

**Comment by PtrckM** [comment]
currently fix on this [development branch](https://github.com/CoinAlpha/hummingbot/pull/2788#pullrequestreview-559849253)
- update wallet balance no longer shows
![image](https://user-images.githubusercontent.com/54516858/103333562-4c99ac00-4aa9-11eb-9d3d-a46bb1f907ba.png)
