### ISSUE TITLE
no token pair validator when using amm_arb strategy

### ISSUE THREAD

**Issue by PtrckM** [CoinAlpha/hummingbot#2756]
**Describe the bug**
- no token pair validator when using `amm_arb` strategy - protocol connectors: balancer, uniswap and terra

**Steps To Reproduce**
- use uniswap or balancer or terra as your connector

**Screenshots**
![image](https://user-images.githubusercontent.com/54516858/102595740-0fe9be80-4153-11eb-8fa2-ebb7688c8f15.png)
![image](https://user-images.githubusercontent.com/54516858/102595919-60611c00-4153-11eb-9744-639802faa8dd.png)
![image](https://user-images.githubusercontent.com/54516858/102596469-2d6b5800-4154-11eb-8ffc-2c814c88c37f.png)

**Release version**
0.34.0

**Attachments**
- n/a

**Comment by jason-hb** [comment]
Victor, please see if this issue persists or is resolved

**Comment by dennisocana** [comment]
Fixed in version 0.37
