### ISSUE TITLE
Change Kill switch functionality to allow the bot to resume trading after kill switch is triggered

### ISSUE THREAD

**Issue by Clanski0** [CoinAlpha/hummingbot#2761]
**Feature Suggestion**
// A succinct description of **how you want to achieve the desired behavior**.
// If you have looked at the code and know exactly what code changes are needed then please _consider submitting a pull request_ instead.

**Impact**
// A succinct description of **why you want the _desired behavior_** specified above.
The desired behaviour will allow me to resume trading after the kill switch rate has been reached and profitability check shows you are back under the rate

**Additional context**
Rather than only stopping the bot ... create a boolean ( kill_swith_resume?? ) to allow the bot to resume trading once the threshold has receded below the defined kill_switch_rate. This will allow unattended start after the rate has been breached.

**Comment by phbrgnomo** [comment]
Duplicated with #2497, closing.
