### ISSUE TITLE
Allow to control bid / ask order amount separately (from script)

### ISSUE THREAD

**Issue by bitphage** [CoinAlpha/hummingbot#2775]
## Why

To implement some advanced logic, I would like to control bid/ask order amounts independently, via script.

## What

1. A possible implementation is to add separate controls to PMM for `order_amount_bid` and `order_amount_ask` which will take precedence over `order_amount`, if set.
2. Pass these params to script interface

**Comment by zappra** [comment]
Can this not already be done with order override?

**Comment by bitphage** [comment]
Oooh you're right, `order_override` allows to set order amounts independently. I just missed it.
