### ISSUE TITLE
Miner website: can't login

### ISSUE THREAD

**Issue by luvhex** [CoinAlpha/hummingbot#2776]
"DID token cannot be validated"

kept having above error and tried with different browsers and clear cookies/cache

**Comment by dennisocana** [comment]
Thanks for reporting. Our back-end team has reached out to the Magic support team to resolve the issue. You can view the updates here in our statuspage https://status.hummingbot.io/

**Comment by JeremyKono** [comment]
The issue has been solved. You can now login to the Hummingbot Miners app. If you continue to encounter any error you can report it to us again. Thanks!
