### ISSUE TITLE
Support docker gateway-api for raspberrypi (arm)

### ISSUE THREAD

**Issue by MaxTitkov** [CoinAlpha/hummingbot#2781]
I had a problems with Gateway installation for amm-arbitrage strategy.
The 3-rd step of Quickstart guide describes the installation of Gateway, but when I tried to install it using create-gateway.sh there was an error because of folder names. The Hummingbot dir contain folders with names: "certs" and "conf", but script create-gateway.sh tries to find "hummingbot_certs" and "hummingbot_conf", and return an error: "hummingbot_conf & hummingbot_certs directory missing from path".
For solve it we just need to edit create-gateway.sh and change all "hummingbot_certs" and "hummingbot_conf", on "certs" and "conf".

The link to correct script: https://drive.google.com/file/d/1jfc2EcuEJKsJMNwkttz3ZbQpJ1BXOkmf/view?usp=sharing

**Comment by CalicaliT** [comment]
Hi, did you run a bot first and run `generate_certs`, before creating a gateway? Can you share a screenshot of the terminal showing the error you encountered?

**Comment by MaxTitkov** [comment]
![Screenshot from 2020-12-23 23-13-48](https://user-images.githubusercontent.com/25408344/103234014-a4bc9b00-494f-11eb-84eb-c427f9f511e6.png)

My OS:
```No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.10
Release:	20.10
Codename:	groovy
```
I installed las version of hummingbot v0.34.0 according this instructions: https://docs.hummingbot.io/installation/linux/#install-from-source-1

My computer is Raspberry Pi 400

**Comment by MaxTitkov** [comment]
Unfortunately, the Gateway doesn't work on ARM processor. There are logs of gateway container:
```
(base) mtitkov@mtitkov-desktop:~$ docker logs gateway-instance
standard_init_linux.go:211: exec user process caused "exec format error"
standard_init_linux.go:211: exec user process caused "exec format error"
standard_init_linux.go:211: exec user process caused "exec format error"
```

**Comment by JeremyKono** [comment]
As of the moment, the official scripts for installing gateway-instance via Source build has not yet been released. Gateway installation is only available via Docker build.

**Comment by PtrckM** [comment]
this is more like a feature request, currently gateway-api for docker doesn't support rpi (arm) yet. As a workaround

you can run [gateway-api from source build](https://github.com/CoinAlpha/gateway-api/blob/master/setup.md) and use [hummingbot source build](https://docs.hummingbot.io/installation/raspberry/#install-from-source) as well.

![image](https://user-images.githubusercontent.com/54516858/103279521-f4ab6880-4a08-11eb-8eac-2975884b94b7.png)
![image](https://user-images.githubusercontent.com/54516858/103279577-0a209280-4a09-11eb-9823-a6d6362860f8.png)

**Comment by MaxTitkov** [comment]
Thanks, I'll try it

**Comment by MaxTitkov** [comment]
I have this error:
'''
(base) user@user-desktop:~/expressjs/gateway-api$ yarn run start
yarn run v1.22.5
warning package.json: License should be a valid SPDX license expression
$ babel-node src/index.js
/home/user/expressjs/gateway-api/src/services/balancer.js:67
        throw Error("Invalid network ".concat(network));
        ^

Error: Invalid network {chain}
    at new Balancer (/home/user/expressjs/gateway-api/src/services/balancer.js:38:15)
    at Object.<anonymous> (/home/user/expressjs/gateway-api/src/routes/balancer.route.js:13:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Module._compile (/home/user/expressjs/gateway-api/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.newLoader [as .js] (/home/user/expressjs/gateway-api/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
'''

**Comment by PtrckM** [comment]
- make sure you have following versions when installing the gateway-api from source
![image](https://user-images.githubusercontent.com/54516858/103329636-74344880-4a98-11eb-8d29-4eb383215df4.png)
- to setup gateway
```
# clone repo
git clone https://github.com/CoinAlpha/gateway-api
# open repo folder
cd gateway-api
# install using yarn
yarn install
# copy sample env then edit the file
cp .env.example .env
# start gateway
yarn run start
```
- make sure you already created a SSL certificate + passphrase on your hummingbot by using `generate_certs` command
- make sure there are no typos or unwanted characters on your env file, here is an example of `.env`

```
APPNAME=Hummingbot Gateway API
NODE_ENV=dev
PORT=5000

# use only if ip whitelist is required for local or docker instance
# note that docker instance does not use 127.0.0.1 address
# ipv6 format for locahost ["::ffff:127.0.0.1", "::ffff:1", "fe80::1", "::1"]
IP_WHITELIST=

HUMMINGBOT_CLIENT_ID={client_id}

# Celo

# Terra
# - mainnet: https://lcd.terra.dev
# - mainnet chain: columbus-4
# - testnet: https://tequila-lcd.terra.dev
# - testnet chain: tequila-0004
TERRA_LCD_URL=https://lcd.terra.dev
TERRA_CHAIN=columbus-4

# Ethereum
# - chain: mainnet, kovan, etc
# - rpc url: infura or other rpc url
ETHEREUM_CHAIN=mainnet
ETHEREUM_RPC_URL=https://mainnet.infura.io/v3/9015591169a3413f8834f70cbc6147a7

# Balancer
# subgraph_chain
# Reference: https://docs.balancer.finance/sor/development#subgraph
# - mainnet: balancer
# - kovan: balancer-kovan
# Note: REACT_APP_SUBGRAPH_URL used by @balancer-labs/sor
REACT_APP_SUBGRAPH_URL=https://api.thegraph.com/subgraphs/name/balancer-labs/balancer

# exchange_proxy:
# Reference: https://docs.balancer.finance/smart-contracts/addresses
# - mainnet: 0x3E66B66Fd1d0b02fDa6C811Da9E0547970DB2f21
# - kovan: 0x4e67bf5bD28Dd4b570FBAFe11D0633eCbA2754Ec
EXCHANGE_PROXY=0x3E66B66Fd1d0b02fDa6C811Da9E0547970DB2f21

# Uniswap
# Reference: https://uniswap.org/docs/v2/smart-contracts/router02/
UNISWAP_ROUTER=0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D

# cert
CERT_PATH=/home/pi/hummingbot/certs
CERT_PASSPHRASE=pi
```

**Comment by MaxTitkov** [comment]
I did all changes according you're instructions. 
I have the next output:
```
(base) user@user-desktop:~/expressjs/gateway-api$ yarn run start
yarn run v1.22.5
warning package.json: License should be a valid SPDX license expression
$ babel-node src/index.js
server: gateway-api | port: 5000
 - ethereum-chain: mainnet
 - terra-chain: columbus-4



```
The bot still outputs me that Markets are not ready (

**Comment by PtrckM** [comment]
mind to share your amm_strategy configurations? you can do a screenshot after typing the command `config` on your bot, make sure to remove sensitive information like api, telegram token etc. thanks

**Comment by MaxTitkov** [comment]
This config I've copied from .yml file generated by bot. Is it enought? All API keys for binance, gas station, private key of ethereum and ethereum_rpc_url I tiped.
```
##########################################
###   AMM Arbitrage strategy config   ###
##########################################

template_version: 1
strategy: amm_arb

# The following configuations are only required for the AMM arbitrage trading strategy

# Connectors and markets parameters
connector_1: balancer
market_1: WETH-DAI
connector_2: binance
market_2: ETH-USDT

order_amount: 0.05

# Minimum profitability target required to place an order
# Expressed in percentage value, e.g. 1 = 1% target profit
min_profitability: 1.0

# A buffer for which to adjust order price for higher chance of the order getting filled.
# This is important for AMM which transaction takes a long time where a slippage is acceptable rather having
# the transaction get rejected. The submitted order price will be adjust higher (by percentage value) for buy order
# and lower for sell order. (Enter 1 for 1%)
market_1_slippage_buffer: 0.05

# A buffer to add to the price to account for slippage when buying/selling on second connector market
# (Enter 1 for 1%)
market_2_slippage_buffer: 0.0

# A flag (true/false), if true the bot submits both arbitrage taker orders (buy and sell) simultaneously
# If false, the bot will wait for first exchange order filled before submitting the other order
concurrent_orders_submission: false

```

**Comment by phbrgnomo** [comment]
Moving discussion to `gateway-v2` repo, [issue #9](https://github.com/CoinAlpha/gateway-v2/issues/9).
