### ISSUE TITLE
Accessing the Order Book in Scripts

### ISSUE THREAD

**Issue by MrBig1964** [CoinAlpha/hummingbot#2783]
A small fraction of the Order Book, including information about the price levels and volumes, are currently available using the order_book command.

It would be nice to let this information be accessible from scripts for the user to use it as an important source of information to script's logic.

Therefore, I propose that the ScriptBase Class should include a function that returns a python list or tuplet containing the current order book price levels and volumes.

**Comment by zappra** [comment]
+1 for this, would be a really useful feature

**Comment by keithbaum** [comment]
Hi @MrBig1964 and @zappra . Could you please provide me use case of the order_book? I have already implemented the code and was looking for ideas to build an example script. Thanks

**Comment by MrBig1964** [comment]
Hi @keithbaum,

The idea of directly accessing the order book would be to be able to
automatically adjust the ask and bid price (not the spread) using the
levels in the order book.
For instance, if you know the order book levels in real-time, one can
automatically adjust the ask and bid price to the 1st level, or the 2nd
level (or 3th and so on), disregarding the market depth and/or percentage
spreads.
The ask and bid price would be directly assigned to certain levels of the
order book.
Sorry for my bad english. I don't know if I was clear...

Best Regards

Luís Mota
luispedromota@gmail.com
