### ISSUE TITLE
Update Exchange Connector developer docs

### ISSUE THREAD

**Issue by mifeng** [CoinAlpha/hummingbot#2789]

**Comment by dennisocana** [comment]
Bumping all stories related to updating the developer documentation.

**Comment by dennisocana** [comment]
@CrimsonJacket to split the stories into exchange connector docs update, protocol connectors, derivatives, etc.

**Comment by dennisocana** [comment]
Resolved a conflict due to a recent change in `Callout.js` and merged the PR.
