### ISSUE TITLE
[BUG]HTTP status is 400,ERROR - API call error

### ISSUE THREAD

**Issue by beyoar** [CoinAlpha/hummingbot#279]
OS:  ubuntu 18.04
hummingbot version: Tag 0.6.0

[hummingbot_logs_2019-05-22-19-00-40.log](https://github.com/CoinAlpha/hummingbot/files/3210407/hummingbot_logs_2019-05-22-19-00-40.log)

[conf_cross_exchange_market_making_strategy_0.zip](https://github.com/CoinAlpha/hummingbot/files/3210409/conf_cross_exchange_market_making_strategy_0.zip)

**Comment by yzhang1994** [comment]
@beyoar I believe you are encountering the 400 API error because the trading-pair that you entered is invalid. Instead of `USDTETH` and `TUSD-WETH`, try using `ETHUSDT` for Binance and `WETH-TUSD` for DDEX. Let me know if you are still seeing the same problem

**Comment by beyoar** [comment]
@yzhang1994 
I changed config, but still seeing the problem.

Waiting for ddex market to get ready for trading. Please keep the bot running try to start again in a few minutes

![Screenshot from 2019-05-23 17-38-02](https://user-images.githubusercontent.com/47019932/58295759-abebf200-7d85-11e9-89eb-c8f45b027031.png)
[conf_cross_exchange_market_making_strategy_0 (copy).txt](https://github.com/CoinAlpha/hummingbot/files/3214636/conf_cross_exchange_market_making_strategy_0.copy.txt)
[hummingbot_logs_2019-05-23-17-28-18.log](https://github.com/CoinAlpha/hummingbot/files/3214637/hummingbot_logs_2019-05-23-17-28-18.log)

**Comment by chowryan** [comment]
closing old bug report. this issue should be fixed in latest build; please reopen if it's still an issue.
