### ISSUE TITLE
Investigate implementing `pause` and `resume` commands

### ISSUE THREAD

**Issue by phbrgnomo** [CoinAlpha/hummingbot#2796]
With version 0.34 the command `exit --suspend` was implemented, allowing the user to exit the bot without canceling the current pending orders created by the bot, and restore them with the command `start --restore`

The `--suspend` argument should also be available to be used with the `stop` command, so the user can "pause" the bot without exiting the bot instance.

**Comment by jason-hb** [comment]
I believe this feature has value and should not be removed from the codebase. It should be updated to be more useful. For example, some config changes require the bot to be stopped and restarted. This feature should allow stopping/starting the bot without canceling any hanging orders or resetting profit/loss/history calculations.

**Comment by dennisocana** [comment]
Discussed to get one of the developers to confirm that this is achievable without making a lot of changes to the strategies.
