### ISSUE TITLE
Bad Ethereum RPC URL

### ISSUE THREAD

**Issue by pointtoken** [CoinAlpha/hummingbot#28]
Tried using an Infura url with an api key: 

```https://mainnet.infura.io/v3/XXXXXX```

But this resulted in the "Bad Ethereum RPC URL" error. 

Also tried null value which also didn't work -- I thought I remember reading if you put nothing it would connect to a coinalpha node.

**Comment by KirkBallou** [comment]
@pointtoken  try manually adding the full url including 'https://'  I saw the same thing when just adding mainnet.infura. Once you add the full url it worked.

**Comment by pointtoken** [comment]
Indeed, I had to manually add it to the conf_global.yaml and then it worked.
