### ISSUE TITLE
Missing pairs with AUD qoute

### ISSUE THREAD

**Issue by rapcmia** [CoinAlpha/hummingbot#2801]
**Describe the bug**
User reported there are no tokens with AUD qoute available in Binance

**Steps To Reproduce**
1. Create Pure Market Making 
2. When selecting the market, no tokens with AUD qoute 

**Screenshots**
This does not show pairs with AUD qoute:
![image](https://user-images.githubusercontent.com/73840223/103768438-76c90c00-505d-11eb-93e1-dc2068e440a9.png)

These are the token user was expecting:
![image](https://user-images.githubusercontent.com/73840223/103768501-92341700-505d-11eb-8d62-9ff89dc58395.png)

**Release version**
v34

**Comment by RC-13** [comment]
fix on dev v0.35.0
