### ISSUE TITLE
K2 Connector

### ISSUE THREAD

**Issue by jason-hb** [CoinAlpha/hummingbot#2803]
## Exchange Details ✏️

- Connector for new centralized exchange K2
- URL: Not yet published. Telegram group established for development communication
- API docs: To be provided 
- Type: Centralized
- Requester details: CoinAlpha engagement

## Rationale / impact ✏️
Established financial company opening crypto trading desk. Will serve UK market

## Additional information ✏️
Committed to v0.36 delivery

---

⚠️ ***Note: do not modify below here***

## Developer notes

This feature request entails building a new exchange connector to allow Hummingbot to connect to an exchange that is currently not supported.

### Resources
- [Exchange connector developer guide](https://docs.hummingbot.io/developers/connectors/)
- [Discord forum](https://discord.hummingbot.io)

### Deliverables
1. A complete set of exchange connector files as listed [above](#developer-notes-resources).
2. Unit tests (see [existing unit tests](https://github.com/CoinAlpha/hummingbot/tree/master/test/integration)):
  1. Exchange market test ([example](https://github.com/CoinAlpha/hummingbot/blob/master/test/integration/test_binance_market.py))
  2. Order book tracker ([example](https://github.com/CoinAlpha/hummingbot/blob/master/test/integration/test_binance_order_book_tracker.py))
  3. User stream tracker ([example](https://github.com/CoinAlpha/hummingbot/blob/master/test/integration/test_binance_user_stream_tracker.py))
3. Documentation:
  1. Code commenting (particularly for any code that is materially different from the templates/examples)
  2. Any specific instructions for the use of that exchange connector ([example](https://docs.hummingbot.io/connectors/binance/))

### Required skills
- Python
- Previous Cython experience is a plus (optional)

**Comment by dennisocana** [comment]
Putting development of this connector on hold for now due to unresolved API issues on K2 end. Pushing to version 0.38 release planning.

**Comment by RC-13** [comment]
added on the development branch (v0.39.0)

**Comment by dennisocana** [comment]
C
