### ISSUE TITLE
`pnl` command not picking up STRAX trades

### ISSUE THREAD

**Issue by phbrgnomo** [CoinAlpha/hummingbot#2805]
**Describe the bug**
Title. 

**Steps To Reproduce**
Run `pmm` with STRAX-BUSD pair, execute `pnl` command.
...

**Screenshots**
![Captura de tela 2021-01-07 15 05 03](https://user-images.githubusercontent.com/34484531/103928060-0f14ce80-50fa-11eb-93e1-1cc09efe244f.png)

**Release version**
0.34

**Comment by rxlxrxsx** [comment]
Did you add `STRAX-BUSD` pair on your `conf_global.yml` on the list below? Mine is working fine.

<img width="1166" alt="Screen Shot 2021-01-08 at 10 42 13 AM" src="https://user-images.githubusercontent.com/64377055/103968363-acc1d980-519e-11eb-8dc2-72df5f8de79d.png">
<img width="450" alt="Screen Shot 2021-01-08 at 10 37 21 AM" src="https://user-images.githubusercontent.com/64377055/103968373-b1868d80-519e-11eb-9c0a-315620974adc.png">

**Comment by RC-13** [comment]
Closing this issue
