### ISSUE TITLE
Perpetual MM Hedge mode take profit parameters are the wrong way around

### ISSUE THREAD

**Issue by krisj** [CoinAlpha/hummingbot#2812]
**Describe the bug**

When using the Hedged mode with Perpetual MM strategy, the long_profit_taking_spread and short_profit_taking_spread settings seem to be working for the opposite orders. (Haven't tested this with One-Way mode)

**Steps To Reproduce**

create ANY Perpetual MM strategy on Binance and set different short/long spreads, you will notice that they are the wrong way around - short will set the take profit spread for the long positions and vice versa

**Release version**

dev-0.35.0

Optional: your discord username: onoff

**Comment by RC-13** [comment]
I believe this the expected behavior, to lock a profit and close a position once the profit taking order gets a fill. Similar behavior happens when in one-way mode, the difference is that if the existing order is the same side as the side the take profit order would be placed, it  will cancel the existing order in favor of the take profit limit order.

**Comment by krisj** [comment]
> I believe this the expected behavior, to lock a profit and close a position once the profit taking order gets a fill. Similar behavior happens when in one-way mode, the difference is that if the existing order is the same side as the side the take profit order would be placed, it will cancel the existing order in favor of the take profit limit order.

It's just my wording interpretation then I guess. 
However, while configuring the strategy the questions go like this: "At what spread from the entry price do you want to place a short order to reduce position?" This sets the value to long_profit_taking_spread variable. and vice versa for long. Which so far makes sense as I am expecting that the question implies there will be a short limit order placed to reduce the LONG position (which is also implied by the variable name in the config it writes to). But when running, the bot uses these variables for the opposing (at least that's what I expected) sides. So the long_profit_taking_spread actually sets the spread for the "Close Short" limit order which closes the SHORT position. 

See image for reference

![Capto_Capture 2021-01-14_12-16-28_p m](https://user-images.githubusercontent.com/590660/104590891-dded4e80-5663-11eb-9227-fa68bb4a9341.png)

In the end I don't really care how things are named as long as everything functions, which is does, but it did cause confusion for sure.

**Comment by RC-13** [comment]
Closing this ticket
