### ISSUE TITLE
Perpetual MM strategy suspend / restore not functioning properly

### ISSUE THREAD

**Issue by krisj** [CoinAlpha/hummingbot#2818]
**Describe the bug**
As per title - the exit --suspend / start --restore functionality is not working properly.
The exit --suspend seems to work ok, as in - it does not close the existing orders. But the start --resume seems to lose track of orders.

I am not sure if this is really a bug or the feature is not fully implemented for perps yet.

**Steps To Reproduce**

1. create perpetual strategy on Binance
2. run a hedged mode
3. wait till a position opens
4. exit with --suspend
5. start with --restore
6. orders don't seem to be picked up by HB

**Release version**
dev-0.35.0

**Optional: your discord username: onoff

**Comment by vic-en** [comment]
This feature wasn't implemented in the perpetual strategy.

**Comment by krisj** [comment]
> This feature wasn't implemented in the perpetual strategy.

cool, I thought as much. It would be super useful of course...

**Comment by RC-13** [comment]
Closing this case for now since feature is currently not implemented
