### ISSUE TITLE
Check heatbeat reporting completeness

### ISSUE THREAD

**Issue by mifeng** [CoinAlpha/hummingbot#2819]
# Why

The heartbeat aggregate data reporting feature we added in v0.34 may not be logging complete trade activity. I've been running a Celo-Bittrex `celo-arb` bot over the past 3 days, and noticed 2 issues:

1. No data for trades on the `celo` connector
2. Aggregated daily trade volume on the Bittrex connector is undercounted

Client has done 10+ trades over the past 2 days:
![Screen Shot 2021-01-09 at 7.37.55 AM.png](https://images.zenhubusercontent.com/545072957c6ccc6277a5c098/c104706a-0dbf-45cd-bae6-866d58ea4451)

DataDog only shows 1 trade on each day:
![Screen Shot 2021-01-09 at 7.38.05 AM.png](https://images.zenhubusercontent.com/545072957c6ccc6277a5c098/bfa9fbf3-d5d1-4ef6-a628-a702960264cf)

# What

@Nullably is the lack of Celo data due to the fact that the current Celo implementation doesn't store trades in local db? 

@RC-13: please check the completeness issue:
- Run test PMM bots on a few different exchanges for 1 week
- Assess in Datadog whether trade count and volume are captured correctly afterwards

**Comment by RC-13** [comment]
Test bots are now running and will update after a week

**Comment by RC-13** [comment]
The heatbeat reporting shows inconsistent data for Terra test bot ( no filled trades yet for Balancer and Uniswap bots). 
![image](https://user-images.githubusercontent.com/57189990/104866443-8c9dd180-5979-11eb-8491-8a5162e9aebb.png)
data dog shows 3 trade count which is suppose to be 10 trades in total:
![image](https://user-images.githubusercontent.com/57189990/104866766-501ea580-597a-11eb-966f-abe6b2bb9dcc.png)
![image](https://user-images.githubusercontent.com/57189990/104866842-7cd2bd00-597a-11eb-83c6-45c83b3363c6.png)

Jason's bot shows inconsistent data as well, on the reporting, we can only see 3 trades from Binance:
![Terra-binance2](https://user-images.githubusercontent.com/57189990/104867192-4a758f80-597b-11eb-8887-41167239072b.PNG)

Centralize exchange appears to show correct info, though we see slight difference in count when checking 4 days reporting and up.

**Comment by Nullably** [comment]
@mifeng 
> @Nullably is the lack of Celo data due to the fact that the current Celo implementation doesn't store trades in local db?

This is because we haven't implemented Celo connector and Celo Gateway yet, so the trades have never been stored on sqlite db.
There was a ticket for adding HB trades on Celo blockchain. 

On the trade data not being captured fully on Terra, I'm not sure what happened, will need to investigate.

**Comment by jason-hb** [comment]
To assist with troubleshooting Terra, I ran a bot with negative profitability to have it execute several trades. Taker exchange was Binance. This occurred on 1/14/2021. The Hummingb[Uploading... logs_conf_amm_arb_1.log.2021-01-15.txt]ot Instance ID#: e2630a02a43d567e5d0626c3038b58e76b1fd184. Trade logs attached

**Comment by Nullably** [comment]
@jason-hb 
From your log file, it's clear that you might have stopped the strategy before the heartbeat interval (the default is once every 5 minutes), so the bot didn't get a chance to report the filled trades yet. @RC-13 Please be aware of this as well when you test, did you set min_profitability to negative? and did you stop the strategy before the heartbeat interval?

I have just tested this, and the trade count and filled order volume is reported correctly on DataDog, though only 1 trade.
![image.png](https://images.zenhubusercontent.com/5f636ed10127e0d4e0d84d8e/f5cc9276-2fb5-4bc7-a5fa-21ccba139c9c)

**Comment by RC-13** [comment]
@Nullably Yes, I set the profitability to negative value. The first trade, that reflected on the bot, I believe I did left the bot running for few minutes. For the other trades, yup, I ended up stopping after getting multiple trades. Will re-test this out again without immediately stopping the bot.

**Comment by Nullably** [comment]
@RC-13 Actually, some correction - stopping the strategy is fine as long as you don't exit the bot nor restart the strategy. Restarting the strategy causes the heartbeat process to restart anew (restart the heartbeat clock and only new events are to be reported) - this is probably the actual problem, I am looking into fixing this now.

**Comment by jason-hb** [comment]
If it helps, here are the steps performed (to the best of my memory):

1. Change profitability to -1%
2. Stop and start strategy (didn't exit the instance or import a new strategy file)
3. Waiting on bot to trade few times (only took a minute or two)
4. Stopped bot and changed profitability back to 3%
5. Started bot
