### ISSUE TITLE
Stuck on cancelling. Never-ending attempts to cancel same order ids

### ISSUE THREAD

**Issue by oconcept** [CoinAlpha/hummingbot#2821]
**Describe the bug**

Pure market making bot works for a few minutes, then repeatedly tries to cancel orders with the same order ids, and does not place any new orders. Only way to refresh is to stop and re-start. 

paper_trade_enabled : TRUE
order_optimization_enabled is set to FALSE ( as related to another previously reported issue)

Appreciate your assistance!

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: 

strategy: pure_market_making
exchange: binance
market: LTC-ETH
bid_spread: 0.02
ask_spread: 0.02
minimum_spread: -100.0
order_refresh_time: 5.0
max_order_age: 1800.0
order_refresh_tolerance_pct: 0.02
order_amount: 2.0
price_ceiling: -1.0
price_floor: -1.0
ping_pong_enabled: false
inventory_skew_enabled: false
inventory_target_base_pct: 50.0
inventory_range_multiplier: 1.0
order_levels: 1
order_level_amount: 0.2
order_level_spread: 0.02
filled_order_delay: 1.0
hanging_orders_enabled: true
hanging_orders_cancel_pct: 0.51
order_optimization_enabled: false
ask_order_optimization_depth: 0.0
bid_order_optimization_depth: 0.0
add_transaction_costs: true
price_source: current_market
price_type: mid_price
price_source_exchange:
price_source_market:
price_source_custom_api:
take_if_crossed: false

2. Start the bot using 'start' command

**Screenshots**

![Screen Shot 2021-01-09 at 12 14 53 PM](https://user-images.githubusercontent.com/6397671/104105960-06e69b80-5280-11eb-98b1-e2ee6629b109.png)

**Release version**

Version 0.34.0

**Attachments**

logs-
[logs_conf_pure_mm_test_1.log](https://github.com/CoinAlpha/hummingbot/files/5791612/logs_conf_pure_mm_test_1.log)

configuration-
[conf.txt](https://github.com/CoinAlpha/hummingbot/files/5791613/conf.txt)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by oconcept** [comment]
I chatted with Jeremy Kono in Discord, and we tried setting order_refresh_tolerance to -1, and filled_order_delay to 10, and the issue still occurred. 

Jeremy was able to reproduce this on his end. 

Would be great to resolve this for newcomers who want to test strategies in paper mode. Thanks

**Comment by oconcept** [comment]
I also just tried a different pair to see if there was any difference, not that it would make much sense, but I tried ETC-BTC, and the same issue occurred.

**Comment by RC-13** [comment]
This is a known issue for paper trade and can be easily replicated when you have hanging order. I'll be closing this case in favor for the first reported issue:  #2233 to avoid duplicate.
