### ISSUE TITLE
Failed Test PR#2 - No funding payment on logs/log pane

### ISSUE THREAD

**Issue by gerald-hb** [CoinAlpha/hummingbot#283]
## Summary and Screenshots
No funding message reflected on logs and or on the log pane. It seems that no funding payment is done.
There is an open position on the exchange
![image](https://user-images.githubusercontent.com/84826167/193397803-308482db-fdd5-45d1-94d8-4b3382de329e.png)
Checked on 7:00am and 3:00pm UTC+8

## Steps To Reproduce
1.Clone and install featured branch
2.Create perpetual market making (set tighter spread to get easily filled order and open a position)
3.Observe the logpane and checked logs during funding time ( Checked on 7:00am and 3:00pm UTC+8)

## Test Result Comparison
new connector

## Attachments

[bitgetfunding.zip](https://github.com/CoinAlpha/hummingbot/files/9689806/bitgetfunding.zip)

**Comment by PtrckM** [comment]
Adding more info on the issue. Export data from exchange during funding time
![image](https://user-images.githubusercontent.com/54516858/193399416-9a058cdd-248c-479a-bc0e-31d8cbf326b1.png)

**Comment by rxlxrxsx** [comment]
Tested on commit [243b1f8](https://github.com/CoinAlpha/hummingbot-bitget/pull/2/commits/243b1f84c8813d6768e05b3bc46953e8fe536ab5) but still not getting any funding payment message while a position is open. cc: @aarmoa 

<img width="1042" alt="Screen Shot 2022-10-05 at 11 06 10 PM" src="https://user-images.githubusercontent.com/64377055/194098032-4309bd2b-fa09-4874-8b5b-e5c72b1a693a.png">

Logs: [logs_conf_perpetual_market_making_1.log](https://github.com/CoinAlpha/hummingbot/files/9716907/logs_conf_perpetual_market_making_1.log)

**Comment by aarmoa** [comment]
@PtrckM I found an issue in the PerpetualDerivativePyBase class. The funding fees were ignored if the amount was negative (when the user has to pay the exchange)

**Comment by gerald-hb** [comment]
Fixed on commit (a94075986f0ddee3a5789204042570cffd7fb572)
![image](https://user-images.githubusercontent.com/84826167/194434017-982e367c-c171-474a-b9b3-c9e95a8b0ed9.png)
