### ISSUE TITLE
order_tolerance_refresh not work if zero balance quote

### ISSUE THREAD

**Issue by tomma100** [CoinAlpha/hummingbot#2836]
**Describe the bug**

When no balance in in base order_refresh_tolerance does not force orders to cancel and move up with the price

**Steps To Reproduce**

start a bot with only quote currency and the following config 

![image](https://user-images.githubusercontent.com/19289703/104413586-7a312b80-5566-11eb-857e-04f00a8694d9.png)

as you can see if the quote currency is 0 and the remaining order is over 0.2% spreed it ought to be cancelled and replaced as the refresh rate is set to 1 second

the problem is that if price continues to go up the orders sit an ever increasing distance away from the spread

**Release version**

0.34.0

**Attachments**

config file above

**Optional: your discord username:**

tomma100

**Comment by RC-13** [comment]
closing duplicate ticket, same with #2837
