### ISSUE TITLE
Add USD trade volume to data reporting

### ISSUE THREAD

**Issue by mifeng** [CoinAlpha/hummingbot#2841]
# Why

Since trade volume is denominated in quote token, it's hard to get a complete picture of daily fill volume coming from Hummingbot clients

# What

Use the USD conversion that @Nullably added to `balance` command to convert record trade volumes to USD, and add to data reporting.

# Acceptance
* Run bots on different connectors for 48 hours and confirm that USD fill volume is correctly calculated in Datadog

**Comment by phbrgnomo** [comment]
Moved discussion to #2914.

Closing Issue
