### ISSUE TITLE
Add stop_loss to Perpetual MM strategy

### ISSUE THREAD

**Issue by vic-en** [CoinAlpha/hummingbot#2842]
**Feature Suggestion**
The profit_taking position mgmt feature appears to be stuck if market doesn't move towards the take_profit order.
Adding a stop_loss parameter to the strategy would allow positions to be closed when it reaches the set stop_loss percent when using profit_taking position mgmt feature. It would also be used to increase the loss tolerance of the trailing_stop feature which would normally close any open position immediately loss is detected.

**Impact**
- Add stop_loss parameter to Perpetual Market Making strategy.

**Comment by krisj** [comment]
similar configurability for LIMIT or MARKET would be great!
