### ISSUE TITLE
Mandala Connector

### ISSUE THREAD

**Issue by jason-hb** [CoinAlpha/hummingbot#2847]
**Connector type** : Governance
**Fee share** : N/A
**Developer** : Mandala

---

⚠️ ***Note: do not modify below here***

## Developer notes

This feature request entails building a new exchange connector to allow Hummingbot to connect to an exchange that is currently not supported.

### Resources
- [Exchange connector developer guide](https://docs.hummingbot.io/developers/connectors/)
- [Discord forum](https://discord.hummingbot.io)

### Deliverables
1. A complete set of exchange connector files as listed [above](#developer-notes-resources).
2. Unit tests (see [existing unit tests](https://github.com/CoinAlpha/hummingbot/tree/master/test/integration)):
  1. Exchange market test ([example](https://github.com/CoinAlpha/hummingbot/blob/master/test/integration/test_binance_market.py))
  2. Order book tracker ([example](https://github.com/CoinAlpha/hummingbot/blob/master/test/integration/test_binance_order_book_tracker.py))
  3. User stream tracker ([example](https://github.com/CoinAlpha/hummingbot/blob/master/test/integration/test_binance_user_stream_tracker.py))
3. Documentation:
  1. Code commenting (particularly for any code that is materially different from the templates/examples)
  2. Any specific instructions for the use of that exchange connector ([example](https://docs.hummingbot.io/connectors/binance/))

### Required skills
- Python
- Previous Cython experience is a plus (optional)

**Comment by dennisocana** [comment]
The pull request linked to this story is incomplete and outdated. Closing for now due to no progress for four months. Feel free to reopen when work will be resumed for this connector.

https://www.reddit.com/r/Hummingbot/comments/n0tyte/announcement_review_stoppage_on_tokocrypto_and/

**Comment by gitr0n1n** [comment]
Request to reopen this PR now that the API work has been completed and the roadblock is removed.

https://medium.com/mandalaex/mandala-exchange-api-now-live-1713cb151c28

@dennisocana @jason-hb
