### ISSUE TITLE
0.35 - Used Telegram API Depreciated Alert When Starting

### ISSUE THREAD

**Issue by rogueops** [CoinAlpha/hummingbot#2850]
**Describe the bug**
not a bug, but a warning message that pops up when starting the bot that the used telegram API is depreciated, can be seen when starting the bot in there terminal on the right

**Steps To Reproduce**
start a bot and watch for the depreciated message that pops up when connecting to telegram in the right window

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: n/a
2. Start the bot using this command: start

**Release version**
0.35

Optional: your discord username: n/a

**Comment by RC-13** [comment]
This is a known concern that occurred when telegram made an [upgrade](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Transition-guide-to-Version-12.0). Currently the telegram integration we have is a bit of a hack and our team plans to improve the integration in the future. For now, you can ignore this message as it doesn't affect your bot  and your strategy, hummingbot and telegram still works despite that message.

**Comment by rogueops** [comment]
Good to know, thanks, you can close
