### ISSUE TITLE
Refactor - Remove mock testing on Crypto.com connector. 

### ISSUE THREAD

**Issue by Nullably** [CoinAlpha/hummingbot#2852]
**Why**
As the API mock unit tests are no longer required for new connectors and Crypto.com connector code base serves as a model for new connector developers to follow, we can remove API mock testing from its unit tests.

**Notes**
* Unit tests are still required for new connectors, they can be run with exchange credential, just the mock part is to be removed.

**Comment by dennisocana** [comment]
Completed in version 0.37.0
