### ISSUE TITLE
Orders not removed while paper testing cross market marking strategy

### ISSUE THREAD

**Issue by moderndanc3** [CoinAlpha/hummingbot#2854]
**Describe the bug**
When testing Cross Exchange Market Making stategy while **paper trading**, hummingbot can't remove orders when the min_profitability condition is no longer met.

it keeps returning the message:

`- cross_exchange_market_making - (XXX-YYY) Limit ask order at XXX $$$ is no longer profitable. Removing the order.`

but the orders stay in place.

**Exchanges: Binance (taker); Kucoin (maker)**.

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):
1. Create Cross exhange market making strategy using a Binance as take exchange and Kucoin as maker exchange.
2. Leave active_order_canceling: true, or set Leave active_order_canceling: false and cancel_order_threshold: to any desired value.
3. Start the strategy, wait for order removal (set limit_order_min_expiration: to a low value to cut the wait time)

**Screenshots**
![image](https://user-images.githubusercontent.com/77745436/105212661-0a1a3b00-5b4e-11eb-9b23-8a61a95b8222.png)

**Release version**
0.35.0

**Attachments**
config file 
[conf_CROSS_BINKUC_ETH-DAI_1.txt](https://github.com/CoinAlpha/hummingbot/files/5844202/conf_CROSS_BINKUC_ETH-DAI_1.txt)

log file
[hummingbot_logs.txt](https://github.com/CoinAlpha/hummingbot/files/5844207/hummingbot_logs.txt)

**Optional: your discord username: moderndance **

**Comment by RC-13** [comment]
This concern has been addressed by pull request #2911 and now available on v0.36.0

**Comment by dennisocana** [comment]
Testing

**Comment by dennisocana** [comment]
Linked corresponding PR to this issue in Zenhub.
