### ISSUE TITLE
Tokens longer than 3 characters are not detected when configuring market on Bitfinex

### ISSUE THREAD

**Issue by rxlxrxsx** [CoinAlpha/hummingbot#2863]
**Describe the bug**

When configuring the parameter `market`, base tokens longer than 3 characters are not detected and accepted on Bitfinex.

**Steps To Reproduce**

Setup a bot and try to configure the `market` parameter, notice that it doesn't detect base tokens longer than 3 characters.

**Screenshots**

Example:

https://trading.bitfinex.com/t/EGLD:USD
<img width="659" alt="Screen Shot 2021-01-24 at 12 21 07 PM" src="https://user-images.githubusercontent.com/64377055/105621189-f4ec2780-5e3f-11eb-9456-130a9d5056e4.png">
https://trading.bitfinex.com/t/AVAX:USD
<img width="654" alt="Screen Shot 2021-01-24 at 12 22 17 PM" src="https://user-images.githubusercontent.com/64377055/105621192-fa497200-5e3f-11eb-988a-5c2263c94754.png">
https://trading.bitfinex.com/t/RINGX:USD
<img width="667" alt="Screen Shot 2021-01-24 at 12 24 22 PM" src="https://user-images.githubusercontent.com/64377055/105621196-fe758f80-5e3f-11eb-9012-0adf1a09fa6a.png">

**Release version**

v0.35.0

**Comment by CrimsonJacket** [comment]
Is this still an issue in `development`?

**Comment by RC-13** [comment]
fix on dev v0.36
