### ISSUE TITLE
Bitfinex Total not adding USDT

### ISSUE THREAD

**Issue by mccrudd3n** [CoinAlpha/hummingbot#2864]
**Describe the bug**
USDT not being summed with total value - See image

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
1. Add USDT into bitfinex
2. Start the bot
3. check balance using the `balance` command on the terminal
4. Total value shows incorrect total value

**Screenshots**
![image](https://user-images.githubusercontent.com/49352991/105630582-f4ed2700-5e41-11eb-86d7-0ce945337e2b.png)

**Release version**
0.35.0
**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

Griffin #2833

**Comment by RC-13** [comment]
same issue with #2773
