### ISSUE TITLE
history command error in binance testnet

### ISSUE THREAD

**Issue by glenntomas** [CoinAlpha/hummingbot#2868]
**Describe the bug**
User reported that `history` command doesn't work in perpetual market making strategy in `binance_perpetual_testnet`

**Steps To Reproduce**
- create `perpetual_market_making` strategy
- derivative `binance_perpetual_testnet`
- set `one_way` position mode and `profit_taking` position management and let orders gets filled
- run `history` command and nothing shows
- on logs pane this error show 

`2021-01-25 01:32:18,317 - 1 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 'int' object has no attribute 'is_nan'`

**Screenshots**

![image](https://user-images.githubusercontent.com/73885708/105655252-abacde00-5efa-11eb-86d0-ac64cadb881d.png)

![image](https://user-images.githubusercontent.com/73885708/105655123-6be5f680-5efa-11eb-98be-2a35f43a33b0.png)

**Attachments**
[logs_hawkscoinhood.log](https://github.com/CoinAlpha/hummingbot/files/5864454/logs_hawkscoinhood.log)

**Release version**
v0.35.0

**Discord username:**
HawksCoinHood

**Comment by rapcmia** [comment]
Tried the same config with the user not getting error.
![image](https://user-images.githubusercontent.com/73840223/105688696-dd429b00-5f34-11eb-83b2-763409a32904.png)

**Comment by RC-13** [comment]
Closing ticket, the issue has been resolved on v0.36.0.
