### ISSUE TITLE
Docker issue or hummingbot issue(or possibly by design)

### ISSUE THREAD

**Issue by rogueops** [CoinAlpha/hummingbot#2882]
When I wanted to run multiple bots I saw docker was optimized for this purpose so I setup Ubuntu and installed docker and then created the bots and all is well. When I was attached to the first hummingbot container and I was setting up the exchange connection I went to paste the API secret which is quite long and it won't paste, nothing would. Is this a docker issue/design or hummingbot?

**Comment by RC-13** [comment]
@rogueops I believe this was an issue with python module, if I remember it right, there was a pending issue with Paperclip library, however, here's how you can paste your API key inside Hummingbot: https://hummingbot.zendesk.com/hc/en-us/articles/900004871203-Copy-and-paste-your-API-keys or you can try `Shift key + right click`

**Comment by rogueops** [comment]
perfect, thanks! I had to do it 4 times before I got it right, they are just so complex and long and unlike the telegram token you cant see what you typed so its prone to fat fingers. This looks like what I need for when I create my next bot. Thanks again. Closing ticket now that I have a workaround.
