### ISSUE TITLE
Bitfinex USD quote available balance is not updating

### ISSUE THREAD

**Issue by rxlxrxsx** [CoinAlpha/hummingbot#2884]
**Describe the bug**
Bitfinex USD quote available balance is not updating when there are open orders. So far this only happens when using USD token as quote.
<img width="531" alt="Screen Shot 2021-01-28 at 4 39 27 PM" src="https://user-images.githubusercontent.com/64377055/106116788-4a506d80-618d-11eb-9ece-cfde791f4881.png">

There are also instances that when a buy order gets filled, available balance turns to 0 and will not create buy orders anymore. Same as above, this only happens when using USD token as quote. Can also confirm that there were no stuck orders on the exchange. Current workaround is to restart the strategy.

<img width="551" alt="Screen Shot 2021-01-28 at 5 26 46 PM" src="https://user-images.githubusercontent.com/64377055/106117650-32c5b480-618e-11eb-8823-ea5631a8a1e0.png">

**Steps To Reproduce**
1. Run a pure market making bot using Bitfinex. 
2. Choose a market pair with quote as USD.
3. Notice that available balance doesn't change even when there's an open order.

**Release version**
development-0.36.0

**Attachments**
Logs: [bitfinex.log](https://github.com/CoinAlpha/hummingbot/files/5886180/bitfinex.log)
Config: [bitfinex.txt](https://github.com/CoinAlpha/hummingbot/files/5886186/bitfinex.txt)

**Comment by RC-13** [comment]
Resolved on v0.36.0

**Comment by rxlxrxsx** [comment]
Closing as issue is no longer happening on latest version (0.37.1)

<img width="544" alt="Screen Shot 2021-03-11 at 8 00 51 AM" src="https://user-images.githubusercontent.com/64377055/110716290-d0a6a780-8241-11eb-8294-d4a8f905815d.png">
<img width="536" alt="Screen Shot 2021-03-11 at 8 02 21 AM" src="https://user-images.githubusercontent.com/64377055/110716300-d4d2c500-8241-11eb-9175-ffc4f246dd2f.png">
