### ISSUE TITLE
Failed Test PR#286 - Missing script / Doubt ticket

### ISSUE THREAD

**Issue by Deepali6997** [CoinAlpha/hummingbot#289]
**Summary and Screenshots**
After cloning it is observed that setup folder only has **generate.conf.sh**. This leads to getting an error when following command is run as shown below :

`./generate_ssl_conf.sh -f $GATEWAY_CONF_FOLDER -c $GATEWAY_CA_FILE -e $GATEWAY_SERVER_CERT_FILE -k $GATEWAY_SERVER_KEY_FILE`

<img width="1656" alt="Screenshot 2022-10-21 at 9 48 15 PM" src="https://user-images.githubusercontent.com/100112937/197242408-4d097dc8-16bb-46e5-9cd0-3feab95c255a.png">

The only workaround is to copy-pasting generate_ssl_conf from a different PR. 
Wanted to know if this is intended?

**Steps To Reproduce**
1. Clone and install clean instance of hummingbot
2. Open separate terminal and run the usual commands to make gateway run from source build
3. Run `./generate_ssl_conf.sh -f $GATEWAY_CONF_FOLDER -c $GATEWAY_CA_FILE -e $GATEWAY_SERVER_CERT_FILE -k $GATEWAY_SERVER_KEY_FILE`
4. Observe the log pane 

**Test Result Comparison**
Same folder structure when cloning master branch of foundation

**Attachments**
No attachment for this.

**Comment by RC-13** [comment]
@Deepali6997 please update this ticket once you're back. Add a comment of what you have discussed with Daniel so that we can close this ticket and create a shortcut ticket instead.

**Comment by RC-13** [comment]
I spoke to QA Ralph on the foundation side, the missing files were removed on one of their fix and cleanup PR (https://github.com/hummingbot/hummingbot/pull/5622) apparently he forgot why the files were removed. I will update my comment in case he recall the reason. @Deepali6997 I will now close this ticket but feel free to add a comment, if there are other information shared to you by Daniel.
