### ISSUE TITLE
OkEx fails to cancel and clear orders

### ISSUE THREAD

**Issue by RC-13** [CoinAlpha/hummingbot#2890]
**Describe the bug**
Bot failed to clear/cancel hanging order that was lost after encountering network issue.  Even after doing force exit, the lost orders are getting restored but not submitted on the exchange and the following error keeps coming up:
```
2021-01-29 11:58:11,057 - 17372 - hummingbot.connector.exchange.okex.okex_exchange - NETWORK - Unexpected error while fetching account updates.
Traceback (most recent call last):
  File "hummingbot/connector/exchange/okex/okex_exchange.pyx", line 513, in hummingbot.connector.exchange.okex.okex_exchange.OkexExchange._status_polling_loop
    await safe_gather(
  File "/home/ubuntu/okex/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
    return await asyncio.gather(*args, **kwargs)
  File "hummingbot/connector/exchange/okex/okex_exchange.pyx", line 408, in _update_order_status
    order_update = await self.get_order_status(exchange_order_id, tracked_order.trading_pair)
  File "hummingbot/connector/exchange/okex/okex_exchange.pyx", line 396, in get_order_status
    return await self._api_request("GET", path_url=path_url, is_auth_required=True)
  File "hummingbot/connector/exchange/okex/okex_exchange.pyx", line 292, in _api_request
    async with response_coro as response:
  File "hummingbot/connector/exchange/okex/okex_exchange.pyx", line 294, in hummingbot.connector.exchange.okex.okex_exchange.OkexExchange._api_request
    raise IOError(f"Error fetching data from {url}. Response: {await response.json()}.")
OSError: Error fetching data from https://www.okex.com/api/spot/v3/orders/-1?instrument_id=ETH-USDT. Response: {'error_message': '{order_id}Parameter value filling error', 'code': 30024, 'error_code': '30024', 'message': '{order_id}Parameter value filling error'}.
```
After renaming the data base file, bot returns back to normal.

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
1. Create a pure market making strategy with hanging order or without hanging order
2. Start strategy, and wait for orders to be created.
3. Disconnect from wifi for at least 2-5 minutes, then resume connection.
4.  Notice that there will be a network error and it will fail to cancel existing orders.
5. Stop and exit strategy and you will be prompted to do force exit.
6.  Import strategy and start then check status, you will notice that the previously created order will be restored and marked as hanging orders.
...

**Screenshots**
before restarting the bot:
![OKEx](https://user-images.githubusercontent.com/57189990/106273826-3d577b00-626e-11eb-881c-7d1959b833f5.PNG)
after restarting the bot:
![OKEx1](https://user-images.githubusercontent.com/57189990/106273842-43e5f280-626e-11eb-9e57-a94cbd08721a.PNG)

screenshot after manually disconnecting from internet:
exiting from existing strategy:
![Okex1](https://user-images.githubusercontent.com/57189990/107182652-1c361d80-6a18-11eb-90b4-ec9ea9304ef2.PNG)

after importing strategy:
![Okex2](https://user-images.githubusercontent.com/57189990/107182669-22c49500-6a18-11eb-94c1-855ffd103b9f.PNG)

**Release version**
```
branch: development 0.36.0
commit bcf83e17a1517b42b2353a53bdbabae1532d97c7 
Date:   Thu Jan 7 19:25:21 2021 -0800

environment:  Source build via cloud
```

**Attachments**
[Okex files.zip](https://github.com/CoinAlpha/hummingbot/files/5893737/Okex.files.zip)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by RC-13** [comment]
Issue re-occurred, this time a normal order was was affected. The bot keeps attempting to refresh and re-create an order that was already been canceled
![okex-failed-to-cancel](https://user-images.githubusercontent.com/57189990/114166712-ae976680-9960-11eb-9e70-a51ebfa9f41e.png)
[logs_okex_eth-usdt.log](https://github.com/CoinAlpha/hummingbot/files/6284988/logs_okex_eth-usdt.log)
v0.38.0

**Comment by keithbaum** [comment]
This should not occur with the recent update

**Comment by RC-13** [comment]
@keithbaum  I'm still seeing this issue on the Okex long-term test bot that we have. Tried a clean copy running on the latest development branch  `commit 4c35bac6ad3f98de86f5c4348fe3a85ac875dd37` and still see the issue. This time no error given, you can simply start a basic PMM strategy and stop once the order gets created, then restart the strategy and run `status`, one of the previously cancelled order will become a hanging order.

**Comment by RC-13** [comment]
Re-test issue again by disconnecting and connecting back from the internet after bot created a new order and bot was able to pick up previous order and cancels it accordingly. Closing ticket now.
