### ISSUE TITLE
"Empty DataFrame" output in arbitrage format_status

### ISSUE THREAD

**Issue by TheHolyRoger** [CoinAlpha/hummingbot#2892]
**Describe the bug**
So far I've only experienced this using paper trade - the format_status output in the debug console displays "Empty DataFrame" where market orders should be (When there are none)

**Steps To Reproduce**
Run arbitrage in paper mode without market orders

...

**Screenshots**
<img width="518" alt="Screenshot 2021-01-29 at 19 16 57" src="https://user-images.githubusercontent.com/39387497/106318195-70e2d700-6267-11eb-81a1-7bab65da0ddb.png">

**Release version**
0.36

**Comment by dennisocana** [comment]
Fixed in version 0.37 - thanks!
