### ISSUE TITLE
crypto.com: cancel_all does not stop tracking inflight orders

### ISSUE THREAD

**Issue by leocape** [CoinAlpha/hummingbot#2897]
**Describe the bug**
Running cancel_all does not stop tracking inflght orders, which means that when the bot starts again after it was stopped it still has the list of cancelled orders in market state, and then attempts to cancel those orders.

**Steps To Reproduce**

1. Run the crypto.com connector with any PMM config
2. Submit the stop command
3. Orders are cancelled (but they remain in the market state)
4. Start the bot again
5. Unnecessary cancel requests are sent at start up

**Release version**
0.35

**Comment by rxlxrxsx** [comment]
HI @leocape, is it possible if you can send your log file when this happened and a screenshot when the unnecessary cancel requests are sent at start up?
