### ISSUE TITLE
[BUG] "Get_balance" doesn't work under "Discovery" strategy

### ISSUE THREAD

**Issue by moraliang** [CoinAlpha/hummingbot#291]
**Describe the bug**
// A clear and concise description of what the bug is.

Get_balance doesn't work under "Discovery" strategy

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:
1. choose "discovery"
2. config your strategy as usual
3. start
4. enter "get_balance"

**Screenshots**
// If applicable, add screenshots to help explain your problem.
![Screen Shot 2019-05-24 at 10 29 16 AM](https://user-images.githubusercontent.com/14824365/58346091-d7ff8580-7e0e-11e9-8c5e-0c0dd9df3f86.png)

**Release version**
// Include your bot's version number (Can be found at the bottom left corner of your CLI).
0.7.0 dev

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by michaelc9** [comment]
Balances are not configured for Discovery strategy since trading is not required.
