### ISSUE TITLE
Failed Test PR#286 - Failing to submit subsequent order when arbitraging between VVS and Crypto.com

### ISSUE THREAD

**Issue by Deepali6997** [CoinAlpha/hummingbot#291]
## Summary and Screenshots
When running arbitrage strategy between VVS and crypto.com, it is seen that it keeps on executing only one side of trades. In my case DEX side.

<img width="1724" alt="Screenshot 2022-10-25 at 7 21 19 PM" src="https://user-images.githubusercontent.com/100112937/197791849-caca2d1a-3886-4ca3-ad68-077ed0c134fa.png">

## Steps To Reproduce
1. Install Hummingbot from source
2. Set up and run a Gateway server by following the instructions in https://docs.hummingbot.org/developers/gateway/setup/
3. Connect to VVS Finance mainnet and Crypto.com exchange
4. Create and run amm_arb strategy  (negative profitability to force trade) 

note : 
please install a clean instance
delete files in db folder
no stuck order in your wallet should be there
refrain using other wallets that are subsequently used by them at the time of testing

## Test Result Comparison
New connector on oss

## Attachments
all the relevant files are here
[newissue.zip](https://github.com/CoinAlpha/hummingbot/files/9860898/newissue.zip)

**Comment by RC-13** [comment]
This is a duplicate issue
