### ISSUE TITLE
Add binance.us for miner option in addition to binance.com

### ISSUE THREAD

**Issue by rogueops** [CoinAlpha/hummingbot#2916]
**Feature Suggestion**
People in the US can no longer use binance.com so we are unable to mine

if it has to be binance.com please let me know and I can close the ticket

**Impact**
anyone within the US that wants to mine on binance

**Additional context**
created a binance.us account, but miner section of web site when logged in states "API error"

**Comment by phbrgnomo** [comment]
@Nullably could you check if this would be possible with the liquidity mining strategy?

**Comment by phbrgnomo** [comment]
binance us already included as a connector.
