### ISSUE TITLE
Need Help With Kucoin Liquidity Mining

### ISSUE THREAD

**Issue by rogueops** [CoinAlpha/hummingbot#2918]
I setup a kucoin account, made an API and when I start the bot I get:

"markets not ready, no market making trade permitted"

I chose ONE -> USDT

and

ONE -> BTC

not sure what I am missing or doing wrong

**Comment by RC-13** [comment]
@rogueops I assume you're using pure market making strategy to participate on the KuCoin liquidity mining. Some check that you can try is to run `connect` to verify that KuCoin API key is connected and confirmed, `status` to check if there are error on the output pane. And also make sure that your `order_amount` meets the minimum order requirement of KuCoin. If no error and order size are okay, kindly send us a screenshot of your hummingbot window after `status` command is run and include your log file. For faster support, you can chat with us on our [discord channel](https://discord.hummingbot.io/)

**Comment by rogueops** [comment]
status shows connected for all 3 tests, i will login and do the rest
sometime today, when I run start it shows connected when talking to the API
then just sits and then after a while I get the error posted, I use the
exact same creds as the connection on the miner hummingbot page and it
shows connected so the creds are good i am guessing.

**Comment by rogueops** [comment]
this is as far as I get, see left window for info requested, ill post logs
shortly, let me know if the below pic gets removed, its a screen shot of
the bot running
[image: image.png]

**Comment by rogueops** [comment]
logs attached, the below stands out, but i dont know why when i use the
same creds on miner.hummingbot.io and it shows connected and also the
status and start show connected on the bot

OSError: Error fetching data from https://api.kucoin.com/api/v1/orders.
HTTP status is 403.

**Comment by rogueops** [comment]
I deleted and recreated the API and now I dont get the access error, just
the unexpected errors listed in the log above

**Comment by rogueops** [comment]
I have recreated and re-added the API creds a few times and

connect after adding keys shows "you are now connected to kucoin"
connect shows kucoin keys added:yes keys confirmed: yes status:green
status shows confirmed for all 3 checks
when issuing start and then status it shows "market connectors are not
ready"

**Comment by rogueops** [comment]
oh and the api permissions are general and trade

**Comment by RC-13** [comment]
@rogueops Can you upload your log file and the screenshot again, it seems they fail to be uploaded.

**Comment by rogueops** [comment]
I will do it when I get home so I can do it directly on github instead
of email like I am doing now

**Comment by rogueops** [comment]
give this a try

https://ibb.co/wdtJc40

i will get you a current log

**Comment by RC-13** [comment]
@rogueops Based on the screenshot, I think the issue now is related to your strategy configuration. At the current state (image sent), if you run `status` that should give you the current best bid and ask price of the current market but may say that `no active maker order`, try checking if you're order amount meets the exchange minimum requirement.

**Comment by rogueops** [comment]
Ok, I plan to work on it tonight, I will post what it lists and what I
entered

**Comment by rogueops** [comment]
See attached

![orderAMOUNT](https://user-images.githubusercontent.com/1724215/107136552-999b4a00-68c1-11eb-92c6-99cf320dbfdd.PNG)
![bidSPREAD](https://user-images.githubusercontent.com/1724215/107136553-999b4a00-68c1-11eb-8b6b-9745ac846e2a.PNG)
![askSPREAD](https://user-images.githubusercontent.com/1724215/107136554-9a33e080-68c1-11eb-816f-fc5b5b40c9ca.PNG)
![20210206](https://user-images.githubusercontent.com/1724215/107136555-9a33e080-68c1-11eb-8798-a3b04ed863d1.PNG)

**Comment by rogueops** [comment]
while at work I am signed into my work github and this is my personal so I was using email to reply and I bet that is why the log and pics did not make it through, i posted the above directly

**Comment by rogueops** [comment]
I think its kucoin, act like I have the bot installed, but have no
kucoin account yet, what do I need?

**Comment by RC-13** [comment]
Hi @rogueops just want to follow up, are you still getting the same issue? If you do, kindly get in touch with us through our discord server for real-time support. Thanks

**Comment by rogueops** [comment]
Waiting for a response on what is needed for kucoin, i think its kucoin so
I want to make sure I setup the account right, it just never adds orders to
the book, it stops at initializing order book

**Comment by RC-13** [comment]
When participating in KuCoin liquidity mining, you need to generate 2 API keys, one for your bot with **general and trade** enabled while the other API key with **read-only or general** enabled only will be added on Hummingbot miners app page.

**Comment by rogueops** [comment]
ok so I got some of that right, created an account, did not KYC
verify, i have no balance as I have it all in coinbase( can transfer
if needed), created 1 API with general and trade and using it on the
dashboard and the bot, I will create another key for the dashboard,
all I need now is to know if I need to verify(miner page says no KYC
needed, but maybe that's meant for the hummingbot dashboard? ) and if
I need to add some ETH as I am doing kucoin ETH -> USDT

thanks for the reply, its driving me nuts on why it wont work like my
other bots that have no issues, only happened when i joined kucoin

**Comment by RC-13** [comment]
I believe you don't need to do KYC verification, however, if you're trading for multiple pairs, you must have sufficient balance to cover all your bots. If you don't have assets at the moment then you will need to transfer some to your KuCoin account.

**Comment by rogueops** [comment]
I am fairly sure that is where I missed a step, I have 0 in kucoin, ill
transfer over and report back, I did redo the API setup where I have a
general API for the dashboard and a general/trade API for the bot

**Comment by rogueops** [comment]
balance did it, all good, do have a command question so will open a new ticket, should be easy for you
