### ISSUE TITLE
[BUG]Bot doesn't place order on binance under pure MM 

### ISSUE THREAD

**Issue by moraliang** [CoinAlpha/hummingbot#292]
**Describe the bug**
// A clear and concise description of what the bug is.
Bot doesn't place order on binance under pure MM while bot **shows** there are active orders. 

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

1. choose pure MM strategy
2. config as usual (the order amount > binance min order size)
3. start

**Screenshots**
// If applicable, add screenshots to help explain your problem.

**Release version**
// Include your bot's version number (Can be found at the bottom left corner of your CLI).
0.7.0 - dev

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 
Logs attached
[hummingbot_logs_2019-05-23-17-06-41.log](https://github.com/CoinAlpha/hummingbot/files/3217975/hummingbot_logs_2019-05-23-17-06-41.log)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by moraliang** [comment]
Config:
```
########################################################
###       Pure market making strategy config         ###
########################################################

# The following configuations are only required for the
# pure market making strategy

# Exchange and token parameters
maker_market: binance
maker_market_symbol: IOSTETH

# size of each order
order_amount: 250.0

# Time in seconds before cancelling and rerunning strategy
# If tick size is 60, the bot cancels active orders and reruns after a minute
cancel_order_wait_time: 120.0

# How far away from mid price to place the bid order
# Expressed in decimals : 0.01 = 1% away from mid price at that time
# Example if mid price is 100 and bid_place threshold is 0.01
# Your bid is placed at 99
bid_place_threshold: 0.005

# How far away from mid price to place the ask order
# Expressed in decimals : 0.01 = 1% away from mid price at that time
# Example if mid price is 100 and ask_place threshold is 0.01
# Your bid is placed at 101
ask_place_threshold: 0.005
```

**Comment by pointtoken** [comment]
I am repo'ing this -- MM strategy and Binance doesn't work

**Comment by veecos2** [comment]
This has been fixed in the latest release.
