### ISSUE TITLE
Configure multiple parameters on a single line / command

### ISSUE THREAD

**Issue by krisj** [CoinAlpha/hummingbot#2922]
**Feature Suggestion**

In the current implementation you can do
`config ask_spread 1
`
or for multiple commands
`config ask_spread 1
`
`config bid_spread 1.5
`
`config order_refresh_time 60
`
I would like to give Hummingbot just 1 command like
`config ask_spread 1 bid_spread 1.5 order_refresh_time 60
`
in one go

**Impact**
This would be very time saving and especially effective when used via telegram and external sources that could send a single request via telegram to update several settings at once.

**Comment by zappra** [comment]
What would be really cool is the ability to define macros/shortcuts that expand to one or more commands with arguments, eg:

`macro:`
`    format: "set1 $1 $2 $3"`
`    output: ["config ask_spread $1", "config bid_spread $2", "config order_refresh_time $3"]`

**Comment by krisj** [comment]
a macro would be sort of predefined by user?
so, you could just type `set1 1 1.5 60` to actually execute a `config ask_spread 1 bid_spread 1.5 order_refresh_time 60` in the background?

**Comment by zappra** [comment]
Yes exactly. Could be part of the global config

**Comment by krisj** [comment]
yes that would be cool indeed. mind you when using external sources - it wouldn't matter too much, as long as the parameters can be sent in 1 single message regardless of how long. but the macro or template principle applied to this could be very effective I agree.

**Comment by dennisocana** [comment]
Will be available starting from version 0.40 release.
