### ISSUE TITLE
Kraken - Not creating orders for XDGUSD pair

### ISSUE THREAD

**Issue by john-hummingbot-support** [CoinAlpha/hummingbot#2930]
**Describe the bug**
// bot is stuck on initialized order book for XDG - USD 1/1 completed. 1/1 completed. 

**Steps To Reproduce**
1. setup API keys with correct permissions and nonce above 10
2. connect hummingbot using the generated API key
3. create a new config file with bid_spread to 1%, ask spread 1% ,order refresh 60 seconds
4. start bot
...

**Screenshots**
![image](https://user-images.githubusercontent.com/78332435/107166096-eed57980-69ef-11eb-9761-30f2bbafe210.png)

**Release version**
0.35.0 docker ubuntu
0.35.0 - mac binary
0.35.0 pi4 arm64 from source

**Attachments**
 
![image](https://user-images.githubusercontent.com/78332435/107166450-06f9c880-69f1-11eb-92e5-27ab4ae39f1e.png)

**Optional: your discord username:**
@John V
@Alex the Emperor Penguin

**Comment by keithbaum** [comment]
hi @john-hummingbot-support I wasn't able to reproduce the issue. Started a strategy using that trading pair without issues
![image](https://user-images.githubusercontent.com/14949838/108284865-ca526d80-7164-11eb-858b-743c537cb7fc.png)

**Comment by rapcmia** [comment]
I tried to follow up with a user about this GitHub issue, confirmed that he had moved to Binance however this is still not working as I tried to replicate it again.

![image](https://user-images.githubusercontent.com/73840223/108291093-a460b380-71cc-11eb-8e1e-37bb31b49bdc.png)

Order amount has been updated as well
![image](https://user-images.githubusercontent.com/73840223/108291391-31a40800-71cd-11eb-86cb-69cfa50f44e4.png)

I tried also to check if the min_qoute_order_amount is added for USD
![image](https://user-images.githubusercontent.com/73840223/108291603-79c32a80-71cd-11eb-9a94-0277b4171c57.png)
