### ISSUE TITLE
Avellaneda-Stoikov Strategy

### ISSUE THREAD

**Issue by phbrgnomo** [CoinAlpha/hummingbot#2934]
**Feature Suggestion**
Implement the Avellanda-Stoikov strategy as decribed on their paper:

https://stanford.edu/class/msande448/2018/Final/Reports/gr5.pdf

Model Spreadsheet:

https://docs.google.com/spreadsheets/d/1XefvOLYXkZLeT0WBQs6FmzHo7j7iXGg2BI54b8Ta_Ho/edit?usp=sharing

**Comment by keithbaum** [comment]
Discussion pasted in notion https://www.notion.so/hummingbot/Avellaneda-Stoikov-Strategy-43c5fe1bd72d46928c9c30704f79372e

**Comment by dennisocana** [comment]
We agreed during the call today to move this story to v0.38 release to allow more time in building and testing the feature.
