### ISSUE TITLE
Rate Oracle module

### ISSUE THREAD

**Issue by Nullably** [CoinAlpha/hummingbot#2939]
**Feature Suggestion**
An oracle which provides exchange rate between tokens. This is a service network module which can be started as needed to provide ongoing conversion rates or can be used as a one time off (async call).

Please note the terminology here where rate is used instead of price. Price implies there is a market for the trading pair while rate could be derived through conversion from multiple markets. For example, there may not be a market for AAVE-UNI (as such no price), we can infer the exchange of AAVE to UNI if there are AAVE-USDT and UNI-USDT markets (or any other common denominator).

There have been feature requests on conversion rates in one form or another.
https://github.com/CoinAlpha/hummingbot/issues/2797
https://github.com/CoinAlpha/hummingbot/issues/2841

The exchange rates should come from the most reliable and free to use source, currently in my opinion is Binance. 

Strategies, like Arbitrage, amm arb and XEMM, can benefit from this. Though we need to ensure a few things
* The token symbols are as intended
* The strategy needs to stop if the exchange rate service is unavailable

Binance provides a very useful and light API endpoint for this. And we can upgrade our existing `market_price` module (hummingbot/core/utils/market_price.py) for this.

**Consideration**
* Do we still consider Coin Gecko for price sourcing?
* To handle a situation when the price source is unavailable
* To handle a situation when token symbols or names are conflicted

**Additional context**
We used to have ExchangeRateConversion module in Hummingbot to get a rate of one token in another. Back in around April last year, we decided to decommission it due to a few problems with the module. Firstly, it relies on CoinGecko which wasn't very reliable back then, secondly there were many conflicts with token codes and names and also price feed was lagging in accuracy.

Though by removing the module, we also lost the ability to dynamically convert token values, hence Arbitrage and XEMM strategies now only allow for fixed rate conversion.

**Comment by Nullably** [comment]
@mifeng suggested allowing for multiple oracle sources for pricing where Binance is the default.

**Comment by Nullably** [comment]
Global configuration suggestion:
* rate_oracle_source: initially Binance, Coingecko and Kucoin

Arbitrage and XEMM configuration update (to replace the fixed conversion rate)
* use_oracle_on_unmatched_symbols: E.g. if AAVE-USDT and AAVE-USDC markets are configured for arbitrage strategy, in this case USDT and USDC are unmatched, if the flag is set the strategy will use the oracle to converse rate between USDT and USDC, otherwise assume 1:1 conversion
Note: when this flag is set. before the strategy starts, it should display the oracle source and the rate and ask user for a confirmation.

**Comment by mifeng** [comment]
+1 I think this is a good approach

**Comment by Nullably** [comment]
I'd like to suggest some additional features on this rate oracle:
1. `rate` command, with --pair or --token argument
    This is to check the rate and probably mainly for QA to test
2. New global config variable as below:
    * `rate_oracle_source` choices are `binance`, `coingecko`, `kucoin`
    * `global_token` - currently this is USD in many places (e.g. `balances`, `pnl`), users can now set something like `EUR`, `BRL`, etc.
    * `global_token_symbol` - e.g. $, € where symbol is needed for the global token

**Comment by Nullably** [comment]
@phbrgnomo 
See #3063 for a working prototype of how this works.

**Comment by Nullably** [comment]
For each oracle source there will be some differences and limitation. 
**Binance**
- USD is not available (it is on binance.us) but USDT is and probably is close enough for displaying purposes.
- Rates refresh time is 1 second

**CoinGecko**
- Rates refresh time is 30 seconds (this is their API rate limit)
- The lag is 30 seconds on top of coingecko's lag

**Comment by Nullably** [comment]
@phbrgnomo Can you please review the design and the features before I continue further?

**Comment by phbrgnomo** [comment]
@Nullably i started to take a look at the PR, but I got some questions:

> rate_oracle_source: initially Binance, Coingecko and Kucoin

Can't we add as options the current connectors?

I know here we would be looking for reliable information sources, but let's say that, for some reason the user don't want to use these sources (maybe the volume of the pair on a local currency is higher on a local exchange than binance for example).

Would that be doable?

Other question is, what if i wanted to look at these rates between stable coins for example? 

On AAVE example, would it work if i wanted to check the disparity between AAVE-USDT and AAVE-DAI?

**Comment by phbrgnomo** [comment]
Complementing the comment above:

I think we could use the "fixed" price oracles (binance, coingecko) as the first iteration of this story, so we can push it for testing, but we would create a new story for allowing custom oracles sources (be it an existing connector or any other source the user would like).

**Comment by Nullably** [comment]
@phbrgnomo 
> Can't we add as options the current connectors?

Not all exchanges/protocols provide API needed for this, some require authentication, some don't provide all the rate in a single API call. And for every exchange we want to provide rate oracle, there is some coding required but not a big task. 

> On AAVE example, would it work if i wanted to check the disparity between AAVE-USDT and AAVE-DAI?

Yes, as long as you can find the rate (using `rate` command), it will work
![image](https://user-images.githubusercontent.com/37262506/111110033-c7e20880-8596-11eb-95fb-45fbc3dc8130.png)

> I think we could use the "fixed" price oracles (binance, coingecko) as the first iteration of this story, so we can push it for testing, but we would create a new story for allowing custom oracles sources (be it an existing connector or any other source the user would like).

Using the word fixed is confusing here, the rate is not fixed. Also we can have more oracle sources for sure, but not many sources would be qualified for providing high quality and availability information. 

It would be better to get to see how this works in a strategy, e.g. we can update `arbitrage` and `XEMM` to use it for the rate conversion.

**Comment by dennisocana** [comment]
Closing story since the linked PR is already merged. The actual implementation of how it works with strategies will be on a separate story as mentioned by Jack in the PR description.
