### ISSUE TITLE
[BUG] [dev/0.7.0] Failed to fetch account updates on DDEX. Check network connection

### ISSUE THREAD

**Issue by sazed5055** [CoinAlpha/hummingbot#294]
**Describe the bug**
Failed to fetch account updates on DDEX. Check network connection

**Steps To Reproduce**
1. Configure Hummingbot (DDEX: Maker, CBPro:Taker)
2. Input status command and perform a preliminary check
3. Input start command

**Actual Result**
Failed to fetch account updates on DDEX. Check network connection

**Screenshots**
![2](https://user-images.githubusercontent.com/50499987/58353845-f634a800-7e45-11e9-94c9-fbda4e24c482.jpg)

**version**
dev/0.7.0

**Comment by mifeng** [comment]
@sazed5055 This doesn't seem like a bug. The bot is telling you to check your network connection. 

If your network connection is stable and the warning persists, that may be a bug. If so, please provide the logs and configs.
