### ISSUE TITLE
LM strategy - Paused outstanding orders are not displayed in status when resumed

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#2941]
**Steps to reproduce the issue:**

1. Run a `liquidity_mining` strategy and wait for open orders to be created
2. Pause the strategy by running `exit --suspend`
3. Restart Hummingbot, import the previously used strategy config file
4. Resume by running `start --restore`
5. Run `status` command

You'll see that the orders showing in the dataframe are only the new ones created after resuming. Although the previous orders prior to pausing are being tracked correctly (they get cancelled when you do a `stop` or `exit` command). Users won't know whether this is an expected behavior or not.

If this is an expected behavior because pause & resume is not yet compatible with other strategies, we can either do one of these two things:

1. Explicitly indicate in the documentation that pause and resume feature only works with pure market making strategy
https://docs.hummingbot.io/features/pause-resume/
2. Add a logic in Hummingbot that prevents users from running `exit --suspend` command when running a strategy other than pure market making

![Screen Shot 2021-02-10 at 9.34.25 AM.png](https://images.zenhubusercontent.com/5f597e9f5e2dba41ca21ad9d/1eb78f34-4bcb-41df-a0aa-3cc0f7c17d7e)

[conf_liquidity_mining_1.txt](https://github.com/CoinAlpha/hummingbot/files/5955559/conf_liquidity_mining_1.txt)
[logs_conf_liquidity_mining_1.log](https://github.com/CoinAlpha/hummingbot/files/5955560/logs_conf_liquidity_mining_1.log)

Version: 0.36.0
Installation type: Docker
Operating system: Ubuntu 18.04 LTS
Machine: AWS t2.large instance

**Comment by jason-hb** [comment]
Jack, please give LOE once reviewed

**Comment by Nullably** [comment]
This is a small 1 day (or less) work. 
Though, for PMM, once strategy resumes (`start --restore`), all restored orders become hanging orders.
There is no hanging orders in LM, and shouldn't be. So what does resume mean for LM?

**Comment by dennisocana** [comment]
Fixed in version 0.37
