### ISSUE TITLE
Huobi - Error class 'decimal.DivisionByZero' on balance command

### ISSUE THREAD

**Issue by rxlxrxsx** [CoinAlpha/hummingbot#2946]
**Describe the bug**
Getting an `Unhandled error on background task` after running `balance` command when connected to Huobi. This has no impact on bot's behavior and balances are showed correctly.
```
2021-02-11 06:12:03,467 - 3730 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: [<class 'decimal.DivisionByZero'>]
Traceback (most recent call last):
  File "/home/ubuntu/04-huobi/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/ubuntu/04-huobi/hummingbot/client/command/balance_command.py", line 96, in show_balances
    self._notify(f"\n  Total: $ {df['Total ($)'].sum():.0f}    "
decimal.DivisionByZero: [<class 'decimal.DivisionByZero'>]
```

**Steps To Reproduce**
1. Connect bot to Huobi
2. Run `balance` command

**Screenshots**
<img width="1422" alt="Screen Shot 2021-02-11 at 2 18 27 PM" src="https://user-images.githubusercontent.com/64377055/107608782-e3947f00-6c77-11eb-997e-1a302f4d1749.png">

**Release version**
dev-0.37.0

**Attachments**
[logs_hummingbot.log](https://github.com/CoinAlpha/hummingbot/files/5963460/logs_hummingbot.log)

**Comment by rxlxrxsx** [comment]
Closing as issue is no longer occurring, will re-open if needed.
<img width="1425" alt="Screen Shot 2021-02-15 at 12 48 28 PM" src="https://user-images.githubusercontent.com/64377055/107906625-80169400-6f8c-11eb-85ba-57bb5d018ab1.png">

**Comment by rxlxrxsx** [comment]
Upon further checking I was able to determine what causes the error to show, it only shows when your available USDT balance is below 1

<img width="1422" alt="Screen Shot 2021-03-04 at 8 39 31 AM" src="https://user-images.githubusercontent.com/64377055/109895618-7c904600-7cca-11eb-9263-a07b2cecdfe2.png">

<img width="1410" alt="Screen Shot 2021-03-04 at 8 49 37 AM" src="https://user-images.githubusercontent.com/64377055/109895631-81ed9080-7cca-11eb-9133-4b4b0a1f0b8e.png">

<img width="1411" alt="Screen Shot 2021-03-04 at 8 42 00 AM" src="https://user-images.githubusercontent.com/64377055/109895726-aba6b780-7cca-11eb-8e52-87466df6105d.png">

**Comment by RC-13** [comment]
I no longer see this error on Huobi, here's a screenshot running the balance command with a balance below $1, do ignore the other error in the log pane. Closing this ticket now.
![image](https://user-images.githubusercontent.com/57189990/120962433-4ca58280-c792-11eb-85ce-625570e5b5ca.png)
