### ISSUE TITLE
Question about history command, exiting and restarting a container/the bot

### ISSUE THREAD

**Issue by rogueops** [CoinAlpha/hummingbot#2948]
I am very happy with my bots and like to see the continued progress, I need to exit the container every week to reset the memory usage on the server or need to reboot the server, I saw at some point a history command that looked like if I run it I could restore the progress shown if the container were to crash, get exited, or if the server needs to reboot. Is this possible? If so, what command should I run after i shutdown the containers gracefully and start them again?

**Comment by RC-13** [comment]
You can use the command `history --days` (https://docs.hummingbot.io/operation/command-ref/#history) to preview your performance from previous days prior to the time when you exit or restart your bot/containers. For example, if you do `history --days 1`, it should show you your performance from the past day.  Take note, after you restarted your container/bot, you need to import your strategy first before running the command.

**Comment by dennisocana** [comment]
Closing since this has been answered and no response for 3 days. If further support is needed related to this question, feel free to re-open or send us a message in https://discord.hummingbot.io
