### ISSUE TITLE
Failed Test PR #294 - Getting configuration file not found during generate-certs command

### ISSUE THREAD

**Issue by PtrckM** [CoinAlpha/hummingbot#295]
**Describe the bug**
- Client showing `SSL configuration file not found. Please use gateway/setup/generate_conf.sh to generate it.` after issuing the command `gateway generate-certs`. Despite the message it still generate a valid certificates on the specified location.

![image](https://user-images.githubusercontent.com/54516858/211995951-fe9ddfef-350e-4691-a6bd-9309b47b5500.png)

**Steps To Reproduce**
1. Clean clone of branch the install and compile it.
2. Start the client
3. generate certificate using `gateway generate-certs`
4. Message will start to appear
5. Despite these enter password and the bot still generate a working certificates.

**Test Result Comparison**
- CoinAlpha OSS and Hummingbot foundation does not use these files.
![image](https://user-images.githubusercontent.com/54516858/211996997-9bb4f322-22bd-46a3-96c5-4e6f700b8fa2.png)

![image](https://user-images.githubusercontent.com/54516858/211997406-fbde9b7c-6bba-4892-9720-144c92dcd302.png)

**Attachments**
- N/A

**Comment by petioptrv** [comment]
Confirming that this is an issue that already exists in `hummingbot` and is not part of this PR

**Comment by PtrckM** [comment]
confirmed foundation already has it.. closing ticket
