### ISSUE TITLE
Loopring connector not submitting orders Ver 0.36.0

### ISSUE THREAD

**Issue by dietzam** [CoinAlpha/hummingbot#2950]
**Describe the bug**

This is with the recently updated v36 Loopring connector. 

1. the bot connects properly to Loopring as per logfile.
2. the bot initiates the orderbook properly as per logfile.
3. the bot calculates the buy and sell orders properly as per logfile.

4. the bot **fails** to submit the orders with Error as per logfile

**Steps To Reproduce**
// The bot runs on AWS EC2 via docker. Config attached.

**Screenshots**
// 
![Screenshot 2021-02-13 095941](https://user-images.githubusercontent.com/8992858/107832449-91bd3780-6de4-11eb-9d32-670e3528a9aa.png)

**Release version**
// Ver 0.36.0

**Attachments**
// 
[logs_conf_pure_mm_1.log](https://github.com/CoinAlpha/hummingbot/files/5974689/logs_conf_pure_mm_1.log)

[conf_pure_mm_1.txt](https://github.com/CoinAlpha/hummingbot/files/5974698/conf_pure_mm_1.txt)

**Comment by PtrckM** [comment]
I'm not able to replicate this running the bot for more than 10 minutes, can you confirm that you already unlocked your loopring wallet before trading? Or try running the bot much longer see if the bot recovers on your end?

![image](https://user-images.githubusercontent.com/54516858/107841714-414fd500-6df8-11eb-8b89-d3b66daf7f93.png)
![image](https://user-images.githubusercontent.com/54516858/107841718-4b71d380-6df8-11eb-935c-99eef3dc6d0c.png)

**Comment by dietzam** [comment]
I am trading on loopring manually, so there is nothing wrong with my wallet as far as I can see. That I am connected properly you can also see that I can see the orderbook
![Screenshot 2021-02-13 160045](https://user-images.githubusercontent.com/8992858/107842130-3eafa880-6e15-11eb-9078-4ab8b115a5c4.png)
 
There is no change in the error message running the bot longer, no.

**Comment by PtrckM** [comment]
are there any other bots running on loopring using the same wallet?

**Comment by dietzam** [comment]
No

**Comment by dietzam** [comment]
looks to me that is were the error msg comes from:

 except Exception as e:
            self.logger().warning(f"Error submitting {order_side.name} {order_type.name} order to Loopring for "
                                  f"{amount} {trading_pair} at {price}.")
            self.logger().info(e)


thats in 'hummingbot/connector/exchange/loopring/loopring_exchange.pyx'

**Comment by dietzam** [comment]
Ok I found the problem actually.  The private keys for the loopring wallet (on phone) and the web account are different, even so it has the same account #. Since I was running the bot from the web I was using the wrong private key. After changing to the correct private key, the bot runs ok.

**Comment by dietzam** [comment]
see above
