### ISSUE TITLE
Kraken - Incorrect value for hardcoded minimum order size

### ISSUE THREAD

**Issue by rxlxrxsx** [CoinAlpha/hummingbot#2953]
**Describe the bug**
Some pairs on Kraken fails to recognize the minimum order size which results to the bot not placing orders.

Example:

For BTC-USDC, the [minimum order size](https://support.kraken.com/hc/en-us/articles/205893708-Minimum-order-size-volume-for-trading) based on the exchange is .0002 however the bot will only place an order if you set the order_amount to .002, anything below this value will not be accepted by the bot and will not place orders.

<img width="626" alt="Screen Shot 2021-02-14 at 6 53 08 PM" src="https://user-images.githubusercontent.com/64377055/107874823-4fd0e600-6ef7-11eb-8ae4-adac9130f7fe.png">

With order_amount configured from .0002 to .001
<img width="468" alt="Screen Shot 2021-02-14 at 6 55 54 PM" src="https://user-images.githubusercontent.com/64377055/107874835-624b1f80-6ef7-11eb-99c5-5a4c4ee1242f.png">

With order_amount configured to .002 (.002 BTC currently ranges from 90-100 USD)
<img width="513" alt="Screen Shot 2021-02-14 at 6 56 53 PM" src="https://user-images.githubusercontent.com/64377055/107874863-8c044680-6ef7-11eb-8da6-075a52580568.png">

Successfully placed an order manually on the exchange with .0002 order size.
<img width="362" alt="Screen Shot 2021-02-14 at 5 37 43 PM" src="https://user-images.githubusercontent.com/64377055/107874959-249ac680-6ef8-11eb-918d-d95f9bb9bfdc.png">

Tried as well using ETH-USD pair
<img width="629" alt="Screen Shot 2021-02-14 at 7 10 13 PM" src="https://user-images.githubusercontent.com/64377055/107875004-5744bf00-6ef8-11eb-963d-29c10735bb5a.png">

With order_amount configured from .005 to .01
<img width="491" alt="Screen Shot 2021-02-14 at 7 12 57 PM" src="https://user-images.githubusercontent.com/64377055/107875066-c15d6400-6ef8-11eb-850c-68104595268b.png">

With order_amount configured to .02 (.02 ETH currently ranges from 34-38 USD)
<img width="524" alt="Screen Shot 2021-02-14 at 7 13 53 PM" src="https://user-images.githubusercontent.com/64377055/107875082-d639f780-6ef8-11eb-92e3-592f5dd0a8ef.png">

Successfully placed an order manually on the exchange with .005 order size.
<img width="362" alt="Screen Shot 2021-02-14 at 7 18 49 PM" src="https://user-images.githubusercontent.com/64377055/107875229-9a536200-6ef9-11eb-8bb2-042358b66054.png">

Tried as well using ANT-USD pair, the bot accepts the minimum order size and places orders successfully.
<img width="628" alt="Screen Shot 2021-02-14 at 7 22 15 PM" src="https://user-images.githubusercontent.com/64377055/107875303-2796b680-6efa-11eb-9bfc-d19403f424e2.png">
<img width="565" alt="Screen Shot 2021-02-14 at 6 55 03 PM" src="https://user-images.githubusercontent.com/64377055/107875331-3b421d00-6efa-11eb-996f-21e21fc1925a.png">

**Steps To Reproduce**
1. Run a pure market making bot on Kraken
2. Set the order_amount to the minimum order size accepted by Kraken
3. Run the bot, notice that it won't place orders until you set the order_amount on a certain value that the bot will accept

**Release version**
dev-0.37.0

**Comment by TheHolyRoger** [comment]
https://github.com/CoinAlpha/hummingbot/blob/master/hummingbot/connector/exchange/kraken/kraken_constants.py#L35
Not sure why these are hardcoded 🤔
