### ISSUE TITLE
Terra - Total ($) in balance displays 0 on most Terra tokens

### ISSUE THREAD

**Issue by PtrckM** [CoinAlpha/hummingbot#2957]
**Describe the bug**
- bot unable to show USD value of other terra tokens

**Steps To Reproduce**
- connect terra
- balance

**Screenshots**
![image](https://user-images.githubusercontent.com/54516858/108019176-9a1ba980-7054-11eb-9737-f3ff72de9685.png)

**Release version**
0.36.0

**Comment by RC-13** [comment]
Rate oracle should address this conversion problem (v0.38.0), MNT is currently not supported by Binance and Coingecko.
![image](https://user-images.githubusercontent.com/57189990/113547376-5985e880-9620-11eb-965a-635b67f592eb.png)
