### ISSUE TITLE
KuCoin - Total balance randomly pulling from "Trading" or "Main" account

### ISSUE THREAD

**Issue by ChadMC** [CoinAlpha/hummingbot#2971]
Let's say you are running the bot against LUNA-USDT. If you type the "status" command over and over, you will sometimes see the Total USDT balance from your "Trading" account, but other times it will show you the value from the "Main" account.

This causes many issues with inventory skew, because it can sometimes show that you own 20% of the base currency, but then randomly see it as only 2% (depending how much USDT you have on either account). It can also mess up your strategy if you are using a script that relies on the bot knowing the total balance of Quote currency, as it it sporadically changes. For example, I'm trying to use the included sample script: inv_skew_using_spread_script.py
This value randomly changes:
self.quote_balance = self.all_total_balances[f"{self.pmm_market_info.exchange}"].get(self.quote_asset, self.quote_balance)

Since this is a trading bot, I don't think it should ever look at the Main account and should be limited to only the Trading account. Or at the very least, it should be consistent and SUM from both accounts.

**Comment by rxlxrxsx** [comment]
Hi @ChadMC, any chance you can provide a screenshot when your bot is using the Main account balance and Trading account balance? Also the version of Hummingbot you encountered this issue. I can't seem to replicate it on my end. I tried checking `status` consecutively and `status --live` as well, I can confirm that my Total Balance is using the balance on my Trading account during the period of testing.

**Comment by ChadMC** [comment]
Hi @rxlxrxsx, see attached. These 2 commands were run back-to-back. No trades in between. I redacted by full balance amount for privacy. It is version 0.36.0. At the time of this command, I did not own any of my Base asset. I do have USDT (quote currency) in both my Main and Trading account. I think that may be a requirement for this to happen.

**Comment by ChadMC** [comment]
I also just noticed my bot not working right, and possibly related to this issue. I'm using "inventory_cost". Yesterday it was working fine and placing my sell orders always above "inventory_cost". But today with this issue showing up more often, it will often place my sell orders below my cost. I think that is probably happening when it is looking at my balances from the "Main" account, so it sometimes does not think I own any ADA, so inventory cost is not properly calculated for my sell orders.

**Comment by ChadMC** [comment]
I can confirm this is the issue. To replicate:

1. Start bot
2. Transfer $1 from Trading to Main.
3. Hummingbot history command will show USDT balance from Main Account.
4. Transfer $1 from Main to Trade.
5. Hummingbot history command will show USDT balance from Trade Account.

**Comment by dennisocana** [comment]
Fixed in version 0.41 release
