### ISSUE TITLE
History command - Typo error for "current time"

### ISSUE THREAD

**Issue by JonasHogman** [CoinAlpha/hummingbot#2974]
**Describe the bug**
There is a typo in the text that appears when you run the history command. "Curent time" should be "Current time"

**Steps To Reproduce**
Run the history command in the bot

**Screenshots**
https://i.gyazo.com/64cb74e3300d55158ecf15dd1a84e31b.png

**Release version**
0.36

**Comment by rxlxrxsx** [comment]
Fixed in current version (0.37.1)

<img width="278" alt="Screen Shot 2021-04-06 at 9 11 53 AM" src="https://user-images.githubusercontent.com/64377055/113644839-3e66b780-96b8-11eb-9670-5ec120a9df88.png">
