### ISSUE TITLE
Telegram formatting tags are sent to Hummingbot UI

### ISSUE THREAD

**Issue by zappra** [CoinAlpha/hummingbot#2978]
**Describe the bug**
Telegram supports simple formatting tags allowing the use of bold and fixed width, eg. in script code
However if these tags are used, they are sent to the Hummingbot UI
Filtering these would allow their use in the Telegram integration 

**Steps To Reproduce**
Modify any existing script to use "b" or "pre" tags in self.notify calls

**Screenshots**

![IMG_8951](https://user-images.githubusercontent.com/35706360/108744129-7b745180-7531-11eb-8943-e1afb1985eae.PNG)
<img width="210" alt="Screenshot 2021-02-22 at 17 06 36" src="https://user-images.githubusercontent.com/35706360/108744146-829b5f80-7531-11eb-940a-1d24e5a6e812.png">

**Comment by dennisocana** [comment]
Fixed in version 0.37 - thank you for your contribution!
