### ISSUE TITLE
Revisions to `perpetual_market_making` strategy

### ISSUE THREAD

**Issue by mifeng** [CoinAlpha/hummingbot#2980]
After demo-ing this strat during Hummingbot Live on Friday, I have a few proposed changes to make it simpler and easier to run:

## 1. Always use Hedged mode
 I think serious users would always use hedged mode so that they can handle long and short positions separately. Remove the `position_mode` parameter and assume that the user will always create orders in hedged mode

## 2. Remove extraneous params from PMM
Since perps add more complexity, we should remove params wherever possible. I would remove `take_if_crossed`, `add_transaction_costs`, and hanging orders from this strategy.

## 3. Always create profit-taking and stop loss orders at position inception
Currently, I believe if the position is at a loss, we don't place the profit-taking order. This is confusing since there's little visual indication from the client or exchange UI what's happening. It will be simpler for users to understand what's happening if we always set these orders.

## 4. Remove `trailing_stop` option and consolidate long and short profit-taking spreads to a single spread
For profit-taking, I think it will be simpler for users to use only one method and just set a single spread.

I also have some questions specific to the logic of `perpetual_market_making.pyx` that I'll discuss with you during our 1:1 tomorrow.

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ram0nm) by [Unito](https://www.unito.io)

**Comment by krisj** [comment]
> ## 1. Always use Hedged mode
> I think serious users would always use hedged mode so that they can handle long and short positions separately. Remove the `position_mode` parameter and assume that the user will always create orders in hedged mode

I've only used hedge mode from day 1, the whole point of contracts in my view. One-Way is too opinionated and simplified.

> ## 3. Always create profit-taking and stop loss orders at position inception
> Currently, I believe if the position is at a loss, we don't place the profit-taking order. This is confusing since there's little visual indication from the client or exchange UI what's happening. It will be simpler for users to understand what's happening if we always set these orders.

I would suggest having it configurable wether to place profit-taking order as the buy orders are filled (as it was at 0.35) or only as the positive pnl is detected (as it is now at 0.36). There are good scenarios for both variations.

> ## 4. Remove `trailing_stop` option and consolidate long and short profit-taking spreads to a single spread
> For profit-taking, I think it will be simpler for users to use only one method and just set a single spread.

I actually depend on the long/short PT spreads being separate. As far as trailing-stop goes - I rarely use it but I do know many who do.

hope this help!

**Comment by phbrgnomo** [comment]
@krisj What is your Discord username? wanted to collect some feedback from you for the perpetual market making strategy.

**Comment by krisj** [comment]
let's continue on discord

**Comment by dennisocana** [comment]
This task is complete and shipped the simplified version of this strategy in 0.46 release.
