### ISSUE TITLE
kill_switch reconect

### ISSUE THREAD

**Issue by drumer979** [CoinAlpha/hummingbot#2985]
if kill_switch: True and bot will stop trading.  

suggestion:

if kill_switch: True and bot kill trading, than we need new variable when he starts again. So bot will still work, but it will be on hold for xxx time. 

This is only in pure_market_making.

**Comment by PtrckM** [comment]
similar feature request https://github.com/CoinAlpha/hummingbot/issues/2497

**Comment by PtrckM** [comment]
closing this ticket in favor of this first request and to avoid clutters, feel free to comment on the feature request
