### ISSUE TITLE
Binance - Missing pairs with VAI quote

### ISSUE THREAD

**Issue by sidmontanez** [CoinAlpha/hummingbot#2986]
**Describe the bug**
User reported there are no tokens with VAI quote available in Hummingbot

**Steps To Reproduce**

1. Create Pure Market Making
2. When selecting the market, no tokens with VAI quote

Here are the steps to reproduce the issue (see attachments in the section below):
This does not show pairs with AUD quote:
![image](https://user-images.githubusercontent.com/78310937/108833863-5d2d5500-7608-11eb-8c05-3e2321ba30c1.png)

These are the token user was expecting:
![image](https://user-images.githubusercontent.com/78310937/108833989-864de580-7608-11eb-9aa2-c209ea37107f.png)

**Release version**
Docker 0.36.0
Binary 0.35.0

**Comment by dennisocana** [comment]
Fixed in version 0.37
