### ISSUE TITLE
Failed Test PR #294 - Not creating sell order

### ISSUE THREAD

**Issue by PtrckM** [CoinAlpha/hummingbot#299]
**Describe the bug**
- The bot is not creating sell order even with enough balance. Also tried adjusting the order amount still does not create sell order.

https://user-images.githubusercontent.com/54516858/212449602-4e103165-b527-4ef4-8019-4abbfc9e2e2c.mp4

- manually place order on exchange
![image](https://user-images.githubusercontent.com/54516858/212449651-86df5dca-4ddf-49fc-8460-d83fd4667056.png)

**Steps To Reproduce**
1. Clean clone of branch the install and compile it.
2. Start the client and gateway
3. create a pure_mm strategy using injective
4. start strategy then observe order creation
5. check orders on exchange.

**Test Result Comparison**
- This does not happen on the previous commit.

**Attachments**
[injec.zip](https://github.com/CoinAlpha/hummingbot/files/10416502/injec.zip)

**Comment by petioptrv** [comment]
This issue may be due to the Injective node being down. Please hold off work on it for now.
