### ISSUE TITLE
Cannot edit conf/conf_global.yml

### ISSUE THREAD

**Issue by philipperemy** [CoinAlpha/hummingbot#30]
Every time I try to edit the configuration filename and restart hummingbot, it returns me that:

![image](https://user-images.githubusercontent.com/4516927/55692724-a315ab80-59e5-11e9-8873-a00349d36e78.png)

**Comment by martinkou** [comment]
You're supposed to issue a `config` command before `start`, s.t. you can choose the strategy config to use for the bot, for every time you restarted hummingbot.

The `config` command will detect valid configs in conf_global.yml and it'll not ask you again for the items that have been correctly configured. But at the very least you'll need to choose the strategy config to use, and most probably also enter a password to unlock your wallet.

**Comment by martinkou** [comment]
Closing this issue. Feel free to reopen if you have any further questions.
