### ISSUE TITLE
Failed Test PR #294 - Balance is not updating

### ISSUE THREAD

**Issue by PtrckM** [CoinAlpha/hummingbot#300]
**Describe the bug**
- Balance are not being updated on the client side.

![image](https://user-images.githubusercontent.com/54516858/212450159-3ef10e07-3ea1-4145-8196-e02284e5fa88.png)

![image](https://user-images.githubusercontent.com/54516858/212450198-1fa19d5e-bb96-4cc3-a827-2a31d402e38a.png)

![image](https://user-images.githubusercontent.com/54516858/212450592-02b76cdf-15b7-4520-a638-a5ffa113f933.png)
- does not update at all

**Steps To Reproduce**
1. Clean clone of branch the install and compile it.
2. Start the client and gateway
3. Connect injective and do `balance` command then compare balance on exchange or using endpoint
4. create a pure_mm strategy using injective
5. start strategy then do `status` / `status --live`

**Test Result Comparison**
- This does not happen on the previous commit.

**Attachments**
[injective.zip](https://github.com/CoinAlpha/hummingbot/files/10416520/injective.zip)

**Comment by petioptrv** [comment]
This issue may be due to the Injective node being down. Please hold off work on it for now.

**Comment by PtrckM** [comment]
fixed on the latest commit 23320f43fbad0f7246c6af68640e8ac9761de7b4
