### ISSUE TITLE
Status command - Issues when executing commands while using --live

### ISSUE THREAD

**Issue by rapcmia** [CoinAlpha/hummingbot#3015]
**Describe the bug**
When you stop the bot while on `status --live` and tried to use the commands like `config` or type random characters, it will not show results on the Hummingbot UI. The only way for the bot to work again is to kept pressing `ESC` and it will show the results of all commands use when it was not working

**Steps To Reproduce**
1. Create default config on any strategy (docker or source build)
2. Start the bot and use the command `status --live`
3. Use the command `stop` and try to use `config` or any random words/characters
4. You will notice that it does not show any results on Hummingbot UI
5. The only way you can use the commands or see the results on the Hummingbot UI is to press `ESC` a couple of times and try again

**Screenshots**
This is running on Pure Market Making on source, getting `Unhandled error in background task`
![PTHWVpKOfs](https://user-images.githubusercontent.com/73840223/109913441-fa634a00-7ce8-11eb-969a-54671cc7bf92.gif)

```
2021-03-04 12:37:17,637 - 1936 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 'NoneType' object has no attribute 'format_status'
Traceback (most recent call last):
  File "C:\Users\Ralph\github\2987\hummingbot\core\utils\async_utils.py", line 9, in safe_wrapper
    return await c
  File "C:\Users\Ralph\github\2987\hummingbot\client\command\status_command.py", line 131, in status_check_all
    await self.strategy_status() + script_status + "\n\n Press escape key to stop update.", 1
  File "C:\Users\Ralph\github\2987\hummingbot\client\command\status_command.py", line 76, in strategy_status
    if inspect.iscoroutinefunction(self.strategy.format_status):
AttributeError: 'NoneType' object has no attribute 'format_status'
```

**Release version**
v0.36.0

**Attachments**
For Pure market making
[logs_pmm-firo.log](https://github.com/CoinAlpha/hummingbot/files/6080914/logs_pmm-firo.log)

**Comment by rxlxrxsx** [comment]
[Fixed](https://github.com/CoinAlpha/hummingbot/pull/3468) in development
