### ISSUE TITLE
Script importer should catch exceptions due to syntax or module import errors

### ISSUE THREAD

**Issue by zappra** [CoinAlpha/hummingbot#3017]
**Feature Suggestion**

Since v0.36, exceptions caught during running script code will be logged to the UI. However, importing the script will still silently fail if there are syntax or module import errors. It would be a simple fix to catch and report exceptions when importing the script

**Impact**

Iterating on scripts can be pretty painful without proper feedback eg.

https://discord.com/channels/530578568154054663/745411770042155122/817073030822887455

**Comment by alsonkemp** [comment]
+100.  I didn't know this was a thing and have been fiddling with a script for a few hours due to this.  I can take a quick look to see if I can gen a PR in a few hours.

**Comment by zappra** [comment]
https://github.com/CoinAlpha/hummingbot/pull/3018

:)

**Comment by dennisocana** [comment]
Completed and available in version 0.40 release. Thanks to @zappra for contributing!
