### ISSUE TITLE
Research how to generalize perpetual market making strategy

### ISSUE THREAD

**Issue by mifeng** [CoinAlpha/hummingbot#3054]
# Why
We aim to generalize the `perpetual_market_making` strategy so that it works on all major exchanges that offer perpetual swaps. Currently, it's optimized for features available on Binance Futures. Before we extend it to other exchanges, we should research how other major futures exchanges handles perpetuals.

# What
Research other large derivative exchanges (see https://ftx.com/volume-monitor) to answer the following questions:

* Should we have a parameter that lets users toggle between one-way and hedged mode?
* How should users take profit and prevent losses?
* Should we have a trailing stop feature?
* How should funding rate be incorporated into the strategy?
* What should we display in `status`?

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ram8yz) by [Unito](https://www.unito.io)

**Comment by dennisocana** [comment]
This task is complete. Will close other related stories.
