### ISSUE TITLE
Failed Test PR #294 - balance for injective not showing on client

### ISSUE THREAD

**Issue by PtrckM** [CoinAlpha/hummingbot#306]
**Describe the bug**
- After connecting the injective wallet and doing the `balance` command, the client does not show the injective assets. Restarting the client and doing balance command again still does not show. 
![image](https://user-images.githubusercontent.com/54516858/215237040-c4df323c-5f4e-4323-836a-b4588028212f.png)

- checking the gateway logs, it seems its not being called by the client.
![image](https://user-images.githubusercontent.com/54516858/215237519-91289e5e-21cf-49a2-badc-25893caad320.png)

- checking the balance using curl request
![image](https://user-images.githubusercontent.com/54516858/215237184-3518e5a9-021b-457b-9d58-65d924ab466a.png)

**Steps To Reproduce**
1.  Clean clone of branch the install and compile it.
2. Start the client and gateway
3. `connect` centralize exchange like binance and `gateway connect` for injective
4. do `balance` command, balance for injective not shown
5. restart client, do just `gateway connect` or `gateway status` to confirm injective is already connected. Then `balance` command again still nothing. Re-adding the wallet again does not worked as well.

**Attachments**
[logs_gateway_app.log.2023-01-28.zip](https://github.com/CoinAlpha/hummingbot/files/10524390/logs_gateway_app.log.2023-01-28.zip)

**Comment by petioptrv** [comment]
This should be fixed after [00c6668](https://github.com/CoinAlpha/hummingbot/pull/294/commits/00c666823f763cc2593437562d8c0289a2d09e19).

**Comment by RC-13** [comment]
Confirming that this issue has been fixed in the specified commit. Closing ticket now.
![image](https://user-images.githubusercontent.com/57189990/215408273-d17a0515-e453-4473-8172-3ab2d5b9d7b7.png)
