### ISSUE TITLE
Initial Order Issue - Beaxy Connector

### ISSUE THREAD

**Issue by ccraighead** [CoinAlpha/hummingbot#3060]
**Bot Cannot Place First Order**
After connecting to the API, the bot displays a message that an order has been reported failed/cancelled. After a short period of time, the log shows an error message: Markets Are Not Ready. No Market Making Trades Are Permitted. However, if the bot is left open long enough (1 hour or more) it will eventually begin trading. Placing a manual order on the trading platform will also "jump start" this process and the bot will begin trading immediately.

If trading begins, the order ID of the reported initial failed/cancelled order will change. If the bot is stopped and restarted with no trades taking place, the order ID will remain the same.

**Steps To Reproduce**
1) Open the bot and connect to Beaxy
2) Import or create a strategy - pure market making is what I have used
3) Start bot - the issue should be apparent right away.

Note: One user reported that the bot worked the first time, but after stopping, exiting, and re-opening the issue presented itself.

**Release version**
0.37.0

**Attachments**
[Archive.zip](https://github.com/CoinAlpha/hummingbot/files/6113368/Archive.zip)

Cooper#8028

**Comment by dennisocana** [comment]
Confirming with @ccraighead if there are any outstanding issues from backend.

**Comment by ccraighead** [comment]
> I believe one factor that triggers this behavior is that there is no `cancel` call or cancel confirmation for the last orders that were placed when the strategy is stopped.

Whats interesting with this is that it appears to cancel all orders when stopped:
![Screen Shot 2021-03-10 at 10 33 45 AM](https://user-images.githubusercontent.com/49931286/110668272-22dfbe00-8199-11eb-922e-7402d8a42c5e.png)

The last orders placed are cancelled, but I'm not sure if that is recorded in any way

**Comment by RC-13** [comment]
> Are there connection issues to specific enpoints?
There are no clear error displayed from the output pane just stuck with `Market connector not ready` and `Initializing the orderbook`. I left our test bot running and it took more than 10 hours before it runs normally. However, at this moment, the problem persist again. I can't start my strategy. If it helps, there are a lot of `HTTP 500 login token endpoint error`

```
2021-03-10 22:17:18,908 - 13947 - hummingbot.connector.exchange.beaxy.beaxy_auth - NETWORK - Unexpected error while fetching auth token.
Traceback (most recent call last):
  File "/home/ubuntu/beaxy/hummingbot/connector/exchange/beaxy/beaxy_auth.py", line 127, in _auth_token_polling_loop
    await safe_gather(self._update_token())
  File "/home/ubuntu/beaxy/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
    return await asyncio.gather(*args, **kwargs)
  File "/home/ubuntu/beaxy/hummingbot/connector/exchange/beaxy/beaxy_auth.py", line 96, in _update_token
    raise IOError(f'Error while connecting to login token endpoint. HTTP status is {response.status}.')
OSError: Error while connecting to login token endpoint. HTTP status is 500.
```
and `HTTP 520 Web server is returning an unknown error`
[logs_eth_usdt_beaxy.log](https://github.com/CoinAlpha/hummingbot/files/6120423/logs_eth_usdt_beaxy.log)

**Comment by ccraighead** [comment]
> > Are there connection issues to specific enpoints?
> 
> There are no clear error displayed from the output pane just stuck with `Market connector not ready` and `Initializing the orderbook`. I left our test bot running and it took more than 10 hours before it runs normally. However, at this moment, the problem persist again. I can't start my strategy. If it helps, there are a lot of `HTTP 500 login token endpoint error`
>
> and `HTTP 520 Web server is returning an unknown error`
> [logs_eth_usdt_beaxy.log](https://github.com/CoinAlpha/hummingbot/files/6120423/logs_eth_usdt_beaxy.log)

There were some backend issues that have been ironed out, the endpoints should now be functioning as expected.

However I am still seeing the same issue with needing to give the bot a push to make it start. I watched the process on the platform after issuing the stop command, and the orders are cancelled on the platform

**Comment by ccraighead** [comment]
This was caused by one remaining backend update issue. It has been resolved, thank you for testing and investigation.
