### ISSUE TITLE
Refactor blocking API calls

### ISSUE THREAD

**Issue by Nullably** [CoinAlpha/hummingbot#3064]
**Why**
`requests` library is used to call REST API in a number of places. This is not a very good practice as it's not asynchronous and blocking other tasks. This causes issues like https://github.com/CoinAlpha/hummingbot/issues/3042.

**Tasks**
- Update the call to use `async` non blocking `aiohttp`
- Set timeout as needed, the default is 5 minutes.

**Comment by dennisocana** [comment]
As mentioned by Jack, this will address roughly 80% of proposed solution on https://github.com/CoinAlpha/hummingbot/issues/3045

**Comment by Nullably** [comment]
I have identify places where `requests` is used. The work to fix this is divided into 2 parts for easier testing as code reviewing.

1. As part of #2905 PR, this is to remove `get_erc20_token_address_list` and `EthGasStationLookUp`. For testers, please ensure configuration on trading pairs work for Uniswap and Balancer.

2. #3071 I added a comment there for what it is and what to look for in testing.
