### ISSUE TITLE
Loopring - Buy order price in client does not match in exchange

### ISSUE THREAD

**Issue by dietzam** [CoinAlpha/hummingbot#3068]
**Describe the bug**
This might be related to Issue 3016.

When there is a tight spread (such as 1.0012 bid / 1.0013 ask) the hummingbot calculated bid is different from the bid displayed at the Loopring Orderbook.

**Steps To Reproduce**
Run a bot on a tight spread as above.

...

**Screenshots**
See screenshots for verification.
![Screenshot 2021-03-12 151950](https://user-images.githubusercontent.com/8992858/110892676-9673fd80-8348-11eb-9d28-4119ab5a0f45.png)
![Screenshot 2021-03-12 152112](https://user-images.githubusercontent.com/8992858/110892712-aa1f6400-8348-11eb-9862-0812743ccbbf.png)
![Screenshot 2021-03-12 153758](https://user-images.githubusercontent.com/8992858/110892936-19955380-8349-11eb-81f2-6f6dfc27d262.png)

**Release version**
0.36.0

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by RC-13** [comment]
I was able to replicate the behavior one time, however, after getting enough assets for my base token, the behavior did not persist.
When I didn't have enough asset for the base token, the issue occurred:
![loopring bid](https://user-images.githubusercontent.com/57189990/111109909-8ea99880-8596-11eb-8d9d-341c4ead82ad.PNG)

After getting 2 filled buy orders, the issue did not persist ( running for more than an hour):
![loopring bid 1](https://user-images.githubusercontent.com/57189990/111109996-b567cf00-8596-11eb-8970-1e32e843cc7e.PNG)

After reselling the base asset (revert to initial base balance) and start the strategy, the issue did not persist:
![bid price after selling base](https://user-images.githubusercontent.com/57189990/111111657-b9e1b700-8599-11eb-9578-d9c8daa81cc2.PNG)

Another scenario that I did is to test if bid price will be round down if the bid price is equal to the current mid-price, but the price was displayed correctly:
![loopring bid is the same as mid](https://user-images.githubusercontent.com/57189990/111110055-d3353400-8596-11eb-9de6-64b37cc3e3a0.PNG)

Also, I wasn't able to see issue #3016 while testing.

**Comment by dietzam** [comment]
Yes, I think your observation is correct. If there is asset the calculation is correct. But it should equally work is your base assets are lower then the order quantity, because that would be a common situation when running a bot.

**Comment by RC-13** [comment]
@dietzam Are you still experiencing this issue? I can't seem to replicate the issue again.

**Comment by RC-13** [comment]
Closing ticket for now, I wasn't able to replicate the problem again on our test bot.
