### ISSUE TITLE
Adding Indian Brokers

### ISSUE THREAD

**Issue by TechTrader86** [CoinAlpha/hummingbot#3069]
Hi Team,

You are doing great work. It will be great if you can add Indian brokers to your solution (AngelBroking, Zerodha, UPstox)

**Comment by sidmontanez** [comment]
Hi TechTrader86, 
    Thank you for your kind feedback. Currently we don't have plans to integrate Hummingbot towards stock exchanges.

**Comment by TechTrader86** [comment]
Is there any way i can add the stock exchanges
