### ISSUE TITLE
Failed Test PR #294 - Unable to input valid trading pairs during strategy creation

### ISSUE THREAD

**Issue by PtrckM** [CoinAlpha/hummingbot#307]
**Describe the bug**
- Valid pairs are not being accepted by the client and keep saying its not an active market on injective.
![image](https://user-images.githubusercontent.com/54516858/215237813-832ac488-a69c-46dc-a847-d7e717a5dca4.png)

- using the suggested pairs
![image](https://user-images.githubusercontent.com/54516858/215238150-a2d55c98-65a0-4220-83da-a9d8d531001e.png)

- injective config
![image](https://user-images.githubusercontent.com/54516858/215237875-b599653c-77ec-481b-ba5e-f93c57a25482.png)

**Steps To Reproduce**
1. Clean clone of branch the install and compile it.
2. Start the client and gateway
3. connect centralize exchange like binance and gateway connect for injective
4. create strategy using pure_mm or amm_strategy
5. In the prompt of the token trading pair you would like to trade on injective, input any valid pair and it will show not an active market on injective or use the suggested pairs. 

**Attachments**
- n/a

**Comment by petioptrv** [comment]
@CoinAlpha/qa-team, this should be fixed after [00c6668](https://github.com/CoinAlpha/hummingbot/pull/294/commits/00c666823f763cc2593437562d8c0289a2d09e19).

**Comment by RC-13** [comment]
Confirming that this issue has been fixed, closing ticket now.
