### ISSUE TITLE
Implement rate oracle uses on arbitrage and XEMM strategy

### ISSUE THREAD

**Issue by phbrgnomo** [CoinAlpha/hummingbot#3081]
After issue #2939 is finished, and PR is approved by QA, Implement the use of rate oracle on the following strategies:

Additional information:

- add a boolean `config` trigger to choose between automated or manual conversion rate
- The conversion must allow the arbitrage between two quote assets, for example:

Arbitrage between BTC-USD and BTC-BRL

Market A
BTC-USD price: US$ 55,750.00

Market B
BTC-BRL price: R$ 318,430.00

Conversion rate

USD-BRL price: US$ 5.613

Conversion on market B (price converted to BTC-USD):

(BTC-BRL price / USD-BRL price ) = (318,430.00 / 5.613 ) = US$ 56,730.80
 
Final price used by the bot to find arbitrage:

Market A: US$ 55,750.00
Market B (converted): US$ 56,730.80

**Comment by Nullably** [comment]
@phbrgnomo 
Are you fine with this for the naming and oracle configuration check before starting a strategy?
https://github.com/coinalpha/hummingbot/issues/2939#issuecomment-783392980

**Comment by phbrgnomo** [comment]
> Which strategies exactly?

Arbitrage and XEMM, like you mentioned

Check mechanism is good.

For the name, I think that `use_oracle_conversion_rate` would be better.
