### ISSUE TITLE
[Feature] Meaningful names for .conf files

### ISSUE THREAD

**Issue by Steve1943** [CoinAlpha/hummingbot#309]
**Feature Suggestion**
Suggestion to improve ease of administration of ".conf" files - both for maintenance; and for ease of selection via  the HB-GUI control panel.

To aid in the identification of ".conf" files, I have taken to naming them in a meaningful manner.

For example - I include in the file name: 
- the type of trading algorithm (eg ARB, XEMM), 
- the Exchange pair (eg DDEX-Binance), 
- the currency pairs (eg WETHDAI-ETHTUSD).

For ease of legibility, these "key fields" are separated by underscores - or some other character acceptable to both Windows and Unix based operating systems.

For example:
conf_arbitrage_Radar-Binance_WETHDAI-ETHTUSD.yml
conf_xemm_DDEX-Binance_BNBWETH-BNBETH.yml

I propose that HB adopt some similar standard "meaningful" format during the initial creation of ".conf" files by the GUI, employing some recommended set of standard abbreviations for algos,  exchanges and currencies in "key fileds".  

Other configuration parameters might also be usefully included as key fields - subject to abbreviation to avoid excessive length of file names.

Multiple files with equal standard fields would be continue to be un-duplicated with a trailing numeric suffix (NNN), as presently. 

In matching ".conf" files I believe the HB-GUI is presently case indifferent (?), which seems very sensible given that this policy helps Windows habituated users; but does not disadvantage the Unix familiar ones.

**Impact**
Aids user administration of ".conf" files - both for maintenance; and for ease of selection via  the HB-GUI control panel.  The available files when displayed appear sorted by their key fields.

**Comment by mifeng** [comment]
This was completed in v0.26.0
