### ISSUE TITLE
Add timestamps to notification when a buy/sell order is filled

### ISSUE THREAD

**Issue by tom-saetran** [CoinAlpha/hummingbot#3097]
**Feature Suggestion**
So you know... here;
![this](https://user-images.githubusercontent.com/79971807/111552112-f4a64380-8781-11eb-996a-84063971ec04.png)
but with timestamps, delicious timestamps

**Impact**
Im not looking at the log all days, but when I do, I miss the feeling of knowing approx when in time things happened, was the spread of fulfilled orders... mostly in the beginning of the day? the end of the day? a bit here and there?

**Additional context**
Pretend the above screenshoot lives here but is visiting the Feature Suggestion as it likes that neighborhood since this was teh original place to out it according to the guidelines, but it is a bit mischievous

**Comment by RC-13** [comment]
@tom-saetran an alternative for this is running `history --verbose` command to display your filled trades which includes the timestamp when it was filled.
![image](https://user-images.githubusercontent.com/57189990/111562288-e92e3900-87d0-11eb-9e22-5e0bb09eebff.png)

**Comment by tom-saetran** [comment]
> @tom-saetran an alternative for this is running `history --verbose` command to display your filled trades which includes the timestamp when it was filled.
> ![image](https://user-images.githubusercontent.com/57189990/111562288-e92e3900-87d0-11eb-9e22-5e0bb09eebff.png)

This would still require input though, I would like to be able to put the CUI on a monitor without a keyboard attached for an at-glance feel of the performance. Having timestamps would greatly increase the overall picture one can get

**Comment by willzs03** [comment]
Hey @tom-saetran, take a look at the Pull Request above! Specifically, take a look at the picture in the PR and the changed code. I managed to print timestamps on executed pure_market_making (PMM) trades. My implementation should also work for any other strategy, you will just have to modify the respective .pyx file.

**Comment by willzs03** [comment]
@tom-saetran, take a look at the code in [here](https://github.com/CoinAlpha/hummingbot/pull/3279). I managed to get some timestamps printed out by modifying part of the source code. It took me some time and my implementation only works for the PMM strategy, but you can easily copy paste the changes to whatever strategy you're using. Hope this helps!
