### ISSUE TITLE
Default Ethereum RPC URL

### ISSUE THREAD

**Issue by philipperemy** [CoinAlpha/hummingbot#31]
What is the default Hummingbot ETH RPC URL? Is there a public provider for that?

In docs, https://www.hummingbot.io/docs/configuration/ (point 8), I can leave this field blank.

When I leave it blank, the value is set to None in the conf_global:

```
ethereum_rpc_url: None
```

And then I cannot start the script because the value is invalid.

Still in the same docs, there's an example:

![image](https://user-images.githubusercontent.com/4516927/55692823-4e266500-59e6-11e9-9846-c4d1f98be56a.png)

The value here is `start` for ETH RPC URL. So I'm a bit confused.

**Comment by carlolm** [comment]
We are not currently providing a default ETH RPC URL, but hummingbot is compatible with 3rd party node providers if you don't want to run your own node.
Some providers you can try are: https://infura.io/, https://alchemyinsights.io/, or https://quiknode.io/.

When entering the URL, make sure you enter the full URL including "http://" or "https://".

**Comment by philipperemy** [comment]
@carlolm ok fair enough thank you!
