### ISSUE TITLE
Classic arbitrage strategy, independent profit targets for each exchane

### ISSUE THREAD

**Issue by ugurvu** [CoinAlpha/hummingbot#3100]
Currently, there is only one setting for desired profit: min_profitability. So the bot tries to reach this target on both exchanges. But for many instruments, prices usually higher on one exhange than others. Prices differences aren't symmetrical.

My suggestion is instead of just min_profitability, there might be two distinct settings: primary_market_min_profitability, secondary_market_min_profitability.  

Attached an example instrument. Indicator shows price differences between two markets. For instance, if you set min_profitability 5, orders never gets triggered on one exhange. primary_market_min_profitability, secondary_market_min_profitability, set 2 (or 0, or even -1) and 5, now it works. 
 
![Opera Snapshot_2021-03-19_125656_www tradingview com](https://user-images.githubusercontent.com/1411746/111766543-b6f70700-88b6-11eb-930b-0b24b33b2b0d.png)

**Comment by phbrgnomo** [comment]
Duplicated issue #1887. If you have more comments/suggestions to add, please use that issue.
