### ISSUE TITLE
Unexpected error running clock tick

### ISSUE THREAD

**Issue by ccs6667778** [CoinAlpha/hummingbot#3104]
16:01:30 - clock - Unexpected error running clock tick. (See log file for stack trace dump)

[logs_Ku.txt](https://github.com/CoinAlpha/hummingbot/files/6185265/logs_Ku.txt)

**Comment by rxlxrxsx** [comment]
Hi, will you be able to provide your config when you encountered this issue?

**Comment by ccs6667778** [comment]
[Ku.zip](https://github.com/CoinAlpha/hummingbot/files/6186315/Ku.zip)

**Comment by rxlxrxsx** [comment]
Thanks. Can you try adjusting the values on ask_order_optimization_depth and bid_order_optimization_depth? It seems that with the current value you entered the bot tries to place the orders 'too deep', order sizes on the BTC-USDT  are typically on decimal values only. I tried setting the depths to 10 with BTC-USDT market as well and it's working properly.

**Comment by RC-13** [comment]
@ccs6667778 Are you still experiencing this issue after following the step provided by @rxlxrxsx ?

**Comment by RC-13** [comment]
Closing this ticket, feel free to reach us on our [discord server](https://discord.hummingbot.io/) if the same issue persists.
