### ISSUE TITLE
[Feature]: Scaffold for exchange connection implementation / documentation

### ISSUE THREAD

**Issue by alexCatena** [CoinAlpha/hummingbot#311]
It would be extremely helpful to have some sort of scaffold or boilerplate for the exchange connections so users can connect to whichever exchange they want. 
If not boilerplate then some documentation on how the data is stored and what is needed for the connection to work

**Comment by ImTheDeveloper** [comment]
Agree I've got a new exchange going live with APIs very soon and I'd love to build a connector

**Comment by yzhang1994** [comment]
We have added documentation on how to build a connector: https://docs.hummingbot.io/developers/connectors/. 
We'll continue to add content to this page.
