### ISSUE TITLE
AMM Arb - Uniswap and Balancer transaction errors

### ISSUE THREAD

**Issue by sdgoh** [CoinAlpha/hummingbot#3114]
**Describe the bug**
Uniswap amm_arb transaction fails intermittently with error `Fail with error 'UniswapV2Router: EXCESSIVE_INPUT_AMOUNT'`

Balancer amm_arb transaction fails intermittently with error `Fail with error 'ERR_INSUFFICIENT_BAL'`

Network: Kovan

Observations: 
- During testing on high profitability setting of `1000`, the transactions completed without any issues.
- When using the profitability setting of `-1`, transaction failure tend to occur. 

**Steps To Reproduce**

**Release version**
Gateway: 0.3.1 (PR: https://github.com/CoinAlpha/gateway-api/pull/37)
Client: dev-0.38.0 (PR: https://github.com/CoinAlpha/hummingbot/pull/2905)

Issues report original source: https://github.com/CoinAlpha/gateway-api/pull/37#issuecomment-805764680

**Comment by PtrckM** [comment]
- :white_check_mark: using positive and negative value for minimum profitability = FIX
   - adjusting UNISWAP_ALLOWED_SLIPPAGE
      - due to price movement
      - increasing the value will result a larger spread
      - this will prevent potential txn error 

- uniswap txn's
![image](https://user-images.githubusercontent.com/54516858/112716058-0b396100-8f1f-11eb-9eeb-54f99b9851ea.png)

- bot
![image](https://user-images.githubusercontent.com/54516858/112716199-e2fe3200-8f1f-11eb-9322-341b585eea7b.png)

- sqlite data and csv
[sqlite_csv.zip](https://github.com/CoinAlpha/hummingbot/files/6215427/sqlite_csv.zip)

**Comment by RC-13** [comment]
Fix on version 0.38.0
