### ISSUE TITLE
Pause and resume do not restore order book

### ISSUE THREAD

**Issue by liquidand** [CoinAlpha/hummingbot#3117]
**Describe the bug**
Following the procedure to use the Pause and resume feature, do not restore the order book.

**Steps To Reproduce**

1. Paper trading on
2. import yml for pure market trading
3. start the bot and wait for some order to be placed
4. exit --suspend
5. start and attach to humming bot
6. import yml for pure market making(same configuration file as in step 2)
7. start --restore
8. The bot do not recover orders

**Release version**
0.37.1

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 
[logs_test11.log](https://github.com/CoinAlpha/hummingbot/files/6211535/logs_test11.log)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**
liquidand

**Comment by TheHolyRoger** [comment]
@liquidand is this only with paper trading? Does it work live?

**Comment by RC-13** [comment]
The pause and resume feature is currently not supported on Paper_trading however this shouldn't be an issue on live trading. I will be closing this ticket and feel free to open an enhancement or feature request to have this feature supported on paper trade.
