### ISSUE TITLE
[BUG] Stop loss percentage calculation clangs

### ISSUE THREAD

**Issue by Steve1943** [CoinAlpha/hummingbot#312]
**Describe the bug**
GUI reports error calculating stop loss percentage and refers to stack trace.

**Steps To Reproduce**
ran xemm strategy between RadarRelay and Binance for currency pair DNT-ETH
Config file; console log; and system log attached

**Screenshots**
see GUI_console_log.txt

**Release version**
master -   Version: 0.7.0

**Attachments**
[hummingbot_logs_2019-05-28-23-52-34.log](https://github.com/CoinAlpha/hummingbot/files/3229901/hummingbot_logs_2019-05-28-23-52-34.log)

[conf_xemm_Radar-Binance_DNTWETH-DNTETH.yml.txt](https://github.com/CoinAlpha/hummingbot/files/3229904/conf_xemm_Radar-Binance_DNTWETH-DNTETH.yml.txt)

[GUI_console_log.txt](https://github.com/CoinAlpha/hummingbot/files/3229906/GUI_console_log.txt)

**Optional: your discord username:**
Steve1943

**Comment by yzhang1994** [comment]
This bug happened because DNT is not a supported token on CoinCap, which stop loss uses to calculate portfolio value. Should have been fixed by the PR above and will be included in 0.8.0

**Comment by Steve1943** [comment]
Thx Yvonne for the update.  Presumably the fix will also work for any other coin not available via the CoinCap API?

Which leads me to a follow-on point, which I will record separately in an enhancement suggestion - which is to replace CoinMarketCap.com as a pricing source by an alternative which is: (a) more reliable and (b) more comprehensive.
