### ISSUE TITLE
BCDT/ETH pair not supported on Loopring

### ISSUE THREAD

**Issue by grostim** [CoinAlpha/hummingbot#3120]
**Describe the bug**
I want to use amm_arb with the BCDT/ETH pair on loopring.io.
https://exchange.loopring.io/swap/BCDT-ETH

I have an error message "market is not active on loopring". 

Please add this pair to the loopring connector.

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: ...
2. Start the bot using this command: ...
...

**Screenshots**
// If applicable, add screenshots to help explain your problem.

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**
Sorg

**Comment by sidmontanez** [comment]
Hi @grostim! You can add the token address to your `erc20_tokens_override.json` found on your Hummingbot directory under `conf` or `hummingbot_conf` folder.

You could follow the reference below from this link: https://docs.hummingbot.io/gateway/installation/#setting-up-kovan-testnet

**Comment by RC-13** [comment]
@grostim As of the moment, we currently don't support the AMM of Loopring. This is why that pair you want to use is unavailable. You can use Loopring as your connector however this will use pairs available in the order book (trade). I will be closing this ticket, and you can open a new one but instead set it as a feature request to support AMM of Loopring.
