### ISSUE TITLE
OKEx upgrade to V5

### ISSUE THREAD

**Issue by rapcmia** [CoinAlpha/hummingbot#3125]
**Feature Suggestion**
It was recently announced that OKEx will update its API to v5. Currently, the bot handles API v3 and newly created accounts for OKEx are now API v5 enabled. 

Link: https://www.okex.com/academy/en/complete-guide-to-okex-api-v5-upgrade

**Impact**
OKEx connector can only cater API v3 but not with v5. I tried to create a new account and there is no option for me to select back to v3.

![image](https://user-images.githubusercontent.com/73840223/112814848-48822800-90b2-11eb-8f1a-86b50fe86e0a.png)

**Additional context**
Here is the error the bot is getting when using OKEx API v5
![image](https://user-images.githubusercontent.com/73840223/112815002-71a2b880-90b2-11eb-9d30-e0d0cb4e117a.png)

**Comment by dennisocana** [comment]
Completed in version 0.39 release
