### ISSUE TITLE
Liquid - Could not fetch account updates

### ISSUE THREAD

**Issue by tampham47** [CoinAlpha/hummingbot#3126]
**Describe the bug**
I tried to do arbitrage between Liquid and Binance. Before starting, I get this error `Could not fetch account updates on Liquid.`. I don't face this error when running pure market making. After checking, I think Liquid is no longer supports this API `FIAT_ACCOUNTS_URI = '/fiat_accounts'`. Both Fiat + crypto accounts can be found from `/accounts` api.

![Screen Shot 2021-03-29 at 20 11 43](https://user-images.githubusercontent.com/5687992/112841745-1204d700-90cb-11eb-84c9-df7dd4075562.png)

**Steps To Reproduce**
Running arbitrage between Binance + Liquid.

**Screenshots**
![Screen Shot 2021-03-29 at 20 13 26](https://user-images.githubusercontent.com/5687992/112841913-3eb8ee80-90cb-11eb-93b0-c4e8f8025f72.png)

**Release version**
0.37.1

**Attachments**

```
#####################################
###   Arbitrage strategy config   ###
#####################################

template_version: 4
strategy: arbitrage

# The following configuations are only required for the
# arbitrage strategy

# Exchange and token parameters
primary_market: binance
secondary_market: liquid
primary_market_trading_pair: BTC-USDT
secondary_market_trading_pair: BTC-USDT

# Minimum profitability target required to place an order
# Expressed in percentage value, e.g. 1 = 1% target profit
min_profitability: 0.95

# The conversion rate for secondary base asset value to primary base asset value.
# e.g. if primary base asset is USD, secondary is DAI and 1 USD is worth 1.25 DAI, "
# the conversion rate is 0.8 (1 / 1.25)
secondary_to_primary_base_conversion_rate: 1.0

# The conversion rate for secondary quote asset value to primary quote asset value.
# e.g. if primary quote asset is USD, secondary is DAI and 1 USD is worth 1.25 DAI, "
# the conversion rate is 0.8 (1 / 1.25)
secondary_to_primary_quote_conversion_rate: 1.0

# For more detailed information, see:
# https://docs.hummingbot.io/strategies/arbitrage/#configuration-parameters
```
*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Comment by rxlxrxsx** [comment]
It seems to me that you're having connection issues with Liquid during your session, can you try to run the strategy again? Here's a screenshot from earlier while trying to run the strategy, I can't seem to replicate the behavior you reported

<img width="1365" alt="Screen Shot 2021-03-30 at 2 28 26 PM" src="https://user-images.githubusercontent.com/64377055/112943579-41b3ed80-9164-11eb-8653-390b4aa1a1eb.png">

**Comment by rxlxrxsx** [comment]
Hi @tampham47, are you still encountering connection issues when running arbitrage using Liquid?

**Comment by tampham47** [comment]
It works now, I think sometime I reach limitation when running a few bot at the same time. I think it's not humming bot issue. Thank you for your support.
