### ISSUE TITLE
Rename Fieldfare strategy to Avellaneda strategy

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#3142]
Stakeholders have agreed to use the name `avellaneda` instead of `fieldfare` for the Avellaneda-Stoikov strategy. This story is to update this requested change from the client side.

https://github.com/CoinAlpha/hummingbot/pull/2956

**Comment by keithbaum** [comment]
This is done. Please check PR https://github.com/CoinAlpha/hummingbot/pull/2956

**Comment by dennisocana** [comment]
Thanks @keithbaum , closing story for completion.
