### ISSUE TITLE
HitBTC - USDT balance no longer recognize

### ISSUE THREAD

**Issue by RC-13** [CoinAlpha/hummingbot#3160]
**Describe the bug**
The USDT balance is no longer recognize. Since HitBTC labels USD as USDT,  I think this  PR (https://github.com/CoinAlpha/hummingbot/pull/3124)  alters how bot check the USDT asset.
![Hitbtc](https://user-images.githubusercontent.com/57189990/113535600-78778100-9606-11eb-9be2-e6c8f9b950cd.PNG)

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):
1. Update to the latest development commit
2. Create PMM strategy using HitBTC as a connector
3.  Set any USDT market pair
4.  Start strategy and run the status command
5. Run balance command and compare the USD and USDT asset
...

**Release version**
0.38.0

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by rxlxrxsx** [comment]
Fixed in version 0.38.0
