### ISSUE TITLE
Ascendex - delay with order pricing when running order book --live

### ISSUE THREAD

**Issue by RC-13** [CoinAlpha/hummingbot#3164]
**Describe the bug**
Opening ticket for monitoring. When running `order_book --live` some prices shown on the bot don't match the current best price in the exchange order book.

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):
1. Create a pure market making strategy and use Ascendex as an exchange
2. Use a market pair that doesn't move too fast to easily capture the issue.
3. Start the strategy and run `order_book --live` and open Ascendex website and compare the best orders for the chosen market.

**Screenshots**
![Ascendex](https://user-images.githubusercontent.com/57189990/113552631-f9e00b00-9628-11eb-99e9-7f815a0c1ef1.png)
![Ascendex1](https://user-images.githubusercontent.com/57189990/113552634-fba9ce80-9628-11eb-9ae2-bd2a177b31b7.png)

**Release version**
0.38.1

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by rxlxrxsx** [comment]
Attaching screenshot wherein bid orders are also out of sync (LINK-ETH)

<img width="750" alt="Screen Shot 2021-05-31 at 12 12 46 PM" src="https://user-images.githubusercontent.com/64377055/120139123-61ba6880-c20a-11eb-8f54-93e6beddc6ac.png">

**Comment by Nullably** [comment]
Mismatched and un-synced order book can cause big trading losses, I changed the priority to P1.

**Comment by dennisocana** [comment]
Fixed in version 0.40 release
