### ISSUE TITLE
Probit fail to cancel orders 

### ISSUE THREAD

**Issue by viktor-settlemint** [CoinAlpha/hummingbot#3167]
**Describe the bug**
When running pure market making strategy on Probit, there are many orders which are not being cancelled properly. After some cycles one end up with many orders hanging in the book without being canceled, so pretty dangerous situation.

**Steps To Reproduce**

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: 
<img width="1419" alt="Screenshot 2021-04-05 at 16 27 55" src="https://user-images.githubusercontent.com/80774122/113585003-e97d5f80-962b-11eb-8735-3bee9c5e4815.png">

2. Example of hanging orders:

<img width="1419" alt="Screenshot 2021-04-05 at 16 29 39" src="https://user-images.githubusercontent.com/80774122/113585170-26495680-962c-11eb-9760-3ace6fe18f29.png">

3. How to replicate:
I can't share my log file as it is too big but the errors that I see are the followings

<img width="693" alt="Screenshot 2021-04-05 at 16 31 59" src="https://user-images.githubusercontent.com/80774122/113585411-7a543b00-962c-11eb-8740-0396ea98e92d.png">

**Release version**
0.37.1

**Optional: your discord username:**
viksettle

**Comment by RC-13** [comment]
@viktor-settlemint Are you still experiencing this issue? If yes, kindly upload your logs for us to further check into this. In case you get the behavior again, kindly try clearing or deleting the sqlite file of your bot found on the `data` folder (https://hummingbot.zendesk.com/hc/en-us/articles/900005206343-Where-is-my-config-and-log-file-).

**Comment by viktor-settlemint** [comment]
@RC-13 No indeed removing the data folder made the trick, what was the reason for that status
