### ISSUE TITLE
Add order levels and hanging orders to Avellaneda MM strategy

### ISSUE THREAD

**Issue by keithbaum** [CoinAlpha/hummingbot#3168]
**Feature Suggestion**
User should be able to include multiple order levels within min-max spread limits. Also, hanging orders feature should be added to favor users who use HBOT for liquidity mining campaigns.

**Criteria of Acceptance**
With both order levels and hanging orders features enabled, strategy should still be able to reach and maintain inventory levels. As this features are out of the original algorithm scope this should be optional.

**Comment by phbrgnomo** [comment]
Broken down to issues #3290 & #3291. Closing this one.
