### ISSUE TITLE
Publish Uniswap v3 contracts on public testnet

### ISSUE THREAD

**Issue by mifeng** [CoinAlpha/hummingbot#3169]
Use https://remix.ethereum.org/ or another service to deploy the Uniswap v3 core and periphery npm artifacts to Ropsten/Kovan testnet.

**Comment by mifeng** [comment]
I created a sample repo https://github.com/CoinAlpha/uniswap-v3 to show how to deploy the Uniswap v3 core contracts to a local blockchain so that we can start interacting with them.

**Comment by viktor-settlemint** [comment]
@mifeng we can't access this repo, is it normal?

**Comment by mifeng** [comment]
> @mifeng we can't access this repo, is it normal?

Yes, it's an internal repo for us to experiment with - we're not opposed to open sourcing it later but it's not really functional yet.

**Comment by mifeng** [comment]
Changing this story to "publish Uniswap v3 contracts on public testnet" after discussion with @vic-en. Since we need to test functionality by creating pools and swapping against them, having each engineers deploy to local testnet would be redundant. It would be better to have public contracts that we can test against.

@vic-en Remix, Truffle or Hardhat might be helpful, but you might also be able to use https://github.com/CoinAlpha/uniswap-v3 to deploy the contracts to Ropsten directly by changing the `web3` provider.

**Comment by mifeng** [comment]
@vic-en please add the addresses of the deployed contracts here and mark this story as **Done** afterwards

**Comment by vic-en** [comment]
Core contract deployed at 0xddB3D3CdC00fc8D8C847d4d2c3Ad0779A2024C0c
Router deployed at 0x0560b6700f8e3cdc798c33c8d08ab3ce1e15b0c2
