### ISSUE TITLE
Avellaneda MM - Strategy parameters not showing on status output

### ISSUE THREAD

**Issue by rxlxrxsx** [CoinAlpha/hummingbot#3183]
**Describe the bug**
There are instances when running the avellaneda_mm strategy that when you enter `status` command it doesn't show the strategy parameters (risk factor, order_book_depth_factor, volatility and closing time). So far I've only seen this happen on Liquid and Kraken but will further check if other connectors are affected.

**Steps To Reproduce**

1. Run a avellaneda_market_making bot
2. After the bot finishes calculating for volatility it'll now place orders
3. Run status command and notice that it'll not show the strategy parameters output

**Screenshots**
On Liquid
<img width="1424" alt="Screen Shot 2021-04-07 at 11 13 41 AM" src="https://user-images.githubusercontent.com/64377055/113811654-333a8700-979f-11eb-9e2c-30527080163b.png">

On Kraken
<img width="1423" alt="Screen Shot 2021-04-07 at 12 02 17 PM" src="https://user-images.githubusercontent.com/64377055/113811601-1a31d600-979f-11eb-9b3c-f39e4d2caad9.png">

Expected sample output on Binance
<img width="1423" alt="Screen Shot 2021-04-07 at 12 47 10 PM" src="https://user-images.githubusercontent.com/64377055/113811791-6bda6080-979f-11eb-8a74-749b935b2f29.png">

**Release version**
development-0.39.0

**Attachments**
Kraken logs and config: [kraken.zip](https://github.com/CoinAlpha/hummingbot/files/6269050/kraken.zip)
Liquid logs and config: [liquid.zip](https://github.com/CoinAlpha/hummingbot/files/6269059/liquid.zip)

**Comment by dennisocana** [comment]
Fixed in version 0.39
