### ISSUE TITLE
Update Setup to Include `avellaneda_market_making`

### ISSUE THREAD

**Issue by R-K-H** [CoinAlpha/hummingbot#3186]
https://github.com/CoinAlpha/hummingbot/blob/e050655084e544b9fc921bc4c9a771aa04149fa5/setup.py#L81

For building locally I think you might want to include this in the setup file?

`"hummingbot.strategy.avellaneda_market_making"`

**Comment by dennisocana** [comment]
Thanks @R-K-H , this will be included in the version 0.39 release.
