### ISSUE TITLE
LM strategy - Token parameter set to none after importing the config file

### ISSUE THREAD

**Issue by dendenski** [CoinAlpha/hummingbot#3188]
**Describe the bug**
Token parameter set to none after importing the config file

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):
1. Create LM strategy.
2. Modify market using this command `config markets ALGO-USDT,FIRO-USDT`.
3. import the LM strategy.
4. token parameter set to none.

**Screenshots**
![image](https://user-images.githubusercontent.com/65387749/113946824-e3f66400-983b-11eb-81e7-5eae51ba29b4.png)

![image](https://user-images.githubusercontent.com/65387749/113946869-f8d2f780-983b-11eb-9345-e54db0ee7306.png)

**Release version**
v0.38.0

**Optional: your discord username:**
dennis b. | support

**Comment by rxlxrxsx** [comment]
Related to #2125

**Comment by rxlxrxsx** [comment]
Closing the ticket as issue no longer persists on the latest version (0.43.0)
