### ISSUE TITLE
Coinzoom - inconsistency with order creation due to delay with balance update

### ISSUE THREAD

**Issue by RC-13** [CoinAlpha/hummingbot#3190]
**Describe the bug**
Opening ticket for tracking: Order creation is inconsistent every after a cycle due to how fast the available balance gets updated.

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):
1. Create a pure market-making strategy and use any market.
2. Make sure that your balance is just enough to create orders on both sides or use the balance limit to easily reproduce the behavior.
3. Start the strategy and run `status --live` and observe the created order after every cycle.

**Screenshots**

https://user-images.githubusercontent.com/57189990/113984231-71a67380-987d-11eb-9a3b-2e5f3b301a74.mov

**Release version**
0.38.0

**Attachments**
[logs_coinzoom_btc-usdt.log](https://github.com/CoinAlpha/hummingbot/files/6276789/logs_coinzoom_btc-usdt.log)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by TheHolyRoger** [comment]
This PR https://github.com/CoinAlpha/hummingbot/pull/3520 might close this issue

**Comment by dennisocana** [comment]
Fixed in version 0.42 release. Thanks @TheHolyRoger
