### ISSUE TITLE
Huobi - Bot fails to track submitted order due to "API signature not valid"

### ISSUE THREAD

**Issue by RC-13** [CoinAlpha/hummingbot#3197]
**Describe the bug**
Creating tickets for tracking:
While checking the Huobi test bot, I've noticed that the bot no longer places any order due to not having enough available balance. And found out that they are all left out on the exchange. 

This issue happens whenever an API error message occurs on the log pane (randomly happens but sometimes, it may occur continuously). 
![image](https://user-images.githubusercontent.com/57189990/114161802-0b901e00-995b-11eb-86c9-c2a7c83c3fac.png)

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):
1. Create any strategy and use Huobi for your exchange. In this scenario, I created a pure market making strategy
2. Configure your desired parameter and start the strategy.
3. Run status --live and observe the available balance and log pane.
4. Whenever the API invalid signature message occurs, notice that the available balance keeps decreasing, and also, no cancel message is given on the logs.

Note:
- Current API key is correct and not yet expired.
- Created a new API key and add it to the bot, however, the same issue persists.
- Try a different Huobi account and API, same result.
- Check Huobi's website for a possible issue, didn't see any, however, I reached out to Huobi support and waiting for the response.

**Release version**
0.38.0

**Attachments**
[logs_huobi_avellaneda_mm.log](https://github.com/CoinAlpha/hummingbot/files/6284789/logs_huobi_avellaneda_mm.log)
[logs_huobi_ht-usdt.log](https://github.com/CoinAlpha/hummingbot/files/6284793/logs_huobi_ht-usdt.log)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by RC-13** [comment]
These lost tracked orders, once filled, the bot won't know as well
![image](https://user-images.githubusercontent.com/57189990/114642744-076f5200-9d07-11eb-9fd0-e410a0a2fdbd.png)
highlighted in red are lost track orders
![image](https://user-images.githubusercontent.com/57189990/114642905-443b4900-9d07-11eb-83bb-df4a5aa91124.png)

**Comment by dennisocana** [comment]
Fixed in version 0.38.1
