### ISSUE TITLE
how to calculate gamma、kappa in avellaneda_market_making?

### ISSUE THREAD

**Issue by ahao1995** [CoinAlpha/hummingbot#3198]
I run this avellaneda_market_making strategy, but I have some questions.
I don't know why gamma and kappa calculate by this way, I see the paper but can't find how to calculate this. Is there any paper mention it?

`max_possible_gamma = min(
                                    (max_spread - min_spread) / (2 * abs(q) * (vol ** 2)),
                                    (max_spread * (2-self._inventory_risk_aversion) /
                                     self._inventory_risk_aversion + min_spread) / (vol ** 2))
            self._gamma = self._inventory_risk_aversion * max_possible_gamma

            # KAPPA
            # Want the maximum possible spread but with restrictions to avoid negative kappa or division by 0
            max_spread_around_reserved_price = max_spread * (2-self._inventory_risk_aversion) + min_spread * self._inventory_risk_aversion
            if max_spread_around_reserved_price <= self._gamma * (vol ** 2):
                self._kappa = Decimal('1e100')  # Cap to kappa -> Infinity
            else:
                self._kappa = self._gamma / (Decimal.exp((max_spread_around_reserved_price * self._gamma - (vol * self._gamma) **2) / 2) - 1)

            # ETA

            q_where_to_decay_order_amount = self.c_calculate_target_inventory() * (1 - self._inventory_risk_aversion)
            self._eta = s_decimal_one
            if q_where_to_decay_order_amount != s_decimal_zero:
                self._eta = self._eta / q_where_to_decay_order_amount`

**Comment by keithbaum** [comment]
Hi @ahao1995, actually the paper does not offer a way to calculate gamma nor kappa. The calculation of the these parameters is an extension of the paper calculations done by our team in order to facilitate the election of parameters, using the restrictions given by user (min/max spread, inventory risk aversion).
If you don't want to stick to this calculations, you can select parameters_based_on_spread equal to false, and you will be able to select manually gamma, kappa and eta.

**Comment by keithbaum** [comment]
@ahao1995 More about the way these parameters are automated using the user restrictions can be previewed in this article (internal link https://www.notion.so/hummingbot/Avellaneda-Stoikov-strategy-doc-7ad9e29ee45c41a8b27e013e04ef060e).
This will be formalized in a hummingbot blog post in a couple of days.
Thanks for your curiosity :)

**Comment by ahao1995** [comment]
thank you ~

**Comment by ahao1995** [comment]
I have another question，at the same there is only two orders, one buy and one sell. when the next tick come,this strategy  must should cancel previous order and create new order?  It can not keep the previous orders for a while, and at the same time create a new order?I am poor in finance, withthe feeling if it can keep more, more possible can trade. @keithbaum

**Comment by keithbaum** [comment]
hey @ahao1995, look for parameter 'order_refresh_tolerance_pct' (see more here https://docs.hummingbot.io/strategies/order-refresh-tolerance/#order_refresh_tolerance_pct). It allows you to leave old orders to stay and delay their cancellation if they stay within certain range from current mid_price

**Comment by keithbaum** [comment]
@ahao1995 if you are ok with it, I'll proceed and close this issue.

**Comment by ahao1995** [comment]
ok~I work it,thank you~
