### ISSUE TITLE
Observation on Memory Usage/Help to Build From Source

### ISSUE THREAD

**Issue by rogueops** [CoinAlpha/hummingbot#3204]
When v0.37 came out I saw a huge difference in memory usage, or at least what it showed it was using. I use docker as I run multiple so using less resources costs me less as I run them in the cloud. When v0.37 came out when starting a bot it was around the low 80's in megs for usage and of course like most things do it growed over time, normal stuff, but having it start that low makes it so I dont have to reset/reboot as often. When v0.37.1 came out it went up to 90's, still lower then before which when starting at bot I would see it start at 105 megs and grow, when I upgraded to v0.38 it went back to the same mem usage as before 0.37. I was interested in trying the new strat so I have not reverted. The figures above may sound very low, but if you add the resources docker uses it amounts to around 500mb for one instance on first start. As the title says, this is an observation on resource usage when using docker, if building the source and running it in screen would use less I will give it a try, recently tried the guide to install from source and the installer kept running into issues on Debian 9 so I just kept using docker.

**Comment by rogueops** [comment]
If anyone can help me with testing running the source on Debian 9 x64( base resource usage is less that the newest ), i have been trying for hours and not stuck on the steps of "conda activate hummingbot". I follow the guides to the letter and once the install scripts kept failing I have gone through each step listed in the manual section to figure out where its getting stuck and its conda activate. I can get through the other steps with no issue, but when I issue "conda activate hummingbot" I get "Could not find conda environment" and when i issue "conda info --envs" the output is :

# conda environments:
# base                  ~/miniconda3

Seem to have worked through all the other issues, i was not able to just follow the guide and have everything setup and install using the scripts or the guides so I have been keeping track of the working steps to give to the devs, tried just the scripts and thats how I went down this rabbit hole of chasing errors, dependencies, and error trying to just get the source built. Its about 3AM my time so gonna call it a night and pause for now, if you need any more info just post and once i awaken i will get the data you need

**Comment by rogueops** [comment]
The below is when using the install script in the docs

Thank you for installing Miniconda3!
Cloning into 'hummingbot'...
remote: Enumerating objects: 30, done.
remote: Counting objects: 100% (30/30), done.
remote: Compressing objects: 100% (24/24), done.
remote: Total 57678 (delta 12), reused 12 (delta 6), pack-reused 57648
Receiving objects: 100% (57678/57678), 61.85 MiB | 32.21 MiB/s, done.
Resolving deltas: 100% (44069/44069), done.
Collecting package metadata (repodata.json): / ./install: line 34: 14342 Killed                  ${CONDA_EXE} env create -f $ENV_FILE
Could not find conda environment: hummingbot
You can list all discoverable environments with `conda info --envs`.

Collecting objgraph
  Downloading objgraph-3.5.0-py2.py3-none-any.whl (17 kB)
Collecting graphviz
  Downloading graphviz-0.16-py2.py3-none-any.whl (19 kB)
Installing collected packages: graphviz, objgraph
Successfully installed graphviz-0.16 objgraph-3.5.0
./install: line 42: pre-commit: command not found
Could not find conda environment: hummingbot
You can list all discoverable environments with `conda info --envs`.

./install-source-debian.sh: line 18: /root/miniconda3/envs/hummingbot/bin/python3: No such file or directory

**Comment by rogueops** [comment]
After looking through the install and running line by line, it fails when it gets to

conda env create environment-linux.yml

**Comment by dennisocana** [comment]
Thanks for reporting this @rogueops . Our support and testing will try to reproduce this and give you feedback.

**Comment by sidmontanez** [comment]
Hi @rogueops Apologies for the late reply. I was able to breeze through the script installation and clone the terminal using Debian  although when I tried to log back in to hummingbot I happen to encounter the same error with `Could not find conda environment: hummingbot` . I'll try to relay this over to the team to check If this happens often when installing Source from Debian.

**Comment by rogueops** [comment]
Glad its not me, i kept trying over and over as I figured the issue was the
VPS or a step I did, so I tried each step in the script the last time to
see if I could narrow it down.

**Comment by PtrckM** [comment]
@rogueops we're not able to replicate the error you are getting when using and activating conda on Debian 9. Test done both `install-source-debian.sh` and [manual installation process](https://docs.hummingbot.io/installation/linux/#install-from-source-1) on Windows + WSL2 Debian and aws t2.small Debian 9. Installing and running the bot works fine as intended. 

Currently we are monitoring 3 bots running on Debian 9 on aws vCPUs 1 Memory 2GB

Bots not running any strategy 260MB (idle)

Bot1 = 30 minutes 288MB after 24hrs 292MB
Bot2 = 30 minutes 286MB after 24hrs 290MB
Bot3 = 30 minutes 278MB after 24hrs 279MB

**Comment by rogueops** [comment]
If you look at the replies another user was able to. I can use docker with
no issues at all, just cant build from source which is the first time I
tried and also spun up ubuntu and centos and the same thing happened. Is
there a min memory to build from source? I can spin up a server on my cloud
host and let you see it happen. I gave up after two days and when the other
user posted he got the same error.

**Comment by PtrckM** [comment]
yes similar to https://github.com/CoinAlpha/hummingbot/issues/2564 we're not able to install source build when using aws t2.micro which has 1 vCPU and 1gb memory but able to run docker build. It's advisable to use similar specs to aws t2.small which has 2gb of memory if you still want to run source build.

**Comment by rogueops** [comment]
good to know, i will try and report back

**Comment by rogueops** [comment]
I do not know the specs of the other person that had the same issue

**Comment by rogueops** [comment]
all good, will make sure to use 2GB min to build from source
