### ISSUE TITLE
Service does not read mining data from the Kucoin exchange

### ISSUE THREAD

**Issue by shan8111** [CoinAlpha/hummingbot#3205]
**Describe the bug**
In my main account does not display information about mining from the Kucoin exchange, although the API key is tied to the account and the bots work normally when placing orders on the exchange.

**Steps To Reproduce**
Several times I created a new key and linked it to my account, but nothing helped, only creating a new account on hummingbot helped. I use for mining all available pairs on the Binance (24) and Kucoin (10) exchanges. Perhaps this led to the system starting to work with an error and did not see the placed orders from the Kucoin exchange. Although the data came from the Binance exchange regularly.

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: ...
2. Start the bot using this command: ...
...

**Screenshots**
There is no need to attach screenshots, since the problem is not on my side.

**Release version**
// Include your bot's version number 0.37.1

**Attachments**
There is no need to attach files, since the problem is not on my side.

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username: Shan

**Comment by glenntomas** [comment]
Hi Shan! 

Have you tried the following:
- Before trying the following disconnect first the API key connected to your miner account
- Generate two separate new API keys: 
  - For Binance 
         1. `Enable Reading` permission API key for your miner account 
         2. `Enable Reading` and `Enable Spot & Margin Trading` permission API key for your bot
  - For Kucoin 
         1. `General` permission API key for your miner account 
         2. `General` and `Trade` permission API key for your bot
- Create a new instance of hummingbot `connect` your API keys to your bot then `create` new strategy

If the following doesn't work can you please send me a screenshot of the following and i'll create a ticket:
- Screenshot of your whole hummingbot terminal after running the `config` command
- Screenshot of your API key permission (blur out your API key)
- Screenshot of your Order Tracking Tab in the miner app
- Screenshot of your Rewards Tab in the miner app

Thank you!

**Comment by shan8111** [comment]
Thanks for the answer, but everything works for me only separately (screenshot 1.2), two exchanges do not work on one account.
![1](https://user-images.githubusercontent.com/82288752/114294245-eb20aa80-9aa5-11eb-8e0d-88272765a348.jpg)
![2](https://user-images.githubusercontent.com/82288752/114294246-ebb94100-9aa5-11eb-8849-f32db709a762.jpg)

But when I connect the API key from the Kucoin exchange to my main Shan account, the service does not receive data from the Kucoin exchange and is not displayed on the tracking tab, there is only data from the Binance exchange. (I understand that it is possible to transfer the Binance API key to the Shuan Account, but I want to stay on the Shan account since it has the VIP status and statistics on it for a longer period may be useful for you)

**Comment by shan8111** [comment]
I connected a new API key from Binance to my new account and everything worked fine, two exchanges scanned
![shuan](https://user-images.githubusercontent.com/82288752/114305331-669f4d80-9ae0-11eb-8f1e-283710fa0bc3.jpg)

**Comment by shan8111** [comment]
> Hi Shan!
> 
> Have you tried the following:
> 
> * Before trying the following disconnect first the API key connected to your miner account
> * Generate two separate new API keys:
>   
>   * For Binance
>     1. `Enable Reading` permission API key for your miner account
>     2. `Enable Reading` and `Enable Spot & Margin Trading` permission API key for your bot
>   * For Kucoin
>     1. `General` permission API key for your miner account
>     2. `General` and `Trade` permission API key for your bot
> * Create a new instance of hummingbot `connect` your API keys to your bot then `create` new strategy
> 
> If the following doesn't work can you please send me a screenshot of the following and i'll create a ticket:
> 
> * Screenshot of your whole hummingbot terminal after running the `config` command
> * Screenshot of your API key permission (blur out your API key)
> * Screenshot of your Order Tracking Tab in the miner app
> * Screenshot of your Rewards Tab in the miner app
> 
> Thank you!

Thanks, figured it out
