### ISSUE TITLE
Missing WOXEN-USDT pair on Uniswap

### ISSUE THREAD

**Issue by lexahb** [CoinAlpha/hummingbot#3208]
**Describe the bug**
A user contacted us regarding the trading pair WOXEN-USDT on Uniswap that's not available when running amm-arb. 

**Steps To Reproduce**
1. Set up amm-arb strategy and gateway.
2. Selected connector: uniswap
3. When selecting market, WOXEN-USDT is not available.

**Screenshots**
![woxen](https://user-images.githubusercontent.com/81738433/114660151-680e8700-9d27-11eb-9fd6-6db46768019b.JPG)

**Release version**
v0.38

**Comment by RC-13** [comment]
Adding notes for reference:
Currently, the `ETHEREUM_TOKEN_LIST_URL` we are using doesn't list this market pair, I've looked for other available token lists (https://tokenlists.org/) however didn't find one that lists the token. Also, I think OXEN is currently listed on v1 and we are using v2 for UNISWAP
