### ISSUE TITLE
Avellaneda Market Making Always Using max_spread value

### ISSUE THREAD

**Issue by rogueops** [CoinAlpha/hummingbot#3209]
I have been running the new strat since it came out and not sure if I set it up correctly, my current issue is when it creates an order it always uses the max, it never seems to go down toward the min_spread or change from using the max when creating orders. I changed the ticks to buffer from 60 all the way to the max 600 to see if that would change the volatility, to confirm it was always using the max_spread I changed it a few times and when it starts it uses the max and never seems to update, I gave it at least 24 hours to see if a change made would make a difference, the coin I aimed it at has been pretty steady tick wise and not getting even close to the max_spread value so no orders have been filled since switching to the new strat. What am I doing wrong?

**Comment by rapcmia** [comment]
Hi @rogueops as far as testing the bot, it should be starting around the max spread and then adjust (spreads and inventory split) until it's near the closing time. May you please share a screenshot of your config and attach your logfile if the bot so we can have a look? thank you

**Comment by rogueops** [comment]
I am using the basic settings and just tweaking what it asked for and only
started adjusting volatility_buffer_size to see if that would do anything,
see attached config, let me know if it did not go through

**Comment by keithbaum** [comment]
Hi @rogueops, so I guess you are using the default closing_time = 0.041666 setting. That's equivalent to 1 hour of trading cycle. You should allow at least 30 minutes and you will see how spread goes from max possible to a smaller number. If you want to see faster change in the cycle, just select a smaller closing_time, like for example 10 minutes (closing_time = 0.007)

**Comment by rogueops** [comment]
It has been quiet at work so I have been watching for most of the day
and it seems to just stay at the max, i will stop and start it at the
beginning of an hour my time and check it toward the end of the hour
to see if it has shrunk, i chose the min due to the flux of the coins
price so once it hits that min it should fill an order, it has yet to
fill an order, i am testing it so not worried, i will post after some
testing, thanks for taking a look

**Comment by rogueops** [comment]
after watching for over an hour after stopping and starting the bot it
never got to the min spread set, it used the max set for every order

maybe the 5min order refresh is the issue? I watched the bot creating
orders just before the end of the hour and after and it seems to stay
the same

should I lower the order refresh and change the closing time or one or
the other first? If one or the other, which should I try first?

**Comment by rogueops** [comment]
checked orders at 40min past the hour and with an order refresh of 60
saw something new, 2 open orders instead of just one, price shows 2.7%
above the coin price

now at the top of the hour, still showing 2 open orders, the orders
listed are still 2.7% above the coin price and have yet to see one hit
the min which is 0.6%

since I have had the coin screen open for the past 30min i can see all
the past orders, they are all close to the same with a difference of
about 0.001 - 0.002

the coin price at the time of this email is 0.653863 so the min order
that should be happening would be 0.657786 and the current orders
showing are 0.671517

**Comment by rapcmia** [comment]
Hi @rogueops I was checking my test bots as well and tried to play around with the config, maybe you can try to change the `inventory_risk_aversion` parameter. If the value is closer to `1` the bot will be aggressively focusing on the inventory split. If the value is far from `1` or closer to `0` then the bot will tend to generate more profitability but also increases the chance of inventory risk. The current order refresh time is at `60` with closing time at `0.0146666`

**Comment by rogueops** [comment]
I set my risk from .5 ( in the middle to start ) and dropped it to 0.25
currently, what should I set it to? Also I left the closing time as is
until i heard back so should I switch to 10min ( 0.0146666 )? It is still
the default.

**Comment by rogueops** [comment]
switched closing time to 0.0146666, left inv risk at 0.25

**Comment by rogueops** [comment]
Dropped to 0.1 risk and its been a couple of hours since stopping and
restarting with the new risk and have not gotten an alert of an order
filled. I have TG connected to each bot so I know when too many orders
happen and can stop it so I can get a chance to connect to the server and
adjust.

**Comment by rapcmia** [comment]
Hi @rogueops you can also test to set inventory_risk_aversion to `0.9` which is closest to 1 so the bot will aggressively create orders according to your current inventory split and spreads will be adjusted as well. The `0.01466666` is the default value for the `closing_time` parameter which is around 1hr.  If you want the other way around, I guess changing the `max_spread` closer to the mid_price might help add the chance orders be filled.

**Comment by rogueops** [comment]
current running settings

inventory_risk_aversion 0.1
closing 0.0146666
min 0.6
max 3

all else is the same as the config posted above

**Comment by rapcmia** [comment]
Hi @rogueops I think I understand now, the spreads of my bot are still around the set max_spreads when I tested this again. Please lend me more time to experiment and see how it goes on my testbots.

**Comment by rogueops** [comment]
of course and yes that is what is happening to me at least, with the
settings posted above and the rest of the settings in the config, with a
min of 0.6 and a max of 3, the lowest i have seen it is 2.5, i chose 0.6 as
even with an order refresh of 60 the price flux would hit that generated
min order and fill an order once it got to the min, once i noticed the
strategy not hitting the min i adjusted to a min that would create an order
that would get filled so I would know it is working and then tweak as needed

**Comment by rogueops** [comment]
I am going to switch over to the pure mm strategy while you test and leave
the Avellaneda Market Making config with the settings mentioned

**Comment by keithbaum** [comment]
> current running settings inventory_risk_aversion 0.1 closing 0.0146666 min 0.6 max 3 all else is the same as the config posted above
> […](#)

inventory_risk_aversion = 0.1 is almost the same as using symmetrical spreads, where difference could be very small, though seeing almost no change from start to end of the cycle, you should try highest possible numbers to see the spreads skewness changing through trading cycle.

**Comment by rogueops** [comment]
I started at 0.5, then as instructed went down, do you want me to try going
up?

**Comment by keithbaum** [comment]
> I started at 0.5, then as instructed went down, do you want me to try going up?
> […](#)

My point is to show that spreads are moving from the initial max_spread point at the beginning of the trading cycle.

**Comment by nftmatters** [comment]
this should help you https://github.com/CoinAlpha/hummingbot/pull/3218

**Comment by keithbaum** [comment]
You can check our latest blogpost in the subject here https://hummingbot.io/blog/2021-04-avellaneda-tech-deepdown/

If you want to see different spreads through time from start to end of the cycle you should choose a high IRA parameter (i.e. 0.99999).
The swing from max to smallest spread will take the closing_time amount of days (i.e. 0.0007 ~ 10 minutes).

Provided the max_spread and the min_spread you selected are far enough you will be able to see the change as time passes.

**Comment by rogueops** [comment]
just started a new bot ( well restarted one i stopped for a while ) so I
will create this strat and use the min and max I want and set closing to
0.0007 and report back
