### ISSUE TITLE
Failed Test PR #315 - Unhandled error in background task using Injective

### ISSUE THREAD

**Issue by rxlxrxsx** [CoinAlpha/hummingbot#321]
**Describe the bug**
There are instances that this error appears while running a bot using Injective. Despite the error it doesn't have any impact on the bot's performance.

<img width="1422" alt="Screen Shot 2023-03-13 at 11 10 01 AM" src="https://user-images.githubusercontent.com/64377055/224802002-abd174b9-2c14-42fa-8637-e06b606fd8fe.png">

```python
2023-03-13 11:10:19,101 - 12105 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: No update found for order SIJUT5f6cb2ef2b806d6e3f2509794b922eaf289e249424ddd
Traceback (most recent call last):
  File "/Users/reiniersalazar/hbot-ca-dexalot/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/Users/reiniersalazar/hbot-ca-dexalot/hummingbot/connector/gateway/clob_spot/data_sources/injective/injective_api_data_source.py", line 497, in get_order_status_update
    raise IOError(f"No update found for order {in_flight_order.client_order_id}")
OSError: No update found for order SIJUT5f6cb2ef2b806d6e3f2509794b922eaf289e249424ddd
```

## Steps To Reproduce
1. Clone and install branch
2. Setup and run gateway using the feature PR for Dexalot
3. Connect Injective wallet
4. Create and run a pure MM strategy using Injective

## Test Result Comparison
I tried replicating this on the foundation repository however I encountered an [issue](https://github.com/hummingbot/hummingbot/issues/6143) which further blocks testing.

## Attachments
Logs and config: 
[inective_315.zip](https://github.com/CoinAlpha/hummingbot/files/10960771/inective_315.zip)

**Comment by petioptrv** [comment]
With these latest CLOB connectors, due to the fact that adding an order to the blockchain takes time, it's very possible that we observe these "order update not found" errors. The key is that the order updates should eventually come in, and that there are no orphan orders during or at the end of the run.

**Comment by rxlxrxsx** [comment]
Tested on commit [0f46fb7](https://github.com/CoinAlpha/hummingbot/pull/315/commits/0f46fb7af6efa7577716c87042542291e9232d8a) and while we still get the error we haven't encountered any orphan orders during or at the end of the run.
