### ISSUE TITLE
KuCoin - Manual orders are cancelled when stopping the bot

### ISSUE THREAD

**Issue by dendenski** [CoinAlpha/hummingbot#3214]
**Describe the bug**
Manual orders are cancelled when stopping the bot

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
1. Start liquidity mining or pure market making strategy bot.
2. Place manual buy order on KuCoin.
3. Stop the bot.
4. Check KuCoin account, manual orders are cancelled.

Other scenario:
1. Start pure market making strategy bot#1.
2. Start pure market making strategy bot#2.
3. Check KuCoin account, placed orders from bot#1 is cancelled.

**Screenshots**
![image](https://user-images.githubusercontent.com/65387749/114852823-b8fca900-9e15-11eb-99bb-31c08215d394.png)
![image](https://user-images.githubusercontent.com/65387749/114852906-d03b9680-9e15-11eb-96dd-498f20d2a6d9.png)
![image](https://user-images.githubusercontent.com/65387749/114853066-feb97180-9e15-11eb-9d1c-b54cff15d569.png)

**Release version**
v0.38.0

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

[logs_conf_pure_mm_2.log](https://github.com/CoinAlpha/hummingbot/files/6317052/logs_conf_pure_mm_2.log)
[conf_pure_mm_2.zip](https://github.com/CoinAlpha/hummingbot/files/6317054/conf_pure_mm_2.zip)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**
dennis b. | support

**Comment by PtrckM** [comment]
Similar case with https://github.com/CoinAlpha/hummingbot/issues/2896 checking with other exchanges.

**Comment by RC-13** [comment]
Other connectors that have this issue: Ascendex and Bitfinex
