### ISSUE TITLE
Failed Test PR #315 - Chain session cookie loaded from disk

### ISSUE THREAD

**Issue by rxlxrxsx** [CoinAlpha/hummingbot#322]
**Describe the bug**
Creating a ticket for confirmation. Getting this message both on the client and on the background after running `bin/hummingbot.py`.

<img width="1423" alt="Screen Shot 2023-03-13 at 10 00 47 AM" src="https://user-images.githubusercontent.com/64377055/224802743-567dadd8-8687-4f31-a19b-d4ddf2f84af8.png">

<img width="1268" alt="Screen Shot 2023-03-13 at 10 05 12 AM" src="https://user-images.githubusercontent.com/64377055/224802753-e19da18f-5854-4520-b430-6c9140971a53.png">

```python
2023-03-13 10:00:26,074 - 10699 - root - INFO - chain session cookie loaded from disk:grpc-cookie=a7ec36196ec9391f978b1fe75d09aca4; Expires=Sun, 12-Mar-23 19:26:58 GMT; Max-Age=172800; Path=/; Secure; HttpOnly
```

## Steps To Reproduce
1. Clone and install branch
2. Setup and run gateway using the feature PR for Dexalot
3. Run the client

## Test Result Comparison
Not hitting this issue on development.

## Attachments
N/A

**Comment by petioptrv** [comment]
This is issued by the injective Python SDK. For now, it simply and extra line in the logging pane, so I believe we can ignore it.
