### ISSUE TITLE
Easy question about price_type

### ISSUE THREAD

**Issue by rogueops** [CoinAlpha/hummingbot#3222]
I have been testing mid_price vs last_price and wonder which is better, i would say more accurate, but i think that's relative. Does the exchange spread cause issues? Not bot min and max spread, my exchange shows a spread of the difference between the bid and ask orders and sometimes it gets up fairly high which makes me thing the calc for mid_price from best bid and ask sometimes, not always, be a bit off a due to the difference(spread) in the bid and ask orders on the exchange. Just trying to learn more about my bot so I can make it awesome.

**Comment by sidmontanez** [comment]
Hi, @rogueops 
   
   I wouldn't be able to give out a concrete answer to which is better though I would suggest to hop in to our [Discord](https://discord.com/invite/2MN3UWg) to get some inputs from our experienced traders to weight down the pros & cons of the price_type from our #trade-chat channel.

**Comment by rogueops** [comment]
fair enough
