### ISSUE TITLE
Stop command improvements

### ISSUE THREAD

**Issue by vxnuke** [CoinAlpha/hummingbot#3225]
**Feature Suggestion**

create a command "stop" and "stop all" where "stop" cancels orders it knows and ignores if order fails to cancel as it would mean its complete maybe. The other command "stop all" would cancel all orders on exchange. I have other bots running when i type stop it cancels everything. 

**Impact**

Better user experience

**Comment by zappra** [comment]
When you enter the stop command it should only cancel the orders placed by that bot instance. If other orders are being cancelled, that sounds like a possible bug or setup issue

**Comment by vxnuke** [comment]
Ok cheers ill look into the code and see what i can find.
