### ISSUE TITLE
History report with Paper Trading enabled shows start and current values reversed under assets

### ISSUE THREAD

**Issue by cpelon** [CoinAlpha/hummingbot#3228]
**Describe the bug**
With paper trading on, when I run a history report. The assets table has the start and current values reversed.

**Screenshots**
![History report](https://user-images.githubusercontent.com/1221883/115476637-470ad200-a210-11eb-8998-df1f16d66974.PNG)

**Release version**
0.38.0

**Comment by rxlxrxsx** [comment]
Hi @cpelon, we have an existing ticket for this issue which you can check [here](https://github.com/CoinAlpha/hummingbot/issues/3094). Please refer to that ticket for updates moving forward. Thanks.
