### ISSUE TITLE
[Question] how to make sure the makers always has better price than the takers?

### ISSUE THREAD

**Issue by cowkeys** [CoinAlpha/hummingbot#323]

**Comment by cowkeys** [comment]
if place a sell limit order from DDEX. once it finished, how to make sure the taker buy price is lower at same time

**Comment by mifeng** [comment]
When you are the maker, you place limit orders on the order book. For trades to occur, you depend upon takers to go onto the exchange and take your orders. You set your limit orders at a "spread" from the market mid price. 

If your buy order spread is 1% from mid and your sell order spread is also 1% from mid, it means that your buy order's price is 2% lower than your sell order's price. The expectation is that over time, you will tend to buy at lower prices and sell at higher prices.
