### ISSUE TITLE
[Info request] Integrating Hummingbot with Telegram on Docker in AWS

### ISSUE THREAD

**Issue by florinteodorescu** [CoinAlpha/hummingbot#3231]
Hi,

I'm trying to integrate a hummingbot instance that is located in AWS (and installed as a docker container) with Telegram.

What I've tried so far:
 - I've followed the steps from here: "https://docs.hummingbot.io/features/telegram/" . I've modiefied telegram_enabled, telegram_token and telegram_chatID and verified them multiple times to make sure they are correct. I`ve also started the hummingbot with a pmm config, but the commands I execute from the telegram bot have no effect (config, balance, etc) .
 - I've modified the Security Group of the AWS VM to allow all traffic inboud  and outboud
 - I've tried modifying the create.sh script and adding "-P --expose 80 --expose 443" to the "docker run" command to try to forward the HTTP API request from the container to the external networks

Do you have any guidance on how to achieve this?

Thank you!

**Comment by dendenski** [comment]
@florinteodorescu, It works fine on my end using AWS cloud. Have you tested your telegram token and chatID if it is working using a local installation? We have 24/7 online support at discord, feel free to join and chat with one of our support to help you with your issue.
Here is our discord invitation link. https://discord.com/invite/2MN3UWg

**Comment by zappra** [comment]
@florinteodorescu how are you configuring the telegram token? you need to copy it into the global config by hand, because of this bug #2391

**Comment by florinteodorescu** [comment]
Thank you for your answers!

Indeed, after copying it by hand in the global config it worked :) 

The strange thing is that I've tried the same steps on a local setup (docker) and it worked with copy paste in the terminal window (without manually configuring the global config file), this left me thinking that the issue was related to the AWS cloud. Sure enough, manually changing the global config worked. Still not sure why it works locally but not in AWS.

**Comment by cj4c0b1** [comment]
> @florinteodorescu, It works fine on my end using AWS cloud. Have you tested your telegram token and chatID if it is working using a local installation? We have 24/7 online support at discord, feel free to join and chat with one of our support to help you with your issue. Here is our discord invitation link. https://discord.com/invite/2MN3UWg

SCAM!!!

this LINK is a SCAM, dont click or follow, its a false invite link to a false hummingbot discord.
