### ISSUE TITLE
Binance_us parsing error upon choosing token pair BNB-USD

### ISSUE THREAD

**Issue by glenntomas** [CoinAlpha/hummingbot#3232]
**Describe the bug**
When choosing BNB-USD token pair in binance_us it shows BN-BUSD

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):
1. Create pure market making
2. Choose binance_us as spot connector
3. Choose BNB-USD as token pair and it shows BN-BUSD

**Screenshots**
![image](https://user-images.githubusercontent.com/73885708/115656001-f5c12680-a366-11eb-8944-b7b3508fc8b7.png)

**Release version**
v0.38.1

**Optional: your discord username:**
dvdaz#0500

**Comment by PtrckM** [comment]
Similar https://github.com/CoinAlpha/hummingbot/issues/2790

**Comment by dennisocana** [comment]
Fixed in version 0.39 release
