### ISSUE TITLE
Unit tests refactor and cleanup

### ISSUE THREAD

**Issue by phbrgnomo** [CoinAlpha/hummingbot#3234]
Original issue #3233 created by @Nullably 

**Why**
We haven't been keeping up with unit tests lately, new strategies and connectors are missing the tests. The current test files structure makes it difficult to find unit tests.
Unit testing is a good coding practice which we should always enforce where possible. This makes the code base cleaner and easier for external developers to follow and understand.

**Where should we enforce unit tests**
* All strategies
* Calculation modules e.g. performance_analysis
* Tools and stand alone services, e.g. rate oracle

**Where unit tests are not required**
* Configurations (both strategy and global)
* UI and commands
* Connectors (tests will be performed by Automated Connector Tester) 

**Missing unit tests**
- hummingbot/client/performance.py
- hummingbot/core/utils/trading_pair_fetcher.py
- hummingbot/core/utils/asyncio_throttle.py
- hummingbot/core/utils/async_retry.py
- hummingbot/core/utils/estimate_fee.py
- hummingbot/core/utils/ethereum.py
- hummingbot/core/utils/ssl_cert.py
- hummingbot/core/utils/tracking_nonce.py
- hummingbot/core/utils/trading_pair_fetcher.py
- hummingbot/core/utils/wallet_setup.py
- hummingbot/core/clock.pyx
- hummingbot/core/network_base.py
- hummingbot/core/network_iterator.pyx
- hummingbot/core/pubsub.pyx
- hummingbot/core/time_iterator.pyx

- All `dev` strategies
- hummingbot/strategy/avellaneda_market_making/avellaneda_market_making.pyx
- hummingbot/strategy/liquidity_mining/liquidity_mining.py
- hummingbot/strategy/perpetual_market_making/perpetual_market_making.pyx
- hummingbot/strategy/spot_perpetual_arbitrage/spot_perpetual_arbitrage.py
- hummingbot/strategy/market_trading_pair_tuple.py
- hummingbot/strategy/order_tracker.pyx
- hummingbot/strategy/strategy_base.pyx
- hummingbot/strategy/strategy_py_base.pyx

**Proposed Tasks**
- Restructure the current test file location to match Hummingbot file structure
- Identify failed unit tests and fix them
- Create unit tests for missing ones above

**Notes**
- All unit tests (except those for connectors) are required to be run and passed on every PR (by GitHub action)
- As for above, all unit tests need to finish within a few minutes (max), thus each unit test should take no longer than a few seconds to perform. 
- Make sure there is no blocking calls, if you need to wait for certain condition to be met, make sure to set time out.
- Mocked objects and data can be used as needed.
- For Automated Connector Tester see https://www.notion.so/hummingbot/Automated-testing-tools-for-QA-49b1bf33ea374083a738243d0bc0ea09

**Comment by dennisocana** [comment]
Adding unit tests will be a continuous effort. We have completed adding test cases to components that we think are important and needs to be prioritized.
