### ISSUE TITLE
Create Uniswap V3 Strategy

### ISSUE THREAD

**Issue by phbrgnomo** [CoinAlpha/hummingbot#3242]

**Comment by Nullably** [comment]
Is the name of the strategy gonna be Uniswap V3, I think that doesn't tell much on what it's gonna do. How about Uniswap v3 Market Making?

**Comment by vic-en** [comment]
> Is the name of the strategy gonna be Uniswap V3, I think that doesn't tell much on what it's gonna do. How about Uniswap v3 Market Making?

I agree. That is descriptive.

**Comment by phbrgnomo** [comment]
This issue have broken down in 3 new stories: #3283, #3284, #3285
