### ISSUE TITLE
Failed Test PR #315 - Failed to cancel orders using Dexalot

### ISSUE THREAD

**Issue by mrhzysbl** [CoinAlpha/hummingbot#325]
## Summary and Screenshots
While running a long term bot, we noticed that there was an order that failed to cancel. It's been active for more than 6 hours.

<img width="1418" alt="Screen Shot 2023-03-16 at 11 03 24 AM" src="https://user-images.githubusercontent.com/120451804/225500950-2e733899-1d5b-42c9-9376-8e30963f9cde.png">

## Steps To Reproduce
1. Clone and install branch
2. Setup and run gateway using the feature PR for Dexalot
3. Connect Dexalot wallet
4. Create and run a pure MM strategy using Dexalot
5. Run the bot in longer hours

## Test Result Comparison
n/a

## Attachments
Logs and config: 
[Dexalot.zip](https://github.com/CoinAlpha/hummingbot/files/10986256/Dexalot.zip)

**Comment by petioptrv** [comment]
This is diagnosed due to insufficient funds to cover the transaction costs.
