### ISSUE TITLE
Developers Documentation Updates

### ISSUE THREAD

**Issue by phbrgnomo** [CoinAlpha/hummingbot#3262]
##Description##

Documentation improvement for the launch of Hummingbot 1.0

##Details##

Documentation is still lacking information and must be improved.

The tasks related to Documentation improvement must cover the following topics:

- Improve Development Documentation
- Improve contribution guidelines
- Create strategies documentation explaining the trading logic and how the strategy works on code level
- Documentation detailing the functions of each hummingbot module (i.e. each class/object on `events.py`)
- Improve developers tutorial
- Gateway user and developer documentation

**Comment by dennisocana** [comment]
Similar to and superseded by https://github.com/CoinAlpha/hummingbot/issues/4162 where we narrowed down the main objective of what needs to be done.
