### ISSUE TITLE
Unit tests for Perpetual market making strategy

### ISSUE THREAD

**Issue by Nullably** [CoinAlpha/hummingbot#3270]

**Comment by dennisocana** [comment]
Moving to backlog for further discussion, similar to https://github.com/CoinAlpha/hummingbot/issues/3271

**Comment by dennisocana** [comment]
During the development of Bybit Perpetual connector, there were some issues found with Perpetual Market Making strategy where it's not behaving correctly. We will investigate first to assess whether it will be a quick fix or a rework of the strategy before adding the unit tests.
