### ISSUE TITLE
Unit tests for Spot-Perpetual arbitrage strategy

### ISSUE THREAD

**Issue by Nullably** [CoinAlpha/hummingbot#3271]
Task for adding unit tests to Spot-Perpetual Arbitrage once the rework of the strategy's logic is complete.

Prerequisite : #3791

**Comment by dennisocana** [comment]
Moving to backlog for further discussion. @vic-en please add your comments in this story.

**Comment by Nullably** [comment]
As I listed bugs and code improvements on the #3679 tickets, I feel those should be addressed first before continuing with this ticket, or they could be done at the same time.

**Comment by phbrgnomo** [comment]
Blocked by strategy rework mentioned on #3679.

**Comment by dennisocana** [comment]
Adding the unit tests is part of the strategy rework story. Closing this issue.
