### ISSUE TITLE
PMM Strategy - Bot stopped tracking orders on binance using multiple order levels

### ISSUE THREAD

**Issue by dendenski** [CoinAlpha/hummingbot#3275]
**Describe the bug**
Bot stopped tracking orders in status on binance using multiple order levels.
When you stop the bot, you have to cancel manually the untracked orders. 
User Gamble#3894 is also experiencing this issue.

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: 
![image](https://user-images.githubusercontent.com/65387749/115897901-898e1200-a48f-11eb-8191-aa894b87f00c.png)

2. Start the bot using this command:
start
status --live
3. Wait until other orders disappear on the status
![image](https://user-images.githubusercontent.com/65387749/115898264-f0abc680-a48f-11eb-9914-b432817c99c6.png)
4. The disappeared orders are not canceled on binance.
![image](https://user-images.githubusercontent.com/65387749/115898390-15a03980-a490-11eb-9fed-b6e5e0b6e11e.png)

...

**Screenshots**
// If applicable, add screenshots to help explain your problem.

**Release version**
0.38.1

**Attachments**
[logs_conf_pure_mm_4.log](https://github.com/CoinAlpha/hummingbot/files/6366633/logs_conf_pure_mm_4.log)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**
dennis b. | support

**Comment by rapcmia** [comment]
I tried to run the same market, price source to `last_own_trade_price` and seems to be working ok.

Steps taken:
- Create PMM strategy with multiple order levels, same market CFX-USDT
- Start bot and run `status --live`, crosscheck binance exchange
![0OxjtFCq4L](https://user-images.githubusercontent.com/73840223/115939803-e6aab780-a4d1-11eb-96ed-ce64e65bd75a.gif)

Attached config and log file:
![image](https://user-images.githubusercontent.com/73840223/115939843-09d56700-a4d2-11eb-9390-a03b2e387e10.png)

[logs_pmm-cfx.log](https://github.com/CoinAlpha/hummingbot/files/6368617/logs_pmm-cfx.log)


Release version: v0.38.1

**Comment by dendenski** [comment]
seems to be also working ok on my end after the Binance maintenance. Closing this PR now.
