### ISSUE TITLE
[BUG]Hummingbot image is error

### ISSUE THREAD

**Issue by beyoar** [CoinAlpha/hummingbot#328]
<img width="948" alt="image" src="https://user-images.githubusercontent.com/47019932/58676809-32a75d00-838c-11e9-81a3-2ad3102f78a5.png">

Docker 
Latest image

**Comment by mifeng** [comment]
@beyoar Are you still seeing this error with the latest `0.8.0` release?

If so, please add more info that would help us reproduce this... environment info, etc. Thanks!

**Comment by chowryan** [comment]
closing old bug report. this issue should be fixed in latest build; please reopen if it's still an issue.
