### ISSUE TITLE
Avellaneda Strategy: Changing Max Order Age has no effect, default still used.

### ISSUE THREAD

**Issue by mss7082** [CoinAlpha/hummingbot#3280]
**Describe the bug**

Changing the max_order_age in the Avellaneda Strategy has no effect, even after restarting the bot installed via docker. Exiting the bot which kills the container  and restarting also has no effect whatsoever.

**Steps To Reproduce**

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters:

Strategy Configurations:
Key                     Value
                         strategy  avellaneda_market_making
                         exchange                    kucoin
                           market                  DOT-USDT
                     order_amount                    0.1686
       order_optimization_enabled                      True
       parameters_based_on_spread                      True
                       min_spread                       4.7
                       max_spread                       5.7
         vol_to_spread_multiplier                       1.5
          inventory_risk_aversion                       0.6
       order_book_depth_factor(κ)                      None
                   risk_factor(γ)                      None
     order_amount_shape_factor(η)                      None
                     closing_time                       7.0
               order_refresh_time                     86400
                    max_order_age                     1800
      order_refresh_tolerance_pct                       1.0
               filled_order_delay                        60
        inventory_target_base_pct                      50.0
            add_transaction_costs                     False
           volatility_buffer_size                       300

2. Start the bot using this command:
    start
3. Once the bot creates the limit order after 1800 secs, the orders are refreshed.
4. config max_order_age 86460
5. stop the bot
6. start the bot
7. After 1800 secs the order still refreshes.
...

**Screenshots**

![image](https://user-images.githubusercontent.com/6820077/115973240-5f018f00-a54b-11eb-8593-f21abc4feeff.png)

![image](https://user-images.githubusercontent.com/6820077/115973246-69bc2400-a54b-11eb-8bff-78304ab4e229.png)

![image](https://user-images.githubusercontent.com/6820077/115973252-6fb20500-a54b-11eb-9813-eef4f8d98edc.png)

**Release version**
0.38.1

**Attachments**

[logs_conf_avellaneda_market_making_dot-usdt_1.log](https://github.com/CoinAlpha/hummingbot/files/6370720/logs_conf_avellaneda_market_making_dot-usdt_1.log)
[conf_avellaneda_market_making_dot-usdt_1.yml.log](https://github.com/CoinAlpha/hummingbot/files/6370722/conf_avellaneda_market_making_dot-usdt_1.yml.log)

**Comment by dendenski** [comment]
To confirm the issue, I set my `max_order_age` to 10 and `order_refresh_time` to 30, orders always refreshes base on `order_refresh_time`, the value of `max_order_age` does not take effect.
![image](https://user-images.githubusercontent.com/65387749/115973613-fb965200-a588-11eb-938c-a97a7931f9a3.png)
The order age is greater than the set `max_order_age`.
![image](https://user-images.githubusercontent.com/65387749/115973702-b32b6400-a589-11eb-98db-2f7cde766783.png)

**Comment by keithbaum** [comment]
Issue was addressed by PR https://github.com/CoinAlpha/hummingbot/pull/3463 already merged.
Issue can be closed

**Comment by RC-13** [comment]
fixed on v0.41.0
