### ISSUE TITLE
Bitfinex - OSError failing to submit orders

### ISSUE THREAD

**Issue by rxlxrxsx** [CoinAlpha/hummingbot#3281]
**Describe the bug**
Bot fails to submit orders and goes on a `OSError: Couldn't place order` loop. Upon further investigation, it seems that it's triggered when the bot tries to cancel the order but initially got filled in the process. Creating a github ticket for tracking, will report again once replicated.

**Steps To Reproduce**
1. Run a pure_mm bot on Bitfinex
2. Wait for an order to get filled, for this instance, the behavior doesn't always happen upon testing and was only able to reproduce when the order wasn't cancelled immediately and initially got filled after a few seconds. The expected behavior was when the `Cancelling the limit order` order shows on the log, it'll cancel the order on the next tick. Based on the screenshot, the order was not immediately cancelled on time and during those period it got filled (see gap on timestamp `2021-04-22 18:20:39,000`). On the next cycle, the issue started.

**Screenshots**
![bitfinex](https://user-images.githubusercontent.com/64377055/116026933-4053e300-a686-11eb-89f0-882db8e78644.png)

<img width="1424" alt="Screen Shot 2021-04-26 at 10 01 39 AM" src="https://user-images.githubusercontent.com/64377055/116027097-8f017d00-a686-11eb-99ed-1d74066eb097.png">

**Release version**
development-0.39.0

**Attachments**
[bitfinex.zip](https://github.com/CoinAlpha/hummingbot/files/6374392/bitfinex.zip)

**Comment by RC-13** [comment]
Closing ticket, issue haven't seen for a month now. Will re-open the ticket if the issue will re-occur in the future.
