### ISSUE TITLE
[BUG]]Failed to submit buy(sell) order 

### ISSUE THREAD

**Issue by Calorite** [CoinAlpha/hummingbot#329]
**Describe the bug**
Failed to submit buy(sell) order, and suggest me to check Ethereum wallet and network connection.

**Steps To Reproduce**

Here are the steps to reproduce the issue :
1. Set up my configuration file with these parameters: pure market making  ,  DDEX , etc...
2. Start the bot using this command: start
...

**Screenshots**

![1559306376191](https://user-images.githubusercontent.com/20766182/58706674-b2194880-83ed-11e9-928c-50dfb5ef16f6.jpg)

**Release version**
( 0.7.0 )

**Attachments**

[Calorite_conf_logs.zip](https://github.com/CoinAlpha/hummingbot/files/3241313/Calorite_conf_logs.zip)

**Optional: your discord username:Calorite

**Comment by anish-neervannan** [comment]
Had the same issue submitting orders specifically on DDEX and pure-market making; on any other exchange, pure market-making seems to work. I was able to narrow the issue down to the order size. In my case, DDEX fails to submit orders when the order size is <= 0.06 WETH. However, the actual interface on DDEX lets you submit limit orders for any order of size >= 0.05 ETH.

**Comment by veecos2** [comment]
This only occurs for small order sizes on ddex, There are no issues for larger order sizes. Investigating as to why this occurs.

**Comment by Cobotto** [comment]
This error occurs also with order size 0.1 on ddex.

[hummingbot_logs_2019-06-04-01-42-20.log](https://github.com/CoinAlpha/hummingbot/files/3249920/hummingbot_logs_2019-06-04-01-42-20.log)

**Comment by veecos2** [comment]
@anish-neervannan : This should have been fixed in the latest branch, Could you please rerun your tests and confirm ?.

**Comment by anish-neervannan** [comment]
@veecos2 still seems to occur when trading WETH-DAI and placing order size of 0.05 and 0.06.  (minimum order size for this pair is 0.05)

**Comment by veecos2** [comment]
As we checked, It was working for weth-dai right now, let me know if there were issues with any other pairs.

**Comment by anish-neervannan** [comment]
Just checked for weth-tusd, seems to work as well

**Comment by anish-neervannan** [comment]
Tested for WETH-DAI and WETH-TUSD, closing issue for now
