### ISSUE TITLE
Implement order_levels into avellaneda_mm

### ISSUE THREAD

**Issue by phbrgnomo** [CoinAlpha/hummingbot#3290]
Add `order_levels` configuration similar to current current config on `pure_market_making` strategy.

The logic should be the same.

@keithbaum what are the possible problems we could face with this implementation?

**Comment by keithbaum** [comment]
@phbrgnomo From the implementation standpoint, I see no big issues. It's just a matter of how to assign order amounts through orders. If the total sum of the order levels is greater than the quantity to be executed to achieve the target, then strategy inventory target might be spoiled.
I'm thinking about a way to reduce the probability of execution of the order levels, maybe by sending the higher levels far from level 0, close to the max_spread

**Comment by phbrgnomo** [comment]
Requirement updates after latest meeting with @keithbaum :

- When `parameters_based_on_spread = true`, only the `order_levels` parameter will be available.
  - The order size of the level will be equal to `order_amount`
  - the spread between the orders will be calculated based on the `max_spread`, and the new orders related to order levels will be created between the first order and `max_spread`, distributed exponentially.

- When `parameters_based_on_spread = false`, the behaviour of `order_levels` will be similar to `pure_market_making`

**Comment by phbrgnomo** [comment]
As discussed with @keithbaum , for the "Manual" mode of the strategy, we will implement the `order_override` parameter, instead of all the parameters related to `order_levels`

**Comment by dennisocana** [comment]
Available in version 0.40 release
