### ISSUE TITLE
Avellaneda MM - Implement `hanging_orders` param

### ISSUE THREAD

**Issue by phbrgnomo** [CoinAlpha/hummingbot#3291]
The addition of `hangin_orders` to the strategy will follow different requirements than the one that exists on `pure_market_making`

With the current `hanging_orders` config, the bot tracks all the unfilled orders with an sqlite database.

The following implementation proposal aims to simplify the management of these unfilled orders by creating one single order that have:
- Order size equals to the sum of all unfilled orders
- Price equals to the weighted average of all unfilled orders

Using this logic, the bot will probably use less resources, and the final trading result will be the same as if all hanging orders were filled. 

Requirements:

- When only one side of an order pair is filled, the `order_price` price would be stored on a single variable list, depending on what type is the order (bid or ask)
  - Two lists will be stored: `hanging_bid_order` & `hanging_ask_order`
  - They will contain two values: [`total_hanging_amount`, `hanging_price`]
- When the bot starts, no values will be stored on these lists.
- When an `order_refresh` cycle happens, and only one side was filled, the unfilled order values (size & price) would be added to each corresponding list (`hanging_bid_order` if it was an unfilled buy offer, `hanging_ask_order` if it was an unfilled sell offer)
  - If the list is empty (first unfilled order), a new list will be created with the size and price of the fist unfilled order
  - When the list isn't empty, and another order isn't filled on the `order_refresh` cyle, the values must be changed to [`(previous total hanging amount + new unfilled order amount)` , `((previous total hanging amount * previous hanging price) + (new order amount * new unfilled order price))/(previous total hanging amount + new unfilled order amount)`]
  - The "old" hanging order is canceled, and a new one is created with the new [`hanging order size` , `hanging price`] values is created.
- If the hanging order is filled, the [`total_hanging_amount`, `hanging_price`] values are reseted.

- Make this feature in a modular way.

------------------

(To add on the documentation)

There will be 4 ways to aggregate the hanging orders:

**No aggregation**

With `hanging_order_aggregation = no_aggregation` hanging orders behaviour will work the same as the original `pure_market_making`

**Weighted aggregation**

With aggregation turned on, instead of keeping all hanging orders on the positions they were created, their information will be added to one single order.

The aggregated hanging order will follow the formula:

![Captura de tela 2021-06-16 17.20.44.png](https://images.zenhubusercontent.com/5f64254ca13ff3717cc3a0c5/cc8159fb-408c-4034-b7b0-07bb3e090d03)

There is 3 modes to aggregate the orders information (besides the `no_aggregation mode`, that can be set by changing the `hanging_orders_aggregation_type`. Each mode changes how the factor `w` (a rate adjustment for each past order) is calculated:

`volume_weighted`

`w` = 1 

All past orders will have the same weight on calculating the aggregated hanging order

`volume_time_weighted`

![Captura de tela 2021-06-16 17.27.20.png](https://images.zenhubusercontent.com/5f64254ca13ff3717cc3a0c5/5ac5d581-ae07-490e-a980-8f54d2790a8a)

Orders that were left hanging for a longer time will have a smaller weight on the aggregated order

`volume_distance_weighted` 

![Captura de tela 2021-06-16 17.30.58.png](https://images.zenhubusercontent.com/5f64254ca13ff3717cc3a0c5/62a8c367-33fe-44a9-a044-a71a77e241ba)

Orders that were farther from the current market price will have a smaller weight on the aggregated order

Example calculations: https://docs.google.com/spreadsheets/d/14WFlSZf_YDMxk2nWXQdUXokGGlV16CprLw0R9IrhWKc/edit?usp=sharing

**Comment by krisj** [comment]
one little detail that would of course change is the place in the FIFO queue. The original implementation has the neat side-effect of those orders staying at the front of the queue.

**Comment by keithbaum** [comment]
A potential issue I see is the probability of filling of the orders. In the original scheme orders very close to mid-price had high probability of being filled while further ones very low. The distribution of this probability is not lineal across price.
In this scheme, the logical variable to use as weight is the amount (as you stated in the example), but that modifies heavily the probability of filling of the resulting order. I think that the function used to weight the orders should be something related with distance to mid-price and amount together. Need to give this a better thought though.

**Comment by phbrgnomo** [comment]
The base of the concept is that, the single averaged order, when filled, would provide the same final trading result of all the hanging orders.
But I understand what you mean about probability. If makes a big move in one direction, the single hanging order would start to "move slower" every time there is an unfilled order.

A have a few ideas to handle that, but lets start with the average weighted by order size.

Another idea would be use something similar to a Hull Moving Average (https://school.stockcharts.com/doku.php?id=technical_indicators:hull_moving_average), where the orders that entered the calculation first would have a smaller weight. But I still have to simulate what would be the final trading result.

**Comment by dennisocana** [comment]
Feature available in version 0.41 release
