### ISSUE TITLE
Spot Perpetual Arbitrage - Sell price and buy price label in status is reverse

### ISSUE THREAD

**Issue by dendenski** [CoinAlpha/hummingbot#3296]
**Describe the bug**
Sell price and buy price label in status is reverse.
Sell price = best bid price in orderbook
Buy price = best ask price in orderbook

**Steps To Reproduce**

Here are the steps to reproduce the issue (see attachments in the section below):
1. Create spot-perpetual aribitrage
2. `Start` and run `status --live`
3. Compare the sell/buy price to Binance orderbook.

**Screenshots**
![image](https://user-images.githubusercontent.com/65387749/116333827-c5660600-a806-11eb-97c1-1ee10512b2b0.png)

**Release version**
v0.38.1

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**
dennis b. | support

**Comment by rapcmia** [comment]
Confirmed this is the same as well when I checked with a different market using HNT-USDT

Steps:
1. Create spot arbitrage strategy (Binance and Binance-testnet)
2. Start bot and run `status --live`
3. Cross-check bot and exchange

![o5UhTeg323](https://user-images.githubusercontent.com/73840223/116351536-6fa15600-a826-11eb-8991-77cf759c3bb2.gif)

Release version:
dev-0.39.0

**Comment by dendenski** [comment]
closing this issue. This is expected behavior.
