### ISSUE TITLE
Expose argument details and values for all strategies

### ISSUE THREAD

**Issue by kmcgowan2000** [CoinAlpha/hummingbot#3305]
**Feature Suggestion**
Expose two things for each strategy class:
- `classmethod` `argument_details` that contains details of all arguments (as we cannot introspect cython class `__init__`)
- `property` `argument_values` that contains a dictionary mapping all the argument names to their current values

**Impact**
This lets me use grid search and other optimisation techniques in Hummingbot Pro.

**Additional context**

**Comment by dennisocana** [comment]
Related clubhouse stories
https://app.clubhouse.io/coinalpha/story/14279/add-required-methods-to-single-market-hummingbot-strategies-for-grid-search
https://app.clubhouse.io/coinalpha/story/15065/add-required-methods-to-remaining-hummingbot-strategies-for-grid-search

**Comment by Nullably** [comment]
I had a discussion with @kmcgowan2000 on this, here is summary.
- The PR #3175 is not needed for the alpha release of Hummingbot Pro next week
- We agreed the approach on the PR is not ideal, the better approach is to standardise the strategy construction using configuration map. This will automate many repetitive tasks on initialising a strategy object. I'll create another story for this soon.
- The solution is not urgent but should be prioritise for coming release. Hummingsim will need update to incorporate this change as well. I'll keep @kmcgowan2000 in the loop.

**Comment by Nullably** [comment]
A simple solution to this is to add a function init_params which is called directly after the strategy initialisation. The parameters in init_params are then discoverable through introspect.
