### ISSUE TITLE
Refactor Gateway connector classes

### ISSUE THREAD

**Issue by Nullably** [CoinAlpha/hummingbot#3306]
Refactor existing Gateway connectors, except for PerpetualFinance, to this design

![image.png](https://images.zenhubusercontent.com/5f636ed10127e0d4e0d84d8e/3d3714bd-226b-4ff2-9610-e4b10e1f6992)

Tasks:
  - Create new Gateway connector base class
  - Create new Ethereum connector base class
  - Update existing Gateway connectors to fit in this new design

Note:
  - UniswapV3 might not need to inherit from Unswap connector
  - PerpetualFinance refactor task is on another issue (as it has other dependency)

**Comment by dennisocana** [comment]
Putting this story on hold until we complete the improvement on the Gateway side and for further discussion. Moving to backlog.

**Comment by phbrgnomo** [comment]
@james-hummingbot What are the requirements on the gateway side that needs completion for the team to start working on this story?

**Comment by vic-en** [comment]
I suggest that we allow the root endpoint(i.e /eth/{amm}/ ) of each connector on Gateway v2 return basic info about the chain being used like the name of chain being used and info about the native currency. This will be useful on the client side to do necessary fee calculations and show balance info correctly.

**Comment by vic-en** [comment]
I'll also suggest that all connectors on Gateway v2 have an endpoint to poll and decode logs directly. Rather that having to make 2 calls(i.e. one call to the eth/poll then the other to debug), we can simply leave eth/poll for erc20 related transactions like approval then make endpoint on each connectors to decode the logs from that function directly and return the results once and for all.

**Comment by mifeng** [comment]
Format for the ` going to the same point endpoint should be similar to https://chainid.network/chains.json

**Comment by mifeng** [comment]
Comments from @vic-en :

Yes, I created a gateway_base class. So Balancer and both uniswaps on the client need to inherit and build on top of it with little additions.

So I refactored Balancer to use that new base class and currently testing.

The ticket aims to create a base class then refactor Balancer and both Uniswaps we have.

**Comment by dennisocana** [comment]
Removing the version 0.44 tag since this is something that goes into the gateway-v2 feature branch and will not be shipped to production in the upcoming release.
