### ISSUE TITLE
Define scope for margin trading (design)

### ISSUE THREAD

**Issue by Nullably** [CoinAlpha/hummingbot#3311]
To define what margin trading functionality we are going to support in Hummingbot.
We can use Binance as our starting point.

https://binance-docs.github.io/apidocs/spot/en/#margin-account-trade

## Definition of Done

- [ ] Update this story with all the requirements and tasks needed for implementation: https://github.com/CoinAlpha/hummingbot/issues/3307

**Comment by Nullably** [comment]
@phbrgnomo 
To define what margin trading functionality we are going to support in Hummingbot.
We can use Binance as our starting point.

https://binance-docs.github.io/apidocs/spot/en/#margin-account-trade

**Comment by dennisocana** [comment]
Thanks, marking this task as complete.
