### ISSUE TITLE
ascendex inconsistent balance

### ISSUE THREAD

**Issue by PtrckM** [CoinAlpha/hummingbot#3328]
**Describe the bug**
- Running 2 bots with similar 1 asset will cause inconsistent balance and inconsistent order creation.

**Steps To Reproduce**
1. make sure both bots can create orders on both side.
2. run bot1 with PMM ETH-BTC
3. run bot2 with PMM BTC-USDT

- bot2 will start inconsistently creating orders and showing 0 balance on quote asset

**Screenshots**
- balance
![image](https://user-images.githubusercontent.com/54516858/117435473-7d5e8600-af60-11eb-92df-b9befccdeee2.png)

- bot1
![image](https://user-images.githubusercontent.com/54516858/117435083-06c18880-af60-11eb-92bf-a510ff485492.png)

- bot2
![image](https://user-images.githubusercontent.com/54516858/117435131-15a83b00-af60-11eb-9666-e9238e1cb6cc.png)

- If you run both bots for awhile bot1 will start to experience and throw this error randomly, wherein unable to find the order and after multiple retries it will success.
```
2021-05-07 10:18:00,241 - 24117 - hummingbot.connector.exchange.ascend_ex.ascend_ex_exchange - NETWORK - Unexpected error while fetching account updates.
Traceback (most recent call last):
    raise IOError(f"{url} API call failed, response: {parsed_response}")
OSError: https://ascendex.com/6/api/pro/v1/cash/order/status?orderId=HMBot179465583c6U949683076705095 API call failed, response: {'code': 300006, 'message': 'Unable to find orderId', 'reason': 'INVALID_ORDER_ID'}
```

**Attachments**
[strategy_logs.zip](https://github.com/CoinAlpha/hummingbot/files/6440865/strategy_logs.zip)

**Comment by dennisocana** [comment]
Fixed in version 0.39 release
