### ISSUE TITLE
Kucoin API Key Error Loop when adding API key to hummingbot

### ISSUE THREAD

**Issue by geloadviento** [CoinAlpha/hummingbot#3337]
**Describe the bug**
// Abay#4537 reported that he/she is having a hard time connecting Kucoin API key to hummingbot. There's this error appearing `Error: Error fetching data from https://api.kucoin.com/api/v1/accounts?type=trade . HTTP status is 401` upon trying and testing it on my end, I'm also getting the same error.

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
1. Created a new API key from kucoin and connected it to hummingbot
2. Made sure to input the correct API key, Secret key and Passphrase
3. It would throw out the error regardless if you put the correct keys and passphrase

**Screenshots**
// ![image](https://user-images.githubusercontent.com/83911710/117574755-319f0e80-b111-11eb-84ef-f31f56464f79.png)

**Release version**
// Hummingbot Version 0.38.1

**Attachments**
// N/A

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Comment by dennisocana** [comment]
@geloadviento what version of KuCoin API key are you using?

**Comment by geloadviento** [comment]
@dennisocana Hi Sir, currently I'm using kucoin API v2.
