### ISSUE TITLE
Loopring - Unable to create or import a strategy

### ISSUE THREAD

**Issue by rxlxrxsx** [CoinAlpha/hummingbot#3339]
**Describe the bug**
Unable to create or import a strategy using Loopring. When creating a strategy, bot throws an error upon entering the value on `order_refresh_time` while importing a strategy, it always throws an invalid `order_amount`, even when the value is within the minimum required by the exchange. Affected strategies are pure_market_making, avellaneda_market_making and cross_exchange_market_making.

```
2021-05-10 04:45:28,614 - 15668 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 'LRC-USDT'
Traceback (most recent call last):
  File "/home/ubuntu/loopring/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/ubuntu/loopring/hummingbot/client/command/create_command.py", line 63, in prompt_for_configuration
    await self.prompt_a_config(config)
  File "/home/ubuntu/loopring/hummingbot/client/command/create_command.py", line 106, in prompt_a_config
    prompt = await config.get_prompt()
  File "/home/ubuntu/loopring/hummingbot/client/config/config_var.py", line 44, in get_prompt
    return await self.prompt()
  File "/home/ubuntu/loopring/hummingbot/strategy/pure_market_making/pure_market_making_config_map.py", line 42, in order_amount_prompt
    min_amount = await minimum_order_amount(exchange, trading_pair)
  File "/home/ubuntu/loopring/hummingbot/client/config/config_helpers.py", line 413, in minimum_order_amount
    mid_price = await get_last_price(exchange, trading_pair)
  File "/home/ubuntu/loopring/hummingbot/core/utils/market_price.py", line 29, in get_last_price
    return Decimal(str(last_prices[trading_pair]))
KeyError: 'LRC-USDT'
```

**Steps To Reproduce**
1. Create or import a strategy using Loopring exchange

**Screenshots**
<img width="1424" alt="Screen Shot 2021-05-10 at 1 25 37 PM" src="https://user-images.githubusercontent.com/64377055/117612054-24c4fe00-b197-11eb-9b05-81281e8675a5.png">

<img width="1424" alt="Screen Shot 2021-05-10 at 1 58 07 PM" src="https://user-images.githubusercontent.com/64377055/117614171-889cf600-b19a-11eb-8007-950b95ba1818.png">

<img width="1423" alt="Screen Shot 2021-05-10 at 2 06 10 PM" src="https://user-images.githubusercontent.com/64377055/117614183-8c307d00-b19a-11eb-89b9-4057ae8848f8.png">

<img width="1424" alt="Screen Shot 2021-05-10 at 1 02 41 PM" src="https://user-images.githubusercontent.com/64377055/117612056-27275800-b197-11eb-944f-70d170d659ce.png">

**Release version**
version-0.38.1 (screenshot is on development but I can confirm that this is also happening on master branch)

**Attachments**
[loopring1.zip](https://github.com/CoinAlpha/hummingbot/files/6449895/loopring1.zip)

**Comment by RC-13** [comment]
Loopring started to work again, I was able to start our test bot and will continue to observe.
![image](https://user-images.githubusercontent.com/57189990/118112485-a7f48700-b417-11eb-86b7-90e4bfd0ebef.png)

**Comment by RC-13** [comment]
A similar case is happening right now on the Beaxy test bot, issue was triggered by a kill switch that fails to stop the bot and got stuck in a loop.
![beaxy-killswitch-error](https://user-images.githubusercontent.com/57189990/118429765-00bc6c00-b705-11eb-9c22-0a204e6cbf1c.png)
After restarting the test bot, it now fails to import an existing strategy or create a new one
![beaxy-failed-to-start](https://user-images.githubusercontent.com/57189990/118429806-16ca2c80-b705-11eb-929f-9e97707a9853.png)
[beaxy_logs.zip](https://github.com/CoinAlpha/hummingbot/files/6490954/beaxy_logs.zip)

**Comment by RC-13** [comment]
Beaxy test bot is now back and running again, will continue to monitor in case the issue re-occurs.
![image](https://user-images.githubusercontent.com/57189990/118566514-9cea7f80-b7a6-11eb-8f58-ffe731e4eee9.png)

**Comment by RC-13** [comment]
similar case #3338

**Comment by RC-13** [comment]
The issue hasn't occurred for at least 2 weeks now, closing the ticket and will re-open if needed.
