### ISSUE TITLE
Failed Test PR #330 - Total balance changes

### ISSUE THREAD

**Issue by rxlxrxsx** [CoinAlpha/hummingbot#335]
## Summary and Screenshots
The total balance changes whenever an order is opened, if I'm not mistaken this should not change even if there are orders currently open.

<img width="668" alt="Screen Shot 2023-04-05 at 1 06 45 PM" src="https://user-images.githubusercontent.com/64377055/230205650-7f16e2f7-8078-48a7-930d-5117180fb043.png">

<img width="659" alt="Screen Shot 2023-04-05 at 2 37 19 PM" src="https://user-images.githubusercontent.com/64377055/230205912-cc803ce9-2a1c-42a3-be8d-81a390628972.png">

## Steps To Reproduce
1. Clone and install featured branch
2. Connect to gateway
3. Create a perpetual market making strategy
4. Run status or status --live command and observe the total balance

## Expected Results
Total balances shown should not change unless there are changes/trades performed

## Test Result Comparison
N/A, new connector

## Attachments
N/A

**Comment by petioptrv** [comment]
This issue should be addressed in the latest [commit](https://github.com/CoinAlpha/hummingbot/pull/330/commits/4718e97dd85580e0a78cda111704655826ea6c92)

**Comment by rxlxrxsx** [comment]
Tested on commit [393b09f](https://github.com/CoinAlpha/hummingbot/pull/330/commits/393b09f4d007508ed74ea149c211ad4dc57f4dd3) and confirmed fixed.
