### ISSUE TITLE
[Feature]Ethereum node config optimization

### ISSUE THREAD

**Issue by moraliang** [CoinAlpha/hummingbot#335]
**Feature Suggestion**
// A succinct description of **how you want to achieve the desired behavior**.
// If you have looked at the code and know exactly what code changes are needed then please _consider submitting a pull request_ instead.

1. Hummingbot should not ask users to fill out ethereum node when they only trade on centralized exchanges no matter what strategy they use. 
2. Automatically add "https://" in front of the node url like "mainnet.infura.io/..."

**Impact**
// A succinct description of **why you want the _desired behavior_** specified above.

Remove the hurdles for users who only want to trade on centralized exchanges (especially in harmony's case, only on binanace currently) and new users who do not know how to set up nodes. 

**Additional context**

**Comment by yzhang1994** [comment]
This is done in development branch. Will be ready in the next release.
