### ISSUE TITLE
Fix `dev_4_twap` and `dev_5_vwap` strategy

### ISSUE THREAD

**Issue by CrimsonJacket** [CoinAlpha/hummingbot#3350]
Early investigations shows that these `dev` strategies are not working as intended. 
Before implementing the Unit test cases for them, we should resolve existing issues.

Some issues include:
1. `create` command not working as intended. Outdated strategy config_map resulting in certain params not being prompted.

**Comment by phbrgnomo** [comment]
Started a research doc on notion: https://www.notion.so/hummingbot/VWAP-and-TWAP-requirements-01e22d8c61334beb96140630f8c9baa7

Added some reference links about the strategy, will detail requirements later.
