### ISSUE TITLE
[BUG]Stop loss tracker error

### ISSUE THREAD

**Issue by moraliang** [CoinAlpha/hummingbot#336]
**Describe the bug**
Came across this stop loss tracker error. Seems it doesn't impact the trading though. 

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Config as usual and start the bot. 

My config: 
Exchange and token parameters
maker_market: binance
maker_market_symbol: ONEUSDT

size of each order
order_amount: 5.0

Time in seconds before cancelling and rerunning strategy
If tick size is 60, the bot cancels active orders and reruns after a minute
cancel_order_wait_time: 360.0

bid_place_threshold: 0.02

ask_place_threshold: 0.02

**Screenshots**
// If applicable, add screenshots to help explain your problem.
![Screen Shot 2019-06-03 at 3 51 24 PM](https://user-images.githubusercontent.com/14824365/58839669-87123d00-8617-11e9-9f32-8982a6512168.png)

**Release version**
// Include your bot's version number (Can be found at the bottom left corner of your CLI).
0.7.0 

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 
[hummingbot_logs_2019-06-03-15-31-06.log](https://github.com/CoinAlpha/hummingbot/files/3249761/hummingbot_logs_2019-06-03-15-31-06.log)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by yzhang1994** [comment]
this should be fixed
