### ISSUE TITLE
[BUG][pure_market_marking]Always show error " <USDT> is less than the require to place an ask order

### ISSUE THREAD

**Issue by hongson1981** [CoinAlpha/hummingbot#337]
**Describe the bug**
(USDT) balance of  (0.00708705) is now less than the required to place an ask order of size: (0.0003)

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):

    choose pure MM strategy
    config as usual (the order amount > binance min order size)
    start

Actual result 
Always show error : (USDT) balance of  (0.00708705) is now less than the required to place an ask order of size: (0.0003)

**Screenshots**
// If applicable, add screenshots to help explain your problem.
![Screenshot from 2019-06-04 21-15-26](https://user-images.githubusercontent.com/29745336/58887177-56adca00-870f-11e9-8e57-44c9699ded6b.png)

**Release version**
dev-0.8.0
**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 
[hummingbot_logs_2019-06-04-14-05-50.log](https://github.com/CoinAlpha/hummingbot/files/3252880/hummingbot_logs_2019-06-04-14-05-50.log)

[conf_pure_market_making_strategy_0.txt](https://github.com/CoinAlpha/hummingbot/files/3252894/conf_pure_market_making_strategy_0.txt)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by veecos2** [comment]
The bot is indicating that you do not have enough USDT balance to place the buy order. Kindly refer to the trading rules for minimum order sizes and minimum order value https://www.binance.com/en/support/articles/115000594711-Trading-Rule

**Comment by veecos2** [comment]
We will try to add the feature to clearly represent why the bot is not trading, when the order is below the minimum order value as well.
