### ISSUE TITLE
key error in kucoin connector

### ISSUE THREAD

**Issue by stayhungry7** [CoinAlpha/hummingbot#3371]
**Describe the bug**
// A clear and concise description of what the bug is.
After updating API key and secret for kucoin API v2.
I got an error like following

2021-05-14 11:06:16,535 - 20949 - hummingbot.connector.exchange.kucoin.kucoin_exchange - ERROR - Unexpected error in user stream listener loop.
Traceback (most recent call last):
  File "hummingbot/connector/exchange/kucoin/kucoin_exchange.pyx", line 282, in hummingbot.connector.exchange.kucoin.kucoin_exchange.KucoinExchange._user_stream_event_listener
    client_order_id = execution_data["clientOid"]
KeyError: 'clientOid'

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

1. run hummingbot
2. run "connect kucoin"
3. input API key
4. input API secret
5. then start hummingbot

**Screenshots**
// If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/37467951/118213247-8099ca80-b4a8-11eb-8892-bc5089b05f1e.png)

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by rapcmia** [comment]
Hi @stayhungry7 I tried to setup the same API I use for Kucoin and still connecting ok, just checking if you tried to create a new set of APIs and see if this works for you?

**Comment by restorepro** [comment]
Im getting a error while setting up the kucoin connecter. After i enter the api key, secret key and passphrase and click save- I get a error that says "invalid exchange credentials for kucoin". I then deleted the api connector on kucoin and created a new one and tried that and i get the same error... Uggghhh!

**Comment by rapcmia** [comment]
Hi @restorepro I tried to create a new API for Kucoin and seems to work ok. You can try to use `shift + RMB` to paste it to the bot. Here is a link as well so you can check the [keyboard shortcuts](https://docs.hummingbot.io/operation/client/#keyboard-shortcuts)

![image](https://user-images.githubusercontent.com/73840223/118482675-a2fd4380-b747-11eb-84b2-556708c138ae.png)
