### ISSUE TITLE
Failed Test PR #330 - Trades performed outside the bot are being captured

### ISSUE THREAD

**Issue by rxlxrxsx** [CoinAlpha/hummingbot#339]
## Summary and Screenshots
Trades are being captured by the bot that were performed manually in the exchange. In this scenario I manually closed a position in the web app and after restarting the bot it captured the trade several times.

<img width="1410" alt="Screen Shot 2023-04-06 at 12 35 57 PM" src="https://user-images.githubusercontent.com/64377055/230468989-e8353502-8b24-463b-a1a9-5594f1068914.png">

<img width="691" alt="Screen Shot 2023-04-06 at 12 50 42 PM" src="https://user-images.githubusercontent.com/64377055/230469013-e760206c-7637-49cc-8ce2-97ada3bc6cd3.png">

<img width="970" alt="Screen Shot 2023-04-06 at 12 50 58 PM" src="https://user-images.githubusercontent.com/64377055/230469030-f0037a60-ea00-41ee-93f5-d4f37b615ced.png">

## Steps To Reproduce
1. Clone and install featured branch
2. Connect to gateway
3. Create a perpetual market making strategy using Injective Perpetual
4. Manually execute a trade in the web app, either by opening or closing a position
5. Start the strategy and observe that it will record the trades performed outside the bot

## Test Result Comparison
N/A, new connector

## Attachments
Logs and config: 
[inj_filled.zip](https://github.com/CoinAlpha/hummingbot/files/11173698/inj_filled.zip)

**Comment by petioptrv** [comment]
I am not able to reproduce this locally. I did push a fix for a bug I caught while investigating this, but I am not sure it will directly address the issue. However, in the logs I see that the order order has a hummingbot order ID associated with it, so it's linking it to an order from the previous session. When trying to test this further, please keep the logs from the previous session. Also, please include the db and csv files along with them. Those will help in chasing down this particular issue.

**Comment by rxlxrxsx** [comment]
Tested on commit [43f25d6](https://github.com/CoinAlpha/hummingbot/pull/330/commits/43f25d68e65ce55cb6010f6de6e063b4c14dc7e3) and still getting the issue.

<img width="1424" alt="Screen Shot 2023-04-07 at 3 10 46 PM" src="https://user-images.githubusercontent.com/64377055/230679575-b97c752c-81f3-4e55-a65e-da02227a5564.png">

Logs, config and data: [inj_339.zip](https://github.com/CoinAlpha/hummingbot/files/11181601/inj_339.zip)

**Comment by petioptrv** [comment]
Thank you for the logs. I was able to pinpoint the issue. I've added a fix in [this commit](https://github.com/CoinAlpha/hummingbot/pull/330/commits/c3e51d11a88c07f37bb33448d622b35663f6477c).

**Comment by mrhzysbl** [comment]
Tested and confirmed in commit [c3e51d1](https://github.com/CoinAlpha/hummingbot/pull/330/commits/c3e51d11a88c07f37bb33448d622b35663f6477c) that it no longer captures trades performed on the exchange
