### ISSUE TITLE
Kucoin - Unexpected error in user stream listener loop

### ISSUE THREAD

**Issue by rxlxrxsx** [CoinAlpha/hummingbot#3390]
**Describe the bug**
Getting an `Unexpected error in user stream listener loop` on Kucoin connector from time to time. Creating a ticket for tracking.

```
2021-05-18 06:10:16,768 - 6343 - hummingbot.connector.exchange.kucoin.kucoin_exchange - ERROR - Unexpected error in user stream listener loop.
Traceback (most recent call last):
  File "hummingbot/connector/exchange/kucoin/kucoin_exchange.pyx", line 282, in hummingbot.connector.exchange.kucoin.kucoin_exchange.KucoinExchange._user_stream_event_listener
    client_order_id = execution_data["clientOid"]
KeyError: 'clientOid'
```

**Steps To Reproduce**
1. Run a pure_mm bot on Kucoin

**Screenshots**
<img width="1423" alt="Screen Shot 2021-05-18 at 3 12 44 PM" src="https://user-images.githubusercontent.com/64377055/118611241-3178d000-b7ef-11eb-8f9f-be536494fcdf.png">

**Release version**
development-0.39.0

**Attachments**
[kucoin.zip](https://github.com/CoinAlpha/hummingbot/files/6499278/kucoin.zip)

**Comment by rxlxrxsx** [comment]
Fixed in development-0.40.0

**Comment by gerald-hb** [comment]
Another user reported this issue 
Discord name: Skan#0658
Support Packets
https://cdn.discordapp.com/attachments/849861880096620607/853804152659509268/unknown.png
[logs_Sh3pp4rd-v1.log](https://github.com/CoinAlpha/hummingbot/files/6645060/logs_Sh3pp4rd-v1.log)

**Comment by RC-13** [comment]
@gerald-hb Kindly advise the user that the fixed has been added to the development branch and will be included in the upcoming release, thanks.
