### ISSUE TITLE
Failed Test PR #330 - Filled trade recorded twice

### ISSUE THREAD

**Issue by rxlxrxsx** [CoinAlpha/hummingbot#340]
## Summary and Screenshots
Captured a scenario where the bot recorded a single filled order twice:

<img width="1423" alt="Screen Shot 2023-04-06 at 1 07 01 PM" src="https://user-images.githubusercontent.com/64377055/230473262-a4c254b7-045d-447d-b222-2554c8bee968.png">

## Steps To Reproduce
1. Clone and install featured branch
2. Connect to gateway
3. Create a perpetual market making strategy using Injective Perpetual
4. Set tight spreads and wait for an order to get filled

## Test Result Comparison
N/A, new connector

## Attachments
Logs, config and data: [inj_filled_twice.zip](https://github.com/CoinAlpha/hummingbot/files/11173797/inj_filled_twice.zip)

**Comment by petioptrv** [comment]
@rxlxrxsx, I am not able to reproduce this locally. I did however push several bug fixes this morning, so this may be addressed already. Please give it another round of testing. I will keep my bot running for a few more trades as well.

**Comment by rxlxrxsx** [comment]
Tested on commit [43f25d6](https://github.com/CoinAlpha/hummingbot/pull/330/commits/43f25d68e65ce55cb6010f6de6e063b4c14dc7e3) and not able to encounter this issue so far, closing for now.
