### ISSUE TITLE
[BUG] Order still shown as active after fill (pureMM ddex)

### ISSUE THREAD

**Issue by Cobotto** [CoinAlpha/hummingbot#341]
**Describe the bug**
// A clear and concise description of what the bug is.

I have an order filled at ddex with pure mm strat. The order is recognised as filled by the bot, but when querying "status", it will still show both the two original orders locally as active.

In the logs you can see that the bot is still searching for the order after it is filled ("Order not found in active asks").

Then, when the next round starts (after a bit more than 1 hour in this case - as cancel order wait time is 3660), the second order (that was never filled) gets cancelled and two new orders are placed according to config. Thing is: the filled order still appears in the active orders list (so that there is now 3 orders active from the bots perspective - but actually there are only 2 orders).

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: 
maker_market: ddex
maker_market_symbol: WETH-DAI
order_amount: 0.1
cancel_order_wait_time: 3660.0
bid_place_threshold: 0.01
ask_place_threshold: 0.01

2. Start the bot using this command: 
bin/hummingbot.py
config
start

3. Wait till your order is filled.

**Screenshots**
// If applicable, add screenshots to help explain your problem.

**Release version**
// Include your bot's version number (Can be found at the bottom left corner of your CLI).
0.7.0

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those!
--> submitted

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by moraliang** [comment]
Discord username: cobo

**Comment by yzhang1994** [comment]
@veecos2 Could you take a look at this issue?

**Comment by veecos2** [comment]
okays
