### ISSUE TITLE
volatility script from docs, bid/ask values dont update on the fly

### ISSUE THREAD

**Issue by rogueops** [CoinAlpha/hummingbot#3418]
I started using the spread volatility script and noticed if I go and update the bid and ask price I get the message that the current strategy has been updated with the new values, but when watching it actually does not update, it kinda gets stuck unless you stop and start the bot which is fine, just want to make sure this is by design or due to a bug somewhere.

**Comment by glenntomas** [comment]
Hi @rogueops! Not all the parameters you change will reflect on the next refresh cycle. You can check on our docs the list of parameters you can configure on the fly for pure market making (https://docs.hummingbot.io/strategies/pure-market-making/#configure-parameters-on-the-fly) and perpetual market making (https://docs.hummingbot.io/strategies/perpetual-market-making/#configure-parameters-on-the-fly).

**Comment by zappra** [comment]
Unfortunately the script will require a stop/start to pick up the new spreads. Look at the top of the tick function, the script caches bid/ask from the pmm parameters and these won't be updated once they are set

**Comment by rogueops** [comment]
thats what I thought and just wanted to confirm, thanks
