### ISSUE TITLE
Ascendex - Arbitrage strategy does not take into account the minimum order amount of $5 imposed by the platform 

### ISSUE THREAD

**Issue by psaulay** [CoinAlpha/hummingbot#3419]
**Describe the bug**
The arbitrage strategy does not take into account the minimum order of $5 imposed by Ascendex. And created the order on the opposite exchange anyway.

**Release version**
Tested in versions   0.38.1 and 0.39.0.

**Comment by JuResurreccion** [comment]
Good day! 

Apologies for the late response. Kindly make another new set of API keys for both miner and hummingbot. May I also ask if what campaign are you currently running so we can check if you are eligible for the reward.

**Comment by JeremyKono** [comment]
Hi, you can edit the `min_quote_order_amount` in `config_global.py` and remove the value for the quote token so that the minimum order amount to be imposed

**Comment by psaulay** [comment]
It doesn't seem to be taken into account by the arbitrage strategy because it generates orders of less than 5 USDT sometimes even less than 1 USDT.

**Comment by JeremyKono** [comment]
Can you send over the log files and your config files as well to further check this concern?

**Comment by psaulay** [comment]
xxxx-xx-xx xx:xx:xx,xxx - 1 - hummingbot.strategy.arbitrage.arbitrage - INFO - Executing limit order buy of XXX-USDT at ascend_ex and sell of XXX-USDT at kucoin with amount 100, and profitability 1.015142360959094026823110488 [clock=xxxx-xx-xx xx:xx:xx,xxx+00:00]
xxxx-xx-xx xx:xx:xx,xxx - 1 - hummingbot.strategy.arbitrage.arbitrage - INFO - 
  Markets:


  Assets:
        Exchange Asset  Total Balance  Available Balance


  Profitability(without fees):
    take bid on kucoin, take ask on ascend_ex: 2.1245 %
    take ask on kucoin, take bid on ascend_ex: -2.6898 %

  Pending limit orders:
          market trading_pair                           order_id quantity            timestamp
    0  ascend_ex     XXX-USDT  XXXXXXXXXXXXXXXXXXXXXXXXXX      100  XXXXXXXXXXXX
    1     kucoin     XXX-USDT     XXXXXXXXXXXXXXXXXXXXXXXXXX      100  XXXXXXXXXXXX
**xxxx-xx-xx xx:xx:xx,xxx - 1 - hummingbot.connector.exchange.ascend_ex.ascend_ex_exchange - NETWORK - Error submitting BUY LIMIT order to AscendEx for 100 XXX-USDT 0.0085255.
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/exchange/ascend_ex/ascend_ex_exchange.py", line 493, in _create_order
    raise ValueError(f"Notional amount {notional} is not withing the range of {ascend_ex_trading_rule.minNotional}-{ascend_ex_trading_rule.maxNotional}.")
ValueError: Notional amount 0.8525500 is not withing the range of 5-200000.**
xxxx-xx-xx xx:xx:xx,xxx - 1 - hummingbot.connector.exchange.ascend_ex.ascend_ex_exchange - WARNING - Notional amount 0.8525500 is not withing the range of 5-200000.
xxxx-xx-xx xx:xx:xx,xxx - 1 - hummingbot.connector.exchange.kucoin.kucoin_exchange - INFO - Created OrderType.LIMIT sell order sell-XXX-USDT-1621551254013962 for 100.0000 XXX-USDT.
xxxx-xx-xx xx:xx:xx,xxx - 1 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": XXXXXXXXXXXX, "type": "OrderType.LIMIT", "trading_pair": "XXX-USDT", "amount": 100.0, "price": 0.0085226, "order_id": "XXXXXXXXXXXXXXXXXXXXXXXXXX", "exchange_order_id": "XXXXXXXXXXXXXXXXXXXXXXXXXX", "leverage": 1, "position": "NILL", "event_name": "SellOrderCreatedEvent", "event_source": "kucoin"}
xxxx-xx-xx xx:xx:xx,xxx - 1 - hummingbot.connector.exchange.kucoin.kucoin_exchange - INFO - Filled 100 out of 100.0000 of the order sell-XXX-USDT-1621551254013962.
xxxx-xx-xx xx:xx:xx,xxx - 1 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": XXXXXXXXXXXX, "order_id": "XXXXXXXXXXXXXXXXXXXXXXXXXX", "trading_pair": "XXX-USDT", "trade_type": "TradeType.SELL", "order_type": "OrderType.LIMIT", "price": "0.0085226", "amount": "100", "trade_fee": ["0.002", []], "exchange_trade_id": "XXXXXXXXXXXXXXXXXXXXXXXXXX", "leverage": 1, "position": "NILL", "event_name": "OrderFilledEvent", "event_source": "kucoin"}
xxxx-xx-xx xx:xx:xx,xxx - 1 - hummingbot.connector.exchange.kucoin.kucoin_exchange - INFO - The market sell order sell-XXX-USDT-1621551254013962 has completed according to KuCoin user stream.
xxxx-xx-xx xx:xx:xx,xxx - 1 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": XXXXXXXXXXXX, "order_id": "XXXXXXXXXXXXXXXXXXXXXXXXXX", "base_asset": "XXX", "quote_asset": "USDT", "fee_asset": "USDT", "base_asset_amount": "100", "quote_asset_amount": "0.8522600", "fee_amount": "0", "order_type": "OrderType.LIMIT", "exchange_order_id": "XXXXXXXXXXXXXXXXXXXXXXXXXX", "event_name": "SellOrderCompletedEvent", "event_source": "kucoin"}
xxxx-xx-xx xx:xx:xx,xxx - 1 - hummingbot.strategy.arbitrage.arbitrage - INFO - Limit order completed on kucoin: sell-XXX-USDT-1621551254013962 [clock=xxxx-xx-xx xx:xx:xx,xxx+00:00]
xxxx-xx-xx xx:xx:xx,xxx - 1 - hummingbot.strategy.arbitrage.arbitrage - INFO - Cooling off from previous trade on kucoin. Resuming in -14 seconds. [clock=xxxx-xx-xx xx:xx:xx,xxx+00:00]
xxxx-xx-xx xx:xx:xx,xxx - 1 - hummingbot.strategy.arbitrage.arbitrage - INFO - Cool off completed. Arbitrage strategy is now ready for new orders. [clock=xxxx-xx-xx xx:xx:xx,xxx+00:00]

**Comment by psaulay** [comment]
#####################################
###   Arbitrage strategy config   ###
#####################################

template_version: 5
strategy: arbitrage

# The following configuations are only required for the
# arbitrage strategy

# Exchange and token parameters
primary_market: kucoin
secondary_market: ascend_ex
primary_market_trading_pair: XXX-USDT
secondary_market_trading_pair: XXX-USDT

# Minimum profitability target required to place an order
# Expressed in percentage value, e.g. 1 = 1% target profit
min_profitability: 1.0

# Whether to use rate oracle on unmatched trading pairs
# Set this to either True or False
use_oracle_conversion_rate: false

# The conversion rate for secondary base asset value to primary base asset value.
# e.g. if primary base asset is USD, secondary is DAI and 1 USD is worth 1.25 DAI, "
# the conversion rate is 0.8 (1 / 1.25)
secondary_to_primary_base_conversion_rate: 1.0

# The conversion rate for secondary quote asset value to primary quote asset value.
# e.g. if primary quote asset is USD, secondary is DAI and 1 USD is worth 1.25 DAI, "
# the conversion rate is 0.8 (1 / 1.25)
secondary_to_primary_quote_conversion_rate: 1.0

# For more detailed information, see:
# https://docs.hummingbot.io/strategies/arbitrage/#configuration-parameters

**Comment by JeremyKono** [comment]
Can you please share the market pair so that I can replicate your configs on my end? thanks

**Comment by psaulay** [comment]
it's NIM-USDT

**Comment by JeremyKono** [comment]
HI, upon testing it seems I can't replicate the issue. My filled orders seem to follow the exchange's minimum.

**Comment by psaulay** [comment]
Hi, thanks for your answer, not all orders are concerned but it happens regularly.  To correct this quickly I had to add an "if quantized_order_amount >= xxx " in arbitrage.pyx

**Comment by Nullably** [comment]
The underlying problem is AscendEx connector doesn't account for minimum order amount properly. In pure market making strategy, you will see the bot trying to an order while getting ValueError, this shouldn't happen.
![image](https://user-images.githubusercontent.com/37262506/120273218-c811ba80-c2e0-11eb-87e0-f91b3a8bd93e.png)
To reproduce this, you will need to manually update `min_quote_order_amount` in conf_global to 0, and set the `order_amount` in strategy config to be below $5 in value, e.g. if current price of ETH-USDT is 2500, set the order amount to 0.001

**Comment by dennisocana** [comment]
Fixed in version 0.40 release.
