### ISSUE TITLE
Raspberry guide typo

### ISSUE THREAD

**Issue by RobJah** [CoinAlpha/hummingbot#3434]
**Describe the bug**
// A clear and concise description of what the bug is.
When you use the guide on https://docs.hummingbot.io/installation/raspberry/ to install from source there is a typo in the suggested code which makes it impossible to finish the guide.

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

https://docs.hummingbot.io/installation/raspberry/
in the first part of code you find: 
# Install Miniforge, Python and update alternatives
wget https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-aarch64.sh
sh Miniforge3-Linux-aarch64.sh
sudo apt-get install python3.7
sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 1

In the last line there is a typo, it should be:
sudo update-alternatives --install /usr/bin/python python /usr/bin/python3.7 1
...

**Screenshots**
// If applicable, add screenshots to help explain your problem.

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).
0.39.0

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**
i hate discord sorry

**Comment by teddyarangorin** [comment]
Hi @RobJah Thank you for reporting this, we will have this updated.

**Comment by RobJah** [comment]
Youre welcome. The strange thing is, now that i tried it a couple of times there is still a hit and miss factor in it. Without the .7 it just doesnt work, but with the .7 it works 6 out of 8 times. So maybe you guys need a wizard to look at it, maybe there is something else missing. Ijust spotted this what i believe is a typo and correcting it works 75% of the times. 

Thanks!
