### ISSUE TITLE
Hummingbot asks for higher version of Numpy on raspberry

### ISSUE THREAD

**Issue by RobJah** [CoinAlpha/hummingbot#3435]
**Describe the bug**
// A clear and concise description of what the bug is.
When you install the hummingbot from source with this guide https://docs.hummingbot.io/installation/raspberry/
You cannot launch the hummingbot software at the end because of an error saying you need numpy 16.5, while i only have 16.2.
I tried to update numpy myself and launch software again but it keeps saying my numpy is only 16.2. Eventhough i installed all dependencies like the guide commands.

Tried it 5 times with a freshly flashed OS and have been installing hummingbot succesfully on raspberries for months now without any failure. 

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
1. run a clean install from source using a raspi 4b 4gb 
2. Launch hummingbot 
...

**Screenshots**
// If applicable, add screenshots to help explain your problem.
I have none because i am reporting this for someone i tried to help yesterday.

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).
0.39.0

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by teddyarangorin** [comment]
Hi @RobJah Thank you for reporting this, I will let the team know of this issue.

**Comment by RobJah** [comment]
Thanks!
