### ISSUE TITLE
Hummingbot wont launch on raspi

### ISSUE THREAD

**Issue by RobJah** [CoinAlpha/hummingbot#3442]
**Describe the bug**
// A clear and concise description of what the bug is.
After installing hummingbot on a raspberry like the guide commands (https://docs.hummingbot.io/installation/raspberry/) the software doesnt launch. At first I got the error that numpy was not up to date, so i re-tried the whole installation process and installed the numpy==1.16.5 pip dependency before i did the other pip dependincies. After this i didnt get the numpy version error anymore, but now im stuck with the following error.

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
1. install latest version of hummingbot on raspi using this guide: https://docs.hummingbot.io/installation/raspberry/
2. after activating conda, installing all dependencies and compiling the software start it with command bin/hummingbot.py

**Screenshots**
// If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/43188591/119535250-19252a00-bd88-11eb-953f-8ca89d44d163.png)

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).
0.39.0

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by glenntomas** [comment]
@RobJah Hi! May I know what is the specs of your Raspberry Pi and also what operating system are you running? Did you follow the prerequisites when installing hummingbot from source? (https://docs.hummingbot.io/installation/raspberry/#prerequisites) Thank you!

**Comment by RobJah** [comment]
ofc u may !

After ur question i realized the guide doenst link to the latest version but just to the topic about the 64 bit OS. Maybe the prerequisites part should link to https://downloads.raspberrypi.org/raspios_arm64/images/ in stead of the forum post.

But now that i want to retry the install with this other version of the 64bit OS i see the pip dependecies part of the guide has been changed to:
# Install the pip dependencies
pip install -r setup/requirements-arm.txt

which leads me to the next error:

(hummingbot) pi@raspberrypi:~ $ pip install -r setup/requirements-arm.txt
Could not open requirements file: [Errno 2] No such file or directory: 'setup/requirements-arm.txt'

**Comment by sidmontanez** [comment]
Hi @RobJah, Apologies on the late response. I just want to confirm prior to `bin/hummingbot.py` have you already tried to `./clean && ./compile`?

**Comment by RobJah** [comment]
Yes sorry for me not being more clear :) 

I did everything the guide commands and this is my 5th Raspberry pi 4b GB i am trying to setup with hummingbot. It always worked, up untill now.

So yeah, i did the 'cd hummingbot && ./clean && ./compile'-command for sure

**Comment by glenntomas** [comment]
Hi @RobJah! Let me try this on my end I'll let you know once I'm done testing.

**Comment by RobJah** [comment]
Thanks for the swift action!!

I am gonna test it right away with this altered code u provided <3

**Comment by RobJah** [comment]
SOLVED

thanks !
