### ISSUE TITLE
Failed Test PR#342 - Error setting leverage

### ISSUE THREAD

**Issue by rxlxrxsx** [CoinAlpha/hummingbot#345]
## Summary and Screenshots
Getting this error after starting the bot related to the leverage, I can confirm the leverage being used by the bot and exchange is the same, I also tried cross and isolated mode but still getting the error.

<img width="1422" alt="Screen Shot 2023-04-14 at 9 55 02 PM" src="https://user-images.githubusercontent.com/64377055/232181836-2c9204bc-4926-47ab-9667-4666b289cadb.png">

```python
2023-04-15 11:14:31,094 - 3313062 - hummingbot.connector.derivative.phemex_perpetual.phemex_perpetual_derivative.PhemexPerpetualDerivative - NETWORK - Error setting leverage 1 for DOGE-USDT: TE_ERR_INCONSISTENT_POS_MODE
```

## Steps To Reproduce
1. Clone and install branch
2. Run the client
3. Connect Phemex API key
4. Create a perpetual market making strategy using Phemex
5. Start the strategy

## Test Result Comparison
N/A, new connector

## Attachments
Logs and config: [phemex_leverage_order.zip](https://github.com/CoinAlpha/hummingbot/files/11238232/phemex_leverage_order.zip)

**Comment by vic-en** [comment]
I pushed a commit that should solve this.

**Comment by mrhzysbl** [comment]
Tested and confirmed working on commit [b3c3df3](https://github.com/CoinAlpha/hummingbot/pull/342/commits/b3c3df386d5db20cace2f85fa0f9ccde5ebf3897).
