### ISSUE TITLE
Perpetual Market Making: profit taking order wrong size to close position

### ISSUE THREAD

**Issue by zappra** [CoinAlpha/hummingbot#3452]
**Describe the bug**
In the event of a partial fill, the bot could end up with a profit taking order insufficient to close a position

**Steps To Reproduce**
This requires a specific sequence of order fills and exposes a flaw in the way the profit taking order is calculated and updated

A buy order for 146.7 ALGO is created
This is partially filled - 142.5 ALGO
The bot creates a profit taking order for 142.5 ALGO to close the position
The remaining portion of the initial buy order is filled
Position size is now 146.7 ALGO but profit taking order does not update. This will only occur if another buy takes place to change the entry price on the position, as the profit taking logic only considers price when determining whether to cancel existing take profit orders

**Release version**
dev 0.39.0

**Attachments**
[logs_conf_pure_mm_algo-futures.log](https://github.com/CoinAlpha/hummingbot/files/6554616/logs_conf_pure_mm_algo-futures.log)

**Comment by petioptrv** [comment]
I'd like to take a shot at that one

**Comment by petioptrv** [comment]
Am I missing something, or are there truly no test cases for the perpetual market making stragety?

**Comment by dennisocana** [comment]
@petioptrv that's correct. We have a story in our backlog to add the missing unit tests to the strategy https://github.com/CoinAlpha/hummingbot/issues/3270.
