### ISSUE TITLE
Failed Test PR #342 - Funding payment not received

### ISSUE THREAD

**Issue by rxlxrxsx** [CoinAlpha/hummingbot#349]
## Summary and Screenshots
The funding payment is not being received by the bot, waited for at least 10 minutes but no message was seen regarding the funding payment received in the logs.

https://user-images.githubusercontent.com/64377055/234637918-e158991d-2436-49c3-9ee0-3f382b7436b6.mov

## Steps To Reproduce
1. Clone and install featured branch
2. Create a perpetual market making strategy using Phemex Perpetual
3. Set tight spreads and wait for an order to get filled
4. With a position currently open, wait for funding period to pass by

## Test Result Comparison
N/A, new connector

## Attachments
Logs and config: [phemex_funding.zip](https://github.com/CoinAlpha/hummingbot/files/11335002/phemex_funding.zip)

**Comment by vic-en** [comment]
@rxlxrxsx Pls test again with:
- Open position remains open 1 minute before and after funding period.
Also set a big values for `long_profit_taking_spread`, `long_profit_taking_spread`, and `stop_loss_spread` to prevent a close order from possibly closing the position.

**Comment by vic-en** [comment]
<img width="1405" alt="Screenshot 2023-04-26 at 3 40 14 PM" src="https://user-images.githubusercontent.com/31972210/234697416-84ff7c12-4fb8-42f0-9857-b95074d83fb2.png">
You can also confirm you actually received on the web app.

**Comment by rxlxrxsx** [comment]
@vic-en re-tested and confirmed were still not getting the funding payment message in the client.

<img width="1034" alt="Screen Shot 2023-04-26 at 7 35 54 PM" src="https://user-images.githubusercontent.com/64377055/234737905-a1e16434-0fac-4657-8cf1-4c474ad11899.png">

Logs and config: [phemex_funding_2.zip](https://github.com/CoinAlpha/hummingbot/files/11338710/phemex_funding_2.zip)

**Comment by vic-en** [comment]
@rxlxrxsx You can test again now. I updated the funding payment.

**Comment by rxlxrxsx** [comment]
@vic-en tested using commit [9ea3c64](https://github.com/CoinAlpha/hummingbot/pull/342/commits/9ea3c646f5821967cf708671739351220ee55c33) and still not able to capture the funding payment message in the client. I can confirm there was an open position during the funding payment period.

Logs: [logs_phemex_funding.log](https://github.com/CoinAlpha/hummingbot/files/11383333/logs_phemex_funding.log)

**Comment by geneuinely07** [comment]
- Closing this issue since Phemex Perp PR has been merged already to the Foundation's `development` 
- @mrhzysbl created a bug report to the Foundation and @vic-en  will provide the necessary fix
