### ISSUE TITLE
UI Suggestion: Enforce valid values

### ISSUE THREAD

**Issue by pointtoken** [CoinAlpha/hummingbot#35]
It is very cool that the UI shows valid values as you type them. However, it is problematic that the UI allows a user to enter invalid values and override these valid values. For example, a user can enter an invalid trading pair, which wreaks havoc on the tool. Perhaps do something such that invalid values can't be entered.

**Comment by martinkou** [comment]
@yzhang1994 is there anything we can do about it? something like validation of user inputs?

**Comment by yzhang1994** [comment]
Yes, we actually currently validate some user inputs (such as exchanges and strategies). We can add additional validators - the symbol validator should be easy since the bot already requests valid symbols. Other inputs can be more complicated to validate.

**Comment by Steve1943** [comment]
Could you validate "my_imported_strategy.yml" when launched to verify that it's trading pairs exist on their respective exchanges?  
I have already twice deployed strategies for a pair that is not actually traded on it's specified exchange!!

**Comment by yzhang1994** [comment]
Added symbol validator to the development branch in #158, and will be available in the next release
