### ISSUE TITLE
Create unit tests for core network module - network_iterator.pyx

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#3500]
As part of unit tests refactor and cleanup epic, create missing unit tests for `hummingbot/core/network_iterator.pyx `

**Comment by petioptrv** [comment]
@dennisocana, I'd like to grab that one too, if no one's working on it

**Comment by dennisocana** [comment]
Hey @petioptrv, thanks for asking. @CrimsonJacket started working on this story already.
