### ISSUE TITLE
Create unit tests for core network module - pubsub.pyx

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#3501]
As part of unit tests refactor and cleanup epic, create missing unit tests for `hummingbot/core/pubsub.pyx`

**Comment by petioptrv** [comment]
I am interested in taking this on if no one is currently working on it.

**Comment by dennisocana** [comment]
Hey @petioptrv, we haven't assigned this yet to anyone in the team. Feel free to submit a pull request and link this story then we will review.

**Comment by dennisocana** [comment]
Completed in version 0.41 development by @petioptrv. Thanks for contributing!
