### ISSUE TITLE
Binance US - USDT-USD pair only shows as USD-TUSD in client

### ISSUE THREAD

**Issue by gerald-hb** [CoinAlpha/hummingbot#3513]
**Describe the bug**
Unable to input or select USDT-USD

**Steps To Reproduce**
1. connect binance_us
2. create PMM as strategy
3. input USDT-USD. will get notified USDT-USD is not an active market on binance_us. while on binance.us exchange its available.

As a workaround there is an option to use USD-TUSD but inventory skew doesn't work because it is seeking a "TUSD". Status request in the Hummingbot terminal results in a $0 ballence

**Screenshots**

![image](https://user-images.githubusercontent.com/84826167/120875449-78800700-c5de-11eb-8032-0791b0c2dd9c.png)
![image](https://user-images.githubusercontent.com/84826167/120875547-ee846e00-c5de-11eb-9ed1-a431aff49fb2.png)

**Release version**
0.39.1

**Attachments**
na

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Comment by RC-13** [comment]
Fixed on version 0.43.0
![image](https://user-images.githubusercontent.com/57189990/131762516-96fb18f1-0279-404b-9862-48a62fd149f9.png)
