### ISSUE TITLE
In paper trading mode, minimum_order_amount was lesser than required by exchanges ($11).

### ISSUE THREAD

**Issue by andrewsiah** [CoinAlpha/hummingbot#3514]
**Describe the bug**
In paper trading mode, while running a strategy with multiple order levels and inventory skew, the adjusted amount of trades was in decimals (lesser than $10). These trades, realistically, shouldn't be issued at all as the exchanges would reject them.

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:
1. Initiate a pure market making strategy
2. Use multiple order levels (3 and above)
3. Use inventory skew (I set 30%)
4. Start

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: ...
2. Start the bot using this command: ...
...

**Screenshots**
// If applicable, add screenshots to help explain your problem.
<img width="530" alt="Screenshot 2021-06-05 at 1 58 30 PM" src="https://user-images.githubusercontent.com/31041391/120883536-54d5b480-c610-11eb-8c5d-bd806887a549.png">
As seen here, price of FRONT-BUSD is 1.11, but my adjusted order amount is <0.01, which would result in orders of $0.01. 

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).
0.39.1

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 
[conf_pure_mm_front_spread1_test.txt](https://github.com/CoinAlpha/hummingbot/files/6602166/conf_pure_mm_front_spread1_test.txt)
I changed it to txt, cause yml is not-uploadable.

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by rxlxrxsx** [comment]
Hi @andrewsiah, we have an [existing ticket](https://github.com/CoinAlpha/hummingbot/issues/2183) regarding this issue. Moving forward please refer to this ticket for updates. Thanks.
