### ISSUE TITLE
Create a method to exit the bot interface without terminating the process

### ISSUE THREAD

**Issue by coldspark29** [CoinAlpha/hummingbot#3516]
When logging into the bot's server via SSH and running the bot, there is not method to exit the bot interface without terminating the process. When you type ``exit`` all operations are stopped, so you have to type ``killall ssh`` and login to the server once more via SSH. This is quite cumbersome.

**Comment by R-K-H** [comment]
You can use docker, attach to the instance and then to exit the instance use `ctrl + p + d` as an option for this already.

**Comment by coldspark29** [comment]
@R-K-H No, that doesn’t work

**Comment by R-K-H** [comment]
Are you speaking about the development console or are you running the bot on a server which you ssh into?

If you're on a server which you ssh into:
1. are you building from source?
or
2. are you running docker?

I can assure you that if you're attaching to a dockerized instance of hummingbot using docker attach and you use `ctrl + p + q` (sorry not d) it will work.

It seems like you're running a local instance on a server, so I'd recommend you check out `screen`

https://linuxize.com/post/how-to-use-linux-screen/

If not, let me know and I'll see if I can help.

**Comment by coldspark29** [comment]
I am using the ``start.sh`` script to start the instance. It is on docker yes, but ``Ctrl + p`` does show me the last entered command and not what you tell me.

**Comment by R-K-H** [comment]
https://dscottraynsford.wordpress.com/2015/08/28/detatch-from-a-docker-container-without-stopping-it/

**Comment by coldspark29** [comment]
That worked. Thanks!
