### ISSUE TITLE
Failed Test #356 - Unable to install feat branch #544

### ISSUE THREAD

**Issue by mrhzysbl** [CoinAlpha/hummingbot#357]
## Summary and Screenshots
Stuck on installing "Installing pip dependencies:" message when we try to install the said branch. Tested both locally and on a test server, getting the same behavior. This has been ongoing for over 30 minutes.

Local PC: 
<img width="1186" alt="image" src="https://github.com/CoinAlpha/armada/assets/120451804/01564fd6-0a52-4dd9-94a9-3ecc147daf32">

Test Server: 51.79.146.118
<img width="1083" alt="image" src="https://github.com/CoinAlpha/armada/assets/120451804/ad7826dd-fdd2-45d5-9cc1-c6a3aceabd19">

## Steps To Reproduce
1. Clone the said branch
2. Go to the root folder and run command ./install
3. Wait for the installation

## Expected Results
Branch should be installed properly

## Test Result Comparison
Tried installing Hummingbot dev branch and the installation was successful.

<img width="1097" alt="image" src="https://github.com/CoinAlpha/hummingbot/assets/120451804/1160d287-fe32-4344-b08b-dfed6e528f16">

## Attachments
Please attach your config file and log file for debugging.

**Comment by rxlxrxsx** [comment]
This is confirmed fixed using commit [cbd1e27](https://github.com/CoinAlpha/hummingbot/pull/356/commits/cbd1e27230a7de257d036d4de8096c405f5316f4).
