### ISSUE TITLE
Max_age for cancelling hanging orders

### ISSUE THREAD

**Issue by andrewsiah** [CoinAlpha/hummingbot#3574]
**Feature Suggestion**
// A succinct description of **how you want to achieve the desired behavior**.
// If you have looked at the code and know exactly what code changes are needed then please _consider submitting a pull request_ instead.
Hanging_orders_max_age = 1800. So that if by certain time, hanging orders aren't cleared, it's cancelled. 
Best yet If it's in conjunction with another lower hanging pct. So conditionally, if hanging_order_age > 1800 and spread > x%, it will cancel. 
Or, reducing the spread of hanging orders every x seconds. 
So if I have a hanging order at 2% spread, it will reduce by Y% (let's say 0.2%) every 10 minutes. So as to increase probability it'll be met and start freeing available capital to trade again. (Since hanging orders lock up capital until cancelled or taken).
Ideally, the ability to just hot-tweak hanging_orders_cancel_pct in script (in pure market making) would solve all this problems.

**Impact**
// A succinct description of **why you want the _desired behavior_** specified above.
The desired behavior will allow me to ...

Hanging orders are my bread and butter. It guarantees we profit the spread margin as market makers, as every other setting puts us at risk of buying the dip and selling the rises. 

One of the biggest hindrances of hanging_orders now is that hanging orders are always left on the table with no way of expiring unless breaking the hanging_pct. But setting too low a hanging_pct isn't ideal in crypto as it's not uncommon to see a rise and fall of 5-10% in a single hour. 

**Additional context**

**Comment by phbrgnomo** [comment]
We are currently working on a new way on how hanging orders are calculated:

https://github.com/CoinAlpha/hummingbot/issues/3291
