### ISSUE TITLE
Pure Market Making - Hanging orders refreshed by max order age is not recreated

### ISSUE THREAD

**Issue by rxlxrxsx** [CoinAlpha/hummingbot#3578]
**Describe the bug**
Hanging orders refreshed by max order age is not recreated due to the delay in balance update. So far I was able to reproduce this on Gate.io (currently under testing phase) and once on Kraken, Binance and Ascendex.

Kraken
<img width="1320" alt="Screen Shot 2021-06-14 at 6 24 37 PM" src="https://user-images.githubusercontent.com/64377055/121878059-db3f7400-cd3d-11eb-92a1-e4b0948cd712.png">

Binance
<img width="1312" alt="Screen Shot 2021-06-15 at 5 14 31 PM" src="https://user-images.githubusercontent.com/64377055/122027624-db9f4400-cdfd-11eb-9a68-4516720ed4d9.png">

Ascendex
<img width="1321" alt="Screen Shot 2021-06-15 at 5 16 38 PM" src="https://user-images.githubusercontent.com/64377055/122027671-e4901580-cdfd-11eb-88f4-a03dac0b86c4.png">

**Steps To Reproduce**
1. Create a pure market making bot
2. Set max order age to a lower value, for testing purposes
3. Enable hanging orders, run the bot and wait for an order to get filled
4. Leave the bot running as it may take some time before the issue happens

**Release version**
development-0.40.0

**Attachments**
Logs and config: [logs-config.zip](https://github.com/CoinAlpha/hummingbot/files/6654412/logs-config.zip)

**Comment by dennisocana** [comment]
Fixed in version 0.41 release
