### ISSUE TITLE
[Feature] Replace CoinMarketCap.com by an alternative price data source

### ISSUE THREAD

**Issue by Steve1943** [CoinAlpha/hummingbot#358]
**Feature Suggestion**

Replace the CoinMarket.com API as a source of market price data by an alternative such as :
OpenMarket.com e.g.

http://api.openmarketcap.com/api/v1/tokens?page=N    (where N = 1 or 2 or 3 etc)  
each page requested reports 100 coins.

**Impact**

Replaces a discredited data source by a more reliable alternative.  At least one alternative source currently offers free reporting on many coins not available gratis via coinmarket.com 
Only "reliable" exchanges (see below) are included in the reporting.

**Additional context**

Recent evidence submitted to the SEC disclosing that 95% of cryptocoin trade volumes reported by exchanges is false - citing the culpable exchanges - and the honest ones.  

Evidence submitted also stated that experienced market traders know full well about these reporting distortions and utilize alternative data based solely on the "reliable" exchanges.

CoinMarketCap.com has since admitted to these reporting distortions.

**Comment by tmlee** [comment]
Have you looked at the CoinGecko API https://www.coingecko.com/en/api ?
While we also display reported volume from exchanges. You have the flexibility to query on a per exchange basis should you need them.

It is hard to tell which volume is real and not, and we are approaching it using Trust Score https://blog.coingecko.com/trust-score/; that being said it is different than what you are looking for.

In any case i am happy to answer any questions and listen to your suggestion and feedback to tackle such problem.

**Comment by Steve1943** [comment]
1) My concerns were based on the findings reported in 
https://www.sec.gov/comments/sr-nysearca-2019-01/srnysearca201901-5164833-183434.pdf 
to the effect that all but a dozen "good" exchanges were reporting "cloud cuckoo land" both in respect of prices and volumes.

2) My proposal assumed, incorrectly, that you were using Coinmarket.com as a source of pricing data.  

3) The CoinGecko approach with Trust-Score is admirable response to the quality issue in exchange reporting.  I'm both reassured and highly encouraged that Coin-Alpha clearly understands the problem and is already working with the cutting edge data provider to overcome it.
