### ISSUE TITLE
[BUG] Deadlink in documentation

### ISSUE THREAD

**Issue by ellieeee** [CoinAlpha/hummingbot#359]
**Describe the bug**
Deadlink in docs for configuration.

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
1. Go to https://docs.hummingbot.io/operation/configuration/
2. Click conf_arbitrage_strategy.yml
3. Use link at bottom (https://docs.hummingbot.io/configuration/#hummingbot-configuration-variables)

Expected: Useful doc shown
Actual: Deadlink or broken page w/o CSS

**Screenshots**
// If applicable, add screenshots to help explain your problem.

**Release version**
// Include your bot's version number (Can be found at the bottom left corner of your CLI).

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**
ellieeeee#4149

**Comment by carlolm** [comment]
Thanks, fixed here: https://github.com/CoinAlpha/hummingbot/pull/362

**Comment by ellieeee** [comment]
Thanks for the quick fix!
