### ISSUE TITLE
unable to input or select SC-USDT

### ISSUE THREAD

**Issue by gerald-hb** [CoinAlpha/hummingbot#3604]
**Describe the bug**
unable to input or select SC-USDT

**Steps To Reproduce**
1. connect to Binance
2. input SC-USDT (not available) but SCU-USDT appears (looks like a spelling error). I can confirm that SC-USDT exist in Binance

Here are the steps to reproduce the issue (see attachments in the section below):

**Screenshots**
![image](https://user-images.githubusercontent.com/84826167/122518895-66718000-d044-11eb-881b-7c727266770e.png)
![image](https://user-images.githubusercontent.com/84826167/122518939-738e6f00-d044-11eb-825e-3720366798b8.png)
![image](https://user-images.githubusercontent.com/84826167/122518960-7be6aa00-d044-11eb-9cfa-f3460db3e2a4.png)

**Release version**
0.40

**Attachments**
na

**Comment by cali-tomas** [comment]
Tested on Windows Docker build
- version 0.41.0

![image](https://user-images.githubusercontent.com/85161223/122672324-a3cd3d80-d1fd-11eb-902a-6b8d281298c0.png)

**Comment by petioptrv** [comment]
If no one's looking at this, I can attempt a fix. I've tracked down the issue to `hummingbot.connector.exchange.binance.binance_utils.split_trading_pair`, but I'd have to investigate a bit more for a proper solution.

**Comment by glenntomas** [comment]
Hi @petioptrv, yeah sure. Let us know if you have the fix. Thank you for contributing.

**Comment by dennisocana** [comment]
Fixed in version 0.42 release.

**Comment by dennisocana** [comment]
Fixed in version 0.43 release
