### ISSUE TITLE
Refactor Binance Perpetual Derivative connector

### ISSUE THREAD

**Issue by Nullably** [CoinAlpha/hummingbot#3615]
**Description**
Refactor Binance Perpetual Derivative connector to conform to Perpetual Trading base class. The Binance Perpetual Derivative connector will no longer derive from DerivativeBase.

Note that Spot Perpetual arbitrage and Perpetual market making strategies will no longer work with Binance Perpetual Derivative connector at this point util they are refactored as well.

**Comment by ajosegideont** [comment]
🗂
