### ISSUE TITLE
Telegram & MacOS apps show different KPI results

### ISSUE THREAD

**Issue by snussik** [CoinAlpha/hummingbot#3620]
**Describe the bug**
The telegram `/history` and macOS app interfaces show different results:

**Screenshots**
<img width="925" alt="Screenshot 2021-06-22 at 09 27 53" src="https://user-images.githubusercontent.com/16715490/122874988-628f7780-d33c-11eb-9d68-86fe2a58780d.png">

**Release version**
macOS app version: `0.40.0`

**Comment by sidmontanez** [comment]
Hi @snussik The Return % that's located on the bottom of the navbar matches the calculated return on History after the last trade. While the Return % that's showing when you run a `history` command differs depending on the market price of the pair that you're trading. 

Here's a link for more information about the Performance History: https://docs.hummingbot.io/features/performance-history/#return-percentage
