### ISSUE TITLE
Add more fields to LimitOrder

### ISSUE THREAD

**Issue by Nullably** [CoinAlpha/hummingbot#3622]
**Why**
LimitOrder is used throughout Hummingbot and HummingSim for both real trading and back testing operations. However, it is currently lacking some important data points, and often we had adopted workarounds to compensate for those, e.g. getting creation time from client_order_id. 

**Features**
Add the following fields to the LimitOrder object.
- `filled_amount` (Decimal) The order amount being filled, this is useful in case of partially filled orders
- `creation_timestamp` (int) The local timestamp at which the order is created in Hummingbot
- `status` (int) The current status of the order
    1 - New (Created in HB but yet open on exchange)
    2 - Open (Open on exchange)
    3 - Canceled
    4 - Completed
    5 - Failed
    
**Additional context**
Since this affects both Hummingbot and HummingSim as such it requires review/approval from both parties.

**Comment by Nullably** [comment]
@kmcgowan2000 Can you please review this?
I add `status` in there as well which I forgot to mention on our last meeting.

**Comment by kmcgowan2000** [comment]
@Nullably Design spec looks good to me. Just to clarify, the created_timestamp is not the timestamp at which it appears on the exchange's order book, it is the timestamp at which the `LimitOrder` object is created in Hummingbot?

**Comment by Nullably** [comment]
@kmcgowan2000 
> it is the timestamp at which the LimitOrder object is created in Hummingbot?

Yes
