### ISSUE TITLE
Uniswap_v3_lp iteration 3 - volatility

### ISSUE THREAD

**Issue by phbrgnomo** [CoinAlpha/hummingbot#3632]
## What must be implemented

Use the historical volatility function implemented in Issue #3629 to calculate the upper and lower bounds of the liquidity positions

## Details

The reason to use volatility as a reference to create liquidity positions on Uniswap V3 is to look for the best price range where the price is expected to be for some time.

Currently, it is only possible to input manual price values to define the positions range.

To use this feature, the following questions must be asked a `uniswap_v3_lp` strategy is created:

`Do you want to use past volatility to calculate position price ranges (Yes/No)?`
If No, the price range of the positions will be created as it is now (asking the user for the spread %)
If Yes, the following questions will be asked:

`What is the timeframe (in days) will be used as volatility reference?`
The prices of the liquidity pool are pulled in a 1-second time frame. The bot needs to transform the calculated volatility through the formula:
`volatility * sqrt(seconds_in_timeframe)`
Example: if the user enter 1 (day), `transformed_volatility = volatility * sqrt(3600)`

`How many times the market volatility you want to use as the position spread?`
The user must enter how many times the volatility will be multiplied by to define the price range
Example: if the user enters 2, using the `spread` of each new position will be equals to `transformed_volatility * 2`

 **Position creation logic**

Every time a new position has to be created (be it the starting position, or when a change is triggered when the price moves out of range), the bot will pull the last market prices of the pool, run the volatility calculation and transformation, and use the updated value as the new position `spread`

## Definition of done

- Present the option to use the volatility to automatically create liquidity positions
- All new liquidity positions created by the bot will use the `transformed_volatility` value multiplied by the `volatility_multiplier` value as the positions bound (upper bound on the sell-side, lower bound on the buy-side)

**Comment by dennisocana** [comment]
Will discuss again before the start of the 2nd sprint of v0.42 to give more time for testing the 2nd iteration in production.
