### ISSUE TITLE
"Markets" field for liquidity mining is overly sensitive to formatting

### ISSUE THREAD

**Issue by tedwardd** [CoinAlpha/hummingbot#3645]
**Describe the bug**
The `markets` configuration option for liquidity mining strategy is a free-form input field and should be a little more flexible with the input formats that it allows or additional input sanitization should be done to ensure the provided format is compatible. Currently, pairs are case sensitive and there can not be a space between the comma and the next pair in the list otherwise the user is unable to set the `token` field.

**Steps To Reproduce**
1. Create a liquidity mining strategy.
2. Enter the pairs in the `markets` field either lower case and/or with a space between the pairs (eg. `eth-usdt, btc-usdt`)
3. Try to set the `token` field but receive an error that any value you put in is invalid.
...

**Screenshots**
Example configuration and behavior:
<img width="572" alt="Screen Shot 2021-06-28 at 11 37 23 AM" src="https://user-images.githubusercontent.com/524645/123666481-3e81d980-d807-11eb-82bd-d5b8cb50fd20.png">

**Release version**
Version: 0.40.0

**Optional: your discord username:** tedward#1533

**Comment by dennisocana** [comment]
Fixed in version 0.42 release.
