### ISSUE TITLE
Integrate new `APIThrottler` into existing connectors

### ISSUE THREAD

**Issue by CrimsonJacket** [CoinAlpha/hummingbot#3663]
This story is an epic that covers the integration process of `APIThrottler` into all connectors.

Generally the task for each connector can be broken down into the following:
1. Determine the RateLimit type the exchange connector uses.
2. Include the list of Rate Limits as part of the exchange's `constants.py` file. 
3. Wrap the contents of the connectors' `_api_request()` method in the `APIThrottler` asynchronous context.

Note:
The `APIThrottler` would see a gradual rollout integration across all the connectors; prioritised according to LM connectors, partner connectors, etc.

**Comment by phbrgnomo** [comment]
@CrimsonJacket @dennisocana Moved the tasks on this epic to epic #3676 to keep all stories related to API Throttler on the same place.

Closing this epic, and moving the description.
