### ISSUE TITLE
Integrate `APIThrottler` into AscendEx connector

### ISSUE THREAD

**Issue by CrimsonJacket** [CoinAlpha/hummingbot#3665]
Below are the possible breakdown for the aforementioned task:
- [ ] Determine the Rate Limit type and collect all the relevant Rate Limit information used by the connector into the `constants.py` file.
- [ ] Integrate `APIThrottler` into the connector class.
- [ ] Update unit test cases as necessary

**Comment by PtrckM** [comment]
As discuss putting a note: 
- Check parrot throttler manager logic if can be reused for ascendex.
