### ISSUE TITLE
Integrate new `APIThrottler` into KuCoin connector

### ISSUE THREAD

**Issue by CrimsonJacket** [CoinAlpha/hummingbot#3666]
Below are the possible breakdown for the aforementioned task:
- [ ] Determine the Rate Limit type and collect all the relevant Rate Limit information used by the connector into the `constants.py` file.
- [ ] Integrate `APIThrottler` into the connector class.
- [ ] Update unit test cases as necessary

**Comment by dennisocana** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/hummingbot-5f340755c5e17300167a8f30/issues/CoinAlpha/hummingbot/3666?planning-poker) with ZenHub @aarmoa @CrimsonJacket @james-hummingbot @petioptrv @mhrvth @vic-en
