### ISSUE TITLE
Failed Test #366 - Unable to start client

### ISSUE THREAD

**Issue by mrhzysbl** [CoinAlpha/hummingbot#367]
## Summary and Screenshots
Getting the error "Error parsing 'content-type' metadata: invalid valu" after starting the client and automatically disconnects from the app.

<img width="1215" alt="image" src="https://github.com/CoinAlpha/hummingbot/assets/120451804/ef1dfec9-0708-4b8d-97a3-e6553a631f9b">

## Steps To Reproduce 
1. Install featured branch
2. Install and activate conda hummingbot
3. Compile
4. Start the client

## Expected Results
The client app should start without any errors.

## Test Result Comparison
No issues when cloning the development branch.

## Attachments
N/A

**Comment by petioptrv** [comment]
@mrhzysbl, what machine and OS was this test performed on?

**Comment by mrhzysbl** [comment]
@petioptrv it's MacOS Catalina Intel

**Comment by mrhzysbl** [comment]
Tried the ./start.sh when opening the app and now it's giving this error:
<img width="1151" alt="image" src="https://github.com/CoinAlpha/hummingbot/assets/120451804/514da233-9747-4188-b397-9e88e06b0702">

**Comment by mrhzysbl** [comment]
Hi @petioptrv , I was able to deploy the bots earlier but after quite sometime, it will disconnect.

https://github.com/CoinAlpha/hummingbot/assets/120451804/6eb84054-e2b1-4513-90a6-fe59f7bd9865

**Comment by petioptrv** [comment]
Should be addressed by [this PR](https://github.com/hummingbot/hummingbot/pull/6547)

**Comment by rxlxrxsx** [comment]
Tested on commit [e7bc938](https://github.com/CoinAlpha/hummingbot/pull/366/commits/e7bc93877816651ad0cf9b5d5000e2b9112b0041) and confirmed fixed.
