### ISSUE TITLE
[Feature]Can I use huobi as maker market?

### ISSUE THREAD

**Issue by beyoar** [CoinAlpha/hummingbot#367]
Can I use huobi as maker market?

Version 0.7.0

**Comment by carlolm** [comment]
Hi @beyoar we do not currently have an integration for Huobi, but we would look to add this in the future.

**Comment by beyoar** [comment]
> Hi @beyoar we do not currently have an integration for Huobi, but we would look to add this in the future.

I will do it. I hope i can commit code.

**Comment by mifeng** [comment]
@beyoar That would be great. If you're serious about this effort, we should schedule a call to walk you through the codebase. We have some Huobi data fetcher code in the codebase that you may be able to re-use. 

Let me know and we can set something up!

**Comment by mifeng** [comment]
We are currently working on the Huobi connector and expect it be available in a few weeks.
