### ISSUE TITLE
Implement `APIThrottler` class

### ISSUE THREAD

**Issue by CrimsonJacket** [CoinAlpha/hummingbot#3677]
**Initial Investigation**
- There are several ways Rate Limits are being implemented by the various exchanges. 

  1. Weighted Requests, where each user is assigned a fix rate limit and each method is assigned a weight. This is used by Binance. Where certain API endpoints has a higher weight depending on the resource consumed.
  2. Rate Limit by Methods, exchanges assigns rate limits for every API endpoint per API key pair. This is observed in Crypto.com i.e. `private/create-order` is limited to `15 requests per 100ms`
  3. Fixed Rate Limit, this is implemented by most other exchanges. i.e. AscendEx has a fixed rate limit of 6,000 requests/min

**Suggested Solution**
- Populate the various exchange specific rate limits for each API endpoint.
- Refactor of a `Throttler` class to deal with these 3 types of rate limits.

**Comment by aarmoa** [comment]
Merged in version 0.41 release
