### ISSUE TITLE
Gate.io - Random delays in between order creation

### ISSUE THREAD

**Issue by rxlxrxsx** [CoinAlpha/hummingbot#3687]
**Describe the bug**
There are also random occurrences where orders being created are delayed when using Gate.io.

**Steps To Reproduce**
1. Run a pure market making bot using Gate.io

**Screenshots**
In this screenshot, you can see that after the previous orders are successfully cancelled, it took around 15 seconds before it placed another set of orders.
<img width="1422" alt="Screen Shot 2021-07-04 at 9 45 06 AM" src="https://user-images.githubusercontent.com/64377055/124373154-615a3500-dcc2-11eb-9a49-b581d99b73b7.png">

You can also see here that it also has a delay between orders created. Looking in the status output order age you can see that all orders were placed at the same time however those orders are being open less than the order refresh time set.
<img width="1424" alt="Screen Shot 2021-07-04 at 9 47 45 AM" src="https://user-images.githubusercontent.com/64377055/124373161-6e772400-dcc2-11eb-9191-65f8f4020eb3.png">

**Release version**
dev-0.41.0

**Attachments**
[gate_io.zip](https://github.com/CoinAlpha/hummingbot/files/6759369/gate_io.zip)

**Comment by dennisocana** [comment]
Would be worth testing once we merge in the improvements to PMM and Avellaneda.

**Comment by dennisocana** [comment]
@CoinAlpha/qa-team please re-validate if this issue still happens in development after https://github.com/CoinAlpha/hummingbot/issues/4303 has been merged.

**Comment by sidmontanez** [comment]
Tested and confirmed by QA that it's working properly on the dev version. LGTM! 🙇🏽
