### ISSUE TITLE
Add `balance` command in Telegram

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#3701]
This is a requested feature that allows users to check their balances from Hummingbot and get the total USD value without having to access the client.

**Comment by zappra** [comment]
Doesn't this already exist?

**Comment by dennisocana** [comment]
@zappra not yet, here are the commands usable in telegram as of now: https://docs.hummingbot.io/features/telegram/#using-the-telegram-bot

**Comment by zappra** [comment]
@dennisocana you can use more commands than that, but not all of them work over Telegram, I submitted a PR several months ago to fix this #3065

**Comment by dennisocana** [comment]
Thanks, we're in discussion about reviewing community contributions including that specific one. I linked your PR to this story so we can track. I'll do the same in Github.

**Comment by dennisocana** [comment]
Added in version 0.44 release (October). Thanks @zappra for contributing 👍

**Comment by dennisocana** [comment]
We are including this fix in tomorrow's version 0.43 release instead.
