### ISSUE TITLE
NDAX Connector

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#3711]
Build new NDAX connector targeted to release this August (v0.42)

Official site: https://ndax.io/
API docs: https://ndaxlo.github.io/API/#introduction

**Comment by dennisocana** [comment]
Setting as high priority as discussed with @phbrgnomo since we have three weeks left until we ship this out in version 0.42 release.

**Comment by CrimsonJacket** [comment]
I have created an epic branch, [`epic/ndax_connector`](https://github.com/CoinAlpha/hummingbot/tree/epic/ndax_connector) that all subtasks of this epic should be based on.
