### ISSUE TITLE
Remove or replace GPL dependencies from Hummingbot

### ISSUE THREAD

**Issue by martinkou** [CoinAlpha/hummingbot#3712]
## Why

We currently have the following GPL package dependencies on Hummingbot:
1. aioconsole
2. readline
3. lzo

Source: https://docs.google.com/spreadsheets/d/1EFAuxfNVuQrNeugiVyTJ3MEYpUXYRNli4aNIIYRgnDk/edit#gid=1774491361

These should be replaced or removed from Hummingbot because GPL licenses are incompatible with the Apache 2.0 license we're using.

In particular, readline is a dependency from aioconsole - which means if we can find a replacement for aioconsole, we should be able to remove readline as well.

lzo is an optional dependency from pytables. The pytables conda package automatically installs lzo with it, but lzo isn't required to run pytables. We can either install pytables in alternatives ways (e.g. via PyPI), or force remove lzo after pytables has been installed.

This is likely a large task, and smaller tasks will likely need to be created on top of this.

## What

* Investigate how to replace aioconsole as the debug console.
* Investigate how to safely remove lzo dependency from Hummingbot.

**Comment by aarmoa** [comment]
Created a task to replace the debug console: https://app.zenhub.com/workspaces/hummingbot-5f340755c5e17300167a8f30/issues/coinalpha/hummingbot/4436
