### ISSUE TITLE
Change Round to Round down for calculation of order qty

### ISSUE THREAD

**Issue by leastchaos** [CoinAlpha/hummingbot#3714]
**Feature Suggestion**
Use Round down instead of round for calculation of order qty sent to exchange.

**Impact**
Prevent not enough account balance to appear.

**Additional context**
I was using inventory skew which was taking all my remaining balance, but not enough account balance occured.
It is rounding off the account balance when taking all remaining account limits instead of rounding down based on the token price. example if i holding 1000.771 ASD, the bot will round up to 1001 and enter the order of 1001 which would result in not enough balance.

ASD is rounded to 0 decimal place for trading on exchange. 
The decimal place was obtained when converting small balance in ascend_ex from other tokens resulting in the error.

![123](https://user-images.githubusercontent.com/64965782/125384465-8b4ede00-e3cb-11eb-86aa-6eb9880abd4f.png)
![unknown2](https://user-images.githubusercontent.com/64965782/125384341-5f335d00-e3cb-11eb-961e-809f86f6362f.png)

**Comment by leastchaos** [comment]
![image](https://user-images.githubusercontent.com/64965782/127946434-ccef17c3-28a0-4773-aa6f-5448eac3ae4e.png)
Upload additional image, account has 81 EXRD but the bot is trying to place 82 EXRD

**Comment by leastchaos** [comment]
![image](https://user-images.githubusercontent.com/64965782/134772964-aac29c32-ee83-4880-9846-6e38ffae4c47.png)
![image](https://user-images.githubusercontent.com/64965782/134772970-8335d9ef-4250-47a8-a6b9-2f5733391adf.png)
need this issue to be fixed.... the rounding issue keep popping up once in a while and it will get stuck in error

**Comment by leastchaos** [comment]
![image](https://user-images.githubusercontent.com/64965782/134773044-c92c663d-411d-4ee6-b000-46c426cdbc67.png)

**Comment by nikspz** [comment]
hi @leastchaos Could you please provide steps to reproduce the bug on the GitHub page? 
https://github.com/CoinAlpha/hummingbot/issues/3714
Please also provide your config and log files 
Here you can find it:
https://docs.hummingbot.io/operation/config-files/#config-file-templates
https://docs.hummingbot.io/operation/log-files/

**Comment by nikspz** [comment]
Issue: Bot Failed to send an order to exchange after round for calculation

Steps to reproduce: 
1. use inventory skew, which is taking all remaining balance
2. If you are holding 1000.771 ASD, the bot round it up to 1001 
3. bot failed to create an order with order_amount 1001 (more than user assets)

**Comment by leastchaos** [comment]
As long as the dust token amount  result in the rounding up  to the nearest quantum amount should cause this issue on all exchanges on pure market making when it attempts to sell all token.
inventory skew may not need to be active.
E.g, sending 1.08 XCAD to ascendex run PMM which uses all available XCAD token. XCAD is rounded to one d (1.1).
or sending 100.8 EXRD which would result in rounding up to 101.
This works on any token  as i encountered DAO, EXRD, DAFI which I just sent token to exchange on kucoin and ascendex which result in errors.

**Comment by nikspz** [comment]
@leastchaos Could you please provide your config and log file? That could help to triage that issue as well. 

https://docs.hummingbot.io/operation/config-files/#config-file-templates
https://docs.hummingbot.io/operation/log-files/

**Comment by leastchaos** [comment]
I see that this issue is been addressed in this pull request, hence closing this issue.
https://github.com/CoinAlpha/hummingbot/pull/4370
