### ISSUE TITLE
Issue Report - Broken Link in Linux Installation Guide

### ISSUE THREAD

**Issue by surazgyawali** [CoinAlpha/hummingbot#373]
I would like to bring to your attention a small issue I encountered while following the Linux installation guide on your website.

In the section titled "Launch Hummingbot" under the Linux installation guide (https://hummingbot.org/installation/linux/), there is a link to the Quickstart Guide that appears to be broken. The link provided is https://hummingbot.org/installation/getting-started/custom-script/index.md, which leads to a 404 error.

**Comment by RC-13** [comment]
Thank you for reporting @surazgyawali, unfortunately, the hummingbot documentation is manage by Hummingbot foundation (https://github.com/hummingbot/hummingbot). I'll send this issue to foundation team members but it would be best if you re-open the ticket in the correct repository. 

I'll be closing this ticket as well.
