### ISSUE TITLE
Research / Investigate BitMart Exchange Connector

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#3742]
## Why

We encountered scenarios where the exchange's API docs do not have the complete information to build the connector. Sometimes we only find out while we are in the middle of development work, and the back and forth communication results in delays or major blockers.

## What

Look through their API docs to investigate / research to define how to build the connector or if there's any missing information that we need to coordinate with their team internally ahead of time.

API docs: https://developer-pro.bitmart.com/en/

## Acceptance Criteria

Create tasks required to complete the connector and link to the [BitMart connector epic](https://github.com/CoinAlpha/hummingbot/issues/3741). Similar to what we did to NDAX connector project.
Any difficulties found that can be a blocker must be registered on the epic.

**Comment by CrimsonJacket** [comment]
**Findings from initial investigation**
- REST API
  - Global API Base URL: https://api-cloud.bitmart.com
  - HongKong API Base URL: https://api-cloud.bitmart.news
  - Authentication procedure are detailed [here](https://developer-pro.bitmart.com/en/part2/auth.html)
     - Requires `accessKey`, `secretKey` and `memo` to be provided by user
  - API Service Status URL: https://api-cloud.bitmart.com/system/service
  - Trading Symbols in `ABC_XYZ` format
  - Trading Rules: Yes
  - OrderBook Depth: Yes
     - Max Depth 200
  - Account Balance(both avail and used balance): Yes
  - Create Order
     - Response returns exchange_order_id
     - No parameters to include client_order_id
  - Cancel Order
     - Response determines if an order has been successfully cancelled.
  - Get Order Details: Yes
     - Retrieves all orders(paginated) / Per order
  - Get User Trade History: Yes
     - Retrieves all trades(paginated) / Per order
  - Rate Limits: Yes
     - Remaining Rate Limit can be obtained from Response headers
- WebSocket API
   - Ping/Pong mechanism to maintain connection if no messages are received within a 20secs timeframe
   - Data compression is used for market data.
   - OrderBook Channel: Yes
      - Max depth: 400
   - User Trades: Yes
   - User Balance: **No**
