### ISSUE TITLE
Consolidate and improve on Async Throttler

### ISSUE THREAD

**Issue by Nullably** [CoinAlpha/hummingbot#3766]
**Why**
We have created a few different versions of async throttlers. We should consolidate them all and remove ones we no longer needed. The reason we didn't remove those before was due to not wanting to touch other parts of the systems which might break or is required much more testing.
These are all throttlers in order of the time they were created.
`hummingbot/core/utils/asyncio_throttle.py`
`hummingbot/core/api_throttler/api_request_context_base.py`
`hummingbot/core/api_throttler/api_throttler_base.py`
`hummingbot/core/api_throttler/fixed_rate_api_throttler.py`
`hummingbot/core/api_throttler/varied_rate_api_throttler.py`
`hummingbot/core/api_throttler/weighted_api_throttler.py`
`hummingbot/core/api_throttler/multi_limit_pool_throttler.py`

The `multi_limit_pool_throttler` has the most features and can be used in place of all the other throttlers.

**Refactors**
- Create a new directory `async_throttler`
- Place `multi_limit_pool_throttler` in it but rename it to `async_throttler.py` (with added improvements below)
- Remove all the other throttlers and data types that are no longer needed
- Add `TaskWeight` field to `MultiLimitsTaskLog` and remove weight from `CallRateLimit`
- Replace throttler in `CryptoCom` with this new throttler

**Improvements on async_throttler**
- `_lock` on the request context, should be passed in during init, not being a class member
- Use performance counter instead of `time.time()` to measure time passing more accurately.
- Rename `period_safety_margin` to `period_safety_margin_ratio`, the safe margin should always be considered as a ratio of the limit time interval and not in seconds.
- Applying limit checks on multiple timeframes - 1.5x and 2x (both time interval and limit) - on `_within_capacity`. This is bc. we don't know exactly the start and end time at which the exchanges count the number of requests, this prevents clustering around the edges.
- Report current rate limit usage upon `status` command for each current throttler - display current usage and limit.

**Definition of Done**
- Only one throttler left in the code base
- CryptoCom is updated with new throttler

**Comment by phbrgnomo** [comment]
@Nullably @dennisocana @CrimsonJacket @aarmoa Shouldn't this story be implemented before the #3666 and #3664?

**Comment by dennisocana** [comment]
@phbrgnomo that's correct

**Comment by phbrgnomo** [comment]
@Nullably will add "Defition of Done" to the story.

**Comment by Nullably** [comment]
This ticket will also address this #3156, we added `rate_limits_share_pct` in #3758 but only for Ascend Ex exchange. This ticket will make it available for all others.

**Comment by phbrgnomo** [comment]
After the update of the mentioned connectors on this story, and after QA test, each other connector will be listed as a separate update story.

After all connectors are updated, the unused throttlers will be removed from the codebase
