### ISSUE TITLE
Ascendex - Cancelled orders appearing as open orders on liquidity mining strategy

### ISSUE THREAD

**Issue by rxlxrxsx** [CoinAlpha/hummingbot#3767]
**Describe the bug**
When running the connector using liquidity mining strategy after some time, on random instances I see that it shows orders that were already cancelled from earlier showing on status, particularly orders with order age more than 10 seconds (order refresh time is currently set 10 to with order refresh tolerance disabled). There's also one order that shows an order age of n/a.

<img width="1424" alt="Screen Shot 2021-07-21 at 5 16 03 PM" src="https://user-images.githubusercontent.com/64377055/126465404-e6e2b1b5-3ea3-42c2-8717-1a41d0082995.png">

**Steps To Reproduce**
1. Run a liquidity mining strategy using Ascendex
2. Run on multiple markets (10 on my test) with order refresh time set to 10 and order refresh tolerance disabled
3. Run for quite some time then run `status` command, notice that every time you enter status it shows orders previously cancelled still showing as open orders. There are also orders that shows an order age of n/a

**Release version**
development-0.42.0

**Attachments**
Logs and config: [ascendex.zip](https://github.com/CoinAlpha/hummingbot/files/6854421/ascendex.zip)

**Comment by phbrgnomo** [comment]
@rxlxrxsx have you seen similar errors on other connectors?

**Comment by Nullably** [comment]
@rxlxrxsx Can you please test this again against the linked PR #3781. Thanks

**Comment by rxlxrxsx** [comment]
> @rxlxrxsx have you seen similar errors on other connectors?

Hi @phbrgnomo so far I haven't encountered this issue on the following connectors I've tried:

Binance
Kucoin
Gate.io
Huobi
OKEx

**Comment by dennisocana** [comment]
Fixed in version 0.42 release
