### ISSUE TITLE
[BUG] history/list trades in telegram does not work with many trades

### ISSUE THREAD

**Issue by carlolm** [CoinAlpha/hummingbot#377]
**Describe the bug**

If you have many trades in the history (observed in an instance with 80 trades), the `list trades` and `history` commands fail to show the trades in telegram.

The trades appear in the CLI, but are not sent to Telegram.

`list trades` => no output in telegram
`history` => no history of trades, but Performance table is sent to telegram

**Steps To Reproduce**

1. Setup an instance of hummingbot with telegram integration
2. Run a strategy and wait until you have completed many trades
3. try out `history` and `list trades` and observe in Telegram

**Screenshots**
// If applicable, add screenshots to help explain your problem.

**Release version**
dev-0.9.0 June 10, 2019

**Attachments**

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by carlolm** [comment]
Here is the error message:

![image](https://user-images.githubusercontent.com/12274903/59395519-3c8c7100-8d39-11e9-83a0-989d2411e3fd.png)

**Comment by ImTheDeveloper** [comment]
I've seen this error on bots I've made it may be the message length being too long. White space and hidden chars are all counted. I had to decide on a limit length and split multiple messages to get a full spam of my info out

**Comment by yzhang1994** [comment]
Fixed. Please test.
