### ISSUE TITLE
Cannot Load Configs with Capital Letters

### ISSUE THREAD

**Issue by mauhcs** [CoinAlpha/hummingbot#3780]
**Describe the bug**
// A clear and concise description of what the bug is.

Due to the following line:

https://github.com/CoinAlpha/hummingbot/blob/master/hummingbot/client/hummingbot_application.py#L131

when trying to load a config file (say `conf_liquid_mine_BTC_USDT.yml`), we get the following error message:

`No such file or directory: 'conf/conf_liquid_mine_btc_usdt.yml' `

The error message is technically correct, but the file name was modified from the input. 

# Suggestion:
Add a check of the type:
```python
if conf_file_name == conf_file_name.lower():
  all_is_good
else:
  raise RunTimeError("Conf file name should be all small letters")
```

This would at least prevent the user to enter a config file that he won't be able to load later.

**Comment by dennisocana** [comment]
Issue related to https://github.com/CoinAlpha/hummingbot/issues/2583

**Comment by phbrgnomo** [comment]
Closing due to similar issue #2583
