### ISSUE TITLE
Verify that USD volume reporting is working

### ISSUE THREAD

**Issue by mifeng** [CoinAlpha/hummingbot#3786]
# Why
Having metrics that indicate overall Hummingbot usage is important for business development. We implemented anonymized aggregated USD volume reporting a few releases ago, but the Datadog client dashboard does not seem to be updated for this metric.

# What
1. Verify that the client reports USD volume to our system for our top exchanges (LM exchanges)
2. Verify that our system passes this data correctly to Datadog
3. Adjust the client dashboard in Datadog to correctly track this data

**Comment by phbrgnomo** [comment]
This is an investigative story to make the engineering scope more clear.

- What is the current state of the datadog report
- create qa Maintainance process to regularly check if the data is being processed correctly

**Comment by RC-13** [comment]
- Confirming that data aggregation is sending the correct information in datadog. The test is done on our liquidity mining supported connectors, all data captured during testing matched the USDT value in the hummingbot.filled_usdt_volume metrics.
- Rate oracle source doesn't affect the aggregated data

Sample screenshot:
KuCoin sample data: USDT total is approximately equal to 19.43
![image](https://user-images.githubusercontent.com/57189990/127258527-e8c823eb-4c80-4b0a-a23b-1c13d2186693.png)
Binance sample data: USDT total is approximately equal to 62.13
![image](https://user-images.githubusercontent.com/57189990/127259246-5ec19dce-1c9a-4c33-bed3-e6c3d0db1c25.png)
AscendEx sample data: USDT total is approximately equal to 21.25
![image](https://user-images.githubusercontent.com/57189990/127262781-dc40f4db-dbdb-4e95-8811-8a256cc88c66.png)
Total USDT for all trades: USDT102.82
Datadog USDT total: USDT102.79

https://user-images.githubusercontent.com/57189990/127263766-0ecb6549-5554-4fd2-843f-4c94ece26aed.mov

**Comment by dennisocana** [comment]
@henry-hummingbot we discussed about adding this Datadog reporting to QA's monitoring routine to ensure we are correctly tracking the data.

**Comment by dennisocana** [comment]
Notion guide for verifying this data: https://www.notion.so/hummingbot/Datadog-for-Support-c0a4c59e6f304c54ad24a31fd58632fb

**Comment by dennisocana** [comment]
Everyone involved agrees that the data reported from the metric is correct. What needs fixing is the HB client dashboard that shows all the relevant graphs and metrics.

Will work with @phbrgnomo in creating a story for that task and how to improve in future iterations.
