### ISSUE TITLE
Pure market making - The value of the last_own_trade_price does not show when using status

### ISSUE THREAD

**Issue by rapcmia** [CoinAlpha/hummingbot#3799]
**Describe the bug**
While testing pure market making with price type, I've noticed that the `last_own_trade_price` feature does not show the value on status 

**Steps To Reproduce**

1. Create a pure market making strategy with price_type set to last_own_trade_price
1. Wait for the first order that will be filled
1. When there is a filled order, run status command

On the screenshot below, after the bid order was filled it does not show the value on the status which is working for the other price types. 
![lastowntradedprice](https://user-images.githubusercontent.com/73840223/127145689-43030833-3f50-4721-9091-122bcc3dbf20.png)

**Release version**
dev-0.42.0

**Attachments**
[logs.zip](https://github.com/CoinAlpha/hummingbot/files/6884994/logs.zip)

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ramu5y) by [Unito](https://www.unito.io)

**Comment by rxlxrxsx** [comment]
Confirmed that this issue doesn't happen anymore. Closing this ticket now.

<img width="1422" alt="Screen Shot 2021-12-06 at 3 38 04 PM" src="https://user-images.githubusercontent.com/64377055/144806353-447101db-2225-474b-9bfb-b8d3456bf152.png">
