### ISSUE TITLE
[BUG]Can not reconfig the bot

### ISSUE THREAD

**Issue by hongson1981** [CoinAlpha/hummingbot#382]
**Describe the bug**
Can not reconfig the bot

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file of conf_cross_exchange_market_making_strategy_0
2. Start the bot 
3. Import cross_exchange strategy
4. Enter command config  <any option>
Expected result : 
Should allow re-config the bot

Actual result:
Not allow re-config the bot, always display "Would you like to reconfigure the bot? (y/n) >>>", if you select 'y', it will display again and again until choose 'n'

**Screenshots**
![Screenshot from 2019-06-12 21-58-42](https://user-images.githubusercontent.com/29745336/59362390-90a94c80-8d5d-11e9-8761-fff61b15e2c4.png)

**Release version**
dev-0.9.0

**Attachments**
[conf_cross_exchange_market_making_strategy_0.txt](https://github.com/CoinAlpha/hummingbot/files/3281909/conf_cross_exchange_market_making_strategy_0.txt)
[conf_global.txt](https://github.com/CoinAlpha/hummingbot/files/3281910/conf_global.txt)

There is not log

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**
sonha145

**Comment by yzhang1994** [comment]
This should have been fixed.
