### ISSUE TITLE
Liquidity Mining - Unexpected error while requesting data from Hummingbot API

### ISSUE THREAD

**Issue by RC-13** [CoinAlpha/hummingbot#3823]
**Describe the bug**
When starting a liquidity mining strategy and running the status command, an error appears on the log pane and the miner section in the output window is not displayed. Despite getting the error, the bot still submits and cancels orders properly.
```python
2021-07-30 07:20:33,632 - 5266 - hummingbot.connector.parrot - ERROR - Unexpected error while requesting data from Hummingbot API.
Traceback (most recent call last):
  File "/home/clint_g/hb-general/hummingbot/connector/parrot.py", line 32, in get_campaign_summary
    campaigns = await get_active_campaigns(exchange, trading_pairs)
  File "/home/clint_g/hb-general/hummingbot/connector/parrot.py", line 70, in get_active_campaigns
    for market in campaign_retval["markets"]:
TypeError: string indices must be integers
```

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):
1. Create a liquidity mining strategy and set 2 or more liquidity mining campaigns for the market.
2. Start the strategy and run the status command or use CTRL + S

**Screenshots**
![LM error](https://user-images.githubusercontent.com/57189990/127577913-f48025af-e692-4180-ab46-ac2fc7693bf0.png)

**Release version**
0.41.0

**Attachments**
[logs_conf_liquidity_mining_2.log](https://github.com/CoinAlpha/hummingbot/files/6904160/logs_conf_liquidity_mining_2.log)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by PtrckM** [comment]
Fixed:

![image](https://user-images.githubusercontent.com/54516858/127726161-2206355b-0376-4415-a7b7-a81e18ae1e00.png)

![image](https://user-images.githubusercontent.com/54516858/127726153-cea806e3-891c-49bd-9739-b9634cc60987.png)
