### ISSUE TITLE
Add broker ID to Huobi connector

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#3837]
Below are the instructions for inserting specific parameters into the existing order placement API:

1. There’s an optional parameter `client-order-id` in the existing order placement API POST `/v1/order/orders/place` 
2. Put the field value to this parameter as follows:
-- Digit 1-10: Use the prefix provided by Huobi
-- Remaining digits: The string cannot be empty. Up to 54 characters
-- Must ensure the uniqueness within 24 hours
-- Allowed characters include letters (case sensitive), numbers, underscores (_), and dashes (-)

**NOTE**:

It is recommended to use `order-id` instead of `client-order-id` to cancel an order as the former is faster and more stable.

Instructions on the API access for orders:
- Chinese version: https://docs.huobigroup.com/docs/spot/v1/cn/#fd6ce2a756
- English version: https://docs.huobigroup.com/docs/spot/v1/en/#place-a-new-order

**NOTE**: 
* Third-party platforms must notify Huobi after making the modification and Huobi will verify the API module to make sure it’s correct.
* No need to add "-" in client-order-id (only a delimiter used for illustration)
Here’s an example: AXX6X2XXx8d38aef97cad3489c88a888f2327b626a

## Definition of Done

- [x] Order ID in the Hummingbot client logs should show the broker ID prefix
- [ ] Huobi to confirm our sample orders are getting picked up from their end

**Comment by aarmoa** [comment]
The broker id for Hummingbot is AA158bd339
