### ISSUE TITLE
[BUG]<low priority>Couldn't fetch new prices from Coincap

### ISSUE THREAD

**Issue by moraliang** [CoinAlpha/hummingbot#387]
**Describe the bug**
// A clear and concise description of what the bug is.
Running Arbitrage btw DDEX & IDEX

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:
```
#####################################
###   Arbitrage strategy config   ###
#####################################

# The following configuations are only required for the
# arbitrage strategy

# Exchange and token parameters
primary_market: ddex
secondary_market: idex
primary_market_symbol: WETH-DAI
secondary_market_symbol: DAI_ETH

# Minimum profitability target required to place an order
# Expressed in decimals: 0.01 = 1% target profit
min_profitability: 0.0006

trade_size_override: 0.0
top_depth_tolerance:
- - ^.+(USDT|USDC|USDS|DAI|PAX|TUSD)$
  - 1000
- - ^.+ETH$
  - 10
- - ^.+BTC$
  - 0.5
```
**Screenshots**
// If applicable, add screenshots to help explain your problem.
![Screen Shot 2019-06-12 at 5 44 06 PM](https://user-images.githubusercontent.com/14824365/59395641-ce947980-8d39-11e9-993e-9b3d696a08fe.png)

**Release version**
// Include your bot's version number (Can be found at the bottom left corner of your CLI).
0.9.0-dev

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 
[hummingbot_logs_2019-06-12-17-21-11.log](https://github.com/CoinAlpha/hummingbot/files/3283659/hummingbot_logs_2019-06-12-17-21-11.log)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**
**Optional: your ETH address:** (If you want to participate in the bug bounty)

**Comment by mifeng** [comment]
We are changing the default provider to CoinGecko, so this problem shouldn't persist anymore.
