### ISSUE TITLE
Some coins do not display $ value

### ISSUE THREAD

**Issue by alediemmee** [CoinAlpha/hummingbot#3870]
As the title says, some coins do not show their $ value.
Here, for example I have some XYM and it has not been showed on the HumminBot

![Screenshot_205](https://user-images.githubusercontent.com/44278487/128573752-41a741d4-256d-4372-9c13-2180f16e9284.png)

The Total $ is not correct, since the value of XYM has not been considered.

**Comment by PtrckM** [comment]
If you're using kucoin, try changing your current `rate_oracle_source` to `kucoin` and set `global_token` to `USDT`. For more info please visit https://docs.hummingbot.io/features/rate-oracle/
