### ISSUE TITLE
Integrate new `APIThrottler` into Binance Perpetual connector

### ISSUE THREAD

**Issue by phbrgnomo** [CoinAlpha/hummingbot#3891]
## Description

Refactor the Binance Perpetual connector to use the consolidated API Throttler

## Details

After the implementation of #3766, integrate the consolidated API Throttler into Binance Perpetual connector

Currently the Binance Perpetual connector uses the `asyncio_throttle.py`. This can only be removed after all connectors using it are refactored.

## Definition of Done

- [ ] Integrate the new Throttler on the Binance Perpetual connector

**Comment by dennisocana** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/hummingbot-5f340755c5e17300167a8f30/issues/CoinAlpha/hummingbot/3891?planning-poker) with ZenHub @aarmoa @CrimsonJacket @james-hummingbot @petioptrv @mhrvth @vic-en
