### ISSUE TITLE
Integrate new `APIThrottler` into Coinzoom connector

### ISSUE THREAD

**Issue by phbrgnomo** [CoinAlpha/hummingbot#3893]
## Description

Refactor the Coinzoom connector to use the consolidated API Throttler

## Details

After the implementation of #3766, integrate the consolidated API Throttler into Coinzoom connector

Currently, the Coinzoom connector uses the `asyncio_throttle.py`. This can only be removed after all connectors using it are refactored.

## Definition of Done

- [ ] Integrate the new Throttler on the Coinzoom connector

**Comment by dennisocana** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/hummingbot-5f340755c5e17300167a8f30/issues/CoinAlpha/hummingbot/3893?planning-poker) with ZenHub @aarmoa @CrimsonJacket @james-hummingbot @petioptrv @mhrvth @vic-en
