### ISSUE TITLE
Remove the remaining API Throttlers from the code base

### ISSUE THREAD

**Issue by phbrgnomo** [CoinAlpha/hummingbot#3895]
## Description

Remove all remaining unused code related to API throttles from the code base

## Details

After refactoring the existing connectors that make use of the old API Throttlers to the consolidated, clean up the code base.

The remaining files are everything left inside the `/hummingbot/core/api_throttler/` folder.

Note: this can only be done after there is no more connectors using the files inside that folder.

## Definition of done
- [ ] Removal of all old API Throttlers code

**Comment by dennisocana** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/hummingbot-5f340755c5e17300167a8f30/issues/CoinAlpha/hummingbot/3895?planning-poker) with ZenHub @aarmoa @CrimsonJacket @james-hummingbot @petioptrv @mhrvth @vic-en
