### ISSUE TITLE
[BUG]Discovery initialization error when Binance (taker) coin-pair is blank

### ISSUE THREAD

**Issue by Steve1943** [CoinAlpha/hummingbot#390]
**Describe the bug**
This Discovery mode of arbitrage fails to initialize correctly when forced to load all coin pairs for Binance - apparently due to an attribute error found for coin pair BNB/USDS.

**Steps To Reproduce**
Run Discover mode with configuration parameter 
target_symbol_2: []

The fault is indifferent to maker exchange or maker coin pair.

Here are the steps to reproduce the issue (see attachments in the section below):
1. see configuration file attached 
2. see console log attached
3. see session log attached

**Release version**
0.8.0

**Attachments**

[discovery_config.txt](https://github.com/CoinAlpha/hummingbot/files/3287078/discovery_config.txt)

[discovery_console_log.txt](https://github.com/CoinAlpha/hummingbot/files/3287079/discovery_console_log.txt)

[discovery_session_log_file.txt](https://github.com/CoinAlpha/hummingbot/files/3287080/discovery_session_log_file.txt)

**Optional: your discord username:**
Steve1943

**Optional: your ETH address:** (If you want to participate in the bug bounty)
0xf452895f879CB78A60af303BCF7B34E56A934Da8

**Comment by nkona** [comment]
Thanks for reporting! The issue was discovered along with similar problems as of this Monday and has already been fixed for the upcoming release.
