### ISSUE TITLE
Bybit Spot connector

### ISSUE THREAD

**Issue by phbrgnomo** [CoinAlpha/hummingbot#3940]
## Exchange Details ✏️

- **Name of exchange**: Bybit
- **Exchange URL**: https://www.bybit.com/
- **Link to API docs**: https://bybit-exchange.github.io/docs/inverse/#t-introduction
- **Type of exchange**: [*] Centralized [ ] Decentralized
- **Requester details**: Are you affiliated with the exchange? [ ] yes [*] no 
  - If yes, what is your role?

## Rationale / impact ✏️
(Describe your rationale for building this exchange connector, impact for hummingbot users/community)
Bybit's APIs are faster in my 'little' experience. I am actually surprised that no one has requested this yet as Bybit is pretty popular. It has -0.025% maker fees and doesn't require KYC so it's easy setup an account. 
## Additional information ✏️
(Provide any other useful information that may be helpful to know about this exchange)

---

⚠️ ***Note: do not modify below here***

## Developer notes

This feature request entails building a new exchange connector to allow Hummingbot to connect to an exchange that is currently not supported.

### Resources
- [Exchange connector developer guide](https://docs.hummingbot.io/developers/connectors/)
- [Discord forum](https://discord.hummingbot.io)

### Deliverables
1. A complete set of exchange connector files as listed [above](#developer-notes-resources).
2. Unit tests (see [existing unit tests](https://github.com/CoinAlpha/hummingbot/tree/master/test/integration)):
  1. Exchange market test ([example](https://github.com/CoinAlpha/hummingbot/blob/master/test/integration/test_binance_market.py))
  2. Order book tracker ([example](https://github.com/CoinAlpha/hummingbot/blob/master/test/integration/test_binance_order_book_tracker.py))
  3. User stream tracker ([example](https://github.com/CoinAlpha/hummingbot/blob/master/test/integration/test_binance_user_stream_tracker.py))
3. Documentation:
  1. Code commenting (particularly for any code that is materially different from the templates/examples)
  2. Any specific instructions for the use of that exchange connector ([example](https://docs.hummingbot.io/connectors/binance/))

### Required skills
- Python
- Previous Cython experience is a plus (optional)

**Comment by dennisocana** [comment]
Biz-dev confirmed we're not going to do this near-term since their exchange was just recently launched with five pairs.
