### ISSUE TITLE
Please add FTX - Derivatives connector and please make scripts available for avelanadella market making also later if you can please create the ability to run multiple bots at once.

### ISSUE THREAD

**Issue by MarcellThoth** [CoinAlpha/hummingbot#3948]
**Feature Suggestion**
// A succinct description of **how you want to achieve the desired behavior**.
// If you have looked at the code and know exactly what code changes are needed then please _consider submitting a pull request_ instead.

**Impact**
// A succinct description of **why you want the _desired behavior_** specified above.
The desired behavior will allow me to ...

**Additional context**

**Comment by dennisocana** [comment]
FTX perpetual connector is part of roadmap near term. Scripts will be reworked in the future - instead of using a separate script to customize the behavior of a strategy, we plan to implement the current functionality of scripts inside the strategy or its config files.
