### ISSUE TITLE
Redesign strategy developer tutorial

### ISSUE THREAD

**Issue by mifeng** [CoinAlpha/hummingbot#3949]
# Why

Enabling the community to create and customize Hummingbot strategies is important, but the resources that teach devs how to create strategies is lacking.

Currently, there exists some content created by a team of Cornell students for a Hummingbot developer tutorial in 2019. This consists of a few strategies with the `dev-` prefix, along with a few documentation pages such as https://docs.hummingbot.io/developers/tutorial/perform-trade/ and https://docs.hummingbot.io/developers/tutorial/simple-trade/.

However, this content is a bit too simple and doesn't really give users the knowledge they need to build their own strategies from scratch. Since we are starting the dYdX strategy bounty and other initiatives that promote custom strategies, we need to have better docs for strategy developers.

# What

Per discussion with @CrimsonJacket, the `twap` strategy is a better starting point for a tutorial. The overall idea is to teach users how the `twap` strategy works by walking them through the strategy.

The main concepts that users should understand after going through the tutorial are:

* How to set up the boilerplate files and folders that define a strategy
* How to configure input params
* How the `tick` function works
* How to quantize orders
* How to place orders
* How to listen for and handle order-related events
* How to format `status`

Structure:
I think we should add to [this page](https://docs.hummingbot.io/developers/strategies/twap/) sections that explain the concepts above in detail along with code blocks and links to code (since it's in same repo).

Unlike the initial developer tutorial, I don't think we need a tutorial that hand-holds users through each step. Rather, as long as we explain each concept and show how the code works, that should be sufficient.

# `vwap` followup tutorial?

Users who build market making strategies need to fetch order book data to make decisions, which `twap` doesn't do but `vwap` does. After finishing this first tutorial, I think we should create a followup that shows how that works using the `vwap` strategy.

 # Out of scope

We will create more tutorials later, so this one should only cover the basics that users need to know in order to create a bot on a spot centralized exchange. Not covered:

* Bot that trades on multiple exchanges
* DEXs
* Perpetual exchanges

# Definition of done

Finalize the concepts outlined and overall structure of the `twap` tutorial so that we can begin writing it.

**Comment by CrimsonJacket** [comment]
@mifeng I think the scope of the tutorial already covers a substantial portion of strategy base. I agree that explaining how to obtain the order book would be useful and I feel we can just work it into the twap tutorial.

**Comment by mifeng** [comment]
Cool I will start working on it this weekend and hand off to you
afterwards.

**Comment by mifeng** [comment]
@CrimsonJacket to finish this ticket, please add to the list of general concepts that should be in the tutorial. See
https://github.com/CoinAlpha/hummingbot/pull/4047

**Comment by mifeng** [comment]
Closing this issue as I have merged this branch into the `feat/upgrade-mkdocs` branch which has general documentation updates for the 0.44 release
