### ISSUE TITLE
[BUG] Redundant orders created in IDEX that bot was unaware of

### ISSUE THREAD

**Issue by mifeng** [CoinAlpha/hummingbot#397]
**Describe the bug**
Running the pure MM strategy on IDEX, the bot got into a situation in which orders were placed on the exchange, but HB said there were no active maker orders.

This only happened after about 12 hours of running the bot on IDEX.

**Screenshots**

Hummingbot:
![Screen Shot 2019-06-15 at 11 46 01 AM](https://user-images.githubusercontent.com/1795030/59555169-3e397d00-8f63-11e9-8137-6db9b3bb9456.png)

IDEX after stopping bot:
![Screen Shot 2019-06-15 at 11 42 33 AM](https://user-images.githubusercontent.com/1795030/59555172-4bef0280-8f63-11e9-8844-b0a78a372983.png)

**Release version**
dev-0.9.0

**Attachments**

Logs:
[hummingbot_logs_2019-06-14-20-50-43.log](https://github.com/CoinAlpha/hummingbot/files/3293435/hummingbot_logs_2019-06-14-20-50-43.log)

Configs:
```
# Exchange and token parameters
maker_market: idex
maker_market_symbol: ETH_IDEX

# size of each order
order_amount: 1351.0

# Time in seconds before cancelling and rerunning strategy
# If tick size is 60, the bot cancels active orders and reruns after a minute
cancel_order_wait_time: 30.0

# How far away from mid price to place the bid order
# Expressed in decimals : 0.01 = 1% away from mid price at that time
# Example if mid price is 100 and bid_place threshold is 0.01
# Your bid is placed at 99
bid_place_threshold: 0.015

# How far away from mid price to place the ask order
# Expressed in decimals : 0.01 = 1% away from mid price at that time
# Example if mid price is 100 and ask_place threshold is 0.01
# Your bid is placed at 101
ask_place_threshold: 0.01
```

**Comment by mifeng** [comment]
I reproduced this again...

In this case, the bot lost track of IDEX orders sometime after the last tracked filled buy order on 6/16 06:17. It placed a bunch of redundant sell orders on IDEX. Some of these sell orders were filled (see the IDEX trade history), while others were left on the order book after I stopped the bot.

`history` screenshot:
![Screen Shot 2019-06-16 at 12 22 45 PM](https://user-images.githubusercontent.com/1795030/59568626-2d0b7180-9032-11e9-8d0f-4077e1506330.png)

Trade history from IDEX:
[idex_trade_history.xlsx](https://github.com/CoinAlpha/hummingbot/files/3294492/idex_trade_history.xlsx)

Logs:
[dup orders 3.log](https://github.com/CoinAlpha/hummingbot/files/3294489/dup.orders.3.log)

**Comment by chowryan** [comment]
this was / is still a bug on IDEX's side and they are still working on a fix. I'll continue following this issue on their Discord channel.

**Comment by carlolm** [comment]
Is this still an issue?  @mifeng
As of the IDEX fixes on June 22-23 weekend, I haven't seen these errors.

**Comment by chowryan** [comment]
IDEX api was unstable that weekend but they fixed it.
