### ISSUE TITLE
Write gateway v2 improvement proposals

### ISSUE THREAD

**Issue by martinkou** [CoinAlpha/hummingbot#3989]
I've started a draft for gateway v2 improvements on https://www.notion.so/hummingbot/Gateway-v2-Improvements-8eb63b53bed241e38ec9af8127269415. I should finish the proposals and create task tickets based on the full proposal.

**Comment by martinkou** [comment]
The chapter "Developer Experience" is now ready for review. This marks the completion of the initial version of the gateway v2 proposals.

https://www.notion.so/hummingbot/Developer-Experience-f40a4e16c3304c15a91619c91ddea2ce

**Comment by dennisocana** [comment]
Please discuss today if the story can be closed before the end of the current sprint this weekend.

**Comment by mifeng** [comment]
The spec is finalized: https://www.notion.so/hummingbot/Gateway-v2-Improvements-8eb63b53bed241e38ec9af8127269415
