### ISSUE TITLE
Integrate ESLint to gateway-v2, and set up Github workflow to automate linting process

### ISSUE THREAD

**Issue by martinkou** [CoinAlpha/hummingbot#3994]
## Why

We've been having endemic coding style issues with the existing gateway API code, where basic coding style inconsistencies, e.g. whether to use semicolon or not - can still be easily spotted.

For gateway-v2, we should strive to have a consistent coding style, to make it easy for the community to work on gateway-v2 code.

## What

* Integrate ESLint, or a better linter, to gateway-v2 codebase
* Add the linting process as Github workflow

**Comment by phbrgnomo** [comment]
Still need to be done:
- Add the linting process as Github workflow
