### ISSUE TITLE
Write blog post on Hummingbot gateway architecture

### ISSUE THREAD

**Issue by martinkou** [CoinAlpha/hummingbot#3998]
## Why

Had a brief chat w/ Yingdan yesterday. We're going to publish a blog post about Hummingbot gateway architecture before the end of this month, in a similar manner to the Hummingbot architecture blog posts before.

## What

* Write blog post on gateway architecture.

**Comment by martinkou** [comment]
I've splitting the blog posts to 2 parts - similar to how the Hummingbot architecture series was made, because of the overall length of the specs.

Part 1 is complete as of today. It can be found inside the "Part 1 of the blog series" separators in the following document.

 https://www.notion.so/hummingbot/Hummingbot-Gateway-v2-Architecture-9794bfe2e8b542f8873908b4fac646f3

**Comment by martinkou** [comment]
Part 2 is complete as of today. I've modified the "Availability and Timeline" chapter to address the comments I got during today's gateway standup.

**Comment by mifeng** [comment]
Looks good - I made a few formatting and minor text changes. @phbrgnomo please publish on the blog.

**Comment by phbrgnomo** [comment]
Articles published, closing story.
