### ISSUE TITLE
Uniswap V3 strategy simplification

### ISSUE THREAD

**Issue by mifeng** [CoinAlpha/hummingbot#3999]
## Description

Rework of the `uniswap_v3_lp` trading logic reducing the complexity.

## Details

The strategy logic must be:
Obs: the variables mentioned are for reference only. They don't need to be named the same way.

**When creating the strategy (`create`)**

Prompts:
- Enter the trading pair
- Fee Tier of the pool (low/medium/high)
- Top price bound (in %) relative to market price (`top_bound_spread`)
- Lower price bound (in %) relative to market price (`lower_bound_spread`)
- Base token amount to add (`base_token_amount`)
- Quote token amount to add (`quote_token_amount`)

- Bot will calculate `top_bound_price` and `lower_bound_price` based on the current `market_price` and the spreads entered by the user

**When starting the strategy (`start`)
- The bot will look for information about the pool, and if it is a valid pool
  - If the pool doesn't exist, warn the user and stop the strategy
- If the pool is valid, the bot will create two starting positions:
  1. The sell position with:
      - Amount of tokens added to the position = `base_token_amount`
      - Top price bound = `top_bound_price`
      - Lower price bound = current market price
  2. The buy position with:
      - Amount of tokens added to the position = `quote_token_amount`
      - Top price bound = current market price
      - Lower price bound = `lower_bound_price`

![image.png](https://images.zenhubusercontent.com/5f64254ca13ff3717cc3a0c5/5f226e75-0ed3-4a56-a80e-9c6d86f3cba7)

**As the strategy is running**
- The bot will monitor the current price of the pool, with two possible conditions to trigger a new position creation:

1. Price goes above `top_bound_price`
```python
if market_price > top_price_bound
  new_position_top_price = market_price + (market_price * top_bound_spread)
  new_position_lower_price = market_price
  new_position_size = base_token_amount
  create_new_position(new_position_top_price, new_position_lower_price, new_position_size)
  top_bound_price = new_position_top_price // The new upper bound becomes the upper bound of the new position
```
![image.png](https://images.zenhubusercontent.com/5f64254ca13ff3717cc3a0c5/d8500163-d3d9-4ca1-b8bd-410f1eb213ca)

2. Price goes below `lower_bound_price`
```python
if market_price < lower_bound_price
  new_position_top_price = market_price
  new_position_lower_price = market_price - (market_price * lower_bound_spread)
  new_position_size = base_token_amount
  create_new_position(new_position_top_price, new_position_lower_price, new_position_size)
  lower_bound_price = new_position_lower_price // The new lower bound becomes the upper bound of the new position
```
![image.png](https://images.zenhubusercontent.com/5f64254ca13ff3717cc3a0c5/0d0bd3f7-2a26-4c60-ad2c-6a8762013e45)

**Outside of the Scope**
The Strategy will not:
- Remove liquidity positions
- Modify existing liquidity positions
 
**Status report**
*OBS: If there isn't enough time to implement this, a separate task will be created to handle the `status` information*

Each liquidity position must be shown separated on the `status` report

On the `status` report, the following information must be shown for each of the created positions:

- The top and lower price bound
- The starting value of the initial position (value of the tokens locked on the position based on the **market price at the moment the position was created**) in USD
- The current value of the position (value of the tokens locked on the position based on the **current market price**) in USD
- Total value of uncollected fees in USD
- Current return of the position, (Total return) =  ( Current value of the position ) + ( uncollected fees ) - ( Initial value of the position) in USD
- % return of the positions ( Total return ) / (Initial value)

## Definition of Done

- Bot is able to create the initial positions
- Bot is able to create new positions when the market price moves outside the initial price bounds
- Bot redefines the new price bounds that will be used as a reference for future price changes and new position creations

**Comment by RC-13** [comment]
Closing story, confirming definition of done are met.
