### ISSUE TITLE
Avellaneda Strategy crashing after several hours on binance

### ISSUE THREAD

**Issue by pppietsch** [CoinAlpha/hummingbot#4007]
**Describe the bug**
Hummingbot bug in the Avellaneda Market Making Strategy: 
Not for the first time my bot hangs itself up after running for several hours.

2021-08-26 00:14:07,555: Strategy starts
Shortly after 8am errors start

2021-08-26 08:01:02,496 - 9436 - hummingbot.connector.exchange.binance.binance_exchange - WARNING - APIError(code=-1013): Filter failure: PRICE_FILTER

Full log is attached.

I cannot exclude there there was a problem with my internet, but the bot does not recover and keeps placing some orders, while others seem to be out of sync. 
[logs_conf_avellaneda_market_making.zip](https://github.com/CoinAlpha/hummingbot/files/7061345/logs_conf_avellaneda_market_making.zip)

**Comment by RC-13** [comment]
We tried to test this behavior again using Mac binary (4 hrs test) and Windows binary (2 hrs test) and bot did not crash. Closing this ticket, we can re-open if the issue will appear in the future.
