### ISSUE TITLE
Mock "Out of Gas" transaction error

### ISSUE THREAD

**Issue by phbrgnomo** [CoinAlpha/hummingbot#4017]
Full details on the related Epic #3991 

Reference for the error: https://metamask.zendesk.com/hc/en-us/articles/360038849792-Why-did-my-transaction-fail-with-an-Out-of-Gas-error-How-can-I-fix-it-

Tx for reference: https://etherscan.io/tx/0x2faeb1aa55f96c1db55f643a8cf19b0f76bf091d0b7d1b068d2e829414576362

**Comment by willyPat** [comment]
This is on hold because we need a definition on the messages that the client is going to interchange with the gateway. Right now gateway doesn't care about the result of the transaction it just wrap the message coming from the blockhain and send it to the client.

**Comment by mifeng** [comment]
Need to define what characterized "out of gas" from the TransactionReceipt: gasUsed >= gasLimit

@vic-en : "insufficent gas" error in the `logs` field of TransactionReceipt, and ethers can decode it.

**Comment by martinkou** [comment]
Seems like that decoding the logs to discover the actual error is rather non-trivial with ethers.js at the moment. So let's just do this for now..

If a transaction has status == 0 and the gas used field is more than 90% of the maximum gas allowed, then we treat it as not enough gas.

**Comment by martinkou** [comment]
The acceptance criteria here is, Willy should capture a failed transaction from etherscan with the out of gas error. Then, create a mock to return that error, and test that the `/poll` API is returning the appropriate error codes and messages for this particular error receipt.

**Comment by willyPat** [comment]
@martinkou using the transaction provided by Paulo in the issue description I get this receipt.
Gas Used and Status and right there, but I dont know where/how to get "maximum gas allowed".

`{
  "to": "0xf650C3d88D12dB855b8bf7D11Be6C55A4e07dCC9",
  "from": "0x58B7AA5bEd029A5D149E108Ad4bdF836D10F70Ea",
  "contractAddress": null,
  "transactionIndex": 44,
  "gasUsed": { "type": "BigNumber", "hex": "0x033111" },
  "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "blockHash": "0xf1780cff8a16b790fcf06bccb9ad09a4ab1a037beeb031c92c45142176cf765b",
  "transactionHash": "0x2faeb1aa55f96c1db55f643a8cf19b0f76bf091d0b7d1b068d2e829414576362",
  "logs": [],
  "blockNumber": 11156112,
  "confirmations": 1991737,
  "cumulativeGasUsed": { "type": "BigNumber", "hex": "0x44787d" },
  "effectiveGasPrice": { "type": "BigNumber", "hex": "0x0773594000" },
  "status": 0,
  "type": 0,
  "byzantium": true
}`

**Comment by willyPat** [comment]
Additionally, according to the API specs if we get an out of gas we should treat that as an error and retrieve a HTTP 503 with and error code and a message. Aren't we losing relevant information contained in the failed transaction receipt that could be meaningful to the client? (like the gasUsed). 
Maybe we want to extract the relevant info and add that to the error object or just add the complete receipt in the response ( errorCode, message, receipt )

**Comment by vic-en** [comment]
@willyPat @martinkou Sample error from ethers library when we try to send a transaction to the network with insufficient gas:
```
insufficient funds for intrinsic transaction cost (error={"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":55,\"error\":{\"code\":-32000,\"message\":\"insufficient funds for gas * price + value\"}}","error":{"code":-32000},"requestBody":"{\"method\":\"eth_sendRawTransaction\",\"params\":[\"0x02f90353013585342770c00085342770c00083030ff094ba12222222228d8ba445958a75a0704d566bf2c880b902e4945bcec9000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001200000000000000000000000000000000000000000000000000000000000000220000000000000000000000000efb7be8631d154d4c0ad8676fec0897b2894fe8f0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000efb7be8631d154d4c0ad8676fec0897b2894fe8f00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000280ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff00000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000020c6a5032dc4bf638e15b4a66bc718ba7ba474ff730002000000000000000000040000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000038d7ea4c6800000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc20000000000000000000000006b175474e89094c44da98b954eedeac495271d0f000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000038d7ea4c680000000000000000000000000000000000000000000000000003261cf9bf2fc2b5dc001a0b73390de23a6ab4c50c959012b54ed43b47cef4e2ebb67f07f3afc539d10d3d5a05ce25e708a971eb047cf445a0f07c25e20754ed566d667b3fb042145dfc32126\"],\"id\":55,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"https://mainnet.infura.io/v3/117bfd0769f54bd2b91f50d2b1c19f9a"}, method="sendTransaction", transaction="0x02f90353013585342770c00085342770c00083030ff094ba12222222228d8ba445958a75a0704d566bf2c880b902e4945bcec9000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001200000000000000000000000000000000000000000000000000000000000000220000000000000000000000000efb7be8631d154d4c0ad8676fec0897b2894fe8f0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000efb7be8631d154d4c0ad8676fec0897b2894fe8f00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000280ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff00000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000020c6a5032dc4bf638e15b4a66bc718ba7ba474ff730002000000000000000000040000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000038d7ea4c6800000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc20000000000000000000000006b175474e89094c44da98b954eedeac495271d0f000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000038d7ea4c680000000000000000000000000000000000000000000000000003261cf9bf2fc2b5dc001a0b73390de23a6ab4c50c959012b54ed43b47cef4e2ebb67f07f3afc539d10d3d5a05ce25e708a971eb047cf445a0f07c25e20754ed566d667b3fb042145dfc32126", code=INSUFFICIENT_FUNDS, version=providers/5.4.1)
```
