### ISSUE TITLE
[BUG] Problem with Binance API CALL ERROR

### ISSUE THREAD

**Issue by locoalien** [CoinAlpha/hummingbot#402]
**Describe the bug**
problems with Binance when setting up the robot.

An error is encountered when invoking the API, as can be seen in the following log: [View log](https://media.discordapp.net/attachments/563462222878212098/590740923978350612/error3.png?width=960&height=455)

**Steps To Reproduce**

Config:
1. Strategy: pure_market_marking
2. Exchange: Binance
3. Correct API Key and Secret Key

**Screenshots**
screenshots to help explain your problem.
![error2](https://user-images.githubusercontent.com/1004466/59734772-58e84c00-9218-11e9-8865-02504169a8cd.png)

Log:
![error3](https://user-images.githubusercontent.com/1004466/59734778-5ede2d00-9218-11e9-8d49-95f03fac0b70.png)

**Release version**
Client Version 0.8.1.

**Attachments**
[hummingbot_logs_2019-06-18-21-28-49.log](https://github.com/CoinAlpha/hummingbot/files/3304293/hummingbot_logs_2019-06-18-21-28-49.log)

**Discord username:** locoalien

**Comment by nkona** [comment]
When looking through the log files, the issue is Binance's API passing an error with code -2011, which means "CANCEL_REJECTED". This appears to be a timing problem, where Hummingbot is attempting to cancel and replace the order but it has been filled at the same time on Binance. 

Such events are more likely to occur when you refresh orders frequently: what interval did you configure this to? Also, this warning on its own should not be a problem, unless you are noticing that there are still live orders after you get this error (i.e. there are extra active orders after refreshing). We'll take a look at it and likely treat this API response as order filled if there are no other issues.

**Comment by locoalien** [comment]
> When looking through the log files, the issue is Binance's API passing an error with code -2011, which means "CANCEL_REJECTED". This appears to be a timing problem, where Hummingbot is attempting to cancel and replace the order but it has been filled at the same time on Binance.
> 
> Such events are more likely to occur when you refresh orders frequently: what interval did you configure this to? Also, this warning on its own should not be a problem, unless you are noticing that there are still live orders after you get this error (i.e. there are extra active orders after refreshing). We'll take a look at it and likely treat this API response as order filled if there are no other issues.

thanks for the reply. The time interval is 360 seconds. When entering Binance, it is not reflected or created any order, also discard that it is a network problem.

I think there is some additional problem, but I could not find the cause. I do not know if he suddenly has another idea that this problem could be.

**Comment by nkona** [comment]
When you say that there are no reflected or created orders in Binance, do you mean that there are no active orders at all while the bot is running? Also, did you notice if any orders were filled or not? If they were, were they noted in your past transactions on Binance?

Finally, did you notice anything else wrong with how the bot was operating besides the error messages and a lack of orders on Binance?

**Comment by testzoneWorld** [comment]
I have the same problem as well. Also same configuration. 
[hummingbot_logs_2019-06-20-10-36-23.txt](https://github.com/CoinAlpha/hummingbot/files/3309976/hummingbot_logs_2019-06-20-10-36-23.txt)

**Comment by mifeng** [comment]
@locoalien @testzoneWorld What OS (Mac, Windows, Linux), environment (local / cloud), and install path (source / Docker) did you use?

Also, please include your strategy config file.

**Comment by mifeng** [comment]
I found the source of this issue. The minimum order size for most trading pairs on Binance is $10 (or 10 USDT), so this means that any order for <500 ONE will fail.

We will see what we can do to handle this error more gracefully.

**Comment by veecos2** [comment]
I had actually changed the logic in the staggered/multiple orders so that the bot takes this into account. I don't see any order placements in the latest branch.

**Comment by locoalien** [comment]
@mifeng thanks for your reply,  I will try that with 600 one

**Comment by locoalien** [comment]
> I found the source of this issue. The minimum order size for most trading pairs on Binance is $10 (or 10 USDT), so this means that any order for <500 ONE will fail.
> 
> We will see what we can do to handle this error more gracefully.

Thanks so much! this is the problem, now it's correct!!
![image](https://user-images.githubusercontent.com/1004466/59958446-77df1c00-946c-11e9-91cc-586ecf0fd6ea.png)

**Comment by mifeng** [comment]
@locoalien Thanks for reporting this bug. Since we have now fixed it, it's eligible for our bug bounty program. If you let me know your ETH address, I will send you 0.1 ETH.
