### ISSUE TITLE
Add `maxFeePerGas` and `maxPriorityFeePerGas` for transacting API calls like `/approve`

### ISSUE THREAD

**Issue by martinkou** [CoinAlpha/hummingbot#4030]
## Why
When there are stuck transactions, we want to be able to either cancel the stuck transactions, or re-send them with higher gas fees. This ticket concerns the latter case.

After the basic `nonce` parameter is implemented, the next step is to allow specifying a higher gas fee to re-send transactions.

`maxFeePerGas` is the traditional gas price in Ethereum, and could generally be used in other similar networks as well.

`maxPriorityFeePerGas` is a new feature from EIP-1559, which allows more precise control for how much tips to offer to EIP-1559 EVM nodes.

## What
* Add `maxFeePerGas` as an optional parameter to transacting APIs.
* Add `maxPriorityFeePerGas` as an optional parameter to transacting APIs.

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ran0tc) by [Unito](https://www.unito.io)

**Comment by phbrgnomo** [comment]
This must be included on all requests that create a tx.
