### ISSUE TITLE
Core and community connectors / strategies

### ISSUE THREAD

**Issue by phbrgnomo** [CoinAlpha/hummingbot#4034]
## Details

As discussed, we will be classifying connectors and strategies into *Core* and *Community*

- Core connectors and strategies will be actively maintained and improved by the Hummingbot team
- Community connectors and strategies must be maintained and improved by the community

## Definiton of Done

- [ ] Definition of what is *core* and what is *community*
- [ ] Documentation is updated

**Comment by dennisocana** [comment]
During yesterday's discussion with @mifeng , he will do this as part of the changes he's making in this branch https://github.com/CoinAlpha/hummingbot/pull/4091.

It will be indicated in the overview section of the docs the difference between a core and community as well as identify which connectors / strategies will fit into each category.

**Comment by dennisocana** [comment]
We won't be using core vs. community labels anymore to separate them. It will be specified who is the maintainer for every strategy and connector in their respective docs page.
