### ISSUE TITLE
Core and Community connectors and strategies

### ISSUE THREAD

**Issue by phbrgnomo** [CoinAlpha/hummingbot#4035]
## Description

Separate both on documentation and inside the code base the separation between Core and Community connectors/strategies

## Details

As discussed, the code base related to *connectors* and *strategies* will be separated in two types:

- **Core** - Connectors & Strategies that will be actively maintained and improved by the Hummingbot team
- **Community** - Connectors & Strategies will be maintained and improved by the community

This separation must be shown in:

- Documentation (https://docs.hummingbot.io/) - Description of wich ones are *Core* and wich one are *Community*
- Code base - Inside the code base, this separation must be clear, preferably with some kind of "classification tag" that allows other parts of the code identify them as *Core* or *Community*
- Client interface - This separation must also be shown on the client interface, preferably through clear menus

**Comment by dennisocana** [comment]
As mentioned in this story https://github.com/CoinAlpha/hummingbot/issues/4034#issuecomment-922582264 we will no longer use core and community for categorizing the connectors and strategies. Closing epic and other related stories.
