### ISSUE TITLE
Create menu for `connect` command

### ISSUE THREAD

**Issue by phbrgnomo** [CoinAlpha/hummingbot#4039]
## Description

Create a menu interface for the `connect` command

## Details

Similar to the `config` command (#4038), the `connect` command must have a  menu interface created using `prompt-toolkit` that allows users to quickly find the connector the user want.

The connectors listed must be separated as the following tree:

- Core Connectors
|- Spot Connectors
|- Perpetual Connectors
|- DEX Connectors
- Community Connectors
|- Spot Connectors
|- Perpetual Connectors
|- DEX Connectors

The separation is defined by #4034, and must follow the most updated documentation (https://docs.hummingbot.io/connectors/)

Similar to #4038, the menu must be accessed with the use of `connect --menu`

## Definition of Done

[] `--menu` modifier added to the `connect` command
[] Menu with the connector classification mentioned above

**Comment by mifeng** [comment]
I'd like to put this and the other menu stories on hold, because I'm not sure that they address serious user needs. In addition, this change would increase maintenance burden since changing the connector structure would need to occur in both the documentation and in the codebase.

**Comment by phbrgnomo** [comment]
Closing this, since we are creating other detailed stories for UI/UX changes
