### ISSUE TITLE
Add documentation details for the events.py file

### ISSUE THREAD

**Issue by phbrgnomo** [CoinAlpha/hummingbot#4042]
## Description

Create a Documentation section detailing the existing classes on the `events.py` file and what is their function

Use this as a reference: https://www.mql5.com/en/docs/event_handlers/onbookevent

## Definition of done

- [ ] Add a description for each class inside the `events.py` file

**Comment by mifeng** [comment]
This story needs more detail on why is this documentation is needed and how developers will use it afterwards.

**Comment by dennisocana** [comment]
Closing for now, refer to https://github.com/CoinAlpha/hummingbot/issues/4162 for more details about developer documentation tasks.
