### ISSUE TITLE
Unable to start trading on some dydx markets

### ISSUE THREAD

**Issue by vic-en** [CoinAlpha/hummingbot#4089]
**Describe the bug**
The dydx connector reports errors when there's an attempt to place orders for some pairs. For some others, it doesn't even attempt to place orders at all.

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up Perpetual MM strategy with dydx perp as connector.
2. Use markets like AAVE-USD or UNI-USD
3. Then start strategy and watch it raise an error or do nothing depending on market.
...

**Screenshots**
Errors with AAVE-USD:
![AAVE](https://user-images.githubusercontent.com/31972210/132005427-0e88943c-85fa-4320-a853-f53922527266.png)

Errors with DOT-USD:
![DOT](https://user-images.githubusercontent.com/31972210/132005439-b8cd0968-1e24-412f-ba6f-7cfcc937986a.png)

**Release version**
dev-0.44.0

**Attachments**
[Uploading logs_conf_perpetual_market_making_5.log…]()

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by RC-13** [comment]
@vic-en we had this issue before and it was resolve by this PR #3734 , I just check those pair and it's working on my side.
![image](https://user-images.githubusercontent.com/57189990/132010634-f0b9a34d-c3e1-4b31-9526-5aed1ee9650a.png)
![image](https://user-images.githubusercontent.com/57189990/132010835-184d2352-1d41-4dbc-83ec-8dfc36059944.png)

**Comment by vic-en** [comment]
confirmed that issue is resolved. Will close this issue ticket now.
