### ISSUE TITLE
[BUG] Cross exchange market making - Unexpected error running clock tick 

### ISSUE THREAD

**Issue by gruberx** [CoinAlpha/hummingbot#409]
Describe the bug
I try to configure Cross exchange market making and get the error "Unexpected error running clock tick"

Steps To Reproduce
Strategy: cross_exchange_market_making
Exchange: tried several variants
1. taker: Binance, maker: RadarRelay
2. taker: Binance, maker: DDEX

Screenshots
![screenshot](https://user-images.githubusercontent.com/35637653/59808017-13ed1400-9303-11e9-946d-ffb51247b6d0.jpg)

System
HyperV guest
Ubuntu 18.04
hummingbot from source release 0.8.1
For sync VM clocks use chrony [https://help.ubuntu.com/lts/serverguide/NTP.html](https://help.ubuntu.com/lts/serverguide/NTP.html)

Attachments
[configs.zip](https://github.com/CoinAlpha/hummingbot/files/3308238/configs.zip)
[RR_hummingbot_logs_2019-06-20-01-48-34.log](https://github.com/CoinAlpha/hummingbot/files/3308241/RR_hummingbot_logs_2019-06-20-01-48-34.log)
[DDEX_hummingbot_logs_2019-06-19-13-01-49.log](https://github.com/CoinAlpha/hummingbot/files/3308245/DDEX_hummingbot_logs_2019-06-19-13-01-49.log)

discord username: gruberx

**Comment by nkona** [comment]
Hey @gruberx! Just tested on the latest dev and public versions with the configurations you used and there doesn't seem to be a clock tick issue. Given this, I'd guess it's a problem with your VM sync clock. Can you check if it works when you reset your VM clock to the Linux default? Alternatively, can you try installing it from Docker and see if that circumvents the problem?

**Comment by gruberx** [comment]
Hi @nkona! I originally ran Linux default time synchronization. May affect location? Server is in Germany and the time is synchronized with ntp servers zone de. When I tested the arbitration strategy there was no such error.
I will try the Docker later and let you know the result.

**Comment by chowryan** [comment]
looks like RLC-WETH was removed from RadarRelay (seems like a lot of pairs are gone now). We should probably clean up the error though.

**Comment by chowryan** [comment]
for DDEX, there's basically no orders for RLC-WETH (https://ddex.io/trade/RLC-WETH). You should never use these strategies on orderbooks that have extremely low volume since the price can fluctuate too much.

**Comment by chowryan** [comment]
closing this issue since it should be fixed. Please reopen if its not, thanks!
