### ISSUE TITLE
Documentation for `HangingOrdersTracker` class

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#4112]
## Why

The `HangingOrdersTracker` class is one of the two clear components (the other is `APIThrottler`) that we have individualized even in the code that are going to be used as they are and something that we want to make it usable by the community.

## What

Add to developer documentation and include as much information as possible about **how to use** this class.

**Comment by mifeng** [comment]
@petioptrv please use the new `development` branch which has the new docs structure. I recommend adding this page as a guide in `/developers/strategies`

![Screen Shot 2021-09-28 at 9.46.54 AM.png](https://images.zenhubusercontent.com/545072957c6ccc6277a5c098/ec267b22-6ca1-4a41-b1a1-0312b018bd2a)
