### ISSUE TITLE
Bitmart: Random inconsistent order creation due to balance delay

### ISSUE THREAD

**Issue by RC-13** [CoinAlpha/hummingbot#4115]
**Describe the bug**
Opening ticket for tracking:
- There are random instances that the order creation is inconsistent. The possible reason for this is due to Bitmart not having websocket update for balance as mentioned in PR #3856

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):
1. Create a pure market making strategy and set order refresh time to 30 sec for faster result.
2. Set a multiple order level, single level will do but may take more time.
3. Start the strategy and run `status --live`
4. Monitor the order creation.
...

**Screenshots**

https://user-images.githubusercontent.com/57189990/132447195-6d9bc81e-6e17-4af0-aaee-199f93601aba.mov

**Release version**
0.44.0

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by aarmoa** [comment]
This is caused by an error in the connector implementation. BitMart does not provide online balance updates through websocket, but the connector was not configure to estimate balance. We should have requested this from the start when validating the initial PR.
