### ISSUE TITLE
NDAX: Incorrect fees calculation

### ISSUE THREAD

**Issue by gerald-hb** [CoinAlpha/hummingbot#4118]
**Describe the bug**
This issue is reported by user in Zendesk Chat. Incorrect fees calculation. NDAX 0.2% transaction fee reflects as 2% in the bots performance history.

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: ...
![image](https://user-images.githubusercontent.com/84826167/132469486-cabe6dbe-2c81-41af-9fd1-58b8abfc5984.png)

2. Start the bot and check out the fees calculation
...

**Screenshots**
![image](https://user-images.githubusercontent.com/84826167/132469624-b65351e9-9d04-4302-9828-53149b76ee95.png)

Orderbook has the correct transaction fee
![image](https://user-images.githubusercontent.com/84826167/132471648-e09fc05b-c4d3-4adb-b845-0693d34f540b.png)

**Release version**
0.43

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 
![image](https://user-images.githubusercontent.com/84826167/132470009-4356cee1-2b48-4ce7-8c63-ce6aadf148f7.png)
Logs to follow

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by RC-13** [comment]
It appears that we use the incorrect fee which resulted to incorrect fee calculation, in the ndax_utils.py, the default fees are set to 2% which suppose to be 0.2%
![image](https://user-images.githubusercontent.com/57189990/132506034-c613cdec-bf97-4e8e-9b2e-ff3597be96c8.png)

**Comment by mifeng** [comment]
@RC-13 @dennisocana Let's fix this bug for 0.43 release since it's just changing the line above to `DEFAULT_FEES = [0.2, 0.2]`

**Comment by dennisocana** [comment]
@mifeng linked a PR to this issue with the quick fix.

**Comment by dennisocana** [comment]
Fixed in version 0.44 release
