### ISSUE TITLE
Update Avellaneda MM strategy documentation

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#4131]
Update the [Avellaneda MM strategy documentation](https://docs.hummingbot.io/strategies/avellaneda-market-making/) to conform with the same format as our existing [Uniswap-v3 LP documentation](https://docs.hummingbot.io/strategies/uniswap-v3-lp/) for a better explanation of how the strategy works.

## Definition of Done

The documentation should have all the following sections:

1. How it works
2. Strategy files (folder, template)
3. Parameters (config map path, param table)
4. Prerequisites (use variables that reference in the strategy file)

**Comment by mifeng** [comment]
I will do this one as a reference.

**Comment by mifeng** [comment]
FYI my estimate for these stories would be 1.

**Comment by dennisocana** [comment]
This has been completed, will add the strategy description (specification) soon. Preview: https://deploy-preview-4091--docs-hb-v4.netlify.app/strategies/avellaneda-market-making/
