### ISSUE TITLE
Update Liquidity Mining strategy documentation

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#4132]
Update the [Liquidity Mining documentation](https://docs.hummingbot.io/strategies/liquidity-mining/) to conform with the same format as our existing [Uniswap-v3 LP documentation](https://docs.hummingbot.io/strategies/uniswap-v3-lp/) for a better explanation of how the strategy works.

## Definition of Done

The documentation should have all the following sections:

1. How it works
2. Strategy files (folder, template)
3. Parameters (config map path, param table)
4. Prerequisites (use variables that reference in the strategy file)
5. Specification

**Comment by mifeng** [comment]
I will do this one as a reference.

**Comment by dennisocana** [comment]
I will work on this task going forward.
