### ISSUE TITLE
Add a "Gateway: ON / OFF" status on the top status bar of Hummingbot

### ISSUE THREAD

**Issue by martinkou** [CoinAlpha/hummingbot#4140]
## Why
See the Hummingbot Setup Experience section of https://www.notion.so/hummingbot/First-Time-User-Experience-6efacde002604881b81b079352d6845e

## What
* Add a "Gateway: ON / OFF" status on the top status bar of Hummingbot.

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ran3r6) by [Unito](https://www.unito.io)

**Comment by phbrgnomo** [comment]
DoD: 
- Hummingbot client must detect if there is a gateway instance/docker currently running, no matter how it was installed.
- API endpoint on gateway side that send a signal back to client telling if it gateway is on/off.
