### ISSUE TITLE
Cannot run tests

### ISSUE THREAD

**Issue by cecilymiller** [CoinAlpha/hummingbot#4147]
**Describe the bug**
Cannot run tests

**Steps To Reproduce**
1) Clone project
2) Run: python3 -m pip install .
3) Run: python3 -m pytest test/hummingbot/strategy/avellaneda_market_making/test_avellaneda_market_making_start.py

**Info**
platform darwin -- Python 3.9.7, pytest-6.2.5, py-1.10.0, pluggy-1.0.0

**Error**
`____________________________________________________ ERROR collecting test/hummingbot/strategy/avellaneda_market_making/test_avellaneda_market_making_start.py _____________________________________________________
ImportError while importing test module 'path/to/hummingbot/test/hummingbot/strategy/avellaneda_market_making/test_avellaneda_market_making_start.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test/hummingbot/strategy/avellaneda_market_making/test_avellaneda_market_making_start.py:3: in <module>
    import hummingbot.strategy.avellaneda_market_making.start as strategy_start
hummingbot/strategy/avellaneda_market_making/__init__.py:3: in <module>
    from .avellaneda_market_making import AvellanedaMarketMakingStrategy
E   ModuleNotFoundError: No module named 'hummingbot.strategy.avellaneda_market_making.avellaneda_market_making'`

Also, I tried running the same test for `nose2` & `unittest`, but no luck

There's no much info about how to run tests, or should those tests pass, so maybe I'm just missing something?

Thanks

**Comment by Jurelll** [comment]
Hi cecilymiller, Jurell from Hummingbot Support Team here. I'm not really sure what type of test you are trying to conduct here. If you are on our bot trying to run some strategy and encountered an error, kindly provide your config and log files so we may try and replicate and test it on our end. We recommend our users to use Python 3.7. Screenshots are much appreciated. Thank you.

You may contact us here as well : https://support.hummingbot.io/hc/en-us

**Comment by dennisocana** [comment]
@cecilymiller this readme file explains the step how to execute the unit tests. https://github.com/CoinAlpha/hummingbot/tree/master/test/connector#unit-testing

Try the commands below (assuming you're in the `hummingbot/` parent directory):

```
conda activate hummingbot
nosetests -v test/hummingbot/strategy/avellaneda_market_making/test_avellaneda_market_making_start.py
```

**Comment by dennisocana** [comment]
@cecilymiller closing this issue for now. Feel free to reopen if problem persists.
