### ISSUE TITLE
Research python-prompt-toolkit

### ISSUE THREAD

**Issue by mifeng** [CoinAlpha/hummingbot#4160]
# Why

https://github.com/prompt-toolkit/python-prompt-toolkit is the framework used to create the Hummingbot user interface. 

# What

Research what can be done with the framework to improve the Hummingbot user interface. For instance:
- Can we allow users to hide the log pane?
- Can we allow users to toggle dark vs light mode?
- How can different colors improve the interface?
- Can toggling paper trading mode change the font colors?

Compile your findings into a Notion doc, and discuss with Luis in order to generate future stories that improve the user interface.

**Comment by dennisocana** [comment]
Since this is a research / investigation / design story, setting the estimate to 1.

**Comment by mhrvth** [comment]
https://www.notion.so/hummingbot/98e6a1f3719a40c4bd2aaeeed904062f?v=6a9a618bcc6841cf9452e4ae49b75859&p=648b6f6ab67941e0a5c8d6d52ec1717e
