### ISSUE TITLE
Installation: Pip package conflicts when installing Hummingbot via source

### ISSUE THREAD

**Issue by RC-13** [CoinAlpha/hummingbot#4173]
**Describe the bug**
Opening ticket for tracking.  We receive multiple reports from our community developers that are experiencing issues with installing Hummingbot via source build. The issue occurs whenever the pip packages are installed, this affects both the current latest version and development branch.
Note: This issue currently affects Linux and Windows environment.

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):
1. Clone the Hummingbot repository on a Linux or Windows machine
2. Run the ./install script

**Screenshots**
![image](https://user-images.githubusercontent.com/57189990/133095444-2877fbfa-5341-4048-b3bf-36bbb74cb8dd.png)

**Release version**
0.43.0 and 0.44.0

**Attachments**

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by dendenski** [comment]
Same issue here.
Clone the Hummingbot repository on a Windows machine
Run the ./install script
![image](https://user-images.githubusercontent.com/65387749/133101311-c824ca64-eb48-41ed-afe6-7f75dec7f5d2.png)

**Comment by Nullably** [comment]
I experience the same issue on Mac Big Sur.
The `install` got stuck at `Installing pip dependencies` (over 30 minutes til I killed it)
![image](https://user-images.githubusercontent.com/37262506/133102313-2af01047-a079-48af-b12c-1d406566fc05.png)

**Comment by Nullably** [comment]
What works for me to resolve this in `development` on Mac OS is to apply the same fix here 
https://github.com/CoinAlpha/hummingbot/pull/4174

**Comment by kmcgowan2000** [comment]
> I experience the same issue on Mac Big Sur.
> The `install` got stuck at `Installing pip dependencies` (over 30 minutes til I killed it)
> ![image](https://user-images.githubusercontent.com/37262506/133102313-2af01047-a079-48af-b12c-1d406566fc05.png)

if it hangs at this step, generally the solution is to kill the install task and run `conda clean` (i generally do `conda clean -a`)

**Comment by ChrisUnitedCrowd** [comment]
![grafik](https://user-images.githubusercontent.com/90383060/133424847-38961012-4b26-4d1c-9e2c-bd76ee145a60.png)
The installation has now been running for over 1.5 hours.
It does not get beyond this point.

**Comment by dennisocana** [comment]
Should be fixed in version 0.43.1 release: https://docs.hummingbot.io/release-notes/0.43.1/

**Comment by slgodwyn** [comment]
release 0.43.1 produces same error regarding environment conflicts on MacOS Big Sur.

**Comment by RC-13** [comment]
@slgodwyn try cleaning your conda environment as well as per suggestion by our dev team:
```
./clean
./uninstall
conda clean -a
./install
```
If you still get the same issue, kindly send us a screenshot of the error.
