### ISSUE TITLE
pyperclip could not find a copy/paste mechanism 

### ISSUE THREAD

**Issue by bazickoff** [CoinAlpha/hummingbot#4181]
**Describe the bug**
I get this error when copy past from windows to ssh client  "pyperclip could not find a copy/paste mechanism"

**Steps To Reproduce**

install hummingbot with docker on vultr.com  Ubuntu 18.04 x64 server
copy paste any text will result the error

**Screenshots**
![Screenshot (8)](https://user-images.githubusercontent.com/22309093/133244859-fe298a00-608f-4b24-962b-b6e0b0360494.png)

**Release version**
0.43.0

**Comment by Jurelll** [comment]
Hi bazickoff, Jurell from Hummingbot Support here. I checked some forums, it seems the copy/paste option inside vultr is a known issue. They use `ctrl + shift + v` or `shift + insert`. You may also try `ctrl + shift + right click`.

You may check the keyboard shortcuts provided in our docs:
https://docs.hummingbot.io/operation/commands-shortcuts/#keyboard-shortcuts

**Comment by bazickoff** [comment]
Thanks for the help , keyboard shortcuts SHIFT + RMB PAST   fixed the problem
