### ISSUE TITLE
the bot can't close the trade 

### ISSUE THREAD

**Issue by bazickoff** [CoinAlpha/hummingbot#4193]
**Describe the bug**

I get this issue 

2021-09-15 10:45:13,001 - 1 - hummingbot.strategy.spot_perpetual_arbitrage.spot_perpetual_arbitrage - INFO - Current spread: 1.50%, minimum convergence spread: 1.50%.
2021-09-15 10:45:13,001 - 1 - hummingbot.strategy.spot_perpetual_arbitrage.spot_perpetual_arbitrage - INFO - Can't arbitrage, binance_perpetual USDT balance (445.18190204) is below required order amount (459.11600).

when the convergence spread is 1.50%  it should close the trade,even if  I have zero balance it should close the trade , right?
why it check the balance? its look like the bot want to open a new trade 

my config is :
min_divergence: 2.0
min_convergence: 1.5

this issue happened because I stopped the bot and start again ,so the bot assumed that the first trade done and bot start to look to open a new trade

it would be nice if you add a pause and resume feature

**Release version**
0.43.0

**Attachments**
[logs_conf_spot_perpetual_arbitrage_2.5.log](https://github.com/CoinAlpha/hummingbot/files/7170807/logs_conf_spot_perpetual_arbitrage_2.5.log)
[conf_spot_perpetual_arbitrage_2.5.txt](https://github.com/CoinAlpha/hummingbot/files/7170815/conf_spot_perpetual_arbitrage_2.5.txt)

**Comment by viktorya777** [comment]
Hello!
I tested it on my end, I got the same warning when my order amount was below my balance. 
<img width="472" alt="coti" src="https://user-images.githubusercontent.com/88438799/133513763-f9940d47-6cfc-4c55-a387-3ac8b8a77871.png">

**Comment by glenntomas** [comment]
Hi @bazickoff, that's the expected behavior if your balance is not enough to execute the 2nd arbitrage.

**Comment by bazickoff** [comment]
> Hi @bazickoff, that's the expected behavior if your balance is not enough to execute the 2nd arbitrage.

it should close the first trade then execute the 2nd arbitrage  if i'm not wrong ?

**Comment by bazickoff** [comment]
this issue happened because I stopped the bot and start again ,so the bot assumed that the first trade done and the bot start to look to open a new trade

it would be nice if you add a pause and resume feature

**Comment by RC-13** [comment]
Hi @bazickoff the behavior you posted is an expected one. If the bot detects that there is an open position, it will always try to close the position if there is an arbitrage opportunity. It is also required to have a sufficient balance on both exchange and the order amount should as well  meet the minimum allowable trade size of both exchange to close/open positions. I will be closing this ticket, for feature request, do open a feature request ticket instead.
