### ISSUE TITLE
Gate.io - Bot places an order below the minimum order amount required

### ISSUE THREAD

**Issue by rxlxrxsx** [CoinAlpha/hummingbot#4199]
**Describe the bug**
While testing gate.io I noticed that it tries to place an order even without enough balance. When this happens and it's time to cancel the orders, it throws an error that it failed to cancel the order. This is expected since the said order is non-existing and wasn't really created however the problem is the bot recognizes it as an existing order which can be seen on the status output and will go on a loop to try to cancel the non-existing order. I waited for 10 minutes but the bot didn't self recover from the issue. It seems to only happen when there's not enough balance on one side of the pair.

<img width="1423" alt="Screen Shot 2021-09-16 at 10 13 06 AM" src="https://user-images.githubusercontent.com/64377055/133540611-1c8e7341-f3d4-46f4-a860-424f4be5c90b.png">
<img width="1423" alt="Screen Shot 2021-09-16 at 10 13 44 AM" src="https://user-images.githubusercontent.com/64377055/133540685-07f3417e-4f20-4054-8480-c894e6ab0085.png">

```python
2021-09-16 10:13:24,008 - 15341 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: Failed to cancel order - t-HBOT-B-EHUT1631758374005795. Order not found.
Traceback (most recent call last):
  File "/Users/reiniersalazar/hummingbot5/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/Users/reiniersalazar/hummingbot5/hummingbot/connector/exchange/gate_io/gate_io_exchange.py", line 555, in _execute_cancel
    raise ValueError(f"Failed to cancel order - {order_id}. Order not found.")
ValueError: Failed to cancel order - t-HBOT-B-EHUT1631758374005795. Order not found.
```

**Steps To Reproduce**
1. Create a pure_mm strategy using gate.io
2. Use a pair with only enough asset to place an order on one side
3. Start the bot and notice that it will still try to place an order on the side that doesn't have enough balance

**Release version**
development-0.44.0

**Attachments**
Logs and config: [gate.io.zip](https://github.com/CoinAlpha/hummingbot/files/7174620/gate.io.zip)

**Comment by RC-13** [comment]
same issue #4087

**Comment by rxlxrxsx** [comment]
Oops, my bad. Closing this one now.
