### ISSUE TITLE
Blocktane - Incorrect fees calculation

### ISSUE THREAD

**Issue by rxlxrxsx** [CoinAlpha/hummingbot#4218]
**Describe the bug**
Fees calculated when trades are executed using Blocktane is incorrect. Upon checking on the blocktane_utils.py file it uses a default fee of [0.35, 0.45] instead of .15% and .25% for maker and taker orders. Fee reference can be seen here:
https://help.blocktane.io/fees-limits
https://trade.blocktane.io/api/v2/xt/public/trading_fees

Edit:
Upon further checking and calculating the fees recorded in the client it looks like it's using the fees listed on the blocktane_exchange.pyx file which is set to .2% on both maker and taker orders.

**Steps To Reproduce**

1. Run a pure_mm bot using blocktane
1. Execute trades and compare fees from the client and exchange website

**Screenshots**
![](https://user-images.githubusercontent.com/64377055/133948776-58343beb-0b68-4cde-9c28-d3f6dc29442c.png)
![](https://user-images.githubusercontent.com/64377055/133948780-7bdf3dce-c506-423c-a8f2-20731f5a7f7a.png)

**Release version**
development-0.44.0

**Attachments**
Logs config and csv: [blocktane.zip](https://github.com/CoinAlpha/hummingbot/files/7193229/blocktane.zip)

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ran5wc) by [Unito](https://www.unito.io)

**Comment by Jurelll** [comment]
Hi @rxlxrxsx, thank you for providing your config and logs, we will have this replicated and monitored on our end.

**Comment by RC-13** [comment]
Closing ticket, Blocktane doesn't provide the fee information thru the websocket. we will continue using the fee estimates (https://github.com/CoinAlpha/hummingbot/issues/2084#issuecomment-992582813).
