### ISSUE TITLE
Liquid - Incorrect fees paid on history 

### ISSUE THREAD

**Issue by rapcmia** [CoinAlpha/hummingbot#4227]
**Describe the bug**
When checking the fees paid in the history command, Liquid has 0 trading fees on market maker if a user's trading volume is less `10,000$` and `0.15` for market taker over the last 30 days (Can be found [here](https://www.liquid.com/fees/)). Our test account has been on level 0 yet our bot returns a value on fees paid after few filled orders. 

![liquid](https://user-images.githubusercontent.com/73840223/133991135-15af8d58-56d7-4ece-bc02-f13b7eca1ea0.png)

I tried to check liquid's default fees on the bot and its current setup is `[0.1, 0.1]`

Steps to reproduce:

1. Create a Pure market-making strategy with spreads tight enough for a fill order event
1. After few filled orders, run the `history` command
1. Compare Liquid's CSV file and the bot's history result

**Release version**
dev-0.44.0

**Attachments**
[Liquid.zip](https://github.com/CoinAlpha/hummingbot/files/7195255/Liquid.zip)

_WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!_

**Optional: your discord username:**

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ran629) by [Unito](https://www.unito.io)

**Comment by RC-13** [comment]
Fixed has been merged to the development branch
