### ISSUE TITLE
Bittrex - Incorrect fees calculation 

### ISSUE THREAD

**Issue by rxlxrxsx** [CoinAlpha/hummingbot#4238]
**Describe the bug**
Fees calculated when trades are executed using Bittrex is incorrect. Upon checking on the bittrex_utils.py file it uses a default fee of [0.25, 0.25] instead of .75% for both maker and taker orders. Fee reference can be seen here:
https://bittrex.zendesk.com/hc/en-us/articles/115000199651-Bittrex-feeshttps://bittrexglobal.zendesk.com/hc/en-us/articles/360009625260-Bittrex-Global-fees
**Steps To Reproduce**

1. Run a pure_mm bot using bittrex
1. Execute trades and compare fees from the client and exchange website

**Screenshots**
![](https://user-images.githubusercontent.com/64377055/134301243-532acb7e-8264-4e65-8c27-dfd6327dc4fb.png)
Note: Commission = fees on bittrex website
![](https://user-images.githubusercontent.com/64377055/134301279-da144a54-e805-4d57-a75c-a6fa29244391.png)
![](https://user-images.githubusercontent.com/64377055/134301314-55a1dc16-c6d8-4b38-8d0a-3bca793279a6.png)

**Release version**
development-0.44.0

**Attachments**
Logs, config and csv: [bittrex.zip](https://github.com/CoinAlpha/hummingbot/files/7208712/bittrex.zip)

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ran6a3) by [Unito](https://www.unito.io)

**Comment by dennisocana** [comment]
The issue could be caused not only by the incorrect fee hardcoded in `utils.py` but also because the connector calls the `c_get_fee` function which is responsible for estimating the fees. Hence the discrepancies from the exchange vs. history output.

**Comment by RC-13** [comment]
Fix has been merged in the development branch.
