### ISSUE TITLE
Adjust Kraken rate limits based on account tier

### ISSUE THREAD

**Issue by petioptrv** [CoinAlpha/hummingbot#4254]
As a Kraken connector user, I want to be able to set my rate limits according to the allowance of my account tier.

# Details
The Kraken exchange allows different rate-limits per account tier [(starter, intermediate, pro)](https://docs.kraken.com/rest/#section/Rate-Limits/REST-API-Rate-Limits). The connector should request the account tier from the user along with the API key and secret, and dynamically create the rate limits based on that setting.

# Definition of Done
- [ ] The Kraken connection process asks the user for account tier (with starter being the default setting).
- [ ] The Kraken connector dynamically creates the rate limits based on the account tier.
- [ ] The Kraken connector sets the `retry_interval` of the `AsyncThrottler` to the appropriate given the account tier.

**Comment by Nullably** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/hummingbot-5f340755c5e17300167a8f30/issues/CoinAlpha/hummingbot/4254?planning-poker) with ZenHub @aarmoa @CrimsonJacket @james-hummingbot @petioptrv @vic-en @willyPat
