### ISSUE TITLE
Digifinex - Incorrect fees calculation

### ISSUE THREAD

**Issue by rxlxrxsx** [CoinAlpha/hummingbot#4255]
**Describe the bug**
Fees calculated when trades are executed using Digifinex is incorrect. Currently it uses a fee of 0.1 on fees being deducted instead of 0.2. Fee reference can be seen here:
https://digifinex.zendesk.com/hc/en-us/articles/360000328422--Contract-List-Fees

**Steps To Reproduce**

1. Run a pure_mm bot using digifinex
1. Execute trades and compare fees from the client and exchange website

**Screenshots**
![](https://user-images.githubusercontent.com/64377055/134472267-0fab662e-0595-473d-9539-27ed4f00d705.png)
![](https://user-images.githubusercontent.com/64377055/134472251-3dd8906c-510e-4f98-92de-685d48afdad3.png)

**Release version**
development-0.44.0

**Attachments**
Logs, config and csv: [digifinex.zip](https://github.com/CoinAlpha/hummingbot/files/7215826/digifinex.zip)

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ran6p9) by [Unito](https://www.unito.io)

**Comment by RC-13** [comment]
Closing ticket since Digifinex doesn't provide fee information thru WebSocket. We will continue using fee estimates (https://github.com/CoinAlpha/hummingbot/issues/2084#issuecomment-992774122)
