### ISSUE TITLE
Deprecate Hummingsim dependency

### ISSUE THREAD

**Issue by Nullably** [CoinAlpha/hummingbot#4260]
**Why**
Hummingsim is a closed source project which we can no longer depend on.
Currently we use some Hummingsim classes for testing Hummingbot strategies, we need to replace these with our own Hummingbot classes so that we can remove the dependency.

**What**
- Create a new mock connector where strategy unit tests can use
- Update all unit tests where Hummingsim is used 
- Remove Hummingsim package from installation
- Rename test/debug/test_order_expiration.py to debug_order_expiration.py, this is only for record keeping purposes

**For developer**
- Do not copy code from HummingSim
- You can make use of PaperTradeExchange, many functionalities needed are there.
- Make the new mock connector Python if possible.

**DoD**
- New mock connector, order book loader and other relevant classes created
- No more Hummingsim dependency
- All unit tests pass

**Comment by aarmoa** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/hummingbot-5f340755c5e17300167a8f30/issues/CoinAlpha/hummingbot/4260?planning-poker) with ZenHub @CrimsonJacket
