### ISSUE TITLE
Implement `patch()` and `unpatch()` for avoiding unit test leakages

### ISSUE THREAD

**Issue by martinkou** [CoinAlpha/hummingbot#4262]
## Why

We are currently leaking mock methods in unit tests, when we are monkey-patching common objects. One example is when we override methods in shared `Ethereum` objects in unit test cases - one unit test would override one method while the next would override another method. This is not scalable since by the time we get to, say, a 6th test case, that test case would likely be seeing the override mock methods from the 1st or 2nd test cases.

In Python, this type of overrides are automatically cleaned up with `mock.patch()` context managers. JavaScript and TypeScript, unfortunately, do not come with context manager support. But we can emulate most of that with `afterEach()` in the Jest testing framework.

## What

* Implement `patch(target, propertyName, mock)`, which patches `target.{propertyName}` with the given mock object, while saving the original to `target.__original__{propertyName}`.
  * This is meant to be called at the beginning of unit test cases.
* Implement `unpatch()`, which reverses all known patches.
  * This is meant to be called in `afterEach()`.

**Comment by phbrgnomo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/hummingbot-5f340755c5e17300167a8f30/issues/CoinAlpha/hummingbot/4262?planning-poker) with ZenHub @james-hummingbot @martinkou @vic-en
