### ISSUE TITLE
https://github.com/CoinAlpha/hummingbot/issues/3961

### ISSUE THREAD

**Issue by klazklaz** [CoinAlpha/hummingbot#4269]
[logs_solx10.log](https://github.com/CoinAlpha/hummingbot/files/7226763/logs_solx10.log)
[logs_ETH_perpetual.log](https://github.com/CoinAlpha/hummingbot/files/7226764/logs_ETH_perpetual.log)
![Binerror](https://user-images.githubusercontent.com/82020159/134699659-d9a416e3-ee64-493a-88ea-03d45d2a7c65.jpg)
![2](https://user-images.githubusercontent.com/82020159/134699665-b8520aaf-a6b0-4d51-818c-9c430dd19112.jpg)
![3](https://user-images.githubusercontent.com/82020159/134699682-e37035f7-1f94-412c-acde-f55c1ba9a710.jpg)
![4](https://user-images.githubusercontent.com/82020159/134699686-93111ecc-e5c2-45de-a587-29dde19953a4.jpg)

**Comment by klazklaz** [comment]
Cant start bot(((

**Comment by Jurelll** [comment]
Hi @klazklaz, Jurell from Hummingbot Support Team here. If I may ask have you tried to toggle the position mode to One-way, then switching it back to Hedge mode after a couple of minutes? Once switched back, it could take a couple of minutes to reflect.

Also, this has already been raised in issue #3961. Kindly leave a comment there as well that you are having the same issue. Thanks!

**Comment by Jurelll** [comment]
Hi @klazklaz, our team is already aware of this bug, and they are currently working on it to be fixed. Kindly close this issue and leave a comment on #3961, letting our team know you're having the same problem. Thanks!

**Comment by RC-13** [comment]
Closing ticket to avoid duplicate issues

**Comment by Wiger123** [comment]
> Hi @klazklaz, our team is already aware of this bug, and they are currently working on it to be fixed. Kindly close this issue and leave a comment on #3961, letting our team know you're having the same problem. Thanks!

Please add the type of order: post only, which means the order will be the only maker, in Binance API, we could use LIMIT + GTX to fix this problem, how should we do in Humming Bot.
By the way, Humming Bot is the best HFT bot I have seen.
