### ISSUE TITLE
[BUG] XEMM on single exchange fails after 1 trade

### ISSUE THREAD

**Issue by mifeng** [CoinAlpha/hummingbot#427]
**Describe the bug**
Running XEMM between 2 pairs on Binance, the bot stops with error code 103 after one trade. Sometimes, the error code is 103.

Here are the steps to reproduce the issue (see attachments in the section below):
Version: 
`dev-0.9.0`

Config:
```
# Exchange and token parameters
maker_market: binance
taker_market: binance
maker_market_symbol: ALGOUSDC
taker_market_symbol: ALGOUSDT

# Minimum profitability target required to place an order
# Expressed in decimals: 0.01 = 1% target profit
min_profitability: 0.01

# Maximum order size in terms of quote currency
trade_size_override: 0.0
```
Logs:
[hummingbot_logs_2019-06-24-08-56-29.log](https://github.com/CoinAlpha/hummingbot/files/3323069/hummingbot_logs_2019-06-24-08-56-29.log)

**Comment by martinkou** [comment]
Fixed with #430
