### ISSUE TITLE
Replace the background color of the panel areas

### ISSUE THREAD

**Issue by luisfilipeoliveira** [CoinAlpha/hummingbot#4270]
## Why
Hummingbot is gradually defining its internal design system — this ongoing process (short and long term) will make some changes to our products. This Design System is being built as we analyze/collect information from our customers.

## What
Replacing or changing the solid colors of the background of each panel.

## Definition of Done
You can consult the following figma artboard to view the implementation.

[>>> Figma (Main-layout)](https://www.figma.com/file/lmkPsyJz5zAV7SHXCaFwXd/Hummingbot-Client?node-id=388%3A2869)
[>>> Figma (Layout & Grid)](https://www.figma.com/file/lmkPsyJz5zAV7SHXCaFwXd/Hummingbot-Client?node-id=388%3A2454)
[>>> DSM (Token: Colors)](https://www.figma.com/file/3bCuxWM2u8y9pJp73K3itU/Hummingbot-Colors?node-id=0%3A1)

![image.png](https://images.zenhubusercontent.com/57179e45bf93871ccd99c501/98640a91-13b6-42b0-a535-baeab2360f6c)

**top-pane —** Black: `#000000`
**bottom-pane —** Black: `#000000`
**output-pane —** Blue Greyscale 500: `#282C2F`
**input-pane —** Blue Greyscale 700: `#151819`
**log-pane —** Blue Greyscale 700: `#151819`

**Comment by mifeng** [comment]
We decided to schedule this story, but the task should be to enable users to edit these color settings. Add 5 variables to the global config file in a section called COLOR SETTINGS that allows users to change these pane colors.

**Comment by Nullably** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/hummingbot-5f340755c5e17300167a8f30/issues/CoinAlpha/hummingbot/4270?planning-poker) with ZenHub @aarmoa @CrimsonJacket @james-hummingbot @petioptrv @vic-en @mhrvth

**Comment by dennisocana** [comment]
Closing w.r.t. https://app.zenhub.com/workspaces/hummingbot-5f340755c5e17300167a8f30/issues/coinalpha/hummingbot/4382
