### ISSUE TITLE
Set a graphical appearance to command parameters

### ISSUE THREAD

**Issue by luisfilipeoliveira** [CoinAlpha/hummingbot#4273]
## Why
Whenever we execute several commands on our screen, it is very confusing to notice the executed commands. There is no visual separation of the executed command and the result—nor is there a visual separation between commands.

## What
I recommend creating a kind of visual tag, which helps to represent the executed command. This visual aspect will create visual impact and separate commands already executed.

## Definition of Done
* [History commands on terminal (Figma)](https://www.figma.com/file/lmkPsyJz5zAV7SHXCaFwXd/Hummingbot-Client?node-id=388%3A2963)
* [Colors (Figma)](https://www.figma.com/file/3bCuxWM2u8y9pJp73K3itU/Hummingbot-Colors?node-id=0%3A1)

![image.png](https://images.zenhubusercontent.com/57179e45bf93871ccd99c501/aeac6a20-ecd7-4631-ab78-d52499270d7c)

The representation of the main command is in the color of the terminal green (declared in the Design System).

![image](https://user-images.githubusercontent.com/15719418/137998823-ef17eca3-c7c6-4fb6-af8e-29c534733b00.png)

But there is the same representation (but with different colors) for when we have alerts in the output panel. For example, if it's an error message, it has a semantic color representation as per the alert.

**Detail:** The information text of the alert passes to the same tag line.

**General Commands**  `#5FFFD7`

**success-alert** `#5FFFD7`

**warning-alert** `#FFFF00`

**info-alert** `#5FD7FF`

**danger/erro-alert** `#FF0000`

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ran6ye) by [Unito](https://www.unito.io)

**Comment by mifeng** [comment]
We decided to schedule this story:
1.  Add label colors to differentiate user commands from command output in output pane. The label color should correspond to the `primary` color.
2. Add success, warning, and danger labels to the connector names in the `connect` command that correspond to their status. Remove the column that contains the existing status labels .
<img width="707" alt="Screen Shot 2021-09-29 at 7 18 37 AM" src="https://user-images.githubusercontent.com/1795030/135287276-72858b5a-6d60-48ef-a46b-9a9929ef0939.png">

**Comment by dennisocana** [comment]
Requested for screenshots from @luisfilipeoliveira of the sample output as Mike described in the comment to add to this story's main description.

**Comment by dennisocana** [comment]
After discussing with @aarmoa today, there are different interpretations of the outcome of this task based on the previous discussion. For the connector status, it may be a good idea to keep the column with words and add a background label to it instead of applying the label colors directly on the exchange name. This also takes into account in case of users with color blindness.

**Comment by luisfilipeoliveira** [comment]
@dennisocana I think it's important to have referenced this point of view in accessibility issues, in this case the colorblind. I want to leave here my contribution of improvements based on the idea of your comment.

![image.png](https://images.zenhubusercontent.com/57179e45bf93871ccd99c501/3964bf7b-9cb4-4f0d-89f3-5ae2306fccde)
