### ISSUE TITLE
Set Primary Color of Hummingbot Client (Green-terminal)

### ISSUE THREAD

**Issue by luisfilipeoliveira** [CoinAlpha/hummingbot#4274]
## Why
Hummingbot is gradually defining its internal design system — this ongoing process (short and long term) will make some changes to our products. This Design System is being built as we analyze/collect information from our customers.

## What
Change the dominant color of the terminal to the new Green-terminal

## Definition of Done
You can consult the following figma artboard to view the implementation.

[>>> Figma (Main-layout)](https://www.figma.com/file/lmkPsyJz5zAV7SHXCaFwXd/Hummingbot-Client?node-id=388%3A2869)
[>>> DSM (Token: Colors)](https://www.figma.com/file/3bCuxWM2u8y9pJp73K3itU/Hummingbot-Colors?node-id=0%3A1)

![image.png](https://images.zenhubusercontent.com/57179e45bf93871ccd99c501/98640a91-13b6-42b0-a535-baeab2360f6c)

Green-terminal: `#00FFE5`

**Comment by Nullably** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/hummingbot-5f340755c5e17300167a8f30/issues/CoinAlpha/hummingbot/4274?planning-poker) with ZenHub @aarmoa @CrimsonJacket @mhrvth @petioptrv

**Comment by dennisocana** [comment]
Closing w.r.t. https://app.zenhub.com/workspaces/hummingbot-5f340755c5e17300167a8f30/issues/coinalpha/hummingbot/4382
