### ISSUE TITLE
Apply toggle component to turn paper trade mode state on & off

### ISSUE THREAD

**Issue by luisfilipeoliveira** [CoinAlpha/hummingbot#4278]
## Why
The paper_trade_mode command turns out to be a very used command, and a little difficult to see if it is turned on or off.

## What
To facilitate the observation and interaction of off and on, we can apply a toggle component to your action. We must not exclude the possibility of the user using the command line.

## Definition of Done
To enable and disable paper trade mode options, the user has 2 ways to do it: 

1. We can use the mouse and interact with clicks with the component (on - off); if we happen to use the component, it must still play a feedback action in the output panel.
2. We can use the paper_trade command: yes/on. After executing this command, the component changes state according to the chosen option.

![image.png](https://images.zenhubusercontent.com/57179e45bf93871ccd99c501/b697d453-69c6-44ce-9b14-c555c9459d93)

![image.png](https://images.zenhubusercontent.com/57179e45bf93871ccd99c501/6cf19d1d-4eae-4439-9865-d5ecb07ad974)

**Comment by dennisocana** [comment]
Since we're reworking paper trade mode near-term, this button is no longer needed.
