### ISSUE TITLE
Windows source build - Getting warnings of "User cython.int etc. directly"

### ISSUE THREAD

**Issue by rapcmia** [CoinAlpha/hummingbot#4286]
**Describe the bug**
After compiling, I'm getting a warning about `Use 'cython. int' etc. directly` on GitBash on Windows 10 source build. The warning does not happen on WSL and Ubuntu18.04LTS

**Steps To Reproduce**

1. Open GitBash and clone Hummingbot 
1. Move to `Hummingbot` folder and run `./clean && ./uninstall`
1. Once uninstall is completed, run `./install` and then `conda activate hummingbot && ./compile`
1. Wait until it finishes compiling the files

**Screenshots**
Version 0.43.1
![image](https://user-images.githubusercontent.com/73840223/134803495-042a4586-6089-496c-816b-411108bbbe09.png)

Version dev-0.44.0
![image](https://user-images.githubusercontent.com/73840223/134803369-e04e7503-86ac-47bd-aa1e-723e49ce4f47.png)

**Release version**
0.43.1 and dev-0.44.0

**Attachments**
NA

_WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!_

**Optional: your discord username:**

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ran79q) by [Unito](https://www.unito.io)

**Comment by gerald-hb** [comment]
Not getting the same result/error.
![image](https://user-images.githubusercontent.com/84826167/134804963-543762ea-4cb5-47a0-be0f-da5449a35080.png)
![image](https://user-images.githubusercontent.com/84826167/134806508-b0cc058d-f11d-4588-95be-8cdcddd30f4a.png)

Steps To Reproduce

Open GitBash and clone Hummingbot
Move to Hummingbot folder and run ./clean && ./uninstall
Once uninstall is completed, run ./install and then conda activate hummingbot && ./compile

**Comment by rapcmia** [comment]
Closing this ticket, no longer occurring when testing v46
