### ISSUE TITLE
Spot Perpetual Arbitrage - bot sells spot on binance

### ISSUE THREAD

**Issue by check1you** [CoinAlpha/hummingbot#4288]
**Describe the bug**
The bot tries to sell a spot on binance and gives an error that there is no coin. But you can't short on the spot.
Shouldn't it be that he should buy spot and short futures? Can I change somewhere or is it how it should be?

**Comment by cali-tomas** [comment]
Hi @check1you, as per our docs, `buy/sell order on the spot connector, while opening an opposing long/short position on the derivative connector.` Can you send a screenshot of the bug you are pertaining to, config, and logfile? so we can have more details. Thanks

Here is the link on our docs
https://docs.hummingbot.io/strategies/spot-perpetual-arbitrage/#how-it-works
