### ISSUE TITLE
Option to open and close Log panel

### ISSUE THREAD

**Issue by luisfilipeoliveira** [CoinAlpha/hummingbot#4295]
## Why
The static layout that the Hummingbot client presents does not give the user much flexibility to organize the application within their context and working environment. In analyzing some customer information, they often don't even end up analyzing their strategies on the Hummingbot log pane.

## What
To create more flexibility in what the user wants to make visible to their work context, it is recommended to add an option to close the log panel in the application.

## Definition of Done

Figma [(Opened Panel)](https://www.figma.com/file/lmkPsyJz5zAV7SHXCaFwXd/Hummingbot-Client?node-id=392%3A3471) | [Closed Panel](https://www.figma.com/file/lmkPsyJz5zAV7SHXCaFwXd/Hummingbot-Client?node-id=392%3A3968) | [Proto](https://www.figma.com/proto/lmkPsyJz5zAV7SHXCaFwXd/Hummingbot-Client?page-id=0%3A1&node-id=392%3A3471&viewport=387%2C48%2C0.52&scaling=contain&starting-point-node-id=392%3A3471&show-proto-sidebar=1)

This change implies:

- Add element (arrow button) with the function to close or open the panel
- This element will be positioned inside the input area - right-aligned
- Command to close/open the panel

**Opened**

![image.png](https://images.zenhubusercontent.com/57179e45bf93871ccd99c501/99341709-7540-41e8-8e9c-03fdde562ac0)

**Closed**

![image.png](https://images.zenhubusercontent.com/57179e45bf93871ccd99c501/ff3b069b-5c2f-4a94-b20b-a9d823230fb5)

**Optimized window for the size desired by the customer**

![image.png](https://images.zenhubusercontent.com/57179e45bf93871ccd99c501/5a802433-c3c5-4918-b257-bbb955b96ac1)

**Comment by Nullably** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/hummingbot-5f340755c5e17300167a8f30/issues/CoinAlpha/hummingbot/4295?planning-poker) with ZenHub @aarmoa @CrimsonJacket @mhrvth @petioptrv

**Comment by aarmoa** [comment]
We might need to change the task specification. I am not sure it will be possible to have an arrow button to close the log pane. We might need to use console command for that.

**Comment by luisfilipeoliveira** [comment]
Updated design with indications. Note: The arrow (as a graphical representation of opening and hiding) is a Glyph of typography.

![image.png](https://images.zenhubusercontent.com/57179e45bf93871ccd99c501/1ff94d9f-152a-4fb9-ae7b-1e1a12e7f246)
![image.png](https://images.zenhubusercontent.com/57179e45bf93871ccd99c501/9ae5c5a8-2759-4578-a5dc-5dcdbfe41ce8)
