### ISSUE TITLE
Replace websockets library with aiohttp library - dYdX

### ISSUE THREAD

**Issue by aarmoa** [CoinAlpha/hummingbot#4404]
See epic https://github.com/CoinAlpha/hummingbot/issues/3941 for the rationale of this task.

## Definition of Done
* [ ] Replace `websockets` library with `aiohttp` in `dYdX` connector
* [ ] Connector should be working without issues after the change

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1pd0g2b) by [Unito](https://www.unito.io)

**Comment by dennisocana** [comment]
Closing this task since we will soon deprecate this connector : https://github.com/CoinAlpha/hummingbot/issues/4734
