### ISSUE TITLE
[BUG] Error submitting trades after registering for bounty program

### ISSUE THREAD

**Issue by martinkou** [CoinAlpha/hummingbot#443]
**Describe the bug**
After registering for the bounty program, regular error messages about trade submission would print out in the console.

**Screenshots**
<img width="1942" alt="Screen Shot 2019-06-26 at 6 03 18 PM" src="https://user-images.githubusercontent.com/304402/60225923-bf372500-983d-11e9-81ba-99500f24e91d.png">

**Comment by martinkou** [comment]
@yzhang1994 please take a look.

btw, you should include stack traces for error logs. So please add `exc_info=True` for the error log above and also any similar errors in bounty utils.

**Comment by martinkou** [comment]
Adding @michaelc9 since it might have to do with the last recorded timestamp APIs returning `str` for long integers.

I'm ok with using strings for returning long integers in JSON - because returning the long integer as-is in JSON may cause troubles when we have JavaScript frontend / leaderboard later. But some warnings or documentations on the API source file would be useful.

**Comment by yzhang1994** [comment]
@martinkou this is fixed.
