### ISSUE TITLE
Error connecting to crypto.com

### ISSUE THREAD

**Issue by zhirong80** [CoinAlpha/hummingbot#4441]
**Describe the bug**
// A clear and concise description of what the bug is.
I am having trouble running my AMM strategy on crypto.com today. The same program was running well yesterday. On starting the strategy, I received the following message 
Error: Error fetching data from https://api.crypto.com/v2/private/get-account-summary. HTTP status is 400. Message: {'id': 1633922923622378, 'method': 'private/get-account-summary', 'code': 10007, 'message': 'INVALID_NONCE'}

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: ...
2. Start the bot using this command: ...
...

**Screenshots**
// If applicable, add screenshots to help explain your problem.

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*
[logs_hummingbot.log](https://github.com/CoinAlpha/hummingbot/files/7319809/logs_hummingbot.log)

**Optional: your discord username:**

**Comment by RC-13** [comment]
@zhirong80 Can you please provide us more details of the issue that you're experiencing. 
- From which environment are you currently running your bot (Windows, Mac, or Linux/cloud)?
- Installation method (Binary executable file, Docker or Source)?

 Kindly attach the following
- Screenshot of your whole Hummingbot terminal
- Your strategy configuration file or screenshot
- Your strategy log file

And also, double check that your crypto.com API account did not get disconnected by running the `connect` command, key status should be both `Yes`

**Comment by RC-13** [comment]
@zhirong80 Closing ticket for now since issue can't be replicated, do let us know if you encounter the issue again in the future so we can re-open the ticket.
