### ISSUE TITLE
[BUG] Could not fetch new trading rules & API call error

### ISSUE THREAD

**Issue by nsshommo** [CoinAlpha/hummingbot#445]
**Describe the bug**
Showing warnings:
1. could not fetch new trading rules from Binance
2. API call error.

**Steps To Reproduce**
Here are the steps to reproduce the issue:
1. Set up your configuration file with these parameters: config, cross exchange MM, import
2. Start the bot using this command: start

**Screenshots**
![image](https://user-images.githubusercontent.com/31445351/60286804-1ae2da80-9932-11e9-9752-8572199f3cbb.png)

**Release version**
Version: 0.8.1

**Attachments**

Log File:
[hummingbot_logs_2019-06-27-23-17-24.log](https://github.com/CoinAlpha/hummingbot/files/3335953/hummingbot_logs_2019-06-27-23-17-24.log)

Discord username: nasim#0665

**Comment by vdbelt** [comment]
You appear you have uploaded your full config including private keys. Please revoke them immediately.

**Comment by nsshommo** [comment]
> You appear you have uploaded your full config including private keys. Please revoke them immediately.

Thanks.

**Comment by chowryan** [comment]
old bug that should be fixed in newest version 0.10. Please reopen if you still see this error.
