### ISSUE TITLE
Define what should be the logic of closing orders depending for each `position_mode`

### ISSUE THREAD

**Issue by phbrgnomo** [CoinAlpha/hummingbot#4498]
## Description
As discussed, both `one_way` and `hedge_mode` will be kept on the strategy, since different connectors allow the use of different modes (or only one of them)

The main issue related to each of the modes is how positions are tracked and closed.

We need to investigate what is the standard behaviour for each mode, and if possible, standardize how positions are handled on each mode

## Definition of done
* [ ] Research doc detailing how each mode handles the tracking/opening/closing positions
* [ ] Propose a standard solution (if possible) for both cases. If no standard solution is viable, clearly define how each mode will handle the positions

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1pd0d10) by [Unito](https://www.unito.io)

**Comment by dennisocana** [comment]
As agreed last night, we will close this story w.r.t. Jack's story for perpetual market making rework.
