### ISSUE TITLE
Remove type of order definition for closing positions, standardize how orders are closed

### ISSUE THREAD

**Issue by phbrgnomo** [CoinAlpha/hummingbot#4500]
## Description
Operations to close open positions (take profit/stop-loss) should follow the same logic:

1. Bot tracks market price
1. If market price crosses the take profit or stop-loss value, bot create a limit order to close the position
1. The limit order created to close the position must have a `slippage` setting. The price of the closing order will be equals to (closing price +- slippage)
1. If the order isn't filled after it's creation (due to market moving more than the defined sllipage), try again until it is filled

##

* [ ] Remove order type for closing operations
* [ ] Close positions (TP/SL) using limit order with a sllipage buffer
* [ ] Add a retry logic to make sure that the operation is closed

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1pd0cyd) by [Unito](https://www.unito.io)

**Comment by dennisocana** [comment]
As agreed last night, we will close this story w.r.t. Jack's story for perpetual market making rework.
