### ISSUE TITLE
Remove funding rate use from perpetual market making

### ISSUE THREAD

**Issue by phbrgnomo** [CoinAlpha/hummingbot#4502]
## Description
Funding rate isn't a fundamental part of the perpetual market making strategy, since the goal of the strategy is to capture spreads.

This should be removed only from the strategy, not from connectors.

## Definition of done
* [ ] Remove code from perpetual market making related to funding rate.

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1pd0cvh) by [Unito](https://www.unito.io)

**Comment by dennisocana** [comment]
As agreed last night, we will close this story w.r.t. Jack's story for perpetual market making rework.
