### ISSUE TITLE
Research what information would be most useful to display on `status` for the perpetual market making strategy

### ISSUE THREAD

**Issue by phbrgnomo** [CoinAlpha/hummingbot#4504]
The following information must be show on the `status` command:

**Open Orders**

It must show what are the current open orders, with their respective prices, and the spread between them.

**Open Positions**

When an *Open Order* is filled, the information related to it's current state would be show here.

The following information must be added to each of the open positions:

- `SHORT` and `LONG` tags, to identify what is the position direction
- The price the position was opened/filled
- Position profit/loss, in relative value (%) to the current market price
- `TP` and `SL` prices, in absolute values
- Liquidation Price of the position
- Position Leverage

**Closed Positions**

This section shows a resume of the positions that have been closed since `start` was executed.

We must have a separation between `SHORT` and `LONG` closed orders, and for each type, show the value of `Average Open` and `Average Close` prices (Refer to dYdX Positions information).

![Captura de tela 2021-11-11 16.26.49.png](https://images.zenhubusercontent.com/5f64254ca13ff3717cc3a0c5/f27b3245-733a-4b6a-ab21-d8175aa63bb0)

This allows a quick visualization if the current bot run is profitable or not.

**Account Information**

It must show information relative to the account situation:

- Start balance - Shows what was the total balance the moment `start` was executed
- Current Balance - Shows what is the current account value, considering 
- Account Profit/Loss - Both in absolute value and relative (%) to the `start` margin balance
- Estimated Capital At Risk - The value of the total loss relative (%) to the account balance if the Stop Loss is triggered, when there is an open position. (Thanks @mss7082)

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1pd0cqu) by [Unito](https://www.unito.io)

**Comment by mss7082** [comment]
1. Calculated current stop loss price, estimated loss in quote currency and estimated loss in percentage of account balance

2. Calculated current take profit price (in take profit mode), estimated profit in quote currency and estimated profit in percentage of account balance.

3. Calculated current take profit price based on current peak (in take trailing profit mode), estimated profit in quote currency and estimated profit in percentage of account balance.

These should help one know the risk to reward ratio taken at glance for better risk management.

**Comment by yancong001** [comment]
For cross margin account , "total leverage rate" is important

**Comment by mhrvth** [comment]
For margin accounts also maintenance margin and account value are important

**Comment by Notoooriou5** [comment]
some info on the liquidity available at the top of the order book would be great if possible.

eg. orders available at the top +/- x% for certain time intervals

This might be tricky to capture though.

**Comment by dennisocana** [comment]
The initial task has been created. Thanks everyone for giving your feedback and suggestions to this research which will help us continue to improve this feature.
