### ISSUE TITLE
Create a tutorial explaining how to create an EVM-type connector, using Avalanche experience as example

### ISSUE THREAD

**Issue by phbrgnomo** [CoinAlpha/hummingbot#4524]
## What
A tutorial showing how to use the existing code of gateway v2 to create a new connection to an EVM compatible chain

## How
Using the Avalanche + Pangolin Implementation, show the steps on transforming the existing Etherum connection/routes as a base to connect to Avalanche Blockchain

EVM compatible chains will probably be a common connection request for gateway v2, so we should have a step-by-step tutorial explaining what part of the code can be used, and what are the parameters that needs to be changed

## Definition of Done
* [ ] Tutorial page on the documentation site showing how to connect to a different EVM compatible exchange using the existing code as a starting point.

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1pd0c1j) by [Unito](https://www.unito.io)

**Comment by willyPat** [comment]
WIP
https://www.notion.so/hummingbot/Adding-an-Ethereum-based-connector-a339ce94cbf74408a8c4a481a33bb9cb
