### ISSUE TITLE
Paper Trade Rework

### ISSUE THREAD

**Issue by Nullably** [CoinAlpha/hummingbot#4525]
## Why
Paper Trade mode doesn't work with a number of strategies and exchanges, the current design doesn't convey to the users clearly on what it can or cannot do.

## What
* Remove paper_trade command
* Remove paper_trade_mode ticker from the top status bar
* Add a new global config `paper_trade_exchanges` where it stores binance, kucoin, ascend_ex and gate_io as its default value
* Add these paper trade exchanges as options during strategy configuration where spot exchange (connector) is required, they appear with `_paper_trade` suffixed, e.g. `binance_paper_trade`
* Do not display paper trade exchanges under `connect` and `balance` command
* On the `start`, HB creates PaperTradeExchange object (with order book data from the underlying exchange)  for each paper trade exchange in the configuration 

## Definition of Done
* paper_trade command removed
* paper_trade_mode ticker removed
* New `paper_trade_exchanges` global config added
* Any strategy that works with spot  exchange (connector) works with any paper trade exchange

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1pd0c0a) by [Unito](https://www.unito.io)

**Comment by dennisocana** [comment]
Agreed on this approach which is better long-term and requires medium effort to implement.
