### ISSUE TITLE
Remove duplicated NetworkStatus

### ISSUE THREAD

**Issue by Nullably** [CoinAlpha/hummingbot#4526]
## Why
There are 2 definitions of the exact same class NetworkStatus on `network_base` and `network_iterator`, this causes confusion and wrong import.

## What
* Remove one of the definition
* Refactor code where the class is imported as needed.

## Definition of Done
* No more duplicate.

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1pd0bzg) by [Unito](https://www.unito.io)

**Comment by dennisocana** [comment]
This task is complete. Thanks @blakephillips for contributing!
