### ISSUE TITLE
Replace old dYdX library in dYdX spot connector

### ISSUE THREAD

**Issue by aarmoa** [CoinAlpha/hummingbot#4530]
## Why?
The dYdX spot connector was developed using a previous version of dYdX API, that is no longer the official one. In their documentation dYdX now suggests to use API V3.
The library dydx-python is not actively maintained any more, and is starting to cause dependencies versions issues.

## What?
Replace the use of dydx-python for dydx-v3-python in the dYdX spot connector. Remove dydx-python from the list of dependencies.

## DoD
* [ ] dydx-python is no longer a dependency

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1pd0brt) by [Unito](https://www.unito.io)

**Comment by dennisocana** [comment]
Closing this task since we will soon deprecate this connector : https://github.com/CoinAlpha/hummingbot/issues/4734
