### ISSUE TITLE
TWAP - decimal/integer required parameters accepts string as input

### ISSUE THREAD

**Issue by RC-13** [CoinAlpha/hummingbot#4559]
**Describe the bug**
When creating a TWAP strategy, the following parameters currently doesn't have any validators: 
 `target_asset_amount `
`order_step_size `
`order_price `
`order_delay_time `
`cancel_order_wait_time `
which results to accepting a string as input although, the strategy doesn't start and throws error in the log pane. It would be best to be able to filter the input immediately.

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):

1. Create a TWAP strategy
1. When asked for the value of any of the parameters above, add a string input or
1. Create a TWAP strategy with correct values and config each parameters individually and add a string input.

**Screenshots**
![image](https://user-images.githubusercontent.com/57189990/138624033-c7afd54d-5af2-4b7c-9874-563cd9de3101.png)

**Release version**
0.44.0

**Attachments**

[logs_hummingbot.log](https://github.com/CoinAlpha/hummingbot/files/7406774/logs_hummingbot.log)

_WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!_

**Optional: your discord username:**

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rp2eg0) by [Unito](https://www.unito.io)

**Comment by dennisocana** [comment]
Fixed in version 0.46 release
