### ISSUE TITLE
Perpetual Market Making Rework

### ISSUE THREAD

**Issue by Nullably** [CoinAlpha/hummingbot#4565]
## Why
To simply the strategy, remove unneeded features and fix bugs.

## What
Remove the following configurations and their related features:

* [x] ts_activation_spread
* [x] ts_callback_rate
* ~stop_loss_spread~ 
* [x] close_position_order_type 
* [x] ping_pong_enabled
* [x] hanging_orders_enabled
* [x] hanging_orders_cancel_pct
* [x] add_transaction_costs
* [x] take_if_crossed (always on, see below)
* [x] position_management (keep profit taking, see below)

Add new configuration:

* [x] stop_loss_slippage_buffer (not prompted on create, default value of 0.5)
  prompt: `How much buffer do you want to add to the price to account for slippage for profit taking orders (Enter 1 for 1%)? >>> `

Updates:

* [x] Use LIMIT order type for any order in this strategy, this also means take_if_crossed is always on.
* [x] Profit taking is always on by default, trailing stop loss features removed. long_profit_taking_spread and short_profit_taking_spread are always required during configuration.

~Profit taking order retry logic:~
* [x] Stop loss order retry logic:
It has been decided that only stop loss orders require slippage and retry. Take profit orders are created before the market arrives to the price, meaning that the orders are already waiting to be filled beforehand (hence no need of slippage).

* The wait time between recreation of the stop loss order has to be configurable (default 10 minutes).
* For each retry, the order price is ~increased (decreased)~ decreased (increased) for sell (buy) order by `profit_taking_slippage_buffer` percent. The slippage percentage is applied also to the first stop loss order created. The price is determined as `(position entry price * (1 plus stop_loss_spread)) * (1 plus slippage_buffer)ˆnumberOfStopLossOrdersCreated`.
~* Maximum retries of 3~
~* The strategy pauses market making if there are outstanding unfilled profit taking orders.~

Code migration:

* Migrate code from Cython to Python only

Unit tests:

* Add unit tests to cover the entire strategy including existing and updated features (but not the removed features of course).

## Definition of Done
* Configuration and features updated as described
* Strategy code is in python 
* Unit tests cover the entire strategy

## Note
* See https://github.com/CoinAlpha/hummingbot/issues/4498#issuecomment-951506040 for more details on hedge mode for this strategy.
* This story is a summary from #4497 epic, to make it more actionable as discussed. 

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rp3zvv) by [Unito](https://www.unito.io)

**Comment by aarmoa** [comment]
Is it correct to remove *stop_loss_spread*? When removing it, any position will be instantly closed as soon as the price crosses the entry price in the contrary direction.
