### ISSUE TITLE
Order Funding Token for derivative trading

### ISSUE THREAD

**Issue by Nullably** [CoinAlpha/hummingbot#4573]
## Why
Currently, we assume quote token (e.g. USDT in BTC-USDT) is the required token to fund a new order (either buy or sell), this is not always the case, e.g. on Binance Future Coin-M, token to fund a new order is the base token, so are inverse perpetuals on ByBit. 

## What
We need to store this new information and make use of it effectively.

Trading Rule - Add new data fields

* buy_order_collateral_token (default value - quote token)
* sell_order_collateral_token (default value - base token)

Derivative connectors

* Set the new data fields to corresponding token when create/update trading rules
* Make sure this new data fields are populated correctly going forward 

A new common function `get_collateral_required`

* For a given exchange, trading pair, order type, price and amount, the function calculates and returns funding amount required for the order and funding token.
* This can be a function in connector base class, or in a common utils somewhere

Every Perpetual strategy (Perp-MM, Spot-Perp arb only):

* Refactor the logic where funding is calculated with the new `get_collateral_required` function

Fix Perpetual Market Making strategy:

* Currently the strategy checks balance for new orders incorrectly for sell orders, for (most) perpetual markets the quote token is required to place both buy and sell orders. See spot perpetual arbitrage strategy as an example.

## Definition of Done
- [ ] New data Trading Rule fields created and populated correctly
- [ ] Update the docs with the new functions that exchange implementations should consider

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rvvrm2) by [Unito](https://www.unito.io)

**Comment by dennisocana** [comment]
Pending from @phbrgnomo for suggestions to rename the word `funding`

**Comment by phbrgnomo** [comment]
To avoid confusion with Funding Rate, we should use `collateral_token` as the name for this story.
