### ISSUE TITLE
Refactor the calculation of the greek parameters (kappa, gamma and eta)

### ISSUE THREAD

**Issue by phbrgnomo** [CoinAlpha/hummingbot#4584]
## Description
As described on the epic #3286, the initial implementation of the automated calculation of the greek parameters made assumptions that weren't effective.

The calculation of these parameters will be refactores.

## Details
The three greek parameters calculation must be refactored based on the following criterea:

### **`gamma` (risk factor)**
This parameter represents the inventory risk the market maker is willing to take.
Since this is a decision taken by the market-maker, this will become a manual input - the market-maker will choose it's value.

The accepted values must be > 0, since with `gamma = 0` the model will create only symetrical spreads (reservation price = mid price)

### **`eta` (shape factor)**
Based on the [Fushimi-Rojas-Herman paper](https://stanford.edu/class/msande448/2018/Final/Reports/gr5.pdf), the shape factor is used to adjust the order sizes to avoid excess position accumulation on one side or another.

This is also a parameter that must be chosen by the market-maker, because it is also an adjustment factor for the market-maker risk.

Since this is a more advanced parameter, when creating a new strategy with `create`, this wont be prompted to the user, and it will have the default value set to 0.

The value of `eta` is limited to a value between 0 and 1. Any signal transformation need for execute the proper calculation will happen in the strategy code.

### **`kappa` (liquitidy factor)**

This parameter represents what is the existing liquidity on the order book of the market the strategy is running.

This value must be calculated based on the market's order book shape, and will use the model presented on [this paper](http://events.chairefdd.org/wp-content/uploads/2013/06/CAHIER_MICRO_1.pdf)

### **Removal of unnecessary parameters**

With this implementation of the greek parameters, some `config` parameters won't be needed anymore and will be removed:

* `min_spread`
* `max_spread`
* `vol_to_spread_multiplier`
* `volatility_sensibility`
* `inventory_risk_aversion`

### **Additional parameter**

Since the AS model doesn't consider the cost of trading fees, a new parameter will be needed to define what is the minimum spread allowed for the orders.

The minimum spread will consider the **total spread between the orders created by the strategy** (distance between bid and ask orders created by the strategy).

That way, if the trading fee is 0.1%, the market-maker can set this parameter to 0.2, so bid & ask orders created will never have a spread between them smaller than 0.2%.

## Completion requirements
* [ ] `kappa` calculation uses the model described above
* [ ] `gamma` is set to be entered manually, always < 1
* [ ] `eta` is set to be entered manually, but not prompted on `create`. The default value is set to 0
* [ ] removal of unnecessary parameter listed above
* [ ] new config parameter that defines the minimum allowed spread between bid & ask orders (use a different name than `min_spread` to avoid confusion with the first implementation

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1t75qb3) by [Unito](https://www.unito.io)

**Comment by mhrvth** [comment]
![image.png](https://images.zenhubusercontent.com/6109194f7cd3e475648ece12/3bee3de5-9b11-4b71-a795-69435fba154b)

gamma = 1 wouldn't make the reserved price equal to the mid price, gamma = 0 would 
I don't really see anything wrong with it anyway, the value should be just non-negative.

**Comment by mhrvth** [comment]
min_spread needs to remain, but won't mean the same thing as before.

**Comment by phbrgnomo** [comment]
> ![image.png](https://camo.githubusercontent.com/81a0040099ff1a89aedbe4f3d4cec8e632c021c1576483e21306e1a2932eddbf/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3631303931393466376364336534373536343865636531322f33626565336465352d396231312d346237312d613739352d363934333566626131353462)
> 
> gamma = 1 wouldn't make the reserved price equal to the mid price, gamma = 0 would I don't really see anything wrong with it anyway, the value should be just non-negative.

Yeah, my bad. I read it backwards on the paper. The closer gamma is to 0, the more symmetric the orders are. From the paper:

> The results of the simulations comparing the ‘inventory’ strategy for  ¼ 0.01 with the corresponding
‘symmetric’ strategy are displayed in table 2. This small value for  represents an investor who is close to risk neutral. The inventory effect is therefore much smaller and the P&L profiles of the two strategies are very similar, as illustrated in figure 3. In fact, in the limit as  !0 the two strategies are identical.
Finally, we display the performance of the two strategies for  ¼ 1 in table 3. This choice corresponds to a very risk averse investor, who will go to great lengths to avoid accumulating an inventory. This strategy produces low standard deviations of profits and final inventory, but generates more modest profits than the corresponding symmetric strategy

Fixing the description, for `gamma` > 0

> min_spread needs to remain, but won't mean the same thing as before as explained in "Additional parameter"

Yes. Just would change the config name to something different to avoid confusion with the "old" usage.

**Comment by mhrvth** [comment]
There will be a new parameter _level_distances_  to specify distances between order levels as a percentage of the spread because before they were calculated based on the min_spread and max_spread.

**Comment by albertchon** [comment]
@phbrgnomo would you mind elaborating on the rationale behind the kappa calculation methodology? Unfortunately the paper referenced is in French and a bit hard to penetrate 😅
