### ISSUE TITLE
test_run_til in ClockUnitTest fails randomly

### ISSUE THREAD

**Issue by aarmoa** [CoinAlpha/hummingbot#4608]
There is a problem with the test ClockUnitTest>>test_run_til that makes it fail randomly in the GitHub validation workflow. The problem is related to the way time is registered, causing the clock to finish but the assertion that comes afterwards to believe that the current time is less than the clock end time.

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1tcy5fx) by [Unito](https://www.unito.io)

**Comment by dennisocana** [comment]
The test failed twice consecutively earlier in https://github.com/CoinAlpha/hummingbot/pull/4563. The error did not show up the third time.

![image](https://user-images.githubusercontent.com/50150287/139630948-2d7fb5aa-5eed-4432-b21b-96b467cbf929.png)

Downloaded logs:
[1_build + stable tests.log](http
[logs_4902.zip](https://github.com/CoinAlpha/hummingbot/files/7451143/logs_4902.zip)
s://github.com/CoinAlpha/hummingbot/files/7451140/1_build.%2B.stable.tests.log)

**Comment by aarmoa** [comment]
@dennisocana the PR you mentioned is not using the latest changes in `development` branch. The PR I created with the tentative fix for this issue is not loaded in that branch.

**Comment by dennisocana** [comment]
Thanks @aarmoa for investigating. I will close this issue now.
