### ISSUE TITLE
Investigate how to proper handle gateway certificates inside the client

### ISSUE THREAD

**Issue by phbrgnomo** [CoinAlpha/hummingbot#4612]
- Major risk to consider: How to present from the UI perspective
- Focus on the websocket between client and gateway
- create gateway command must create and add the certificate to gateway container that is being created
- changes on passphrase needs to create a new one -> also implies on creating a new gateway container
- How to transfer an existing configuration (including certificates) to a new gateway container

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1tcyk76) by [Unito](https://www.unito.io)

**Comment by vic-en** [comment]
I recommend the following:
- We use `mkcert`(https://github.com/FiloSottile/mkcert) to create certificate into ./cert directory in Gateway project from script. This cert should also be mounted for Gateway docker instances.
- We also need to map the local system's root store into the client's docker container instance.

**Comment by martinkou** [comment]
Some comments from today's standup

1. Don't pollute the user's CA root. The CA certificates created by Hummingbot are intended for only communicating with the gateway, it's not intended to be system-wide trust root. Do please don't add the CA certificates to the system CA root. Besides, as I said, in Linux systems, the method and location for storing CA root certs is different depending on distribution and setup - so it's probably not a reliable method anyway.

2. Don't skip the passphrase for the SSL private key. This is the standard practice for setting up servers with SSL (e.g. Apache w/ HTTPS), let's not deviate from the current best practices and invent our own method w.r.t. encryption stuff. You generally don't want to deviate from best practices on infosec-related matters.

**Comment by vic-en** [comment]
Since we'll be going with the current approach, I create a new issue(https://github.com/coinalpha/hummingbot/issues/4694) for the benefit of users who will use Gateway as standalone. 

Hence, this issue can be closed.
