### ISSUE TITLE
[BUG] Exceeded Binance Hard-Limits 100k after spaming orders due to insufficient balance.

### ISSUE THREAD

**Issue by gruberx** [CoinAlpha/hummingbot#462]
**Describe the bug**
Bot getting an error: "Account has insufficient balance for requested action", but continued spaming send orders. After half a day of such work, an error began to come: "Too many new orders; current limit is 100000 orders per DAY". My account has exceeded the hard limit Binance - 100000 orders per 24 hours.

**Steps To Reproduce**
Strategy pure market making on Binance.
I set number_of_orders: 5
It should be a long time insufficient of funds for placing orders (My bot worked half a day in this mode)
Bot in the log received this error: binance.exceptions.BinanceAPIException: APIError(code=-2010): Account has insufficient balance for requested action.
After began to receive such an error: binance.exceptions.BinanceAPIException: APIError(code=-1015): Too many new orders; current limit is 100000 orders per DAY.

**Release version**
Version: dev-0.9.0

**Attachments**
Logs file is very big. If the full log is needed, I will post it on demand.
The first part of the log, where spam orders are visible.
[hummingbot_logs_-1.log](https://github.com/CoinAlpha/hummingbot/files/3341203/hummingbot_logs_-1.log)
The second part of the log where the error appeared: Too many new orders.
[hummingbot_logs_-2.log](https://github.com/CoinAlpha/hummingbot/files/3341209/hummingbot_logs_-2.log)
Configs
[Configs.zip](https://github.com/CoinAlpha/hummingbot/files/3341211/Configs.zip)

discord username: gruberx
ETH address: 0x73ad12c470cfed7c8d2b2c759c59e31F345CcB21

**Comment by chowryan** [comment]
make sure you don't have any open orders related to the trading currencies in your case, no other TNT or ETH orders. Right now we assume that total amount = available amount which will be fixed soon. You'll have to work within the binance order limit yourself, try increasing `cancel_order_wait_time` or reducing the `number_of_orders`.

**Comment by gruberx** [comment]
I found another reason that worsens the problem. Periodically appear lost orders, about which the bot does not know. If the average price goes higher or lower, these orders remain for a long time causing insufficient balance. Over time, the number of  lost orders may also increase. Perhaps this problem appears only with multiple orders. I can post logs.

**Comment by mifeng** [comment]
@gruberx Thanks, we are investigating the lost orders issue when running multiple orders: https://github.com/CoinAlpha/hummingbot/issues/493

**Comment by billwilson12** [comment]
I have this problem twice now with the exchange locking me out for My account had exceeded the hard limit Binance - 100000 orders per 24 hours. It is easy to get out of balance in value when sharp moves in the market happen. I want to be able start with a balance for example 80,000 of X token which will raise and  fall in value as the market moves, but no matter how far that move is if the bot can only use 50% (any %)  of the whole it could never have a failed order until the exchange minimum is reached. The current formula is 100% or nothing which requires manually buying or selling to keep a buffer.
