### ISSUE TITLE
Trades and Total P&L frozen in PMM

### ISSUE THREAD

**Issue by Nishan-Pradhan** [CoinAlpha/hummingbot#4621]
**Describe the bug**
When running `pure_market_making` the bottom of the terminal is freezing after some number of trades/time.

The number of trades and other information here is not updating and therefore not matching the `history` command output in the terminal.

This might have occurred after running `status --live`, then stopping it and then restarting `status --live` but im not entirely sure. 

**Screenshots**
![image](https://user-images.githubusercontent.com/61545498/139413334-1395da2a-2c6a-42d2-afa6-10219387c446.png)

**Release version**
0.44.0

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1tjhk21) by [Unito](https://www.unito.io)

**Comment by RC-13** [comment]
Same issue #4712
