### ISSUE TITLE
Rework the Time factor (T) on the Avellaneda strategy to allow an infinite time horizon

### ISSUE THREAD

**Issue by phbrgnomo** [CoinAlpha/hummingbot#4650]
## Description

Rework the way `(T-t)` is calculated inside the strategy and implement the infinite horizon timeframe

## Details

The AS model uses an start and stop trading time to calculate the reserved price and the optimal spreads. This is considered on the formula by the value of `(T-t)`, where `T` is the final time of the trading session and `t` is the current time.

Since crypto markets works 24/7, the current implementation considers the value of (T-t) as a cycle, where the user enters the `closing_time`, that defines how many hours a cycle will last (`closing_time = 1` the strategy will "restart" every one hour)

This time consideration on the AS paper is assuming the trader wants to end the trading session with the same inventory position he started, considering the market is open only a few hours during a trading day.

Based on that, we need to approach the time factor in three different cases:

A - The trader wants to run the bot 24/7, creating orders as long as the bot is running
B - The trader wants to run the bot only during a defined time during the day
C - The trader wants to run the bot 24 hours, but until a certain date

For each case, the following approach must be implemented:

A - The trader wants to run the bot 24/7, creating orders as long as the bot is running

Implement the infinite time horizon, as described on the paper (or any other following papers that made improvements over the original one)
![image.png](https://images.zenhubusercontent.com/5f64254ca13ff3717cc3a0c5/ba42dcf6-a726-4038-9ccc-ada45d272bb1)

B - The trader wants to run the bot only during a defined time during the day

Allow the trader to define an `open_trading_time` and a `close_trading_time`, where the original `(T-t)` would be used on the calculation. 

The bot would create new orders every day, but only if the current time is between `open_trading_time` and `close_trading_time`.

The value of `T` is equal to the `close_trading_time`, and the value of `t` is the current time

C - The trader wants to run the bot 24 hours, but only until a certain date

Similar to what is implemented on the TWAP strategy, the bot only starts to create new orders at the `start_trading_date_time` and stop the order creation at `stop_trading_date_time`.

In this case, the value of the terminal time `T` would be equal to the `stop_trading_time`, and `t` the current time.

## Definition of Done

- [ ] Remove  the current time horizon logic, including the `closing_time` configuration
- [ ] Add a config parameter for the user to choose wich type of time horizon he wants to use (`infinite_time`, `daily_trading_hours`, `fixed_end_date`) (these parameter names are just initial suggestions, they can be changed for a better description)
- [ ] Add the related time configuration for each of the time horizon:
  - `infinite` : no extra parameters needed
  - `daily_trading_hours` : `open_trade_hour` and `close_trade_hour`
  - `fixed_end_date` : `start_date_time` and `stop_date_time`
- [ ] Add the proper logic for each of the possible time horizon configurations

**Comment by mhrvth** [comment]
The equation for calculating the optimal spread for an infinite horizon:

![image.png](https://images.zenhubusercontent.com/6109194f7cd3e475648ece12/af156c27-4c70-4c5b-8499-48df3ab6cfe3)
