### ISSUE TITLE
Paper trade - Exchanges not appearing when creating a strategy on Docker build

### ISSUE THREAD

**Issue by rxlxrxsx** [CoinAlpha/hummingbot#4651]
**Describe the bug**
Paper trade exchanges are not showing when creating a strategy. This is observed to be happening on Docker build only.

**Steps To Reproduce**
1. Create any strategy that supports paper trading.

**Screenshots**
<img width="1422" alt="Screen Shot 2021-11-04 at 10 35 12 AM" src="https://user-images.githubusercontent.com/64377055/140248851-e8888e1e-6eec-479f-8b63-7535e7fd8b09.png">
<img width="215" alt="Screen Shot 2021-11-04 at 10 40 45 AM" src="https://user-images.githubusercontent.com/64377055/140248869-a4c7a704-9b00-4348-aafe-834c2160683b.png">
**Release version**
development-0.46.0

**Attachments**
[conf_global.yml.zip](https://github.com/CoinAlpha/hummingbot/files/7471928/conf_global.yml.zip)

**Comment by RC-13** [comment]
It looks like this is because the paper trade exchanges are not added on the setup.py file https://github.com/CoinAlpha/hummingbot/blob/9023822744202624fad276b326cc999b72048d67/setup.py#L52

**Comment by sisco0** [comment]
The _Docker_ version lacks the call for generating the _Paper trades_. The _non-Docker_ version contains it without inconvenience at `bin/hummingbot.py:52`.

You could see this by running the next commands to discover the problem in the _Docker_ container:
```bash
docker run --rm -u 0 -it coinalpha/hummingbot bash
apt update
apt install neovim -y
nvim bin/hummingbot.py
```

The _non-Docker_ version shows the command as expected. I have attached a screenshot as proof of evidence.
![image](https://user-images.githubusercontent.com/25695302/140661445-b1822c8e-0463-4d65-a4f3-f0308977caa0.png)
