### ISSUE TITLE
Migrate configurations from config manager to config manager v2

### ISSUE THREAD

**Issue by martinkou** [CoinAlpha/hummingbot#4654]
## Why

We have created a new config manager for gateway v2 in #4136. The next step is to migrate the current configurations.

## What

* Plan out and document down the mapping of flat configurations from the existing configuration manager to the name-spaced configuration manager.
  * Mapping from namespace to config entries.
  * Whether default configurations are needed.
* Write the JSON schemas for the newly defined config namespaces.
* Migrate default configurations inside modules to new configuration manager.
* Migrate configurations logic and config files to new configuration manager.

**Comment by Nullably** [comment]
@martinkou 
> Migrate default configurations inside modules to new configuration manager.

How should I approach this?
Should we have default config files, e.g. ethereum-defaults.json, where defaults are loaded and set on ConfigManagerV2? If we have default files, should they be specified on root.yml? e.g.
```
$namespace ethereum:
  configurationPath: ethereum.yml
  schemaPath: ethereum-schema.json
  defaultPath: ethereum-defaults.json

```
We can then update the config manager to first set defaults from these files

**Comment by martinkou** [comment]
No. The defaults are meant to be set into the `ConfigManagerV2` via the `setDefaults()` function.

e.g. let's say you're writing a Polygon connector, and you want to include some default network IDs - you can do something like this...

```
ConfigManagerV2.setDefaults("polygon", {
  networks: {
    mainnet: { ... },
    testnet_1: { ... },
    testnet_2: { ... },
    ...
  },
});
```

**Comment by Nullably** [comment]
@martinkou 
Shouldn't the all defaults be set as soon as the app starts, not at the modules? The reason is if `/config` endpoint is consumed, we'll have all the configs ready to provide.

**Comment by martinkou** [comment]
It should be ok architecturally.. my expectation is those defaults would go to the `*.config.ts` files like `ethereum.config.ts`. Those files are generally loaded with either the routes or the controller modules, which means they are imported from `app.ts`. At this moment we don't have any dynamic module loading on the routes.

So this means when `/config` is defined, the default configs should also be already defined.

**Comment by Nullably** [comment]
@martinkou 
Since we have templates for all our configs (https://github.com/CoinAlpha/hummingbot/issues/4735) , would it be simpler if the default values are specified in the templates?

**Comment by Nullably** [comment]
@martinkou A few more questions
* Where is `root.xml` going to reside in? 
* Do the config templates (from https://github.com/CoinAlpha/hummingbot/issues/4735) create and update config yml files to fill in default values?
