### ISSUE TITLE
[BUG] Can see balance but unable to trade

### ISSUE THREAD

**Issue by baconbkk** [CoinAlpha/hummingbot#467]
**Describe the bug**
// A clear and concise description of what the bug is.

When starting the Bot I can see the balance but it appears that the api is rejecting the trades.

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: ...
2. Start the bot using this command: ...
...

**Screenshots**
// If applicable, add screenshots to help explain your problem.

**Release version**
0.8.1
// Include your bot's version number (Can be found at the bottom left corner of your CLI).

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:** Orpheus
![Screenshot from 2019-07-01 10-29-59](https://user-images.githubusercontent.com/8854714/60409045-f154d800-9beb-11e9-9c92-414f590bfea4.png)
[hummingbot_logs_2019-06-30-12-03-36.log](https://github.com/CoinAlpha/hummingbot/files/3343853/hummingbot_logs_2019-06-30-12-03-36.log)

**Optional: your ETH address:** (If you want to participate in the bug bounty)

**Comment by veecos2** [comment]
Please refer to https://www.binance.com/en/support/articles/115000594711-Trading-Rule for minimum trade sizes. Kindly ensure that the total nominal value of your order is above the minimum notional as mentioned in the website. We have added warnings that the order will not be placed in the latest version, which will be releasing shortly.
