### ISSUE TITLE
Connect Terra [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by Facundo20** [CoinAlpha/hummingbot#4676]
**Describe the bug**
// Hi guys, I´m getting [Errno 2] No such file or directory when trying to connect to Terra. It ask me for address and seed, then the error. 

**Steps To Reproduce**
Windows binary install 0.45, two different PCs, and the same error in test drive / Paper_trade_mode 

Terra connector folder look like this: 
![image](https://user-images.githubusercontent.com/58235626/140825194-3aa7ef29-1f04-47b6-9b34-426b190c3135.png)

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: ...
2. Start the bot using this command: ...
...

**Screenshots**
![image](https://user-images.githubusercontent.com/58235626/140824993-0aa77a64-33ef-430d-bec5-1574e1019968.png)
**Release version**
Version 0.45.0

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those!

**Comment by cali-tomas** [comment]
Hi, you would need Gateway to use Terra. Which gateway is only available on Docker and source builds of the bot. Here's a link to our docs

- Gateway 
https://docs.hummingbot.io/protocols/gateway/#what-is-hummingbot-gateway

- Terra 
https://docs.hummingbot.io/protocols/terra/

Installation 
(Docker)
https://docs.hummingbot.io/installation/docker/

(Source)
https://docs.hummingbot.io/installation/source/

**Comment by dennisocana** [comment]
https://docs.hummingbot.io/protocols/terra/#connection
