### ISSUE TITLE
Prerequisite for Client to create and manage Gateway docker containers.

### ISSUE THREAD

**Issue by vic-en** [CoinAlpha/hummingbot#4679]
**To-Do:**
- Create a docker file to automate building of  image for Gateway v2.
- ~Update/add more bash scripts in Gateway's setup dir to do complete setup of configuration files.~
- Add docker library to client deps.

For users who want to only run Gateway docker instance without the client, we need to update the docker-commands related to Gateway in the Client's installation folder to pull the Gateway v2 image, exec the configuration setup scripts and start a container.

**Comment by aarmoa** [comment]
NOTE: Item 2 has been removed since in this task we just want to make sure we can create the docker image.

**Comment by Nullably** [comment]
The 3rd item doesn't make sense to me to be on this story. The dependencies should be added on the task which needs them (not this one).

**Comment by vic-en** [comment]
> The 3rd item doesn't make sense to me to be on this story. The dependencies should be added on the task which needs them (not this one).

@Nullably Does it really matter? It's going to be added anyway, now or later. I added it because it was among the things that came to my mind when I was thinking of the prerequisites for the next task in the epic. Again, it doesn't matter if its here or in the next task. 
Also, all that's going to happen is we'll add a single line of code. I don't think we need to waste much time deciding where it should belong and updating tickets unnecessary. Lastly, pls keep in mind that this ticket is estimated with the hope that the tasks listed will be executed.

**Comment by Nullably** [comment]
@vic-en Please don't take this a wrong way. No, it's not a big deal, I should have explained a bit more. It's hard to know the exact library you need until you need to use it for something and this ticket has make no use of the library for anything here (I think that's in another ticket?)

**Comment by vic-en** [comment]
@Nullably ok, no worries. Feel free to add it anytime.

For whenever you decide, we'll be using [docker 5.0.3](https://pypi.org/project/docker/). It was what I used while testing during the investigation task for this epic.
