### ISSUE TITLE
Rogue Orders Created on Ascendex

### ISSUE THREAD

**Issue by DeFiSimon** [CoinAlpha/hummingbot#4682]
**Describe the bug**
When running multiple bots, sometimes a Liquidity Mining or Pure MM bot on Ascendex will encounter an error while creating new orders (when refreshing). The order is still created but not tracked by the bot, leaving open orders piling up. Also displays error about other pairs at the same time, could be related.

**Steps To Reproduce**

Run a few Pure MM bot on Ascendex with very short refresh rate (30 seconds or less), usually happens every hour or so.

See error on logfile at timestamp 2021/11/09 16:43:19

Config attached

**Screenshots**
![image](https://user-images.githubusercontent.com/83984738/141030803-2e45427c-0e1a-4fd7-9228-9243a0749b36.png)

**Release version**
Binary, Windows, 0.45.0

**Attachments**
[ConfigAndLogs.zip](https://github.com/CoinAlpha/hummingbot/files/7509056/ConfigAndLogs.zip)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**
Psy7y

**Comment by RC-13** [comment]
This issue is the same with this ticket #3970

**Comment by RC-13** [comment]
Fix has been merged to the development branch, closing ticket.
