### ISSUE TITLE
Investigate a better way of applying budget constraints to proposals in [spot] strategies

### ISSUE THREAD

**Issue by petioptrv** [CoinAlpha/hummingbot#4687]
# Why
Spot strategies (e.g. PMM, liquidity mining, the spot portion of the spot-perp arb) currently use the following logic to apply budget constraints to proposals:
- For buy proposals:
    - The true size is calculated as the proposed size plus the exchange fee (a percentage of the size)
    - If there is not enough quote funds, the proposal's size is adjusted to take up the remainder of the quote balance, all the while taking for granted that fees are added onto the order size
- For sell proposals:
    - The true size remains as is on the proposal
    - If there is not enough quote funds, the proposal's size is adjusted to take up the remainder of the base balance

This approach conservatively assumes that exchange fees are added onto the buy order before the fact, but are subtracted from the funds gained by the sell order after the fact. This is not always the case. 

For instance, Binance applies the fees to the buy order after the fact. For example, if the user is placing a buy order for 100 DOGE and the fee is 1%, they will be charged 100 DOGE worth of the quote asset, but will receive 99 DOGE. This pattern still fits within the confines of the outlined worst-case scenario above, but can lead to sub-optimal allocation of the funds.

Worst is the case of Bittrex, which [always charges fees in the quote asset](https://bittrex.zendesk.com/hc/en-us/articles/115000199651-Bittrex-fees). In that case, both buys and sells deduct from the total quote asset available, and the final buy order that is supposedly adjusted to take up the remainder of the available quote asset would potentially be rejected or unable to fill.

# What
Re-think the place where budget constraint adjustment happens. It should be dependent on the exchange rather than the strategy (although, the logic could probably live in a helper object that is passed by the exchange to the strategy - one that allows for hypothetical proposal registering and knows the user's exchange balance for the relevant tokens).

# Definition of Done
- [ ] Explore the various ways in which exchanges calculate and apply fees and come up with a suitable approach to applying budget constraints to strategy proposals.

**Comment by petioptrv** [comment]
@Nullably and @CrimsonJacket, based on our discussion today, feel free to add any details that I've missed

**Comment by dennisocana** [comment]
Set estimate to 1 and moved to ready for development.

**Comment by petioptrv** [comment]
Resolved in #4573
