### ISSUE TITLE
[BUG] connect okex error: [<class 'decimal.ConversionSyntax'>]     

### ISSUE THREAD

**Issue by daizong** [CoinAlpha/hummingbot#4690]
**Describe the bug**
connect okex

Enter your OKEx API key >>> ************************************

Enter your OKEx secret key >>> ********************************

Enter your OKEx passphrase key >>> **************

Error: [<class 'decimal.ConversionSyntax'>]                      

**Release version**
0.45.0

**Comment by gerald-hb** [comment]
Hello @daizong 

I believe this is the same issue with this github ticket - https://github.com/CoinAlpha/hummingbot/issues/4287 

The solution is to change the trade mode to simple. 

I hope this helps.

**Comment by daizong** [comment]
> Hello @daizong
> 
> I believe this is the same issue with this github ticket - #4287
> 
> The solution is to change the trade mode to simple.
> 
> I hope this helps.

thanks.
