### ISSUE TITLE
Add Gateway create command

### ISSUE THREAD

**Issue by vic-en** [CoinAlpha/hummingbot#4698]
## Why
See the Hummingbot Setup Experience section of https://www.notion.so/hummingbot/First-Time-User-Experience-6efacde002604881b81b079352d6845e

## What
- Add a `gateway create` command using docker python library(https://docker-py.readthedocs.io/en/stable/), that does the following:
  1. Check whether there's an existing gateway configuration. If yes - ask whether to erase the existing gateway configuration (along with the existing Docker container if there's one). If not, proceed to the next step.
  1. Check, and create if not existing, the SSL certificates for both Hummingbot and gateway.
  1. Check, and create if not existing, the Docker container for running Hummingbot gateway.

 **NOTE:**
  For setup questions - whenever reasonable defaults are available (e.g. use main net for Ethereum, auto-calculate names for Docker containers, etc.), the setup prompt should just use the default without asking the user. Only essential parameters like Infura API key and SSL certificate passphrase should need user intervention. If the user wants to change other detailed parameters, e.g. he wants to switch to Kovan, he should use `gateway config`.

**Comment by martinkou** [comment]
The `gateway create` command should give users a working gateway after it's completed, for users with Infura keys.

During the create command, it should ask two questions

 1. Do you have an Infura API key? (Yes / No)
 2. What is your Infura API key?

If the user answers "No" for question 1, then question 2 is skipped, and there should be a message telling the user to run `gateway config` to configure the node API URLs himself.

**Comment by martinkou** [comment]
@mifeng please take a look at the above UX and see if you're ok with it.

**Comment by mifeng** [comment]
I propose a slightly different set of questions to make it easier to add other providers like Alchemy in the future:

- `Enter your node provider (infura / custom)`
- (if infura) `Enter your Infura API key`
- (if custom) `Enter your node's RPC port (i.e. http://localhost:8545)`

I think we can assume that a user using Gateway this way will always start by configuring Ethereum, so I don't think we need to consider setting up other blockchains yet.
