### ISSUE TITLE
[Feature] When bot is winding down explain what specifically the cause

### ISSUE THREAD

**Issue by Oldman-Sam** [CoinAlpha/hummingbot#470]
**Feature Suggestion**
When bot is winding down explain what specifically the cause 

**Impact**
So there is less guess work for the user, chances are the bot lost too much money but when the bot becomes more complex maybe there will be other causes.

**Comment by mifeng** [comment]
@Oldman-Sam The only time when the bot should automatically winds down is because of the stop-loss trigger. We can consider adding more descriptive messages to inform users when that occurs.

**Comment by Oldman-Sam** [comment]
That's fine, maybe to help new users so they aren't initially confused.

**Comment by yzhang1994** [comment]
@Oldman-Sam With the 0.10.0 release, the new kill switch should notify the user about bot wind down and the cause as well. Hope this helps.
