### ISSUE TITLE
Gate IO order book depth error

### ISSUE THREAD

**Issue by leastchaos** [CoinAlpha/hummingbot#4710]
**Describe the bug**
// A clear and concise description of what the bug is.
Order depth of gate io is not deep enough/fully loaded.
There is sufficient depth on the exchange >1 however, setting a bid depth of 1 will already result in error due to NaN as no order depth data is found.
The order book depth live data shows there is NaN at a very low order depth resulting in this issue.

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: ...
2. Start the bot using this command: ...
...
load config and run order_book --lines 30 -- live

**Screenshots**
// If applicable, add screenshots to help explain your problem.

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).
0.45.0 master source
**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 
[conf_pure_mm_gate.zip](https://github.com/CoinAlpha/hummingbot/files/7534098/conf_pure_mm_gate.zip)
![image](https://user-images.githubusercontent.com/64965782/141688627-40b2eb9b-ed9f-49fb-aa51-0be8e759348c.png)

https://user-images.githubusercontent.com/64965782/141688624-22db417b-4b9e-4fba-90e9-42aee6f58e9f.mp4

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by aarmoa** [comment]
I think this issue could be solved with the changes added in #4756. The original implementation was replacing the local order book with a partial snapshot of depth 5 because the connector was registering to snapshot endpoint that should not be used.
