### ISSUE TITLE
New exchangeInfo API endpoint

### ISSUE THREAD

**Issue by Nullably** [CoinAlpha/hummingbot#4711]
## Why
To provide exchange information for all Gateway exchanges. Initially, the data we need is the networks on which the exchanges can be configured.

## What
The new endpoint does not take any parameters. The response is something like below 
```
{
    exchanges: [
        {
            exchang: uniswap
            chains: [
                {
                    chain: ethereum
                    network: [ mainnet, kovan ]
                }
            ]
        },
        {
            exchange: pangolin
            chains: [
                {
                    chain: avalanche
                    network: [ mainnet, fuji-testnet ]
                }
            ]
        }
    ]
}
```

The API endpoint name and response format can be changed to conform to current Gateway standard.

## Definition of Done
- New endpoint created along with unit tests

**Comment by mifeng** [comment]
LGTM - I suggest `exchange` instead of `dex`

**Comment by Nullably** [comment]
Superseded by https://github.com/CoinAlpha/hummingbot/issues/4730
