### ISSUE TITLE
Gateway DEX and chain configuration in Hummingbot

### ISSUE THREAD

**Issue by Nullably** [CoinAlpha/hummingbot#4713]
## Why
To provide user with the current Gateway chain connection configuration. Initially, the user can specify only one chain connection on Gateway. 

## What
- Display the current Gateway chain and network  on the top status bar (only when user uses Gateway), suggested format is `chain: ethereum -mainnet`
- The chain and network can be updated by current `gateway update` command, e.g. `gateway update CHAIN` to update the current chain setting.
- Filter a list of connectors (when configuring a strategy) depending on the network setting, e.g. `pangolin` does not appear when `CHAIN` is ethereum (but `uniswap` and `balancer` do)
- Create new `gateway list-connectors` command to display DEX data from  (https://github.com/coinalpha/hummingbot/issues/4711)

## Definition of Done
- Top status bar updated
- Connectors options filtered.
- New command created.

**Comment by mifeng** [comment]
LGTM

**Comment by Nullably** [comment]
Superseded by https://github.com/CoinAlpha/hummingbot/issues/4732 and https://github.com/CoinAlpha/hummingbot/issues/4733
