### ISSUE TITLE
Update chain configuration

### ISSUE THREAD

**Issue by Nullably** [CoinAlpha/hummingbot#4714]
## Why
Based on our last stand-up (Nov 12th), initially we want to limit the connection to only one chain at a time, some configs in gateway-config need to be updated to reflect this.

## What
Create 2 new configs: `CHAIN` and `NETWORK` to replace `ETHEREUM_CHAIN` and `AVALANCHE_CHAIN`. CHAIN refers to the current blockchain Gateway connects to e.g. ethereum, avalanche. NETWORK is the chain network of the blockchain e.g. mainnet, kovan.

Refactor the code base where the old configs are referred to.

## Definition of Done
New configs created, `ETHEREUM_CHAIN` and `AVALANCHE_CHAIN` removed.

**Comment by mifeng** [comment]
LGTM - note that it's likely we will enable connecting to multiple chains in the future, so you may want to use a list of CHAIN/NETWORK pairs

**Comment by Nullably** [comment]
Superseded by https://github.com/CoinAlpha/hummingbot/issues/4729
