### ISSUE TITLE
Design multi-wallet architecture

### ISSUE THREAD

**Issue by mifeng** [CoinAlpha/hummingbot#4726]
As discussed in today's standup, we decided to allow users to interact with multiple blockchains simultaneously after issue #4263, because doing so now would be simpler than accommodating it later on.

However, the standup raised the issue that to enable users to interact with multiple blockchains, we should accommodate the need to allow users to maintain multiple wallets so that they can interact with multiple blockchains.

We decided to accommodate multiple wallets into the client/Gateway architecture now. Below are the work items related to this effort:

1. Change nonceManager so that it uses different wallet instances: Victor mentioned that we should look at the old gateway-v1 nonceManager design.

2. Client should include specify wallet address and handle wallet-related errors in requests, since if the client maintains multiple wallets, it has to tell Gateway which to use. See diagram below that Paulo created:

![image (9).png](https://images.zenhubusercontent.com/545072957c6ccc6277a5c098/11d0d550-b49d-4b41-957c-54c70a5969dc)

3. Tasks related to supporting multiple wallets in the client user interface. I'm not sure we tackle these now, but here are what I think are the main tasks:

a. Add a `wallet` command to add, list and export wallets
a. Change `balance` command so that you can run `balance -wallet [wallet address] or -chain [chain] -exchange [exchange]" to query balances 

@Nullably Lets discuss this with you during your morning

**Comment by Nullably** [comment]
The key to achieve this is to add network and wallet to Gate exchange configs: https://github.com/CoinAlpha/hummingbot/issues/4729
For client, we'll need to
https://github.com/CoinAlpha/hummingbot/issues/4732
https://github.com/CoinAlpha/hummingbot/issues/4733

**Comment by Nullably** [comment]
We'll also need to design how we're going to manage private keys, I'll investigate and create a story for this.

**Comment by Nullably** [comment]
I added Wallet Management ticket. https://github.com/CoinAlpha/hummingbot/issues/4798
if the design passes review, we can close off this ticket.
