### ISSUE TITLE
Gate_io - Order_book data is not synchronized with the exchange order_book

### ISSUE THREAD

**Issue by bluecammut** [CoinAlpha/hummingbot#4742]
**Describe the bug**
When running the PMM strategy on differents connectors, I notice that some of them are not showing accurate data.

**Steps To Reproduce**
1. Create a PMM strategy
2. Start the strategy
3. Run the "order_book --live" command
4. compare the HBOT order book info vs exchange info
Note: try to select a market which is not too busy so you can compare easily.

**Screenshots**
<img width="1440" alt="gateIO copy" src="https://user-images.githubusercontent.com/79382440/142129010-c05197af-7142-48f7-8bbe-c250a3297b49.png">

**Release version**
Branch Master - MAC source build 0.46

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by bluecammut** [comment]
as a result of the order book desynchronization, the output in order_book, ticker and the best bid/ask in status also are incorrect or do not match with the exchange

**Comment by aarmoa** [comment]
I think this issue could be solved with the fix we are adding in #4756. @rxlxrxsx found the same problem while testing the PR and I have added some changes to solve the problem.
