### ISSUE TITLE
21:58:32 root - Error loading configs. Your config file may be corrupt.

### ISSUE THREAD

**Issue by tonytungtung** [CoinAlpha/hummingbot#4745]
**Describe the bug**
// A clear and concise description of what the bug is.
21:58:32
root - Error loading configs. Your config file may be corrupt. 'Cp950' codec can't decode byte Oxe2 in position 5317: illegal multibyte sequence (See log file for stack trace dump)

21:58:32
root- Error writing configs: 'cp950' codec can't decode byte 0xe2 in position 5317: illegal multibyte sequence (See log file for stack trace dump)

Traceback (most recent call last) :
File
"bin\bot
line 75,
in <modules
File
"asyncio\base events.py"
line 616, in run_until_complete
File
"bin\bot'
line 68,
in main
File
"hummingbot\corelutilslasync_utils.py
line 22.
in safe gather
File
"hummingbot\client \hunningbot application.py"
line 204,
in run
File
"hummingbot\clientluilhummingbot_cli.py"
line 74.
in run
File
"hummingbot\clientluilstyle.py"
line 26.
File
"hummingbot\clientluilstyle.py'
in load _style
line 89, in hex_to_ansi
AttributeError:
"'NoneType'
object has no attribute
"replace
(9936] Failed to execute script bot

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: ...
2. Start the bot using this command: ...
...

**Screenshots**
// If applicable, add screenshots to help explain your problem.

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by RC-13** [comment]
@tonytungtung if you are using an old configuration from older version of the Hummingbot client, I suggest to re-create the strategy file.

**Comment by RC-13** [comment]
Closing ticket for now, let us know if the step above did not help.
