### ISSUE TITLE
Avellaneda Stoikov marketmaking - Spread issues when min max both below 0.1

### ISSUE THREAD

**Issue by tronder88** [CoinAlpha/hummingbot#4755]
**Describe the bug**
// A clear and concise description of what the bug is.

Having issues with spread beeing set above max when using max spread 0.1.
Minimum spread set 0.01

I have add transaction cost = true setting. as not to "loose" cash
Fees are 0.5%

Using Coinbase Pro

I am expecting max spread to be 0.6. Max spread 0.1 plus fees of 0.5%. But something is going on here

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: ...
2. Start the bot using this command: ...
...

**Screenshots**
// If applicable, add screenshots to help explain your problem.

![Bug1](https://user-images.githubusercontent.com/9850293/142405805-ec67e6cf-3150-4296-aa17-c22642c9dc27.PNG)

![bug2](https://user-images.githubusercontent.com/9850293/142406120-3d90ec6b-dacb-4c2e-9b99-bdccfcbac410.PNG)

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).
0.45 - windows install

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by gerald-hb** [comment]
Hello @tronder88 

I'll check this and try to replicate it on my end. Can you also send us a copy of your `logs` so we can check if there are any unusual error?
Thanks,

**Comment by gerald-hb** [comment]
Hello @tronder88 

Just to check, I dont think `add_transaction_cost` is calculated that way. It affect/adjust the bid and ask orders but not the spread. More information on our docs https://docs.hummingbot.io/strategy-configs/add-transaction-costs/ 

We will still check this issue so when you have the `logs` please send it here.

Thanks,

**Comment by RC-13** [comment]
@tronder88 Kindly try the avellaneda market strategy in the latest version of Hummingbot. The strategy has been improve and no longer uses the `min and max` spread parameter. I'll be closing this ticket, and f you encounter a different issue, feel free to open a new one.
