### ISSUE TITLE
[Gateway] Wallet management

### ISSUE THREAD

**Issue by Nullably** [CoinAlpha/hummingbot#4798]
## Why
To enhance Gateway to be able to handle and manage multiple wallets.

## What
- Add a new `wallets` folder under `conf`
- Add a new `add_wallet` API endpoint which takes a chain name and a private key as its parameters. The endpoint then creates a wallet json file for it. The wallet file name is the wallet address (public key) e.g. `0x123433434343.json` in a chain sub folder under `wallets`, e.g. `/wallets/ethereum/`. The wallet private key is encrypted with Gateway server pass phase. 
- Add a new `remove_wallet` API endpoint which takes a chain name and wallet address (public key) as its parameter. The endpoint removes the corresponding wallet 
- Add a new `get_wallets` API endpoint which takes no parameter, and returns a list of chain and its wallets (make sure to not return private key) e.g. 
```
[ {'chain': 'ethereum', wallet_addresses: ['0x123433434343', '0x000000000000'] }]
``` 

## Suggested solution

WalletManager class: a singleton that provides functionalities for adding, removing, listing, encrypting and decrypting wallets. 

A private key can be accessed for a given public key and chain name, e.g. `WalletManager.instance.getPrivateKey(chainName, publicKey)`

## Definition of Done
- End points are created and functioning.
- wallet files is created and encrypted.
- Ethereum wallet file can be imported in Metamask.

**Comment by martinkou** [comment]
Since we're going to share the encrypted wallet files between Hummingbot and gateway v2 - there should be no need for gateway to add or remove wallet keys by itself. Also, we should not store the private keys in an unencrypted form in any config files.

**Comment by Nullably** [comment]
@martinkou The wallet files in Hummingbot are encrypted with Hummingbot password (not pass phase) which Gateway has no access to. Also we need to make this wallet management solution for a stand-alone Gateway.

> Also, we should not store the private keys in an unencrypted form in any config files.

The `wallets.json` file (the entire content) is encrypted with pass phase.

My only concern on my suggested solution is to add a wallet to Gateway, the private key is still exposed on the API call.

**Comment by martinkou** [comment]
Had a chat w/ @Nullably tonight. Hummingbot client is going to stop managing the Ethereum wallets soon, so his proposal actually makes sense - gateway v2 should be managing the wallets going forward.

The only thing of note after the discussion is that Hummingbot will be sharing the passphrase with gateway v2, s.t. no user input will be needed when starting gateway v2. Coz Hummingbot will provide the passphrase to gateway v2 for decrypting the wallet files.
