### ISSUE TITLE
Spot perp future arbitrage: Unexpected error while processing event 102, 103, 107, 201

### ISSUE THREAD

**Issue by Notoooriou5** [CoinAlpha/hummingbot#4802]
**Describe the bug**
// Errors occur after placing a trade. Once errors occur the bot continues to trade but does not record any further history of trades, P/L is no longer update, and once the bot is stopped it cannot be restarted, connectors drop out. Bot must be rebooted to start again.
I have had the same errors using windows, ubuntu 20 in windows docker, and ubuntu 20 using linux docker, tried both latest and development versions.

**Steps To Reproduce**
// load config and start bot.

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: snapshot attached

**Screenshots**
// Screenshots of config setup, snapshot of errors, log file attached

**Release version**
// 0.45.0

Discord: Notoooriou5

![tlm bug feed](https://user-images.githubusercontent.com/94784165/143368342-fd1a36ad-d091-46ef-8bd9-c3dd2a2030f1.JPG)
![tlm bug config](https://user-images.githubusercontent.com/94784165/143368000-7cef8d2f-42f1-4503-baf3-42e901517373.JPG)
[logs_sp_tlm_usdt_narrow.log](https://github.com/CoinAlpha/hummingbot/files/7599770/logs_sp_tlm_usdt_narrow.log)

**Comment by RC-13** [comment]
Same issue with #4564, a workaround that you can try is to delete the current sqlite file found in the data folder of your hummingbot directory and restart the bot.

**Comment by Notoooriou5** [comment]
> sqlite fil

no success there unfortunately, i removed the file but the errors persist

**Comment by Notoooriou5** [comment]
i have also tried this setup on a different pair but the same error

**Comment by RC-13** [comment]
Thanks for the update @Notoooriou5 I'll close this ticket and link it on the original one to avoid having duplicate issues.

**Comment by RC-13** [comment]
Closing duplicate ticket
