### ISSUE TITLE
[Feature] Adjust refresh rate and bid place threshol

### ISSUE THREAD

**Issue by Oldman-Sam** [CoinAlpha/hummingbot#481]
**Feature Suggestion**
Adjust refresh rate and bid place threshold on the fly with bot commands. Possibly expose order amount to this for pure-marketing.

**Impact**
Essentially so users who are away from their computer can use their telegram bot to adjust the bot on the fly in case markets change against their favor. 

**Additional context**
There should probably be two variations of change. One that temporarily changes the settings like "refresh" so all future orders use the new refresh rate but it will reset if the bot is stopped and started again. The other would be a more permanent call like "set-refresh" so that even if the bot has a reset the new refresh rate is in place. 

This would be the same for the other settings.

**Comment by mifeng** [comment]
Agree that this is something that we should do across all strategies. There are certain configuration parameters which should be allowed to change without starting and stopping the bot, such as:
* spread
* order amount
* refresh frequency
* etc

**Comment by mifeng** [comment]
Fixed by https://github.com/CoinAlpha/hummingbot/pull/1544
