### ISSUE TITLE
[BUG] Half Leg Orders & Minimum Size Threshold

### ISSUE THREAD

**Issue by joesixpack** [CoinAlpha/hummingbot#502]
**Describe the bug**
Endlessly sends one half of the pair when one leg meets the minimum size threshold but not the other.

**Steps To Reproduce**
Setup pure-mm-strategy on Binance with near minimum size qty.  Config file is in the zip.

**Screenshots**
![image](https://user-images.githubusercontent.com/23145642/60723444-7e4baa00-9ee8-11e9-8768-d481acfbe518.png)
![image](https://user-images.githubusercontent.com/23145642/60723470-8dcaf300-9ee8-11e9-963c-31abf1cd95f1.png)

**Release version**
0.9.1

**Attachments**
[logs.zip](https://github.com/CoinAlpha/hummingbot/files/3362778/logs.zip)

Optional: your ETH address: 0x2F6102a60813aF809C8dA5f46Ceb1D022dd718f2

**Comment by mifeng** [comment]
This is the same issue as https://github.com/CoinAlpha/hummingbot/issues/493. We are investigating now.
