### ISSUE TITLE
[Feature] Paper Trading / Backtesting

### ISSUE THREAD

**Issue by leovigna** [CoinAlpha/hummingbot#503]
**Feature Suggestion**
I'm not sure if this is currently supported but I believe Paper Trading / Backtesting capabilities would enable the development of more complex trading strategies. Currently it seems one has to have API keys and actually trade to get an estimation of performance which would become quite risky for users testing out new strategies.

**Impact**
Enable initial users to test out the platform with no funds needed.

**Additional context**
The Zipline library by Quantopian has similar ideas, but is more focused on traditional stocks (though can use custom data such as BTC price). Zipline also enables metrics such as Sharpe ratio which could also be an interesting feature for hummingbot.
https://github.com/quantopian/zipline

**Comment by mifeng** [comment]
Thanks for the suggestion. We have started working on a paper trading mode - it should be ready in a few weeks!

**Comment by andrewczgithub** [comment]
Cheers!
Really excited about the bot!
I might see if i can help with some python.
Looks awesome!
Best,
Andrew

**Comment by yzhang1994** [comment]
This is live in v.0.15.0
