### ISSUE TITLE
[Feature] Pure-MM Strategy: Allow for Fewer than Total Quantity of Multiple Orders per Side

### ISSUE THREAD

**Issue by carlolm** [CoinAlpha/hummingbot#517]
**Feature Suggestion**

When market making with multiple orders per side, allow for fewer than the total quantity of multiple orders per side.

***Current***:
The strategy will place orders on one side only if it has sufficient inventory for all of the multiple orders for that side; all-or-none.

For example, if you have 3 orders per side, the bot will only place orders for that side if you have enough inventory for placing all 3 orders.

***Desired***:
As long as you have inventory for any number of orders, place those orders.

In the example above, if you have enough inventory for 1 or 2 orders (< the total 3), place the 1 or 2 orders.

**Comment by ImTheDeveloper** [comment]
Definitely a good suggestion this is causing me consistent issues on idex

**Comment by fengkiej** [comment]
Also has this issue, creating pull request for our fix
