### ISSUE TITLE
[BUG] Idex timeout

### ISSUE THREAD

**Issue by smartbrain** [CoinAlpha/hummingbot#537]
**Describe the bug**
// A clear and concise description of what the bug is.

Fresh install. Trying to arbitrage radar_relay and idex. Keep getting idex timeout errors.

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Install from docker. Link idex and radar to metamask. Export metamask key for hummingbot config. Using Infura.io endpoint.

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: ...
2. Start the bot using this command: ...
...

#####################################
#####################################

# The following configuations are only required for the
# arbitrage strategy

# Exchange and token parameters
primary_market: radar_relay
secondary_market: idex
primary_market_symbol: USDC-DAI
secondary_market_symbol: USDC_DAI

# Minimum profitability target required to place an order
# Expressed in decimals: 0.01 = 1% target profit
min_profitability: 0.009

# For more detailed information, see:
# https://docs.hummingbot.io/strategies/arbitrage/#configuration-parameters

**Screenshots**
// If applicable, add screenshots to help explain your problem.

![Screenshot_2019-07-12_19-21-29](https://user-images.githubusercontent.com/4337062/61150487-750ba000-a4db-11e9-9d82-53316a631366.png)

**Release version**
// Include your bot's version number (Can be found at the bottom left corner of your CLI).
0.9.1

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

[hummingbot_logs_2019-07-12-17-57-50.log](https://github.com/CoinAlpha/hummingbot/files/3387580/hummingbot_logs_2019-07-12-17-57-50.log)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:** smartbrain
**Optional: your ETH address:** (If you want to participate in the bug bounty)

**Comment by smartbrain** [comment]
Asked in support and was told by Ryan to open a github issue instead. Have a feeling it's a noob mistake and I just have to enable something to get it working.

First day trying to get Hummingbot to work. Thanks.

**Comment by chowryan** [comment]
issue was fixed via discord.
