### ISSUE TITLE
[BUG]Error on config file even with fresh install

### ISSUE THREAD

**Issue by tetsuyari** [CoinAlpha/hummingbot#539]
**Describe the bug**
// A clear and concise description of what the bug is.
Error message stating config file is corrupted even though it is the first time config command is entered upon fresh install. Same behaviour is observed with 2 separate devices running on windows64

Would appreciate some advice on whether this is a known issue and if this issue should be resolved before further configuration with sensitive details should be commenced?

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:
- Running the bot off a fresh windows docker install following the step by step instructions on the official website.

- Behaviour occurs right after entering the config command for the first time.

- Have managed to reproduce the same result with 2 separate devices on windows64

**Screenshots**
// If applicable, add screenshots to help explain your problem.
![hmbot error1](https://user-images.githubusercontent.com/52836634/61151720-2d0b6e00-a519-11e9-9583-e15780f7f946.JPG)

**Release version**
// Include your bot's version number (Can be found at the bottom left corner of your CLI).
ver0.9.1
**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 
[hummingbot_logs_2019-07-12-03-43-07.log](https://github.com/CoinAlpha/hummingbot/files/3387670/hummingbot_logs_2019-07-12-03-43-07.log)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username: tetsuyari
**Optional: your ETH address: 0x2da4984e39F9b283A726A1259a9f068d1d0b98F3

**Comment by yzhang1994** [comment]
@tetsuyari Looks like there is an invalid value in your global config file. We can't really help you without looking at the file. You can attach it here but make sure you delete any secret API keys before.

**Comment by tetsuyari** [comment]
here you go


[conf_global.txt](https://github.com/CoinAlpha/hummingbot/files/3388468/conf_global.txt)

**Comment by tetsuyari** [comment]
Hi @yzhang1994 any more insights to the issue raised?

**Comment by yzhang1994** [comment]
@tetsuyari Yes so if you look at your config file line 7:
```binance_api_key: nullbinance_api_secret: nullcoinbase_pro_api_key: null```
3 different configs are saved on the same line.
Please change it to:
```
binance_api_key: null
binance_api_secret: null
coinbase_pro_api_key: null
...
```
Then it should work.

**Comment by tetsuyari** [comment]
thanks! let me give it a shot!

**Comment by tetsuyari** [comment]
Btw, I am using windows notepad to open this config file and there's no clear indication of line number and the text is just a long continuous string with no demarcation.

What should I open this file with ideally so that I can view the line numbers clearly?

**Comment by yzhang1994** [comment]
I see. I'm not familiar with windows myself. But if the default text editor doesn't work, you can try to download Sublime (https://www.sublimetext.com/3).

**Comment by tetsuyari** [comment]
thanks will try it!
