### ISSUE TITLE
[BUG] fatal:  Not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by jaswinkchopra** [CoinAlpha/hummingbot#580]
![Docker](https://user-images.githubusercontent.com/53235056/61740349-45626080-ad43-11e9-9eb8-0a9a610e3274.png)
**Describe the bug**
As per Carlo when we ran the ./start.sh script we face the below error

fatal: Not a git repository (or any of the parent directories): .git

**Steps To Reproduce**
Yesterday we followed the below steps 

wget https://raw.githubusercontent.com/CoinAlpha/hummingbot/refactor/docker-scripts/installation/docker-commands/create.sh
wget https://raw.githubusercontent.com/CoinAlpha/hummingbot/refactor/docker-scripts/installation/docker-commands/update.sh
wget https://raw.githubusercontent.com/CoinAlpha/hummingbot/refactor/docker-scripts/installation/docker-commands/start.sh
chmod a+x *.sh
./start.sh

**Screenshots**
// If applicable, add screenshots to help explain your problem.

**Release version**
// Include your bot's version number (Can be found at the bottom left corner of your CLI).
The hummingbot version is 0.10.1
**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**
**Optional: your ETH address:** (If you want to participate in the bug bounty)

**Comment by mifeng** [comment]
Per the screenshot, this is because you have already created those folders and have a running instance already.

Also, please follow the instructions in the bug issue template and add the content where indicated. The screenshot alone generally doesn't give us enough info to triage bugs.

**Comment by carlolm** [comment]
@mifeng this error message appears when someone exits from docker/hummingbot.
I think two resolutions (@martinkou ): 
1) copy the .git file to the docker image (Dockerfile)
2) find out why it's checking for the .git file on exit; if not necessary, remove that check

**Comment by carlolm** [comment]
fixed
