### ISSUE TITLE
[BUG]hummingbot.core.utils.kill_switch Error calculating profitability: 'ETH'

### ISSUE THREAD

**Issue by hongson1981** [CoinAlpha/hummingbot#611]
**Describe the bug**
2019-07-31 13:33:09,974 - hummingbot.core.utils.kill_switch - ERROR - Error calculating profitability: 'ETH'
Traceback (most recent call last):
  File "/hummingbot/core/utils/kill_switch.py", line 35, in check_profitability_loop
    self._profitability = self._hummingbot_application.calculate_profitability() / 1e2
  File "/hummingbot/client/command/history_command.py", line 122, in calculate_profitability
    performance_analysis: PerformanceAnalysis = self.get_performance_analysis_with_updated_balance()
  File "/hummingbot/client/command/history_command.py", line 73, in get_performance_analysis_with_updated_balance
    amount = self.starting_balances[asset_name][market_name] if is_starting \
KeyError: 'ETH'

**Steps To Reproduce**
**:
Here are the steps to reproduce the issue (see attachments in the section below):
1. Install version 0.11.1
2. Use the config
[conf_cross_exchange_market_making_strategy_0.txt](https://github.com/CoinAlpha/hummingbot/files/3452133/conf_cross_exchange_market_making_strategy_0.txt)
3. Run bot
 

...

**Screenshots**
// If applicable, add screenshots to help explain your problem.

**Release version**
0.11.1

**Attachments**
[hummingbot_logs_2019-07-31-13-26-16.log](https://github.com/CoinAlpha/hummingbot/files/3452150/hummingbot_logs_2019-07-31-13-26-16.log)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**
**Optional: your ETH address:** (If you want to participate in the bug bounty)

**Comment by hongson1981** [comment]
Update steps on dev.0.12.0 : 

    Install version 0.12
    Use the config
    conf_cross_exchange_market_making_strategy_0.txt
    Run bot
Stop bot
Start bot again

**Comment by yzhang1994** [comment]
This is fixed
