### ISSUE TITLE
[Feature] Add more exchanges to the list..

### ISSUE THREAD

**Issue by Lamonz88** [CoinAlpha/hummingbot#614]
Hello Everyone..Can we add more exchanges to the bot like Bittrex , Poloniex .? 

Thanks

**Comment by senjam008** [comment]
@Lamonz88  Hummingbot have plan to add more exchanges like the one you have mentioned.
More information can be found at https://docs.hummingbot.io/connectors/#hummingbot-supported-connectors .

**Comment by senjam008** [comment]
@Lamonz88  Hummingbot has plan to add more exchanges like the one you have mentioned.
More information can be found at https://docs.hummingbot.io/connectors/#hummingbot-supported-connectors .

**Comment by senjam008** [comment]
@Lamonz88   Hummingbot has plan to add more exchanges like the one you have mentioned. Bittrex is being released soon (within the next few weeks) but Poloniex is not yet on our road map. More information can be found at https://docs.hummingbot.io/connectors/#hummingbot-supported-connectors.

**Comment by Lamonz88** [comment]
That's great .  Looking forward to the release of update . !
