### ISSUE TITLE
[BUG] XEMM on single exchange with stable coins: taker trades >> maker trades

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#627]
**Describe the bug**

When the bot first ran it was only placing orders on the `maker_market`. But looking at the trade history, there are 1886 trades of variety of sizes (<$1 to ~$99) for the taker market and only 1 single trade of $99 value for the maker market.

Tried to replicate, but didn't see the behavior. We're still looking into this.

**Steps To Reproduce**
1. Set up bot with same strategy config in the attachment `link.yml`

2. Run with

```
maker_market_symbol: <BASE SYMBOL>/USDC
taker_market_symbol: <BASE SYMBOL>/USDT
```

**Screenshots**

![image](https://user-images.githubusercontent.com/50150287/62664962-2b19bb00-b9b0-11e9-8880-a1ffdde89677.png)
[Full report from Binance](https://github.com/CoinAlpha/hummingbot/files/3479238/full_as_reported_by_binance.xlsx)

**Release version**

`latest 0.11.0`

**Attachments**

[dirtycomputer.zip](https://github.com/CoinAlpha/hummingbot/files/3479275/dirtycomputer.zip)

**Discord username: dirtycomputer**

**Comment by carlolm** [comment]
Hummingbot version: dev-0.12.0 ("Created": "2019-07-30T17:17:57.399618579Z")

## Config files
[conf_cross_exchange_market_making_strategy_0.yml.txt](https://github.com/CoinAlpha/hummingbot/files/3483845/conf_cross_exchange_market_making_strategy_0.yml.txt)
[conf_global.yml.txt](https://github.com/CoinAlpha/hummingbot/files/3483846/conf_global.yml.txt)

## Binance Trade History
[Binance Trade History.xlsx](https://github.com/CoinAlpha/hummingbot/files/3483842/Binance.Trade.History.xlsx)

## Maker Orders on PAX

None are getting filled

<img width="1291" alt="Binance-maker-orders" src="https://user-images.githubusercontent.com/12274903/62740136-c714e800-b9eb-11e9-9919-614233cdf00a.png">

## Taker Orders on USDT

However, many taker orders are being created and filled:

<img width="1328" alt="Binance-taker-fills" src="https://user-images.githubusercontent.com/12274903/62740138-c7ad7e80-b9eb-11e9-8e39-47b85b675ae1.png">

**Comment by carlolm** [comment]
Fixed here: https://github.com/CoinAlpha/hummingbot/pull/662
