### ISSUE TITLE
[BUG] Trade type is always tagged as "Sell" 

### ISSUE THREAD

**Issue by rennel-tabing** [CoinAlpha/hummingbot#631]
**Describe the bug**
// Hummingbot shows 4 sell orders on History whilst Binance shows 2 buys and 2 sells. 

**Steps To Reproduce**
// Using Pure MM strategy on binance with ONE/USDT pair

Here are the steps to reproduce the issue (see attachments in the section below):
1. Do a fresh install of version 0.11.1
2. Run Pure MM strategy on binance.
3. Once orders are filled, binance account will show a mixed buy/sell transaction while the hummingbot history command shows all "sell" as a the trade_type

**Screenshots**

![image](https://user-images.githubusercontent.com/53868268/62707320-20b2ed80-b9bf-11e9-987a-e660f986bd12.png)

**Release version**
// 0.11.1

**Attachments**
// 
![image](https://user-images.githubusercontent.com/53868268/62707700-d54d0f00-b9bf-11e9-9c4d-e9849f87dc1f.png)

**Optional: your discord username: StartledMonkey#5707 
**Optional: your ETH address:** 0xb25228cddd4a37d9fba2640937366461bd21c97a

**Comment by rennel-tabing** [comment]
I am able to reproduce the issue using the dev-0.12.0 build
![image](https://user-images.githubusercontent.com/53868268/62709854-3676e180-b9c4-11e9-8c57-0966bc1b5aed.png)

**Comment by mifeng** [comment]
This will be fixed in the upcoming `v0.12.0` release.

**Comment by moraliang** [comment]
@rennel-tabing The ETH address is wrong. Please make sure we have the correct ETH address that the person actually has. Thanks.

**Comment by rennel-tabing** [comment]
I have reached out to the user to comment down his ETH wallet.

**Comment by dasalter** [comment]
Rennel, as requested my ETH address is 0xcF444A898778Ed425105Dc71482557da1d26cEeE

However, this has all been sorted out now and I greatfully received the bug bounty to the correct address last night (UTC time)
