### ISSUE TITLE
[BUG] History not tracking Original Inventory properly

### ISSUE THREAD

**Issue by adamnmcc** [CoinAlpha/hummingbot#664]
When the history the command is run, the Original Inventory changes when running multiple times.

The original Inventory should stay static from when the bot started allowing us to see the profit gained in the current session. 

![humminbot-history-issue](https://user-images.githubusercontent.com/2370463/62936261-4118e880-bdc1-11e9-8517-f6c7f5ea1648.PNG)

**Comment by rennel-tabing** [comment]
Starting inventory value is calculated based on current market prices at the time you start the bot. Therefore it will change if there are changes in the price of the asset
But if you look at your actual inventory token balances, those should be consistent, after taking into account any trades that have occurred.

Please refer to the link below for a more in-depth explanation
https://hummingbot.io/blog/2019-07-measure-performance-crypto-trading/

**Comment by mifeng** [comment]
@adamnmcc you're right that we could definitely make this more intuitive so that users understand how performance is calculated. We use the method above because we think it's both the simplest and the most accurate.
