### ISSUE TITLE
[BUG] PureMM multiple orders showing same bid/ask price in case of small order interval percent for low cost assets

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#671]
**Describe the bug**
All orders are first in line and placed on top of each other without a step, all same bid/ask price. Works fine on an ETH pair with same configs but not on BTC.

**Steps To Reproduce**
Set up and run pure market making strategy with this configuration
```
maker_market: binance
maker_market_symbol: SNMBTC
order_amount: 1.0
cancel_order_wait_time: 60.0
bid_place_threshold: 0.01
ask_place_threshold: 0.01
mode: multiple
number_of_orders: 2
order_start_size: 5000.0
order_step_size: 5000.0
order_interval_percent: 0.005
inventory_skew_enabled: true
inventory_target_base_percent: 0.006
```

**Screenshots**
Image below shows expected behavior on ETH pair.

![Screen_Shot_2019-08-14_at_1 21 45_PM](https://user-images.githubusercontent.com/50150287/63057032-e6e06a80-bf1b-11e9-9fe4-da421fa85d68.png)

Image below with BTC pair, orders sitting on top of each other.

![Screen_Shot_2019-08-14_at_1 20 53_PM](https://user-images.githubusercontent.com/50150287/63056410-8e5c9d80-bf1a-11e9-8cb9-e35e862479ca.png)

We created a bot to replicate the issue and shows the same below.

![unknown](https://user-images.githubusercontent.com/50150287/63057154-2f982380-bf1c-11e9-958d-614425e98e81.png)

**Release version**
branch: development
version: 0.13.0
date: 2019-08-13T23:29:12Z

**Attachments**
[hummingbot_logs_2019-08-14-20-45-27.log](https://github.com/CoinAlpha/hummingbot/files/3503364/hummingbot_logs_2019-08-14-20-45-27.log)

**Comment by veecos2** [comment]
This can occur for low cost assets where after rounding it would place on the same tick level if the order interval percent is too low.
