### ISSUE TITLE
[Feature] Inventory preservation change

### ISSUE THREAD

**Issue by Oldman-Sam** [CoinAlpha/hummingbot#685]
**Feature Suggestion**
Instead of having the amount change to keep the % maybe it should just buy more (it can just progressively make fewer sell orders)to keep above it's specified threshold. This could be an option from the default.

**Impact**
Since I use a small amount per trade I don't want the amount to go lower as binance will likely reject my trade. I think just telling the bot to buy and not sell when it's about to go below the threshold makes more sense in my case.

**Comment by mifeng** [comment]
As of v0.26.0, Inventory Skew now has floor and ceiling thresholds.
