### ISSUE TITLE
Server responded with status 500

### ISSUE THREAD

**Issue by cryptotrade3** [CoinAlpha/hummingbot#689]
**Describe the bug**
After I insert my public eth address the server "responded with status 500". 

**Steps To Reproduce**
I have installed Hummingbot following docker instruction. Then I started the configuration answering the question about licensing, mail address. 
After I insert my public eth wallet address the server "responded with status 500". 

**Screenshots**
<img width="612" alt="Schermata 2019-08-22 alle 20 36 03" src="https://user-images.githubusercontent.com/53374224/63540708-e1d37a80-c51c-11e9-8899-167f9b0a42bd.png">
l
**Release version**
0.12.1

**Attachments**
Log file are two and both empty.

**Optional: your discord username:**
micheleinvest#1775

**Optional: your ETH address:**
781868fb8606b1afc2cea0a2187a054cd891d1b9

**Comment by chowryan** [comment]
server might have been down temporarily. feel free to reopen if it's still down for you.
