### ISSUE TITLE
[Feature] Persistent Orderbook

### ISSUE THREAD

**Issue by RichardAtCT** [CoinAlpha/hummingbot#699]
**Feature Suggestion**
For `cancel_order_wait_time`, only cancel the order if `bid_place_threshold` and/or `ask_place_threshold`have deviated from their set parameters. 

**Impact**
Implementing this will allow orders to retain their place in the order book when there is no price movement, improving the chance of an order being filled when there are many competing orders.

**Comment by mifeng** [comment]
Fixed by #1673
