### ISSUE TITLE
[BUG] Pure MM + DDEX + multiple + skew not placing orders

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#705]
**Describe the bug**

Hummingbot not placing any orders with inventory skew enabled. Disabling inventory skew feature will create orders but re-enabling will stop the bot again from creating.

**Steps To Reproduce**

Set up and run pure-mm with this configuration
```
maker_market: ddex
maker_market_symbol: WETH-DAI
order_amount: 1.0
cancel_order_wait_time: 60.0
bid_place_threshold: 0.005
ask_place_threshold: 0.005
mode: multiple
number_of_orders: 2
order_start_size: 0.1
order_step_size: 0.1
order_interval_percent: 0.01
inventory_skew_enabled: true
inventory_target_base_percent: 0.5
```

**Screenshots**

Screenshot from the logs when inventory skew is enabled.

![image](https://user-images.githubusercontent.com/50150287/63731460-31f66800-c8a2-11e9-8a25-a2c413249855.png)

Screenshot from the logs when inventory skew is disabled.

![image](https://user-images.githubusercontent.com/50150287/63731501-7f72d500-c8a2-11e9-8815-a8015ea55ac5.png)

I will post more screenshots from the Hummingbot interface when Carlo gets back to re-enter the wallet password.

**Release version**

version: `dev-0.13.0`
branch: "development"
commit: "a85e497303021b0e451216470dfd6a403c769e6b"
date: "2019-08-13T23:29:12Z"

**Attachments**

[hummingbot_logs_2019-08-14-16-52-12.log](https://github.com/CoinAlpha/hummingbot/files/3543678/hummingbot_logs_2019-08-14-16-52-12.log)

**Comment by dennisocana** [comment]
More previous logs
[hummingbot_logs_2019-08-14-01-24-19.zip](https://github.com/CoinAlpha/hummingbot/files/3543773/hummingbot_logs_2019-08-14-01-24-19.zip)

**Comment by veecos2** [comment]
@chowryan : Is this expected behavior then ?

**Comment by veecos2** [comment]
The logs indicate that the sell order was not placed because there was not enough asset. Also I checked with zrx-weth with inventory skew enabled and it was working.
