### ISSUE TITLE
[BUG] Running Discovery Strategy with all tokens results to "Too Many Request; current limit is 1200"

### ISSUE THREAD

**Issue by rennel-tabing** [CoinAlpha/hummingbot#706]
**Describe the bug** 
// A clear and concise description of what the bug is.
When using the Discovery strategy,running all symbols on the 1st and and 2nd token symbol will results on reaching API limit causing the the strategy to loop indefinitely

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:
Run a New Discovery Strategy with the following config

primary_market: binance
secondary_market: coinbase_pro
target_profitability: 0.01
target_amount: .inf
target_symbol_1: []
target_symbol_2: []
equivalent_tokens:
- - USDT
  - USDC
  - USDS
  - DAI
  - PAX
  - TUSD
  - USD
- - ETH
  - WETH
- - BTC

**Screenshots**
// If applicable, add screenshots to help explain your problem.
Here is the error that stops the strategy and this will start the strategy to run all over again.

![image](https://user-images.githubusercontent.com/53868268/63783813-9b36a500-c8bb-11e9-9e5f-11ee9312ee30.png)

**Release version**
// Include your bot's version number (Can be found at the bottom left corner of your CLI).
0.13.0

**Attachments**
// Here is the config file...
[conf_discovery_strategy_0.yml.txt](https://github.com/CoinAlpha/hummingbot/files/3546905/conf_discovery_strategy_0.yml.txt)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Comment by michaelc9** [comment]
@rennel-tabing Can you include your log file for trace dump.

**Comment by rennel-tabing** [comment]
Debug file was too big to be added here as it was 20MB

I run the strategy today and I am no longer getting this error. I did however got a different  error that was shown in this issue https://github.com/CoinAlpha/hummingbot/issues/721

**Comment by rennel-tabing** [comment]
I was able to split the log file into multiple files.

[hummingbot_1.txt](https://github.com/CoinAlpha/hummingbot/files/3562684/hummingbot_1.txt)
[hummingbot_2.txt](https://github.com/CoinAlpha/hummingbot/files/3562685/hummingbot_2.txt)
[hummingbot_3.txt](https://github.com/CoinAlpha/hummingbot/files/3562686/hummingbot_3.txt)
[hummingbot_4.txt](https://github.com/CoinAlpha/hummingbot/files/3562687/hummingbot_4.txt)

**Comment by michaelc9** [comment]
@rennel-tabing Thanks. We have increase the wait time between each snapshot request for Binance, and that should prevent the bot reaching API rate limit. The change is merged in development.
