### ISSUE TITLE
[BUG] Expired Orders are still showing as active under My orders for Bamboo Relay

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#714]
**Describe the bug**
Bot creates order, will show in Bamboo Relay under 'My Orders' and in the order book

<img width="949" alt="hbot_bamboo1" src="https://user-images.githubusercontent.com/50150287/63979623-ecc57680-caeb-11e9-9eda-18f9ec843225.PNG">

<img width="552" alt="order_book" src="https://user-images.githubusercontent.com/50150287/63979632-f18a2a80-caeb-11e9-82ea-57be466b44ec.PNG">

When `cancel_order_wait_time` has passed the order will disappear from the order book but will stay in 'My Orders'.

<img width="555" alt="order_book2" src="https://user-images.githubusercontent.com/50150287/63979791-504fa400-caec-11e9-9124-52a2165073de.PNG">

Bot will appear to be stuck not showing in the logs that the order was canceled nor it was trying to replace the previous order. In the screenshot below you will see I waited for 2 more minutes.

<img width="959" alt="hbot_bamboo2" src="https://user-images.githubusercontent.com/50150287/63979833-72492680-caec-11e9-8c9e-b6283620cff1.png">

**Steps To Reproduce**
Set up pure-mm bot with the ff. config:

```
maker_market: bamboo_relay
maker_market_symbol: ZRX-WETH
order_amount: 10.0
cancel_order_wait_time: 60.0
bid_place_threshold: 0.01
ask_place_threshold: 0.01
mode: single
number_of_orders: 1
order_start_size: 1.0
order_step_size: 0.0
order_interval_percent: 0.01
inventory_skew_enabled: false
```

**Release version**
version: dev-0.14.0
commit: "727ab35175da4c76f9447189e075686605ebad7c"
date: "2019-08-29T18:00:49Z"

**Attachments**
[hummingbot_logs_2019-08-29-21-51-15.log](https://github.com/CoinAlpha/hummingbot/files/3557515/hummingbot_logs_2019-08-29-21-51-15.log)

**Comment by dennisocana** [comment]
May be related to https://github.com/CoinAlpha/hummingbot/issues/660 and https://github.com/CoinAlpha/hummingbot/issues/661

**Comment by dennisocana** [comment]
Same active orders stuck after 21 hours

![image](https://user-images.githubusercontent.com/50150287/64045467-f7d7df80-cb9b-11e9-811e-7e717e42fdd5.png)

Latest logs: 
[hummingbot_logs_2019-08-30-00-52-20.log](https://github.com/CoinAlpha/hummingbot/files/3561205/hummingbot_logs_2019-08-30-00-52-20.log)

Stopped bot but orders are still showing under 'My Orders' in Bamboo

![image](https://user-images.githubusercontent.com/50150287/64045843-ee02ac00-cb9c-11e9-93f6-a495858a4065.png)

Getting "Transaction failed, try again" when attempting to manually cancel orders in exchange

![image](https://user-images.githubusercontent.com/50150287/64045969-2d30fd00-cb9d-11e9-8ea9-6d67e290367b.png)

**Comment by veecos2** [comment]
The issue is with the bamboo relay connector.

**Comment by Arctek** [comment]
I'm looking into this now, thanks for reporting.

**Comment by Arctek** [comment]
@dennisocana are you using the connector in coordinated mode or normal mode?
i.e. what is `bamboo_relay_use_coordinator` set to in the global config?

**Comment by Arctek** [comment]
Ok, I've corrected the underlying cause of this; which was related to orders expiring but not updating the REST-facing websocket pub/sub channels.

@dennisocana If you check now it should be correct when you start it next time.

Also I would suggest using the coordinated mode for market making on Bamboo Relay as it takes advantage of being able to cancel and replace orders.

**Comment by dennisocana** [comment]
@Arctek I was doing it in normal mode before.

I just ran two tests - one in normal mode and another with coordinated mode w/ preemptive cancel. Both are working fine now.

Thanks!
