### ISSUE TITLE
[BUG] Token symbol format for Discovery configuration

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#724]
**Describe the bug**

When setting up config for Discovery strategy, entering the token symbol as ['tokenpair'] doesn't work. It only works when entering the value in ["tokenpair"] format. List needs to be JSON formatted, but the example in prompt prints the Python object format.

Example:

```
Enter list of token symbol on ddex (e.g. ['ZRX-WETH'] or press ENTER for all symbols.)
>>> ['ZRX-WETH']

['ZRX-WETH'] is not a valid target_symbol_1 value
```

![image](https://user-images.githubusercontent.com/50150287/64200528-4c8e9980-cebf-11e9-8a01-3f793484a452.png)

**Release version**

version: dev-0.14.0
commit: "126d5f0c4058bbf0d9fadea117f2d5c9e5648ac3"
date: "2019-08-27T00:47:47Z"

**Discord username:** War)-(eaD
**ETH address:** 0x8950e3Cb47601cEA2fFd6AC292953209fE5D92C0

**Comment by rennel-tabing** [comment]
Here is an update from the user on the discord channel
![image](https://user-images.githubusercontent.com/53868268/64191207-f9c4cb80-ce45-11e9-9af3-b778d7e55013.png)

**Comment by dennisocana** [comment]
Confirmed that ["tokenpair"] works but not ['tokenpair'].

![image](https://user-images.githubusercontent.com/50150287/64200098-5d8adb00-cebe-11e9-93bd-76261262499d.png)
