### ISSUE TITLE
[BUG] Deposits are Included in Performance

### ISSUE THREAD

**Issue by joesixpack** [CoinAlpha/hummingbot#732]
**Describe the bug**
Any quote pair deposit after the bot is running confuses the performance section in history and is then included in the delta and return.  This may extend to the base pair also.

**Steps To Reproduce**
Deposit any quote or base pair currency on Binance.

**Release version**
Version: 0.13.0

Your ETH address: Provided upon request.

**Comment by dennisocana** [comment]
This is correct, deposits and withdrawals affect performance. Right now the performance calculation in `history` is based on inventory balances. We are looking to find a better way to do this.
