### ISSUE TITLE
futures support

### ISSUE THREAD

**Issue by zhiji666** [CoinAlpha/hummingbot#738]
The exchanges that humming bot currently support don't have futures. And I want to add a connector for another exchange that trading futures. So I want to know if humming bot support futures. If not, is it difficult to make it by myself?

**Comment by zhiji666** [comment]
And I knew humming bot is going to support Bitmex, will futures in bitmex be supported too?

**Comment by moraliang** [comment]
@zhiji666 Hello, your questions have been answered in our weekly Hummingbot Live. Check it out here: https://www.youtube.com/watch?v=SrJqPAhP40w
