### ISSUE TITLE
[BUG] Failed to batch cancel orders in Huobi

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#745]
**Describe the bug**

Previous orders that failed to cancel (timestamp 2019-09-06 01:52:51) stuck in exchange but are not tracked by Hummingbot. Huobi shows I have 7 outstanding orders and Hummingbot only shows I have 4 active orders.

```
2019-09-05 17:52:51,784 - hummingbot.market.huobi.huobi_market - NETWORK - Failed to cancel all orders: []
Traceback (most recent call last):
  File "huobi_market.pyx", line 720, in hummingbot.market.huobi.huobi_market.HuobiMarket.cancel_all
  File "huobi_market.pyx", line 247, in _api_request
  File "huobi_market.pyx", line 262, in hummingbot.market.huobi.huobi_market.HuobiMarket._api_request
OSError: Error reading data from https://api.huobi.pro/v1/order/orders/batchcancel. Response is {'status': 'error', 'err-code': 'batchcancel-order-id-list-empty', 'err-msg': 'Batch cancel order id list empty.', 'data': None}.
2019-09-05 17:52:51,784 - hummingbot.market.huobi.huobi_market - WARNING - Failed to cancel all orders on Huobi. Check API key and network connection.
```

![order_book1](https://user-images.githubusercontent.com/50150287/64382323-01fc5100-d068-11e9-81ac-2e2590fad9c0.png)
![order_book2](https://user-images.githubusercontent.com/50150287/64382327-045eab00-d068-11e9-97b4-9a99dbb82378.png)
![order_book3](https://user-images.githubusercontent.com/50150287/64382330-06286e80-d068-11e9-88cc-f56d31536e3f.png)

Stopped the bot, all 4 active orders are gone but the old orders are still stuck.

<img width="607" alt="order_book4" src="https://user-images.githubusercontent.com/50150287/64385811-01fd5080-d06a-11e9-9e52-9c72b56ad8d2.png">

Had to manually cancel the outstanding orders and restart the bot.

**Steps To Reproduce**

Test bot is set up in `test-development.hummingbot.io`.

**Release version**

"branch": "development",
"commit": "3a985fc04f1aee0e0d777d01a3af64502c409231",
"date": "2019-09-04T18:16:24Z",

**Attachments**

[hummingbot_logs_2019-09-05-17-54-24.log](https://github.com/CoinAlpha/hummingbot/files/3581371/hummingbot_logs_2019-09-05-17-54-24.log)

**Comment by chowryan** [comment]
potential fix https://github.com/CoinAlpha/hummingbot/pull/815

please reopen if this continues, thanks!
