### ISSUE TITLE
[BUG] Fluctuating Infura RPC calls on AWS

### ISSUE THREAD

**Issue by gabririgo** [CoinAlpha/hummingbot#748]
**Describe the bug**
The number of RPC calls to infura variates sharply over time. A pure mkt mking strategy consumes around 5000/6000 rpc calls per hour. After leaving hummingbot running a few days, I experienced a sharp drop in the number of calls to 394/400 per hour, and a reduction to 0 of log queries. Yet the bot is running smoothly.

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: pure market making, bamboorelay, coordinator true, softcancel true, infura endpoint, GRGWETH, 2 orders per side each 5 minutes  
2. Start the bot using this command: docker start hummingbot-instance && docker attach hummingbot-instance
3. Leave the bot running until you see the sharp reduction in rpc calls on the infura dashboard

**Screenshots**
![infuraScreenshot from 2019-09-06 14-33-25](https://user-images.githubusercontent.com/12066256/64429305-f3d52180-d0b5-11e9-8b92-0dd814d2569d.png)

**Release version**
0.13.0

**Attachments**
[config.zip](https://github.com/CoinAlpha/hummingbot/files/3584004/config.zip)

**Optional: your discord username:** gabrigo | RigoBlock
**Optional: your ETH address:** 0x320C38912B1611a0706c0A74427f64fA5Dc3598e

**Comment by rennel-tabing** [comment]
@gabririgo reached out to me yesterday with the issue and I run my test environment for 16 hrs. I see a drop on the RPC request but it did not affect the orders that are being placed.
I am not nearing my Infura daily limit and just used 52% of the daily allowance.
![image](https://user-images.githubusercontent.com/53868268/64430716-dd63a180-d086-11e9-8b0e-8bb379435cbd.png)

**Comment by rennel-tabing** [comment]
> @gabririgo reached out to me yesterday with the issue and I run my test environment for 16 hrs. I see a drop on the RPC request at around 5am but it did not affect the orders that are being placed.
> I am not nearing my Infura daily limit and just used 52% of the daily allowance.
> ![image](https://user-images.githubusercontent.com/53868268/64430716-dd63a180-d086-11e9-8b0e-8bb379435cbd.png)

**Comment by yzhang1994** [comment]
@gabririgo please provide your logs so we can debug more effectively.

**Comment by rennel-tabing** [comment]
@gabririgo I run the strategy again and I am no longer experiencing the issue. Can you confirm if you are still seeing those on your hummingbot? If yes, then please provide the logs as instructed on the previous response.

**Comment by gabririgo** [comment]
> @gabririgo I run the strategy again and I am no longer experiencing the issue. Can you confirm if you are still seeing those on your hummingbot? If yes, then please provide the logs as instructed on the previous response.

still does, please find screenshot of infura calls hereby. Also the bot does not update logs, which is most likely not intended.
![GRG-Screenshot from 2019-09-18 10-47-48](https://user-images.githubusercontent.com/12066256/65135902-04b35a80-da07-11e9-9825-a21985a27708.png)

please find log file in the link below, as the file is pretty big (more than 50MB):
[https://drive.google.com/file/d/1i1JzZCHxrY61cbD5lcno_FhrWi6SWyUp/view?usp=drive_web](url)

**Comment by rennel-tabing** [comment]
I have run the strategy again for three consecutive days and it is till then before the behavior manifests on my test bot. 
![image](https://user-images.githubusercontent.com/53868268/66707154-3e2b6d00-ed0a-11e9-8814-9c6406746237.png)

As per user, this does not affect his existing orders but he is unsure if this have unintended consequences.

**Comment by rennel-tabing** [comment]
as per @gabririgo ...
"I think I have an explanation after speaking to ops who run ethereum aws nodes extensively
basically I believe infura does not answer to the same calls when it deems they are unnecessary
therefore hummingbot makes the call, infura responds initially and after a couple of hours starts responding selectively
this is a guess, as I have no proof fo what I am saying
however I have now hummingbot instances pointing to infura and others pointing to an aws node I set up, they have been running smoothly (though I am not benchmarking on the number of rpc calls to the aws node I did set up)"

**Comment by dennisocana** [comment]
@gabririgo please let us know if you're still getting this behavior after we merged this PR https://github.com/CoinAlpha/hummingbot/pull/1995 in the 0.29.0 relase.
