### ISSUE TITLE
Bounty

### ISSUE THREAD

**Issue by devcoinfet** [CoinAlpha/hummingbot#760]
I thought I read somewhere You offered a bounty if an issue was the cause of a bugfix

1.) Is this correct?
2.) If so how much is the bounty
3.) Thanks for allowing me to help either way

**Comment by PtrckM** [comment]
@devcoinfet You can read more on our documentations here https://docs.hummingbot.io/bounties/faq/ https://docs.hummingbot.io/support/bug-bounty-program/

**Comment by devcoinfet** [comment]
so am i good do i get paid that's what I am asking i seemed to have followed the rules  so that's a 18 dollar bounty with a possible discretionary bounty? the reason i am asking here is its been months no one replies to my emails

**Comment by znerol19619** [comment]
@devcoinfet its 0.1 ETH for any bug reported that meets a certain criteria. and you must follow the submission guidelines.
Refer to this blog
 https://hummingbot.io/blog/2019-04-hummingbot-bug-bounty/

**Comment by chowryan** [comment]
we do pay 0.1 wheres your ticket?

**Comment by PtrckM** [comment]
@devcoinfet is this the ticket? #555

**Comment by devcoinfet** [comment]
affirmative sorry answered wrong spot was mobile

**Comment by chowryan** [comment]
Whats your ETH address? We'll still give the reward, but please provide your address in the bug submission next time. Thanks!

**Comment by devcoinfet** [comment]
0x1D955a63259E4Ef915518C1E0f2db8A6aC9B2f56


sorry about that I wasn't aware you had a bounty at first thanks guys

**Comment by moraliang** [comment]
@devcoinfet  Just sent 0.1 to you! Thanks for reporting!
