### ISSUE TITLE
[BUG] Huobi market fails to start with Discovery strategy

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#761]
**Describe the bug**

Discovery strategy is stuck and fails to start after going through the order books in both markets. If you wait long enough, it will start over initializing the order books (e.g. 1/351 completed, 1/535 completed) only to end up stopping when completed. It goes into a loop to restart, complete, restart.

These 3 bots show the same behavior as described above. What's common among their configuration is they are all set up with Huobi as one of their markets.

```
primary_market: binance
secondary_market: huobi
target_symbol_1: []
target_symbol_2: []
```
[bn-hb_discovery.log](https://github.com/CoinAlpha/hummingbot/files/3593673/bn-hb_discovery.log)

<img width="947" alt="bn-hb_discovery" src="https://user-images.githubusercontent.com/50150287/64584827-e75c0c00-d3c8-11e9-9464-4de6ab864654.png">

```
primary_market: huobi
secondary_market: ddex
target_symbol_1: []
target_symbol_2: []
```
[hb-dd_discovery.log](https://github.com/CoinAlpha/hummingbot/files/3593671/hb-dd_discovery.log)

<img width="947" alt="hb-dd_discovery" src="https://user-images.githubusercontent.com/50150287/64584504-841daa00-d3c7-11e9-923c-7ce59c09676b.png">

Checked to see if the issue is related to too many token pairs so another bot was set up to only one trading pair and it's experiencing the same issue.

```
primary_market: binance
secondary_market: huobi
target_symbol_1:
- ZRXETH
target_symbol_2:
- zrxeth
```
[bn-hb_zrxeth.log](https://github.com/CoinAlpha/hummingbot/files/3593674/bn-hb_zrxeth.log)

<img width="674" alt="zrx-weth_discovery" src="https://user-images.githubusercontent.com/50150287/64583292-0eafda80-d3c3-11e9-8a70-da12d9928ef0.png">

Removed Huobi but this setup with Binance returns with a BTTTRX error parsing symbol issue https://github.com/CoinAlpha/hummingbot/issues/755
```
primary_market: binance
secondary_market: ddex
target_symbol_1: []
target_symbol_2: []
```

Strategy was only successful if Huobi or Binance market are excluded.
```
primary_market: ddex
secondary_market: radar_relay
target_symbol_1: []
target_symbol_2: []
```
<img width="674" alt="ddrr_discovery" src="https://user-images.githubusercontent.com/50150287/64583025-220e7600-d3c2-11e9-8260-40cb0a034ed0.png">

**Release version**

`latest 0.14.0` and `dev-0.15.0`

**Comment by chowryan** [comment]
fixed. https://github.com/CoinAlpha/hummingbot/pull/766

**Comment by chowryan** [comment]
there is another issue with running all pairs for discovery on huobi. I've noticed that it takes 4GB+.

**Comment by dennisocana** [comment]
Confirmed working.

<img width="947" alt="putty_SKWuBe0esX" src="https://user-images.githubusercontent.com/50150287/64664400-b12e9300-d481-11e9-9439-e03b54619a69.png">
