### ISSUE TITLE
[New Exchange Connector Request] Liquid

### ISSUE THREAD

**Issue by Deimoos** [CoinAlpha/hummingbot#762]
## Exchange Details ✏️

- **Name of exchange**: Liquid
- **Exchange URL**: https://www.liquid.com/
- **Link to API docs**: https://developers.liquid.com/
- **Type of exchange**: [X ] Centralized [ ] Decentralized
- **Requester details**: Are you affiliated with the exchange? [ ] yes [X ] no 
  - If yes, what is your role?

## Rationale / impact ✏️
(Describe your rationale for building this exchange connector, impact for hummingbot users/community)
I would like to use the MM bot to add liquidity on Liquid, on DASH and other pairs (CEL token, ...)
Liquid has lots of low volume and low liquidity pairs and there is a great opportunity to inject liquidity there.

## Additional information ✏️
(Provide any other useful information that may be helpful to know about this exchange)

---

⚠️ ***Note: do not modify below here***

## Developer notes

This feature request entails building a new exchange connector to allow Hummingbot to connect to an exchange that is currently not supported.

### Resources
- [Exchange connector developer guide](https://docs.hummingbot.io/developers/connectors/)
- [Discord forum](https://discord.hummingbot.io)

### Deliverables
1. A complete set of exchange connector files as listed [above](#developer-notes-resources).
2. Unit tests (see [existing unit tests](https://github.com/CoinAlpha/hummingbot/tree/master/test/integration)):
  1. Exchange market test ([example](https://github.com/CoinAlpha/hummingbot/blob/master/test/integration/test_binance_market.py))
  2. Order book tracker ([example](https://github.com/CoinAlpha/hummingbot/blob/master/test/integration/test_binance_order_book_tracker.py))
  3. User stream tracker ([example](https://github.com/CoinAlpha/hummingbot/blob/master/test/integration/test_binance_user_stream_tracker.py))
3. Documentation:
  1. Code commenting (particularly for any code that is materially different from the templates/examples)
  2. Any specific instructions for the use of that exchange connector ([example](https://docs.hummingbot.io/connectors/binance/))

### Required skills
- Python
- Previous Cython experience is a plus (optional)

**Comment by carlolm** [comment]
Closing this request since we are starting a gitcoin bounty: https://github.com/CoinAlpha/hummingbot/issues/909
