### ISSUE TITLE
[BUG] flake8 cython issues

### ISSUE THREAD

**Issue by veecos2** [CoinAlpha/hummingbot#763]
**Describe the bug**
// A clear and concise description of what the bug is.
1. Getting invalid syntax issues for cython imports and cython classes. Flake8 is flagging the following as E999 SyntaxErrors,
- cdef class OrderIDMarketPairTrackingItem:
- from libc.stdint cimport int64_t
- from hummingbot.core.clock cimport Clock
2. Getting E225 missing whitespace around operator for <int64_t> data types
cdef:
            int64_t current_tick = <int64_t>(timestamp // self._status_report_interval)
            int64_t last_tick = <int64_t>(self._last_timestamp // self._status_report_interval)

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:
Run flake8 on Cross exchange market making directory

**Screenshots**
// If applicable, add screenshots to help explain your problem.

**Release version**
// Include your bot's version number (Can be found at the bottom left corner of your CLI).

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**
**Optional: your ETH address:** (If you want to participate in the bug bounty)

**Comment by martinkou** [comment]
E999 is disabled in the .flake8 config. How did you run the flake8 linter to begin with?

**Comment by veecos2** [comment]
Oh should i run it from the home directory ?. I might have run it in a different directory.

**Comment by martinkou** [comment]
You should run it from the project directory. That's the directory that the pre-commit hook uses.

**Comment by veecos2** [comment]
yeah, i don't see any issues running from project directory.
