### ISSUE TITLE
[BUG] Discovery - Way too many requests; IP banned

### ISSUE THREAD

**Issue by PtrckM** [CoinAlpha/hummingbot#767]
Way too many requests; IP banned

```
# The following configuations are only required for the
# discovery strategy

# Exchange and token parameters
primary_market: binance
secondary_market: coinbase_pro

# Minimum profitability target required to place an order
# Expressed in decimals: 0.01 = 1% target profit
target_profitability: 0.0
target_amount: .inf

target_symbol_1: []
target_symbol_2: []
```

![image](https://user-images.githubusercontent.com/54516858/64664182-e5ee1a80-d480-11e9-8a0b-7857425eecbc.png)

[hummingbot_logs_2019-09-11-02-30-16.log](https://github.com/CoinAlpha/hummingbot/files/3598633/hummingbot_logs_2019-09-11-02-30-16.log)

```
                "branch": "dev-0.15.0",
                "commit": "6d68ea6385b3d899f255b5a01408b005da62e4a2",
                "date": "2019-09-11T00:52:56Z",
                "maintainer": "CoinAlpha, Inc. <dev@coinalpha.com>"
```

tested in `support-patrick.hummingbot.io` and `localmachine` on dev-0.15.0

**Comment by dennisocana** [comment]
How long did you leave it running? I got the same error yesterday because of the stuck and looping issue with the strategy https://github.com/CoinAlpha/hummingbot/issues/761 where the bot keeps doing the same thing over and over until you eventually get the IP banned message.

Try to restart or wait for hours (or tomorrow) and comment if the issue persists with the latest docker image.

**Comment by PtrckM** [comment]
almost an hour 1 in VM then 45 mins in localpc,

I will try your suggestions

**Comment by PtrckM** [comment]
confirmed working again after less than hour.

```
                "branch": "0.14.0",
                "commit": "a1bce79aae846b396b591b12208a75103ab2e361",
                "date": "2019-09-09T17:57:15Z",

                "branch": "dev-0.15.0",
                "commit": "daaf89847347ff50d369653ad1de984f02e966ce",
                "date": "2019-09-11T00:10:14Z",
```
