### ISSUE TITLE
[BUG] Paper Trading - config paper_trade_account_balance error

### ISSUE THREAD

**Issue by rennel-tabing** [CoinAlpha/hummingbot#769]
**Describe the bug**
// A clear and concise description of what the bug is.
running the `config paper_trade_account_balance'  command before starting  the strategy will result to an error that prevents the bot to run.

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
1. Create a PureMM stragegy
2. Run the command 'config paper_trade_account_balance' then press ENTER for the default value
![image](https://user-images.githubusercontent.com/53868268/64710402-e1783080-d485-11e9-9e88-f5b58d3bdd15.png)

3. Start the bot by using the "start" command
...

**Screenshots**
// 

**Release version**
// dev-0.15.0

**Attachments**
//
Error is as follows 
''' 2019-09-11 14:12:08,002 - hummingbot.core.clock - ERROR - Unexpected error running clock tick. Traceback (most recent call last): File "clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til File "pure_market_making_v2.pyx", line 270, in hummingbot.strategy.pure_market_making.pure_market_making_v2.PureMarketMakingStrategyV2.c_tick File "pure_market_making_v2.pyx", line 375, in hummingbot.strategy.pure_market_making.pure_market_making_v2.PureMarketMakingStrategyV2.c_execute_orders_proposal AttributeError: 'NoneType' object has no attribute 'actions' 2019-09-11 14:12:09,001 - hummingbot
'''
PureMM strategy
```
########################################################
###       Pure market making strategy config         ###
########################################################

# The following configuations are only required for the
# pure market making strategy

# Exchange and token parameters
maker_market: ddex
maker_market_symbol: WETH-DAI

# size of each order
order_amount: 5.0

# Time in seconds before cancelling and rerunning strategy
# If tick size is 60, the bot cancels active orders and reruns after a minute
cancel_order_wait_time: 60.0

# How far away from mid price to place the bid order
# Expressed in decimals : 0.01 = 1% away from mid price at that time
# Example if mid price is 100 and bid_place threshold is 0.01
# Your bid is placed at 99
bid_place_threshold: 0.01

# How far away from mid price to place the ask order
# Expressed in decimals : 0.01 = 1% away from mid price at that time
# Example if mid price is 100 and ask_place threshold is 0.01
# Your bid is placed at 101
ask_place_threshold: 0.01

# If you want to have single or multiple bids and asks on each side
mode: single

# If you have multiple orders number of orders you want to place on one side of the orderbook
number_of_orders: 1

# Size of the first bid and ask order for multiple order mode
order_start_size: 1.0

# Increment size of consecutive orders after the first order in multiple order mode
order_step_size: 0.0

# Spacing between orders in multiple order mode
order_interval_percent: 0.01

# Toggle enabling of Inventory skew
inventory_skew_enabled: false

# Target base asset inventory percentage target to be maintained
inventory_target_base_percent: 0.5

# For more detailed information, see:
# https://docs.hummingbot.io/strategies/pure-market-making/#configuration-parameters
```

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**
**Optional: your ETH address:** (If you want to participate in the bug bounty)

**Comment by michaelc9** [comment]
@rennel-tabing We currently only allow config single variable in the CLI after you configure the strategy. We have a PR open to allow configuring global config at the start: https://github.com/CoinAlpha/hummingbot/pull/770

**Comment by dennisocana** [comment]
Might also be a good idea to include your paper trade balance in the post. You will get this error along with another stack trace if you don't have enough balance on either side. The default values when pressing `ENTER` with `config paper_trade_account_balance` does not include DAI which you want to trade.
