### ISSUE TITLE
[BUG] XEMM spams errors if there is not enough balance on one side

### ISSUE THREAD

**Issue by chowryan** [CoinAlpha/hummingbot#773]
**Describe the bug**
// A clear and concise description of what the bug is.
spamming this message every second because not enough balance on 1 side. other order is fine.
looks like a regression this issue is not on master.

[hummingbot_logs_2019-09-11-16-54-56.log](https://github.com/CoinAlpha/hummingbot/files/3603148/hummingbot_logs_2019-09-11-16-54-56.log)

![image](https://user-images.githubusercontent.com/26056161/64743552-439c5a00-d4b5-11e9-9be8-40a2f3e09f3d.png)

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: ...
2. Start the bot using this command: ...
...

**Screenshots**
// If applicable, add screenshots to help explain your problem.

**Release version**
// Include your bot's version number (Can be found at the bottom left corner of your CLI).

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**
**Optional: your ETH address:** (If you want to participate in the bug bounty)

**Comment by veecos2** [comment]
Expected behavior that it does not place orders. I will check on logging.

**Comment by veecos2** [comment]
Also can you add the config file ?.

**Comment by martinkou** [comment]
The log flood is definitely a problem. Also, the recommended course of action "Check Ethereum wallet and network connection" is misleading.

**Comment by martinkou** [comment]
Also, the "about to create orders" message should be a debug message. It's not useful to users.

**Comment by martinkou** [comment]
Another thing is... if the order size is 0, then the strategy should not submit order anyway.

**Comment by chowryan** [comment]
I never said that it should be placing that order (theres not enough balance on one side). I don't expect it to spam warnings every second though.

**Comment by chowryan** [comment]
config is default except order_amount = 35

```
########################################################
###   Cross exchange market making strategy config   ###
########################################################

# The following configuations are only required for the
# cross exchange market making strategy

# Exchange and token parameters
maker_market: radar_relay
taker_market: binance
maker_market_symbol: ZRX-WETH
taker_market_symbol: ZRXETH

# Minimum profitability target required to place an order
# Expressed in decimals: 0.01 = 1% target profit
min_profitability: 0.001

# Maximum order size in terms of base currency
order_amount: 35.0

# Have Hummingbot actively adjust/cancel orders if necessary.
# If set to true, outstanding orders are adjusted if
# profitability falls below min_profitability.
# If set to false, outstanding orders are adjusted if
# profitability falls below cancel_order_threshold.
active_order_canceling: true

# If active_order_canceling = false, this is the profitability/
# loss threshold at which to cancel the order.
# Expressed in decimals: 0.01 = 1% target profit
cancel_order_threshold: 0.05

# An amount in seconds, which is the minimum duration for any
# placed limit orders. Default value = 130 seconds.
limit_order_min_expiration: 130.0

# If enabled (parameter set to `True`), the strategy will place the order on top of the top bid and ask,
# if its more profitable to place it there
adjust_order_enabled: true

# An amount expressed in base currency which is used for getting the top bid and ask,
# ignoring dust orders on top of the order book
top_depth_tolerance: 0.0

# An amount in seconds, which is the minimum amount of time interval between adjusting limit order prices
anti_hysteresis_duration: 60.0

# An amount expressed in decimals (i.e. input of `0.01` corresponds to 1%), which is the maximum size limit of new limit orders,
# in terms of ratio of hedge-able volume on taker side.
order_size_taker_volume_factor: 0.25

# An amount expressed in decimals (i.e. input of `0.01` corresponds to 1%), which is the maximum size limit of new limit orders,
# in terms of ratio of asset balance available for hedging trade on taker side
order_size_taker_balance_factor: 0.995

# An amount expressed in decimals (i.e. input of `0.01` corresponds to 1%), which is the maximum size limit of new limit orders,
# in terms of ratio of total portfolio value on both maker and taker markets
order_size_portfolio_ratio_limit: 0.1667

# For more detailed information, see:
# https://docs.hummingbot.io/strategies/cross-exchange-market-making/#configuration-parameters
```

**Comment by veecos2** [comment]
U mentioned other order is fine, which seems to me as not placing this order is not ok. Will address the logging issue.
