### ISSUE TITLE
[BUG] Errors in logs when submitting orders in IDEX

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#774]
**Describe the bug**

Bot is currently running fine as expected, reporting issues found in logs and for tracking.

Start: `2019-09-11 18:34:21,179`
End: `2019-09-11 18:46:07,692`

The issue lasted for ~12 minutes; error submitting buy and sell orders in IDEX.

```
OSError: Error fetching data from https://api.idex.market/order. HTTP status is 400 - {'error': "Cannot destructure property `tier` of 'undefined' or 'null'."}
OSError: Error fetching data from https://api.idex.market/order. HTTP status is 500 - {'error': 'Something went wrong. Try again in a moment.'}
OSError: Error fetching data from https://api.idex.market/order. HTTP status is 400 - {'error': 'Unauthorized'}
```

**Steps To Reproduce**

Run a normal pure-mm bot in IDEX.

```
maker_market: idex
maker_market_symbol: ETH_[BASE]
order_amount: 10
cancel_order_wait_time: 45.0
bid_place_threshold: 0.015
ask_place_threshold: 0.015
mode: multiple
number_of_orders: 2
order_start_size: 10
order_step_size: 5.0
order_interval_percent: 0.01
inventory_skew_enabled: false
inventory_target_base_percent: 0.01
```

**Release version**

Version: latest 0.14.0
Image timestamp: "2019-09-09T17:57:15Z"

**Attachments**

[hummingbot_logs_2019-09-09-19-20-21.log](https://github.com/CoinAlpha/hummingbot/files/3603342/hummingbot_logs_2019-09-09-19-20-21.log)

**Comment by chowryan** [comment]
confirmed that this was a temporary server bug on IDEX's end. it should be fixed now
