### ISSUE TITLE
[BUG] Autostart feature fails due to XEMM trade_size_override

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#778]
**Describe the bug**

With the latest changes made to xemm including the maximum order size is now in terms of base currency, it won't allow you to start or restart the bot using the autostart feature due to `trade_size_override`.

```
2019-09-12 11:33:25,863 - root - ERROR - Error loading configs. Your config file may be corrupt. Cannot find corresponding config to key trade_size_override.
Traceback (most recent call last):
  File "/hummingbot/client/config/config_helpers.py", line 171, in load_yml_into_cm
    raise ValueError(f"Cannot find corresponding config to key {key}.")
ValueError: Cannot find corresponding config to key trade_size_override.
2019-09-12 11:33:26,557 - root - WARNING - Bot config incomplete: Missing empty configs: 
- order_amount
- adjust_order_enabled
- active_order_canceling
- cancel_order_threshold
- limit_order_min_expiration
- top_depth_tolerance
- anti_hysteresis_duration
- order_size_taker_volume_factor
- order_size_taker_balance_factor
- order_size_portfolio_ratio_limit
- coinbase_pro_api_key
- coinbase_pro_secret_key
- coinbase_pro_passphrase
- huobi_api_key
- huobi_secret_key
- idex_api_key
. Starting normally...
```

To confirm this, I created a bot fresh from start with the latest development image and was able to use the autostart feature. I edited the config file of the other bot and removed the `trade_size_override` and got it working with autostart.

If I may suggest and if possible, remove the trade size override in the old xemm strategy config file after the update. It will avoid users having to manually delete it from the file. I attached two config files for comparison.

[old_xemm_template.txt](https://github.com/CoinAlpha/hummingbot/files/3605447/old_xemm_template.txt)
[new_xemm_template.txt](https://github.com/CoinAlpha/hummingbot/files/3605451/new_xemm_template.txt)

**Steps To Reproduce**

1. Update XEMM bot to latest image of development branch ("2019-09-12T00:53:24Z").
2. Use the autostart feature to restart the bot

**Release version**

Version: `dev-0.15.0`
Image stamp: `2019-09-12T00:53:24Z`

**Comment by yzhang1994** [comment]
This should have been fixed. Please test again to verify. Thanks!

**Comment by dennisocana** [comment]
Performed test to autostart cross-exchange strategy using an old config file with `trade_size_override`. Fix in PR https://github.com/CoinAlpha/hummingbot/pull/787 confirmed working.
