### ISSUE TITLE
[New Exchange Connector] Stablecoinswap.io

### ISSUE THREAD

**Issue by gonchs** [CoinAlpha/hummingbot#784]
## Exchange Details ✏️

- **Name of exchange**: Stablecoinswap
- **Exchange URL**: https://stablecoinswap.io
- **Link to API docs**: https://docs.stablecoinswap.io
- **Type of exchange**: Decentralized
- **Requester details**: Are you affiliated with the exchange? yes
  - If yes, what is your role? Founder

## Rationale / impact ✏️
The integration will open new arbitrage opportunities for the Hummingbot users. Stablecoinswap is a smart contract with stablecoin reserves. The prices are set by an oracle.

## Additional information ✏️

It should be possible to use this connector for the [Arbitrage](https://docs.hummingbot.io/developers/strategies/arbitrage) and [Cross Exchange Market Making](https://docs.hummingbot.io/developers/strategies/cross-exchange-market-making/) strategies (with Stablecoinswap being used on a taker side).

---

⚠️ ***Note: do not modify below here***

## Developer notes

This feature request entails building a new exchange connector to allow Hummingbot to connect to an exchange that is currently not supported.

### Resources
- [Exchange connector developer guide](https://docs.hummingbot.io/developers/connectors/)
- [Discord forum](https://discord.hummingbot.io)

### Deliverables
1. A complete set of exchange connector files as listed [above](#developer-notes-resources).
2. Unit tests (see [existing unit tests](https://github.com/CoinAlpha/hummingbot/tree/master/test/integration)):
  1. Exchange market test ([example](https://github.com/CoinAlpha/hummingbot/blob/master/test/integration/test_binance_market.py))
  2. Order book tracker ([example](https://github.com/CoinAlpha/hummingbot/blob/master/test/integration/test_binance_order_book_tracker.py))
  3. User stream tracker ([example](https://github.com/CoinAlpha/hummingbot/blob/master/test/integration/test_binance_user_stream_tracker.py))
3. Documentation:
  1. Code commenting (particularly for any code that is materially different from the templates/examples)
  2. Any specific instructions for the use of that exchange connector ([example](https://docs.hummingbot.io/connectors/binance/))

### Required skills
- Python
- Previous Cython experience is a plus (optional)

**Comment by GildedHonour** [comment]
Is help in resolving this needed?

**Comment by gonchs** [comment]
It's currently in development.

**Comment by carlolm** [comment]
This connector is available at this following fork:
https://github.com/stablecoinswap/hummingbot/tree/development
