### ISSUE TITLE
[BUG] Binance market fails with Discovery

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#785]
**Describe the bug**

Running discovery strategy will sometimes start, and sometimes it won't. If successful, Binance market will eventually fail and does not restart.

**Steps To Reproduce**

Set up a bot and run with Discovery strategy on Binance. This is the `bn-hb_discovery` bot in `test-semiweekly.hummingbot.io`.

**Screenshots**

![image](https://user-images.githubusercontent.com/50150287/64855822-4cc32d80-d653-11e9-82f8-f67883ea4eab.png)

**Release version**

version: `dev-0.15.0`
commit: `35f56abc1054553c4c9dc04bc7cf79d3b3da09b2`
date: `2019-09-13T00:38:51Z`

**Attachments**

[hummingbot_logs_2019-09-11-02-29-39.zip](https://github.com/CoinAlpha/hummingbot/files/3609579/hummingbot_logs_2019-09-11-02-29-39.zip)
[hummingbot_logs_2019-09-12-02-43-14.zip](https://github.com/CoinAlpha/hummingbot/files/3609583/hummingbot_logs_2019-09-12-02-43-14.zip)
[hummingbot_logs_2019-09-13-01-30-44.log](https://github.com/CoinAlpha/hummingbot/files/3609584/hummingbot_logs_2019-09-13-01-30-44.log)
[hummingbot_logs_2019-09-13-01-45-44.log](https://github.com/CoinAlpha/hummingbot/files/3609585/hummingbot_logs_2019-09-13-01-45-44.log)

**Comment by chowryan** [comment]
418 on binance is temp ip ban. possibly from too many requests. is every bot a different ip / binance account?

**Comment by dennisocana** [comment]
@chowryan yes it's on a separate IP and Binance account. If you run the discovery strategy on Binance market you will get an error like this on many trading pairs.

```
2019-09-13 03:52:47,225 - hummingbot.market.binance.binance_api_order_book_data_source - ERROR - Error getting snapshot for WAVESBTC. 
Traceback (most recent call last):
  File "/hummingbot/market/binance/binance_api_order_book_data_source.py", line 143, in get_tracking_pairs
    snapshot: Dict[str, Any] = await self.get_snapshot(client, trading_pair, 1000)
  File "/hummingbot/market/binance/binance_api_order_book_data_source.py", line 124, in get_snapshot
    raise IOError(f"Error fetching Binance market snapshot for {trading_pair}. "
OSError: Error fetching Binance market snapshot for WAVESBTC. HTTP status is 429.
```

The bot will keep trying and will eventually get the IP ban.

**Comment by chowryan** [comment]
does this still happen on dev?

**Comment by PtrckM** [comment]
Unable to start binance-huobi on dev-0.15.0

config
```
#####################################
###   Discovery strategy config   ###
#####################################

# The following configuations are only required for the
# discovery strategy

# Exchange and token parameters
primary_market: binance
secondary_market: huobi

# Minimum profitability target required to place an order
# Expressed in decimals: 0.01 = 1% target profit
target_profitability: 0.0
target_amount: .inf

target_symbol_1: []
target_symbol_2: []
equivalent_tokens:
- - USDT
  - USDC
  - USDS
  - DAI
  - PAX
  - TUSD
  - USD
- - ETH
  - WETH
- - BTC
  - WBTC
# For more detailed information, see:
# https://docs.hummingbot.io/strategies/discovery/
```
Logs

```
2019-09-20 01:35:34,346 - hummingbot.notifier.telegram_notifier - INFO - Telegram is listening...
2019-09-20 01:35:36,052 - hummingbot.data_feed.coin_gecko_data_feed - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2019-09-20 01:35:36,278 - hummingbot.data_feed.coin_cap_data_feed - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2019-09-20 01:35:53,801 - hummingbot.client.hummingbot_application - ERROR - Error initializing strategy.
Traceback (most recent call last):
  File "binance_market.pyx", line 194, in hummingbot.market.binance.binance_market.BinanceMarket.split_symbol
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/hummingbot/strategy/discovery/start.py", line 98, in start
    target_symbol_1 = process_symbol_list(market_1, target_symbol_1)
  File "/hummingbot/strategy/discovery/start.py", line 91, in process_symbol_list
    return filtered_trading_pair + filter_trading_pair_by_single_token(market_name, single_tokens)
  File "/hummingbot/strategy/discovery/start.py", line 78, in filter_trading_pair_by_single_token
    base_token, quote_token = MARKET_CLASSES[market_name].split_symbol(t)
  File "binance_market.pyx", line 196, in hummingbot.market.binance.binance_market.BinanceMarket.split_symbol
ValueError: Error parsing symbol BNBBUSD: 'NoneType' object has no attribute 'group'
2019-09-20 01:37:04,071 - hummingbot.data_feed.coin_gecko_data_feed - WARNING - Coin Gecko API request failed. Unable to get prices.
```
Version
```
                "branch": "development",
                "commit": "62ade2f7a055d51f6c907dc3119bc4c93f815a17",
                "date": "2019-09-20T00:11:45Z",
```

**Comment by dennisocana** [comment]
@chowryan so far it's working and logged the output to a .csv file. But no arbitrage discovered yet. The error usually happens if you keep the bot running for a couple of hours. I will keep you posted.

<img width="947" alt="putty_ISdJrPeh20" src="https://user-images.githubusercontent.com/50150287/65293238-22123100-db8d-11e9-8fbe-3541ed494cc4.png">

**Comment by dennisocana** [comment]
@chowryan I'm getting the same errors with Binance.

<img width="947" alt="putty_idfQSPF3WR" src="https://user-images.githubusercontent.com/50150287/65295565-6523d280-db94-11e9-96ec-27260422882e.png">

**Comment by rennel-tabing** [comment]
I had the this error running the same strategy using the latest development  branch as of this writing.
![image](https://user-images.githubusercontent.com/53868268/65330982-cabe9180-db89-11e9-8ee5-8e27e8a8584a.png)

branch: development
Commit: 71c39c2
date: 2019-09-20T06:57:30Z

**Comment by yzhang1994** [comment]
@rennel-tabing I believe what you are seeing is a separate bug. Could you send me your log file?

**Comment by rennel-tabing** [comment]
@yzhang1994 The error no longer exists after updating to 
```
 "branch": "development",
 "commit": "51434d1f825af3ad3d599db3a352230b56099cea",
 "date": "2019-09-21T14:50:30Z",
```

**Comment by dennisocana** [comment]
This is confirmed working in version 0.15.0 release.
