### ISSUE TITLE
[BUG] XEMM Selling out of Base Currency

### ISSUE THREAD

**Issue by joesixpack** [CoinAlpha/hummingbot#790]
**Describe the bug**
I've seen this happen twice in the past several days, both occuring in the 00:00 hour.  Suddenly, all but dust of the base currency is sold off rapidly.  While it shows up in the Binance trade history, the trades are not in the bot history and not reported to the bounty.

**Steps To Reproduce**
Just run XEMM as per normal.

**Screenshots**
![image](https://user-images.githubusercontent.com/23145642/64920915-ae79b980-d771-11e9-9eca-c3a97c750658.png)
![image](https://user-images.githubusercontent.com/23145642/64920920-b5a0c780-d771-11e9-9416-5344166a641e.png)
![image](https://user-images.githubusercontent.com/23145642/64920980-6eff9d00-d772-11e9-8838-4392c816bdee.png)
![image](https://user-images.githubusercontent.com/23145642/64920972-66a76200-d772-11e9-939a-b5d7f7b93abc.png)

**Release version**
14.0

**Attachments**
[configs&logs.zip](https://github.com/CoinAlpha/hummingbot/files/3613712/configs.logs.zip)

Your ETH address: Provided upon request.

**Comment by martinkou** [comment]
@veecos2 please take a look

**Comment by veecos2** [comment]
@joesixpack: We have recently changed the Xemm strategy. Request you to please create a new config file. You can find the updated documentation here https://docs.hummingbot.io/strategies/cross-exchange-market-making/.

**Comment by veecos2** [comment]
I will look into the other issues you have mentioned as well.

**Comment by veecos2** [comment]
@joesixpack: The latest Xemm strategy appears to be working fine. I executed some trades and they appear in the bot history. I will add the check so that earlier configs will not be used with the current strategy.

**Comment by joesixpack** [comment]
These new fields don't seem to be in v0.14.0.  I just did the config manually and only the older options were presented.

**Comment by veecos2** [comment]
This is currently in the development branch. We will be releasing this in upcoming release.

**Comment by chowryan** [comment]
seems like this is fixed. please reopen if not.
