### ISSUE TITLE
Suggestion for modification to your current arbitrage methodology

### ISSUE THREAD

**Issue by Tilanthi** [CoinAlpha/hummingbot#795]
Is there any possibility please to modify the strategy to support intra-exchange arbitrage - then it might get >really< interesting by skipping the need to have two different exchanges involved and doing it all on a single exchange?

As a second question, have you looked at quad intra-exchange arbitrage - this is little used, but was a >highly< profitable strategy back in the days of zero fee exchanges - but its profitability fell away a little once GDAX reverted to adding fees to maker calls and I am not sure how well it will fare under current market conditions and with, for example, Binance Tier 0 or Tier 1 fees?

Many thanks, @Tilanthi on your DISCORD channel

**Comment by chowryan** [comment]
the name is misleading for the strategy but you are allowed to use the same exchange ie binance 'ETH-USDT' and binance 'ETH-USDC'
