### ISSUE TITLE
[BUG] Failed to start running a bot on IDEX

### ISSUE THREAD

**Issue by znerol19619** [CoinAlpha/hummingbot#804]
**Describe the bug**
Getting error running pmm on idex

**Steps To Reproduce**
Just run a normal pure market making

**Screenshots**
![image](https://user-images.githubusercontent.com/27669951/65237017-5d205000-db0c-11e9-8b50-7fb76580d11e.png)

``2019-09-19 09:16:25,226 - hummingbot.client.hummingbot_application - ERROR - Can't instantiate abstract class IDEXAPIOrderBookDataSource with abstract methods listen_for_trades
Traceback (most recent call last):
  File "/hummingbot/client/command/start_command.py", line 106, in start_market_making
    self.starting_balances = await self.wait_till_ready(self.balance_snapshot)
  File "/hummingbot/client/command/start_command.py", line 42, in wait_till_ready
    all_ready = all([market.ready for market in self.markets.values()])
  File "/hummingbot/client/command/start_command.py", line 42, in <listcomp>
    all_ready = all([market.ready for market in self.markets.values()])
  File "idex_market.pyx", line 162, in hummingbot.market.idex.idex_market.IDEXMarket.ready.__get__
  File "idex_market.pyx", line 154, in hummingbot.market.idex.idex_market.IDEXMarket.status_dict.__get__
  File "/hummingbot/core/data_type/order_book_tracker.py", line 86, in ready
    symbols: List[str] = self.data_source._symbols or []
  File "/hummingbot/market/idex/idex_order_book_tracker.py", line 65, in data_source
    self._data_source = IDEXAPIOrderBookDataSource(idex_api_key=self._idex_api_key, symbols=self._symbols)
TypeError: Can't instantiate abstract class IDEXAPIOrderBookDataSource with abstract methods listen_for_trades``

**Release version**
version: 0.15.0
branch: development
commit: ``4f7b4d71eea118274395a3bb82128f0f9803a8a1``
date: 2019-09-19T01:23:32Z

**Attachments**
[hummingbot_logs_2019-09-19-09-04-01.log](https://github.com/CoinAlpha/hummingbot/files/3630740/hummingbot_logs_2019-09-19-09-04-01.log)
[conf_pmm_idex.txt](https://github.com/CoinAlpha/hummingbot/files/3630749/conf_pmm_idex.txt)

**Comment by rennel-tabing** [comment]
had the same error using the same development version.

**Comment by PtrckM** [comment]
tested on both version same error.

```
                "branch": "master",
                "commit": "a1bce79aae846b396b591b12208a75103ab2e361",
                "date": "2019-09-09T17:57:15Z",
```
```
                "branch": "development",
                "commit": "62ade2f7a055d51f6c907dc3119bc4c93f815a17",
                "date": "2019-09-20T00:11:45Z",
```

**Comment by chowryan** [comment]
fixed on dev thanks
