### ISSUE TITLE
[BUG] Bamboorelay showing up as filled in hummingbot, but are actually not filled on Bamboorelay

### ISSUE THREAD

**Issue by AlTheAlligator** [CoinAlpha/hummingbot#817]
**Describe the bug**
// A clear and concise description of what the bug is.
Hummingbot will log that a limitorder has been (partially)filled on the maker side (Bamboorelay using Cross market making strat) and then create a market order on the taker side (Binance).
If you then go to bamboo relay, you can see that no order went through and the wallet still has the initial amount, so no transaction happened.
The market order on binance went through correctly, so now there is a missmatch as an order was only executed on the taker side, not the maker side.

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: 
Cross market making
bamboorelay as maker and binance as taker
active_order_canceling: false
Bamboo_relay_use_coordinator: true
bamboo_relay_pre_emptive_soft_cancels: true

2. Start the bot using this command: 
Start

**Screenshots**
// If applicable, add screenshots to help explain your problem.
![unknown](https://user-images.githubusercontent.com/8904635/65378883-2fc7d380-dcbf-11e9-8c16-a80194667ef8.png)

**Release version**
// Include your bot's version number (Can be found at the bottom left corner of your CLI).
0.14.0

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 
[hummingbot_logs_2019-09-21-15-14-53.log](https://github.com/CoinAlpha/hummingbot/files/3639058/hummingbot_logs_2019-09-21-15-14-53.log)
Order gets filled at 15:34:26,609

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:** 
**Optional: your ETH address:** (If you want to participate in the bug bounty)

**Comment by rennel-tabing** [comment]
Here is the complete config used by @AlTheAlligator 
```
########################################################
###   Cross exchange market making strategy config   ###
########################################################

# The following configuations are only required for the
# cross exchange market making strategy

# Exchange and token parameters
maker_market: radar_relay
taker_market: binance
maker_market_symbol: BAT-WETH
taker_market_symbol: BATETH

# Minimum profitability target required to place an order
# Expressed in decimals: 0.01 = 1% target profit
min_profitability: 0.007

# Maximum order size in terms of quote currency
trade_size_override: 0.0

# Maximum aggregate amount of orders in quote currency
# that are allowed at a better price than Hummingbot's
# order before Hummingbot adjusts its order and pricing
top_depth_tolerance:

- - ^.+(USDT|USDC|USDS|DAI|PAX|TUSD)$
  - 0
- - ^.+ETH$
  - 0
- - ^.+BTC$
  - 0
# Have Hummingbot actively adjust/cancel orders if necessary.
# If set to true, outstanding orders are adjusted if
# profitability falls below min_profitability.
# If set to false, outstanding orders are adjusted if
# profitability falls below cancel_order_threshold.
active_order_canceling: false

# If active_order_canceling = false, this is the profitability/
# loss threshold at which to cancel the order.
# Expressed in decimals: 0.01 = 1% target profit
cancel_order_threshold: -1.0

# An amount in seconds, which is the minimum duration for any
# placed limit orders. Default value = 130 seconds.
limit_order_min_expiration: 130.0

# For more detailed information, see:
# https://docs.hummingbot.io/strategies/cross-exchange-market-making/#configuration-parameters
```

![image](https://user-images.githubusercontent.com/53868268/65381529-5a1a9080-dcc1-11e9-972a-27bec4cff695.png)


The Etherscan using his ETH address shows no `BAT` assets being moved for today
https://etherscan.io/address/0x123b003186Bd158878aAB62354d6BA2c4E22141F

**Comment by Arctek** [comment]
I spoke with @AlTheAlligator, and it turns out he was running a bot on Radar and Bamboo at the same time.

Because orders are syndicated across this resulted in orders on the sell side out numbering the available BAT balance.

This is then adjusted down accordingly, but because the connector reads a single value remaining it assumes this change occurred from a fill.
This then means the strategy then hedges on the taker market (binance).

I'm going to look at re-working some of the API/connector so it only records fills when there are mined transaction receipts to prove it and not when the `remainingBaseAmount` field changes.

In the short term the fix here is to only run a bot across a single market bamboo/radar.
