### ISSUE TITLE
[BUG] Arbitrage - False positives are returned by Bamboo Relay

### ISSUE THREAD

**Issue by k4ms** [CoinAlpha/hummingbot#818]
**Describe the bug**

Bamboo relay returns orders that are unfillable but the hummingbot acts as if they were real orders. A check should be added in the same manner as what is done on the exchange's website to avoid returning false positives and triggering asymetric trades. In my case I had an order executed on Binance to buy USDC with 7 ETH ( rate: 216.09 USDC/ETH) whereas the executed order on Bamboo relay finally bought only 0.000123056266363578 WETH with 0.023 DAI (rate of 195 DAI/WETH)
https://etherscan.io/tx/0x362f4b603903465f2c5f89059786ce69e8bc7be4dc218ee5ced3f62cb5f437b4

**Steps To Reproduce**

Configure the bot in arbitrage mode between Binance ETHUSD (or ETHUSDC, ETHUSDT,...) and Bamboo Relay WETH-DAI. Be sure to have enough tokens on the both sides.
Here are the steps to reproduce the issue (see attachments in the section below):

1. Set up your configuration file with these parameters: 
primary_market: bamboo_relay
secondary_market: binance
primary_market_symbol: WETH-DAI
secondary_market_symbol: ETHUSDC

min_profitability: 0.005

2. Start the bot using this command: ./start.sh

**Release version**
version 0.14.0

**Attachments**
enclosed you will find : 
- logs
[hummingbot_logs_2019-09-21-20-51-43.log](https://github.com/CoinAlpha/hummingbot/files/3639152/hummingbot_logs_2019-09-21-20-51-43.log)

- Illustration how the sell order of 195 DAI/ETH  appears on https://bamboorelay.com/trade/WETH-DAI
PDF: [WETH - DAI - Bamboo Relay - before order.pdf](https://github.com/CoinAlpha/hummingbot/files/3639168/214.95784470WETH.-.DAI.-.Bamboo.Relay.-.before.order.pdf)

- Illustration how this order is removed from the web interface if we attempt to take it and how we are informed
PDF: [WETH - DAI - Bamboo Relay - order unfillable.pdf](https://github.com/CoinAlpha/hummingbot/files/3639171/213.42835449WETH.-.DAI.-.Bamboo.Relay.-.order.unfillable.pdf)

**Optional: your ETH address:
0x997F5eADd7C4366548Bb866857061cf8DD2D0F63

**Comment by rennel-tabing** [comment]
This bug looks to be related to https://github.com/CoinAlpha/hummingbot/issues/817

**Comment by yzhang1994** [comment]
Closing as this is probably stale
