### ISSUE TITLE
[BUG] Discovery fails to get profit in Huobi

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#825]
**Describe the bug**

Performed testing with Discovery strategy. All tests passed except when running on Huobi. All tests are performed with `target_profitability 0.0` and `target_amount inf`.

latest: `2019-09-23T17:29:45Z`
development: `2019-09-23T17:57:25Z`

## Test 1 :  bamboo_relay & radar_relay (all pairs)

version: dev-0.16.0

target_symbol_1: all (304 order books)
target_symbol_2: all (635 order books)

start: 03:16:12
end: 03:28:50

- success in less than 15 minutes
- with both DEXs, total of 939 order books initialized

Log file: [bamboo_radar_all.log](https://github.com/CoinAlpha/hummingbot/files/3646073/bamboo_radar_all.log)

<img width="674" alt="bamboo_radar_all" src="https://user-images.githubusercontent.com/50150287/65494363-4486b000-dee7-11e9-8a5f-2bff47dc113f.png">

## Test 2 : huobi & ddex (all pairs)

version: latest 0.15.0

target_symbol_1: all (538 order books)
target_symbol_2: all (358 order books)

start: 00:34:48
end: 04:14:00

- arbitrage discovery not ready yet
- total of 893 order books, smaller than test 1
- bot uptime of almost 4 hours
- goes into a loop and will reinitialize order books from the beginning

Log file: 
[huobi_ddex_all.log](https://github.com/CoinAlpha/hummingbot/files/3646093/huobi_ddex_all.log)

<img width="947" alt="huobi_ddex_all" src="https://user-images.githubusercontent.com/50150287/65495160-d3e09300-dee8-11e9-817b-16603b3c42ff.png">

## Test 3 : huobi & ddex (single pair)

version: latest 0.15.0

target_symbol_1: zrxeth
target_symbol_2: ZRX-WETH

start: 05:02:38
end: 07:01:26

- arbitrage discovery not ready yet
- initializing huobi and ddex order book goes into a loop

Log file: [huobi_ddex_zrx-eth.log](https://github.com/CoinAlpha/hummingbot/files/3646098/huobi_ddex_zrx-eth.log)

<img width="947" alt="huobi_ddex_zrx-eth" src="https://user-images.githubusercontent.com/50150287/65495230-fa063300-dee8-11e9-81cd-773b4212e41a.png">

## Test 4 : binance & huobi (all pairs)

version: dev-0.16.0

target_symbol_1: all (538 order books)
target_symbol_2: all (577 order books)

start: 00:52:21
end: 03:42:39

- arbitrage discovery not ready yet
- initializing binance order books goes into a loop

Log file: 
[binance_huobi_all.log](https://github.com/CoinAlpha/hummingbot/files/3646111/binance_huobi_all.log)

<img width="947" alt="binance_huobi_all" src="https://user-images.githubusercontent.com/50150287/65495540-7ef14c80-dee9-11e9-98ac-e99a16e54dd6.png">

## Test 5 : binance & huobi (single pair)

version: dev-0.16.0

target_symbol_1: ZRX-ETH
target_symbol_2: zrxeth

start: 07:10:06
end: 07:10:11

- arbitrage discovery not ready yet

Log file: 
[binance_huobi_zrx-eth.log](https://github.com/CoinAlpha/hummingbot/files/3646125/binance_huobi_zrx-eth.log)

<img width="947" alt="binance_huobi_zrx-eth" src="https://user-images.githubusercontent.com/50150287/65495729-ce377d00-dee9-11e9-8458-85956fb0a391.png">

## Test 6 : ddex & idex (all pairs)

version: dev-0.16.0

target_symbol_1: all (359 order books)
target_symbol_2: all (657 order books)

start: 07:17:03
end: 07:31:13

- success in less than 15 minutes
- both DEXs, total of 1,016 order books

Log file: 
[ddex_idex_all.log](https://github.com/CoinAlpha/hummingbot/files/3646148/ddex_idex_all.log)

<img width="947" alt="ddex_idex_all" src="https://user-images.githubusercontent.com/50150287/65495937-22426180-deea-11e9-8c31-1487de114f36.png">

## Test 7 : binance & idex (all pairs)

version: dev-0.16.0

target_symbol_1: all (625 order books)
target_symbol_2: all (657 order books)

start: 08:45:16
end: 08:59:41

Log file: 
[binance_idex_all.log](https://github.com/CoinAlpha/hummingbot/files/3646278/binance_idex_all.log)

- success, almost 15 minutes
- CEX and DEX, total of 1,282 order books

<img width="674" alt="binance_idex_all" src="https://user-images.githubusercontent.com/50150287/65497434-d644ec00-deec-11e9-85f9-5ef69d8bafdf.png">

**Comment by dennisocana** [comment]
Performed one more test with Binance and IDEX and works fine. Looks like the issue is with Huobi exchange.

## Test 7 : binance & idex (all pairs)

version: dev-0.16.0

target_symbol_1: all (625 order books)
target_symbol_2: all (657 order books)

start: 08:45:16
end: 08:59:41

Log file: 
[binance_idex_all.log](https://github.com/CoinAlpha/hummingbot/files/3646278/binance_idex_all.log)

- success, almost 15 minutes
- CEX and DEX, total of 1,282 order books

<img width="674" alt="binance_idex_all" src="https://user-images.githubusercontent.com/50150287/65497434-d644ec00-deec-11e9-85f9-5ef69d8bafdf.png">

**Comment by znerol19619** [comment]
I tried running discovery on huobi & idex, and its not initializing the order book on idex. After all pairs are scanned on huobi it will give a websocket warning. 
verion: latest 0.15.0
[hummingbot_logs_2019-09-24-08-09-37.txt](https://github.com/CoinAlpha/hummingbot/files/3646419/hummingbot_logs_2019-09-24-08-09-37.txt)

**Comment by dennisocana** [comment]
Re-ran a single pair discovery bot with Huobi and Binance. After almost an hour, found this in the logs.

```
2019-09-24 08:58:26,650 - hummingbot.market.huobi.huobi_api_order_book_data_source - ERROR - Unexpected error with WebSocket connection. Retrying after 30 seconds...
Traceback (most recent call last):
  File "/hummingbot/market/huobi/huobi_api_order_book_data_source.py", line 230, in listen_for_order_book_diffs
    await ws.send(f'{{"op":"pong","ts": {str(msg["ping"])}}}')
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/websockets/protocol.py", line 361, in send
    yield from self.ensure_open()
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/websockets/protocol.py", line 501, in ensure_open
    self.close_code, self.close_reason) from self.transfer_data_exc
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1003 (unsupported type), reason = ping check expired, session: 50c7f50e-6f03-4e42-a50f-4c5db15e347c
```

```
2019-09-24 09:12:36,182 - hummingbot.market.huobi.huobi_api_order_book_data_source - ERROR - Unexpected error with WebSocket connection. Retrying after 30 seconds...
Traceback (most recent call last):
  File "/hummingbot/market/huobi/huobi_api_order_book_data_source.py", line 215, in listen_for_order_book_diffs
    async with websockets.connect(HUOBI_WS_URI) as ws:
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/websockets/py35/client.py", line 2, in __aenter__
    return await self
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/websockets/py35/client.py", line 19, in __await_impl__
    extra_headers=protocol.extra_headers,
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/websockets/client.py", line 263, in handshake
    raise InvalidStatusCode(status_code)
websockets.exceptions.InvalidStatusCode: Status code not 101: 525
```

[hummingbot_logs_2019-09-24-07-10-03.log](https://github.com/CoinAlpha/hummingbot/files/3646425/hummingbot_logs_2019-09-24-07-10-03.log)

**Comment by michaelc9** [comment]
Thanks. We are investigating the issue.

**Comment by veecos2** [comment]
I ran into segmentation fault and the bot automatically shut down while trying to run for all pairs between Huobi and Binance.
