### ISSUE TITLE
[BUG] Huobi | Assets are not displayed when using Cross exchange MM Strategy

### ISSUE THREAD

**Issue by rennel-tabing** [CoinAlpha/hummingbot#826]
**Describe the bug**
// A clear and concise description of what the bug is.
When using Huobi on XEMM, the token pairs are using lower case by default when creating the config strategy
This causes the assets to not be fetched properly and  will show "0" in  value

Modifying the `conf_global.yml` and replacing the value of the Houbi token pair to upper case will fix the issue

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:
Create a XEMM strategy and run as normal

Here are the steps to reproduce the issue (see attachments in the section below):
```
# Exchange and token parameters
maker_market: huobi
taker_market: binance
maker_market_symbol: batusdt
taker_market_symbol: BATUSDT

# Minimum profitability target required to place an order
# Expressed in decimals: 0.01 = 1% target profit
min_profitability: 0.007

# Maximum order size in terms of base currency
order_amount: 70.0

# Have Hummingbot actively adjust/cancel orders if necessary.
# If set to true, outstanding orders are adjusted if
# profitability falls below min_profitability.
# If set to false, outstanding orders are adjusted if
# profitability falls below cancel_order_threshold.
active_order_canceling: true

# If active_order_canceling = false, this is the profitability/
# loss threshold at which to cancel the order.
# Expressed in decimals: 0.01 = 1% target profit
cancel_order_threshold: 0.05

# An amount in seconds, which is the minimum duration for any
# placed limit orders. Default value = 130 seconds.
limit_order_min_expiration: 3000.0

# If enabled (parameter set to `True`), the strategy will place the order on top of the top bid and ask,
# if its more profitable to place it there
adjust_order_enabled: true

# An amount expressed in base currency which is used for getting the top bid and ask,
# ignoring dust orders on top of the order book
top_depth_tolerance: 0.0

# An amount in seconds, which is the minimum amount of time interval between adjusting limit order prices
anti_hysteresis_duration: 60.0

# An amount expressed in decimals (i.e. input of `0.01` corresponds to 1%), which is the maximum size limit of new limit orders,
# in terms of ratio of hedge-able volume on taker side.
order_size_taker_volume_factor: 0.25

# An amount expressed in decimals (i.e. input of `0.01` corresponds to 1%), which is the maximum size limit of new limit orders,
# in terms of ratio of asset balance available for hedging trade on taker side
order_size_taker_balance_factor: 0.995

# An amount expressed in decimals (i.e. input of `0.01` corresponds to 1%), which is the maximum size limit of new limit orders,
# in terms of ratio of total portfolio value on both maker and taker markets
order_size_portfolio_ratio_limit: 0.1667
```

...

**Screenshots**
// If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/53868268/65527152-32dde200-dec0-11e9-9892-38eecb19c949.png)

**Release version**
// 0.15.0
```
                "branch": "master",
                "commit": "4941ec38b8090b8f458d19ca5ad98d667f561b4e",
                "date": "2019-09-23T17:29:45Z",
```

**Attachments**
// 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:** bob_tan
**Optional: your ETH address:** (If you want to participate in the bug bounty)

**Comment by rennel-tabing** [comment]
after running the strategy again with the modified Houbi token pair (All CAPS), its now goving an error
![image](https://user-images.githubusercontent.com/53868268/65531159-3e80d700-dec7-11e9-8ff0-0714ebd82c58.png)

**Comment by michaelc9** [comment]
@rennel-tabing Thanks. We have a PR for the fix.
https://github.com/CoinAlpha/hummingbot/pull/833

**Comment by rennel-tabing** [comment]
Here is the users ETH address as he would like to participate on the `Bug Bounty program`

`0x09B4bFD35D8a58CC14E30bA02108cD56383E455d`

**Comment by moraliang** [comment]
Bounty has been sent.
