### ISSUE TITLE
[BUG] Runtime Warning on restart after sending list configs command

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#828]
**Describe the bug**

Bot gets disconnected from the network and fails to restart after triggering an error produced by command `list configs`:

```
/opt/conda/envs/hummingbot/lib/python3.6/asyncio/events.py:145: RuntimeWarning:
coroutine 'ERC20Token.get_decimals' was never awaited
self._callback(*self_args)
```

## Test 1

Sending `list configs` command will show an error in running logs:

```
- root - ERROR - Unhandled error in background task: unsupported operand type(s) for +=:
'NoneType' and 'str' (See log file for stack trace dump)
```

<img width="947" alt="1 - list configs" src="https://user-images.githubusercontent.com/50150287/65564530-caeed080-df7f-11e9-87e0-6809e605f6a1.png">

Trace dump:

```
2019-09-25 01:13:02,451 - root - ERROR - Unhandled error in background task: unsupported operand type(s) for +=: 'NoneType' and 'str'
Traceback (most recent call last):
  File "/hummingbot/core/utils/async_call_scheduler.py", line 80, in _coro_scheduler
    fut.set_result(await coro)
  File "/opt/conda/envs/hummingbot/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/hummingbot/notifier/telegram_notifier.py", line 185, in <lambda>
    reply_markup=reply_markup
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/telegram/bot.py", line 65, in decorator
    result = func(self, *args, **kwargs)
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/telegram/bot.py", line 90, in decorator
    result = self._request.post(url, data, timeout=kwargs.get('timeout'))
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/telegram/utils/request.py", line 309, in post
    headers={'Content-Type': 'application/json'})
  File "/opt/conda/envs/hummingbot/lib/python3.6/site-packages/telegram/utils/request.py", line 223, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Message must be non-empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/hummingbot/core/utils/async_utils.py", line 8, in safe_wrapper
    return await c
  File "/hummingbot/core/utils/async_call_scheduler.py", line 92, in _coro_scheduler
    app_warning_msg += f" [[Got exception: {str(e)}]]"
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'
```

The bot will continue to cancel and place orders but will start to get errors like markets are offline, eth wallet not connected, NetworkStatus.NOT_CONNECTED.

<img width="947" alt="2 - market goes offline" src="https://user-images.githubusercontent.com/50150287/65564561-e35eeb00-df7f-11e9-810d-209f15478071.png">

Stopping and restarting the strategy will give an error:

```
/opt/conda/envs/hummingbot/lib/python3.6/asyncio/events.py:145: RuntimeWarning:
coroutine 'ERC20Token.get_decimals' was never awaited
self._callback(*self_args)
```

<img width="947" alt="3 - error on restart" src="https://user-images.githubusercontent.com/50150287/65564605-01c4e680-df80-11e9-8150-7dd29b27be73.png">
<img width="947" alt="4- status on restart" src="https://user-images.githubusercontent.com/50150287/65564609-05586d80-df80-11e9-885e-4b2938331203.png">

## Test 2 (Binance)

Performed test with the same steps on a different exchange (Binance). Command `list config` will show an error in running logs but it did not give a run time warning as seen on IDEX when restarted. Bot continued to behave as expected.

**Release version**

Tests have been performed on both latest and development version.

"branch": "master",
"commit": "4941ec38b8090b8f458d19ca5ad98d667f561b4e",
"date": "2019-09-23T17:29:45Z",

"branch": "development",
"commit": "69d71a42e1ad42c72320360d1fd4dc78f8aeae4a",
"date": "2019-09-23T17:57:25Z",

**Attachments**

Strategy config file: 
[conf_pmm_base-eth.txt](https://github.com/CoinAlpha/hummingbot/files/3650306/conf_pmm_base-eth.txt)
Log file: 
[hummingbot_logs_2019-09-25-00-01-56.log](https://github.com/CoinAlpha/hummingbot/files/3650307/hummingbot_logs_2019-09-25-00-01-56.log)

**Comment by dennisocana** [comment]
## Test 3 (Bamboo Relay)

Same issue happened on a different strategy (cross-exchange) and connector.

<img width="947" alt="xemm_bamboo_binance" src="https://user-images.githubusercontent.com/50150287/65743758-92d6c180-e128-11e9-966d-c18f7a5da809.png">

## Test 4 (DDEX)

Pure market making bot in DDEX did not show any of both errors.

**Comment by yzhang1994** [comment]
This should have been fixed. @dennisocana let me know if you see it again.
