### ISSUE TITLE
[BUG] Telegram notifier sends messages from non Telegram inputs

### ISSUE THREAD

**Issue by iicc1** [CoinAlpha/hummingbot#844]
**Describe the bug**
With Telegram notifier enabled, if you send commands to the Telegram bot, it answers throught Telegram and the cli, but if you send any command to the cli, the response is sent both to the cli and Telegram.

**Steps To Reproduce**
Having the Telegram notifier enabled and the hummingbot started, on the cli, write "status" and the response will be sent to the cli and the Telegram bot.

Here are the steps to reproduce the issue (see attachments in the section below):
1. Configure the Telegram notifier and be sure it is working fine.
2. Create any configuration, I have tested with Arbitrage, XEMM and discovery.
3. Start the bot.
4. Send the command "status" from the cli.

**Release version**
Tested with 0.15.0 and dev 0.16.0

**Attachments**
I have not found anything interesting in the logs.

**Optional: your discord username:** iicc#4715

**Comment by rennel-tabing** [comment]
I am able to reproduce the behavior but I think this is expected since telegram acts as an extension of the hummingbot CLI.

**Comment by iicc1** [comment]
> 
> 
> I am able to reproduce the behavior but I think this is expected since telegram acts as an extension of the hummingbot CLI.

You may be right. Anyway I think is a bit annoying to be configuring and testing your bot on the CLI and afterwards you open Telegram and you have been flooded with dozens of messages.

**Comment by PtrckM** [comment]
Messages are synchronized in real-time between the Telegram bot and the actual Hummingbot instance running.

**Comment by znerol19619** [comment]
Its expected to get that behavior, as telegram bot populates the commands result made on hummingbot cli real-time and vice versa

**Comment by iicc1** [comment]
Understood, thanks for the replies.
