### ISSUE TITLE
[BUG] Wrong ETH wallet preliminary check with PMM in Idex

### ISSUE THREAD

**Issue by iicc1** [CoinAlpha/hummingbot#845]
**Describe the bug**
The bot does not start the pure market making strategy in Idex because of this preliminary check:
```x ETH wallet check: Not enough ETH in wallet. A small amount of Ether is required for sending transactions on Decentralized Exchanges```
But I have enough balance on my wallet, and enough inventory to make orders.

**Steps To Reproduce**
Configure a pure market making strategy in Idex and start the bot.

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters:
```
maker_market: idex
maker_market_symbol: ETH_LTO
order_amount: 1.0
cancel_order_wait_time: 20.0
bid_place_threshold: 0.03
ask_place_threshold: 0.03
mode: single
number_of_orders: 1
order_start_size: 1.0
order_step_size: 0.0
order_interval_percent: 0.01
inventory_skew_enabled: true
inventory_target_base_percent: 0.5
filled_order_replenish_wait_time: 10.0
enable_order_filled_stop_cancellation: false
jump_orders_enabled: true
jump_orders_depth: 0.0
```
2. Start the bot with ```start```
3. Check the bot status with ```status``` and the preliminary check will pop-up.

**Screenshots**
[CLI screenshot](https://i.imgur.com/fzymbST.jpg)
[Idex balances](https://i.imgur.com/PT9q53r.jpg)
[Wallet balances](https://i.imgur.com/YeG6Hr7.jpg)

**Release version**
Tested with 0.15.0 and lastest dev 0.16.0 image.

**Attachments**
Log: [hummingbot_logs_2019-09-29-19-35-39.log](https://github.com/CoinAlpha/hummingbot/files/3668007/hummingbot_logs_2019-09-29-19-35-39.log)
Config: [conf_pure_market_making_strategy_0.yml.txt](https://github.com/CoinAlpha/hummingbot/files/3668008/conf_pure_market_making_strategy_0.yml.txt)

**Optional: your discord username:** iicc#4715
**Optional: your ETH address:** 0x3Be7Fe9be7a924A51564715A1C00d141EEB045F1

**Comment by chowryan** [comment]
do you have your ethereum node `ethereum_rpc_url` set up properly in hb_global.yml?

**Comment by iicc1** [comment]
> 
> 
> do you have your ethereum node `ethereum_rpc_url` set up properly in hb_global.yml?

Yes. Also, other strategies work correctly on Idex

**Comment by dennisocana** [comment]
Maker orders must be at least the equivalent of 0.15 ETH in IDEX and taker orders must be at least 0.05 ETH.

**Comment by dennisocana** [comment]
Maker orders must be at least equivalent to 0.15 ETH. See what happens if you set `order_amount` to 1000. It should create orders, just want to check what happens when it's placing orders while having the wallet check warning.

**Comment by iicc1** [comment]
> 
> 
> Maker orders must be at least equivalent to 0.15 ETH. See what happens if you set `order_amount` to 1000. It should create orders, just want to check what happens when it's placing orders while having the wallet check warning.

That was the problem, orders were lower than 0.15 ETH. It is still the wallet check warning but works fine.

**Comment by znerol19619** [comment]
Confirmed that bot works fine as expected, despite having the ``ETH wallet check`` message

**Comment by znerol19619** [comment]
Fixed. ``Eth balance check`` warning is not showing anymore
![idex_working](https://user-images.githubusercontent.com/27669951/66895862-4cd59500-f026-11e9-8931-a17891f70a63.png)

**Comment by iicc1** [comment]
I can confirm the balance check warning is not showing anymore, great work. Closing issue.
