### ISSUE TITLE
[BUG] Trades not showing in trade history

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#853]
**Describe the bug**

Some of the trades executed in the exchange are not showing in trade history and exported trades.

Here's the exported trades from Hummingbot:
[trades_2019-10-01-03-04-24.xlsx](https://github.com/CoinAlpha/hummingbot/files/3674712/trades_2019-10-01-03-04-24.xlsx)

And here's from Huobi:
[OrderHistory-20191001.xlsx](https://github.com/CoinAlpha/hummingbot/files/3674711/OrderHistory-20191001.xlsx)

Executed trades from 9/29/2019 14:24 to the latest timestamp did not show in Hummingbot but are in the logs.

**Release version**

"branch": "development",
"commit": "563befd726d2fd523fb884b3124d7f85882851ab",
"date": "2019-09-27T00:14:48Z",

**Attachments**

[hummingbot_logs_2019-09-28-02-30-40.log](https://github.com/CoinAlpha/hummingbot/files/3674722/hummingbot_logs_2019-09-28-02-30-40.log)

**Comment by rennel-tabing** [comment]
I did a BAT/USDT pair and I am able to reproduce the error running cross exchange between Huobi and binance exchange

![image](https://user-images.githubusercontent.com/53868268/66260737-b2a55f80-e790-11e9-870c-1af220e5fa00.png)

I am using `version - 0.15.0`

**Comment by michaelc9** [comment]
@rennel-tabing @dennisocana 
This is expected behaviour. In the history command, the bot will only show trades executed during the current session. The reason for this behaviour is to avoid loading too many trades into the bot display.
All older trades from previous sessions should be stored in the local database. Can you guys verify that those trades are in the database?

**Comment by rennel-tabing** [comment]
Here are the database and hummingbot CLI results showing a single trade

![image](https://user-images.githubusercontent.com/53868268/67875182-6558ab80-fb0c-11e9-8122-5abecfdc86ac.png)


Here are my Huobi trades for today showing multiple trades
![image](https://user-images.githubusercontent.com/53868268/67874775-cfbd1c00-fb0b-11e9-86d9-86c5369d1365.png)

[logs_conf_cross_exchange_market_making_strategy_0.txt](https://github.com/CoinAlpha/hummingbot/files/3789943/logs_conf_cross_exchange_market_making_strategy_0.txt)

Using hummingbot version 0.17.1

**Comment by yzhang1994** [comment]
Closing as this is probably stale
