### ISSUE TITLE
[BUG] Discovery fails to show the profitability coinbase_pro - idex

### ISSUE THREAD

**Issue by PtrckM** [CoinAlpha/hummingbot#863]
**Describe the bug**
Discovery fails to show the profitability between two markets

tested 3 different VM's
VM1: wait 10 mins for profitability
VM2: wait 15 mins for profitability
Vm3: wait 40 mins for profitability

**Screenshots**
![image](https://user-images.githubusercontent.com/54516858/66099149-408a1a80-e5d8-11e9-9fc3-e64fb2aa0b66.png)

**Release version**
```
                "branch": "dev-0.16.0",
                "commit": "7e1d3906e0f67bdf442246f0816e9205a5edb6dd",
                "date": "2019-10-02T18:20:23Z",
```

```
#####################################
###   Discovery strategy config   ###
#####################################

# The following configuations are only required for the
# discovery strategy

# Exchange and token parameters
primary_market: idex
secondary_market: coinbase_pro

# Minimum profitability target required to place an order
# Expressed in decimals: 0.01 = 1% target profit
target_profitability: 0.0
target_amount: .inf

target_symbol_1: []
target_symbol_2: []
equivalent_tokens:
- - USDT
  - USDC
  - USDS
  - DAI
  - PAX
  - TUSD
  - USD
- - ETH
  - WETH
- - BTC
  - WBTC
# For more detailed information, see:
# https://docs.hummingbot.io/strategies/discovery/
```

**Comment by znerol19619** [comment]
Test bug report with same config
                "branch": "dev-0.16.0",
                "commit": "7e1d3906e0f67bdf442246f0816e9205a5edb6dd",
                "date": "2019-10-02T18:20:23Z",

Successfully scanned all pairs on two exchanges, and produce profitable pairs and .csv file.

**Comment by rennel-tabing** [comment]
Running the config was working as expected on my end 

![image](https://user-images.githubusercontent.com/53868268/66124742-343f9680-e5b3-11e9-8ff2-7bc9d2295dbf.png)

![image](https://user-images.githubusercontent.com/53868268/66124817-6a7d1600-e5b3-11e9-8d0c-2a48601e6c5f.png)

![image](https://user-images.githubusercontent.com/53868268/66124848-81236d00-e5b3-11e9-8962-6b21af5ec0ba.png)

**Comment by BUDDHA-TONY** [comment]
tested the config and was successful. 
![test](https://user-images.githubusercontent.com/55869559/66168222-3d8e3900-e66f-11e9-8c98-2303bf3337b7.png)
![test1](https://user-images.githubusercontent.com/55869559/66168223-3d8e3900-e66f-11e9-98dc-6f213140aa5b.png)
![test3](https://user-images.githubusercontent.com/55869559/66168224-3e26cf80-e66f-11e9-925f-0e642d52afaf.png)

**Comment by PtrckM** [comment]
Thank you guys.

**Resolution:** open idex website accept new TOS for using API, generate new API, problem resolved.

![image](https://user-images.githubusercontent.com/54516858/66175672-1fcfcc80-e68d-11e9-97ff-742daeb9b465.png)

tested in 3 VM's

```
                "branch": "dev-0.16.0",
                "commit": "e92cb492ea28f1a1c1f73b6605613e80d731386e",
                "date": "2019-10-03T22:33:36Z",
```
