### ISSUE TITLE
[Feature] Start - Detector

### ISSUE THREAD

**Issue by PtrckM** [CoinAlpha/hummingbot#868]
Bot already started with a config running and I accidentally type start again instead of status, is it possible that hummingbot warn me instead that the bot started already or give me an option would you like to stop that bot. It will be a good new feature for hummingbot

**Suggested by / Credits:** 
Discord username: **bob.tan**

**Comment by Sirlupinwatson1** [comment]
What you mean by that ? its a scrit that make the bot start. you can end it up anytime you want.  but where are you talking about you mean the bot for the practice ?

**Comment by PtrckM** [comment]
@Sirlupinwatson1  Yes `start` will start hummingbot with a specified config but a user **bob.tan** accidentally type `start` instead of `status` and the bot started again with the same config but the bot not able to cancel the previous orders, the user wants hummingbot to warn him when he accidentally type `start` like **bot already running** or **bot already started** and I think this is the source file that you are looking for see here: https://github.com/CoinAlpha/hummingbot/blob/4941ec38b8090b8f458d19ca5ad98d667f561b4e/hummingbot/client/command/start_command.py

**Comment by Sirlupinwatson1** [comment]
@PtrckM What about we implement a rules around it. or it need a fix. if you want it to stop we should look for the command, but if automated we can just a rules ? I am not sure of what I say … lol

**Comment by Sirlupinwatson1** [comment]
@PtrckM Hi sir, I had to work a lot yesterday so I did not had time to look.  Thanks for the details you gave me, I just practice and try to understand at the same time

**Comment by PtrckM** [comment]
Feature is being added now... https://github.com/CoinAlpha/hummingbot/pull/1537

**Comment by PtrckM** [comment]
![image](https://user-images.githubusercontent.com/54516858/77130472-11d30400-6a93-11ea-986c-98d73760e74e.png)
