### ISSUE TITLE
[./Install] Install Anaconda with Python 3.7+ First Error

### ISSUE THREAD

**Issue by SaucyOfficiale** [CoinAlpha/hummingbot#89]
**Describe the bug**
./install command not working in Bash for Windows. Says Anaconda needs updated as well as Python, after already being updated.

**Steps To Reproduce**
1. type "cd hummingbot" in terminal
2. type "./install"

**Screenshots**
https://prnt.sc/ndxse4

**Release version**
0.4.0

**Comment by mifeng** [comment]
I believe you need to install Anaconda for Linux in your Bash subsystem for Windows. To do this, download the [Linux version](https://repo.anaconda.com/archive/Anaconda3-2019.03-Linux-x86_64.sh). Then, move the file into your Bash subsystem (see [this article](https://www.howtogeek.com/261383/how-to-access-your-ubuntu-bash-files-in-windows-and-your-windows-system-drive-in-bash/) on how to access your Windows files from Bash) and run it from Bash.
