### ISSUE TITLE
[BUG] Discovery report showing pairs below target profitability

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#893]
**Describe the bug**

Parameter `target_profitability` value is set to 0.01 to show trading pair combinations with profits 1% and above. Arbitrage opportunity report would still show all other combinations with less than 1% profitability.

**Steps To Reproduce**

```
primary_market: radar_relay
secondary_market: bamboo_relay
target_profitability: 0.01
target_amount: .inf
target_symbol_1: []
target_symbol_2: []
```

**Screenshots**

<img width="947" alt="putty_50c0BfnKHc" src="https://user-images.githubusercontent.com/50150287/66468683-27420c00-eab9-11e9-97c2-caef1e5982da.png">

**Release version**

"branch": "development",
"commit": "3b12050d6a845b6c05cb628b0f0d29ed876fb4aa",
"date": "2019-10-07T22:01:10Z",

**Attachments**

Log file: 
[hummingbot_logs_2019-10-09-08-15-45.log](https://github.com/CoinAlpha/hummingbot/files/3706565/hummingbot_logs_2019-10-09-08-15-45.log)

**Comment by znerol19619** [comment]
I run the configuration and got a different behavior instead. It has been ``Waiting to finish fetching traiding pair from bamboo_relay`` for 1 hr now. 
![image](https://user-images.githubusercontent.com/27669951/66553360-88cbae80-eb7d-11e9-8151-c3aae3dc6d4c.png)

**Comment by Hashira-Lars** [comment]
Retested with the latest dev  image `version-0.22.0` issue still exist.

![image](https://user-images.githubusercontent.com/55869559/71636881-f9accf00-2c71-11ea-9d87-2949239e1dc6.png)

                "branch": "development",
                "commit": "909ccf8b76544ae5f85205b7b1cfadc28aa3296b",
                "date": "2019-12-31T19:08:37Z",

**Comment by dennisocana** [comment]
Deprecated discovery strategy in version 0.26.0
