### ISSUE TITLE
[BUG] Penny jumping not placing orders at top bid/ask

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#894]
**Describe the bug**

I'm running my own bot in Huobi exchange and enabled jump orders to achieve orders with the best prices in the book. I set `jump_orders_enabled` to true with `jump_orders_depth` to 0 just like in the example in the documentation however, it's not placing top bid/ask orders.

**Steps To Reproduce**

Run a pure-mm bot with the ff. configuration:

```
maker_market: huobi
maker_market_symbol: hb10usdt
order_amount: 20.0
cancel_order_wait_time: 40.0
bid_place_threshold: 0.0025
ask_place_threshold: 0.0025
mode: single
inventory_skew_enabled: true
inventory_target_base_percent: 0.5
filled_order_replenish_wait_time: 10.0
enable_order_filled_stop_cancellation: false
jump_orders_enabled: true
jump_orders_depth: 0.0
```

**Screenshots**

<img width="947" alt="hummingbot" src="https://user-images.githubusercontent.com/50150287/66474044-1c8c7480-eac3-11e9-8117-247e5e047cd3.png">

<img width="683" alt="huobi" src="https://user-images.githubusercontent.com/50150287/66474059-21512880-eac3-11e9-8659-a3f5720884b6.png">

**Release version**

"branch": "development",
"commit": "030d95478a3730f6a721914d3ca72ce3408dabfb",
"date": "2019-10-09T00:54:10Z",

**Attachments**

Log file: 
[hummingbot_logs_2019-10-09-10-03-37.log](https://github.com/CoinAlpha/hummingbot/files/3706822/hummingbot_logs_2019-10-09-10-03-37.log)

**Comment by veecos2** [comment]
If the bid_threshold and ask_threshold is greater than the current bid ask spread, it would not place the order at the top of the bid ask. If suppose the mid price is 100, and the top bid is 98, if your threshold is 1%, instead of placing the buy order at 99, it would place at 98.01 as you are still the top bid if you do this. If your threshold is 5% it would not place at 98.01 as it would need to place at 95 and 98.01 > 95.

**Comment by dennisocana** [comment]
Hi @veecos2 , if I want my orders to be the best orders in the book I should have the highest bid and the lowest ask - is that correct?

In the screenshot above, the highest bid price is 0.4658 while the lowest ask price is 0.4660. If I want to beat those prices, my bid price should be 0.4659 and ask is 0.4659?

**Comment by veecos2** [comment]
Yes
