### ISSUE TITLE
Notification messenger for Fees estimated in history command

### ISSUE THREAD

**Issue by luisfilipeoliveira** [CoinAlpha/hummingbot#9]
## Why
The team identified that some exchanges do not include fee trade via API.

## What
Having the history command show some exchanges with fees and others without fees would be confusing, unless we make that clear.

## Definition of Done

- [ ] For performance calculations, use actual fees when available, and estimated when not available
- [ ] Include Fee Amount column in the `--verbose` **Recent Trades** table. For trades from exchanges without this data, leave it blank
- [ ] For each exchange using estimated fees, include message below **Performance** table “`Fees for [exchange] not estimated via API, assuming 0.1% maker and 0.1% taker fees.`"
- [ ] Change **Fees paid** in Performance table to **Fees**

### History command - without fees via API ❌
![image.png](https://images.zenhubusercontent.com/57179e45bf93871ccd99c501/ab88b1fb-cdca-4b71-99ba-899ad85e3651)
![image.png](https://images.zenhubusercontent.com/57179e45bf93871ccd99c501/24d5a3c6-c862-4ed5-979c-5c614047836c)

### History command - with fees via API ✅
![image.png](https://images.zenhubusercontent.com/57179e45bf93871ccd99c501/c161fc62-c672-46f3-a82c-e0c0aab5a971)![image.png](https://images.zenhubusercontent.com/57179e45bf93871ccd99c501/65a099ba-1f6b-4b16-8d2f-29149abcda15)

**Comment by dennisocana** [comment]
@luisfilipeoliveira I will repost this in Shortcut, going forward please create stories there. Let me know if you need help or guidance in doing that.
