### ISSUE TITLE
[New Exchange Connector] Coss

### ISSUE THREAD

**Issue by Aliori1** [CoinAlpha/hummingbot#910]
## Exchange Details ✏️
COSS is a cryptocurrency exchange based in Singapore. COSS promotes five factors as the main benefits of its trading platform. These five factors are transparency, instant conversion, state of the art security, integrated cash flow and “FSA”. FSA stands for the fact that 50% of all trading fees that the exchange charges goes back to the holders of the exchange’s own token, the COS-token. The trading fees for takers at COSS are 0.25%. This fee is in line with industry average. The exchange also has a great offer to makers, who don’t have to pay any trading fees at all (0.00%). But that’s not all. If your trading volume reaches a certain level, trading fees are reduced. Takers can pay as little as 0.15% and makers can get paid for trading. 
- **Name of exchange**:
Coss
- **Exchange URL**:
https://www.coss.io/
- **Link to API docs**: 
https://api.coss.io/v1/spec
- **Type of exchange**: [ ] Centralized [ ] Decentralized
Centralized
- **Requester details**: Are you affiliated with the exchange? [ ] yes [ ] no 
  - If yes, what is your role?
No just a user who is heavily invested in its idea

## Rationale / impact ✏️
(Describe your rationale for building this exchange connector, impact for hummingbot users/community)
it will bring more volume to the exchange which in turn will benefit the COSS community 
## Additional information ✏️
(Provide any other useful information that may be helpful to know about this exchange)
the exchange also has a coin called CELT. Holding CELT tokens provides users with a weekly payout in the form of a Profit split allocation. The profile comes from a liquidity bot running on coss.io. And the profits get distributed to CELT token holders On a weekly basis
---
⚠️ ***Note: do not modify below here***

## Developer notes

This feature request entails building a new exchange connector to allow Hummingbot to connect to an exchange that is currently not supported.

### Resources
- [Exchange connector developer guide](https://docs.hummingbot.io/developers/connectors/)
- [Discord forum](https://discord.hummingbot.io)

### Deliverables
1. A complete set of exchange connector files as listed [above](#developer-notes-resources).
2. Unit tests (see [existing unit tests](https://github.com/CoinAlpha/hummingbot/tree/master/test/integration)):
  1. Exchange market test ([example](https://github.com/CoinAlpha/hummingbot/blob/master/test/integration/test_binance_market.py))
  2. Order book tracker ([example](https://github.com/CoinAlpha/hummingbot/blob/master/test/integration/test_binance_order_book_tracker.py))
  3. User stream tracker ([example](https://github.com/CoinAlpha/hummingbot/blob/master/test/integration/test_binance_user_stream_tracker.py))
3. Documentation:
  1. Code commenting (particularly for any code that is materially different from the templates/examples)
  2. Any specific instructions for the use of that exchange connector ([example](https://docs.hummingbot.io/connectors/binance/))

### Required skills
- Python
- Previous Cython experience is a plus (optional)

**Comment by dennisocana** [comment]
Please refer to this article on how connectors are integrated into Hummingbot
https://hummingbot.zendesk.com/hc/en-us/articles/900004506986-How-connectors-are-integrated-into-Hummingbot
