### ISSUE TITLE
[BUG] Bamboo Relay showing 0 available balance

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#912]
**Describe the bug**

I reached out to Joshua regarding this and posting a GitHub issue for tracking. Hummingbot cannot place orders probably due to balance showing 0 available. It's working fine in the previous versions, bug happened after the latest release v0.16.0

This is the only unusual thing I have in the logs.

```
2019-10-14 05:01:13,443 - root - ERROR - Unhandled error in background task: type object 'BambooRelayAPIOrderBookDataSource' has no attribute '_api_prefix'
Traceback (most recent call last):
  File "/hummingbot/core/utils/async_utils.py", line 8, in safe_wrapper
    return await c
  File "/hummingbot/market/bamboo_relay/bamboo_relay_order_book_tracker.py", line 127, in _order_book_diff_router
    address_token_map: Dict[str, any] = await self._data_source.get_all_token_info()
  File "/hummingbot/market/bamboo_relay/bamboo_relay_api_order_book_data_source.py", line 80, in get_all_token_info
    async with client.get(f"{REST_BASE_URL}{cls._api_prefix}/tokens?perPage=1000") as response:
AttributeError: type object 'BambooRelayAPIOrderBookDataSource' has no attribute '_api_prefix'
```

**Steps To Reproduce**

Run a cross-exchange market making bot in Bamboo Relay (maker).

**Screenshots**

<img width="947" alt="putty_8q9VJcV1yM" src="https://user-images.githubusercontent.com/50150287/66730516-e9f8c800-ee84-11e9-9871-f627be96e434.png">

**Release version**

```
"branch": "development",
"commit": "99f45919e141296ea0e059cf933068dc34b83fca",
"date": "2019-10-11T03:01:46Z",
```

**Attachments**

Log file:
[hummingbot_logs_2019-10-14-05-01-00.log](https://github.com/CoinAlpha/hummingbot/files/3723041/hummingbot_logs_2019-10-14-05-01-00.log)

**Comment by Arctek** [comment]
See: https://github.com/CoinAlpha/hummingbot/pull/913

**Comment by dennisocana** [comment]
Confirmed working. Fixed by https://github.com/CoinAlpha/hummingbot/pull/913.
