### ISSUE TITLE
[BUG] code bug in ddex_market.pyx

### ISSUE THREAD

**Issue by zhiji666** [CoinAlpha/hummingbot#923]
Thanks for your incredible job. I found a code bug in ddex_market.pyx when I used.

In func cancel_order(), when canceled order successfully, available_amount_base and pending_amount_base are going to be zero according to following codes:

    ===========
    order.available_amount_base = s_decimal_0
    order.pending_amount_base = s_decimal_0
    ===========

This will affect the logic in following codes in func _update_order_status():

    ===========
    previous_is_done = tracked_order.is_done
    tracked_order.last_state = order_update["status"]
    tracked_order.executed_amount_base = Decimal(order_update["confirmedAmount"])
    tracked_order.available_amount_base = Decimal(order_update["availableAmount"])
    tracked_order.pending_amount_base = Decimal(order_update["pendingAmount"])
    tracked_order.executed_amount_quote = tracked_order.executed_amount_base * Decimal(order_update["price"])
    tracked_order.gas_fee_amount = Decimal(order_update["gasFeeAmount"])
    if not previous_is_done and tracked_order.is_done:
    ===========

Because available_amount_base and pending_amount_base are already zero, previous_is_done is True(it's expected to be False). And tracked_order.is_done is True all the time, the codes after the condition(the last line) will never be accessed.

**Comment by chowryan** [comment]
thanks for catching this!

**Comment by moraliang** [comment]
@zhiji666 Hello, you are qualified for 0.1ETH bug bounty, let me know your ETH address.

**Comment by zhiji666** [comment]
@moraliang Thanks, my eth address is 0x21a0063d36411A11b806e5ED63FBc0631B459245.
