### ISSUE TITLE
[BUG] Arbitrage Price is wrong and profitability math is wrong

### ISSUE THREAD

**Issue by KirkBallou** [CoinAlpha/hummingbot#93]
**Describe the bug**
The profit margin shown is wrong and price data is actually wrong. 

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):
1. Checking live price on Binance via Trading view BAT-ETH 0.00217444
2. Actual price on Radar Relay for BAT-WETH 0.0021578
3. Screen shot below shows bot prices and math do not match up. Radar relay isn't even in the same bid/ask range.
4. Real profit would of been:  % .007 taking ask bid
     Bot based on #'s it was grabbing %.001 (if you do the math on the screenshot below)
     Odd # bot came up with is negative
...

**Screenshots**
Binance actual price 
![image](https://user-images.githubusercontent.com/346184/56448623-326c6a00-62d6-11e9-8ffa-1d5337dba860.png)
Radar Relay actual price
![image](https://user-images.githubusercontent.com/346184/56448796-1e296c80-62d8-11e9-9f6f-72f2cc4a153a.png)
Humming bot 
![image](https://user-images.githubusercontent.com/346184/56448629-3dbf9580-62d6-11e9-94e1-615733ab251c.png)

**Release version**
0.4.0

**Comment by mifeng** [comment]
I don't think these are bugs:

## Price
Hummingbot lists the bid ask spread (the highest bid and the lowest ask price). The price in that UI component on Radar Relay is different from the highest bid and the lowest ask price. See example below for the WETH/DAI pair:
<img width="710" alt="Screen Shot 2019-04-19 at 5 32 25 PM" src="https://user-images.githubusercontent.com/1795030/56449004-3fcf2780-62c9-11e9-9bd5-7818380bb7bf.png">

## Profitability
In the arbitrage strategy, you buy at the lowest ask price in one market and selling at the highest bid price in another market. Based on the Hummingbot screenshot above, the two possible trades are:
1. Buy BAT at 0.00217445 on Binance + Sell BAT at 0.002160045 on Radar
2. Buy BAT at 0.0021719 on Radar + Sell BAT at 0.0021623 on Binance

The profitability calculation is (Sell price / Buy price) - 1, so profitability equal:
1. 0.002160045 / 0.00217445 - 1 = -0.66%
2. 0.0021623 / 0.0021719 - 1 = -0.44%

Max profitability = max(1, 2) = -0.44%
