### ISSUE TITLE
[BUG] Sept trades for Harmony One bounty were not calculated

### ISSUE THREAD

**Issue by rennel-tabing** [CoinAlpha/hummingbot#930]
**Describe the bug**
// A clear and concise description of what the bug is.
 September trades weren't calculated correctly, for some reason it drops off at 13th and did not update ever since.

This issue is related to https://github.com/CoinAlpha/hummingbot/issues/918

Please provide an update once available so I can reach out to the user and provide its status.

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:
He was running an older version f the bot and he just noticed that his bounty performance were not recorded half way through the month of September.

..

**Screenshots**

![image](https://user-images.githubusercontent.com/53868268/67004543-8b169700-f0ae-11e9-8937-a5696bee7df6.png)

Logs shows that are orders that were filled Sept 16th
![image](https://user-images.githubusercontent.com/53868268/67004566-98338600-f0ae-11e9-8322-37d5f8a0e064.png)

**Release version**
// Include your bot's version number (Can be found at the bottom left corner of your CLI).
Hummingbot version 0.14.0 , please note that I did not recommend updating his hummingbot as it may delete the filled orders on his local database 

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

Log file can be found on this link 
https://mega.nz/#!bc1GxQ5T!18OjBM9AIj0m_Ni2PM-PnNEYicTEVK2R4panIYyE2Js

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:** Oldman_Sam
**Optional: your ETH address:** 0x29aCf3A964ca6fb9971d7cBe422C35c023f4a03f

**Comment by yzhang1994** [comment]
@rennel-tabing this issue is related to #918 and should be fixed on the dev branch. The fix will be included in the next release. 

If the user wants to recover his lost trades, he will have to share his read-only Binance API keys.

**Comment by rennel-tabing** [comment]
Hi @yzhang1994 I have sent you the Binance API keys as requested.

**Comment by Oldman-Sam** [comment]
Any update on this?

**Comment by rennel-tabing** [comment]
This has been resolved
