### ISSUE TITLE
File Too Short

### ISSUE THREAD

**Issue by SaucyOfficiale** [CoinAlpha/hummingbot#94]
Describe the bug
Getting error "file too short" import error after command "bin/hummingbot.py". Linux running in Virtual Box on Windows. Anaconda is fully installed, ./install and ./compile commands done with 0 errors, and "conda activate hummingbot" done with 0 errors.

Steps To Reproduce
type "bin/hummingbot.py" in terminal

Screenshots
https://prnt.sc/nerriw

Release version
0.4.0

**Comment by martinkou** [comment]
This likely means some compiled files were corrupted for some reason - there may have been a compile error when that file was generated.

Try removing all the `.cpp` and `.so` files generated from `.pyx` files and compile again.

```
for fname in $(find . -name "*.pyx"); do 
  rm -f $(echo $fname | sed s/pyx$/cpp/g) $(echo $fname | sed s/pyx$/so/g)
done
```

**Comment by SaucyOfficiale** [comment]
File permissions just needed changed. The command: "chmod -R 777 ./" when in my home directory in linux worked great. Now it compiles.

**Comment by mifeng** [comment]
I have sent you 0.1 ETH as part of our Bug Bounty program: https://docs.hummingbot.io/support/bug-bounty-program/
