### ISSUE TITLE
[BUG] Cannot read existing conf files in local directory

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#940]
**Describe the bug**

Docker container with the latest development image cannot read the files in the `conf` directory, causing problems trying to import existing configuration files. It's like Hummingbot's files are mapped to a location that doesn't exist in the machine.

Make sure to update to the latest development branch.

```
"branch": "development",
"commit": "9b5662bb5dcbf0ef674b9542964ae17ea188fe80",
"date": "2019-10-18T19:25:47Z",
```

Output of `docker inspect dev-test-2`
[docker_inspect_dev-test-2.txt](https://github.com/CoinAlpha/hummingbot/files/3746074/docker_inspect_dev-test-2.txt)

## Test 1

Create a new dev instance. In this case, the instance is named `dev-test-1`.

<img width="947" alt="putty_piRF5KZWyK" src="https://user-images.githubusercontent.com/50150287/67135466-a0c1c300-f24c-11e9-8cb1-f67ab1f3f205.png">

The created directories are empty, whereas before `hummingbot_conf` should have `conf_global.yml`, `conf_liquidity_bounty.yml`, `hummingbot_logs.yml` by default.

<img width="479" alt="56pXjTgtBb" src="https://user-images.githubusercontent.com/50150287/67135511-01510000-f24d-11e9-835e-d969462803de.png">

<img width="415" alt="putty_7YM5tE9Rxk" src="https://user-images.githubusercontent.com/50150287/67135519-19c11a80-f24d-11e9-9df8-913f626c91d5.png">

Create a new pure-mm config file and complete the walkthrough.

<img width="947" alt="putty_Yykn1IjO9U" src="https://user-images.githubusercontent.com/50150287/67135528-407f5100-f24d-11e9-9bc7-f4a8571a7ccf.png">

Exit from Hummingbot and confirm the created file/s are still not in the directory.

<img width="792" alt="weXfPH0WCq" src="https://user-images.githubusercontent.com/50150287/67135586-df0bb200-f24d-11e9-97f0-49cb5654d4c4.png">

Restart docker container `dev-test-1` and attempt to import the previously created file. 

<img width="947" alt="putty_jt97Y06Y7R" src="https://user-images.githubusercontent.com/50150287/67135615-1ed29980-f24e-11e9-9464-50eb285e7b82.png">

Hummingbot will actually recognize that the file/s are there but it only stays with the docker image. 

## Test 2

Create a new docker instance `dev-test-2` and copy existing config files to the conf directory.

<img width="947" alt="putty_BKIgLj5xg8" src="https://user-images.githubusercontent.com/50150287/67135672-a3251c80-f24e-11e9-9f22-83a52877d5ab.png">

Confirm that the files are there. However, Hummingbot can't read them.

<img width="947" alt="putty_Fe8ENePEZG" src="https://user-images.githubusercontent.com/50150287/67135675-a9b39400-f24e-11e9-825f-45163df44e2a.png">

## Test 3

It would only work when the container is configured with trading strategy autostart.

```
docker run -it \
--name dev-test-2 \
-e STRATEGY=pure_market_making \
-e CONFIG_FILE_NAME=conf_pmm_zrx-weth.yml \
-e WALLET=**DELETED**\
-e WALLET_PASSWORD=**DELETED** \
--mount "type=bind,source=$(pwd)/dev-test-2_files/hummingbot_conf,destination=/conf/" \
--mount "type=bind,source=$(pwd)/dev-test-2_files/hummingbot_logs,destination=/logs/" \
coinalpha/hummingbot:development
```

<img width="947" alt="putty_Osn5aoZBbs" src="https://user-images.githubusercontent.com/50150287/67135760-cdc3a500-f24f-11e9-9edc-0a31a049ea02.png">

**Comment by PtrckM** [comment]
mounts are correct still can't read conf files

```
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/home/patrick/hummingbot-instance-dev_files/hummingbot_conf",
                "Destination": "/conf",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/home/patrick/hummingbot-instance-dev_files/hummingbot_logs",
                "Destination": "/logs",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
```

**Comment by BUDDHA-TONY** [comment]
Tested "Test 1" and had the same output. 
     "branch": "development",
                "commit": "9b5662bb5dcbf0ef674b9542964ae17ea188fe80",
                "date": "2019-10-18T19:25:47Z",


![ls](https://user-images.githubusercontent.com/55869559/67140196-b0f89300-f28a-11e9-97d4-74c08dab610a.png)

![conf](https://user-images.githubusercontent.com/55869559/67140197-b655dd80-f28a-11e9-87df-368a44b39e58.png)

![ls1](https://user-images.githubusercontent.com/55869559/67140198-b9e96480-f28a-11e9-9769-a24ef8bd9c65.png)

![pmm](https://user-images.githubusercontent.com/55869559/67140362-56f8cd00-f28c-11e9-8ace-c3ce627b8fce.png)

![final1](https://user-images.githubusercontent.com/55869559/67140379-72fc6e80-f28c-11e9-9ecc-47a143cffe2c.png)

![final](https://user-images.githubusercontent.com/55869559/67140383-7abc1300-f28c-11e9-8f82-15195c156c3d.png)

**Comment by PtrckM** [comment]
confirmed working on
```
                "branch": "0.17.1",
                "commit": "14d85d18d3bd5909447c95f8b332562f810ee38d",
                "date": "2019-10-23T00:24:15Z",
```
```
                "branch": "dev-0.18.0",
                "commit": "e278c9d2b3ae10c5e60b1406a2b961fecdf74eb8",
                "date": "2019-10-23T01:01:03Z",
````

![image](https://user-images.githubusercontent.com/54516858/67351169-5ce9f900-f57f-11e9-88a4-9f3dab5a17ff.png)
