### ISSUE TITLE
[BUG] No orders being created in Radar Relay for Pure MM due to absence of available balance feature

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/hummingbot#942]
**Describe the bug**

No orders are being created in Radar Relay with any configuration. Tried default configs with order_amount > minimum order size in single mode.

**Steps To Reproduce**

Run a normal pure-mm bot in Radar Relay.

```
maker_market: radar_relay
maker_market_symbol: ZRX-WETH
order_amount: 10.0
cancel_order_wait_time: 60.0
bid_place_threshold: 0.01
ask_place_threshold: 0.01
inventory_skew_enabled: true
inventory_target_base_percent: 0.5
filled_order_replenish_wait_time: 10.0
enable_order_filled_stop_cancellation: false
jump_orders_enabled: false
jump_orders_depth: 0.0
```

**Screenshots**

<img width="947" alt="putty_9PMOAuqH81" src="https://user-images.githubusercontent.com/50150287/67136712-e090a680-f25c-11e9-8b1c-99217de66b65.png">

**Release version**

```
"branch": "development",
"commit": "9b5662bb5dcbf0ef674b9542964ae17ea188fe80",
"date": "2019-10-18T19:25:47Z",
```

**Attachments**

Log file: 
[radar_zrx-weth_single.log](https://github.com/CoinAlpha/hummingbot/files/3746134/radar_zrx-weth_single.log)

**Comment by dennisocana** [comment]
@veecos2 if the cause is absence available balance feature, this might help https://github.com/CoinAlpha/hummingbot/issues/912. Joshua mentioned in the fix PR that this might also happen in Radar Relay.

**Comment by veecos2** [comment]
@dennisocana : That implementation needs to be corrected. I have messaged Joshua about the same. This should fix the issue. Feel free to reopen if not.
