### ISSUE TITLE
[BUG] Start Stop Telegram Bot 

### ISSUE THREAD

**Issue by Oldman-Sam** [CoinAlpha/hummingbot#951]
**Describe the bug**
I had an issue where it seems like my bot just stopped by itself. I believe it has to do with the Telegram bot command stop and start.

**Steps To Reproduce**
 I used the stop command and then the start command in Telegram. About a day or so later I noticed that my history command stopped working (it was working after I sent those commands). It seems that my session stopped after and I had to start it back up again, I never had this issue before and I never used the start and stop from my telegram before either. 

Here are the steps to reproduce the issue (see attachments in the section below):
This is V16 using puremarket strategy connecting to binance.

**Screenshots**
// If applicable, add screenshots to help explain your problem.

**Release version**
// Include your bot's version number (Can be found at the bottom left corner of your CLI).

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**
**Optional: your ETH address: 0x29aCf3A964ca6fb9971d7cBe422C35c023f4a03f

**Comment by rennel-tabing** [comment]
@Oldman-Sam Kindly include/attach your log file located under the `hummingbot_log` folder

**Comment by Oldman-Sam** [comment]
Ah sorry about that, I didn't think about that. Here you go. 
[hummingbot_logs_2019-10-11-14-45-39.log](https://github.com/CoinAlpha/hummingbot/files/3752358/hummingbot_logs_2019-10-11-14-45-39.log)

**Comment by rennel-tabing** [comment]
The range of the log that was from the date of Oct. 11 to Oct. 21. Kindly provide the estimated timestamp as to when you have to  start the bot manually after the bot stops on its own.

**Comment by Oldman-Sam** [comment]
Probably between the 17th - 21st is where things go wrong. The bot never gave any shutdown messages during this time.

**Comment by Oldman-Sam** [comment]
I'm not sure useful it is but here is a screen cap from my telegram. 
![image](https://user-images.githubusercontent.com/52423431/67400156-3f1a9500-f57b-11e9-989e-10e4d96f1dd4.png)

**Comment by rennel-tabing** [comment]
By looking on the logs, I do not think that this issue is related to the telegram. The issue happened at 2019-10-21 01:51:25 and from her on out, the bot stops generating orders. then at around 01:54:27 the logs stops generating. Let us know if you will encounter the same issue after you had updated your hummingbot version.

**Comment by Oldman-Sam** [comment]
I downgraded from 17 to 16 because 17 has a bug with the config files. I'll try 17 at a later date and see if the bug occurs again.

**Comment by PtrckM** [comment]
you can upgrade to 0.17.1 hot fix release from the bug https://github.com/CoinAlpha/hummingbot/issues/940

**Comment by Oldman-Sam** [comment]
Will do!

**Comment by Oldman-Sam** [comment]
[logs_conf_pure_market_making_strategy_0.log](https://github.com/CoinAlpha/hummingbot/files/3790083/logs_conf_pure_market_making_strategy_0.log)

I updated but came across the same error.

**Comment by Oldman-Sam** [comment]
`2019-10-30 17:03:34,535 - 10 - hummingbot.client.hummingbot_application - ERROR - This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.ProgrammingError) SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 139730695997184 and this is thread id 139731772147072.
[SQL: INSERT INTO "Order" (id, config_file_path, strategy, market, symbol, base_asset, quote_asset, creation_timestamp, order_type, amount, price, last_status, last_update_timestamp) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: [{'base_asset': 'ONE', 'config_file_path': 'conf_pure_market_making_strategy_0.yml', 'strategy': 'pure_market_making', 'creation_timestamp': 1572361756384, 'quote_asset': 'BTC', 'amount': 1200.0, 'price': 5.7e-07, 'id': 'buy-ONEBTC-1572361756001190', 'symbol': 'ONEBTC', 'order_type': 'LIMIT', 'last_status': 'BuyOrderCreated', 'market': 'binance', 'last_update_timestamp': 1572361756384}]]
(Background on this error at: http://sqlalche.me/e/f405)
`

This appears to be the error message I get when I try to run history now. I'm using 17.1

**Comment by znerol19619** [comment]
encountered a user having the same problem [newcryptodev]. 

User getting an error message ``Error running performance analysis`` after running history command in telegram 

**Version**
ver-0.17.1
ver-0.18.1

**Comment by PtrckM** [comment]
a fix for `history` problem `Error running performance analysis` https://github.com/CoinAlpha/hummingbot/pull/1072

**Comment by PtrckM** [comment]
confirmed fix for problem `Error running performance analysis` update to version 0.19.0

**Comment by yzhang1994** [comment]
This is likely fixed by https://github.com/CoinAlpha/hummingbot/pull/1072
