### ISSUE TITLE
get_wallet -e and get_wallet c does not work

### ISSUE THREAD

**Issue by zbanga** [CoinAlpha/hummingbot#96]
**Describe the bug**
'get_wallet -e' and 'get_wallet -c does not show balance or currency
Says -e/--exchange: expects one argument 
When typed in 
"get_balance -e/--exchange" it says the exchange has not been initialised. 
I tried just the get_balance -e it says it expects one argument. 
get_balance -w works 
**Steps To Reproduce**

Here are the steps to reproduce the issue (see attachments in the section below):
1. Configure Binance for USDT/ETH through the Configuration when first statted
2. Edit Config file for API KEY and secret
3. Start bot
4. Ask for the get_wallet throws error about exchange not being initialised 
5. Look up status and bot seems to be running with no orders

**Screenshots**
Binance get_ balance
<img width="508" alt="Screen Shot 2019-04-22 at 9 29 09 pm" src="https://user-images.githubusercontent.com/12522897/56498579-b11b0e80-6545-11e9-8ff2-0fc67120e3a8.png">
status
<img width="519" alt="Screen Shot 2019-04-22 at 9 30 54 pm" src="https://user-images.githubusercontent.com/12522897/56498627-ede70580-6545-11e9-90c9-a12cd3dbd4c8.png">

**Release version**
Version 0.4.0

**Comment by martinkou** [comment]
@yzhang1994 please take a look

**Comment by yzhang1994** [comment]
@zbanga The `-e` or `--exchange` takes one argument. 
You should be able to enter command `get_balance -e binance` instead and the correct balances

**Comment by zbanga** [comment]
@yzhang1994 can confirm the -e and --exchange works as intended. 
Maybe the help should be updated so its clearer? :) 
However, I still cannot get the -c --currency to work

**Comment by yzhang1994** [comment]
@zbanga You'd have to specify the exchange / wallet you would like to read the balance from and also the name of the currency. Please try 
`get_balance -e binance -c <CURRENCY such as ETH>` 
or 
`get_balance -w -c <CURRENCY such as ETH>`
Let me know if this works. We can change our docs to make this part clearer.

**Comment by zbanga** [comment]
<img width="440" alt="Screen Shot 2019-04-24 at 5 18 16 pm" src="https://user-images.githubusercontent.com/12522897/56639853-f6118300-66b4-11e9-8f4c-065d3778040c.png">
@yzhang1994  Getting error for both commands. The top error is for the top command and the bottom error is for the bottom command 

Do I need to do anything else?

**Comment by yzhang1994** [comment]
@zbanga Hey I believe that is a bug and just fixed it! Thanks for finding it.

**Comment by mifeng** [comment]
@zbanga Thanks for reporting this bug. This is eligible for our bug bounty program (https://docs.hummingbot.io/support/bug-bounty-program/). Please send me your ETH address either here, on Discord, or mike@coinalpha.com, and I will send you 0.1 ETH.
