### ISSUE TITLE
[BUG] Error running performance analysis while in paper trade arbitrage strategy

### ISSUE THREAD

**Issue by pikobese** [CoinAlpha/hummingbot#974]
**Describe the bug**

It's been several times that I try to run the "history" command while in a paper trade arbitrage strategy on binance. On 0.16.0 it worked fine but now I only get the past trades and then it's written "error running performance analysis". It's not showing the usual deltas and ongoing profit/deficit % of the overall balance.

**Steps To Reproduce**
commands in Hummingbot interface (paper trade mode ON) : 
`config`
`arbitrage`
`import`
`conf_arbitrage_strategy_3.yml` (see attachement)
`start`

You need to wait for trades to be done (if no trades have been done, the performance analysis in `history` is showing correctly with Delta and profit at 0.00% and 0.0 TUSD).

Then, when some trades are in : 
`history`
and it shows this :

![Capture2](https://user-images.githubusercontent.com/40965729/67484544-99455400-f668-11e9-8165-044183195985.PNG)

**Release version**
0.17.1

**Attachments**
[logs_conf_arbitrage_strategy_3.log](https://github.com/CoinAlpha/hummingbot/files/3767415/logs_conf_arbitrage_strategy_3.log)
[conf_arbitrage_strategy_3.txt](https://github.com/CoinAlpha/hummingbot/files/3767435/conf_arbitrage_strategy_3.txt) (it seems that .yml files are not supported so here's a .txt)

discord username : @pikobèse
ETH address : 0x5a83935ceACB7b538bad1fc57DcD0cC3ce8dA9cE

**Comment by rennel-tabing** [comment]
I am able to reproduce this behavior on version-0.17.1

**Comment by BUDDHA-TONY** [comment]
Tested it and had the same result 

![gitARB](https://user-images.githubusercontent.com/55869559/67526178-d94b1c00-f6e6-11e9-98bc-34b576e70d63.png)

**Comment by znerol19619** [comment]
I tested on both 0.17.1 & 0.18.0 and got the same behavior. I tried other strategy with paper trade mode on, and didn't get any error.

```
2019-10-25 10:56:25,992 - 11 - hummingbot.client.hummingbot_application - ERROR - Unexpected error running performance analysis.
Traceback (most recent call last):
  File "/hummingbot/client/command/history_command.py", line 161, in trade_performance_report
    self.market_trading_pair_tuples
  File "/hummingbot/client/performance_analysis.py", line 206, in calculate_trade_performance
    market_trading_pair_tuples)
  File "/hummingbot/client/performance_analysis.py", line 174, in calculate_asset_delta_from_trades
    asset_stats[base_asset]["spent"] += base_delta
KeyError: 'USDC'
```

**Comment by BUDDHA-TONY** [comment]
re-tested this for more accurate output and reproduced the behavior on XEMM v0.18.0

```
########################################################
###   Cross exchange market making strategy config   ###
########################################################

template_version: 1

# The following configuations are only required for the
# cross exchange market making strategy

# Exchange and token parameters
maker_market: binance
taker_market: coinbase_pro
maker_market_symbol: EOSUSDT
taker_market_symbol: EOS-USD

# Minimum profitability target required to place an order
# Expressed in decimals: 0.01 = 1% target profit
min_profitability: 1e-05

# Maximum order size in terms of base currency
order_amount: 100.0

# Have Hummingbot actively adjust/cancel orders if necessary.
# If set to true, outstanding orders are adjusted if
# profitability falls below min_profitability.
# If set to false, outstanding orders are adjusted if
# profitability falls below cancel_order_threshold.
active_order_canceling: true

# If active_order_canceling = false, this is the profitability/
# loss threshold at which to cancel the order.
# Expressed in decimals: 0.01 = 1% target profit
cancel_order_threshold: 0.05

# An amount in seconds, which is the minimum duration for any
# placed limit orders. Default value = 130 seconds.
limit_order_min_expiration: 130.0

# If enabled (parameter set to `True`), the strategy will place the order on top of the top bid and ask,
# if its more profitable to place it there
adjust_order_enabled: true

# An amount expressed in base currency which is used for getting the top bid and ask,
# ignoring dust orders on top of the order book
top_depth_tolerance: 0.0

# An amount in seconds, which is the minimum amount of time interval between adjusting limit order prices
anti_hysteresis_duration: 60.0

# An amount expressed in decimals (i.e. input of `0.01` corresponds to 1%), which is the maximum size limit of new limit orders,
# in terms of ratio of hedge-able volume on taker side.
order_size_taker_volume_factor: 0.25

# An amount expressed in decimals (i.e. input of `0.01` corresponds to 1%), which is the maximum size limit of new limit orders,
# in terms of ratio of asset balance available for hedging trade on taker side
order_size_taker_balance_factor: 0.995

# An amount expressed in decimals (i.e. input of `0.01` corresponds to 1%), which is the maximum size limit of new limit orders,
# in terms of ratio of total portfolio value on both maker and taker markets
order_size_portfolio_ratio_limit: 0.1667

# For more detailed information, see:
# https://docs.hummingbot.io/strategies/cross-exchange-market-making/#configuration-parameters
```
![git974](https://user-images.githubusercontent.com/55869559/67739210-ae492b00-fa4c-11e9-8754-a207e72ef8d8.png)

**Comment by PtrckM** [comment]
tested both arb and xemm on dev-0.18.0 `Error running performance analysis`

```
                "branch": "development",
                "commit": "12cb7513b9df2dfaa4294e4e0a8e9606f81661da",
                "date": "2019-10-29T04:03:01Z",
```

**Comment by znerol19619** [comment]
Rerun on dev-0.18.0, performance analysis is showing correctly now after trades are executed.

![image](https://user-images.githubusercontent.com/27669951/67834945-af00c080-fb23-11e9-9758-daee90493a7d.png)

**Release version**

```
                "branch": "development",
                "commit": "6cd74036cd23918a5af0aee0f5e522b23fc5eb34",
                "date": "2019-10-30T03:02:03Z",

```

**Comment by dennisocana** [comment]
Confirmed fix by https://github.com/CoinAlpha/hummingbot/pull/1003
