### ISSUE TITLE
[BUG] Orders stacking up in Coinbase Pro

### ISSUE THREAD

**Issue by PtrckM** [CoinAlpha/hummingbot#981]
**Describe the bug**
It's in single mode but it created and left multiple open orders in the exchange one after the other.

**Screenshots**
![image](https://user-images.githubusercontent.com/54516858/67542562-ed5f3f80-f71f-11e9-8be0-32a94dccf04a.png)
![image](https://user-images.githubusercontent.com/54516858/67542571-f7813e00-f71f-11e9-921c-5cdcd100e465.png)
![image](https://user-images.githubusercontent.com/54516858/67542577-fcde8880-f71f-11e9-83ec-df948caa7c9a.png)

**Release version**
```
                "branch": "0.17.1",
                "commit": "14d85d18d3bd5909447c95f8b332562f810ee38d",
                "date": "2019-10-23T00:24:15Z",
```

**Attachments**
conf 
[conf_pmm.txt](https://github.com/CoinAlpha/hummingbot/files/3770327/conf_pmm.txt)

logs 
[logs_pmm.log](https://github.com/CoinAlpha/hummingbot/files/3770328/logs_pmm.log)

**Comment by dennisocana** [comment]
Same behavior when making orders with cross-exchange strategy.

**Comment by veecos2** [comment]
@dennisocana : Can you recheck if this issue still exists ?.

**Comment by dennisocana** [comment]
@veecos2 : This specific bug no longer occurs but I found another issue which I will post separately.
