### ISSUE TITLE
[BUG] Unable to start discovery with binance - coinbase

### ISSUE THREAD

**Issue by PtrckM** [CoinAlpha/hummingbot#988]
**Describe the bug**
Unable to start discovery strategy with binance - coinbase_pro
```
ValueError: Error parsing symbol BUSDNGN: 'NoneType' object has no attribute 'group'
```
**Screenshots**
![image](https://user-images.githubusercontent.com/54516858/67612829-27d8e300-f7d9-11e9-9475-4c0554f70426.png)

**Release version**
```
                "branch": "dev-0.18.0",
                "commit": "923eb4d20cf03638d498428eee6d4cdf6bdd06ce",
                "date": "2019-10-26T00:09:24Z",
```

**Attachments**
CONF 
[discovery_binance-coinbase_dev-0-18-0_conf.txt](https://github.com/CoinAlpha/hummingbot/files/3774339/discovery_binance-coinbase_dev-0-18-0_conf.txt)
LOGS 
[discovery_binance-coinbase_dev-0-18-0.txt](https://github.com/CoinAlpha/hummingbot/files/3774340/discovery_binance-coinbase_dev-0-18-0.txt)

**Comment by chowryan** [comment]
binance added a new pair which breaks discovery. ill work on this on monday

**Comment by einjhelclint13** [comment]
Re-run configuration on development version 0.18.0, confirm that error is no longer showing.
![Bug 988 Test](https://user-images.githubusercontent.com/57189990/67887791-ea80a680-fb86-11e9-93ae-3012ce552432.PNG)

**Release version**

                "branch": "dev-0.18.0",
                "commit": "7a43ffad4c02f47be800ff55f1d153e26a2bd3a",
                "date": "22019-10-30T05:46:39Z"

**Comment by PtrckM** [comment]
confirmed fix

![image](https://user-images.githubusercontent.com/54516858/67910662-92fe2d00-fbbe-11e9-9382-826679fb4a55.png)

```
                "branch": "dev-0.18.0",
                "commit": "c526ee5217b3c8079ecd526d9641b46e2f0e3a82",
                "date": "2019-10-31T00:17:06Z",
```
