### ISSUE TITLE
[BUG]`list configs` Shows Duplicate order_size_taker_balance_factor in the Interface(XEMM)

### ISSUE THREAD

**Issue by BUDDHA-TONY** [CoinAlpha/hummingbot#989]
----XEMM----version-0.17.1

`list configs` Shows Duplicate `order_size_taker_balance_factor` in the Interface,that should be `order_size_portfolio_ratio_limit`.Despite showing duplicate `order_size_taker_balance_factor` in the Interface when you view the conf_strategy_file it still shows `order_size_portfolio_ratio_limit`

1.create new strategy file
2.completed initial configuration 
3.enter `list configs`
4.check the new strategy file in your files
5.verify if you have duplicate order_size_take_balance_factor

create new
![2](https://user-images.githubusercontent.com/55869559/67616157-f6c3d700-f807-11e9-8964-6b2e9688e6b3.png)
enter `list configs` command
![3](https://user-images.githubusercontent.com/55869559/67616159-fcb9b800-f807-11e9-9080-51f336c97bf7.png)
verify if the file has duplicate order_size_taker_balance
![5](https://user-images.githubusercontent.com/55869559/67616164-080ce380-f808-11e9-9e0d-6e18476b19e9.png)

**Comment by znerol19619** [comment]
I tried running XEMM on 0.17.1 and got the same behavior. Duplicate ``order_size_take_balance_factor``

![Screenshot from 2019-10-27 22-26-58](https://user-images.githubusercontent.com/27669951/67636195-1989e480-f909-11e9-8e99-498a27e847d6.png)

**Comment by PtrckM** [comment]
![image](https://user-images.githubusercontent.com/54516858/67650621-b041ba00-f978-11e9-809e-8fff3b04148f.png)
![image](https://user-images.githubusercontent.com/54516858/67650628-ba63b880-f978-11e9-92dd-24b77f091c48.png)

Tested on development
```
                "branch": "dev-0.18.0",
                "commit": "923eb4d20cf03638d498428eee6d4cdf6bdd06ce",
                "date": "2019-10-26T00:09:24Z",
```

**Comment by dennisocana** [comment]
Fix in pull request https://github.com/CoinAlpha/hummingbot/pull/997

**Comment by BUDDHA-TONY** [comment]
tested before closing and was successful the interface now is not showing duplicate `order_size_taker_balance_factor`

![git989](https://user-images.githubusercontent.com/55869559/67734633-82be4480-fa3c-11e9-8d20-098871566912.png)
